# -*- coding: utf-8 -*-
"""Iliad characters and relationships, Chinese and English.
cat: god / demi (child of a god and a mortal) / mortal
camp: ach (Greek side) / troy (Trojan side) / neutral
dies: book in which the character is killed within the poem, or None
"""

N = lambda **k: k

NODES = [
  # ------------------------------------------------------------------ gods
  N(id="zeus", zh="宙斯", gr="Ζεύς", en="Zeus", cat="god", camp="neutral", dies=None,
    sub=("众神之王", "King of the gods"),
    bio=("众神之王。他应忒提斯之请，让特洛伊人暂占上风，好让希腊人尝到冷落阿喀琉斯的代价；又用金天平称量赫克托尔与阿喀琉斯的命运。最后他派赫尔墨斯护送普里阿摩斯去赎回赫克托尔的遗体。",
         "King of the gods. At Thetis's request he lets the Trojans gain the upper hand so the Greeks feel the cost of slighting Achilles; later he weighs the fates of Hector and Achilles on golden scales. At the end he sends Hermes to guide Priam to ransom Hector's body."),
    icon=("长须、月桂冠与霹雳。", "Long beard, laurel wreath and thunderbolt.")),
  N(id="hera", zh="赫拉", gr="Ἥρα", en="Hera", cat="god", camp="ach", dies=None,
    sub=("天后", "Queen of the gods"),
    bio=("天后，宙斯的妻子和姐姐，与特洛伊势不两立。她借来阿佛洛狄忒的腰带、请睡神相助，让宙斯在伊达山上沉睡，好让希腊人反攻。",
         "Queen of the gods, Zeus's wife and sister, and Troy's implacable enemy. She borrows Aphrodite's charmed band and enlists Sleep to lull Zeus on Mount Ida, so the Greeks can strike back."),
    icon=("高冠（polos）、面纱与王杖。", "Tall crown (polos), veil and scepter.")),
  N(id="athena", zh="雅典娜", gr="Ἀθηνᾶ", en="Athena", cat="god", camp="ach", dies=None,
    sub=("智慧女神", "Goddess of wisdom"),
    bio=("智慧与战争女神，与赫拉一同站在希腊人一边。她在卷一按住拔剑的阿喀琉斯，在卷五赐狄奥墨得斯神勇，最后化作得伊福玻斯，骗赫克托尔停步迎战。",
         "Goddess of wisdom and war, siding with Hera and the Greeks. She stops Achilles from drawing his sword in Book 1, fills Diomedes with divine strength in Book 5, and at the end takes the form of Deiphobus to trick Hector into standing his ground."),
    icon=("高冠头盔与猫头鹰。", "Crested helmet and owl.")),
  N(id="poseidon", zh="波塞冬", gr="Ποσειδῶν", en="Poseidon", cat="god", camp="ach", dies=None,
    sub=("海神", "God of the sea"),
    bio=("海神，宙斯的兄弟，站在希腊人一边。趁宙斯沉睡，他化作卡尔卡斯鼓舞两位埃阿斯；却又从阿喀琉斯手下救出特洛伊人埃涅阿斯，因为命运注定埃涅阿斯要延续特洛伊王族。",
         "God of the sea and Zeus's brother, on the Greek side. While Zeus sleeps he takes Calchas's form to rally the two Ajaxes; yet he also snatches the Trojan Aeneas from Achilles, because Aeneas is fated to carry on Troy's royal line."),
    icon=("长须、发带与三叉戟。", "Long beard, headband and trident.")),
  N(id="hermes", zh="赫尔墨斯", gr="Ἑρμῆς", en="Hermes", cat="god", camp="ach", dies=None,
    sub=("神使", "Messenger god"),
    bio=("神使，宙斯之子，神战中站在希腊人一边。卷二十四，他扮作阿喀琉斯的侍从，护送老王普里阿摩斯夜入敌营。",
         "Messenger of the gods and son of Zeus, on the Greek side when the gods take the field. In Book 24 he poses as one of Achilles's men and guides old Priam through the enemy camp by night."),
    icon=("带翼的宽檐帽与双蛇杖。", "Winged traveler's hat and herald's staff.")),
  N(id="hephaestus", zh="赫菲斯托斯", gr="Ἥφαιστος", en="Hephaestus", cat="god", camp="ach", dies=None,
    sub=("火神 · 匠神", "God of the forge"),
    bio=("火与锻造之神，赫拉之子，跛足。应忒提斯之请，他连夜为阿喀琉斯打造新铠甲，那面盾牌上刻着整个人间；河神围困阿喀琉斯时，他放火烧退了河水。",
         "God of fire and the forge, Hera's lame son. At Thetis's request he forges new armor for Achilles overnight, with a shield that shows the whole human world; when the river god traps Achilles, he drives the water back with fire."),
    icon=("工匠小帽、锤子与火钳。", "Craftsman's cap, hammer and tongs.")),
  N(id="thetis", zh="忒提斯", gr="Θέτις", en="Thetis", cat="god", camp="ach", dies=None,
    sub=("海中女神", "Sea goddess"),
    bio=("海中女神，阿喀琉斯的母亲。她抱住宙斯的膝盖为儿子求得荣誉，又向赫菲斯托斯讨来新铠甲。她知道儿子的命运：杀死赫克托尔之后，他自己也将很快死去。",
         "A sea goddess, mother of Achilles. She clasps Zeus's knees to win honor for her son and fetches new armor for him from Hephaestus. She knows his fate: soon after he kills Hector, he too must die."),
    icon=("海豚——她是海中老人涅柔斯的女儿。", "A dolphin: she is a daughter of Nereus, the Old Man of the Sea.")),
  N(id="aphrodite", zh="阿佛洛狄忒", gr="Ἀφροδίτη", en="Aphrodite", cat="god", camp="troy", dies=None,
    sub=("爱与美之神", "Goddess of love"),
    bio=("爱与美的女神，宙斯与狄俄涅之女，偏袒特洛伊，因为帕里斯当年把奖赏判给了她。她从决斗场上救走帕里斯，又在救儿子埃涅阿斯时被狄奥墨得斯刺伤了手腕。",
         "Goddess of love and beauty, daughter of Zeus and Dione, partial to Troy because Paris once judged her the fairest. She whisks Paris away from his duel, and is wounded in the wrist by Diomedes while rescuing her son Aeneas."),
    icon=("头冠与鸽子。", "Diadem and dove.")),
  N(id="apollo", zh="阿波罗", gr="Ἀπόλλων", en="Apollo", cat="god", camp="troy", dies=None,
    sub=("远射之神", "The far-shooter"),
    bio=("远射之神，宙斯与勒托之子，特洛伊的守护神。他应祭司克律塞斯的祈祷降下瘟疫，引出全诗开头的争吵；又从背后击落帕特洛克罗斯的铠甲，一路护佑赫克托尔。",
         "The far-shooting god, son of Zeus and Leto, and Troy's protector. Answering his priest Chryses, he sends the plague that sets off the quarrel of Book 1; he strikes the armor from Patroclus and watches over Hector to the end."),
    icon=("月桂冠与里拉琴。", "Laurel wreath and lyre.")),
  N(id="ares", zh="阿瑞斯", gr="Ἄρης", en="Ares", cat="god", camp="troy", dies=None,
    sub=("战神", "God of war"),
    bio=("战神，宙斯与赫拉之子，站在特洛伊一边。卷五他被雅典娜相助的狄奥墨得斯刺伤，嚎叫声如上万人齐吼；宙斯说他是众神里最可恨的一个。",
         "God of war, son of Zeus and Hera, fighting for Troy. In Book 5 Diomedes, helped by Athena, wounds him, and he bellows like ten thousand men; Zeus calls him the most hateful of the gods."),
    icon=("科林斯式头盔与长矛。", "Corinthian helmet and spear.")),
  N(id="scamander", zh="斯卡曼德罗斯", gr="Σκάμανδρος", en="Scamander", cat="god", camp="troy", dies=None,
    sub=("河神", "River god"),
    bio=("特洛伊平原上的河神，凡人叫他斯卡曼德罗斯，众神叫他克珊托斯。阿喀琉斯把尸体塞满河道，他怒而掀起洪水追赶阿喀琉斯，直到被赫菲斯托斯的火焰烧退。",
         "God of the river on the Trojan plain, called Scamander by men and Xanthus by the gods. When Achilles chokes his stream with corpses, he rises in flood and chases him, until Hephaestus's fire drives him back."),
    icon=("发间的芦苇与水波。", "Reeds in his hair and rippling water.")),

  # ------------------------------------------------------------------ Greeks
  N(id="achilles", zh="阿喀琉斯", gr="Ἀχιλλεύς", en="Achilles", cat="demi", camp="ach", dies=None,
    sub=("希腊第一勇士", "Greatest of the Greeks"),
    bio=("希腊联军中最强的战士，海中女神忒提斯之子。阿伽门农夺走布里塞伊斯，他愤而退出战斗；挚友帕特洛克罗斯战死后，他重返战场杀死赫克托尔，最后在普里阿摩斯面前放下了愤怒。全诗第一个词就是“愤怒”。",
         "The greatest Greek warrior, son of the sea goddess Thetis. When Agamemnon takes Briseis from him, he withdraws from the fighting in anger; after his friend Patroclus is killed, he returns to kill Hector, and at last lays his anger down before Priam. The poem's first word is “wrath”."),
    icon=("长发与盾牌——赫菲斯托斯为他打造的那面盾，上面刻着城市、田野与星辰。", "Long hair and the shield Hephaestus made him, worked with cities, fields and stars.")),
  N(id="agamemnon", zh="阿伽门农", gr="Ἀγαμέμνων", en="Agamemnon", cat="mortal", camp="ach", dies=None,
    sub=("联军统帅", "Commander-in-chief"),
    bio=("迈锡尼国王，希腊联军统帅，墨涅拉奥斯的哥哥。他拒绝让祭司赎回女儿，招来瘟疫；被迫归还后，又夺走阿喀琉斯的布里塞伊斯，引发全诗的冲突。",
         "King of Mycenae, commander of the Greek army, brother of Menelaus. His refusal to let a priest ransom his daughter brings the plague; forced to give her back, he takes Briseis from Achilles instead, setting off the whole conflict."),
    icon=("尖齿王冠与王杖——那根王杖是赫菲斯托斯所造，代代相传到他手中（卷二）。", "A spiked crown and the scepter Hephaestus made, handed down to him through generations (Book 2).")),
  N(id="menelaus", zh="墨涅拉奥斯", gr="Μενέλαος", en="Menelaus", cat="mortal", camp="ach", dies=None,
    sub=("斯巴达国王", "King of Sparta"),
    bio=("斯巴达国王，海伦的丈夫，阿伽门农的弟弟。卷三他与帕里斯决斗，眼看得胜，帕里斯却被阿佛洛狄忒救走；卷十七他拼死护住帕特洛克罗斯的遗体。",
         "King of Sparta, Helen's husband and Agamemnon's brother. In Book 3 he duels Paris and is about to win when Aphrodite spirits Paris away; in Book 17 he fights to protect Patroclus's body."),
    icon=("浅色头发——荷马常称他“金发的墨涅拉奥斯”；头冠与王杖。", "Light hair (Homer's “fair-haired Menelaus”), diadem and scepter.")),
  N(id="patroclus", zh="帕特洛克罗斯", gr="Πάτροκλος", en="Patroclus", cat="mortal", camp="ach", dies="卷十六",
    sub=("阿喀琉斯的挚友", "Achilles's companion"),
    bio=("阿喀琉斯最亲密的伙伴。他穿上阿喀琉斯的铠甲出战，杀死萨尔佩冬，一路追到特洛伊城下，被阿波罗击落铠甲，死在赫克托尔手中。他的死让阿喀琉斯重返战场。",
         "Achilles's dearest companion. Wearing Achilles's armor, he kills Sarpedon and drives the Trojans back to their walls, until Apollo strikes the armor from him and Hector kills him. His death brings Achilles back into the war."),
    icon=("头盔——他穿着借来的阿喀琉斯铠甲出战。", "A helmet: he goes into battle in Achilles's borrowed armor.")),
  N(id="odysseus", zh="奥德修斯", gr="Ὀδυσσεύς", en="Odysseus", cat="mortal", camp="ach", dies=None,
    sub=("伊塔卡国王", "King of Ithaca"),
    bio=("伊塔卡国王，以智谋和口才著称。他送还克律塞伊斯，用王杖教训忒尔西特斯，随使团劝说阿喀琉斯，又与狄奥墨得斯夜袭敌营。",
         "King of Ithaca, known for cunning and eloquence. He returns Chryseis to her father, beats Thersites into silence with the scepter, joins the embassy to Achilles, and raids the Trojan lines by night with Diomedes."),
    icon=("尖顶毡帽（pilos）与弓。", "The pointed felt cap (pilos) and a bow.")),
  N(id="diomedes", zh="狄奥墨得斯", gr="Διομήδης", en="Diomedes", cat="mortal", camp="ach", dies=None,
    sub=("阿尔戈斯国王", "King of Argos"),
    bio=("阿尔戈斯国王，希腊联军中最年轻的猛将之一。卷五在雅典娜相助下，他一天之内刺伤了阿佛洛狄忒和战神阿瑞斯；又与格劳科斯认出是世交，阵前交换铠甲。",
         "King of Argos, one of the youngest of the great Greek fighters. In Book 5, with Athena's help, he wounds both Aphrodite and Ares in a single day; later he finds that Glaucus is an old family guest-friend, and they exchange armor on the field."),
    icon=("燃着火焰的头盔——雅典娜让火焰从他的盔顶燃起（卷五）。", "A helmet crowned with flame: Athena kindles fire on his helmet (Book 5).")),
  N(id="ajax", zh="大埃阿斯", gr="Αἴας", en="Ajax", cat="mortal", camp="ach", dies=None,
    sub=("忒拉蒙之子", "Son of Telamon"),
    bio=("萨拉米斯人的首领，希腊人中身材最魁梧的一个，手持“像城墙一样”的大盾。他与赫克托尔决斗不分胜负，互赠礼物；希腊战船危急时，他几乎独力守住船头。",
         "Leader of the men of Salamis, the biggest of the Greeks, carrying a shield “like a tower”. His duel with Hector ends in a draw and an exchange of gifts; when the ships are about to burn, he almost single-handedly holds them."),
    icon=("塔一样的大盾。", "A shield like a tower.")),
  N(id="nestor", zh="涅斯托尔", gr="Νέστωρ", en="Nestor", cat="mortal", camp="ach", dies=None,
    sub=("皮洛斯老王", "Old king of Pylos"),
    bio=("皮洛斯的老王，希腊人中最年长、最善言辞的谋士。他多次调解争端，也在卷十一劝帕特洛克罗斯借阿喀琉斯的铠甲出战，这一计改变了战局，也断送了帕特洛克罗斯。",
         "The aged king of Pylos, oldest and most eloquent of the Greek counselors. He tries again and again to make peace, and in Book 11 urges Patroclus to go into battle in Achilles's armor, advice that turns the war and costs Patroclus his life."),
    icon=("白发白须与“涅斯托尔之杯”——卷十一描写的那只饰有金鸽的大杯。", "White hair and beard, and “Nestor's cup”, the great cup adorned with golden doves described in Book 11.")),
  N(id="antilochus", zh="安提洛科斯", gr="Ἀντίλοχος", en="Antilochus", cat="mortal", camp="ach", dies=None,
    sub=("涅斯托尔之子", "Son of Nestor"),
    bio=("涅斯托尔之子，年轻敏捷。是他含泪把帕特洛克罗斯的死讯告诉阿喀琉斯；在葬礼赛车中，他靠抢道胜过墨涅拉奥斯，又得体地让出奖品。",
         "Nestor's son, young and quick. He is the one who brings Achilles the news of Patroclus's death; in the funeral chariot race he cuts in front of Menelaus, then gracefully offers him the prize."),
    icon=("战车车轮——他在葬礼赛车中得了第二名。", "A chariot wheel: he came second in the funeral chariot race.")),
  N(id="phoenix", zh="福尼克斯", gr="Φοῖνιξ", en="Phoenix", cat="mortal", camp="ach", dies=None,
    sub=("阿喀琉斯之师", "Achilles's tutor"),
    bio=("阿喀琉斯的老师，从小把他抱在膝上喂养。他随使团劝阿喀琉斯回心转意，讲了墨勒阿革洛斯因愤怒而错失时机的故事。",
         "Achilles's old tutor, who held him on his knee as a child. With the embassy he pleads with Achilles to relent, telling the story of Meleager, whose anger made him miss his moment."),
    icon=("白发与手杖。", "White hair and a walking staff.")),
  N(id="calchas", zh="卡尔卡斯", gr="Κάλχας", en="Calchas", cat="mortal", camp="ach", dies=None,
    sub=("预言者", "Seer"),
    bio=("希腊军中的预言者。在阿喀琉斯担保下，他说出瘟疫的原因：阿伽门农羞辱了阿波罗的祭司。",
         "The Greek army's seer. With Achilles's promise of protection, he reveals the cause of the plague: Agamemnon has insulted Apollo's priest."),
    icon=("月桂枝与飞鸟——荷马称他是最好的鸟卜者。", "A laurel sprig and a bird: Homer calls him the best of bird-diviners.")),
  N(id="thersites", zh="忒尔西特斯", gr="Θερσίτης", en="Thersites", cat="mortal", camp="ach", dies=None,
    sub=("口无遮拦的兵士", "The loudmouth"),
    bio=("希腊军中最丑的人，口无遮拦。他在大会上辱骂阿伽门农贪婪，被奥德修斯用王杖打得背上起了血痕，众人哄笑。",
         "The ugliest man in the Greek army and the most foul-mouthed. When he rails at Agamemnon's greed in the assembly, Odysseus beats him with the scepter until a bloody welt rises on his back, and the soldiers laugh."),
    icon=("尖脑袋、稀疏的头发——荷马对他的相貌描写得毫不客气（卷二）。", "A pointed head with sparse hair: Homer describes him unsparingly (Book 2).")),
  N(id="briseis", zh="布里塞伊斯", gr="Βρισηΐς", en="Briseis", cat="mortal", camp="ach", dies=None,
    sub=("阿喀琉斯的女俘", "Achilles's captive"),
    bio=("阿喀琉斯攻下吕尔涅索斯时俘获的女子，被分给他作为荣誉的奖赏。阿伽门农夺走她，引发阿喀琉斯的愤怒；她回到阿喀琉斯营帐时，扑在帕特洛克罗斯的遗体上痛哭。",
         "A woman Achilles captured when he sacked Lyrnessus, awarded to him as his prize of honor. Agamemnon's seizure of her sparks Achilles's wrath; when she is returned, she throws herself on Patroclus's body and weeps."),
    icon=("面纱与耳饰。", "Veil and earrings.")),

  # ------------------------------------------------------------------ Trojans
  N(id="hector", zh="赫克托尔", gr="Ἕκτωρ", en="Hector", cat="mortal", camp="troy", dies="卷二十二",
    sub=("特洛伊主将", "Troy's champion"),
    bio=("特洛伊王子、守城主将，普里阿摩斯之子。他明知城池难保仍坚持出战，杀死帕特洛克罗斯，最终在城下被阿喀琉斯所杀。全诗以他的葬礼结束。",
         "Prince of Troy and its chief defender, son of Priam. Knowing the city cannot be saved, he fights on, kills Patroclus, and is killed by Achilles beneath the walls. The poem ends with his funeral."),
    icon=("高高的马鬃盔缨——荷马称他“头盔闪亮的赫克托尔”，这盔缨曾吓哭他的幼子。", "A tall horsehair crest: Homer's “Hector of the flashing helmet”. The crest once made his baby son cry.")),
  N(id="priam", zh="普里阿摩斯", gr="Πρίαμος", en="Priam", cat="mortal", camp="troy", dies=None,
    sub=("特洛伊国王", "King of Troy"),
    bio=("特洛伊老王，五十个儿子的父亲。卷二十四，他带着赎礼夜入希腊营地，亲吻杀死他儿子的那双手，求阿喀琉斯归还赫克托尔的遗体。",
         "The old king of Troy, father of fifty sons. In Book 24 he goes by night into the Greek camp with a ransom, kisses the hands that killed his son, and begs Achilles for Hector's body."),
    icon=("白须、头冠与赎礼金碗。", "White beard, crown and a golden bowl from the ransom.")),
  N(id="hecuba", zh="赫卡柏", gr="Ἑκάβη", en="Hecuba", cat="mortal", camp="troy", dies=None,
    sub=("特洛伊王后", "Queen of Troy"),
    bio=("特洛伊王后，赫克托尔的母亲。她率特洛伊妇女向雅典娜献上最好的袍子祈求保佑，女神却不予理睬；赫克托尔出城迎战前，她袒露胸脯哀求儿子回来。",
         "Queen of Troy and Hector's mother. She leads the Trojan women in offering Athena their finest robe, but the goddess refuses them; before Hector's last fight she bares the breast that nursed him, begging him to come inside."),
    icon=("老妇的面纱与献给雅典娜的袍子。", "An old woman's veil and the robe offered to Athena.")),
  N(id="andromache", zh="安德罗马刻", gr="Ἀνδρομάχη", en="Andromache", cat="mortal", camp="troy", dies=None,
    sub=("赫克托尔之妻", "Hector's wife"),
    bio=("赫克托尔的妻子。她的父亲和七个兄弟都死在阿喀琉斯手下，赫克托尔就是她的一切。卷六夫妻在城头诀别；卷二十二她在织布时听到哭声，奔上城墙，看见丈夫的遗体被拖走。",
         "Hector's wife. Achilles killed her father and all seven of her brothers, so Hector is everything to her. In Book 6 they say goodbye on the wall; in Book 22, at her loom, she hears the wailing and runs to the wall to see his body dragged away."),
    icon=("头巾——她在悲恸中扯落了阿佛洛狄忒送的头纱（卷二十二）。", "A headdress: in her grief she tears off the veil Aphrodite gave her (Book 22).")),
  N(id="astyanax", zh="阿斯提阿纳克斯", gr="Ἀστυάναξ", en="Astyanax", cat="mortal", camp="troy", dies=None,
    sub=("赫克托尔之子", "Hector's son"),
    bio=("赫克托尔的幼子，名字意为“城邦之主”。父亲伸手抱他时，他被盔顶晃动的马鬃吓得哭着缩回乳母怀里，父母相视而笑。",
         "Hector's baby son, whose name means “lord of the city”. When his father reaches for him, he shrinks back crying into his nurse's arms, frightened by the nodding horsehair crest, and his parents laugh."),
    icon=("婴儿与父亲的盔缨。", "A baby and his father's crest.")),
  N(id="paris", zh="帕里斯", gr="Πάρις", en="Paris", cat="mortal", camp="troy", dies=None,
    sub=("特洛伊王子", "Prince of Troy"),
    bio=("普里阿摩斯之子，又名亚历山德罗斯。他从斯巴达带走海伦，引发这场战争。长于射箭，拙于近战；赫克托尔临死预言，他将在阿波罗相助下射杀阿喀琉斯。",
         "Son of Priam, also called Alexandros. By carrying Helen off from Sparta he caused the war. Skilled with the bow and poor in close combat; the dying Hector foretells that he, with Apollo, will kill Achilles."),
    icon=("弗里吉亚软帽与金苹果——后世传说中三女神之争的奖品，卷二十四提到了这场裁判。", "Phrygian cap and golden apple, the prize in the contest of the goddesses that Book 24 alludes to.")),
  N(id="helen", zh="海伦", gr="Ἑλένη", en="Helen", cat="demi", camp="troy", dies=None,
    sub=("斯巴达王后", "Queen of Sparta"),
    bio=("宙斯之女，墨涅拉奥斯的妻子，随帕里斯来到特洛伊。她在城头为普里阿摩斯指认希腊将领；她厌恶帕里斯的怯懦，也自责是这场战争的祸根。",
         "Daughter of Zeus and wife of Menelaus, who went with Paris to Troy. From the wall she names the Greek chiefs for Priam; she despises Paris's cowardice and blames herself for the war."),
    icon=("头冠、面纱与铜镜。", "Diadem, veil and a bronze mirror.")),
  N(id="aeneas", zh="埃涅阿斯", gr="Αἰνείας", en="Aeneas", cat="demi", camp="troy", dies=None,
    sub=("达达尼亚首领", "Dardanian leader"),
    bio=("特洛伊一方的名将，女神阿佛洛狄忒之子。卷五他被狄奥墨得斯用巨石砸伤，由母亲和阿波罗救走；卷二十与阿喀琉斯交锋时，又被波塞冬救出。命运注定他要延续特洛伊的血脉。",
         "A leading Trojan warrior, son of the goddess Aphrodite. In Book 5 Diomedes crushes him with a boulder and he is rescued by his mother and Apollo; in Book 20 Poseidon saves him from Achilles, since he is fated to carry on Troy's line."),
    icon=("头盔与长矛。", "Helmet and spear.")),
  N(id="sarpedon", zh="萨尔佩冬", gr="Σαρπηδών", en="Sarpedon", cat="demi", camp="troy", dies="卷十六",
    sub=("吕基亚国王", "King of Lycia"),
    bio=("吕基亚国王，宙斯之子，特洛伊最重要的盟友。他对格劳科斯说：既然人终有一死，就去赢得荣耀。宙斯想救他却终未出手，只降下血雨致哀；他死于帕特洛克罗斯之手。",
         "King of Lycia, son of Zeus, and Troy's most important ally. He tells Glaucus that since men must die anyway, they should go and win glory. Zeus longs to save him but holds back, shedding a rain of blood; he dies at Patroclus's hands."),
    icon=("身后的翅膀——睡神与死神把他的遗体送回故乡，著名的欧弗洛尼奥斯陶瓶就画着这一幕。", "Wings behind him: Sleep and Death carry his body home, the scene on the famous Euphronios krater.")),
  N(id="glaucus", zh="格劳科斯", gr="Γλαῦκος", en="Glaucus", cat="mortal", camp="troy", dies=None,
    sub=("吕基亚将领", "Lycian captain"),
    bio=("吕基亚将领，萨尔佩冬的战友。他在阵前向狄奥墨得斯讲述家世，说出“人类的世代如同树叶”；两人认出祖辈是世交，于是交换铠甲，他拿金甲换了铜甲。",
         "A Lycian captain and Sarpedon's comrade. Facing Diomedes, he tells his lineage and says that the generations of men are like leaves; learning that their grandfathers were guest-friends, they exchange armor, his gold for Diomedes's bronze."),
    icon=("金色的头盔——他用金甲换了铜甲。", "A golden helmet: he traded gold armor for bronze.")),
  N(id="pandarus", zh="潘达罗斯", gr="Πάνδαρος", en="Pandarus", cat="mortal", camp="troy", dies="卷五",
    sub=("弓箭手", "Archer"),
    bio=("特洛伊一方的弓箭手。雅典娜化身劝诱，他暗箭射伤墨涅拉奥斯，撕毁了双方的停战誓约；随后被狄奥墨得斯所杀。",
         "An archer on the Trojan side. Egged on by Athena in disguise, he shoots Menelaus and breaks the sworn truce; soon afterward Diomedes kills him."),
    icon=("弓——他的弓用野山羊角制成（卷四）。", "A bow, made from the horns of a wild goat (Book 4).")),
  N(id="polydamas", zh="波吕达马斯", gr="Πουλυδάμας", en="Polydamas", cat="mortal", camp="troy", dies=None,
    sub=("特洛伊谋士", "Trojan counselor"),
    bio=("特洛伊谋士，与赫克托尔同一夜出生，一个善谋、一个善战。他几次劝赫克托尔退守城内，都被斥退；赫克托尔临死前才后悔没听他的话。",
         "A Trojan counselor, born on the same night as Hector: one good with words, the other with the spear. Several times he urges Hector to fall back inside the walls and is brushed aside; only before his death does Hector regret it."),
    icon=("抓着蛇的鹰——他解读过这个凶兆，劝特洛伊人别攻船营（卷十二）。", "An eagle clutching a snake: he reads this omen as a warning not to attack the ships (Book 12).")),
  N(id="dolon", zh="多隆", gr="Δόλων", en="Dolon", cat="mortal", camp="troy", dies="卷十",
    sub=("特洛伊探子", "Trojan scout"),
    bio=("特洛伊探子，贪图阿喀琉斯的神驹，自愿夜探希腊营地。他披着狼皮出发，途中被奥德修斯和狄奥墨得斯擒获，吐露军情后仍被处死。",
         "A Trojan scout who volunteers to spy on the Greek camp by night, lured by the promise of Achilles's horses. Wearing a wolfskin, he is caught by Odysseus and Diomedes, tells them everything, and is killed anyway."),
    icon=("狼皮头套。", "A wolfskin hood.")),
  N(id="chryses", zh="克律塞斯", gr="Χρύσης", en="Chryses", cat="mortal", camp="troy", dies=None,
    sub=("阿波罗祭司", "Priest of Apollo"),
    bio=("阿波罗的祭司。他带着赎礼来赎回被俘的女儿，却被阿伽门农粗暴赶走；他向阿波罗祈祷，瘟疫随即降临希腊军营。",
         "A priest of Apollo. He comes with a ransom for his captured daughter and is driven off roughly by Agamemnon; he prays to Apollo, and plague falls on the Greek camp."),
    icon=("系着羊毛彩带的金杖——祭司的标志（卷一）。", "A golden staff hung with woolen fillets, the mark of a priest (Book 1).")),
  N(id="chryseis", zh="克律塞伊斯", gr="Χρυσηΐς", en="Chryseis", cat="mortal", camp="troy", dies=None,
    sub=("祭司之女", "The priest's daughter"),
    bio=("克律塞斯的女儿，被俘后分给阿伽门农。阿伽门农说她胜过自己的王后，拒绝归还；瘟疫降临后，奥德修斯把她送回了父亲身边。",
         "Chryses's daughter, captured and given to Agamemnon. He says he prefers her to his own queen and refuses to give her back; after the plague, Odysseus takes her home to her father."),
    icon=("发带与项链。", "Headband and necklace.")),
]

# (source, target, type, zh label, zh text, en label, en text, book ref in Chinese)
E = lambda *a: a
EDGES = [
  E("zeus","hera","kin","夫妻","赫拉是宙斯的妻子，也是他的姐姐。她借阿佛洛狄忒的腰带、请睡神相助，让宙斯在伊达山上沉睡，好让希腊人反攻；宙斯醒来后大怒。",
    "Married","Hera is Zeus's wife and sister. With Aphrodite's charmed band and the help of Sleep, she lulls him on Mount Ida so the Greeks can counterattack; he wakes in fury.","卷十四、卷十五"),
  E("zeus","athena","kin","父女","雅典娜是宙斯之女。宙斯一度禁止众神参战，最后又准许她下凡，助阿喀琉斯杀死赫克托尔。",
    "Father–daughter","Athena is Zeus's daughter. He at one point forbids the gods to fight, but at the end lets her go down to help Achilles kill Hector.","卷八、卷二十二"),
  E("zeus","poseidon","kin","兄弟","宙斯命他退出战场，波塞冬不服，说三兄弟本是平分天下，最后还是悻悻退去。",
    "Brothers","Ordered out of the battle by Zeus, Poseidon protests that the three brothers divided the world equally, but in the end withdraws, grumbling.","卷十五"),
  E("zeus","hermes","kin","父子","宙斯派赫尔墨斯护送普里阿摩斯穿过希腊营地。",
    "Father–son","Zeus sends Hermes to guide Priam through the Greek camp.","卷二十四"),
  E("zeus","apollo","kin","父子","阿波罗是宙斯与勒托之子。宙斯派他去重振受伤的赫克托尔，又派他为萨尔佩冬收殓遗体。",
    "Father–son","Apollo is the son of Zeus and Leto. Zeus sends him to revive the wounded Hector and to recover Sarpedon's body.","卷十五、卷十六"),
  E("zeus","aphrodite","kin","父女","阿佛洛狄忒是宙斯与狄俄涅之女。她负伤回到奥林波斯，宙斯笑着劝她：打仗不是你的事，去管婚姻爱情吧。",
    "Father–daughter","Aphrodite is the daughter of Zeus and Dione. When she returns to Olympus wounded, Zeus smiles and tells her war is not her business; she should see to love and marriage.","卷五"),
  E("zeus","ares","kin","父子","阿瑞斯受伤后回奥林波斯诉苦，宙斯却说他是众神中最可恨的一个。",
    "Father–son","When the wounded Ares complains to him, Zeus tells him he is the most hateful of all the gods.","卷五"),
  E("zeus","hephaestus","kin","父子","赫菲斯托斯回忆，他曾因护着母亲，被宙斯抓住脚扔下奥林波斯，摔落在利姆诺斯岛上。",
    "Father–son","Hephaestus recalls how Zeus once seized him by the foot and hurled him from Olympus for siding with his mother; he landed on Lemnos.","卷一"),
  E("hera","hephaestus","kin","母子","他劝母亲别跟宙斯争吵，一瘸一拐地为众神斟酒，惹得满堂大笑；河神围困阿喀琉斯时，他应母亲之请放火退水。",
    "Mother–son","He begs his mother not to quarrel with Zeus and hobbles round pouring wine, setting the gods laughing; when the river traps Achilles, he answers her call and drives it back with fire.","卷一、卷二十一"),
  E("zeus","thetis","aid","应求点头","忒提斯抱住宙斯的膝盖，求他让特洛伊人占上风，直到希腊人肯尊重阿喀琉斯。宙斯点头应允，奥林波斯为之震动。",
    "Grants her plea","Thetis clasps Zeus's knees and begs him to let the Trojans prevail until the Greeks honor Achilles. Zeus nods, and Olympus shakes.","卷一"),
  E("zeus","sarpedon","kin","父子","宙斯想把儿子救出战场，被赫拉劝阻；他降下血雨哀悼，又让睡神与死神把遗体送回吕基亚。",
    "Father–son","Zeus wants to snatch his son from the battle, but Hera talks him out of it; he sheds a rain of blood in mourning and has Sleep and Death carry the body home to Lycia.","卷十六"),
  E("zeus","helen","kin","父女","荷马称海伦为“宙斯的女儿”。",
    "Father–daughter","Homer calls Helen the daughter of Zeus.","卷三"),
  E("zeus","hector","tie","称量命运","宙斯一度把荣耀赐给赫克托尔；最后他拿出金天平称量两人的命运，赫克托尔的一端沉向了冥府。",
    "Weighs his fate","For a time Zeus gives Hector glory; at the end he sets out his golden scales, and Hector's fate sinks toward Hades.","卷十五、卷二十二"),
  E("zeus","agamemnon","tie","托假梦","为兑现对忒提斯的承诺，宙斯给阿伽门农托了一个假梦，骗他立即攻城。",
    "False dream","To keep his promise to Thetis, Zeus sends Agamemnon a false dream urging him to attack at once.","卷二"),
  E("hera","athena","aid","同盟","两位女神都因帕里斯的裁判而仇视特洛伊，一同驾车下凡助战。",
    "Allies","Both goddesses hate Troy because of Paris's judgment, and drive down together to help the Greeks.","卷五、卷八"),
  E("hera","aphrodite","tie","借腰带","赫拉谎称要去调解一对老夫妻的争吵，向阿佛洛狄忒借来绣着爱欲魔力的腰带，用来迷惑宙斯。",
    "Borrows her band","Pretending she wants to reconcile an old couple, Hera borrows Aphrodite's embroidered band, full of desire, to beguile Zeus.","卷十四"),
  E("hera","paris","foe","裁判之仇","帕里斯在三位女神中把奖赏判给了阿佛洛狄忒，从此赫拉与雅典娜对特洛伊怀恨在心。",
    "The judgment","Paris judged Aphrodite the winner among the three goddesses; ever since, Hera and Athena have hated Troy.","卷二十四"),
  E("aphrodite","paris","aid","救出决斗","帕里斯与墨涅拉奥斯决斗将败，阿佛洛狄忒把他裹在雾中，送回卧房。",
    "Saves him","As Paris is about to lose his duel with Menelaus, Aphrodite wraps him in mist and sets him down in his bedroom.","卷三"),
  E("athena","achilles","aid","按住怒火","阿喀琉斯要拔剑杀阿伽门农，雅典娜从背后抓住他的金发劝止；最后她帮他对付赫克托尔，还把掷空的长矛递回他手中。",
    "Restrains, then aids","As Achilles draws his sword on Agamemnon, Athena seizes him by his golden hair and stops him; at the end she helps him against Hector, even handing back his thrown spear.","卷一、卷二十二"),
  E("athena","hector","foe","化身欺敌","雅典娜化作赫克托尔的弟弟得伊福玻斯，让他以为有人助战而停步迎战阿喀琉斯；等他回头，身边空无一人。",
    "Deceives him","Athena takes the form of his brother Deiphobus, so Hector stands to fight Achilles thinking he has help; when he turns, no one is there.","卷二十二"),
  E("athena","diomedes","aid","赐予神勇","雅典娜让他能分辨神与凡人，又亲自为他驾车，冲向战神阿瑞斯。",
    "Gives him might","Athena clears his eyes to tell gods from men, and takes the reins of his chariot herself to charge the war god Ares.","卷五"),
  E("athena","odysseus","aid","护佑","希腊人争相上船要回家时，雅典娜派奥德修斯拦住大军；赛跑时她让领先的小埃阿斯滑倒，帮奥德修斯夺冠。",
    "Protects him","When the Greeks rush to the ships to sail home, Athena sends Odysseus to stop them; in the foot race she makes the leader slip so Odysseus wins.","卷二、卷二十三"),
  E("athena","pandarus","tie","唆使破约","雅典娜化作特洛伊人劳多科斯，怂恿潘达罗斯暗射墨涅拉奥斯，让停战誓约作废。",
    "Tempts him","Disguised as the Trojan Laodocus, Athena urges Pandarus to shoot Menelaus and so break the sworn truce.","卷四"),
  E("athena","ares","foe","两度击败","她先帮狄奥墨得斯把长矛刺进阿瑞斯腹中；神战时又举起巨石砸倒了他。",
    "Defeats him twice","She first drives Diomedes's spear into Ares's belly; later, in the battle of the gods, she fells him with a boulder.","卷五、卷二十一"),
  E("poseidon","aeneas","aid","救出战场","埃涅阿斯迎战阿喀琉斯，波塞冬用雾蒙住阿喀琉斯的眼，把他救走：命运注定他要延续特洛伊王族。",
    "Rescues him","When Aeneas faces Achilles, Poseidon clouds Achilles's eyes and carries Aeneas off: he is fated to carry on the royal line of Troy.","卷二十"),
  E("poseidon","ajax","aid","鼓舞","趁宙斯不注意，波塞冬化作卡尔卡斯，用神杖点触两位埃阿斯，给他们注入力量守住战船。",
    "Rallies him","While Zeus looks away, Poseidon takes Calchas's shape and touches the two Ajaxes with his staff, filling them with strength to hold the ships.","卷十三"),
  E("hermes","priam","aid","护送","赫尔墨斯扮作阿喀琉斯的年轻侍从，让守卫入睡，驾车把普里阿摩斯送进阿喀琉斯的营帐，天亮前又送他出营。",
    "Escorts him","Posing as a young squire of Achilles, Hermes puts the guards to sleep, drives Priam to Achilles's hut, and brings him out before dawn.","卷二十四"),
  E("hephaestus","achilles","aid","打造铠甲","一夜之间，他为阿喀琉斯打造新铠甲；盾牌上刻着天地星辰、战争中的城与和平中的城、田野与舞蹈。",
    "Forges his arms","Overnight he forges new armor for Achilles; on the shield he works earth, sky and stars, a city at war and a city at peace, fields and dances.","卷十八"),
  E("hephaestus","thetis","aid","报旧恩","他被母亲扔下奥林波斯时，是忒提斯收留了他九年；所以她一开口，他立刻答应。",
    "Repays a debt","When his mother threw him from Olympus, Thetis took him in for nine years; so when she asks, he agrees at once.","卷十八"),
  E("hephaestus","scamander","foe","火攻河神","河神掀起洪水追赶阿喀琉斯，赫菲斯托斯放出烈火，烧得河水沸腾，河神只好求饶。",
    "Fire against water","As the river floods after Achilles, Hephaestus unleashes fire until the water boils and the river god begs for mercy.","卷二十一"),
  E("thetis","achilles","kin","母子","她听到儿子的哭声从海底赶来。阿喀琉斯说，母亲告诉过他有两种命运：长寿而默默无闻，或短命而荣耀不朽；杀死赫克托尔之后，他的死期也就近了。",
    "Mother–son","She rises from the sea at the sound of his weeping. She has told him of his two fates, a long obscure life or a short one with undying glory; once Hector is dead, his own death is near.","卷一、卷九、卷十八"),
  E("aphrodite","aeneas","kin","母子","埃涅阿斯被巨石砸伤，母亲用双臂抱起他，却被狄奥墨得斯刺伤手腕，只得丢下他，由阿波罗接手救走。",
    "Mother–son","When Aeneas is struck down by a boulder, his mother gathers him in her arms, but Diomedes wounds her wrist and she drops him; Apollo carries him off.","卷五"),
  E("aphrodite","helen","tie","胁迫","决斗后，阿佛洛狄忒要海伦去帕里斯房中。海伦不肯，女神威胁要让她被两边同时憎恨，她只得顺从。",
    "Coerces her","After the duel Aphrodite orders Helen to Paris's bed. When Helen refuses, the goddess threatens to make both sides hate her, and she obeys.","卷三"),
  E("aphrodite","diomedes","foe","被刺伤","狄奥墨得斯追上阿佛洛狄忒，刺破她的手腕，流出了神的血液“灵液”。",
    "Wounded by him","Diomedes chases Aphrodite down and pierces her wrist, drawing ichor, the blood of the gods.","卷五"),
  E("apollo","chryses","aid","应祷降瘟","克律塞斯受辱后向阿波罗祈祷。阿波罗从奥林波斯下来，一连九天向希腊军营射出瘟疫之箭。",
    "Answers his prayer","Insulted, Chryses prays to Apollo, who comes down from Olympus and for nine days shoots arrows of plague into the Greek camp.","卷一"),
  E("apollo","patroclus","foe","击落铠甲","帕特洛克罗斯三次冲上特洛伊城墙，都被阿波罗推回；最后阿波罗从背后一掌击落他的头盔和铠甲，让他任人宰割。",
    "Strips him","Three times Patroclus tries to scale Troy's wall and three times Apollo thrusts him back; at last the god strikes him from behind, knocking off his helmet and armor and leaving him helpless.","卷十六"),
  E("apollo","hector","aid","护佑","阿波罗重振受伤的赫克托尔，带他冲向船营；他死后，又用金色神盾护住遗体不受损毁。",
    "Protects him","Apollo revives the wounded Hector and leads the charge on the ships; after his death, the god shields the body from harm with the golden aegis.","卷十五、卷二十四"),
  E("apollo","achilles","foe","诱敌 · 注定之死","阿波罗化作特洛伊人阿革诺尔引开阿喀琉斯；赫克托尔临死预言，阿喀琉斯将死在帕里斯与阿波罗手下。",
    "Decoy · fated death","Apollo takes the shape of the Trojan Agenor to lure Achilles away; the dying Hector foretells that Paris and Apollo will kill him.","卷二十一、卷二十二"),
  E("ares","diomedes","foe","被刺伤","雅典娜把狄奥墨得斯的长矛推进阿瑞斯腹中，战神的嚎叫声如九千、一万个战士齐吼。",
    "Wounded by him","Athena drives Diomedes's spear into Ares's belly, and the war god bellows as loud as nine or ten thousand men.","卷五"),
  E("scamander","achilles","foe","河战","阿喀琉斯把特洛伊人的尸体塞满河道，河神怒而掀起巨浪追赶他，差点把他淹死。",
    "Battle with a river","Achilles chokes the river with Trojan dead; the river god rises in a great wave and chases him, nearly drowning him.","卷二十一"),
  E("achilles","agamemnon","tie","争吵 · 夺妾","阿伽门农夺走布里塞伊斯，阿喀琉斯怒而罢战，发誓让希腊人后悔。直到帕特洛克罗斯死后，两人才当众和解。",
    "The quarrel","Agamemnon takes Briseis, and Achilles withdraws from the war, swearing the Greeks will regret it. Only after Patroclus's death are they publicly reconciled.","卷一、卷九、卷十九"),
  E("achilles","patroclus","aid","生死之交","两人自幼在佩琉斯家中一同长大。帕特洛克罗斯的亡魂托梦，求与阿喀琉斯骨灰同葬；阿喀琉斯把他的骨灰收进金瓮，留待自己死后同葬。",
    "Beloved friend","They grew up together in Peleus's house. Patroclus's ghost asks that their bones lie together, and Achilles gathers his bones in a golden urn to be shared with his own.","卷十六、卷十八、卷二十三"),
  E("achilles","hector","foe","杀死 · 拖尸","阿喀琉斯在城下追着赫克托尔绕城三圈，将他刺死，又把遗体拴在战车后拖行，一连多日不肯罢休。",
    "Kills, desecrates","Achilles chases Hector three times around the walls, kills him, and drags the body behind his chariot, day after day.","卷二十二、卷二十四"),
  E("achilles","priam","tie","夜会赎尸","普里阿摩斯亲吻杀子之手，让阿喀琉斯想起自己年迈的父亲。两人相对痛哭，阿喀琉斯归还遗体，并答应停战十一天。",
    "Night meeting","Priam kisses the hands that killed his son and makes Achilles think of his own old father. They weep together; Achilles gives back the body and grants an eleven-day truce.","卷二十四"),
  E("achilles","briseis","tie","战利品 · 所爱","她是阿喀琉斯的战利品，他却说自己真心爱她，如同爱自己的妻子。",
    "Prize and love","She is his prize of war, yet he says he loves her with all his heart, as a man loves his wife.","卷一、卷九、卷十九"),
  E("achilles","phoenix","aid","老师","福尼克斯从小把阿喀琉斯抱在膝上喂饭，又随他出征。使团来访时，他含泪讲述墨勒阿革洛斯的故事，劝阿喀琉斯别等到太迟。",
    "Old tutor","Phoenix fed Achilles on his knee as a child and came with him to war. With the embassy he tells through tears the story of Meleager, begging him not to wait too long.","卷九"),
  E("achilles","odysseus","tie","劝说遭拒","奥德修斯转述阿伽门农许下的厚礼，阿喀琉斯回答：心口不一的人，我恨他如恨冥府之门。",
    "Rebuffed","Odysseus lists the rich gifts Agamemnon offers; Achilles replies that he hates like the gates of Hades the man who says one thing and hides another in his heart.","卷九"),
  E("achilles","ajax","aid","直言相劝","使团中埃阿斯的话最直率：你为了一个女子，就抛下爱你的战友。阿喀琉斯承认他说得在理，但仍不肯出战。",
    "Blunt appeal","Ajax speaks most bluntly on the embassy: for one girl, Achilles abandons friends who love him. Achilles admits he is right, but still will not fight.","卷九"),
  E("achilles","antilochus","aid","报丧","安提洛科斯含泪跑来报告帕特洛克罗斯的死讯，紧紧握住阿喀琉斯的双手。",
    "Brings the news","Antilochus runs to him in tears with the news of Patroclus's death and holds his hands tight.","卷十八"),
  E("achilles","calchas","aid","担保","卡尔卡斯怕得罪国王，不敢说出瘟疫的原因；阿喀琉斯当众保证：即使是阿伽门农，也没人敢碰你。",
    "Protects him","Calchas fears to name the cause of the plague and offend a king; Achilles swears no one will lay a hand on him, not even Agamemnon.","卷一"),
  E("agamemnon","menelaus","kin","兄弟","阿伽门农为弟弟夺回海伦而领兵远征。墨涅拉奥斯中箭时，他惊恐万分，以为弟弟必死无疑。",
    "Brothers","Agamemnon leads the expedition to win back his brother's wife. When Menelaus is hit by an arrow, he is terrified he will die.","卷四"),
  E("agamemnon","chryseis","tie","不肯归还","他当众说喜爱克律塞伊斯胜过自己的王后克吕泰涅斯特拉，拒绝放她回家。",
    "His captive","He declares that he prefers Chryseis to his own queen, Clytemnestra, and refuses to let her go.","卷一"),
  E("agamemnon","chryses","foe","羞辱祭司","克律塞斯带着赎礼前来，阿伽门农却粗暴地把他赶走，并警告他别再靠近船营。",
    "Insults him","Chryses comes with a ransom, and Agamemnon drives him off roughly, warning him never to come near the ships again.","卷一"),
  E("agamemnon","briseis","tie","强夺","被迫归还克律塞伊斯后，他派人从阿喀琉斯帐中带走布里塞伊斯；后来他发誓从未碰过她。",
    "Seizes her","Forced to give up Chryseis, he has Briseis taken from Achilles's hut; later he swears he never touched her.","卷一、卷十九"),
  E("agamemnon","calchas","tie","迁怒","卡尔卡斯揭出瘟疫的原因，阿伽门农怒斥他：你从没对我说过一句好话。",
    "Lashes out","When Calchas names the cause of the plague, Agamemnon rounds on him: you have never once prophesied anything good for me.","卷一"),
  E("agamemnon","nestor","aid","谋臣","涅斯托尔试图调解统帅与阿喀琉斯的争吵，又建议派出使团去劝和。",
    "Counselor","Nestor tries to settle the quarrel between the commander and Achilles, and proposes the embassy to win Achilles back.","卷一、卷九"),
  E("agamemnon","odysseus","aid","奉命出使","奥德修斯奉命把克律塞伊斯送回她父亲身边，又作为使者去劝说阿喀琉斯。",
    "His envoy","Odysseus is sent to return Chryseis to her father, and to carry Agamemnon's offer to Achilles.","卷一、卷九"),
  E("agamemnon","thersites","foe","受辱骂","忒尔西特斯在大会上骂阿伽门农贪婪好色，把最好的战利品和女人都据为己有。",
    "Reviled","In the assembly Thersites rails at Agamemnon for greed, for keeping the best of the spoils and the women for himself.","卷二"),
  E("menelaus","paris","foe","决斗","两人约定单打独斗，决定海伦的归属。墨涅拉奥斯抓住帕里斯的头盔往回拖，阿佛洛狄忒弄断盔带，把帕里斯救走了。",
    "The duel","They agree to settle the war by single combat for Helen. Menelaus drags Paris by his helmet until Aphrodite snaps the strap and whisks Paris away.","卷三"),
  E("menelaus","helen","kin","原配夫妻","海伦是墨涅拉奥斯的妻子。决斗前她站在城头，心中又思念起前夫和故乡。",
    "Husband and wife","Helen is Menelaus's wife. Watching from the wall before the duel, she longs again for her first husband and her home.","卷三"),
  E("menelaus","pandarus","foe","中箭","潘达罗斯的暗箭射中墨涅拉奥斯，雅典娜把箭拨偏，只擦伤了他。",
    "Shot","Pandarus's arrow hits Menelaus, but Athena turns it aside so it only grazes him.","卷四"),
  E("menelaus","patroclus","aid","护尸","帕特洛克罗斯倒下后，墨涅拉奥斯第一个冲上前护住遗体，与特洛伊人激烈争夺。",
    "Guards his body","When Patroclus falls, Menelaus is the first to stand over the body, fighting the Trojans for it.","卷十七"),
  E("paris","helen","tie","私奔","帕里斯从斯巴达带走海伦，引发十年战争。海伦当面讥讽他临阵脱逃，却仍留在他身边。",
    "Eloped","Paris took Helen from Sparta and started a ten-year war. She mocks him to his face for running from the fight, yet stays with him.","卷三、卷六"),
  E("paris","hector","kin","兄弟","赫克托尔骂他“空有一副好相貌”，为他的怯懦感到羞耻，却不得不替他打这场仗。",
    "Brothers","Hector calls him a pretty face and nothing more, ashamed of his cowardice, yet must fight his war for him.","卷三、卷六"),
  E("paris","priam","kin","父子","有人提议交还海伦，帕里斯只肯赔财宝、不肯交人，普里阿摩斯同意照他的意思去谈。",
    "Father–son","When it is proposed to give Helen back, Paris will return the treasure but not the woman, and Priam lets his offer stand.","卷七"),
  E("paris","diomedes","foe","射伤","帕里斯躲在墓碑后放箭，射穿狄奥墨得斯的脚掌，迫使他退出战斗。",
    "Wounds him","Hiding behind a grave marker, Paris shoots Diomedes through the foot and puts him out of the fight.","卷十一"),
  E("paris","achilles","foe","注定射杀","赫克托尔临死预言：帕里斯将在阿波罗相助下，于斯开亚门前杀死阿喀琉斯。",
    "Fated killer","The dying Hector foretells that Paris, with Apollo's help, will kill Achilles at the Scaean Gates.","卷二十二"),
  E("hector","andromache","kin","夫妻","城头诀别时她哀求丈夫留下；赫克托尔说他预见了特洛伊的陷落，最痛心的是她将沦为奴隶。",
    "Husband and wife","On the wall she begs him to stay; Hector says he foresees Troy's fall and grieves most at the thought of her led away as a slave.","卷六、卷二十二"),
  E("hector","astyanax","kin","父子","孩子被父亲的盔缨吓哭，赫克托尔摘下头盔，抱起他亲吻，祈祷他将来胜过父亲。",
    "Father–son","The child cries in fright at his father's crest; Hector takes off his helmet, kisses him, and prays he will be a better man than his father.","卷六"),
  E("andromache","astyanax","kin","母子","赫克托尔死后，她预见儿子的命运：要么随她为奴，要么被希腊人从城墙上扔下去。",
    "Mother–son","After Hector's death she foresees her son's fate: slavery with her, or being hurled from the walls by a Greek.","卷二十二、卷二十四"),
  E("hector","priam","kin","父子","老父在城头拔着白发，哀求赫克托尔进城躲避，他没有听从。",
    "Father–son","His old father, tearing his white hair, begs him from the wall to come inside; he does not listen.","卷二十二"),
  E("hector","hecuba","kin","母子","母亲袒露哺育过他的胸脯，哭着求他回城，他仍留在城外等待阿喀琉斯。",
    "Mother–son","His mother bares the breast that nursed him and begs him to come in, but he stays outside to wait for Achilles.","卷二十二"),
  E("priam","hecuba","kin","夫妻","赫卡柏劝丈夫不要冒险去敌营，普里阿摩斯执意前往。",
    "Married","Hecuba begs her husband not to risk going to the enemy camp, but Priam insists.","卷二十四"),
  E("hector","patroclus","foe","杀死","阿波罗击落铠甲后，赫克托尔一枪刺死帕特洛克罗斯，并剥下他身上阿喀琉斯的铠甲。",
    "Kills him","After Apollo strips Patroclus, Hector finishes him with a spear and takes Achilles's armor from his body.","卷十六、卷十七"),
  E("hector","ajax","tie","决斗 · 互赠","两人决斗到天黑不分胜负，赫克托尔赠剑，埃阿斯回赠腰带，友好地各自散去。",
    "Duel and gifts","They fight until nightfall without a winner; Hector gives Ajax a sword, Ajax gives him a belt, and they part as friends.","卷七"),
  E("hector","polydamas","tie","忠告被拒","波吕达马斯劝他退回城里，他斥之为胆怯；阿喀琉斯重返战场后，赫克托尔才后悔没有听从。",
    "Ignored advice","Polydamas urges him to pull back inside the walls and Hector calls it cowardice; once Achilles returns, Hector regrets not listening.","卷十二、卷十八、卷二十二"),
  E("hector","helen","aid","善待","海伦哭悼赫克托尔：别人辱骂她时，只有他从未说过一句刻薄话，还会出言阻止。",
    "Kind to her","Mourning Hector, Helen says he alone never spoke a harsh word to her, and stopped others when they did.","卷六、卷二十四"),
  E("hector","dolon","tie","许诺神驹","赫克托尔发誓，事成后把阿喀琉斯的神驹赏给他，多隆这才自愿出营刺探。",
    "Promises horses","Hector swears to give him Achilles's horses if he succeeds, and Dolon volunteers to spy.","卷十"),
  E("hector","glaucus","tie","斥责","萨尔佩冬死后，格劳科斯斥责赫克托尔见了埃阿斯就退缩，辜负了盟友。",
    "Rebukes him","After Sarpedon's death, Glaucus rebukes Hector for shrinking from Ajax and failing his allies.","卷十七"),
  E("priam","helen","aid","城头问将","普里阿摩斯唤海伦坐到身边，请她指认希腊将领，并说：我不怪你，该怪的是众神。",
    "Kind to her","Priam calls Helen to sit beside him and name the Greek chiefs, saying: I don't blame you; the gods are to blame.","卷三"),
  E("hecuba","athena","tie","献袍被拒","赫卡柏选出最美的袍子，由女祭司放在雅典娜神像的膝上，妇女们祈求女神折断狄奥墨得斯的长矛，女神却摇头拒绝。",
    "Offering refused","Hecuba chooses the finest robe, the priestess lays it on the knees of Athena's statue, and the women pray her to break Diomedes's spear, but the goddess refuses.","卷六"),
  E("sarpedon","glaucus","aid","战友","萨尔佩冬对格劳科斯说：既然人终有一死，不如去赢得荣耀。临死前他托格劳科斯守住自己的遗体。",
    "Comrades","Sarpedon tells Glaucus that since death comes to all, they should win glory; dying, he asks Glaucus to guard his body.","卷十二、卷十六"),
  E("sarpedon","patroclus","foe","被杀","萨尔佩冬迎战帕特洛克罗斯，被刺中心口，像一棵大树般倒下。",
    "Killed by him","Sarpedon faces Patroclus and is speared near the heart, falling like a great tree.","卷十六"),
  E("glaucus","diomedes","aid","世交 · 换甲","阵前通报家世后，两人发现祖辈曾互为宾友，于是握手言欢，交换铠甲：格劳科斯拿价值百头牛的金甲，换了九头牛的铜甲。",
    "Guest-friends","Trading lineages on the battlefield, they learn their grandfathers were guest-friends, so they clasp hands and swap armor: Glaucus's gold, worth a hundred oxen, for bronze worth nine.","卷六"),
  E("pandarus","diomedes","foe","被杀","潘达罗斯射伤狄奥墨得斯的肩膀，又与埃涅阿斯同车来战；狄奥墨得斯的长矛刺中他眼旁的鼻梁，将他杀死。",
    "Killed by him","Pandarus wounds Diomedes in the shoulder, then charges him with Aeneas; Diomedes's spear strikes him beside the eye and kills him.","卷五"),
  E("aeneas","diomedes","foe","巨石砸伤","狄奥墨得斯举起两个人都搬不动的巨石，砸碎了埃涅阿斯的髋骨。",
    "Crushes him","Diomedes lifts a stone two men could not carry and smashes Aeneas's hip.","卷五"),
  E("diomedes","odysseus","aid","夜袭搭档","两人夜探特洛伊营地，擒获多隆，杀死色雷斯王瑞索斯，牵回他的骏马。",
    "Night raid","Together they raid the Trojan lines by night, capture Dolon, kill the Thracian king Rhesus and take his horses.","卷十"),
  E("diomedes","dolon","foe","处死","多隆吐露军情后求饶，狄奥墨得斯仍一剑斩下了他的头。",
    "Kills him","When Dolon has told them everything and begs for his life, Diomedes cuts off his head.","卷十"),
  E("odysseus","dolon","tie","诱供","奥德修斯笑着安慰多隆“别想着死”，套出了特洛伊营地的布防。",
    "Interrogates","Odysseus smiles and tells Dolon not to think of death, and draws out the layout of the Trojan camp.","卷十"),
  E("odysseus","thersites","foe","杖责","奥德修斯怒斥忒尔西特斯，用王杖打他的背，打得他缩在一旁掉泪，众人都叫好。",
    "Beats him","Odysseus rebukes Thersites and strikes his back with the scepter until he cowers in tears, to the army's delight.","卷二"),
  E("odysseus","chryses","aid","送还女儿","奥德修斯率船把克律塞伊斯送回克律塞，祭司随即祈求阿波罗停止瘟疫。",
    "Returns his daughter","Odysseus sails to Chryse with Chryseis; the priest then prays to Apollo to end the plague.","卷一"),
  E("nestor","antilochus","kin","父子","赛车前，涅斯托尔教儿子如何在转弯标柱处取胜。",
    "Father–son","Before the chariot race, Nestor teaches his son how to win at the turning post.","卷二十三"),
  E("nestor","patroclus","tie","献计","涅斯托尔劝帕特洛克罗斯说服阿喀琉斯出战，不行就借他的铠甲出阵吓退敌人。这一计让帕特洛克罗斯走向了死亡。",
    "Fatal advice","Nestor urges Patroclus to persuade Achilles to fight, or else to borrow his armor and frighten the Trojans; the plan leads Patroclus to his death.","卷十一"),
  E("chryses","chryseis","kin","父女","他带着无数赎礼来赎女儿，最终由奥德修斯把她送回。",
    "Father–daughter","He brings a boundless ransom for his daughter; in the end Odysseus brings her home.","卷一"),
  E("briseis","patroclus","aid","温和的人","布里塞伊斯扑在他的遗体上痛哭：她被俘时，是帕特洛克罗斯安慰她，许诺让她成为阿喀琉斯的妻子，他待人总是那样温和。",
    "Kind to her","Briseis throws herself on his body and weeps: when she was captured, he comforted her and promised she would be Achilles's wife; he was always gentle.","卷十九"),
]

EDGE_TYPES = {
  "kin": dict(zh="亲缘", en="Kin", desc="血缘与婚姻", desc_en="Blood and marriage"),
  "aid": dict(zh="友助", en="Ally", desc="庇护、相助、友谊与忠诚", desc_en="Protection, help, friendship, loyalty"),
  "foe": dict(zh="敌对", en="Enemy", desc="交战、加害、欺骗", desc_en="Combat, harm, deception"),
  "tie": dict(zh="纠葛", en="Entangled", desc="恩怨交织、争夺、胁迫与命运", desc_en="Mixed motives, rivalry, coercion, fate"),
}
