# -*- coding: utf-8 -*-
"""Journey to the West (西游记): characters and relationships, Chinese and English.
cat:   god (buddhas, bodhisattvas, heavenly gods, immortals, dragon kings)
       demi (a deity reborn as a mortal) / demimon (between god and demon) / mortal / monster
camp:  buddha / heaven / dragon / pilgrim / tang / gao / baoxiang / wuji / women (places of mortals)
       backed (a demon with a patron in heaven) / wild (a demon on its own)
dies:  chapter in which the character is killed, or None
py:    pinyin
Chapter numbers (回) follow the standard 100-chapter text.
"""

N = lambda **k: k

NODES = [
  # ------------------------------------------------------------------ the pilgrims
  N(id="tangseng", zh="唐僧", py="Táng Sēng", en="Tang Sanzang", cat="demi", camp="pilgrim", dies=None,
    sub=("取经人 · 金蝉子转世", "Tripitaka, the pilgrim monk"),
    bio=("法名玄奘，唐太宗的御弟，号三藏。他本是如来的二弟子金蝉子，因轻慢佛法被贬下凡。他奉旨西行，一路被妖怪当作“吃一块肉可以长生”的唐僧肉；他心慈耳软，两次赶走孙悟空。取经成功后，被封为旃檀功德佛。",
         "The monk Xuanzang, sworn brother of Emperor Taizong, who names him Sanzang, “Tripitaka”. He was once the Buddha’s second disciple, Golden Cicada, banished to be reborn for slighting the Buddha’s teaching. Every demon on the road wants a bite of him, since his flesh is said to grant long life; soft-hearted and easily swayed, he twice sends Sun Wukong away. At the end he becomes the Buddha of Candana Merit."),
    icon=("毗卢帽、锦襕袈裟与九环锡杖——袈裟和锡杖是观音送到长安、经唐太宗转赠的。", "Vairocana crown, brocade cassock and nine-ringed staff; the cassock and staff were Guanyin’s gifts, passed on by the emperor.")),
  N(id="wukong", zh="孙悟空", py="Sūn Wùkōng", en="Sun Wukong", cat="demimon", camp="pilgrim", dies=None,
    sub=("美猴王 · 齐天大圣", "The Monkey King"),
    bio=("花果山仙石迸出的石猴。他拜菩提祖师学会七十二变和筋斗云，从龙宫取来金箍棒，自封齐天大圣，大闹天宫，被如来压在五行山下五百年。唐僧揭去封帖救他出山，他一路降妖除魔，最后被封为斗战胜佛。",
         "A monkey born from a magic stone on the Mountain of Flowers and Fruit. He learns the seventy-two transformations and the cloud somersault from Patriarch Subodhi, takes his iron staff from the Dragon King, calls himself Great Sage Equal to Heaven and wreaks havoc in Heaven, until the Buddha pins him under the Mountain of Five Elements for five hundred years. Freed by Tang Sanzang, he fights his way west and becomes the Victorious Fighting Buddha."),
    icon=("紧箍、火眼金睛与如意金箍棒。", "The golden headband, fiery golden eyes and the gold-banded staff.")),
  N(id="bajie", zh="猪八戒", py="Zhū Bājiè", en="Zhu Bajie", cat="demimon", camp="pilgrim", dies=None,
    sub=("天蓬元帅 · 二师兄", "Pigsy, once Marshal of the Heavenly Reeds"),
    bio=("本是天河的天蓬元帅，因酒后调戏嫦娥被贬下凡，错投猪胎。观音为他取法名悟能，唐僧又叫他八戒。他贪吃好色，爱偷懒、爱挑拨，却也力大憨直，一路扛着九齿钉钯。取经后被封为净坛使者。",
         "Once Marshal of the Heavenly Reeds, commander of the Milky Way, banished for making drunken advances to Chang’e and reborn by mistake in a sow’s womb. Guanyin names him Wuneng; Tang Sanzang calls him Bajie, “Eight Precepts”. Greedy, lustful, lazy and a troublemaker, he is also strong and good-natured, and carries a nine-toothed rake. At the end he is made Cleanser of the Altars."),
    icon=("猪头大耳与九齿钉钯。", "Pig’s head, big ears and the nine-toothed rake.")),
  N(id="shaseng", zh="沙僧", py="Shā Sēng", en="Sha Wujing", cat="demimon", camp="pilgrim", dies=None,
    sub=("卷帘大将 · 三师弟", "Sandy, once the Curtain-Lifting General"),
    bio=("本是天宫的卷帘大将，在蟠桃会上失手打碎玻璃盏，被打了八百下，贬到流沙河，每七天还要受飞剑穿胸之苦。他在河中吃人，把九个取经人的骷髅串成项链。观音为他取名悟净；他最忠厚任劳，取经后被封为金身罗汉。",
         "Once the Curtain-Lifting General of Heaven, he broke a crystal cup at the Peach Banquet, was given eight hundred lashes and exiled to the Flowing Sand River, where a flying sword pierced his side every seven days. He ate travelers there and strung the skulls of nine pilgrims into a necklace. Guanyin names him Wujing; the most loyal and hard-working of the disciples, he becomes a Golden-Bodied Arhat."),
    icon=("光头、赤须、骷髅项链与降妖宝杖。", "Shaved head, red beard, a necklace of skulls and the demon-quelling staff.")),
  N(id="horse", zh="白龙马", py="Bái Lóng Mǎ", en="White Dragon Horse", cat="demimon", camp="pilgrim", dies=None,
    sub=("西海龙王三太子", "Third son of the Dragon King of the West Sea"),
    bio=("西海龙王敖闰的三太子，纵火烧了殿上的明珠，被父亲告了忤逆，险些被斩。观音救下他，让他在鹰愁涧等候取经人；他吃了唐僧的白马，又被观音变成白马，驮唐僧走完全程。取经后被封为八部天龙马。",
         "Third son of Ao Run, Dragon King of the West Sea. He set fire to the pearls in his father’s palace, was charged with disobedience by his own father and nearly executed. Guanyin saves him and has him wait at Eagle Grief Stream; he eats Tang Sanzang’s horse, and Guanyin turns him into a white horse to carry the monk all the way west. At the end he becomes a Heavenly Dragon of the Eight Classes."),
    icon=("白马，鬃如龙鳞。", "A white horse with a mane like dragon scales.")),
  # ------------------------------------------------------------------ the Buddhist world
  N(id="rulai", zh="如来佛祖", py="Rúlái Fózǔ", en="The Buddha", cat="god", camp="buddha", dies=None,
    sub=("西天灵山之主", "Lord of Vulture Peak in the West"),
    bio=("西天灵山雷音寺的佛祖。他与孙悟空打赌，悟空翻不出他的手掌，被压在五行山下；他派观音去东土寻找取经人，又一眼认出六耳猕猴。取经人到了灵山，他的弟子阿傩、伽叶却先向他们讨要“人事”。",
         "The Buddha of the Thunderclap Monastery on Vulture Peak in the West. He wagers that Sun Wukong cannot leap out of his palm, and when Wukong fails, pins him under a mountain; he sends Guanyin east to find a pilgrim, and he alone can tell the Six-Eared Macaque apart. When the pilgrims finally arrive, his disciples Ananda and Kasyapa first ask them for a “gift”."),
    icon=("螺发、长耳与翻掌——孙悟空翻不出的那只手掌。", "Curled hair, long earlobes and an open palm: the hand Sun Wukong could not escape.")),
  N(id="guanyin", zh="观音菩萨", py="Guānyīn Púsà", en="Guanyin", cat="god", camp="buddha", dies=None,
    sub=("南海普陀落伽山的菩萨", "Bodhisattva of the Southern Sea"),
    bio=("大慈大悲的菩萨，取经的总策划。她奉如来之命东行，一路收下悟空、八戒、沙僧、白龙马，选中玄奘；她把三个箍儿分给了悟空、黑熊精和红孩儿。许多难关要靠她出面解救，而好几个妖怪，恰恰是从她身边跑出去的。",
         "The compassionate bodhisattva who plans the whole pilgrimage. Sent east by the Buddha, she recruits Wukong, Bajie, Sha Wujing and the dragon horse and chooses Xuanzang; she gives her three magic hoops to Wukong, the Black Bear and Red Boy. Many ordeals end only when she steps in, and several of the demons turn out to have slipped away from her own household."),
    icon=("白衣头巾、净瓶与杨柳枝。", "White hood, a vase of pure water and a willow sprig.")),
  N(id="maitreya", zh="弥勒佛", py="Mílè Fó", en="Maitreya", cat="god", camp="buddha", dies=None,
    sub=("东来佛祖 · 笑和尚", "The Laughing Buddha of the future"),
    bio=("未来佛，笑口常开。他的司磬童子偷了金铙和人种袋，在小雷音寺假扮佛祖；他扮作种瓜老汉，用一只熟瓜引妖怪吞下变成瓜的悟空，才把童子收回。",
         "The Buddha of the future, always laughing. His chime-keeping page steals his golden cymbals and his “human seed” sack and poses as the Buddha in the Lesser Thunderclap Monastery; Maitreya disguises himself as a melon farmer and tricks the demon into eating a ripe melon that is Wukong in disguise, then takes his page home."),
    icon=("光头大耳、笑口与布袋。", "Bald head, big ears, laughing mouth and his cloth sack.")),
  N(id="manjushri", zh="文殊菩萨", py="Wénshū Púsà", en="Manjushri", cat="god", camp="buddha", dies=None,
    sub=("智慧菩萨", "Bodhisattva of wisdom"),
    bio=("智慧的菩萨，坐骑是青毛狮子。乌鸡国王曾把化作凡僧的文殊浸在御水河里三天三夜，如来便派他的狮子把国王推下井三年作为报应。后来他的狮子又在狮驼岭作乱。",
         "The bodhisattva of wisdom, who rides a green-maned lion. The king of Wuji once dunked him, disguised as an ordinary monk, in the palace moat for three days and nights, so the Buddha sent his lion to push the king down a well for three years. Later the same lion runs wild at Lion-Camel Ridge."),
    icon=("宝冠与智慧剑。", "Jeweled crown and the sword of wisdom.")),
  N(id="samantabhadra", zh="普贤菩萨", py="Pǔxián Púsà", en="Samantabhadra", cat="god", camp="buddha", dies=None,
    sub=("行愿菩萨", "Bodhisattva of practice"),
    bio=("以行愿著称的菩萨，坐骑是六牙白象。他的白象下界，在狮驼岭做了二大王；如来降伏大鹏之后，普贤念动真言，白象现出原形，被他骑回。",
         "The bodhisattva of practice and vows, who rides a white elephant. His elephant comes down to earth and becomes the second demon king of Lion-Camel Ridge; after the Buddha subdues the roc, Samantabhadra chants a spell, and the elephant shows its true form and carries him home."),
    icon=("宝冠与如意。", "Jeweled crown and a ruyi scepter.")),
  N(id="lingji", zh="灵吉菩萨", py="Língjí Púsà", en="Bodhisattva Lingji", cat="god", camp="buddha", dies=None,
    sub=("小须弥山的菩萨", "Bodhisattva of Little Sumeru"),
    bio=("住在小须弥山的菩萨，受如来之托看管黄风怪，持有如来赐的定风丹和飞龙宝杖。他用宝杖降伏黄风怪；后来又把定风丹送给悟空，让他不怕铁扇公主的芭蕉扇。",
         "A bodhisattva on Little Mount Sumeru, charged by the Buddha with keeping the Yellow Wind Demon in check, with a wind-fixing pill and a flying-dragon staff from the Buddha. He subdues the demon with the staff, and later gives Wukong the pill so that Princess Iron Fan’s fan can no longer blow him away."),
    icon=("飞龙宝杖。", "The flying-dragon staff.")),
  # ------------------------------------------------------------------ Heaven and the immortals
  N(id="jade", zh="玉皇大帝", py="Yùhuáng Dàdì", en="The Jade Emperor", cat="god", camp="heaven", dies=None,
    sub=("天庭之主", "Ruler of Heaven"),
    bio=("天庭的统治者。他先封孙悟空为弼马温，又封他为有名无权的齐天大圣；悟空大闹天宫，他请来如来才平定。天蓬元帅、卷帘大将、西海三太子、奎木狼都是被他贬罚的。",
         "The ruler of Heaven. He first makes Sun Wukong keeper of the heavenly horses, then Great Sage Equal to Heaven, a title without power; when Wukong wrecks Heaven, he must send for the Buddha. The Marshal of the Heavenly Reeds, the Curtain-Lifting General, the West Sea dragon prince and the Wolf Star are all punished by him."),
    icon=("冕旒——前后垂珠的帝王冠。", "The emperor’s flat-topped crown hung with strings of beads.")),
  N(id="queenmother", zh="王母娘娘", py="Wángmǔ Niángniáng", en="The Queen Mother", cat="god", camp="heaven", dies=None,
    sub=("瑶池蟠桃会的主人", "Hostess of the Peach Banquet"),
    bio=("瑶池的女神，蟠桃园的主人。她的蟠桃三千年、六千年、九千年一熟，吃了能长生；悟空看守蟠桃园时偷吃了大半，又搅了蟠桃会。卷帘大将也是在她的蟠桃会上打碎了玻璃盏。",
         "The goddess of the Jade Pool, owner of the peach orchard whose peaches ripen once in three, six or nine thousand years and grant long life. Put in charge of the orchard, Wukong eats most of the peaches and ruins her banquet. It is at the same banquet that the Curtain-Lifting General breaks the crystal cup."),
    icon=("凤冠与蟠桃。", "Phoenix crown and a peach of immortality.")),
  N(id="laojun", zh="太上老君", py="Tàishàng Lǎojūn", en="Laozi", cat="god", camp="heaven", dies=None,
    sub=("兜率宫的道祖", "The Most High Lord Lao"),
    bio=("兜率宫的道祖，炼丹的宗师。悟空偷吃了他的金丹，又在他的八卦炉里炼出火眼金睛；他用金刚琢打中悟空的头，助二郎神擒住大圣。他的青牛、看炉的金角银角两个童子都下界成了妖，每次都由他亲自收回。",
         "The Daoist patriarch of the Tushita Palace, master of the elixir. Wukong gobbles his golden pills and, locked in his eight-trigram furnace, comes out with fiery golden eyes; Laozi’s diamond snare strikes Wukong on the head and helps Erlang capture him. His green ox and the two boys who tend his furnaces, Golden Horn and Silver Horn, all go down to earth as demons, and each time he comes to take them back himself."),
    icon=("白须、道冠与金刚琢。", "White beard, a Daoist crown and the diamond snare.")),
  N(id="jinxing", zh="太白金星", py="Tàibái Jīnxīng", en="Gold Star of Venus", cat="god", camp="heaven", dies=None,
    sub=("天庭的和事佬", "Heaven’s peacemaker"),
    bio=("白发的老神仙，天庭里的好好先生。他两次向玉帝提议招安孙悟空，又亲自下界请他上天；取经路上，他化作老人在双叉岭救出唐僧，又在狮驼岭前报信，提醒妖魔厉害。",
         "A white-haired old immortal, the kindest voice in Heaven. Twice he persuades the Jade Emperor to offer Sun Wukong a post instead of fighting him, and goes down himself to invite him up. On the road he takes the form of an old man to rescue Tang Sanzang at Double Fork Ridge, and later warns the pilgrims about the demons of Lion-Camel Ridge."),
    icon=("白发、白须与拂尘。", "White hair, white beard and a horsehair whisk.")),
  N(id="erlang", zh="二郎神", py="Èrláng Shén", en="Erlang Shen", cat="god", camp="heaven", dies=None,
    sub=("显圣真君 · 玉帝外甥", "The True Lord, nephew of the Jade Emperor"),
    bio=("玉帝的外甥，住在灌江口，额上生有神眼。天兵拿不住悟空，观音便推荐了他；他与悟空变化斗法，在老君的金刚琢和哮天犬相助下擒住大圣。后来他打猎路过碧波潭，又帮悟空打败九头虫。",
         "The Jade Emperor’s nephew, who lives at Guanjiang and has a third eye in his forehead. When Heaven’s armies cannot take Wukong, Guanyin recommends him; the two fight a duel of transformations, and with Laozi’s snare and his hunting dog he captures the Great Sage. Years later, passing by on a hunt, he helps Wukong defeat the Nine-Headed Bug."),
    icon=("额上的神眼与三尖两刃刀。", "The eye in his forehead and his three-pointed, double-edged blade.")),
  N(id="lijing", zh="李靖", py="Lǐ Jìng", en="Li Jing", cat="god", camp="heaven", dies=None,
    sub=("托塔天王", "The Pagoda-Bearing Heavenly King"),
    bio=("天庭的元帅，手托宝塔，哪吒的父亲。他率天兵围剿花果山；取经路上又奉命捉拿牛魔王。他曾收一只偷香油的老鼠精为义女，后来被悟空拿着牌位告到玉帝面前。",
         "Heaven’s commander, who holds a pagoda in his hand, and father of Nezha. He leads the heavenly army against the Mountain of Flowers and Fruit, and on the road is sent to capture the Bull Demon King. He once took in a mouse spirit who had stolen lamp oil as his adopted daughter, and Wukong later brings her memorial tablet to the Jade Emperor as evidence against him."),
    icon=("盔甲、长须与玲珑宝塔。", "Armor, a long beard and his pagoda.")),
  N(id="nezha", zh="哪吒", py="Nézhā", en="Nezha", cat="god", camp="heaven", dies=None,
    sub=("三太子", "The Third Prince"),
    bio=("李靖的三儿子，能变三头六臂。他在花果山与悟空交手落败；火焰山之战，他砍下牛魔王的头又生出新头，最后用火轮烧、缚妖索穿鼻，擒住牛魔王。老鼠精拜李靖为父，也就认他做了哥哥。",
         "Li Jing’s third son, who can grow three heads and six arms. He loses to Wukong at the Mountain of Flowers and Fruit; at the Flaming Mountains he cuts off the Bull Demon King’s head, only to see a new one grow, and finally takes him with fire wheels and a demon-binding rope through the nose. When the mouse spirit takes Li Jing as her father, she takes Nezha as her brother."),
    icon=("双髻、乾坤圈与混天绫。", "Twin hair buns, the universe ring and a red silk sash.")),
  N(id="change", zh="嫦娥", py="Cháng'é", en="Chang'e", cat="god", camp="heaven", dies=None,
    sub=("广寒宫的仙子", "Goddess of the moon palace"),
    bio=("月宫广寒宫的仙子。天蓬元帅酒后调戏嫦娥，被贬下界，成了猪八戒；天竺国的假公主是广寒宫捣药的玉兔，太阴星君带着嫦娥们下界把它收回，八戒见了又忍不住上前拉扯。",
         "A goddess of the Palace of Great Cold on the moon. The Marshal of the Heavenly Reeds makes drunken advances to Chang’e and is banished to become Zhu Bajie; the false princess of India is the jade rabbit that pounds medicine in the moon palace, and when the Moon Goddess comes down with her ladies to take it back, Bajie cannot help grabbing at them again."),
    icon=("高髻、飘带与一弯新月。", "High hairdo, floating ribbons and a crescent moon.")),
  N(id="zhenyuan", zh="镇元子", py="Zhènyuán Zǐ", en="Master Zhenyuan", cat="god", camp="heaven", dies=None,
    sub=("地仙之祖", "Patriarch of the Earth Immortals"),
    bio=("万寿山五庄观的主人，地仙之祖。他的人参果树九千年才结三十个果，闻一闻活三百六十岁；他与金蝉子是旧相识，特意留果招待唐僧。悟空偷果不成，一怒推倒果树；观音用净瓶甘露救活果树后，镇元子与悟空结为兄弟。",
         "Master of the Five Villages Abbey on Longevity Mountain, patriarch of the earth immortals. His ginseng tree bears thirty fruits every nine thousand years, and one sniff gives 360 years of life; an old acquaintance of Golden Cicada, he saves two fruits for Tang Sanzang. After a quarrel over stolen fruit, Wukong knocks the tree down; once Guanyin revives it with the dew from her vase, Zhenyuan and Wukong become sworn brothers."),
    icon=("道冠、长须与形似婴儿的人参果。", "A Daoist crown, long beard and a ginseng fruit shaped like a baby.")),
  N(id="subodhi", zh="菩提祖师", py="Pútí Zǔshī", en="Patriarch Subodhi", cat="god", camp="heaven", dies=None,
    sub=("悟空的师父", "Wukong’s first teacher"),
    bio=("灵台方寸山斜月三星洞的祖师。他给石猴取名孙悟空，在他头上敲了三下，暗示他三更天来后门学艺，传他长生之道、七十二变和筋斗云。悟空卖弄本事，他便把他逐出师门，不许他说出师父是谁。",
         "The patriarch of the Cave of the Slanting Moon and Three Stars. He names the stone monkey Sun Wukong, taps him three times on the head as a secret sign to come to the back door at the third watch, and teaches him the way of long life, the seventy-two transformations and the cloud somersault. When Wukong shows off, he expels him and forbids him ever to say who his teacher was."),
    icon=("白须道人与戒尺。", "A white-bearded Daoist with a teacher’s ruler.")),
  N(id="aoguang", zh="东海龙王", py="Dōnghǎi Lóngwáng", en="East Sea Dragon King", cat="god", camp="dragon", dies=None,
    sub=("敖广", "Ao Guang"),
    bio=("东海龙宫的龙王敖广，四海龙王之首。悟空到龙宫借兵器，扛走了镇海的定海神针（如意金箍棒），龙王告到天庭；悟空第一次离开唐僧时，也是在他的龙宫里，被一幅“圯桥进履”的画劝了回去。",
         "Ao Guang, Dragon King of the East Sea and eldest of the four sea dragons. Wukong comes to borrow a weapon and walks off with the iron pillar that steadies the sea, the gold-banded staff, and the Dragon King takes his complaint to Heaven. When Wukong first walks out on Tang Sanzang, it is in this dragon palace that a painting of a young man patiently fetching an old man’s shoe persuades him to go back."),
    icon=("龙首、官帽与笏板。", "A dragon’s head, an official’s hat and a court tablet.")),
  N(id="aorun", zh="西海龙王", py="Xīhǎi Lóngwáng", en="West Sea Dragon King", cat="god", camp="dragon", dies=None,
    sub=("敖闰", "Ao Run"),
    bio=("西海龙王敖闰，东海龙王的弟弟。他的三太子烧了殿上明珠，被他告了忤逆，后来成了白龙马；他的外甥鼍龙在黑水河作怪捉了唐僧，他派儿子摩昂太子把外甥锁了回来。",
         "Ao Run, Dragon King of the West Sea and brother of the East Sea king. His third son burns the pearls in his palace and is charged by his own father with disobedience, later becoming the white dragon horse; when his nephew the Alligator Dragon seizes Tang Sanzang at the Black River, he sends his son Prince Mo’ang to bring the nephew back in chains."),
    icon=("龙首、王冠与宝珠——三太子烧掉的正是殿上的明珠。", "A dragon’s head, a crown and a pearl: his son burned the pearls of his palace.")),
  # ------------------------------------------------------------------ mortals
  N(id="taizong", zh="唐太宗", py="Táng Tàizōng", en="Emperor Taizong", cat="mortal", camp="tang", dies=None,
    sub=("大唐皇帝", "Emperor of Tang"),
    bio=("大唐皇帝李世民。他许诺救泾河龙王却没救成，被龙王冤魂纠缠，魂游地府，还阳后举办水陆大会超度亡魂。观音在会上显圣，他便派玄奘西天取经，与他结为兄弟，称他御弟，赐号三藏。",
         "Li Shimin, Emperor of Tang. He promises to save the Jing River Dragon King, fails, is haunted by the dragon’s ghost and visits the underworld; restored to life, he holds a great mass for the souls of the dead. When Guanyin appears at the mass, he sends Xuanzang west for the scriptures, swears brotherhood with him and gives him the name Sanzang."),
    icon=("幞头与龙袍。", "A black gauze hat and a dragon robe.")),
  N(id="cuilan", zh="高翠兰", py="Gāo Cuìlán", en="Gao Cuilan", cat="mortal", camp="gao", dies=None,
    sub=("高老庄的三小姐", "Daughter of the Gao family farm"),
    bio=("高老庄高太公的三女儿。猪八戒化作一个黑胖汉子入赘高家，干活勤快，后来却露出猪相，把她关在后院半年不让见家人。悟空变成翠兰的模样，在房里等八戒回来。",
         "Third daughter of old Mr. Gao of Gao Village. Zhu Bajie marries into the family as a dark, hefty, hard-working son-in-law, then shows his pig’s face and keeps her shut in the back rooms for half a year. Sun Wukong takes her shape and waits for Bajie in her room."),
    icon=("发髻与花簪。", "Hair bun and flower pin.")),
  N(id="baihuaxiu", zh="百花羞", py="Bǎihuāxiū", en="Princess Baihuaxiu", cat="demi", camp="baoxiang", dies=None,
    sub=("宝象国三公主", "Third princess of Baoxiang"),
    bio=("宝象国的三公主，原是天宫披香殿侍香的玉女，思凡下界投胎为公主。她被黄袍怪掳去做了十三年夫人。她偷偷放走唐僧，托他给父王带去家书，才引出后面的救援。",
         "Third princess of Baoxiang, in a former life a jade maiden who tended the incense in a hall of Heaven and came down to be reborn. The Yellow Robe Demon carries her off and keeps her as his wife for thirteen years. She secretly frees Tang Sanzang and gives him a letter for her father, which sets the rescue in motion."),
    icon=("凤钗与家书。", "A phoenix hairpin and her letter home.")),
  N(id="wujiking", zh="乌鸡国王", py="Wūjī Guówáng", en="King of Wuji", cat="mortal", camp="wuji", dies=None,
    sub=("被推下井的国王", "The king drowned in a well"),
    bio=("乌鸡国的国王，被一个全真道士推进御花园的井里，道士变成他的模样做了三年国王。他的冤魂托梦给唐僧求救；悟空用老君的九转还魂丹救活了他。原来那道士是文殊的青狮，因为国王当年把化成凡僧的文殊浸了三天三夜。",
         "The king of Wuji, pushed into a well in his palace garden by a Daoist who then rules in his shape for three years. His ghost comes to Tang Sanzang in a dream to beg for help, and Wukong revives him with one of Laozi’s nine-times-refined pills. The Daoist is Manjushri’s lion, sent because the king had once dunked Manjushri, disguised as a monk, for three days and nights."),
    icon=("王冠与水珠——他在井底泡了三年。", "A crown and drops of water: he lay three years at the bottom of a well.")),
  N(id="womanking", zh="女儿国国王", py="Nǚ'érguó Guówáng", en="Queen of the Women's Kingdom", cat="mortal", camp="women", dies=None,
    sub=("西梁女国的国王", "Ruler of the Kingdom of Women"),
    bio=("西梁女国的女王，国中只有女子。她愿以一国之富招唐僧为夫，让他做国王。悟空定下“假亲脱网”之计：唐僧假意答应，骗她在通关文牒上盖了印，送出城外后才告辞离开。",
         "The queen of the Kingdom of Women, where there are no men. She offers Tang Sanzang her whole kingdom if he will marry her and rule. Wukong’s plan is a false engagement: the monk pretends to agree, she stamps his travel papers with her seal, and only when she has seen him out of the city does he take his leave."),
    icon=("王冠与国印——她在通关文牒上盖的印。", "A crown and the royal seal she stamps on his travel papers.")),
  # ------------------------------------------------------------------ demons
  N(id="bull", zh="牛魔王", py="Niú Mówáng", en="Bull Demon King", cat="monster", camp="wild", dies=None,
    sub=("平天大圣 · 悟空的结拜大哥", "Wukong’s sworn elder brother"),
    bio=("大力牛魔王，悟空当年结拜的七兄弟之首。他的妻子是铁扇公主，儿子是红孩儿，却撇下妻子，到积雷山做了玉面公主的上门女婿。悟空借芭蕉扇，与他斗智斗法；最后李靖、哪吒率天兵和佛门护法将他擒住，牵归佛门。",
         "The mighty Bull Demon King, eldest of the seven sworn brothers of Wukong’s youth. His wife is Princess Iron Fan and his son is Red Boy, but he has left them to live with Princess Jade Face on Accumulated Thunder Mountain. When Wukong needs the palm-leaf fan, the two fight a battle of tricks and transformations; in the end Li Jing, Nezha and Buddhist guardians capture him and lead him away to the Buddha."),
    icon=("牛头、双角与混铁棍。", "Bull’s head, two horns and an iron club.")),
  N(id="ironfan", zh="铁扇公主", py="Tiěshàn Gōngzhǔ", en="Princess Iron Fan", cat="monster", camp="wild", dies=None,
    sub=("罗刹女", "The Raksasi"),
    bio=("牛魔王的妻子，红孩儿的母亲，住在翠云山芭蕉洞。她的芭蕉扇能扇灭火焰山的火，一扇就把悟空扇到五万多里外。她恨悟空害她母子分离，不肯借扇；悟空变成小虫钻进她肚里，又变成牛魔王，三番五次才借到扇子。最后她交出扇子，隐姓修行。",
         "Wife of the Bull Demon King and mother of Red Boy, living in Palm Leaf Cave. Her palm-leaf fan can put out the Flaming Mountains, and one wave blows Wukong more than fifty thousand li away. She blames Wukong for taking her son away and will not lend it; Wukong gets inside her belly as an insect and later poses as her husband, and it takes three attempts to get the fan. In the end she gives it up and goes away to practice the Way."),
    icon=("芭蕉扇。", "The palm-leaf fan.")),
  N(id="redboy", zh="红孩儿", py="Hóng Hái'ér", en="Red Boy", cat="monster", camp="wild", dies=None,
    sub=("圣婴大王", "The Great King Holy Child"),
    bio=("牛魔王和铁扇公主的儿子，火云洞的圣婴大王，会吐三昧真火，连四海龙王的雨都浇不灭，把悟空烧得昏死过去。观音用天罡刀化成的莲台和五个金箍降伏了他，收为善财童子。",
         "Son of the Bull Demon King and Princess Iron Fan, the Great King Holy Child of Fire Cloud Cave. He breathes a samadhi fire that even the rain of the four dragon kings cannot put out, and burns Wukong until he faints. Guanyin traps him on a lotus throne of blades and binds him with five gold hoops, then takes him as her page, the Boy of Good Fortune."),
    icon=("童子发髻、火尖枪与火焰。", "A child’s tufted hair, a fire-tipped spear and flames.")),
  N(id="jadeface", zh="玉面公主", py="Yùmiàn Gōngzhǔ", en="Princess Jade Face", cat="monster", camp="wild", dies="第六十一回",
    sub=("牛魔王的妾", "The Bull Demon King’s second wife"),
    bio=("积雷山摩云洞万岁狐王的女儿，招牛魔王做了上门女婿。悟空来请牛魔王，她出言不逊，被悟空追得跑回洞里哭诉。火焰山大战时，她被猪八戒一钯打死，现出原形，是一只玉面狸。",
         "Daughter of the Myriad-Year Fox King of Cloud-Touching Cave, who took the Bull Demon King as her husband. When Wukong comes looking for the Bull, she insults him and runs home in tears when he chases her. In the battle of the Flaming Mountains Zhu Bajie kills her with his rake; her true form is a jade-faced civet."),
    icon=("白如玉的脸与珠翠。", "A face white as jade, and pearl hair ornaments.")),
  N(id="whitebone", zh="白骨精", py="Báigǔ Jīng", en="White Bone Demon", cat="monster", camp="wild", dies="第二十七回",
    sub=("尸魔 · 白骨夫人", "The corpse demon, Lady White Bone"),
    bio=("白虎岭上一具成精的白骨。她三次变化——送饭的村姑、寻女的老妇、寻妻女的老翁——想骗唐僧，都被悟空识破打死。八戒在旁挑唆，唐僧认定悟空滥杀无辜，写下贬书把他赶走。",
         "A skeleton on White Tiger Ridge that has become a demon. Three times she takes a new shape to get at Tang Sanzang, a village girl bringing food, an old woman looking for her daughter, an old man looking for his family, and three times Wukong sees through her and strikes her down. With Bajie egging him on, Tang Sanzang decides Wukong is killing innocent people, writes a letter of dismissal and drives him away."),
    icon=("白骨与发簪。", "Bare bone and a hairpin.")),
  N(id="yellowrobe", zh="黄袍怪", py="Huángpáo Guài", en="Yellow Robe Demon", cat="demimon", camp="backed", dies=None,
    sub=("奎木狼下界", "The Wolf Star in demon form"),
    bio=("本是天上二十八宿中的奎木狼。披香殿的玉女思凡投胎为宝象国公主，他便私自下界，把公主掳到碗子山波月洞做了十三年夫妻。他把唐僧变成老虎，赶走悟空后的取经队伍束手无策。悟空回来揭穿他的身份，玉帝把他召回，罚去给老君烧火。",
         "Really the Wolf Star, one of the twenty-eight lunar mansions. When a jade maiden of Heaven is reborn as the princess of Baoxiang, he slips down to earth, carries her off and lives with her for thirteen years. He turns Tang Sanzang into a tiger, and without Wukong the pilgrims are helpless. Wukong comes back and exposes him; the Jade Emperor recalls him and sets him to tending Laozi’s furnace."),
    icon=("青脸獠牙、红发与黄袍。", "Blue face, fangs, red hair and a yellow robe.")),
  N(id="goldhorn", zh="金角大王", py="Jīnjiǎo Dàwáng", en="Golden Horn", cat="monster", camp="backed", dies=None,
    sub=("平顶山莲花洞大王", "Elder demon king of Lotus Flower Cave"),
    bio=("平顶山莲花洞的大魔头，原是太上老君看金炉的童子。他与兄弟银角偷了老君的五件宝贝下界：紫金红葫芦、羊脂玉净瓶、芭蕉扇、七星剑和幌金绳。老君说，这是观音向他借了三次，派来考验取经人的。",
         "The elder demon king of Lotus Flower Cave on Flat Top Mountain, really the boy who tends Laozi’s gold furnace. With his brother Silver Horn he comes down with five of Laozi’s treasures: a red gourd, a jade vase, a palm-leaf fan, a seven-star sword and a golden rope. Laozi says Guanyin asked him three times to lend them, to test the pilgrims."),
    icon=("金角与七星剑。", "A golden horn and the seven-star sword.")),
  N(id="silverhorn", zh="银角大王", py="Yínjiǎo Dàwáng", en="Silver Horn", cat="monster", camp="backed", dies=None,
    sub=("金角的兄弟", "Golden Horn’s brother"),
    bio=("老君看银炉的童子，金角的弟弟。他搬来三座大山压住悟空，又拿紫金红葫芦叫悟空的名字——谁答应就被收进去。悟空化名“者行孙”“行者孙”应声，还是被装了进去，最后骗得葫芦，反把银角装了进去。",
         "The boy who tends Laozi’s silver furnace, Golden Horn’s younger brother. He crushes Wukong under three mountains and later calls his name with the red gourd, which swallows anyone who answers. Wukong answers to made-up names and is sucked in anyway, but in the end tricks him out of the gourd and traps Silver Horn in it instead."),
    icon=("银角与紫金红葫芦。", "A silver horn and the red gourd.")),
  N(id="blackbear", zh="黑熊精", py="Hēixióng Jīng", en="Black Bear Demon", cat="monster", camp="wild", dies=None,
    sub=("黑风山黑风大王", "The Great King of Black Wind Mountain"),
    bio=("黑风山的熊精。观音院的老院主贪图唐僧的锦襕袈裟，纵火要烧死师徒，他趁火打劫偷走了袈裟，还要办“佛衣会”。观音变作送仙丹的道士，让悟空变成仙丹被他吞下，又给他戴上禁箍，收为落伽山的守山大神。",
         "A bear spirit on Black Wind Mountain. When the greedy old abbot of the Guanyin Monastery sets fire to the pilgrims’ lodging to get Tang Sanzang’s brocade cassock, the bear takes advantage of the blaze to steal it for a “Buddha robe party” of his own. Guanyin comes disguised as a Daoist bearing an elixir pill, which is really Wukong; once the bear swallows it, she puts a hoop on his head and makes him guardian of her mountain."),
    icon=("熊头与锦襕袈裟。", "Bear’s head and the brocade cassock.")),
  N(id="yellowwind", zh="黄风怪", py="Huángfēng Guài", en="Yellow Wind Demon", cat="monster", camp="backed", dies=None,
    sub=("黄风岭的妖王", "Demon of Yellow Wind Ridge"),
    bio=("灵山脚下得道的黄毛貂鼠，偷吃了琉璃盏里的灯油，怕金刚捉拿，逃到黄风岭成精。他的三昧神风吹得悟空两眼疼痛流泪。如来早就派灵吉菩萨看管他，灵吉用飞龙宝杖将他擒住。",
         "A yellow marten from the foot of Vulture Peak who drank the oil in the Buddha’s crystal lamp and fled to Yellow Wind Ridge for fear of the guardian kings. His samadhi wind makes Wukong’s eyes ache and stream. The Buddha had already put Bodhisattva Lingji in charge of him, and Lingji takes him with the flying-dragon staff."),
    icon=("貂鼠头与三股叉，口吐黄风。", "A marten’s head and a trident, breathing yellow wind.")),
  N(id="greenox", zh="青牛精", py="Qīngniú Jīng", en="Green Ox Demon", cat="monster", camp="backed", dies=None,
    sub=("独角兕大王", "The Single-Horned Rhino King"),
    bio=("太上老君的坐骑青牛。看牛的童子偷吃了一粒七返火丹睡着了，他趁机偷了老君的金刚琢下界，在金兜山称王。金刚琢能套走一切兵器，哪吒的六件兵器、火德星君的火、十八罗汉的金丹砂都被收去。最后老君亲自来，才把他牵回。",
         "Laozi’s green ox. When the boy who looks after him falls asleep after eating an elixir pill, the ox steals Laozi’s diamond snare and sets himself up as king of Golden Helmet Mountain. The snare swallows any weapon: Nezha’s six weapons, the Fire God’s flames, the arhats’ golden sand. Only when Laozi comes himself is the ox led home."),
    icon=("独角牛头与金刚琢。", "A one-horned ox head and the diamond snare.")),
  N(id="greenlion", zh="青狮精", py="Qīngshī Jīng", en="Green Lion Demon", cat="monster", camp="backed", dies=None,
    sub=("文殊菩萨的青毛狮子", "Manjushri’s lion"),
    bio=("文殊菩萨的坐骑青毛狮子。在乌鸡国，他奉命把国王推下井，化作国王在位三年；在狮驼岭，他又做了三魔中的大大王，一口吞下悟空，结果被悟空在肚里折腾得求饶。两次都由文殊亲自收回。",
         "Manjushri’s green-maned lion. In Wuji he pushes the king down a well on orders and rules in his shape for three years; at Lion-Camel Ridge he is the eldest of three demon kings and swallows Wukong whole, only to beg for mercy as Wukong runs riot in his belly. Both times Manjushri comes to take him back."),
    icon=("青毛狮头。", "A green-maned lion’s head.")),
  N(id="whiteelephant", zh="白象精", py="Báixiàng Jīng", en="White Elephant Demon", cat="monster", camp="backed", dies=None,
    sub=("普贤菩萨的六牙白象", "Samantabhadra’s elephant"),
    bio=("普贤菩萨的坐骑白象，狮驼岭的二大王，用长鼻子卷住八戒。如来降伏三魔后，他被普贤收回。",
         "Samantabhadra’s white elephant, second demon king of Lion-Camel Ridge, who snatches up Bajie with his trunk. When the Buddha subdues the three demons, Samantabhadra takes him home."),
    icon=("白象头、长鼻与象牙。", "A white elephant’s head, trunk and tusks.")),
  N(id="roc", zh="大鹏金翅雕", py="Dàpéng Jīnchìdiāo", en="Golden-Winged Roc", cat="monster", camp="backed", dies=None,
    sub=("狮驼国的三大王", "Third demon king of Lion-Camel"),
    bio=("狮驼岭的三大王，号称云程万里鹏，吃尽了狮驼国满城百姓。他与佛母孔雀大明王同为一母所生，论起来是如来的“舅舅”。如来亲自出手，一指让他翅上抽了筋，飞逃不得，只能停在佛顶上，从此留作护法。",
         "The third demon king of Lion-Camel, the “roc of ten thousand miles of cloud”, who has eaten every person in the city of Lion-Camel. He was born of the same mother as the Peacock Queen whom the Buddha calls his mother, which makes him, in a manner of speaking, the Buddha’s uncle. The Buddha himself points a finger and the sinews of his wings go slack, so that he cannot fly off his perch above the Buddha’s head; he is kept as a guardian of the Law."),
    icon=("鹰喙、金翅与方天戟。", "Eagle’s beak, golden wings and a halberd.")),
  N(id="yellowbrow", zh="黄眉大王", py="Huángméi Dàwáng", en="Yellow Brows", cat="monster", camp="backed", dies=None,
    sub=("小雷音寺的假佛", "The false Buddha of Lesser Thunderclap"),
    bio=("弥勒佛座下司磬的黄眉童子，趁主人赴会，偷了金铙和人种袋下界，在小雷音寺假扮佛祖骗唐僧下拜。他用金铙把悟空扣在里面，又用人种袋把前来相助的天神一并装走。最后弥勒亲自来收。",
         "Maitreya’s yellow-browed page, keeper of the chimes. While his master is away he steals the golden cymbals and the human seed sack and sets up a fake Thunderclap Monastery, where Tang Sanzang bows to him as the Buddha. He traps Wukong between the cymbals and sweeps every god who comes to help into the sack, until Maitreya comes for him."),
    icon=("黄眉与金铙。", "Yellow eyebrows and the golden cymbals.")),
  N(id="saitaisui", zh="赛太岁", py="Sài Tàisuì", en="Sai Taisui", cat="monster", camp="backed", dies=None,
    sub=("观音的金毛犼", "Guanyin’s golden-haired hou"),
    bio=("观音菩萨的坐骑金毛犼，偷了颈下的紫金铃下界，抢走朱紫国的金圣宫娘娘三年，铃铛能放火、放烟、放沙。原来朱紫国王做太子时射伤了佛母孔雀大明王的两个孩子，佛母罚他与王后分离三年；犼正好听见，便下界来办了这件事。",
         "Guanyin’s mount, a golden-haired hou, who steals the golden bells from around his neck and carries off the queen of Zhuzi for three years; the bells pour out fire, smoke and sand. As a young prince the king of Zhuzi had shot and wounded two children of the Peacock Queen, who decreed he must be parted from his wife for three years; the hou overheard, and came down to carry it out."),
    icon=("金毛犼与紫金铃。", "A golden-maned hou and its golden bells.")),
  N(id="goldfish", zh="灵感大王", py="Línggǎn Dàwáng", en="Great King of Miracles", cat="monster", camp="backed", dies=None,
    sub=("通天河的金鱼精", "The goldfish of the River to Heaven"),
    bio=("通天河的妖王，每年要当地人献上一对童男童女。原来他是观音莲花池里养大的金鱼，每天浮头听经修成了法力，他的九瓣铜锤是一枝未开的莲苞。观音来不及梳妆，提着竹篮来到河边，把他收了回去——这就是“鱼篮观音”。",
         "The demon king of the River to Heaven, who demands a boy and a girl from the villagers every year. He is a goldfish from Guanyin’s lotus pond who gained his powers by surfacing every day to hear the sutras; his copper mace is an unopened lotus bud. Guanyin comes straight to the river without dressing her hair, carrying a bamboo basket, and takes him home: the “Guanyin with the fish basket”."),
    icon=("金鱼头与莲苞铜锤。", "A goldfish head and the lotus-bud mace.")),
  N(id="jaderabbit", zh="玉兔精", py="Yùtù Jīng", en="Jade Rabbit", cat="monster", camp="backed", dies=None,
    sub=("天竺国的假公主", "The false princess of India"),
    bio=("月宫里捣药的玉兔。她把天竺国的真公主摄走，自己变成公主，抛绣球正好打中唐僧，要招他为驸马。悟空识破后与她大战，太阴星君带着嫦娥们赶来收回。原来真公主前世是月宫的素娥，曾打过玉兔一掌。",
         "The jade rabbit that pounds medicine in the moon palace. She spirits away the real princess of India, takes her place, and throws the embroidered ball that picks Tang Sanzang as her husband. Wukong unmasks her, and the Moon Goddess arrives with her ladies to take her back. The real princess, it turns out, was once a moon lady who slapped the rabbit."),
    icon=("白兔与捣药杵。", "A white rabbit and her medicine pestle.")),
  N(id="mouse", zh="老鼠精", py="Lǎoshǔ Jīng", en="Mouse Spirit", cat="monster", camp="backed", dies=None,
    sub=("无底洞地涌夫人", "Lady Earth Flow of the Bottomless Cave"),
    bio=("金鼻白毛的老鼠精，三百年前在灵山偷吃了如来的香花宝烛，被李靖父子捉住，如来饶了她一命，她便拜李靖为父、哪吒为兄。她在陷空山无底洞逼唐僧成亲，悟空凭她供奉的牌位把李靖告到玉帝面前，李靖父子只好下界把她捉回。",
         "A white mouse with a golden nose who, three hundred years ago, ate the incense, flowers and candles on the Buddha’s altar; Li Jing and his son caught her, the Buddha spared her, and she took Li Jing as her father and Nezha as her brother. When she tries to force Tang Sanzang to marry her in the Bottomless Cave, Wukong takes her shrine tablets to the Jade Emperor as evidence, and Li Jing and Nezha have to come down and take her back."),
    icon=("白鼠、金鼻与双股剑。", "A white mouse with a golden nose, and her paired swords.")),
  N(id="spiders", zh="蜘蛛精", py="Zhīzhū Jīng", en="The Spider Spirits", cat="monster", camp="wild", dies="第七十三回",
    sub=("盘丝洞七姐妹", "Seven sisters of Silk Cave"),
    bio=("盘丝岭盘丝洞的七个女妖，能从肚脐中吐出丝绳。唐僧化斋落入她们手里；八戒趁她们在濯垢泉洗澡，变成一条鲇鱼在她们腿间钻来钻去。她们逃到师兄百眼魔君的黄花观，被悟空打死。",
         "Seven women demons of Silk Cave who spin silk ropes from their navels. Tang Sanzang falls into their hands while begging for food; while they bathe in the Filth-Cleansing Spring, Bajie turns into a catfish and wriggles between their legs. They flee to their senior brother, the Hundred-Eyed Demon, and are killed by Wukong."),
    icon=("女子与蛛网。", "A woman and a spider’s web.")),
  N(id="sixear", zh="六耳猕猴", py="Liù'ěr Míhóu", en="Six-Eared Macaque", cat="monster", camp="wild", dies="第五十八回",
    sub=("假美猴王", "The false Monkey King"),
    bio=("悟空被唐僧赶走后出现的假悟空，本事与悟空一般无二。他打伤唐僧、抢走行李，还在花果山另组了一支假取经队伍。观音、玉帝的照妖镜都分不出真假，只有如来认出他是六耳猕猴，悟空一棒将他打死。",
         "A double who appears after Tang Sanzang sends Wukong away, equal to him in every power. He strikes Tang Sanzang, steals his luggage and assembles a fake pilgrim party on the Mountain of Flowers and Fruit. Neither Guanyin nor the Jade Emperor’s demon-revealing mirror can tell the two apart; only the Buddha names him the Six-Eared Macaque, and Wukong kills him with one blow."),
    icon=("六只耳朵、紧箍与铁棒——连紧箍都一模一样。", "Six ears, a headband and a staff: he copied even the headband.")),
  N(id="ninehead", zh="九头虫", py="Jiǔtóu Chóng", en="Nine-Headed Bug", cat="monster", camp="wild", dies=None,
    sub=("碧波潭九头驸马", "Son-in-law of the Green Wave Pool"),
    bio=("碧波潭万圣龙王的女婿，九个头的怪鸟。他下血雨偷走祭赛国金光寺宝塔上的佛宝舍利，他的妻子万圣公主又偷了王母的九叶灵芝草。二郎神打猎路过，他的细犬咬下九头虫一个头，九头虫带伤逃往北海。",
         "Son-in-law of the Myriad Sage Dragon King of the Green Wave Pool, a monstrous bird with nine heads. He brings down a rain of blood and steals the relic from the pagoda of the Golden Light Monastery, while his wife steals the Queen Mother’s nine-leaved magic mushroom. Erlang, passing by on a hunt, sets his dog on him; the dog bites off one of his heads, and he flees wounded to the North Sea."),
    icon=("九头怪鸟。", "A monstrous bird with nine heads.")),
  N(id="tuolong", zh="鼍龙", py="Tuó Lóng", en="Alligator Dragon", cat="monster", camp="backed", dies=None,
    sub=("黑水河的妖龙", "Demon of the Black River"),
    bio=("泾河龙王的第九个儿子，西海龙王的外甥，霸占了黑水河神的府第。他扮作艄公把唐僧和八戒弄进水府，要请舅舅来吃唐僧肉。悟空拿着请帖告到西海龙宫，西海龙王只好派儿子摩昂太子把他锁回。",
         "The ninth son of the Jing River Dragon King and nephew of the Dragon King of the West Sea, who has seized the Black River god’s palace. Disguised as a ferryman, he carries Tang Sanzang and Bajie down into the river and invites his uncle to a feast of monk’s flesh. Wukong takes the invitation to the West Sea as evidence, and the Dragon King has to send his son to bring the nephew back in chains."),
    icon=("鼍龙头与竹节钢鞭。", "An alligator dragon’s head and a jointed steel whip.")),
]

# (source, target, type, zh label, zh text, en label, en text, chapter ref in Chinese)
# type: kin / aid / foe / tie, and mas (主从: master and mount, page, pet or subordinate; source is the master)
E = lambda *a: a
EDGES = [
  # ---------------------------------------------------------------- the pilgrims
  E("tangseng","wukong","aid","师徒","唐僧揭去五行山的封帖放出悟空，收他为大徒弟。观音给了唐僧一顶花帽和紧箍咒；悟空不服管教，一念咒就头疼欲裂。唐僧两次误会赶走他，最后仍是悟空一路护他到灵山。",
    "Master and disciple","Tang Sanzang lifts the seal on the Mountain of Five Elements and takes Wukong as his first disciple. Guanyin gives the monk a cap and the tightening spell: whenever Wukong disobeys, the spell makes his head feel ready to split. Twice the monk wrongly drives him away, yet it is Wukong who sees him all the way to Vulture Peak.","第十四回、第二十七回、第五十六回"),
  E("tangseng","bajie","aid","师徒","唐僧在高老庄收下猪悟能，因他本已持斋把素，断了五荤三厌，给他起了别名“八戒”。八戒一路爱在师父面前说悟空的坏话，唐僧也常偏听他。",
    "Master and disciple","At Gao Village Tang Sanzang takes Zhu Wuneng as a disciple and, since he has already given up the forbidden foods, calls him Bajie, “Eight Precepts”. Bajie is forever telling tales on Wukong, and the master often listens.","第十九回"),
  E("tangseng","shaseng","aid","师徒","唐僧在流沙河收下沙悟净，让悟空为他落了发，叫他沙和尚。沙僧挑着担子走完全程，是最少惹事的徒弟。",
    "Master and disciple","At the Flowing Sand River Tang Sanzang takes Sha Wujing as a disciple, has Wukong shave his head and calls him the Sha Monk. Sha carries the luggage the whole way and gives the least trouble of any disciple.","第二十二回"),
  E("tangseng","horse","mas","坐骑","白龙吃了唐僧的白马，观音便让他化作白马，驮唐僧西行。宝象国一难，他现出龙身与黄袍怪交手受伤，又劝八戒去花果山请回悟空。",
    "His mount","The white dragon eats Tang Sanzang’s horse, so Guanyin turns him into a white horse to carry the monk west. At Baoxiang he changes back into a dragon to fight the Yellow Robe Demon, is wounded, and persuades Bajie to go and fetch Wukong.","第十五回、第三十回"),
  E("wukong","bajie","tie","斗嘴的师兄弟","悟空常捉弄八戒，八戒常在师父面前告悟空的状，白虎岭上更是挑唆师父赶走了他。可八戒被捉了，总是悟空去救；悟空被赶走了，也是八戒去花果山把他请了回来。",
    "Bickering brothers","Wukong plays tricks on Bajie, and Bajie tells tales on Wukong, above all at White Tiger Ridge, where he talks the master into dismissing him. But when Bajie is captured, Wukong is the one who rescues him; and when Wukong has been sent away, it is Bajie who goes to bring him back.","第二十七回、第三十一回"),
  E("wukong","shaseng","aid","师兄弟","沙僧敬重大师兄。悟空被赶走后，沙僧去花果山讨还行李，看见一个假沙僧，一杖将他打死。",
    "Brothers in the Way","Sha respects his senior brother. After Wukong is sent away, Sha goes to the Mountain of Flowers and Fruit to get the luggage back, sees a false Sha Monk there and kills him with one blow.","第五十七回"),
  E("bajie","shaseng","aid","师兄弟","两人常一起守着师父，也常一起被妖怪捉去。流沙河边，八戒与沙僧先打了一场才成为师兄弟。",
    "Brothers in the Way","The two usually stay behind together to guard the master, and are often captured together. Before becoming brothers they fought each other at the Flowing Sand River.","第二十二回"),
  # ---------------------------------------------------------------- Buddhist world
  E("rulai","guanyin","mas","奉旨东行","如来要找一个善信到西天取经，观音自请前往，如来给了她锦襕袈裟、九环锡杖和金、紧、禁三个箍儿。",
    "Sends her east","The Buddha wants a faithful pilgrim to come west for his scriptures; Guanyin offers to find one, and he gives her a brocade cassock, a nine-ringed staff and three magic hoops.","第八回"),
  E("rulai","wukong","tie","五行山","悟空夸口要夺玉帝的位子，如来与他打赌：翻得出我的手掌，天宫让你坐。悟空在“天尽头”的柱子上写字撒尿，原来只是佛祖的手指；如来翻掌把他压在五行山下。五百年后，又封他为斗战胜佛。",
    "Under the mountain","When Wukong boasts he will take the Jade Emperor’s throne, the Buddha bets him he cannot leap out of his palm. Wukong writes his name and pees on a pillar at the “end of the world”, which turns out to be the Buddha’s finger; the Buddha turns his hand over and pins him beneath a mountain. Five hundred years later he makes him the Victorious Fighting Buddha.","第七回、第一百回"),
  E("rulai","tangseng","tie","金蝉子","唐僧前世是如来的二弟子金蝉子，因不听说法、轻慢佛教，被贬转生东土。取经功成，如来封他为旃檀功德佛。",
    "Golden Cicada","In a former life Tang Sanzang was the Buddha’s second disciple, Golden Cicada, banished to be reborn in the East for not listening to the Buddha’s teaching. When the pilgrimage is complete, the Buddha makes him the Buddha of Candana Merit.","第一百回"),
  E("rulai","sixear","foe","识破","两个悟空打到灵山，如来说出世间有四种猴不入十类，其中六耳猕猴“善聆音，能察理”；他用金钵盂罩住假悟空，现出原形。",
    "Unmasks him","When the two Wukongs fight their way to Vulture Peak, the Buddha explains that four kinds of monkey belong to none of the ten orders of beings, among them the six-eared macaque, who “hears every sound and grasps every principle”; he traps the impostor under his golden bowl and reveals his true form.","第五十八回"),
  E("rulai","roc","kin","舅甥","如来说：孔雀曾把他吸进肚里，他剖开孔雀的脊背出来，尊孔雀为佛母孔雀大明王；大鹏与孔雀同为一母所生，所以与他“有些亲处”。如来擒住大鹏，让他做了护法。",
    "Nephew and uncle","The Buddha explains that a peacock once swallowed him and he cut his way out through its back, afterward honoring it as the Peacock Queen, Mother of Buddhas; the roc was born of the same mother as the peacock, so the two of them are “somewhat related”. The Buddha captures him and makes him a guardian of the Law.","第七十七回"),
  E("rulai","yellowwind","mas","早有安排","黄风怪偷了灵山的灯油逃走，如来念他罪不至死，派灵吉菩萨看管，还赐了定风丹和飞龙宝杖。",
    "His arrangement","When the marten runs off with the oil from the Buddha’s lamp, the Buddha judges he does not deserve death and puts Bodhisattva Lingji in charge of him, with a wind-fixing pill and a flying-dragon staff.","第二十一回"),
  E("rulai","mouse","tie","饶她一命","老鼠精三百年前偷吃了如来的香花宝烛，李靖父子捉住她，如来说“积水养鱼终不钓，深山喂鹿望长生”，饶了她的性命。",
    "Spares her","Three centuries earlier the mouse ate the incense, flowers and candles on the Buddha’s altar; Li Jing and Nezha caught her, and the Buddha let her live.","第八十三回"),
  E("guanyin","wukong","aid","救苦救难","观音在五行山给悟空指了出路，又给唐僧紧箍制住他；一路上她送他三根救命毫毛，一次次为他收妖。悟空也常跑去南海向她诉苦。",
    "His rescuer","At the Mountain of Five Elements Guanyin shows Wukong a way out, and gives Tang Sanzang the headband to keep him in check; on the road she gives him three life-saving hairs and takes away demon after demon for him. Wukong often goes to the Southern Sea to pour out his troubles to her.","第八回、第十四回、第十五回"),
  E("guanyin","tangseng","aid","选中取经人","观音扮作癞头和尚在长安卖袈裟、锡杖，在水陆大会上显圣，选中玄奘西去取经。",
    "Chooses him","Disguised as a scabby monk, Guanyin sells a cassock and staff in Chang’an, then reveals herself at the great mass and chooses Xuanzang to go west for the scriptures.","第十二回"),
  E("guanyin","bajie","aid","赐名悟能","观音东行路过福陵山，劝天蓬元帅转生的猪妖等候取经人，为他摩顶受戒，取名猪悟能。",
    "Names him Wuneng","On her way east Guanyin meets the pig demon on Fuling Mountain, persuades him to wait for the pilgrim, gives him the precepts and names him Zhu Wuneng.","第八回"),
  E("guanyin","shaseng","aid","赐名悟净","观音在流沙河劝卷帘大将改过，取名沙悟净；后来又让他把九个骷髅穿成法船，渡唐僧过河。",
    "Names him Wujing","At the Flowing Sand River Guanyin persuades the fallen general to reform and names him Sha Wujing; later his nine skulls are strung together into a raft to ferry Tang Sanzang across.","第八回、第二十二回"),
  E("guanyin","horse","aid","救下性命","西海三太子被父亲告了忤逆，要被处斩，观音向玉帝求情救下他，让他为取经人做脚力。",
    "Saves his life","Charged with disobedience by his father and about to be executed, the dragon prince is saved when Guanyin pleads for him with the Jade Emperor, on condition that he carry the pilgrim.","第八回、第十五回"),
  E("guanyin","blackbear","mas","守山大神","观音用禁箍降伏黑熊精，收他做落伽山的守山大神。",
    "Guardian of her mountain","Guanyin subdues the Black Bear with the forbidding hoop and makes him guardian of her island mountain.","第十七回"),
  E("guanyin","redboy","mas","善财童子","观音用莲台与五个金箍降伏红孩儿，一步一拜，把他带回南海做了善财童子。",
    "Her page","Guanyin subdues Red Boy with her lotus throne and five gold hoops and takes him, bowing at every step, back to the Southern Sea as her page, the Boy of Good Fortune.","第四十二回"),
  E("guanyin","goldfish","mas","莲池金鱼","灵感大王是观音莲花池里的金鱼，趁海潮泛涨溜到通天河。观音来不及梳妆，提着鱼篮把他收回。",
    "Her goldfish","The Great King of Miracles is a goldfish from Guanyin’s lotus pond who slipped away to the River to Heaven on a high tide. She comes to fetch him with a fish basket, not even stopping to dress her hair.","第四十九回"),
  E("guanyin","saitaisui","mas","坐骑","赛太岁是观音的坐骑金毛犼，趁牧童睡着，咬断铁索下界。观音赶来喝出原形，骑着他回了南海。",
    "Her mount","Sai Taisui is Guanyin’s golden-haired hou, who bit through his chain while the herd boy slept. She arrives, calls him back to his true form and rides him home.","第七十一回"),
  E("guanyin","goldhorn","tie","借宝考验","老君说：金角、银角下界，是观音向他借了三次，才派来考验取经人的。",
    "A test she arranged","Laozi says Guanyin asked him three times to lend her his two boys, and sent them down as demons to test the pilgrims.","第三十五回"),
  E("guanyin","zhenyuan","aid","救活果树","悟空推倒了人参果树，只有观音的净瓶甘露能救；她来到五庄观，让果树重新发芽结果。",
    "Revives his tree","Wukong has knocked down the ginseng fruit tree, and only the dew from Guanyin’s vase can save it; she comes to the Five Villages Abbey and brings it back to life.","第二十六回"),
  E("guanyin","erlang","aid","举荐","天兵拿不下悟空，观音向玉帝举荐玉帝的外甥二郎真君。",
    "Recommends him","When the heavenly armies cannot take Wukong, Guanyin recommends the Jade Emperor’s nephew, the True Lord Erlang.","第六回"),
  E("guanyin","taizong","aid","长安显圣","观音在长安卖袈裟锡杖，太宗要付钱，她分文不取；水陆大会上她现出真身，留下一张帖子，太宗才决心派人西天取经。",
    "Appears in Chang’an","Guanyin sells a cassock and staff in Chang’an and refuses the emperor’s money; at the great mass she appears in her true form and leaves a message, and Taizong resolves to send someone west for the scriptures.","第十二回"),
  E("guanyin","sixear","tie","难辨真假","两个悟空打到南海，观音念紧箍咒，两个一齐喊疼，她也分辨不出。",
    "Cannot tell them apart","When the two Wukongs fight their way to the Southern Sea, Guanyin recites the tightening spell and both cry out in pain; even she cannot tell them apart.","第五十八回"),
  E("maitreya","yellowbrow","mas","司磬童子","黄眉大王是弥勒座下敲磬的童子，偷了主人的金铙和人种袋。弥勒扮作瓜农，让悟空变成熟瓜被黄眉吃下，再把他装进袋里带走。",
    "His page","Yellow Brows is the page who strikes Maitreya’s chimes, and he stole his master’s cymbals and sack. Maitreya disguises himself as a melon farmer, lets the demon eat Wukong in the shape of a ripe melon, then bags him and takes him home.","第六十六回"),
  E("manjushri","greenlion","mas","坐骑","青毛狮子是文殊的坐骑。乌鸡国与狮驼岭两次作乱，都是文殊亲自来收。",
    "His mount","The green-maned lion is Manjushri’s mount. Both at Wuji and at Lion-Camel Ridge, Manjushri comes himself to take him back.","第三十九回、第七十七回"),
  E("maitreya","wukong","aid","瓜田之计","悟空请来的天神一个个被人种袋装走，他走投无路时弥勒现身，在山坡上变出一片瓜田，让悟空变作一只熟瓜，引黄眉来吃，在他肚里拳打脚踢。",
    "The melon field","When every god Wukong brings has been swept into the sack and he has nowhere left to turn, Maitreya appears, conjures a melon patch on the hillside and has Wukong turn into a ripe melon for the demon to eat; inside, Wukong kicks and punches until Yellow Brows gives up.","第六十六回"),
  E("manjushri","samantabhadra","aid","同赴狮驼岭","如来亲往狮驼岭降魔，带上了文殊、普贤两位菩萨，各自收回走失的坐骑。",
    "Side by side","The Buddha goes in person to Lion-Camel Ridge and brings Manjushri and Samantabhadra with him, each to take back his runaway mount.","第七十七回"),
  E("manjushri","wujiking","tie","三日三年","乌鸡国王曾把化作凡僧的文殊浸在御水河里三天三夜。如来便让文殊的狮子把国王推下井，泡上三年作为报应。",
    "Three days for three years","The king once dunked Manjushri, disguised as an ordinary monk, in the moat for three days and nights, so the Buddha had Manjushri’s lion leave the king in a well for three years in return.","第三十九回"),
  E("samantabhadra","whiteelephant","mas","坐骑","白象是普贤的坐骑，在狮驼岭做了二大王。普贤念动真言，白象现出原形被收回。",
    "His mount","The white elephant is Samantabhadra’s mount and the second demon king of Lion-Camel Ridge. Samantabhadra chants a spell, and the elephant shows his true form.","第七十七回"),
  E("lingji","yellowwind","mas","奉命看管","灵吉菩萨受如来之托看管黄风怪。悟空请他来，他抛出飞龙宝杖化作金龙，一把抓住黄毛貂鼠。",
    "His charge","Bodhisattva Lingji keeps watch over the marten on the Buddha’s orders. When Wukong asks for help, he throws the flying-dragon staff, which turns into a golden dragon and seizes the demon.","第二十一回"),
  E("lingji","wukong","aid","定风丹","悟空被铁扇公主一扇扇到小须弥山，灵吉送他一粒定风丹。再去借扇时，那扇子再也扇不动他。",
    "The wind-fixing pill","Blown all the way to Little Sumeru by Princess Iron Fan’s fan, Wukong is given a wind-fixing pill by Lingji; the next time she fans him, he does not budge.","第五十九回"),
  # ---------------------------------------------------------------- Heaven
  E("jade","wukong","tie","大闹天宫","玉帝先封悟空做弼马温，他嫌官小反下天宫；又封他为齐天大圣，让他看管蟠桃园。悟空偷桃、偷酒、偷金丹，打得十万天兵无法近身，玉帝只好请来如来。",
    "Havoc in Heaven","The Jade Emperor first makes Wukong keeper of the heavenly horses, and he quits in disgust at the low rank; then he makes him Great Sage Equal to Heaven and puts him in charge of the peach orchard. Wukong steals peaches, wine and elixir and holds off a hundred thousand heavenly soldiers, until the Jade Emperor sends for the Buddha.","第四回、第五回、第七回"),
  E("jade","rulai","aid","请佛降妖","众神拿不住大闹天宫的悟空，玉帝派人去西天请来如来。事后，玉帝设“安天大会”答谢佛祖。",
    "Sends for the Buddha","When no god can stop Wukong, the Jade Emperor sends to the West for the Buddha, and afterward holds a banquet to celebrate peace in Heaven in his honor.","第七回"),
  E("jade","erlang","kin","舅甥","二郎神是玉帝的外甥：玉帝的妹妹思凡下界，与杨君生下了他。他住在灌江口，“听调不听宣”。",
    "Uncle and nephew","Erlang is the Jade Emperor’s nephew, born when the emperor’s sister went down to earth and married a mortal named Yang. He lives at Guanjiang and answers requests but not summonses.","第六回"),
  E("jade","bajie","tie","贬下凡间","天蓬元帅酒后调戏嫦娥，玉帝把他打了二千锤，贬下凡间，他错投了猪胎。",
    "Banishes him","For his drunken advances to Chang’e, the Jade Emperor has the Marshal beaten with two thousand strokes of the hammer and banished to the world below, where he is born by mistake as a pig.","第八回"),
  E("jade","shaseng","tie","八百鞭","卷帘大将打碎了玻璃盏，玉帝打了他八百下，贬到流沙河，还每七日派飞剑来穿他胸胁。",
    "Eight hundred lashes","For the broken crystal cup the Jade Emperor has the Curtain-Lifting General given eight hundred lashes and exiled to the Flowing Sand River, with a flying sword sent every seven days to pierce his side.","第八回"),
  E("jade","yellowrobe","mas","召回天庭","奎木狼私自下界十三年。悟空查到他的来历，玉帝点名召回，罚他去兜率宫给老君烧火。",
    "Recalls him","The Wolf Star has been gone from Heaven for thirteen years. When Wukong discovers who he is, the Jade Emperor calls him back and sets him to tending Laozi’s furnace.","第三十一回"),
  E("jade","aoguang","tie","上表告状","悟空抢走金箍棒，东海龙王亲上天庭递表告状。太白金星却建议招安，玉帝便封了悟空官职。",
    "His complaint","After Wukong walks off with the staff, the Dragon King goes to Heaven himself to lodge a complaint; the Gold Star of Venus proposes making Wukong an official instead, and the Jade Emperor agrees.","第三回"),
  E("queenmother","wukong","foe","搅乱蟠桃会","悟空看守蟠桃园，把熟桃吃了大半；听说王母的蟠桃会没请他，又偷喝了会上的仙酒、偷吃了老君的金丹，逃回花果山。",
    "Ruins her banquet","Put in charge of the orchard, Wukong eats most of the ripe peaches; hearing he has not been invited to the Queen Mother’s banquet, he drinks the wine laid out for it, eats Laozi’s elixir and runs home.","第五回"),
  E("queenmother","shaseng","tie","玻璃盏","卷帘大将在王母的蟠桃会上失手打碎了玻璃盏，因此被贬。",
    "The crystal cup","It is at the Queen Mother’s peach banquet that the Curtain-Lifting General drops and breaks the crystal cup.","第八回"),
  E("queenmother","ninehead","tie","灵芝草","九头虫的妻子万圣公主偷了王母的九叶灵芝草，拿来温养偷来的舍利。",
    "The stolen mushroom","The Nine-Headed Bug’s wife steals the Queen Mother’s nine-leaved magic mushroom to nourish the stolen relic.","第六十二回"),
  E("laojun","wukong","tie","八卦炉","悟空偷吃了老君葫芦里的金丹；被擒后，老君把他放进八卦炉炼了四十九天，没炼死，反炼出一双火眼金睛。取经路上悟空又几次上兜率宫，找老君讨还他走失的坐骑和童子。",
    "The furnace","Wukong eats the elixir in Laozi’s gourds; once captured, he is put in Laozi’s eight-trigram furnace for forty-nine days, which fails to kill him and leaves him with fiery golden eyes. On the road he goes back to Laozi more than once to demand he fetch his runaway ox and boys.","第五回、第七回、第五十二回"),
  E("laojun","greenox","mas","坐骑","青牛是老君的坐骑，偷了金刚琢下界。老君拿芭蕉扇一扇，收回金刚琢，牵牛回天。",
    "His mount","The green ox is Laozi’s mount and has run off with the diamond snare. With one wave of his palm-leaf fan Laozi takes back the snare and leads the ox home.","第五十二回"),
  E("laojun","goldhorn","mas","看金炉的童子","金角大王是老君看金炉的童子。老君来讨，悟空才还了宝贝，放他回去。",
    "His furnace boy","Golden Horn is the boy who tends Laozi’s gold furnace. When Laozi comes for him, Wukong hands back the treasures and lets him go.","第三十五回"),
  E("laojun","silverhorn","mas","看银炉的童子","银角大王是老君看银炉的童子，被悟空收进了紫金红葫芦，老君倒出来，一起领回。",
    "His furnace boy","Silver Horn is the boy who tends Laozi’s silver furnace. Wukong has trapped him in the red gourd; Laozi pours him out and takes both boys home.","第三十五回"),
  E("laojun","erlang","aid","金刚琢","二郎神与悟空斗得难分难解，老君从天上抛下金刚琢，正打中悟空头顶，二郎神才得手。",
    "The diamond snare","While Erlang and Wukong are locked in combat, Laozi drops his diamond snare from the clouds; it hits Wukong on the head, and Erlang takes him.","第六回"),
  E("laojun","wujiking","aid","还魂丹","悟空上兜率宫，软磨硬泡讨来一粒九转还魂丹，救活了井底泡了三年的乌鸡国王。",
    "The reviving pill","Wukong goes up to Laozi’s palace and begs and pesters until he gets a nine-times-refined pill, which brings the drowned king back to life.","第三十九回"),
  E("jinxing","wukong","aid","两番招安","太白金星两次提议招安，亲自下界请悟空上天，先做弼马温，再做齐天大圣。狮驼岭前，他化作老人报信。",
    "Twice invites him","Twice the Gold Star proposes an offer instead of war and comes down himself to bring Wukong up to Heaven, first as keeper of the horses, then as Great Sage. Before Lion-Camel Ridge he appears as an old man to warn him.","第三回、第四回、第七十四回"),
  E("jinxing","tangseng","aid","双叉岭脱险","唐僧刚出长安就落入虎精手中，太白金星化作老人，救他出洞，指点他上路。",
    "Rescues him","Just out of Chang’an, Tang Sanzang falls into the hands of a tiger demon; the Gold Star, in the form of an old man, leads him out of the cave and sets him on his way.","第十三回"),
  E("erlang","wukong","tie","不打不相识","二郎神与悟空变化斗法，悟空变麻雀他就变饿鹰，悟空变庙宇他就认出旗杆是尾巴，最后擒住了大圣。几百年后在碧波潭，两人又联手打九头虫。",
    "Old rivals","Erlang and Wukong fight a duel of transformations: sparrow against hawk, and when Wukong turns into a temple, Erlang spots his tail as the flagpole behind it; at last he captures the Great Sage. Centuries later, at the Green Wave Pool, the two join forces against the Nine-Headed Bug.","第六回、第六十三回"),
  E("erlang","ninehead","foe","细犬咬头","九头虫现出本相扑来，二郎神一弹弓打中，他的细犬跳上去，咬下九头虫一个头。",
    "The dog bites","When the Nine-Headed Bug swoops in his true form, Erlang hits him with a pellet, and his hound leaps up and bites off one of the heads.","第六十三回"),
  E("lijing","nezha","kin","父子","哪吒是李靖的三儿子。老鼠精一案中，悟空拿着牌位告李靖“纵女为妖”，李靖大怒要砍悟空，还是哪吒提醒父亲，确有一个下界的义女。",
    "Father and son","Nezha is Li Jing’s third son. When Wukong accuses Li Jing of letting his daughter run wild as a demon, Li Jing is ready to cut him down, until Nezha reminds his father that he does have an adopted daughter down below.","第八十三回"),
  E("lijing","wukong","tie","天兵天将","李靖做降魔大元帅，率天兵围剿花果山，屡战屡败。取经路上，悟空又常找他借兵，还把他告到玉帝面前。",
    "Heaven’s commander","As commander against the demons, Li Jing leads the heavenly army against the Mountain of Flowers and Fruit and loses again and again. On the road Wukong often asks him for troops, and once brings a lawsuit against him before the Jade Emperor.","第四回、第八十三回"),
  E("lijing","mouse","kin","义父女","老鼠精感念不杀之恩，拜李靖为义父，在无底洞供着“尊父李天王之位”。李靖父子最后亲自下界，把她拿回天庭发落。",
    "Adoptive father","Grateful to be spared, the mouse spirit took Li Jing as her adoptive father and kept a tablet to “my honored father, Heavenly King Li” in her cave. In the end Li Jing and Nezha come down themselves and take her back to Heaven.","第八十三回"),
  E("lijing","bull","foe","擒牛","李靖率天兵、哪吒与佛门护法四面合围，牛魔王无处可逃，被牵往灵山。",
    "Captures the Bull","Li Jing surrounds the Bull Demon King with heavenly troops, Nezha and Buddhist guardians, and he is led away to Vulture Peak.","第六十一回"),
  E("nezha","wukong","foe","花果山交手","哪吒变作三头六臂与悟空交战，悟空也变三头六臂，还拔毫毛变出假身，在背后打中哪吒。",
    "Their duel","Nezha grows three heads and six arms to fight Wukong, who does the same, then leaves a hair double in front of him and strikes Nezha from behind.","第四回"),
  E("nezha","bull","foe","火轮缚牛","哪吒砍下牛魔王的头，又长出一个；他把火轮挂在牛角上烧，牛魔王求饶，被他用缚妖索穿了鼻孔。",
    "Takes the Bull","Nezha cuts off the Bull Demon King’s head, and another grows; he hangs his fire wheel on the bull’s horns until the demon begs for his life, then threads a demon-binding rope through his nose.","第六十一回"),
  E("nezha","mouse","kin","义兄妹","老鼠精拜哪吒为兄，供着“尊兄哪吒三太子位”。",
    "Adoptive siblings","The mouse spirit took Nezha as her brother and kept a tablet to “my honored brother, the Third Prince Nezha”.","第八十三回"),
  E("change","bajie","tie","调戏嫦娥","天蓬元帅因酒后调戏嫦娥被贬下凡。到了天竺国，嫦娥们下界来收玉兔，八戒又动了心，跳上去拉扯霓裳仙子。",
    "Old weakness","Drunk, the Marshal of the Heavenly Reeds made advances to Chang’e and was banished for it. When the moon ladies come down to India to fetch the rabbit, Bajie leaps up and grabs at one of them again.","第八回、第九十五回"),
  E("change","jaderabbit","mas","广寒宫的玉兔","玉兔是月宫捣药的兔子，太阴星君带着嫦娥们下界，把她收回广寒宫。",
    "The moon palace rabbit","The jade rabbit pounds medicine in the moon palace, and the Moon Goddess comes down with her ladies to bring her home.","第九十五回"),
  E("zhenyuan","wukong","tie","人参果","悟空偷果被骂，一怒推倒人参果树。镇元子用“袖里乾坤”把师徒装回，又是油锅又是绑树；悟空请观音救活果树，两人不打不相识，结为兄弟。",
    "The ginseng fruit","Scolded for stealing fruit, Wukong knocks down the ginseng tree. Zhenyuan sweeps the pilgrims up in his sleeve and brings them back for a boiling in oil; once Guanyin revives the tree, the two old enemies become sworn brothers.","第二十四回至二十六回"),
  E("zhenyuan","tangseng","tie","故人","镇元子说唐僧前世是金蝉子，当年在盂兰盆会上，金蝉子曾亲手传茶敬他，所以特意留了两个人参果；唐僧看果子像婴儿，不敢吃。",
    "An old friend","Zhenyuan says that in his former life Tang Sanzang, as Golden Cicada, once served him tea with his own hands at a festival, so he saves two ginseng fruits for him; the monk thinks they look like newborn babies and will not eat them.","第二十四回"),
  E("subodhi","wukong","aid","师徒","菩提祖师为石猴取名孙悟空，传他长生之道、七十二变和筋斗云。悟空在同门面前卖弄变化，祖师便赶他下山，嘱咐他不许说是自己的徒弟。",
    "Teacher and pupil","The patriarch names the stone monkey Sun Wukong and teaches him the way of long life, the seventy-two transformations and the cloud somersault. When Wukong shows off his transformations to the other pupils, the patriarch sends him away and forbids him to say whose pupil he was.","第一回、第二回"),
  # ---------------------------------------------------------------- dragons
  E("aoguang","wukong","tie","金箍棒","悟空到东海借兵器，挑中了一万三千五百斤的定海神针，又逼四海龙王凑齐一身披挂。后来他赌气离开唐僧，也是东海龙王劝他回去。",
    "The staff","Wukong comes to the East Sea for a weapon, chooses the 13,500-pound iron pillar that steadies the sea, and makes the four dragon kings give him a suit of armor as well. Later, when he walks out on Tang Sanzang in a huff, it is this Dragon King who talks him into going back.","第三回、第十四回"),
  E("aoguang","aorun","kin","兄弟","东海龙王敖广与西海龙王敖闰同为四海龙王。悟空来要披挂时，敖广敲响铁鼓金钟，把三个兄弟都召了来。",
    "Brothers","Ao Guang of the East Sea and Ao Run of the West Sea are two of the four dragon kings. When Wukong demands armor, Ao Guang sounds the drum and bell to summon his three brothers.","第三回"),
  E("aorun","horse","kin","父子","三太子纵火烧了殿上明珠，西海龙王亲自上表天庭，告他忤逆，险些害他丢了性命。",
    "Father and son","When his third son burns the palace pearls, the Dragon King himself reports him to Heaven for disobedience, nearly costing him his life.","第八回"),
  E("aorun","tuolong","kin","舅甥","鼍龙是西海龙王的外甥，父亲泾河龙王被斩后，由舅舅安置在黑水河修身。他捉了唐僧还给舅舅发请帖，西海龙王吓得赶紧派儿子去拿他。",
    "Uncle and nephew","The Alligator Dragon is the West Sea king’s nephew; after his father the Jing River Dragon King was executed, his uncle settled him at the Black River. When he captures Tang Sanzang and sends his uncle an invitation to the feast, the alarmed Dragon King sends his son to arrest him.","第四十三回"),
  # ---------------------------------------------------------------- mortals
  E("taizong","tangseng","aid","御弟","太宗选玄奘为水陆大会的坛主，又派他西天取经，与他结为兄弟，称他御弟，赐号三藏。取经归来，太宗亲撰《圣教序》。",
    "Sworn brothers","Taizong chooses Xuanzang to lead the great mass, sends him west for the scriptures, swears brotherhood with him and names him Sanzang. When he returns, the emperor writes a preface to the scriptures himself.","第十二回、第一百回"),
  E("bajie","cuilan","kin","夫妻","八戒入赘高老庄，娶了三小姐翠兰。临走他还嘱咐丈人好好看待浑家，说取经不成还要回来做女婿。",
    "Husband and wife","Bajie marries into the Gao family and takes Cuilan as his wife. As he leaves with the pilgrims, he tells his father-in-law to look after her, since if the pilgrimage fails he will be back.","第十八回、第十九回"),
  E("wukong","cuilan","tie","假扮翠兰","悟空变成翠兰的模样坐在房里，等八戒回来，把他吓了一跳。",
    "Takes her shape","Wukong takes Cuilan’s shape and sits waiting in her room to give Bajie a fright.","第十八回"),
  E("baihuaxiu","tangseng","aid","放走唐僧","唐僧被黄袍怪捉住，公主假托梦兆放了他，托他给父王捎去家书。",
    "Frees him","When the Yellow Robe Demon captures Tang Sanzang, the princess invents a dream as an excuse to let him go, and gives him a letter for her father.","第二十九回"),
  E("yellowrobe","baihuaxiu","tie","十三年夫妻","她前世是天宫的玉女，与奎木狼相恋；投胎做公主后，被他掳去做了十三年夫妻，生下两个孩子，心中却一直想家。",
    "Thirteen years","In a former life she was a jade maiden of Heaven in love with the Wolf Star; reborn as a princess, she is carried off by him and lives thirteen years as his wife, bearing him two children, while always longing for home.","第二十九回、第三十一回"),
  E("wujiking","tangseng","aid","托梦求救","乌鸡国王的冤魂夜里闯进宝林寺，托梦给唐僧，留下白玉圭为证，求他为自己申冤。",
    "His ghost’s plea","The drowned king’s ghost comes to Tang Sanzang in a dream at the Treasure Wood Monastery, leaves a white jade tablet as proof, and begs him for justice.","第三十七回"),
  E("wukong","wujiking","aid","起死回生","悟空让八戒从井底把国王的尸体背上来，又讨来老君的仙丹，把他救活。",
    "Brings him back","Wukong has Bajie carry the king’s body up from the bottom of the well, then gets an elixir pill from Laozi and brings him back to life.","第三十八回、第三十九回"),
  E("greenlion","wujiking","foe","推井夺位","青狮化作全真道士，趁国王游园把他推下井，自己变成国王的模样坐了三年江山。",
    "Takes his throne","Disguised as a Daoist, the lion pushes the king down a well in his garden and rules in his shape for three years.","第三十七回至三十九回"),
  E("womanking","tangseng","tie","愿以国相托","女王见唐僧相貌堂堂，愿以一国之富招他为王，自己做王后。唐僧“假亲脱网”，送出西关才告辞。",
    "Offers him her kingdom","Charmed by Tang Sanzang, the queen offers him her kingdom and herself as his queen. He plays along with a false engagement and takes his leave only once she has seen him beyond the western gate.","第五十四回"),
  E("wukong","womanking","tie","假亲脱网","悟空替师父定下“假亲脱网”之计：让唐僧假意答应亲事，骗女王在通关文牒上盖印、送出西关，再脱身西去。",
    "The false engagement","Wukong devises the plan for his master: agree to the marriage, let the queen stamp the travel papers and see them off at the western gate, and then slip away west.","第五十四回"),
  # ---------------------------------------------------------------- the Bull's family
  E("bull","wukong","tie","结拜兄弟","悟空年轻时与牛魔王等七位魔王结为兄弟，牛魔王居长。取经路上，悟空先降了他的儿子，又三借芭蕉扇，兄弟反目成仇。",
    "Sworn brothers","In his youth Wukong swore brotherhood with seven demon kings, the Bull the eldest. On the road he subdues the Bull’s son and then comes for his wife’s fan three times, and the brothers become enemies.","第三回、第五十九回至六十一回"),
  E("bull","ironfan","kin","夫妻","铁扇公主是牛魔王的原配，牛魔王另娶玉面公主，久不回家。悟空变作他的模样回家，骗得了扇子；牛魔王又变作八戒，把扇子骗了回去。",
    "Married","Princess Iron Fan is the Bull’s first wife, whom he has left for Princess Jade Face. Wukong gets the fan by coming home to her in her husband’s shape; the Bull gets it back by posing as Bajie.","第六十回、第六十一回"),
  E("bull","redboy","kin","父子","红孩儿是牛魔王的儿子。悟空变成牛魔王去火云洞，被红孩儿问起生辰八字，当场露馅。",
    "Father and son","Red Boy is the Bull’s son. Wukong goes to Fire Cloud Cave disguised as the Bull, and gives himself away when the boy asks him the time and date of his own birth.","第四十二回"),
  E("bull","jadeface","kin","妾","玉面公主带着百万家私，招牛魔王做了上门女婿。",
    "His second wife","Princess Jade Face brings him a fortune of a million and takes him in as her husband.","第六十回"),
  E("ironfan","redboy","kin","母子","红孩儿被观音收去做了善财童子，铁扇公主恨悟空害她母子分离，一见悟空便拔剑来砍。",
    "Mother and son","Red Boy has been taken by Guanyin to be her page, and Princess Iron Fan blames Wukong for parting her from her son; she draws her sword the moment she sees him.","第五十九回"),
  E("ironfan","wukong","foe","三借芭蕉扇","第一次她一扇把悟空扇到五万多里外的小须弥山；第二次悟空钻进她肚里逼她交扇，拿到的却是假扇；第三次他变成牛魔王才骗到真扇。",
    "The fan","The first time, one wave blows Wukong more than fifty thousand li, all the way to Little Sumeru; the second time he gets inside her belly and makes her hand it over, but it is a fake; the third time he comes as her husband and gets the real one.","第五十九回至六十一回"),
  E("redboy","wukong","foe","三昧真火","悟空说自己与牛魔王是结拜兄弟，算来是红孩儿的叔叔；红孩儿不认，吐出三昧真火，四海龙王的雨也浇不灭，悟空被烧得昏死过去。",
    "The samadhi fire","Wukong says that as the Bull’s sworn brother he is the boy’s uncle; Red Boy refuses to know him and breathes a samadhi fire that the rain of the four dragon kings cannot put out, and Wukong is burned until he faints.","第四十回、第四十一回"),
  E("jadeface","bajie","foe","一钯打死","火焰山大战时，八戒冲进摩云洞，一钯打死玉面公主，现出了玉面狸的原形。",
    "Killed by his rake","In the battle of the Flaming Mountains Bajie storms into Cloud-Touching Cave and kills Princess Jade Face with his rake; she turns back into a jade-faced civet.","第六十一回"),
  # ---------------------------------------------------------------- demons and the pilgrims
  E("whitebone","tangseng","foe","三戏唐僧","白骨精三次变化来骗唐僧，唐僧只看见悟空打死了三个“好人”。",
    "Three deceptions","Three times the White Bone Demon comes to Tang Sanzang in a new shape, and all he sees is Wukong killing three innocent people.","第二十七回"),
  E("whitebone","wukong","foe","三打白骨精","悟空三次识破白骨精，三次举棒；第三次先叫来山神土地在空中守住去路，才打死了她，却因此被唐僧逐走。",
    "Struck down","Wukong sees through her three times and strikes three times; the third time he first posts the local mountain gods in the sky to cut off her escape, and kills her, and is sent away by his master for it.","第二十七回"),
  E("yellowrobe","tangseng","foe","变作老虎","黄袍怪变成俊秀书生到宝象国认亲，反诬唐僧是虎精，喷口法水把唐僧变成了一只斑斓猛虎。",
    "Turns him into a tiger","Posing as a handsome scholar at the court of Baoxiang, the demon accuses Tang Sanzang of being a tiger spirit, and with a spray of magic water turns him into a tiger.","第三十回"),
  E("yellowrobe","wukong","foe","识破星宿","八戒请回悟空，悟空变成公主等黄袍怪回洞，又上天查明他是奎木狼。",
    "Unmasks the star","Brought back by Bajie, Wukong waits for the demon in the shape of the princess, then goes up to Heaven and discovers he is the Wolf Star.","第三十一回"),
  E("yellowrobe","horse","foe","龙马负伤","白龙马现出龙身，变作宫女去刺黄袍怪，被他用满堂红打伤了后腿。",
    "The horse is wounded","The dragon horse changes back, poses as a palace maid and tries to stab the demon, who wounds him in the hind leg with a heavy candlestick.","第三十回"),
  E("silverhorn","wukong","foe","紫金红葫芦","银角叫一声“孙行者”，悟空不敢应；叫“者行孙”，他随口一应，便被装进葫芦。后来悟空骗得葫芦，反叫一声“银角大王”，把他装了进去。",
    "The red gourd","Silver Horn calls “Sun Wukong!” and Wukong does not answer; but when he answers to a made-up name, he is sucked into the gourd anyway. Later Wukong tricks him out of it, calls his name, and traps him inside.","第三十三回至三十五回"),
  E("goldhorn","silverhorn","kin","兄弟","金角、银角同是老君的看炉童子，下界后在莲花洞称兄道弟，要吃唐僧肉。",
    "Brothers","Both boys tend Laozi’s furnaces, and on earth they rule Lotus Flower Cave together as elder and younger brother, hoping to eat Tang Sanzang.","第三十二回"),
  E("blackbear","wukong","foe","袈裟之争","黑熊精偷走锦襕袈裟，悟空打上黑风山讨要不成，只好去请观音。",
    "The stolen cassock","The bear steals the brocade cassock, and when Wukong cannot get it back by force, he goes to fetch Guanyin.","第十六回、第十七回"),
  E("yellowwind","wukong","foe","三昧神风","黄风怪一口神风吹得悟空两眼酸痛、冷泪直流，唐僧也被他捉去。",
    "The yellow wind","The demon’s wind makes Wukong’s eyes sting and stream, and carries off Tang Sanzang.","第二十回、第二十一回"),
  E("greenox","wukong","foe","金刚琢","青牛精用金刚琢套走悟空的金箍棒，又套走天兵天将的所有兵器和法宝。",
    "The snare","The ox uses the diamond snare to take Wukong’s staff, then every weapon and magic treasure the gods bring against him.","第五十回至五十二回"),
  E("greenlion","wukong","foe","吞下肚去","狮驼岭上，青狮一口吞下悟空，悟空在他肚里翻筋斗、竖蜻蜓，把他折腾得连声求饶。",
    "Swallowed","At Lion-Camel Ridge the lion swallows Wukong in one gulp, and Wukong somersaults and does handstands in his belly until he begs for mercy.","第七十五回"),
  E("whiteelephant","bajie","foe","鼻卷八戒","白象用长鼻子卷住八戒拖回洞里；后来悟空又用棒拄住白象的鼻子，牵着他走。",
    "Caught by the trunk","The elephant coils his trunk around Bajie and drags him off; later Wukong jams his staff up the elephant’s trunk and leads him about by it.","第七十六回"),
  E("roc","tangseng","foe","狮驼国","大鹏占了狮驼国，把满城人吃尽。他们捉住唐僧，还假称已经吃了他，让悟空伤心欲绝。",
    "Lion-Camel City","The roc has taken Lion-Camel City and eaten everyone in it. The demons seize Tang Sanzang and pretend they have already eaten him, leaving Wukong in despair.","第七十四回至七十七回"),
  E("yellowbrow","wukong","foe","金铙","黄眉用金铙把悟空扣住，悟空变大，金铙也变大，最后靠亢金龙的角钻进去才救他出来。",
    "The cymbals","Yellow Brows traps Wukong between his golden cymbals, which grow as he grows; he gets out only when a star god’s horn is forced through the seam.","第六十五回"),
  E("yellowbrow","tangseng","foe","小雷音寺","唐僧见了小雷音寺，不顾悟空劝阻，进门就拜，被假佛祖捉住。",
    "The false temple","Tang Sanzang sees the Lesser Thunderclap Monastery and, ignoring Wukong’s warning, goes in and bows to the false Buddha, who seizes him.","第六十五回"),
  E("saitaisui","wukong","foe","紫金铃","悟空变作小妖进洞，偷换了紫金铃，与赛太岁对阵摇铃，放出烟火黄沙。",
    "The golden bells","Wukong gets into the cave as a little demon, swaps the golden bells for fakes, and turns their fire, smoke and sand on their owner.","第七十回、第七十一回"),
  E("goldfish","tangseng","foe","通天河","灵感大王让通天河结冰，诱唐僧踏冰过河，冰裂后把他捉进水府。",
    "The frozen river","The goldfish freezes the River to Heaven, lures Tang Sanzang onto the ice, cracks it and carries him down to his palace.","第四十八回"),
  E("jaderabbit","tangseng","tie","抛绣球招亲","玉兔变成的公主抛绣球正打中唐僧，要招他为驸马，其实想采他的元阳。",
    "The embroidered ball","The false princess throws the embroidered ball that picks her husband and hits Tang Sanzang; what she really wants is his vital essence.","第九十三回、第九十五回"),
  E("mouse","tangseng","tie","逼婚","老鼠精把唐僧掳进无底洞，要与他成亲。",
    "Forced marriage","The mouse spirit carries Tang Sanzang down into her Bottomless Cave and tries to marry him.","第八十一回、第八十二回"),
  E("mouse","wukong","foe","无底洞","悟空变成桃子让她吞下，在她肚里逼她放人；又在洞中找到李靖父子的牌位，上天告状。",
    "The Bottomless Cave","Wukong has her swallow him as a peach and bullies her from inside; then he finds her tablets to Li Jing and Nezha and takes them to Heaven as evidence.","第八十二回、第八十三回"),
  E("spiders","tangseng","foe","盘丝洞","唐僧抢着去化斋，落入盘丝洞，被七个女妖用丝绳吊了起来。",
    "Silk Cave","Tang Sanzang insists on begging for food himself and walks into Silk Cave, where the seven women hang him up with their silk.","第七十二回"),
  E("spiders","bajie","tie","濯垢泉","八戒趁七个女妖在濯垢泉洗澡，变成鲇鱼在她们腿间钻来钻去，结果被她们用丝绳绊得跌跌撞撞。",
    "The spring","While the seven bathe in the Filth-Cleansing Spring, Bajie turns into a catfish and wriggles between their legs, and ends up tangled and tripped by their silk.","第七十二回"),
  E("spiders","wukong","foe","打死七怪","七个蜘蛛精逃到师兄百眼魔君的黄花观，悟空把七怪打死；百眼魔君后来由毗蓝婆菩萨收去。",
    "Kills the seven","The spiders flee to their senior brother at the Yellow Flower Abbey, and Wukong kills all seven; the brother, a centipede demon, is later taken away by Bodhisattva Pilanpo.","第七十三回"),
  E("sixear","wukong","foe","真假美猴王","六耳猕猴冒充悟空，两个悟空从花果山打到南海、天宫、地府，最后打到灵山，如来说出真相，悟空一棒打死了他。",
    "Two Monkey Kings","The Six-Eared Macaque impersonates Wukong, and the two fight from the Mountain of Flowers and Fruit to the Southern Sea, Heaven and the underworld, and finally to Vulture Peak, where the Buddha tells the truth and Wukong kills him.","第五十六回至五十八回"),
  E("sixear","tangseng","foe","打伤唐僧","唐僧赶走悟空后，假悟空回来送水，唐僧不肯要，他一棒打伤唐僧，抢走了包袱。",
    "Strikes the master","After the monk sends Wukong away, the impostor comes back with water; when Tang Sanzang refuses it, he strikes him down with his staff and makes off with the luggage.","第五十六回、第五十七回"),
  E("ninehead","wukong","foe","碧波潭","悟空与八戒为祭赛国讨还佛宝，打进碧波潭；八戒一钯打死了万圣龙王，九头虫最后被二郎神的细犬咬伤逃走。",
    "The Green Wave Pool","Wukong and Bajie storm the Green Wave Pool to recover the stolen relic; Bajie kills the old dragon king, and the Nine-Headed Bug flees after Erlang’s hound bites off a head.","第六十二回、第六十三回"),
  E("tuolong","tangseng","foe","黑水河","鼍龙扮成艄公，把唐僧和八戒连船带人卷进黑水河底。",
    "The Black River","Posing as a ferryman, the Alligator Dragon sinks the boat and drags Tang Sanzang and Bajie to the bottom of the Black River.","第四十三回"),
]

EDGE_TYPES = {
  "kin": dict(zh="亲缘", en="Kin", desc="血缘、婚姻与义亲", desc_en="Blood, marriage and adoption"),
  "mas": dict(zh="主从", en="Master & servant", desc="神佛与坐骑、童子、宠物、下属", desc_en="Gods and their mounts, pages, pets and subordinates"),
  "aid": dict(zh="友助", en="Ally", desc="师徒、庇护、相助与友谊", desc_en="Teachers, protection, help and friendship"),
  "foe": dict(zh="敌对", en="Enemy", desc="交战、加害、欺骗", desc_en="Combat, harm, deception"),
  "tie": dict(zh="纠葛", en="Entangled", desc="恩怨交织、贬罚、考验与缘分", desc_en="Mixed motives, punishment, tests and fate"),
}

CN = {'零': 0, '一': 1, '二': 2, '三': 3, '四': 4, '五': 5, '六': 6, '七': 7, '八': 8, '九': 9}


def cn_int(s):
    """一百, 九十五, 十四, 二十 -> int."""
    if s == '一百':
        return 100
    if '十' in s:
        a, b = s.split('十')
        return (CN[a] if a else 1) * 10 + (CN[b] if b else 0)
    return CN[s]


def ch_en(ref):
    """'第十四回' -> 'Chapter 14'; '第五十九回至六十一回' -> 'Chapters 59–61'; '第八回、第二十二回' -> 'Chapters 8, 22'."""
    parts, count = [], 0
    for seg in ref.split('、'):
        seg = seg.replace('第', '').replace('回', '')
        if '至' in seg:
            a, b = seg.split('至')
            parts.append(f'{cn_int(a)}–{cn_int(b)}')
            count += 2
        else:
            parts.append(str(cn_int(seg)))
            count += 1
    return ('Chapters ' if count > 1 else 'Chapter ') + ', '.join(parts)
