# -*- coding: utf-8 -*-
"""Aeneid characters and relationships, Chinese and English.
cat:   god / demi (child of a god and a mortal) / mortal / monster
camp:  pro (gods who favor Aeneas) / contra (powers against the Trojans) / neutral (Jupiter)
       troy / greek / carthage / cumae / arcadia / italy / none
dies:  book in which the character dies within the poem (Book 2's fall of Troy included), or None
style: fresco palette for the portrait: fg (gods) / fm (mortals) / fx (monsters) / fs (ghosts)
la:    Latin name; same_as: id of the same figure in the other books (Greek name), if different
"""

N = lambda **k: k

NODES = [
  # ------------------------------------------------------------------ gods
  N(id="jupiter", zh="朱庇特", la="Iuppiter", en="Jupiter", same_as="zeus", cat="god", camp="neutral", dies=None, style="fg",
    sub=("众神之王", "King of the gods"),
    bio=("众神之王，命运的执行者。他向维纳斯许诺：埃涅阿斯的后代将建立罗马，“我给他们的统治没有疆界，也没有期限”。卷十二，他与朱诺和解：特洛伊人可以留在意大利，但要改用拉丁人的名字和语言。",
         "King of the gods and the enforcer of fate. He promises Venus that Aeneas's descendants will found Rome: “For them I set no limits in space or time; I have given them empire without end.” In Book 12 he makes peace with Juno: the Trojans may stay in Italy, but they will take the Latins' name and language."),
    icon=("长须、月桂冠与霹雳。", "Long beard, laurel wreath and thunderbolt.")),
  N(id="juno", zh="朱诺", la="Iuno", en="Juno", same_as="hera", cat="god", camp="contra", dies=None, style="fg",
    sub=("天后", "Queen of the gods"),
    bio=("天后，全诗一切磨难的推手。她恨特洛伊人：为帕里斯的评判，为宙斯宠爱特洛伊少年伽倪墨得斯，更因为命运说特洛伊人的后代将毁灭她心爱的迦太基。她掀起海难，促成狄多的“婚姻”，又从冥府唤出复仇女神点燃战火：“如果我不能说动天上的神，我就去搅动冥河。”",
         "Queen of the gods and the force behind every hardship in the poem. She hates the Trojans for the judgment of Paris, for Jupiter's love of the Trojan boy Ganymede, and above all because fate says their descendants will destroy her beloved Carthage. She raises the storm, arranges Dido's “marriage”, and calls up a Fury to start the war: “If I cannot bend the gods above, I will stir up the underworld.”"),
    icon=("高冠、面纱与王杖。", "Tall crown, veil and scepter.")),
  N(id="venus", zh="维纳斯", la="Venus", en="Venus", same_as="aphrodite", cat="god", camp="pro", dies=None, style="fg",
    sub=("爱神 · 埃涅阿斯之母", "Goddess of love, Aeneas's mother"),
    bio=("爱与美之神，埃涅阿斯的母亲。她扮作猎女在迦太基城外为儿子指路，派丘比特让狄多爱上他；又请丈夫伏尔甘打造铠甲，在儿子中箭时送来仙草白鲜。",
         "Goddess of love and beauty, and Aeneas's mother. Disguised as a huntress she shows her son the way to Carthage, and sends Cupid to make Dido fall in love with him; she has her husband Vulcan forge his armor, and brings healing dittany when he is wounded by an arrow."),
    icon=("头冠与鸽子——她派一对鸽子为埃涅阿斯引路，找到金枝（卷六）。", "Diadem and dove: a pair of her doves leads Aeneas to the golden bough (Book 6).")),
  N(id="neptune", zh="尼普顿", la="Neptunus", en="Neptune", same_as="poseidon", cat="god", camp="pro", dies=None, style="fg",
    sub=("海神", "God of the sea"),
    bio=("海神。他平息了朱诺掀起的风暴，喝退群风；可在特洛伊陷落之夜，埃涅阿斯也看见他用三叉戟撼动城墙。卷五，他答应维纳斯让船队平安抵达意大利，代价是“一人替众人而死”——舵手帕里努鲁斯。",
         "God of the sea. He calms the storm Juno raised and drives off the winds; yet on Troy's last night Aeneas sees him heaving at its walls with his trident. In Book 5 he promises Venus a safe crossing to Italy at the price of “one life for many”: the helmsman Palinurus."),
    icon=("长须、发带与三叉戟。", "Long beard, headband and trident.")),
  N(id="mercury", zh="墨丘利", la="Mercurius", en="Mercury", same_as="hermes", cat="god", camp="pro", dies=None, style="fg",
    sub=("神使", "Messenger god"),
    bio=("神使，朱庇特之子。他先让迦太基人善待落难的特洛伊人；后来两次奉命催埃涅阿斯离开迦太基，第二次是在梦里：“女人总是反复无常。”",
         "Messenger of the gods and son of Jupiter. First he makes the Carthaginians kind to the shipwrecked Trojans; later, on Jupiter's orders, he twice tells Aeneas to leave Carthage, the second time in a dream: “A woman is always a fickle, changing thing.”"),
    icon=("带翼的宽檐帽与双蛇杖。", "Winged traveler's hat and herald's staff.")),
  N(id="vulcan", zh="伏尔甘", la="Vulcanus", en="Vulcan", same_as="hephaestus", cat="god", camp="pro", dies=None, style="fg",
    sub=("火神 · 匠神", "God of the forge"),
    bio=("火与锻造之神，维纳斯的丈夫。经不住妻子的温言恳求，他为埃涅阿斯（维纳斯与凡人所生的儿子）打造铠甲；那面盾牌上刻着罗马未来的历史，一直刻到奥古斯都在亚克兴的胜利。",
         "God of fire and the forge, and Venus's husband. Won over by his wife's caresses, he makes armor for Aeneas, her son by a mortal; the shield shows the future history of Rome, all the way down to Augustus's victory at Actium."),
    icon=("工匠小帽、锤子与火钳。", "Craftsman's cap, hammer and tongs.")),
  N(id="apollo", zh="阿波罗", la="Apollo", en="Apollo", cat="god", camp="pro", dies=None, style="fg",
    sub=("预言之神", "God of prophecy"),
    bio=("预言之神。他在得洛斯岛指示特洛伊人“去寻找你们古老的母亲”——意大利；又借先知赫勒诺斯和库迈的女先知之口揭示前路。卷九，他夸奖初上战场的阿斯卡纽斯，又劝他就此罢手。",
         "God of prophecy. On Delos he tells the Trojans to “seek out your ancient mother”, which turns out to mean Italy, and he reveals the way ahead through the seer Helenus and the Sibyl of Cumae. In Book 9 he praises young Ascanius for his first kill, then tells him to fight no more."),
    icon=("月桂冠与里拉琴。", "Laurel wreath and lyre.")),
  N(id="minerva", zh="密涅瓦", la="Minerva", en="Minerva", same_as="athena", cat="god", camp="contra", dies=None, style="fg",
    sub=("智慧女神", "Goddess of wisdom"),
    bio=("智慧与战争女神，特洛伊的敌人。希腊人谎称木马是献给她的祭品；缠死拉奥孔父子的巨蛇，事后躲到了她神像的盾牌下。特洛伊陷落之夜，埃涅阿斯看见她高踞卫城，手持戈尔工盾。",
         "Goddess of wisdom and war, and Troy's enemy. The Greeks pass off the wooden horse as an offering to her; the serpents that kill Laocoön and his sons take refuge under her statue's shield. On Troy's last night Aeneas sees her on the citadel, with the Gorgon on her shield."),
    icon=("高冠头盔与猫头鹰。", "Crested helmet and owl.")),
  N(id="cupid", zh="丘比特", la="Cupido", en="Cupid", cat="god", camp="pro", dies=None, style="fg",
    sub=("小爱神", "God of desire"),
    bio=("维纳斯之子，埃涅阿斯同母异父的弟弟。母亲命他扮成阿斯卡纽斯，在宴会上坐进狄多怀里，让她一点点忘掉亡夫、爱上埃涅阿斯。",
         "Venus's son and Aeneas's half-brother. On his mother's orders he takes the form of Ascanius and, at the banquet, settles in Dido's lap, slowly wiping out the memory of her dead husband and filling her with love for Aeneas."),
    icon=("双翼与小弓。", "Wings and a small bow.")),
  N(id="aeolus", zh="埃俄罗斯", la="Aeolus", en="Aeolus", cat="god", camp="contra", dies=None, style="fg",
    sub=("风神", "King of the winds"),
    bio=("风的看守者，把群风关在山洞里。朱诺许他一位最美的仙女为妻，他便用矛尖击开山体，放出狂风，把特洛伊船队打散在海上。",
         "Keeper of the winds, who holds them locked in a mountain cave. When Juno offers him the loveliest of her nymphs as a wife, he strikes the mountain with his spear and lets the storm loose on the Trojan fleet."),
    icon=("王杖与翻卷的风。", "Scepter and swirling winds.")),
  N(id="juturna", zh="尤图尔娜", la="Iuturna", en="Juturna", cat="god", camp="contra", dies=None, style="fg",
    sub=("泉水仙女 · 图尔努斯之妹", "Nymph of springs, Turnus's sister"),
    bio=("图尔努斯的妹妹。朱庇特夺走她的贞洁，作为补偿让她成为不死的泉水仙女。卷十二，朱诺怂恿她救兄长：她搅乱停战誓约，又扮成车夫载着图尔努斯避开埃涅阿斯。直到朱庇特派来的复仇女神化作怪鸟，她才明白兄长必死，哀叹自己不能随他死去，沉入了河中。",
         "Turnus's sister. Jupiter took her virginity and in return made her an immortal nymph of the springs. In Book 12 Juno urges her to save her brother: she wrecks the truce and, disguised as his charioteer, keeps Turnus away from Aeneas. When a Fury sent by Jupiter comes in the shape of a bird, she knows he must die, laments that she cannot die with him, and sinks into her river."),
    icon=("面纱与水罐。", "Veil and water jar.")),
  # ------------------------------------------------------------------ monsters
  N(id="allecto", zh="阿列克托", la="Allecto", en="Allecto", cat="monster", camp="contra", dies=None, style="fx",
    sub=("复仇女神", "A Fury"),
    bio=("复仇三女神之一，连她的父亲冥王和她的姐妹都厌恶她。朱诺把她从冥府唤出：她把一条蛇投进王后阿玛塔的胸口，把火把插进图尔努斯的心，又让阿斯卡纽斯的猎犬去追一头人人珍爱的家养牡鹿——战争就此爆发。",
         "One of the Furies, loathed even by her father Pluto and her own sisters. Called up by Juno, she throws a snake into Queen Amata's breast, drives a torch into Turnus's heart, and sets Ascanius's hounds on a much-loved tame stag. The war begins."),
    icon=("蛇发与火把。", "Snakes for hair, and a torch.")),
  N(id="polyphemus", zh="波吕斐摩斯", la="Polyphemus", en="Polyphemus", cat="monster", camp="none", dies=None, style="fx",
    sub=("独眼巨人", "The Cyclops"),
    bio=("被尤利西斯刺瞎的独眼巨人。特洛伊人在西西里登岸时，正撞见他拄着松树干摸索着下海，清洗眼窝里的血；他听见划桨声涉水追来，一声怒吼唤来了成群的独眼巨人，特洛伊人拼命划船逃走。",
         "The Cyclops blinded by Ulysses. When the Trojans land in Sicily, they see him feeling his way into the sea with a pine trunk for a staff, to wash the blood from his eye socket; hearing their oars, he wades after them, and his roar brings the other Cyclopes crowding to the shore as the Trojans row for their lives."),
    icon=("独眼巨人的大眼与蓬乱的须发。", "The Cyclops's great eye and shaggy hair and beard.")),
  N(id="celaeno", zh="刻莱诺", la="Celaeno", en="Celaeno", cat="monster", camp="none", dies=None, style="fx",
    sub=("鸟身女妖之首", "Chief of the Harpies"),
    bio=("鸟身女妖（哈耳皮埃）之首，住在斯特洛法得斯群岛。特洛伊人宰了她们的牛群，她们便扑下来抢食、弄脏宴席。刻莱诺诅咒他们：不到饿得啃桌子的那一天，你们的城墙就建不起来。",
         "Chief of the Harpies, the bird-bodied women of the Strophades islands. The Trojans slaughter their cattle, and the Harpies swoop down to snatch and foul the feast. Celaeno curses them: they will not wall their city until hunger drives them to eat their tables."),
    icon=("少女的脸、鸟的身子与利爪。", "A girl's face, a bird's body and talons.")),
  # ------------------------------------------------------------------ Trojans
  N(id="aeneas", zh="埃涅阿斯", la="Aeneas", en="Aeneas", cat="demi", camp="troy", dies=None, style="fm",
    sub=("特洛伊王子 · 罗马人的先祖", "Trojan prince, ancestor of the Romans"),
    bio=("维纳斯与安奇塞斯之子。特洛伊陷落时，他背起父亲、牵着儿子逃出火城，奉命运去意大利建立新邦。他在迦太基与狄多相爱又弃她而去，下到冥府见到父亲和罗马未来的英雄，最后在拉丁姆的战争中杀死图尔努斯。维吉尔称他“虔敬的埃涅阿斯”：对神、对父亲、对使命尽责。",
         "Son of Venus and Anchises. When Troy falls he carries his father on his back and leads his son out of the burning city, bound by fate to found a new home in Italy. He loves and leaves Dido in Carthage, goes down to the underworld to meet his father and the Roman heroes to come, and at last kills Turnus in the war in Latium. Virgil calls him “pious Aeneas”: dutiful to the gods, to his father and to his mission."),
    icon=("头盔与金盾——伏尔甘为他打造的盾牌。", "Helmet and a golden shield, the one Vulcan made for him.")),
  N(id="anchises", zh="安奇塞斯", la="Anchises", en="Anchises", cat="mortal", camp="troy", dies="卷三", style="fm",
    sub=("埃涅阿斯之父", "Aeneas's father"),
    bio=("埃涅阿斯的父亲，年轻时曾得维纳斯垂爱，后来被朱庇特的雷电所伤。特洛伊陷落时他本不肯走，直到孙子头上燃起火焰的吉兆；他怀抱家神、坐在儿子肩上出城，后来死在西西里的德瑞帕努姆。卷六，他在冥府的乐土为儿子指点罗马未来的伟人。",
         "Aeneas's father, once loved by Venus and later struck by Jupiter's lightning. When Troy falls he refuses to leave until a flame appears on his grandson's head as an omen; then he rides out on his son's shoulders, holding the household gods. He dies at Drepanum in Sicily. In Book 6, in the Elysian Fields, he shows his son the great Romans of the future."),
    icon=("弗里吉亚帽、白须与家神像——他抱着家神出城。", "Phrygian cap, white beard and a household god, which he carried out of Troy.")),
  N(id="creusa", zh="克列乌莎", la="Creusa", en="Creusa", cat="mortal", camp="troy", dies="卷二", style="fm",
    sub=("埃涅阿斯之妻", "Aeneas's wife"),
    bio=("埃涅阿斯的妻子，阿斯卡纽斯的母亲，传说是普里阿摩斯的女儿。出逃时她跟在后面，在混乱中走失。埃涅阿斯冲回火城寻找，只遇见她的亡魂：她说远方有新的王国和一位王族妻子在等他，请他爱护他们的儿子。他三次想拥抱她，三次扑空。",
         "Aeneas's wife and Ascanius's mother; in tradition, a daughter of Priam. Following behind in the escape, she is lost in the confusion. Aeneas runs back into the burning city and meets only her ghost: she tells him a kingdom and a royal bride await him far away, and asks him to cherish their son. Three times he tries to embrace her; three times she slips through his arms."),
    icon=("面纱。", "Veil.")),
  N(id="ascanius", zh="阿斯卡纽斯", la="Ascanius", en="Ascanius", cat="mortal", camp="troy", dies=None, style="fm",
    sub=("埃涅阿斯之子，又名尤路斯", "Aeneas's son, also called Iulus"),
    bio=("埃涅阿斯与克列乌莎的儿子，又名尤路斯；维吉尔说，罗马的尤利乌斯家族（恺撒与奥古斯都）由此得名。他头上燃起的火焰让祖父决定出逃；在意大利，他射中一头家养的牡鹿，点燃了战争，又在卷九射杀了辱骂特洛伊人的努玛努斯。",
         "Son of Aeneas and Creusa, also called Iulus; the Julian family of Caesar and Augustus, Virgil says, takes its name from him. The flame that plays on his head persuades his grandfather to leave Troy; in Italy he shoots a tame stag and starts the war, and in Book 9 he kills Numanus, who has been taunting the Trojans, with an arrow."),
    icon=("弗里吉亚帽、头上的火焰与弓。", "Phrygian cap, the flame on his head, and a bow.")),
  N(id="achates", zh="阿卡特斯", la="Achates", en="Achates", cat="mortal", camp="troy", dies=None, style="fm",
    sub=("忠实的伙伴", "Faithful companion"),
    bio=("埃涅阿斯形影不离的伙伴，诗中总称他“忠实的阿卡特斯”。海难后是他敲打燧石生起火来；在迦太基，他与埃涅阿斯一同隐身于云雾中进城。",
         "Aeneas's constant companion, called “faithful Achates” throughout the poem. After the shipwreck he strikes a spark from flint to light a fire; in Carthage he walks into the city beside Aeneas, both hidden in a cloud."),
    icon=("燧石与火星。", "Flint and sparks.")),
  N(id="palinurus", zh="帕里努鲁斯", la="Palinurus", en="Palinurus", cat="mortal", camp="troy", dies="卷五", style="fm",
    sub=("舵手", "The helmsman"),
    bio=("埃涅阿斯的舵手。尼普顿要“一人替众人而死”，睡神便在夜里把他推入海中，连同舵柄一起。他在海上漂了三天，爬上意大利海岸时被当地人杀害。卷六，他未得安葬的亡魂在冥河边求埃涅阿斯带他过河，女先知许诺，将有一处海角以他为名。",
         "Aeneas's helmsman. Neptune demands “one life for many”, and in the night the god of Sleep tips him overboard, still holding the tiller. He drifts for three days, reaches the Italian shore and is murdered there. In Book 6 his unburied ghost begs Aeneas to take him across the river of the dead; the Sibyl promises him that a headland will bear his name."),
    icon=("舵桨。", "A steering oar.")),
  N(id="priam", zh="普里阿摩斯", la="Priamus", en="Priam", cat="mortal", camp="troy", dies="卷二", style="fm",
    sub=("特洛伊老王", "King of Troy"),
    bio=("特洛伊的老王。城破之夜，他穿上多年不用的铠甲，被赫卡柏劝到祭坛前避难；皮鲁斯当着他的面杀死他的儿子波利忒斯，又拖着老人滑过儿子的血泊，把剑刺进他的肋下。“海岸上躺着一具巨大的躯干，头已离肩，一具没有名字的尸体。”",
         "The old king of Troy. On the last night he puts on armor he has not worn in years, and Hecuba persuades him to take refuge at the altar; Pyrrhus kills his son Polites before his eyes, then drags the old man, slipping in his son's blood, to the altar and drives a sword into his side. “He lies on the shore, a huge trunk, the head torn from the shoulders, a body without a name.”"),
    icon=("白须、王冠与长矛——城破之夜他掷向皮鲁斯的那无力的一矛。", "White beard, crown and a spear: the feeble spear he throws at Pyrrhus on the last night.")),
  N(id="hector", zh="赫克托尔", la="Hector", en="Hector", cat="mortal", camp="troy", dies=None, style="fs",
    sub=("亡魂 · 特洛伊的英雄", "Troy's hero, now a ghost"),
    bio=("特洛伊最勇敢的英雄，此时早已战死。城破之夜，他的亡魂出现在埃涅阿斯梦中，满身血污尘土，正是被阿喀琉斯拖在战车后的模样。他催埃涅阿斯快逃，把特洛伊的圣物与家神托付给他：“为它们去寻找城池。”",
         "Troy's greatest hero, long dead by now. On the night Troy falls his ghost comes to Aeneas in a dream, filthy with blood and dust as when Achilles dragged him behind his chariot. He urges Aeneas to flee and entrusts Troy's holy things and household gods to him: “Seek walls for them.”"),
    icon=("淡色的亡魂，仍戴着高高的盔缨。", "Drawn pale as a ghost, still wearing his tall crest.")),
  N(id="laocoon", zh="拉奥孔", la="Laocoon", en="Laocoön", cat="mortal", camp="troy", dies="卷二", style="fm",
    sub=("尼普顿的祭司", "Priest of Neptune"),
    bio=("特洛伊的祭司。他从卫城跑下来警告众人：“我怕希腊人，哪怕他们带着礼物。”并把长矛掷进木马的肚子。随后他正为尼普顿献祭，两条巨蛇从海上游来，先缠死他的两个儿子，再缠死了他。特洛伊人以为这是他刺木马的报应，于是把木马拖进了城。",
         "A Trojan priest. He runs down from the citadel to warn the crowd, “I fear the Greeks, even bearing gifts,” and hurls his spear into the horse's side. Soon after, as he sacrifices to Neptune, two giant serpents swim in from the sea and crush his two sons, then him. Taking it as punishment for striking the horse, the Trojans drag it into the city."),
    icon=("缠绕的巨蛇。", "Coiling serpents.")),
  N(id="andromache", zh="安德罗马刻", la="Andromache", en="Andromache", cat="mortal", camp="troy", dies=None, style="fm",
    sub=("赫克托尔的遗孀", "Hector's widow"),
    bio=("赫克托尔的遗孀。特洛伊陷落后，她先被皮鲁斯据为奴妾，后被转给赫勒诺斯为妻。埃涅阿斯在布特罗通遇见她时，她正在赫克托尔的空坟前祭奠。临别时，她把亲手织的衣物送给阿斯卡纽斯——他让她想起自己死去的儿子阿斯提阿那克斯。",
         "Hector's widow. After Troy falls she becomes Pyrrhus's slave and concubine, then is handed on to Helenus as his wife. When Aeneas finds her at Buthrotum, she is making offerings at Hector's empty tomb. At parting she gives Ascanius clothes she wove herself: he reminds her of her dead son Astyanax."),
    icon=("面纱与泪水。", "Veil and tears.")),
  N(id="helenus", zh="赫勒诺斯", la="Helenus", en="Helenus", cat="mortal", camp="troy", dies=None, style="fm",
    sub=("普里阿摩斯之子 · 先知", "Priam's son, a seer"),
    bio=("普里阿摩斯的儿子，阿波罗的先知。皮鲁斯死后他得到一部分国土，在伊庇鲁斯建了一座“小特洛伊”。他为埃涅阿斯详细指路：避开意大利的近岸，躲过斯库拉与卡律布狄斯，去库迈找女先知；看见白母猪带着三十头小猪的地方，就是建城之地。",
         "Priam's son and a prophet of Apollo. After Pyrrhus's death he inherits part of his kingdom and builds a “little Troy” in Epirus. He gives Aeneas detailed directions: avoid the near coast of Italy, steer clear of Scylla and Charybdis, consult the Sibyl at Cumae; where he finds a white sow with thirty piglets, there he will found his city."),
    icon=("弗里吉亚帽与月桂。", "Phrygian cap and laurel.")),
  N(id="nisus", zh="尼苏斯", la="Nisus", en="Nisus", cat="mortal", camp="troy", dies="卷九", style="fm",
    sub=("特洛伊勇士", "Trojan warrior"),
    bio=("特洛伊营地的守门人，欧律阿鲁斯的挚友。卷五赛跑中他滑倒在血泊里，顺势绊倒对手，让欧律阿鲁斯夺冠。卷九，两人趁夜出营去找埃涅阿斯，一路砍杀熟睡的敌兵；欧律阿鲁斯被捉，尼苏斯冲出去救他，两人一同战死。",
         "Guard of a gate in the Trojan camp and Euryalus's devoted friend. In the footrace of Book 5 he slips in blood and trips a rival so that Euryalus can win. In Book 9 the two slip out at night to find Aeneas, killing sleeping enemies on the way; when Euryalus is caught, Nisus charges in to save him, and both die."),
    icon=("胡须与长矛。", "Beard and spear.")),
  N(id="euryalus", zh="欧律阿鲁斯", la="Euryalus", en="Euryalus", cat="mortal", camp="troy", dies="卷九", style="fm",
    sub=("尼苏斯的伙伴", "Nisus's companion"),
    bio=("特洛伊营中最俊美的少年，母亲为了他随军远行。夜袭时他戴上从敌人那里夺来的闪亮头盔，月光一照，暴露了行踪。他死时“像一朵被犁割断的紫色花”。",
         "The handsomest young man among the Trojans, whose mother followed the army for his sake. On the night raid he puts on a gleaming helmet taken from the enemy; it catches the moonlight and gives them away. He dies “like a purple flower cut down by the plow”."),
    icon=("闪亮的金盔。", "A gleaming golden helmet.")),
  # ------------------------------------------------------------------ Greeks
  N(id="helen", zh="海伦", la="Helena", en="Helen", cat="demi", camp="greek", dies=None, style="fm",
    sub=("斯巴达王后", "Queen of Sparta"),
    bio=("斯巴达王后，特洛伊战争的起因。城破之夜，埃涅阿斯撞见她躲在维斯塔神庙里，一度想杀了她泄愤，被母亲维纳斯拦住：毁掉特洛伊的不是海伦，而是众神。卷六又说，她在城破时藏起丈夫得伊福玻斯的剑，把他出卖给希腊人。（卷二这段海伦诗行只见于古代注疏家的引用，学者怀疑是否出自维吉尔之手。）",
         "Queen of Sparta and the cause of the war. On Troy's last night Aeneas finds her hiding at the shrine of Vesta and is about to kill her in his anger when Venus stops him: it is not Helen but the gods who are destroying Troy. In Book 6 we learn she hid her husband Deiphobus's sword and betrayed him to the Greeks. (The Helen passage in Book 2 survives only through an ancient commentator, and scholars doubt Virgil wrote it.)"),
    icon=("头冠、面纱与铜镜。", "Diadem, veil and a bronze mirror.")),
  N(id="sinon", zh="西农", la="Sinon", en="Sinon", cat="mortal", camp="greek", dies=None, style="fm",
    sub=("希腊间谍", "Greek spy"),
    bio=("故意被俘的希腊人。他哭诉自己因得罪尤利西斯而被选作活祭、侥幸逃脱，骗得普里阿摩斯下令为他松绑；又说木马是献给密涅瓦的赎罪之物，拖进城就能保佑特洛伊。夜里，他打开木马的机关，放出藏在里面的希腊人。",
         "A Greek who lets himself be captured. He weeps that Ulysses had him picked out as a human sacrifice and that he barely escaped, and Priam orders his bonds removed; he claims the horse is an offering to Minerva that will protect Troy if brought inside. That night he unbolts the horse and lets out the Greeks hidden in it."),
    icon=("木马的头。", "The head of the wooden horse.")),
  N(id="pyrrhus", zh="皮鲁斯", la="Pyrrhus", en="Pyrrhus", cat="mortal", camp="greek", dies=None, style="fm",
    sub=("阿喀琉斯之子", "Achilles's son"),
    bio=("阿喀琉斯之子，又名涅俄普托勒摩斯。城破之夜，他像一条蜕了皮的蛇，铜甲闪亮，砸开王宫的大门；他杀死波利忒斯和普里阿摩斯，战后把安德罗马刻据为奴妾，后来被俄瑞斯忒斯杀死。",
         "Achilles's son, also called Neoptolemus. On Troy's last night he gleams in bronze like a snake that has shed its skin, and he batters down the palace doors; he kills Polites and Priam, takes Andromache as his slave and concubine, and is later killed by Orestes."),
    icon=("闪亮的铜盔与长矛。", "Gleaming bronze helmet and spear.")),
  N(id="ulysses", zh="尤利西斯", la="Ulixes", en="Ulysses", same_as="odysseus", cat="mortal", camp="greek", dies=None, style="fm",
    sub=("希腊智将", "The Greek schemer"),
    bio=("奥德修斯的罗马名。在特洛伊人口中，他是“残忍的尤利西斯”“罪行的设计者”：他与狄奥墨得斯偷走密涅瓦的神像，西农的谎言也围绕他编造。他逃离独眼巨人时，把同伴阿开墨尼德斯遗落在了西西里。他在诗中从未亲自出场，只活在别人的讲述里。",
         "The Roman name of Odysseus. In Trojan mouths he is “cruel Ulysses”, “the contriver of crimes”: with Diomedes he steals Minerva's sacred statue, and Sinon's lies are built around him. Escaping the Cyclops, he leaves his companion Achaemenides behind on Sicily. He never appears in person; he lives only in other people's stories."),
    icon=("水手帽与弓。", "Sailor's cap and bow.")),
  N(id="achaemenides", zh="阿开墨尼德斯", la="Achaemenides", en="Achaemenides", cat="mortal", camp="greek", dies=None, style="fm",
    sub=("被遗弃的希腊人", "A Greek left behind"),
    bio=("尤利西斯的部下，同伴逃离独眼巨人时把他忘在了西西里，他靠野果草根活了三个月。他衣衫褴褛，衣服用荆棘别着，向特洛伊人哀求：带我走，或者杀了我，死在人手里总好过被巨人吃掉。安奇塞斯向他伸出了右手。",
         "One of Ulysses's men, forgotten on Sicily when his companions escaped the Cyclops; he has lived three months on berries and roots. In rags pinned together with thorns, he begs the Trojans to take him, or kill him: better to die at human hands. Anchises gives him his right hand."),
    icon=("蓬乱的头发与胡须。", "Wild, matted hair and beard.")),
  N(id="diomedes", zh="狄奥墨得斯", la="Diomedes", en="Diomedes", cat="mortal", camp="greek", dies=None, style="fm",
    sub=("阿尔庇的希腊国王", "Greek king at Arpi"),
    bio=("特洛伊战争中的希腊猛将，战后在意大利南部建城阿尔庇。拉丁人派使者求他出兵，他拒绝了：他曾刺伤维纳斯，归途中同伴都变成了鸟。他说埃涅阿斯是特洛伊最难对付的敌手之一，劝拉丁人讲和。",
         "A great Greek fighter at Troy, who afterward founded Arpi in southern Italy. When the Latins send envoys to ask for his help, he refuses: he once wounded Venus, and on his way home his companions were turned into birds. He tells them Aeneas was one of Troy's two most formidable fighters, and urges them to make peace."),
    icon=("王冠与飞鸟——他的同伴在归途中变成了鸟。", "A crown and a bird: on the way home his companions were turned into birds.")),
  # ------------------------------------------------------------------ Carthage, Cumae
  N(id="dido", zh="狄多", la="Dido", en="Dido", cat="mortal", camp="carthage", dies="卷四", style="fm",
    sub=("迦太基女王", "Queen of Carthage"),
    bio=("腓尼基推罗城的公主。丈夫许凯斯被她贪财的哥哥皮格马利翁杀害后，她带人逃到北非，建立迦太基。她收留遭遇海难的特洛伊人，爱上了埃涅阿斯；两人在山洞避雨时结合，她称之为婚姻。埃涅阿斯奉神命离去，她诅咒他的后代与迦太基世代为敌，用他留下的剑自尽。卷六在冥府，她一言不发，转身回到亡夫身边。",
         "A princess of Tyre. After her greedy brother Pygmalion murders her husband Sychaeus, she flees to Africa and founds Carthage. She takes in the shipwrecked Trojans and falls in love with Aeneas; they come together in a cave during a storm, and she calls it marriage. When he leaves at the gods' command, she curses his descendants with Carthage's undying enmity and kills herself with the sword he left behind. In the underworld in Book 6 she will not say a word to him, and turns back to her husband."),
    icon=("头冠、面纱与棕榈枝——棕榈是迦太基的象征；她穿推罗紫袍。", "Diadem, veil and a palm frond, the emblem of Carthage; her robe is Tyrian purple.")),
  N(id="anna", zh="安娜", la="Anna", en="Anna", cat="mortal", camp="carthage", dies=None, style="fm",
    sub=("狄多的妹妹", "Dido's sister"),
    bio=("狄多的妹妹和知心人。是她劝姐姐放下守寡的誓言，接受埃涅阿斯；埃涅阿斯要走时，她替姐姐一次次去求情。她照狄多的吩咐搭起火葬堆，却不知道那是为姐姐自己准备的。",
         "Dido's sister and confidante. It is Anna who persuades Dido to set aside her vow of widowhood and accept Aeneas; when he prepares to leave, she carries her sister's pleas to him again and again. She builds the pyre at Dido's bidding, not knowing it is meant for Dido herself."),
    icon=("发带与项链。", "Headband and necklace.")),
  N(id="sychaeus", zh="许凯斯", la="Sychaeus", en="Sychaeus", cat="mortal", camp="carthage", dies=None, style="fs",
    sub=("狄多的亡夫", "Dido's dead husband"),
    bio=("推罗的富人，狄多的丈夫，被觊觎他财富的皮格马利翁在祭坛前暗杀。他的亡魂托梦给狄多，露出胸口的伤，告诉她真相和埋藏财宝的地方，催她逃走。卷六在冥府，他与狄多重聚，“以同样的爱回应她的悲伤”。",
         "A rich man of Tyre and Dido's husband, murdered at the altar by Pygmalion, who wanted his wealth. His ghost comes to Dido in a dream, bares his wounded breast, tells her the truth and where treasure lies buried, and urges her to flee. In the underworld in Book 6 he is with her again, “answering her sorrows and matching her love”."),
    icon=("淡色的亡魂。", "Drawn pale as a ghost.")),
  N(id="sibyl", zh="西比尔", la="Sibylla", en="The Sibyl", cat="mortal", camp="cumae", dies=None, style="fm",
    sub=("库迈的女先知", "The Sibyl of Cumae"),
    bio=("阿波罗在库迈的女先知，名叫得伊福柏。她在神灵附体的狂乱中预言意大利的血战：“我看见台伯河上翻涌着鲜血。”她告诉埃涅阿斯，要进冥府须先折下一根献给冥后的金枝，然后亲自领他穿过冥界。",
         "Apollo's prophetess at Cumae, named Deiphobe. Possessed by the god, she foretells the bloody war in Italy: “I see the Tiber foaming with blood.” She tells Aeneas that to enter the underworld he must first pluck a golden bough as a gift for its queen, and then guides him through it herself."),
    icon=("老妇的面纱与金枝。", "An old woman's veil and the golden bough.")),
  # ------------------------------------------------------------------ Italy
  N(id="evander", zh="埃万德尔", la="Euander", en="Evander", cat="demi", camp="arcadia", dies=None, style="fm",
    sub=("帕兰特乌姆国王", "King of Pallanteum"),
    bio=("从希腊阿卡迪亚流亡而来的老王，仙女卡尔门提斯之子，在日后罗马城所在的帕拉丁山上建了小城帕兰特乌姆。他年轻时见过安奇塞斯，于是与埃涅阿斯结盟，领他看遍未来罗马的山丘，又把独子帕拉斯托付给他。",
         "An old king exiled from Arcadia in Greece, son of the nymph Carmentis, who has built the little town of Pallanteum on the Palatine, where Rome will one day stand. He met Anchises as a young man, so he makes an alliance with Aeneas, shows him around the hills of the future Rome, and entrusts his only son Pallas to him."),
    icon=("白须与手杖。", "White beard and a staff.")),
  N(id="pallas", zh="帕拉斯", la="Pallas", en="Pallas", cat="mortal", camp="arcadia", dies="卷十", style="fm",
    sub=("埃万德尔之子", "Evander's son"),
    bio=("埃万德尔的独子，随埃涅阿斯出征。他向图尔努斯挑战，被对方一矛刺穿胸膛；图尔努斯剥下他的剑带佩在自己身上。全诗最后，埃涅阿斯正是看见这条剑带，才杀了求饶的图尔努斯。",
         "Evander's only son, who goes to war with Aeneas. He challenges Turnus and is killed by a spear through the chest; Turnus strips off his sword belt and wears it himself. In the poem's last lines it is the sight of this belt that makes Aeneas kill Turnus as he begs for his life."),
    icon=("长矛与镶金的剑带。", "Spear and gold-studded sword belt.")),
  N(id="turnus", zh="图尔努斯", la="Turnus", en="Turnus", cat="demi", camp="italy", dies="卷十二", style="fm",
    sub=("鲁图利人之王", "King of the Rutulians"),
    bio=("鲁图利人的年轻国王，仙女维尼利娅之子，埃涅阿斯到来之前拉维尼娅的求婚者。复仇女神点燃他的怒火后，他率意大利诸族与特洛伊人开战，杀死帕拉斯，佩上他的剑带。最后的决斗中他被刺倒在地，求埃涅阿斯饶命；埃涅阿斯犹豫了，直到看见那条剑带。",
         "Young king of the Rutulians, son of the nymph Venilia, and Lavinia's suitor before Aeneas came. Set ablaze by a Fury, he leads the peoples of Italy against the Trojans, kills Pallas and puts on his sword belt. In the final duel he falls and begs Aeneas for his life; Aeneas hesitates, until he sees the belt."),
    icon=("以喷火怪兽喀迈拉为饰的高盔与剑带。", "A tall helmet crowned with the fire-breathing Chimaera, and the sword belt.")),
  N(id="latinus", zh="拉提努斯", la="Latinus", en="Latinus", cat="demi", camp="italy", dies=None, style="fm",
    sub=("拉丁人之王", "King of the Latins"),
    bio=("拉丁姆的老王，林野之神法乌努斯与仙女马里卡之子。神谕告诉他，独女拉维尼娅要嫁给外来的女婿，于是他欣然接纳埃涅阿斯的使者。复仇女神点燃战火后，他拦不住众人，便闭门不出，“放下了统治的缰绳”。",
         "The old king of Latium, son of the woodland god Faunus and the nymph Marica. An oracle tells him his only daughter Lavinia must marry a son-in-law from abroad, so he welcomes Aeneas's envoys. When the Fury sets off the war and he cannot hold his people back, he shuts himself away and “lets go the reins of rule”."),
    icon=("十二道金光的王冠——太阳神后裔的标志（卷十二）。", "A crown of twelve golden rays, the mark of the Sun's descendants (Book 12).")),
  N(id="amata", zh="阿玛塔", la="Amata", en="Amata", cat="mortal", camp="italy", dies="卷十二", style="fm",
    sub=("拉丁王后", "Queen of the Latins"),
    bio=("拉提努斯的王后，一心要把女儿嫁给图尔努斯。复仇女神的蛇钻进她的胸口，她假托酒神附体，把拉维尼娅藏进山林，领着拉丁妇女一同狂奔。卷十二，她误以为图尔努斯已死，绝望自尽。",
         "Latinus's queen, set on marrying her daughter to Turnus. When the Fury's snake slips into her breast, she feigns possession by Bacchus, hides Lavinia in the mountain woods and leads the Latin women in frenzy. In Book 12, believing Turnus dead, she takes her own life in despair."),
    icon=("常春藤冠与酒神杖。", "Ivy wreath and Bacchic wand.")),
  N(id="lavinia", zh="拉维尼娅", la="Lavinia", en="Lavinia", cat="mortal", camp="italy", dies=None, style="fm",
    sub=("拉丁公主", "Latin princess"),
    bio=("拉提努斯的独女，神谕中的“王族妻子”，整场战争为她而打。她在祭坛前头发燃起火焰却毫发无伤，预示她将享有荣耀，却给人民带来战争。她在诗中从未开口说话，只在母亲哀求图尔努斯时满脸通红，泪流满面。",
         "Latinus's only daughter, the “royal bride” of prophecy, over whom the whole war is fought. At the altar her hair catches fire and she is unharmed, a sign that she will be famous but bring war to her people. She never speaks in the poem; when her mother pleads with Turnus, she only blushes deeply and weeps."),
    icon=("长发上燃着火焰。", "Flames in her long hair.")),
  N(id="camilla", zh="卡密拉", la="Camilla", en="Camilla", cat="mortal", camp="italy", dies="卷十一", style="fm",
    sub=("沃尔斯基女战士", "Volscian warrior"),
    bio=("沃尔斯基人的女战士，狄安娜的追随者。她在襁褓中被父亲绑在长矛上掷过河去，在林中长大；她跑过麦田不压弯麦穗，掠过海浪不沾湿脚掌。卷十一她杀敌无数，却被一件金光闪闪的战袍吸引，一心追赶，被阿伦斯的长矛刺死。",
         "A Volscian warrior woman devoted to Diana. As a baby she was tied to a spear by her father and thrown across a river, and she grew up in the forest; she can run over a field of grain without bending the ears, or across the sea without wetting her feet. In Book 11 she kills many, but her eye is caught by a gleaming golden costume, and as she chases it Arruns kills her with his spear."),
    icon=("弓与箭袋。", "Bow and quiver.")),
  N(id="mezentius", zh="墨赞提乌斯", la="Mezentius", en="Mezentius", cat="mortal", camp="italy", dies="卷十", style="fm",
    sub=("被逐的伊特鲁里亚暴君", "Exiled Etruscan tyrant"),
    bio=("“蔑视众神的”伊特鲁里亚暴君，残忍到把活人和死尸面对面捆在一起，让他们慢慢死去。人民起义把他赶走，他投奔了图尔努斯。儿子劳苏斯为救他而死，他悲痛欲绝，骑马冲向埃涅阿斯，只求死后与儿子同葬。",
         "The Etruscan tyrant, “scorner of the gods”, so cruel that he bound living men face to face with corpses and left them to die. His people rose and drove him out, and he fled to Turnus. When his son Lausus dies saving him, he rides out against Aeneas in grief, asking only to be buried with his son."),
    icon=("紧皱的眉、胡须与头盔。", "Scowling brow, beard and helmet.")),
  N(id="lausus", zh="劳苏斯", la="Lausus", en="Lausus", cat="mortal", camp="italy", dies="卷十", style="fm",
    sub=("墨赞提乌斯之子", "Mezentius's son"),
    bio=("墨赞提乌斯的儿子，维吉尔说他“本该有一位更好的父亲”。父亲负伤时，他挺身挡在前面，被埃涅阿斯杀死。埃涅阿斯看着这张垂死的年轻的脸，想起自己对父亲的孝心，不禁叹息。",
         "Mezentius's son, who “deserved a better father”. When his father is wounded, he steps in to shield him and is killed by Aeneas. Looking at the young dying face, Aeneas thinks of his own love for his father and groans in pity."),
    icon=("年轻的脸与盾牌。", "A young face and a shield.")),
]

# (source, target, type, zh label, zh text, en label, en text, book ref in Chinese)
E = lambda *a: a
EDGES = [
  # ---------------------------------------------------------------- gods
  E("jupiter","juno","kin","夫妻","朱诺是朱庇特的妻子，也是他的姐姐。卷十二，他终于说服她放手：特洛伊人可以留在意大利，但要改用拉丁人的名字和语言，两族融合，成为最敬神的民族。",
    "Married","Juno is Jupiter's wife and sister. In Book 12 he finally persuades her to let go: the Trojans may stay in Italy, but they will take the Latins' name and language, and from the two peoples will come a race more devout than any other.","卷一、卷十二"),
  E("jupiter","venus","kin","父女","维纳斯含泪问父亲，特洛伊人的苦难何时是尽头；朱庇特吻了女儿，向她展开命运：罗慕路斯、罗马，“没有尽头的统治”。",
    "Father–daughter","In tears, Venus asks her father when the Trojans' suffering will end; Jupiter kisses her and unfolds the future: Romulus, Rome, “empire without end”.","卷一"),
  E("jupiter","mercury","kin","父子","朱庇特两次派墨丘利下凡：先让迦太基人善待特洛伊人，再命埃涅阿斯离开迦太基。",
    "Father–son","Jupiter sends Mercury down twice: first to make the Carthaginians kind to the Trojans, then to order Aeneas out of Carthage.","卷一、卷四"),
  E("jupiter","aeneas","tie","天命","朱庇特是埃涅阿斯命运的担保人。埃涅阿斯在迦太基流连时，他传话说：就算你不在乎自己的荣誉，也该想想阿斯卡纽斯应得的意大利和罗马的土地。",
    "Destiny","Jupiter is the guarantor of Aeneas's fate. When Aeneas lingers in Carthage, he sends word: even if your own glory means nothing to you, think of Ascanius, who is owed Italy and the land of Rome.","卷一、卷四"),
  E("jupiter","turnus","tie","称量命运","最后的决斗中，朱庇特举起天平，放上两人的命运，看谁会因这一战而死。",
    "Weighs his fate","During the final duel Jupiter holds up a pair of scales with the fates of the two men, to see whose doom this fight will bring.","卷十二"),
  E("jupiter","juturna","tie","先宠后逐","朱庇特夺走她的贞洁，作为补偿赐她不死之身。最后他派一个复仇女神化作怪鸟，扑打图尔努斯的盾牌，把她从兄长身边赶走。",
    "Favor, then banishment","Jupiter took her virginity and in return made her immortal. At the end he sends one of the Furies, in the shape of a bird, to beat against Turnus's shield and drive her from her brother's side.","卷十二"),
  E("juno","venus","tie","明争暗斗","两位女神各护一方。朱诺提议让埃涅阿斯与狄多成婚、把特洛伊人留在迦太基；维纳斯看穿她的用意，假意答应。卷十开头的众神会议上，两人又激烈争吵。",
    "Rivals","The two goddesses each protect their own. Juno proposes that Aeneas marry Dido and the Trojans stay in Carthage; Venus sees through her and plays along. At the council of the gods in Book 10 they quarrel bitterly again.","卷四、卷十"),
  E("juno","aeolus","tie","许以仙女","朱诺许给风神最美的仙女得伊俄珮亚为妻，要他放出狂风打散特洛伊船队。",
    "A bribe","Juno promises Aeolus the loveliest of her nymphs, Deiopea, as his wife if he will unleash the winds on the Trojan fleet.","卷一"),
  E("juno","allecto","aid","唤出冥府","“如果我不能说动天上的神，我就去搅动冥河。”朱诺从冥府唤出阿列克托，让她破坏特洛伊人与拉丁人的和约；战火点燃后，又把她打发回冥府。",
    "Summons her","“If I cannot bend the gods above, I will stir up the underworld.” Juno calls up Allecto to wreck the peace between Trojans and Latins, and once the war is lit, sends her back below.","卷七"),
  E("juno","juturna","aid","怂恿","朱诺对尤图尔娜说，自己已无力再护着图尔努斯，劝她放手一搏去救哥哥。尤图尔娜于是搅乱了停战誓约。",
    "Urges her on","Juno tells Juturna she can no longer protect Turnus herself and urges her to try anything to save her brother; Juturna goes and wrecks the truce.","卷十二"),
  E("juno","turnus","aid","庇护","卷九，她派伊里斯催图尔努斯趁埃涅阿斯不在进攻特洛伊营地；卷十，她用云雾造出一个假埃涅阿斯，把图尔努斯引上一条船，漂离战场，保住他的性命。",
    "Protects him","In Book 9 she sends Iris to urge Turnus to attack the Trojan camp while Aeneas is away; in Book 10 she makes a phantom Aeneas out of cloud and lures Turnus onto a ship that carries him away from the battle, saving his life.","卷九、卷十"),
  E("juno","dido","aid","迦太基的守护神","迦太基是朱诺最爱的城市，狄多为她建了宏伟的神庙。朱诺促成她与埃涅阿斯在山洞中结合；狄多垂死挣扎时，也是朱诺派伊里斯剪下她的一缕头发，让她的灵魂解脱。",
    "Her patron","Carthage is Juno's favorite city, and Dido has built her a great temple. Juno arranges her union with Aeneas in the cave; and when Dido lies dying in agony, Juno sends Iris to cut a lock of her hair and release her soul.","卷一、卷四"),
  E("juno","aeneas","foe","宿怨","朱诺是埃涅阿斯一路苦难的根源：海难、迦太基、船队被焚、意大利的战争。维吉尔开篇就问：“天神的心中竟有如此大的怒火吗？”",
    "Old hatred","Juno is the source of Aeneas's suffering all the way: the storm, Carthage, the burning of the ships, the war in Italy. At the very start Virgil asks: “Can there be such anger in the hearts of the gods?”","卷一、卷五、卷七"),
  E("venus","aeneas","kin","母子","她扮作猎女为儿子指路，特洛伊陷落之夜现出真身，催他回家救亲人，又送来伏尔甘的铠甲和治伤的白鲜。埃涅阿斯埋怨她：“为什么你也这样残忍，总用假象捉弄你的儿子？”",
    "Mother–son","She appears as a huntress to show her son the way, reveals herself on Troy's last night to send him home to his family, and brings him Vulcan's armor and the healing dittany. Aeneas reproaches her: “Why do you, too, so cruelly mock your son with false shapes?”","卷一、卷二、卷八、卷十二"),
  E("venus","cupid","kin","母子","维纳斯命丘比特扮成阿斯卡纽斯，去点燃狄多的爱火：“孩子，你是我的力量，我唯一的大能。”",
    "Mother–son","Venus sends Cupid, disguised as Ascanius, to set Dido on fire with love: “My son, my strength, my one great power.”","卷一"),
  E("venus","vulcan","kin","夫妻","维纳斯夜里在丈夫怀中温言恳求，伏尔甘便答应为她与凡人所生的儿子打造铠甲。",
    "Married","Venus coaxes her husband in bed at night, and Vulcan agrees to make armor for her son by a mortal.","卷八"),
  E("venus","anchises","kin","恋人","维纳斯曾在特洛伊的西摩伊斯河畔为安奇塞斯生下埃涅阿斯；狄多一见面，就说出了这段往事。",
    "Lovers","Venus bore Aeneas to Anchises beside the Simois river near Troy; Dido knows the story the moment she meets him.","卷一"),
  E("venus","neptune","aid","请求","维纳斯向尼普顿诉说朱诺的迫害，求他让船队平安抵达台伯河；尼普顿答应了，只要一个人的性命。",
    "Her plea","Venus pours out Juno's persecution to Neptune and asks him to see the fleet safely to the Tiber; he agrees, at the price of one life.","卷五"),
  E("venus","dido","tie","设下情网","维纳斯担心朱诺的迦太基会加害儿子，便让丘比特先点燃狄多的爱火，好让她对埃涅阿斯死心塌地。",
    "Her snare","Fearing Juno's Carthage will turn on her son, Venus has Cupid set Dido burning with love first, so that she will be bound to Aeneas.","卷一"),
  E("venus","achates","aid","云雾隐身","维纳斯把埃涅阿斯和阿卡特斯裹进浓雾，让两人隐身走进迦太基城。",
    "Hidden in mist","Venus wraps Aeneas and Achates in a thick mist so that the two can walk into Carthage unseen.","卷一"),
  E("venus","helen","tie","为她开脱","埃涅阿斯要杀海伦泄愤时，维纳斯现身对他说：毁掉特洛伊的不是这个斯巴达女人可恨的美貌，也不是帕里斯，而是众神的无情。（这段诗行真伪存疑。）",
    "Absolves her","When Aeneas is about to kill Helen in his anger, Venus appears and tells him: it is not the hated beauty of the Spartan woman, nor Paris, but the harshness of the gods that is destroying Troy. (The passage's authenticity is disputed.)","卷二"),
  E("cupid","dido","tie","爱火","丘比特扮成阿斯卡纽斯坐进狄多怀里。她抱着这个“孩子”，不知怀中是神，亡夫的记忆一点点被抹去。",
    "Kindles her love","Disguised as Ascanius, Cupid sits in Dido's lap. She holds the “child” close, not knowing she holds a god, while the memory of her dead husband is slowly wiped away.","卷一"),
  E("cupid","ascanius","tie","冒名顶替","维纳斯让真正的阿斯卡纽斯沉睡，把他藏到伊达利翁的山林里，由丘比特顶替他去赴宴。",
    "Impersonates him","Venus sends the real Ascanius to sleep and hides him in the groves of Idalium, while Cupid takes his place at the banquet.","卷一"),
  E("cupid","aeneas","kin","兄弟","同为维纳斯之子。维纳斯对丘比特说：“你的哥哥埃涅阿斯怎样在海上颠沛，你是知道的。”",
    "Half-brothers","Both are sons of Venus. She tells Cupid: “You know how your brother Aeneas is tossed about the seas.”","卷一"),
  E("neptune","aeneas","aid","平息风暴","尼普顿发觉有人擅自掀起风暴，浮出海面平息波涛，把搁浅的船推离礁石，特洛伊人才得以在利比亚靠岸。",
    "Calms the storm","Neptune notices a storm raised without his leave, rises from the sea to calm the waves and pries the stranded ships off the rocks, so the Trojans can make land in Libya.","卷一"),
  E("neptune","aeolus","tie","斥责","“你们竟敢不经我允许，搅乱天地？我要……”尼普顿一句没说完的威胁就喝退了群风，又命它们回去告诉风王：海的统治权归我。",
    "Rebukes him","“Do you dare to throw sky and earth into chaos without my leave? I'll—” Neptune's unfinished threat is enough to scatter the winds, and he tells them to remind their king that the sea is his.","卷一"),
  E("neptune","palinurus","tie","一人替众人","尼普顿答应让船队平安，但“要有一个人替众人而死”。当夜，睡神把舵手帕里努鲁斯推入海中。",
    "One for many","Neptune grants the fleet safe passage, but “one life shall be given for many”. That night the god of Sleep casts the helmsman Palinurus into the sea.","卷五"),
  E("neptune","laocoon","tie","他的祭司","拉奥孔是抽签选出的尼普顿祭司；他正在为海神献祭公牛时，巨蛇从海上游来。",
    "His priest","Laocoön was chosen by lot as Neptune's priest; he is sacrificing a bull to the sea god when the serpents come out of the sea.","卷二"),
  E("mercury","aeneas","tie","催他启程","墨丘利看见埃涅阿斯披着狄多送的紫袍，正在监造迦太基的城堡，便传达朱庇特的命令：立刻起航。后来他又入梦警告：再不走，就会看见海岸上火把通明。",
    "Orders him on","Mercury finds Aeneas in a purple cloak Dido gave him, overseeing the building of Carthage's towers, and delivers Jupiter's command: set sail at once. Later he comes in a dream to warn that if he waits, he will see the shore ablaze with torches.","卷四"),
  E("mercury","dido","aid","化解敌意","朱庇特派墨丘利下凡，让迦太基人和狄多放下戒心，友善地接待落难的特洛伊人。",
    "Softens her","Jupiter sends Mercury down so that the Carthaginians, and Dido above all, will lay aside their suspicion and welcome the shipwrecked Trojans.","卷一"),
  E("vulcan","aeneas","aid","铸造铠甲","伏尔甘与独眼巨人工匠们打造了头盔、胸甲、长矛和一面盾牌，盾上刻着罗马未来的历史。埃涅阿斯看不懂那些画面，却欣然把“子孙的声名与命运”扛上了肩。",
    "Forges his armor","With his Cyclops smiths Vulcan makes a helmet, breastplate, spear and a shield engraved with the future history of Rome. Aeneas does not understand the scenes, but gladly lifts onto his shoulder “the fame and fortunes of his descendants”.","卷八"),
  E("apollo","aeneas","aid","神谕","阿波罗在得洛斯岛告诉特洛伊人：“寻找你们古老的母亲。”安奇塞斯误以为是克里特，一场瘟疫之后，家神才在梦中说明是意大利。",
    "Oracles","On Delos Apollo tells the Trojans to “seek out your ancient mother”. Anchises takes it to mean Crete, and only after a plague do the household gods explain in a dream that it means Italy.","卷三"),
  E("apollo","sibyl","aid","附体","女先知是阿波罗的祭司。神灵附体时，她面色大变，头发散乱，胸口起伏，用“不像凡人的声音”说出预言。",
    "Possesses her","The Sibyl is Apollo's priestess. When the god takes hold of her, her face changes, her hair flies loose, her breast heaves, and she prophesies in a voice no longer mortal.","卷六"),
  E("apollo","helenus","aid","他的先知","赫勒诺斯是阿波罗的祭司，他领埃涅阿斯走进阿波罗神殿，在神灵感召下说出前路。",
    "His prophet","Helenus is Apollo's priest; he leads Aeneas into the god's shrine and, inspired, reveals the way ahead.","卷三"),
  E("apollo","ascanius","aid","夸奖与劝阻","阿斯卡纽斯射杀努玛努斯，阿波罗在云端称赞：“好样的，孩子，这就是通往星辰之路！”随即化作老仆布特斯，劝他就此罢手。",
    "Praise and restraint","When Ascanius shoots Numanus, Apollo cries from the clouds, “Well done, boy! This is the way to the stars!” then comes down in the shape of the old servant Butes and tells him to fight no more.","卷九"),
  E("apollo","camilla","foe","应允杀她","阿伦斯向阿波罗祈祷，求能杀死卡密拉并平安回家；阿波罗只成全了一半——让他杀死她，却不让他回乡。",
    "Grants her death","Arruns prays to Apollo to let him bring down Camilla and return home; Apollo grants half the prayer: he may kill her, but he will never see home again.","卷十一"),
  E("apollo","celaeno","tie","预言的来源","刻莱诺说，她的诅咒是“全能的父亲告诉阿波罗，阿波罗又告诉我的”。",
    "Source of her prophecy","Celaeno says her curse is what “the almighty Father told Apollo, and Apollo told me”.","卷三"),
  E("minerva","laocoon","foe","巨蛇","缠死拉奥孔父子的巨蛇，事后游上卫城，躲到密涅瓦神像脚下、盾牌之下。特洛伊人认定是女神在惩罚他。",
    "The serpents","After killing Laocoön and his sons, the serpents glide up to the citadel and shelter at the feet of Minerva's statue, under her shield. The Trojans conclude the goddess has punished him.","卷二"),
  E("minerva","sinon","tie","借她之名","西农说，木马是献给密涅瓦的赎罪之物，因为尤利西斯与狄奥墨得斯偷走了她的神像；只要把木马拖进城，女神就会转而保佑特洛伊。",
    "Uses her name","Sinon says the horse is an offering to Minerva, in atonement for the theft of her statue by Ulysses and Diomedes; bring it into the city, he says, and the goddess will protect Troy instead.","卷二"),
  E("aeolus","aeneas","foe","风暴","风神放出狂风，特洛伊船队在西西里附近被打散，埃涅阿斯绝望地喊道：死在特洛伊城下的人才是有福的。",
    "The storm","Aeolus unleashes the winds and the Trojan fleet is scattered off Sicily; Aeneas cries in despair that those who died beneath Troy's walls were the lucky ones.","卷一"),
  E("juturna","turnus","kin","兄妹","尤图尔娜扮成车夫墨提斯库斯，驾着哥哥的战车四处避开埃涅阿斯；图尔努斯的剑断了，她又为他送来父亲的宝剑。最后她认出兄长的死兆，扯下头巾，沉入深深的河中。",
    "Brother and sister","Disguised as his charioteer Metiscus, Juturna drives her brother's chariot all over the field to keep him away from Aeneas; when his sword breaks, she brings him his father's sword. At last she recognizes the omen of his death, tears off her veil and plunges into the depths of her river.","卷十二"),
  # ---------------------------------------------------------------- monsters
  E("allecto","amata","foe","投蛇入怀","阿列克托从蛇发中扯下一条蛇，投进阿玛塔的衣襟；蛇在她身上游走，把毒气吹进她的心。",
    "The snake","Allecto pulls a snake from her hair and flings it into Amata's clothing; it glides over her body and breathes its venom into her heart.","卷七"),
  E("allecto","turnus","foe","投火入心","她扮成老祭司卡吕柏劝图尔努斯开战，被他嘲笑；她便现出原形，把一支冒着黑烟的火把插进他的胸膛。他从梦中惊醒，大喊要武器。",
    "The torch","Disguised as the old priestess Calybe, she urges Turnus to war and is laughed at; then she shows her true form and drives a smoking torch into his chest. He wakes shouting for his weapons.","卷七"),
  E("allecto","ascanius","tie","惊鹿","阿列克托让阿斯卡纽斯的猎犬嗅到一头牡鹿——那是拉丁牧人之女西尔维娅驯养的宠物。阿斯卡纽斯一箭射中它，战争从这里开始。",
    "The stag","Allecto puts the scent of a stag in the noses of Ascanius's hounds: the tame pet of Silvia, daughter of the Latin herdsman. Ascanius shoots it, and the war begins there.","卷七"),
  E("polyphemus","achaemenides","foe","巨人的洞穴","阿开墨尼德斯亲眼看见巨人抓起两个同伴砸在石头上吞吃。尤利西斯一行刺瞎巨人逃走，却把他遗落在岛上。",
    "The Cyclops's cave","Achaemenides watched the giant seize two of his companions, dash them against a rock and devour them. Ulysses and the rest blinded the Cyclops and fled, but left him behind on the island.","卷三"),
  E("polyphemus","aeneas","foe","险遭追捕","特洛伊人听从阿开墨尼德斯的警告，砍断缆绳，悄悄划离；巨人听见桨声涉水追来，一声怒吼唤来了群山中的独眼巨人。",
    "A narrow escape","Warned by Achaemenides, the Trojans cut their cables and row quietly away; the giant hears the oars and wades after them, and his roar brings the Cyclopes down from the mountains.","卷三"),
  E("celaeno","aeneas","foe","诅咒","刻莱诺预言，特洛伊人建城之前要饿到啃自己的桌子。到了意大利，他们把当盘子用的麦饼也吃了，阿斯卡纽斯笑道：“我们连桌子都吃了！”诅咒应验，原来是到家的信号。",
    "The curse","Celaeno prophesies that before they build their city, the Trojans will be so hungry they eat their tables. In Italy they eat the flat loaves they have used as plates, and Ascanius laughs, “Look, we're eating our tables too!” The curse fulfilled turns out to be a sign they have come home.","卷三、卷七"),
  # ---------------------------------------------------------------- Aeneas
  E("aeneas","anchises","kin","父子","埃涅阿斯背着父亲逃出火城：“来吧，亲爱的父亲，骑到我的肩上。”父亲死在西西里，一年后他为父亲举办葬礼竞技；在冥府，他三次想拥抱父亲，三次扑了个空。",
    "Father–son","Aeneas carries his father out of the burning city: “Come, dear father, climb onto my shoulders.” After his father dies in Sicily, he holds funeral games for him a year later; in the underworld he tries three times to embrace him, and three times clasps empty air.","卷二、卷三、卷五、卷六"),
  E("aeneas","creusa","kin","夫妻","出逃时她跟在后面走失。埃涅阿斯冒死回城，在街巷里呼喊她的名字，只遇见她的亡魂：“不要再为你心爱的克列乌莎哭泣。”",
    "Married","She follows behind in the escape and is lost. Aeneas goes back into the city at the risk of his life, calling her name through the streets, and meets only her ghost: “Stop weeping for your beloved Creusa.”","卷二"),
  E("aeneas","ascanius","kin","父子","埃涅阿斯所做的一切，都为了儿子将来的王国。最后一战前，他隔着头盔吻了儿子：“孩子，向我学勇敢和真正的辛劳，向别人去学好运吧。”",
    "Father–son","Everything Aeneas does is for his son's future kingdom. Before the last battle he kisses him through his helmet: “Learn courage and true toil from me, my son; learn good fortune from others.”","卷四、卷十二"),
  E("aeneas","achates","aid","忠实伙伴","阿卡特斯几乎寸步不离。在迦太基，两人看着朱诺神庙壁画上的特洛伊战争，埃涅阿斯落泪道：“世间万物都有眼泪。”",
    "Faithful friend","Achates is almost never from his side. In Carthage the two look at the paintings of the Trojan War in Juno's temple, and Aeneas weeps: “There are tears in things.”","卷一"),
  E("aeneas","palinurus","aid","舵手","帕里努鲁斯为埃涅阿斯掌舵，穿过风暴与险礁。埃涅阿斯醒来发现舵手不见了，叹息他太相信平静的海。在冥府，他没能带这位未安葬的亡魂过河。",
    "His helmsman","Palinurus steers for Aeneas through storms and reefs. Waking to find him gone, Aeneas grieves that he trusted too much in a calm sea. In the underworld he cannot take his unburied ghost across the river.","卷五、卷六"),
  E("aeneas","hector","aid","托付","赫克托尔的亡魂把特洛伊的家神与圣火托付给埃涅阿斯：“特洛伊把圣物和家神交给你了，带上它们，为它们去寻找城池。”",
    "Entrusts Troy","Hector's ghost hands Troy's household gods and sacred fire to Aeneas: “Troy entrusts her holy things and her gods to you; take them with you and seek walls for them.”","卷二"),
  E("aeneas","priam","tie","目睹王死","埃涅阿斯从王宫屋顶目睹皮鲁斯杀死普里阿摩斯。看着这位老王倒下，他才第一次想起同样年迈的父亲。",
    "Watches him die","From the palace roof Aeneas watches Pyrrhus kill Priam; seeing the old king fall, he thinks for the first time of his own aged father.","卷二"),
  E("aeneas","helen","tie","欲杀而止","城破之夜，埃涅阿斯撞见躲在维斯塔神庙里的海伦：她怕特洛伊人报复，也怕被她抛弃的丈夫。他怒火中烧，想杀了这个“特洛伊与祖国共同的复仇女神”，直到母亲现身拦住他。（这段诗行真伪存疑。）",
    "Spares her","On Troy's last night Aeneas comes upon Helen hiding at the shrine of Vesta, afraid of the Trojans' revenge and of the husband she deserted. He burns to kill this “Fury of Troy and of her own country”, until his mother appears and stops him. (The passage's authenticity is disputed.)","卷二"),
  E("aeneas","andromache","aid","故人重逢","在布特罗通，安德罗马刻见到埃涅阿斯，以为是鬼魂，当场晕倒；醒来后她问：“赫克托尔在哪里？”",
    "Reunion","At Buthrotum Andromache sees Aeneas, thinks he is a ghost and faints; coming round, she asks: “Where is Hector?”","卷三"),
  E("aeneas","helenus","aid","指路","赫勒诺斯为埃涅阿斯详细指明航线和建城的征兆，临别赠他金银、铠甲和桨手。",
    "Guidance","Helenus maps out the voyage and the signs of the future city for Aeneas, and at parting gives him gold, silver, armor and oarsmen.","卷三"),
  E("aeneas","dido","tie","相爱与诀别","两人在山洞避雨时结合，狄多称之为婚姻，埃涅阿斯却说自己从未许诺。他奉神命离去：“我去意大利，并非出于本心。”在冥府，他流着泪追着她的亡魂辩白，她始终没有回头。",
    "Love and parting","They come together in a cave while sheltering from a storm; Dido calls it marriage, but Aeneas says he never made that promise. He leaves at the gods' command: “I sail for Italy not of my own will.” In the underworld he weeps and pleads after her ghost, and she never turns back.","卷四、卷六"),
  E("aeneas","sibyl","aid","冥府向导","女先知告诉埃涅阿斯：下到冥府容易，回来才难。她让他折取金枝，用蜜饼迷倒三头犬，带他穿过亡魂去见父亲。",
    "Guide below","The Sibyl tells Aeneas the descent to the underworld is easy; the return is the hard part. She has him pluck the golden bough, drugs Cerberus with a honey cake, and leads him through the dead to his father.","卷六"),
  E("aeneas","achaemenides","aid","收留","这个希腊人本是敌人，衣衫褴褛地跪地求救；特洛伊人不计前嫌，把他带上了船。",
    "Takes him in","This Greek, an enemy, kneels in rags and begs for help; the Trojans put the war behind them and take him aboard.","卷三"),
  E("aeneas","evander","aid","结盟","埃涅阿斯溯台伯河而上，正逢埃万德尔祭祀赫拉克勒斯。老王在简朴的家中款待他，与他结盟，并派骑兵随他出征。",
    "Alliance","Aeneas sails up the Tiber and finds Evander sacrificing to Hercules. The old king entertains him in his humble home, makes an alliance with him and sends horsemen with him to war.","卷八"),
  E("aeneas","pallas","aid","托付与复仇","埃涅阿斯答应照看帕拉斯，却没能保住他。他亲手为少年装殓，送回他父亲身边；最后，他看见图尔努斯身上帕拉斯的剑带，喊着“是帕拉斯用这一剑把你献祭”，把剑刺进他的胸膛。",
    "A ward, avenged","Aeneas takes Pallas under his care but cannot save him. He dresses the boy's body for the journey home to his father; and at the end, seeing Pallas's belt on Turnus, he cries “With this wound Pallas makes you his sacrifice” and drives his sword into his chest.","卷八、卷十一、卷十二"),
  E("aeneas","latinus","aid","盟约","拉提努斯接受埃涅阿斯的求婚与结盟。战争爆发后，两人立下停战誓约，埃涅阿斯发誓：无论谁胜，两族都将平等相处。",
    "Treaty","Latinus accepts Aeneas's offer of marriage and alliance. After war breaks out, the two swear a truce in which Aeneas pledges that, whoever wins, the two peoples will live as equals.","卷七、卷十二"),
  E("aeneas","lavinia","tie","命定的婚约","神谕说拉维尼娅要嫁给外来的女婿，这桩婚事成了战争的起因。两人在诗中从未见面。",
    "Promised bride","An oracle says Lavinia must marry a stranger from abroad, and this marriage becomes the cause of the war. The two never meet in the poem.","卷七、卷十二"),
  E("aeneas","turnus","foe","最后的决斗","两人争夺拉维尼娅与意大利。决斗中埃涅阿斯的长矛刺穿图尔努斯的大腿，他跪地求饶；埃涅阿斯正在动摇，看见了帕拉斯的剑带。全诗在图尔努斯的魂魄“呻吟着、含恨逃往阴间”中结束。",
    "The final duel","They fight for Lavinia and for Italy. In the duel Aeneas's spear pierces Turnus's thigh and he kneels to beg for mercy; Aeneas is wavering when he sees Pallas's belt. The poem ends as Turnus's life “flees with a groan, resentful, down to the shades”.","卷十二"),
  E("aeneas","mezentius","foe","仇敌","埃涅阿斯刺伤墨赞提乌斯，又杀了挺身救父的劳苏斯；墨赞提乌斯骑马回来寻死，被埃涅阿斯杀死，只求与儿子同葬。卷十一开头，埃涅阿斯把他的铠甲立成战利品纪念柱。",
    "Enemy","Aeneas wounds Mezentius and kills Lausus, who steps in to save him; Mezentius rides back seeking death, is killed by Aeneas, and asks only to be buried with his son. At the start of Book 11 Aeneas sets up his armor as a trophy.","卷十、卷十一"),
  E("aeneas","lausus","foe","怜悯的敌人","埃涅阿斯警告少年不要自不量力，还是杀了他。看着那张苍白的脸，他想起自己对父亲的孝心，亲手把尸体从地上扶起，没有剥下他的铠甲。",
    "A pitied foe","Aeneas warns the boy not to overreach, and kills him anyway. Looking at the pale face, he thinks of his own love for his father, lifts the body from the ground himself and leaves him his armor.","卷十"),
  E("aeneas","diomedes","tie","昔日劲敌","在特洛伊，狄奥墨得斯曾打伤埃涅阿斯。如今他对拉丁使者说：我和他交过手，知道他有多厉害；若特洛伊再出两个这样的人，希腊人早就败了。",
    "Old adversary","At Troy Diomedes once wounded Aeneas. Now he tells the Latin envoys: “I have fought him hand to hand and know his strength. Had Troy produced two more such men, the Greeks would have lost.”","卷一、卷十一"),
  E("aeneas","ulysses","foe","宿敌","在特洛伊人的讲述里，尤利西斯是木马诡计和一切罪行的主谋。船队驶过伊萨卡时，他们诅咒这片“养育了残忍的尤利西斯的土地”。",
    "Old enemy","In the Trojans' telling, Ulysses is the mastermind of the horse and of every crime. Sailing past Ithaca, they curse “the land that nursed cruel Ulysses”.","卷二、卷三"),
  E("aeneas","nisus","aid","赛跑的奖品","卷五赛跑，尼苏斯摔倒后满身污泥，向埃涅阿斯诉苦；埃涅阿斯笑着赏了他一面精美的盾牌。",
    "A prize","After the footrace in Book 5, Nisus, covered in filth from his fall, complains to Aeneas; Aeneas laughs and gives him a fine shield.","卷五"),
  # ---------------------------------------------------------------- Trojans and Troy
  E("anchises","ascanius","kin","祖孙","安奇塞斯不肯离开特洛伊，直到一团火焰在小阿斯卡纽斯头顶燃起，却不伤他分毫；老人举手向天，求朱庇特证实，天上立刻响起雷声，划过一颗流星。",
    "Grandfather–grandson","Anchises refuses to leave Troy until a flame plays harmlessly over young Ascanius's head; the old man raises his hands to the sky and asks Jupiter to confirm the sign, and at once thunder sounds and a shooting star crosses the sky.","卷二"),
  E("anchises","achaemenides","aid","伸手接纳","安奇塞斯毫不犹豫，向这个希腊人伸出右手，许他平安。",
    "Welcomes him","Without hesitation Anchises gives the Greek his right hand as a pledge of safety.","卷三"),
  E("anchises","evander","aid","旧识","埃万德尔年轻时见过来阿卡迪亚访问的安奇塞斯，倾慕不已，还收下了他赠送的箭袋和金缰绳。所以他一眼就从埃涅阿斯脸上认出了他的父亲。",
    "Old acquaintance","As a young man Evander met Anchises on a visit to Arcadia and admired him greatly; Anchises gave him a quiver and golden bridles. So he sees the father in Aeneas's face at once.","卷八"),
  E("creusa","ascanius","kin","母子","克列乌莎的亡魂最后嘱托丈夫：“永别了，好好爱护我们共同的儿子。”",
    "Mother–son","Creusa's ghost's last words to her husband: “Farewell, and keep your love for the son we share.”","卷二"),
  E("achates","ascanius","aid","奉命迎接","埃涅阿斯派阿卡特斯回船上接阿斯卡纽斯来赴狄多的宴会，并带上从特洛伊救出的礼物，其中有海伦的衣裙和面纱。",
    "Fetches him","Aeneas sends Achates back to the ships to bring Ascanius to Dido's banquet, with gifts saved from Troy, among them a gown and veil that once belonged to Helen.","卷一"),
  E("priam","pyrrhus","foe","祭坛前被杀","皮鲁斯当着普里阿摩斯的面杀死他的儿子波利忒斯。老王掷出无力的一矛，骂他不配做阿喀琉斯的儿子——阿喀琉斯还曾把赫克托尔的尸体还给他。皮鲁斯答：“那就去告诉我父亲吧。”",
    "Killed at the altar","Pyrrhus kills Priam's son Polites in front of him. The old king throws a feeble spear and says he is no true son of Achilles, who at least gave back Hector's body. Pyrrhus answers: “Then go and tell my father.”","卷二"),
  E("priam","sinon","aid","释放","普里阿摩斯下令为这个“俘虏”松绑，好言安慰：“不管你是谁，忘掉希腊人吧，从今以后你就是我们的人。”",
    "Frees him","Priam orders the “captive” untied and comforts him: “Whoever you are, forget the Greeks; from now on you are one of us.”","卷二"),
  E("priam","hector","kin","父子","狄多神庙的壁画上，普里阿摩斯正向阿喀琉斯伸出空空的双手，赎回赫克托尔的遗体。埃涅阿斯看得泪流不止。",
    "Father–son","On the walls of Dido's temple, Priam stretches out his empty hands to Achilles to ransom Hector's body, and Aeneas cannot stop weeping.","卷一"),
  E("priam","helenus","kin","父子","赫勒诺斯是普里阿摩斯之子，城破后沦为俘虏，最终在伊庇鲁斯称王。",
    "Father–son","Helenus is Priam's son; captured when the city fell, he ends up a king in Epirus.","卷三"),
  E("hector","andromache","kin","夫妻","安德罗马刻在赫克托尔的空坟前祭奠——那是她用青草堆起、设了两座祭坛的衣冠冢。",
    "Married","Andromache makes offerings at Hector's empty tomb, a mound of green turf with two altars that she built herself.","卷三"),
  E("andromache","helenus","kin","夫妻","皮鲁斯死后，安德罗马刻被转给同为奴隶的赫勒诺斯，“一个奴隶配给另一个奴隶”。如今两人统治着一座仿造的小特洛伊。",
    "Married","After Pyrrhus's death Andromache was passed on to Helenus, “a slave given to a slave”. Now the two rule a small copy of Troy.","卷三"),
  E("andromache","pyrrhus","foe","被迫为妾","她被迫为阿喀琉斯的儿子生子，忍受他的傲慢。后来皮鲁斯另娶海伦之女赫耳弥俄涅，被俄瑞斯忒斯杀死在祭坛前。",
    "Enslaved","She was forced to bear a child to Achilles's son and endure his arrogance. When Pyrrhus married Hermione, Helen's daughter, Orestes killed him at an altar.","卷三"),
  E("andromache","ascanius","aid","赠衣","临别时，她把亲手织的衣物送给阿斯卡纽斯：他的眼睛、双手和脸庞，多像她死去的阿斯提阿那克斯。",
    "Her gift","At parting she gives Ascanius clothes she wove herself: his eyes, his hands, his face are just like her dead Astyanax's.","卷三"),
  E("nisus","euryalus","aid","生死之交","卷五赛跑中，尼苏斯滑倒后绊倒对手，让欧律阿鲁斯夺冠；卷九夜袭，欧律阿鲁斯被敌骑包围，尼苏斯冲出来救他，死在他的身上。维吉尔许诺：只要罗马长存，你们的名字就不会被遗忘。",
    "Devoted friends","In the footrace of Book 5, Nisus falls and trips a rival so Euryalus can win; on the night raid in Book 9, when enemy horsemen surround Euryalus, Nisus rushes in to save him and dies on his body. Virgil promises: as long as Rome stands, your names will not be forgotten.","卷五、卷九"),
  E("ascanius","euryalus","aid","许诺","两人出发前，阿斯卡纽斯流着泪承诺：欧律阿鲁斯的母亲，从此就是我的母亲。",
    "His promise","Before they set out, Ascanius promises with tears that Euryalus's mother will be as a mother to him.","卷九"),
  E("palinurus","sibyl","aid","安慰","帕里努鲁斯的亡魂求女先知让他过河，她斥责他妄想违背天命，又安慰他：当地人会为他修坟，那处海角将永远以他为名。",
    "Consoles him","When Palinurus's ghost asks to be taken across, the Sibyl rebukes him for trying to bend fate, then comforts him: the local people will build him a tomb, and the headland will bear his name forever.","卷六"),
  # ---------------------------------------------------------------- Greeks
  E("ulysses","sinon","tie","谎称仇人","西农编造说，尤利西斯害死了他的恩主帕拉墨得斯，又与先知卡尔卡斯串通，选他做活祭。特洛伊人对这套说辞深信不疑。",
    "A feigned enemy","Sinon claims that Ulysses destroyed his patron Palamedes, then conspired with the seer Calchas to have him chosen as the human sacrifice. The Trojans believe every word.","卷二"),
  E("ulysses","diomedes","aid","同盗神像","据西农说，狄奥墨得斯与尤利西斯趁夜潜入特洛伊卫城，杀死守卫，用沾血的手偷走了密涅瓦的神像，从此女神转而恨希腊人。",
    "Partners in theft","According to Sinon, Diomedes and Ulysses crept into Troy's citadel by night, killed the guards and carried off Minerva's statue with bloody hands; from then on the goddess turned against the Greeks.","卷二"),
  E("ulysses","achaemenides","tie","遗弃","阿开墨尼德斯是尤利西斯的部下，一行人匆匆逃离独眼巨人时，把他忘在了岛上。",
    "Left him behind","Achaemenides served under Ulysses; in their haste to escape the Cyclops, the others forgot him on the island.","卷三"),
  E("ulysses","polyphemus","foe","刺瞎","阿开墨尼德斯讲述：尤利西斯灌醉巨人，趁他沉睡，用削尖的木桩刺进他唯一的眼睛。",
    "Blinded him","Achaemenides tells how Ulysses got the giant drunk and, while he slept, drove a sharpened stake into his single eye.","卷三"),
  E("diomedes","venus","foe","刺伤女神","狄奥墨得斯自承，他在特洛伊用长矛刺伤了维纳斯的手，从此噩运不断：归途中，同伴一个个变成了鸟。",
    "Wounded her","Diomedes admits that at Troy he wounded Venus in the hand with his spear, and misfortune has followed him ever since: on the way home his companions were turned into birds.","卷十一"),
  # ---------------------------------------------------------------- Carthage
  E("dido","anna","kin","姐妹","狄多向妹妹倾诉对埃涅阿斯的爱，安娜劝她放下守寡的誓言。狄多临死时，安娜赶来，用嘴唇接住姐姐最后一口气：“姐姐，原来你是这个打算？”",
    "Sisters","Dido confides her love for Aeneas to her sister, and Anna urges her to give up her vow of widowhood. As Dido dies, Anna rushes in to catch her last breath with her lips: “Sister, was this what you meant all along?”","卷四"),
  E("dido","sychaeus","kin","夫妻","狄多曾发誓为亡夫守节，背弃誓言让她痛苦不堪。她在宫中为许凯斯建了大理石神龛，临死前仿佛听见他在呼唤自己。卷六在冥府，她回到了他身边。",
    "Married","Dido swore to stay faithful to her dead husband, and breaking the vow torments her. She keeps a marble shrine to Sychaeus in her palace and, before she dies, seems to hear him calling her. In the underworld she returns to him.","卷一、卷四、卷六"),
  E("anna","aeneas","tie","替姐姐求情","安娜一次次去见埃涅阿斯，转达姐姐的哀求；他却像风中的老橡树，不为所动，“泪水徒然地流”。",
    "Pleads for her sister","Anna goes to Aeneas again and again with her sister's pleas, but he stands like an old oak in the wind: “the tears fall in vain”.","卷四"),
  # ---------------------------------------------------------------- Italy
  E("evander","pallas","kin","父子","送别时，老父祈祷：若命运要夺走儿子，就让我现在就死。帕拉斯的遗体运回时，他扑在上面痛哭，要埃涅阿斯用图尔努斯的性命来偿还。",
    "Father–son","Seeing him off, the old father prays that if fate means to take his son, he may die now. When Pallas's body comes home, he throws himself on it weeping and asks Aeneas to pay the debt with Turnus's life.","卷八、卷十一"),
  E("pallas","turnus","foe","杀死","图尔努斯要亲手杀帕拉斯，“但愿他父亲在场看着”。他一矛刺穿少年的盾牌和胸膛，剥下他的剑带。维吉尔叹道：人心不知命运，得意时不知节制——图尔努斯终有一天会后悔。",
    "Kills him","Turnus wants to kill Pallas himself, “and I wish his father were here to watch”. His spear pierces the boy's shield and chest, and he strips off the belt. Virgil comments: how little human minds know of fate, how little restraint they keep in success; the day will come when Turnus wishes he had never touched it.","卷十"),
  E("turnus","lavinia","tie","求婚者","图尔努斯本是拉维尼娅最有希望的求婚者，得到王后阿玛塔的支持，神谕却另有所指。她在他面前满脸通红，他因此更加决意为她而战。",
    "Suitor","Turnus was Lavinia's likeliest suitor, backed by Queen Amata, but the oracles pointed elsewhere. When she blushes in front of him, he is all the more determined to fight for her.","卷七、卷十二"),
  E("turnus","amata","aid","王后的支持","阿玛塔一心要图尔努斯做女婿。决斗前她哭着求他不要去：“你若遭遇不测，我也不活了。”后来她误信他已战死，真的自尽了。",
    "The queen's champion","Amata is set on Turnus as her son-in-law. Before the duel she begs him in tears not to go: “Whatever befalls you befalls me too.” Later, believing him dead, she takes her own life.","卷七、卷十二"),
  E("turnus","latinus","tie","不和","拉提努斯劝图尔努斯放弃拉维尼娅，承认自己不该违背神谕；图尔努斯不听，执意决斗。",
    "At odds","Latinus urges Turnus to give up Lavinia and admits he was wrong to defy the oracles; Turnus will not listen and insists on the duel.","卷十二"),
  E("turnus","camilla","aid","并肩作战","卡密拉请缨迎击特洛伊骑兵，图尔努斯把骑兵交给她指挥，自己去山谷设伏。听到她的死讯，他放弃埋伏回师，恰好让埃涅阿斯安然通过。",
    "Allies","Camilla offers to meet the Trojan cavalry, and Turnus gives her command of the horse while he lays an ambush in a mountain pass. When he hears she is dead, he abandons the ambush, just in time to let Aeneas through.","卷十一"),
  E("turnus","mezentius","aid","同盟","被伊特鲁里亚人驱逐的墨赞提乌斯投奔图尔努斯，率部与他并肩作战；伊特鲁里亚人正是为了捉拿他，才与埃涅阿斯结盟。",
    "Allies","Driven out by the Etruscans, Mezentius takes refuge with Turnus and fights at his side; it is to get their hands on him that the Etruscans join Aeneas.","卷七、卷八"),
  E("latinus","diomedes","tie","求援被拒","拉丁人派使者去阿尔庇求狄奥墨得斯出兵，带回的却是拒绝和讲和的劝告；拉提努斯于是在议事会上提议与特洛伊人议和。",
    "Help refused","The Latins send envoys to Arpi to ask Diomedes for troops, and they bring back a refusal and advice to make peace; Latinus then proposes peace with the Trojans in council.","卷十一"),
  E("latinus","amata","kin","夫妻","阿玛塔哭求丈夫不要把女儿嫁给外邦人，拉提努斯不为所动；她便在全城掀起疯狂。",
    "Married","Amata begs her husband in tears not to give their daughter to a foreigner; when Latinus will not move, she spreads frenzy through the city.","卷七"),
  E("latinus","lavinia","kin","父女","法乌努斯的神谕告诉拉提努斯：不要把女儿嫁给拉丁人，外来的女婿会让你的名字升上星辰。",
    "Father–daughter","Faunus's oracle tells Latinus not to marry his daughter to a Latin: sons-in-law will come from abroad whose blood will raise his name to the stars.","卷七"),
  E("amata","lavinia","kin","母女","阿玛塔假托酒神附体，把女儿藏进山林，不让她嫁给特洛伊人。王后死后，拉维尼娅第一个撕扯自己的金发与脸颊。",
    "Mother–daughter","Feigning possession by Bacchus, Amata hides her daughter in the mountain woods to keep her from the Trojan. When the queen dies, Lavinia is the first to tear her golden hair and cheeks.","卷七、卷十二"),
  E("mezentius","lausus","kin","父子","劳苏斯为掩护负伤的父亲撤退而死。墨赞提乌斯抱着儿子的尸体悲叹：你竟替我挨了这一击；他终于承认，自己的罪孽玷污了儿子的名字。",
    "Father–son","Lausus dies covering his wounded father's retreat. Holding his son's body, Mezentius mourns that the boy took the blow meant for him, and admits at last that his own crimes have stained his son's name.","卷十"),
]

EDGE_TYPES = {
  "kin": dict(zh="亲缘", en="Kin", desc="血缘与婚姻", desc_en="Blood and marriage"),
  "aid": dict(zh="友助", en="Ally", desc="庇护、相助、友谊与忠诚", desc_en="Protection, help, friendship, loyalty"),
  "foe": dict(zh="敌对", en="Enemy", desc="交战、加害、欺骗", desc_en="Combat, harm, deception"),
  "tie": dict(zh="纠葛", en="Entangled", desc="恩怨交织、争夺、胁迫与命运", desc_en="Mixed motives, rivalry, coercion, fate"),
}
