# -*- coding: utf-8 -*-
"""Dream of the Red Chamber relationships, part 1: Baoyu, the cousins, Grandmother Jia and the elders of the Rong mansion.

Each relationship has phases P(chapter, type, zh label, zh text, en label, en text, ref). Types:
  kin 亲缘 · love 情缘 · mas 主仆 · aid 知交 · foe 构陷 · tie 纠葛
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import P, E  # noqa: E402

EDGES_A = [
  # =============================================================== Baoyu, Daiyu, Baochai
  E("baoyu", "daiyu",
    P(1, "love", "木石前盟", "前世神瑛侍者以甘露浇灌绛珠仙草；仙草修成女身，发愿随他下世为人，用一生的眼泪还他。",
      "Stone and flower", "In a former life the attendant Shenying watered the Crimson Pearl flower with dew; given a woman’s form, she vowed to follow him into the world and repay him with a lifetime of tears."),
    P(3, "love", "似曾相识", "两人初见，黛玉心想“好生奇怪，倒象在那里见过一般”，宝玉笑道“这个妹妹我曾见过的”；听说黛玉没有玉，宝玉摘下自己的玉狠命摔去。",
      "“I’ve seen her before”", "At their first meeting each feels they have met before; Baoyu laughs, “I’ve seen this cousin somewhere.” Hearing she has no jade, he tears off his own and flings it down."),
    P(23, "love", "共读西厢", "桃花树下，宝玉偷看《会真记》被黛玉撞见，两人同读，宝玉借书中的话说“我就是个'多愁多病身'，你就是那'倾国倾城貌'”。",
      "The Western Chamber", "Under the peach tree Daiyu catches Baoyu reading The Western Chamber; they read it together, and he quotes it: he is the lovesick one, she the beauty who topples cities."),
    P(29, "tie", "砸玉剪穗", "清虚观打醮回来，为了张道士提亲和“金玉”之说两人大吵，宝玉砸玉，黛玉剪了替他穿玉的穗子；贾母急得抱怨“不是冤家不聚头”。",
      "The jade smashed", "After the temple service Abbot Zhang’s talk of a match and the “gold and jade” prophecy set off a furious quarrel: Baoyu smashes his jade, Daiyu cuts up the tassel she made for it, and Grandmother Jia sighs that they are enemies fated to meet.", (29, 30)),
    P(32, "love", "诉肺腑", "宝玉对黛玉说“你放心”，说她一身病都是不放心的缘故，黛玉听了“如轰雷掣电”；黛玉走后宝玉出了神，把送扇子来的袭人当作黛玉，说出了心里话。",
      "“Set your mind at rest”", "Baoyu tells Daiyu, “Set your mind at rest” — all her illness comes from worrying — and the words strike her like thunder. After she leaves, dazed, he pours out his heart to Xiren, thinking she is Daiyu."),
    P(34, "love", "旧帕题诗", "宝玉挨打后叫晴雯给黛玉送去两块旧手帕，黛玉体会出其中的意思，在帕上题了三首诗。",
      "Two old handkerchiefs", "After his beating Baoyu sends Daiyu two old handkerchiefs; she understands, and writes three poems on them."),
    P(57, "love", "试玉", "紫鹃骗宝玉说黛玉明年要回苏州，宝玉急得两眼发直，人事不省，见了姓林的就闹。",
      "The test", "When Zijuan says Daiyu is going home to Suzhou, Baoyu falls senseless and raves at anything called Lin."),
    P(97, "love", "焚稿断痴情", "黛玉得知宝玉娶宝钗，焚了诗稿和题诗的旧帕；宝玉成婚之时，她在潇湘馆死去，临终叫道“宝玉，宝玉，你好……”。",
      "The burnt poems", "Learning that Baoyu is to marry Baochai, Daiyu burns her poems and the handkerchiefs. She dies at the hour of his wedding, crying, “Baoyu, Baoyu, how could you…”", (96, 98))),
  E("baoyu", "baochai",
    P(8, "tie", "比通灵", "宝玉到梨香院看宝钗，两人互看了玉和金锁，莺儿在旁说锁上的字和玉上的字“是一对儿”。",
      "Jade and locket", "Visiting Baochai, Baoyu compares his jade with her gold locket; her maid remarks that the inscriptions make a pair."),
    P(28, "tie", "红麝串", "元妃端午节的赏赐，只有宝玉和宝钗的一样；宝玉要看宝钗的红麝串，见她雪白的膀子，竟看呆了。",
      "The red musk beads", "The Imperial Consort’s festival gifts are identical for Baoyu and Baochai alone; asking to see her bracelet, Baoyu is struck dumb by her bare white arm."),
    P(34, "aid", "托药探伤", "宝玉挨打后，宝钗托着一丸药来看他，说“早听人一句话，也不至今日”，说完又红了脸。",
      "A visit after the beating", "After the beating Baochai brings him medicine: “If you had listened to people sooner, it wouldn’t have come to this” — and blushes."),
    P(36, "tie", "梦兆绛芸轩", "宝钗坐在宝玉床边替他绣兜肚，忽听宝玉在梦中喊骂：“什么是金玉姻缘，我偏说是木石姻缘！”",
      "A dream overheard", "Sitting by Baoyu’s bed embroidering his undershirt, Baochai hears him shout in his sleep: “Gold and jade? I say wood and stone!”"),
    P(97, "kin", "出闺成大礼", "宝玉失玉疯癫，贾母、王夫人和凤姐定下调包计；宝钗含悲出嫁，宝玉还以为娶的是黛玉。",
      "The wedding", "With Baoyu out of his wits, the elders arrange the switch; Baochai is married to him in sorrow while he believes his bride is Daiyu.", (96, 97)),
    P(119, "kin", "尘缘已断", "宝玉中举后出走，宝钗已有身孕。",
      "Left behind", "Baoyu passes the examination and vanishes, leaving Baochai with child.", (119, 120))),
  E("daiyu", "baochai",
    P(8, "tie", "半含酸", "黛玉来梨香院，见宝玉也在，便说“早知他来，我就不来了”，话里带着酸意。",
      "A little sour", "Finding Baoyu at Baochai’s, Daiyu remarks, “Had I known he was here, I wouldn’t have come.”"),
    P(27, "tie", "金蝉脱壳", "宝钗在滴翠亭外偷听到小红的私话，怕被疑心，故意喊“颦儿，我看你往那里藏”，好像黛玉也在附近。",
      "A convenient name", "Overhearing two maids’ secret, Baochai calls out “Pin’er, where are you hiding?” so they will think Daiyu was the eavesdropper."),
    P(42, "aid", "兰言解疑癖", "宝钗私下劝黛玉不该在行酒令时说出《西厢》《牡丹亭》里的句子，黛玉心服。",
      "Sisterly counsel", "Baochai quietly warns Daiyu against quoting The Western Chamber and The Peony Pavilion in a drinking game; Daiyu is won over."),
    P(45, "aid", "金兰契", "宝钗来探病，又送燕窝来，黛玉说从前错怪了她，两人互剖心事，结为知己。",
      "Sworn sisters", "Baochai visits Daiyu in her illness and sends bird’s nest; Daiyu admits she misjudged her, and they open their hearts to each other."),
    P(97, "tie", "调包", "宝钗与宝玉成婚的同一时刻，黛玉在潇湘馆死去。",
      "The switch", "At the hour Baochai is married to Baoyu, Daiyu dies at Bamboo Lodge.", (97, 98))),
  E("baoyu", "xiangyun",
    P(20, "kin", "表兄妹", "湘云来了，咬舌把“二哥哥”叫成“爱哥哥”，黛玉取笑她。",
      "Cousins", "Xiangyun arrives and, with her lisp, calls Baoyu “Ai-gege”; Daiyu teases her."),
    P(31, "tie", "白首双星", "宝玉在清虚观得了一只金麒麟，想留给也戴着麒麟的湘云，不想丢了，被湘云和翠缕拾到；回目说“因麒麟伏白首双星”。",
      "The gold unicorn", "Baoyu keeps a gold unicorn from the temple for Xiangyun, who wears one like it; he drops it and she finds it. The chapter title hints the two will grow old together.", (29, 31)),
    P(32, "tie", "混帐话", "湘云劝宝玉留心仕途经济，宝玉说：“林姑娘从来说过这些混帐话不曾？若他也说过这些混帐话，我早和他生分了。”",
      "“Rubbish”", "When Xiangyun urges him to think about a career, Baoyu asks whether Miss Lin has ever talked such rubbish — if she had, he would have broken with her long ago.")),

  # =============================================================== Baoyu and the maids
  E("baoyu", "xiren",
    P(3, "mas", "改名袭人", "袭人原是贾母的丫鬟，给了宝玉，宝玉替她改名袭人。",
      "A new name", "Xiren, once Grandmother Jia’s maid, is given to Baoyu, who renames her."),
    P(6, "love", "初试云雨情", "宝玉从太虚幻境醒来，与袭人“初试云雨情”。",
      "The first time", "Waking from the Land of Illusion, Baoyu sleeps with Xiren."),
    P(19, "tie", "花解语", "袭人借家里要赎她回去的话，要宝玉答应三件事：不说死、作出个喜读书的样子、不毁僧谤道。",
      "Three conditions", "Pretending her family may buy her back, Xiren makes Baoyu promise three things: no talk of death, some show of study, and no mocking the clergy."),
    P(30, "tie", "误踢", "宝玉淋雨回来叫门，开门迟了，一脚踢在开门的袭人肋上，袭人当夜吐血。",
      "The kick", "Soaked and kept waiting at the gate, Baoyu kicks whoever opens it — Xiren — and that night she coughs blood.", (30, 31)),
    P(36, "mas", "姨娘份例", "王夫人从自己的月钱里给袭人二两银子一吊钱，等于默认她是宝玉的屋里人。",
      "A concubine’s allowance", "Lady Wang pays Xiren a concubine’s allowance from her own purse, tacitly marking her as Baoyu’s."),
    P(77, "tie", "疑心", "晴雯等人被撵，宝玉问袭人：“怎么人人的不是太太都知道，单不挑出你和麝月秋纹来？”",
      "Suspicion", "After Qingwen and the others are dismissed, Baoyu asks Xiren why Lady Wang knows everyone’s faults except hers, Sheyue’s and Qiuwen’s."),
    P(120, "tie", "另嫁", "宝玉出家后，袭人被家人许给了蒋玉菡，含悲出嫁。",
      "Married off", "After Baoyu leaves the world, Xiren’s family marries her to Jiang Yuhan.")),
  E("baoyu", "qingwen",
    P(5, "mas", "宝玉的丫鬟", "晴雯是宝玉屋里的丫鬟。",
      "His maid", "Qingwen is one of Baoyu’s maids."),
    P(31, "aid", "撕扇", "晴雯跌断扇骨，宝玉说了她两句，两人吵起来；晚上宝玉拿扇子给她撕着玩，说“千金难买一笑”。",
      "Tearing fans", "She breaks a fan, he scolds, they quarrel; that evening he gives her fans to tear for fun — a smile is worth more than gold."),
    P(52, "aid", "病补雀金裘", "宝玉的孔雀毛大氅烧了个洞，外头没人敢接，晴雯病中挣扎着熬夜补好，补完便身不由主倒下了。",
      "Mending the cloak", "When Baoyu’s peacock-feather cloak is burnt and no tailor will touch it, Qingwen, though ill, mends it overnight and collapses."),
    P(77, "love", "抱屈夭风流", "晴雯病中被撵，宝玉偷偷去看她，她铰下两根指甲给宝玉，又和他换了贴身的袄儿，说“早知如此，我当日也另有个道理”。",
      "Wronged", "Thrown out while ill, Qingwen is visited by Baoyu; she cuts off two of her fingernails for him and exchanges inner jackets with him — had she known she would be accused anyway, she would have acted otherwise."),
    P(78, "love", "芙蓉女儿诔", "小丫头说晴雯做了芙蓉花神，宝玉写了《芙蓉女儿诔》，在芙蓉花前祭她。",
      "Dirge for the Hibiscus Maiden", "Told she has become the spirit of the hibiscus, Baoyu writes a dirge and reads it before the flowers.")),
  E("baoyu", "sheyue",
    P(20, "mas", "篦头", "众人都出去玩，麝月独自看屋子，宝玉替她篦头，被晴雯撞见取笑。",
      "Combing her hair", "With the others out, Baoyu combs Sheyue’s hair; Qingwen walks in and teases them.")),
  E("baoyu", "mingyan",
    P(9, "mas", "闹学堂", "金荣辱骂秦钟，茗烟受贾蔷挑唆，冲进学堂大骂，引起混战。",
      "The school brawl", "Egged on by Jia Qiang, Mingyan storms in to abuse Jin Rong, and a brawl breaks out."),
    P(19, "mas", "私访袭人家", "宝玉闷得慌，茗烟带他偷偷到袭人家去。",
      "A secret visit", "Mingyan takes the bored Baoyu secretly to Xiren’s family home."),
    P(43, "mas", "井台致祭", "金钏生日，茗烟陪宝玉到城外水仙庵，在井台上焚香，还替宝玉祷告。",
      "Rites at the well", "On Jinchuan’s birthday Mingyan goes with Baoyu to a convent well to burn incense, and adds a prayer of his own.")),
  E("baoyu", "limama",
    P(8, "tie", "枫露茶", "李嬷嬷拿走了留给晴雯的包子，又喝了宝玉沏的枫露茶，宝玉摔了茶杯，要撵她出去。",
      "The maple-dew tea", "Nanny Li takes the dumplings saved for Qingwen and drinks Baoyu’s tea; he smashes his cup and threatens to have her dismissed.")),
  E("baoyu", "jinchuan",
    P(30, "tie", "一句玩笑", "王夫人午睡，宝玉和金钏调笑，金钏说“金簪子掉在井里头，有你的只是有你的”；王夫人翻身打了她一个嘴巴，宝玉早一溜烟跑了。",
      "A joke", "While Lady Wang naps Baoyu flirts with Jinchuan; Lady Wang wakes and slaps her, and Baoyu slips away."),
    P(32, "tie", "投井", "金钏被撵出去后投井而死，宝玉“五内摧伤”。",
      "The well", "Dismissed, Jinchuan drowns herself; Baoyu is heartbroken.", (32, 33)),
    P(43, "love", "私祭", "金钏生日，宝玉偷偷出城，在水仙庵的井台上焚香祭她。",
      "Incense at the well", "On her birthday Baoyu slips out of the city and burns incense for her at a convent well.")),
  E("baoyu", "yuchuan",
    P(35, "tie", "亲尝莲叶羹", "玉钏奉命给宝玉送莲叶羹，恨他害死了姐姐，冷着脸不理他；宝玉百般陪笑，她才笑了，又被宝玉哄着尝了一口。",
      "The lotus-leaf soup", "Sent with soup, Yuchuan will not speak to the young man she blames for her sister’s death, until his coaxing makes her laugh despite herself; then he tricks her into tasting it.")),
  E("baoyu", "xiaohong",
    P(24, "mas", "倒茶", "小红趁屋里没人给宝玉倒了碗茶，被秋纹、碧痕撞见，骂她想往上爬。",
      "A cup of tea", "Xiaohong pours Baoyu tea while the senior maids are out, and is scolded for trying to rise above her place.")),
  E("baoyu", "fangguan",
    P(58, "mas", "茜纱窗", "芳官分到怡红院；宝玉从她那里听说藕官为死去的菂官烧纸的缘故，又是欢喜，又是悲叹。",
      "Behind the green gauze", "Fangguan joins Baoyu’s household; through her he learns why Ouguan burns offerings for a dead fellow actress, and is moved."),
    P(63, "aid", "寿怡红", "宝玉生日夜宴，芳官喝醉了，和宝玉同榻睡了一夜；宝玉又给她起了个番名叫“耶律雄奴”。",
      "The birthday party", "At Baoyu’s birthday party Fangguan falls asleep drunk beside him; he gives her a foreign nickname.", (62, 63))),
  E("baoyu", "lingguan",
    P(30, "tie", "划蔷", "宝玉看见一个女孩子在蔷薇架下一遍遍地划“蔷”字，下雨了，他提醒她避雨，自己倒淋湿了。",
      "A name in the earth", "Baoyu watches a girl scratch one character over and over under the rose trellis; when the rain comes he warns her and gets soaked himself."),
    P(36, "tie", "识分定", "宝玉请龄官唱曲，她正色说“嗓子哑了”；看见她和贾蔷的情形，宝玉才明白“人生情缘，各有分定”。",
      "Each to their own", "Lingguan coldly refuses to sing for him; watching her with Jia Qiang, Baoyu understands that each person’s love is destined for someone.")),
  E("baoyu", "yuanyang",
    P(24, "tie", "讨胭脂", "宝玉猴在鸳鸯身上，要吃她嘴上的胭脂，被袭人说了一顿。",
      "Rouge", "Baoyu hangs on Yuanyang begging to taste her lip rouge, and Xiren scolds him.")),
  E("baoyu", "pinger",
    P(44, "aid", "理妆", "平儿无故挨打，宝玉请她到怡红院，拿出自制的脂粉让她理妆，觉得是“今生意中不想之乐”。",
      "Making up Ping’er", "When Ping’er is struck for no fault, Baoyu brings her to his rooms and offers her his own powder and rouge to make herself up, delighted at the unlooked-for chance.")),
  E("baoyu", "zijuan",
    P(57, "tie", "情辞试忙玉", "紫鹃说林姑娘要回苏州，宝玉急病了，死拉住紫鹃不放。",
      "The test", "Zijuan’s story that Daiyu is leaving makes Baoyu ill, and he will not let go of her."),
    P(113, "tie", "释旧憾", "宝玉夜里隔窗向紫鹃诉说苦衷，紫鹃才渐渐明白他的心。",
      "Understanding", "Baoyu pleads with Zijuan through her window at night, and she comes to understand him.")),
  E("baoyu", "xiangling",
    P(62, "aid", "情解石榴裙", "香菱斗草时弄脏了新裙子，宝玉叫袭人拿一条一样的石榴红绫裙给她换上。",
      "The pomegranate skirt", "When Xiangling ruins her new skirt playing in the grass, Baoyu has Xiren bring an identical one.")),

  # =============================================================== Baoyu and the wider world
  E("baoyu", "qinzhong",
    P(7, "aid", "一见如故", "宝玉在宁府见到秦钟，两人互相倾慕，约好一同入塾读书。",
      "Friends at first sight", "They meet at the Ning mansion, are charmed by each other, and agree to study together."),
    P(9, "aid", "同入家塾", "两人一同上学，惹出闹学堂的风波。",
      "At school", "They join the clan school together, and set off a brawl."),
    P(15, "tie", "馒头庵", "宝玉撞破秦钟与智能儿私会，说等睡下再和他算账。",
      "At the convent", "Baoyu catches Qin Zhong with the nun Zhineng and says he will settle with him later."),
    P(16, "aid", "临终之言", "秦钟临终劝宝玉“以后还该立志功名，以荣耀显达为是”。",
      "Last words", "Dying, Qin Zhong tells Baoyu he should seek an official career after all.")),
  E("baoyu", "jiangyuhan",
    P(28, "aid", "互赠汗巾", "宝玉和琪官一见如故，互换了汗巾。",
      "Exchanging sashes", "Baoyu and the actor Qiguan take to each other and exchange sashes."),
    P(33, "tie", "琪官之祸", "忠顺王府来要人，宝玉被迫说出琪官藏身的紫檀堡，回头便挨了父亲的毒打。",
      "Trouble over Qiguan", "The Prince of Zhongshun’s steward comes for the runaway actor; Baoyu has to give away his hiding place, and is then beaten by his father."),
    P(93, "aid", "重逢", "宝玉在临安伯府看戏，又见到了蒋玉菡。",
      "Meeting again", "At a party Baoyu sees Jiang Yuhan on stage again.")),
  E("baoyu", "beijingwang",
    P(15, "aid", "路谒北静王", "秦可卿出殡，北静王召宝玉相见，赞他“果然如'宝'似'玉'”，赠他鹡鸰香念珠。",
      "On the road", "At Qin Keqing’s funeral the prince calls Baoyu to him, praises him and gives him the emperor’s rosary.", (14, 15))),
  E("baoyu", "liuxianglian",
    P(47, "aid", "知交", "宝玉和柳湘莲交好，柳湘莲一直照看着秦钟的坟。",
      "Friends", "Baoyu and Liu Xianglian are friends; Liu has been tending Qin Zhong’s grave."),
    P(66, "tie", "一句话", "柳湘莲问起尤三姐，宝玉说她是珍大嫂子继母带来的；柳湘莲跌脚道，“你们东府里除了那两个石头狮子干净，只怕连猫儿狗儿都不干净”。",
      "A careless answer", "When Liu asks about You Sanjie, Baoyu says she is Madam You’s stepsister. Liu stamps: in the East Mansion, he says, only the stone lions at the gate are clean.")),
  E("baoyu", "miaoyu",
    P(41, "aid", "品茶", "妙玉请宝钗、黛玉吃体己茶，宝玉跟了来，她用自己日常吃茶的绿玉斗给宝玉斟茶。",
      "Tea at the hermitage", "Miaoyu serves Baochai and Daiyu her finest tea; Baoyu tags along, and she pours his in her own green jade cup."),
    P(50, "aid", "乞红梅", "宝玉联诗落第，被罚去栊翠庵向妙玉讨红梅。",
      "Begging plum blossom", "Losing at linked verse, Baoyu is sent to Miaoyu to beg a branch of red plum."),
    P(63, "aid", "槛外人", "宝玉生日，妙玉送来一张粉笺，落款“槛外人”；宝玉回帖署“槛内人”。",
      "Outside the threshold", "For his birthday Miaoyu sends a card signed “one outside the threshold”; he signs his reply “one inside the threshold”."),
    P(87, "tie", "走火入魔", "妙玉在惜春处见到宝玉，不觉脸红；夜里打坐心神不定，走火入魔。",
      "Possessed", "Meeting Baoyu at Xichun’s, Miaoyu blushes; that night her meditation goes astray and she is possessed.")),
  E("baoyu", "jiahuan",
    P(25, "foe", "推灯烫脸", "贾环故意推倒蜡灯，把滚热的蜡油泼在宝玉脸上。",
      "Hot wax", "Jia Huan deliberately knocks over a candle, splashing hot wax over Baoyu’s face."),
    P(33, "foe", "进谗", "贾环对贾政说，金钏是被宝玉强奸不遂，才投井的。",
      "Slander", "Jia Huan tells their father that Jinchuan drowned herself after Baoyu tried to force himself on her.")),
  E("baoyu", "zhaoyiniang",
    P(25, "foe", "魇魔法", "赵姨娘买通马道婆魇镇宝玉，宝玉发狂，几乎丧命。",
      "Black magic", "Concubine Zhao pays Mother Ma to bewitch Baoyu, who goes mad and nearly dies.")),
  E("baoyu", "madaopo",
    P(25, "foe", "寄名干娘", "马道婆是宝玉的寄名干娘，却拿了赵姨娘的钱，用魇魔法害他。",
      "A false godmother", "Baoyu’s godmother in religion takes Concubine Zhao’s money and bewitches him.")),
  E("baoyu", "sengdao",
    P(1, "aid", "携入红尘", "一僧一道把女娲补天剩下的顽石化成美玉，携入红尘。",
      "Into the world", "The monk and the Taoist turn the stone left from mending the sky into a jade and carry it into the world."),
    P(25, "aid", "通灵遇双真", "宝玉中了魇魔法，癞僧跛道来到，把通灵玉持诵一番，宝玉才好了。",
      "The jade restored", "When Baoyu is bewitched the two arrive and chant over the jade, and he recovers."),
    P(115, "aid", "送玉", "宝玉失玉病危，一个和尚送来了玉，宝玉的魂魄随他再游太虚幻境。",
      "The jade returned", "With Baoyu near death a monk brings back the jade, and Baoyu’s spirit follows him to the Land of Illusion again.", (115, 116)),
    P(120, "aid", "飘然而去", "宝玉披着大红猩猩毡斗篷，在雪地里拜别父亲，被一僧一道夹着飘然而去。",
      "Gone", "In a scarlet cloak in the snow, Baoyu bows to his father and goes off between the monk and the Taoist.")),
  E("baoyu", "jinghuan",
    P(5, "aid", "太虚幻境", "警幻领宝玉看十二钗的册子，听《红楼梦》十二支曲，盼他“改悟前情”。",
      "The Land of Illusion", "Disenchantment shows Baoyu the registers of the Twelve Beauties and has the twelve songs performed, hoping to cure him of love."),
    P(116, "aid", "再游幻境", "宝玉魂游太虚，重看册子，渐渐悟了。",
      "A second visit", "Baoyu’s spirit visits the Land of Illusion again, rereads the registers and begins to understand.")),
  E("baoyu", "zhenbaoyu",
    P(56, "tie", "梦中相见", "宝玉梦见自己到了甄家，见到一个和自己一模一样的宝玉。",
      "A dream of his double", "Baoyu dreams he visits the Zhens and meets a Baoyu just like himself."),
    P(115, "tie", "失相知", "两人终于相见，甄宝玉满口仕途经济，宝玉大失所望。",
      "No kindred spirit", "They meet at last, but Zhen Baoyu talks only of careers, and Baoyu is bitterly disappointed.")),
  E("baoyu", "liulaolao",
    P(39, "tie", "寻根究底", "刘姥姥随口编了个雪下抽柴的女孩儿的故事，宝玉信以为真，第二天就派茗烟去找那女孩儿的庙。",
      "A tall tale", "Granny Liu invents a girl who gathers firewood in the snow; Baoyu believes it and sends Mingyan to find her shrine.")),
  E("baoyu", "jiayun",
    P(24, "aid", "认作父亲", "宝玉说贾芸“倒象我的儿子”，贾芸顺势认他做父亲。",
      "An adopted ‘son’", "Baoyu says Jia Yun looks like his son, and Jia Yun promptly adopts him as a father.")),
  E("baoyu", "tanchun",
    P(27, "aid", "兄妹", "探春托宝玉在外头买些精巧的玩意儿，答应给他做鞋。",
      "Brother and sister", "Tanchun asks Baoyu to buy her some pretty trinkets outside, and promises to make him shoes."),
    P(37, "aid", "海棠社", "探春写帖子给宝玉，发起诗社。",
      "The poetry club", "Tanchun writes to Baoyu proposing a poetry club."),
    P(100, "tie", "悲远嫁", "宝玉听说探春要远嫁，“啊呀”一声，哭倒在炕上。",
      "A distant marriage", "Hearing that Tanchun will be married far away, Baoyu collapses in tears.", (100, 102))),
  E("baoyu", "yuanchun",
    P(18, "kin", "姊弟裁题咏", "元春入宫前亲自教宝玉读书，“其名分虽系姊弟，其情状有如母子”；省亲时她命宝玉题诗，黛玉暗中替他作了一首《杏帘在望》。",
      "Sister and brother", "Before entering the palace Yuanchun taught Baoyu to read, “a sister in name, a mother in fact”. On her visit she sets him to write poems, and Daiyu secretly writes one for him.", (17, 18)),
    P(23, "kin", "命住园中", "元妃命宝玉随姊妹们住进大观园。",
      "Into the garden", "The Consort orders Baoyu to live in the garden with the girls."),
    P(95, "kin", "元妃薨逝", "元妃病逝，宝玉此时已失玉昏愦。",
      "Her death", "The Consort dies while Baoyu, without his jade, is lost in a daze.")),
  E("baoyu", "qinkeqing",
    P(5, "tie", "梦游太虚", "宝玉在秦可卿房中午睡，梦游太虚幻境，梦中警幻把“乳名兼美字可卿”的妹妹许给了他。",
      "A dream in her room", "Napping in Qin Keqing’s room, Baoyu dreams of the Land of Illusion, where he is married to a fairy also called Keqing."),
    P(13, "kin", "闻丧吐血", "宝玉夜里听说秦氏死了，“只觉心中似戳了一刀的不忍”，哇地吐出一口血来。",
      "The news", "Hearing in the night that she has died, Baoyu feels stabbed to the heart and spits blood.")),
  E("baoyu", "jialan",
    P(119, "kin", "叔侄同榜", "宝玉与侄子贾兰同中乡试。",
      "Uncle and nephew", "Baoyu and his nephew Jia Lan pass the provincial examination together.")),

  # =============================================================== Grandmother Jia
  E("jiamu", "baoyu",
    P(3, "kin", "心肝宝贝", "宝玉是贾母最疼的孙子，从小养在她身边。",
      "Her darling", "Baoyu is Grandmother Jia’s darling, raised at her side."),
    P(33, "kin", "护孙", "贾政毒打宝玉，贾母赶来，说“先打死我，再打死他，岂不干净了”。",
      "“Kill me first”", "When Jia Zheng beats Baoyu, his grandmother arrives: “Kill me first, then him — that will settle it!”"),
    P(96, "kin", "冲喜", "宝玉失玉疯癫，贾母做主让他娶宝钗冲喜。",
      "A wedding for luck", "With Baoyu out of his mind, she decides to marry him to Baochai to turn his luck.", (96, 97))),
  E("jiamu", "daiyu",
    P(3, "kin", "惜孤女", "黛玉进府，贾母一把搂入怀中，“心肝儿肉”叫着大哭起来。",
      "Her motherless granddaughter", "When Daiyu arrives Grandmother Jia takes her in her arms, calling her “my heart”, and weeps."),
    P(97, "tie", "冷了心", "贾母听说黛玉的病是为宝玉，冷了心，说“这心病也是断断有不得的”。",
      "Her heart hardens", "Told that Daiyu is lovesick for Baoyu, her grandmother turns cold: such feelings must not be.", (96, 97))),
  E("jiamu", "xifeng",
    P(3, "kin", "凤辣子", "贾母对黛玉笑道：“他是我们这里有名的一个泼皮破落户儿，南省俗谓作'辣子'，你只叫他'凤辣子'就是了。”",
      "“Peppery Feng”", "Grandmother Jia introduces her to Daiyu as the family’s notorious hot pepper: “Just call her Peppery Feng.”"),
    P(44, "kin", "泼醋", "凤姐撞破贾琏私情，闹到贾母跟前；贾母笑说“小孩子们年轻，馋嘴猫儿似的”，替他们调停。",
      "The jealous scene", "Xifeng storms to Grandmother Jia over Jia Lian’s affair; the old lady laughs that young men are like greedy cats, and makes peace."),
    P(110, "tie", "力诎失人心", "贾母丧事，凤姐手里无钱，又被邢夫人掣肘，处处不周，“失人心”。",
      "At the end of her strength", "Short of money and blocked by Lady Xing, Xifeng cannot manage Grandmother Jia’s funeral and loses the household’s respect.")),
  E("jiamu", "yuanyang",
    P(24, "mas", "心腹丫鬟", "鸳鸯是贾母最离不开的丫鬟，宴席上替贾母三宣牙牌令。",
      "Indispensable", "Yuanyang is the maid Grandmother Jia cannot do without, who calls the domino rules at her feast.", [24, 40]),
    P(46, "mas", "铰发明志", "贾赦要讨鸳鸯，鸳鸯跪在贾母面前铰发立誓；贾母气得浑身乱战。",
      "Refusing Jia She", "When Jia She demands her, Yuanyang kneels before her mistress, cuts her hair and swears never to marry; the old lady shakes with rage."),
    P(111, "mas", "殉主", "贾母去世，鸳鸯自缢殉主。",
      "Following her mistress", "After Grandmother Jia’s death Yuanyang hangs herself.")),
  E("jiamu", "xiangyun",
    P(20, "kin", "侄孙女", "湘云是贾母娘家的侄孙女，常被接来住。",
      "Her grandniece", "Xiangyun, granddaughter of Grandmother Jia’s brother, often comes to stay.")),
  E("jiamu", "liulaolao",
    P(39, "aid", "老亲家", "贾母正想找个积古的老人家说话，听说来了个乡下老太太，便留她住下。",
      "An old friend", "Wanting an old person to talk to, Grandmother Jia invites the visiting countrywoman to stay."),
    P(40, "aid", "两宴大观园", "贾母带刘姥姥游大观园，刘姥姥装傻逗乐。",
      "The garden feasts", "Grandmother Jia shows Granny Liu the garden, and Granny Liu plays the fool to amuse everyone.", (40, 41))),
  E("jiamu", "baochai",
    P(22, "kin", "做生日", "贾母自己拿出二十两银子，给宝钗做十五岁的生日。",
      "A birthday", "Grandmother Jia pays twenty taels of her own for Baochai’s fifteenth birthday."),
    P(35, "kin", "夸赞", "贾母当着薛姨妈说：“千真万真，从我们家四个女孩儿算起，全不如宝丫头。”",
      "Praise", "Grandmother Jia tells Aunt Xue that none of her own four granddaughters can match Baochai."),
    P(96, "kin", "定亲", "贾母做主，为宝玉聘定了宝钗。",
      "The match", "Grandmother Jia arranges Baoyu’s marriage to Baochai.", (96, 97))),
  E("jiamu", "wangfuren",
    P(46, "kin", "错怪", "贾母为鸳鸯的事气急，连王夫人一起数落；探春提醒后，贾母知道错怪了，又向王夫人赔不是。",
      "Blamed and forgiven", "In her fury over Yuanyang she scolds Lady Wang too; when Tanchun points out the mistake, she apologizes.")),
  E("jiamu", "xingfuren",
    P(47, "tie", "贤慧太过", "贾母数落邢夫人：“你倒也三从四德，只是这贤慧也太过了！”",
      "Too obedient", "Grandmother Jia rebukes Lady Xing for helping her husband: “Your wifely virtue goes too far!”")),
  E("jiamu", "jiashe",
    P(3, "kin", "母子", "贾赦是贾母的长子。",
      "Mother and son", "Jia She is her elder son."),
    P(46, "tie", "讨鸳鸯", "贾赦想讨母亲的丫鬟鸳鸯做妾，贾母大怒。",
      "Yuanyang", "Jia She wants his mother’s maid as a concubine, and she is furious.")),
  E("jiamu", "jiazheng",
    P(3, "kin", "母子", "贾政是贾母的次子，最孝顺。",
      "Mother and son", "Jia Zheng is her dutiful younger son."),
    P(33, "tie", "大承笞挞", "贾政毒打宝玉，贾母冷笑说要带着宝玉回南京去。",
      "The beating", "When Jia Zheng beats Baoyu, his mother coldly threatens to take the boy back to Nanjing.")),
  E("jiamu", "qinkeqing",
    P(5, "kin", "重孙媳", "贾母素知秦氏极妥当，是重孙媳中第一个得意之人。",
      "Great-granddaughter-in-law", "Grandmother Jia thinks Qin Keqing the best of her great-grandsons’ wives.")),
  E("jiamu", "baoqin",
    P(49, "kin", "疼爱", "贾母一见宝琴就喜欢，逼着王夫人认作干女儿，送她凫靥裘，还想把她说给宝玉。",
      "A favourite", "Grandmother Jia dotes on Baoqin, makes Lady Wang adopt her, gives her a feather cloak and even thinks of her for Baoyu.", (49, 50))),
  E("jiamu", "yingchun",
    P(109, "kin", "诀别", "迎春回贾府，对贾母说“我只是没有再来的时候了”。",
      "Farewell", "On her last visit Yingchun tells her grandmother she will never come again.")),
  E("jiamu", "shadajie",
    P(73, "mas", "做粗活", "傻大姐是贾母房里做粗活的丫头，贾母爱拿她取笑。",
      "Maid of all work", "Simple Sister does the rough work in Grandmother Jia’s rooms and amuses her.")),
  E("jiamu", "yuanchun",
    P(18, "kin", "呜咽对泣", "元妃省亲，见了祖母和母亲，三人满心里有许多话，只是说不出，只管呜咽对泣。",
      "Tears", "On her visit home the Consort, her grandmother and her mother can only weep together.")),

  # =============================================================== Jia She and Lady Xing
  E("jiashe", "xingfuren",
    P(3, "kin", "夫妻", "邢夫人是贾赦的妻子，一味顺从他。",
      "Husband and wife", "Lady Xing does whatever her husband wants.")),
  E("jiashe", "jialian",
    P(2, "kin", "父子", "贾琏是贾赦的儿子。",
      "Father and son", "Jia Lian is Jia She’s son."),
    P(48, "tie", "石呆子的扇子", "贾琏说了一句“为这点子小事，弄得人坑家败业，也不算什么能为”，被贾赦打得动不得。",
      "The fans", "When Jia Lian objects to ruining a man over some old fans, his father beats him until he cannot move."),
    P(69, "kin", "赏妾", "贾琏办事得力，贾赦把丫鬟秋桐赏给他做妾。",
      "A reward", "Pleased with his son, Jia She gives him the maid Qiutong as a concubine.")),
  E("jiashe", "yingchun",
    P(3, "kin", "父女", "迎春是贾赦的妾所生。",
      "Father and daughter", "Yingchun is Jia She’s daughter by a concubine."),
    P(79, "tie", "许嫁", "贾赦不听贾政劝阻，把迎春许给孙绍祖。",
      "The match", "Ignoring Jia Zheng’s advice, Jia She marries Yingchun to Sun Shaozu.")),
  E("jiashe", "yuanyang",
    P(46, "foe", "逼娶", "贾赦被拒，扬言凭她嫁到谁家去，也难出他的手心。",
      "Threats", "Refused, Jia She swears that wherever she marries she will not escape him.")),
  E("jiashe", "sunshaozu",
    P(79, "tie", "五千两", "贾赦使过孙绍祖五千两银子，把迎春许给了他。",
      "Five thousand taels", "Jia She owes Sun Shaozu five thousand taels, and gives him Yingchun.", (79, 80))),
  E("jiashe", "yucun",
    P(48, "aid", "夺扇", "贾雨村为讨好贾赦，诬石呆子拖欠官银，抄来二十把古扇送给贾赦。",
      "The fans", "To please Jia She, Jia Yucun ruins a poor man on a false charge and seizes his antique fans.")),
  E("jiashe", "qiutong",
    P(69, "mas", "赏人", "秋桐是贾赦房中的丫鬟，被赏给贾琏为妾。",
      "Given away", "Qiutong, Jia She’s maid, is given to his son.")),
  E("xingfuren", "yingchun",
    P(73, "tie", "嫡母", "迎春的乳母聚赌被罚，邢夫人反来责备迎春。",
      "Stepmother", "When Yingchun’s nurse is caught gambling, Lady Xing blames Yingchun.")),
  E("xingfuren", "xifeng",
    P(3, "kin", "婆媳", "凤姐是邢夫人的儿媳。",
      "Mother-in-law", "Xifeng is Lady Xing’s daughter-in-law."),
    P(71, "tie", "当众给没脸", "贾母寿宴上，邢夫人当着众人替得罪尤氏的婆子向凤姐求情，凤姐又羞又气，回房哭了。",
      "Public humiliation", "At Grandmother Jia’s birthday Lady Xing pointedly asks Xifeng, before everyone, to release two women who offended Madam You; Xifeng weeps with shame.")),
  E("xingfuren", "wangshanbao",
    P(74, "mas", "陪房", "王善保家的是邢夫人的陪房，替她到园里抄检。",
      "Her woman", "Wang Shanbao’s wife came with Lady Xing at her marriage, and acts for her in the search.")),
  E("xingfuren", "yuanyang",
    P(46, "foe", "说媒", "邢夫人亲自去找鸳鸯，劝她去给贾赦做姨娘。",
      "Matchmaking", "Lady Xing goes herself to persuade Yuanyang to be Jia She’s concubine.")),
  E("xingfuren", "shadajie",
    P(73, "tie", "绣春囊", "傻大姐拿着捡来的绣春囊，迎面碰上邢夫人。",
      "The pouch", "Simple Sister, carrying the pouch she found, runs into Lady Xing.")),
  E("xingfuren", "wangfuren",
    P(74, "tie", "封囊相送", "邢夫人把绣春囊封了，送给王夫人，等于责她管家不严。",
      "A pointed gift", "Lady Xing sends the pouch sealed to Lady Wang — an accusation of lax housekeeping.")),
  E("xingfuren", "qiaojie",
    P(118, "foe", "许给外藩", "贾琏出门，邢夫人听信王仁、贾芸等人，要把巧姐许给外藩王爷。",
      "Sold off", "With Jia Lian away, Lady Xing is talked into giving Qiaojie to a foreign prince.", (118, 119))),

  # =============================================================== Jia Zheng and Lady Wang
  E("jiazheng", "wangfuren",
    P(3, "kin", "夫妻", "王夫人是贾政的妻子。",
      "Husband and wife", "Lady Wang is Jia Zheng’s wife.")),
  E("jiazheng", "zhaoyiniang",
    P(20, "kin", "妾", "赵姨娘是贾政的妾，生了探春和贾环。",
      "Concubine", "Concubine Zhao has borne Jia Zheng a daughter and a son.")),
  E("jiazheng", "baoyu",
    P(2, "kin", "抓周", "宝玉周岁抓周，只抓脂粉钗环，贾政从此不喜欢他。",
      "The first birthday", "At his first birthday Baoyu grabs only rouge and hairpins, and his father has disliked him ever since."),
    P(17, "tie", "试才题对额", "大观园落成，贾政带宝玉游园题匾额对联，嘴上骂，心里也暗暗称许。",
      "Naming the garden", "Jia Zheng takes Baoyu round the new garden to compose inscriptions, scolding him all the while but secretly pleased."),
    P(33, "foe", "大承笞挞", "贾政听说宝玉结交优伶、逼死金钏，叫人把他按在凳上，亲自打了三四十板。",
      "The beating", "Told that Baoyu befriends actors and drove a maid to her death, Jia Zheng has him held down and beats him savagely himself."),
    P(120, "kin", "雪地拜别", "贾政扶贾母灵柩回南安葬，归途泊船毗陵驿，在雪影里看见宝玉向他拜了四拜，随一僧一道而去。",
      "Farewell in the snow", "Sailing home after burying his mother in the south, Jia Zheng sees Baoyu bow to him four times in the falling snow and vanish with the monk and the Taoist.")),
  E("jiazheng", "jiahuan",
    P(33, "kin", "进谗", "贾环跑到贾政面前告宝玉的状。",
      "Telling tales", "Jia Huan runs to his father with tales about Baoyu.")),
  E("jiazheng", "tanchun",
    P(22, "kin", "风筝谜", "探春的灯谜是风筝，贾政看了，觉得不祥。",
      "The kite riddle", "Tanchun’s lantern riddle is a kite; her father finds it ill-omened."),
    P(99, "kin", "远嫁", "贾政在任上把探春许给了镇守海疆的周家。",
      "A distant match", "At his post Jia Zheng betroths Tanchun to the son of a coastal commander.", (99, 100))),
  E("jiazheng", "yuanchun",
    P(18, "kin", "隔帘奏对", "元妃省亲，贾政隔着帘子参见，父女垂泪，互相勉励。",
      "Behind the curtain", "On her visit Jia Zheng speaks to his daughter from behind a curtain; both weep and urge each other to loyal duty.")),
  E("jiazheng", "yucun",
    P(3, "aid", "援引", "贾雨村持林如海的荐书来见，贾政竭力内中协助，雨村补了金陵应天府。",
      "Patronage", "Jia Yucun brings Lin Ruhai’s letter, and Jia Zheng helps him to a post as prefect of Yingtian.")),
  E("jiazheng", "beijingwang",
    P(105, "aid", "照应", "锦衣军查抄贾府，北静王奉旨前来，处处照应贾政。",
      "Protection", "When imperial guards search the house, the Prince of Beijing arrives with the emperor’s orders and protects Jia Zheng.")),
  E("wangfuren", "baoyu",
    P(3, "kin", "孽根祸胎", "王夫人对黛玉说，宝玉是她的“孽根祸胎”，是家里的“混世魔王”。",
      "Root of all trouble", "Lady Wang warns Daiyu that her son is the “root of all trouble”, the household’s little demon king.")),
  E("wangfuren", "jinchuan",
    P(7, "mas", "主仆", "金钏是王夫人房里的大丫鬟。",
      "Mistress and maid", "Jinchuan is Lady Wang’s senior maid."),
    P(30, "foe", "掌掴撵逐", "王夫人打了金钏一个嘴巴，不顾她哭求，叫玉钏把她母亲叫来，领了出去。",
      "Slapped and dismissed", "Lady Wang slaps Jinchuan and, deaf to her pleas, has her mother take her away."),
    P(32, "tie", "愧悔", "金钏投井，王夫人哭着对宝钗说“岂不是我的罪过”；宝钗拿了自己的两套衣服给金钏装裹。",
      "Remorse", "After Jinchuan’s death Lady Wang weeps to Baochai that it is her fault; Baochai gives two of her own dresses for the burial.")),
  E("wangfuren", "xiren",
    P(34, "mas", "进言", "宝玉挨打后，袭人劝王夫人设法叫宝玉搬出园子，王夫人感动得叫她“我的儿”。",
      "Advice", "After the beating Xiren urges Lady Wang to move Baoyu out of the garden; Lady Wang is moved to call her “my child”."),
    P(36, "mas", "月例", "王夫人从自己的月钱里每月给袭人二两银子一吊钱。",
      "An allowance", "Lady Wang pays Xiren a monthly allowance from her own purse.")),
  E("wangfuren", "qingwen",
    P(74, "foe", "病西施", "王夫人听了王善保家的话，叫来晴雯，骂她“好个美人！真象个病西施了”。",
      "“A sickly Xi Shi”", "Prompted by Wang Shanbao’s wife, Lady Wang summons Qingwen and sneers at her looks."),
    P(77, "foe", "撵逐", "王夫人亲自到怡红院，叫人把病中的晴雯从炕上拉下来撵了出去。",
      "Thrown out", "Lady Wang comes to Red Delight in person and has the sick Qingwen dragged out of bed and sent away.")),
  E("wangfuren", "fangguan",
    P(77, "foe", "狐狸精", "王夫人说“唱戏的女孩子，自然是狐狸精了”，把芳官撵出去交给干娘。",
      "Vixens", "“Actresses are all vixens,” says Lady Wang, and dismisses Fangguan.")),
  E("wangfuren", "yuchuan",
    P(36, "mas", "双份月钱", "金钏死后，王夫人把金钏的月钱加给了玉钏。",
      "Double wages", "After Jinchuan’s death Lady Wang adds her wages to her sister’s.")),
  E("wangfuren", "zhouruijia",
    P(6, "mas", "陪房", "周瑞家的是王夫人的陪房。",
      "Her woman", "Zhou Rui’s wife came with Lady Wang at her marriage.")),
  E("wangfuren", "caixia",
    P(25, "mas", "主仆", "彩霞是王夫人房里的丫鬟。",
      "Maid", "Caixia is one of Lady Wang’s maids."),
    P(72, "mas", "放出", "王夫人见彩霞大了又多病，开恩放她出去自行择婿。",
      "Released", "Lady Wang lets Caixia, grown up and often ill, go home to be married.")),
  E("wangfuren", "zhaoyiniang",
    P(25, "tie", "妻妾", "贾环烫伤宝玉，王夫人把赵姨娘叫来骂了一顿。",
      "Wife and concubine", "When Jia Huan scalds Baoyu, Lady Wang summons his mother and berates her.")),
  E("wangfuren", "baochai",
    P(4, "kin", "姨甥", "宝钗是王夫人的外甥女，随母亲住进荣府梨香院。",
      "Aunt and niece", "Baochai is Lady Wang’s niece and comes to live in the Rong mansion."),
    P(97, "kin", "婆媳", "宝钗嫁给宝玉，成了王夫人的儿媳。",
      "Daughter-in-law", "Baochai marries Baoyu and becomes Lady Wang’s daughter-in-law.")),
  E("wangfuren", "wangshanbao",
    P(74, "tie", "进谗", "王善保家的趁机告晴雯的状，撺掇王夫人抄检大观园。",
      "Spite", "Wang Shanbao’s wife slanders Qingwen and urges Lady Wang to search the garden.")),
  E("wangfuren", "xueyima",
    P(4, "kin", "姊妹", "薛姨妈和王夫人是一母所生的姊妹。",
      "Sisters", "Aunt Xue is Lady Wang’s full sister.")),
  E("wangfuren", "wangziteng",
    P(4, "kin", "兄妹", "王子腾是王夫人的哥哥。",
      "Brother and sister", "Wang Ziteng is Lady Wang’s brother.")),
  E("wangfuren", "xifeng",
    P(3, "kin", "姑侄", "凤姐是王夫人的内侄女，替她管家。",
      "Aunt and niece", "Xifeng is Lady Wang’s niece and runs her household."),
    P(74, "tie", "绣春囊", "王夫人拿着绣春囊来质问凤姐，凤姐跪下含泪辩白。",
      "The pouch", "Lady Wang confronts Xifeng with the embroidered pouch; Xifeng kneels in tears to clear herself."),
    P(96, "kin", "调包计", "凤姐献调包计，王夫人和贾母都赞成。",
      "The switch", "Xifeng proposes the switch, and Lady Wang and Grandmother Jia agree.")),
  E("wangfuren", "yuanchun",
    P(3, "kin", "母女", "元春是贾政与王夫人的长女。",
      "Mother and daughter", "Yuanchun is Lady Wang’s eldest daughter.")),

  # =============================================================== Jia Lian and Xifeng
  E("jialian", "xifeng",
    P(3, "kin", "夫妻", "凤姐是贾琏的妻子。",
      "Husband and wife", "Xifeng is Jia Lian’s wife."),
    P(44, "tie", "变生不测", "凤姐生日撞破贾琏和鲍二家的私情，贾琏拔剑要杀凤姐。",
      "The jealous rage", "Xifeng catches Jia Lian with Bao Er’s wife on her birthday, and he draws a sword on her."),
    P(65, "tie", "偷娶", "贾琏背着凤姐偷娶了尤二姐。",
      "A secret marriage", "Jia Lian secretly takes You Erjie as a second wife.", (64, 65)),
    P(106, "tie", "放债事发", "抄家查出凤姐放债的借券，贾琏说自己并不知情，从此冷淡了她。",
      "The moneylending", "The search turns up Xifeng’s moneylending papers; Jia Lian, who says he knew nothing, turns cold to her.", (105, 106))),
  E("jialian", "pinger",
    P(6, "kin", "通房", "平儿是凤姐的陪嫁丫头，也是贾琏的屋里人。",
      "Concubine", "Ping’er, Xifeng’s maid, is also Jia Lian’s concubine."),
    P(21, "aid", "软语救贾琏", "平儿在贾琏的铺盖里抖出一绺女人的头发，替他瞒过了凤姐。",
      "Covering for him", "Ping’er finds another woman’s hair in Jia Lian’s bedding and hides it from Xifeng."),
    P(119, "kin", "将要扶正", "巧姐得救，贾琏越发敬重平儿，打算把她扶为正室。",
      "To be his wife", "After Qiaojie is saved Jia Lian resolves to make Ping’er his wife.")),
  E("jialian", "youerjie",
    P(64, "love", "九龙佩", "贾琏看上尤二姐，趁着讨槟榔，把一个汉玉九龙佩解下来留给了她。",
      "The jade pendant", "Taken with You Erjie, Jia Lian leaves her his nine-dragon jade pendant."),
    P(65, "kin", "偷娶", "贾琏在小花枝巷偷娶尤二姐做二房。",
      "Secret wife", "He marries her secretly and sets her up in Flower Lane."),
    P(69, "tie", "冷落", "有了秋桐，贾琏冷落了二姐；她死后，他抱尸大哭。",
      "Neglect", "With Qiutong in his bed he neglects Erjie; when she dies he weeps over her body.")),
  E("jialian", "qiutong",
    P(69, "kin", "烈火干柴", "秋桐和贾琏本有旧，如今得了，“一对烈火干柴”。",
      "Tinder and flame", "Qiutong and Jia Lian had long eyed each other; now they are inseparable.")),
  E("jialian", "baoer",
    P(44, "love", "私通", "凤姐生日，贾琏趁空把鲍二家的叫进房里私会。",
      "An affair", "On Xifeng’s birthday Jia Lian brings Bao Er’s wife to his room.")),
  E("jialian", "daiyu",
    P(12, "aid", "护送", "林如海病重，贾琏护送黛玉回扬州，又送她回京。",
      "Escort", "Jia Lian escorts Daiyu home to her dying father and back again.", (12, 16))),
  E("xifeng", "pinger",
    P(6, "mas", "心腹", "平儿是凤姐的陪嫁丫头和心腹。",
      "Right hand", "Ping’er is Xifeng’s maid and confidante."),
    P(44, "tie", "迁怒", "凤姐醋性大发，迁怒平儿，打了她；事后又向她赔不是。",
      "Struck", "In her jealous fury Xifeng hits Ping’er, and later apologizes."),
    P(106, "mas", "托孤", "抄家后凤姐病重，求平儿在她死后扶养巧姐。",
      "Her child", "Gravely ill after the raid, Xifeng begs Ping’er to raise Qiaojie when she is gone.")),
  E("xifeng", "jiarui",
    P(11, "foe", "起淫心", "贾瑞在宁府花园里拦住凤姐，言语轻薄。",
      "Unwanted advances", "Jia Rui accosts Xifeng in the Ning garden."),
    P(12, "foe", "毒设相思局", "凤姐两次假意约他：一次在穿堂冻了一夜，一次被贾蓉、贾蔷捉住，泼了一身屎尿。",
      "The trap", "Twice she pretends to meet him: once he freezes all night in a passage, then Jia Rong and Jia Qiang catch him and pour filth over him.")),
  E("xifeng", "qinkeqing",
    P(11, "aid", "探病", "凤姐与秦氏素来亲厚，常去看望病中的她。",
      "Visiting the sick", "Close friends, Xifeng visits her in her illness."),
    P(13, "aid", "托梦", "秦氏死前托梦给凤姐，嘱咐她在祖茔附近多置田庄，以备将来家道败落时的退路。",
      "A warning in a dream", "Dying, Qin Keqing appears in Xifeng’s dream and warns her to buy land by the family graves against the day of ruin.")),
  E("xifeng", "liulaolao",
    P(6, "aid", "二十两银子", "刘姥姥一进荣国府，凤姐给了她二十两银子。",
      "Twenty taels", "On her first visit Granny Liu is given twenty taels by Xifeng."),
    P(42, "aid", "取名", "凤姐请刘姥姥给女儿起名。",
      "A name", "Xifeng asks Granny Liu to name her daughter."),
    P(113, "aid", "托村妪", "凤姐病中把巧姐托付给刘姥姥。",
      "Her daughter", "Dying, Xifeng asks Granny Liu to look after Qiaojie.")),
  E("xifeng", "youerjie",
    P(68, "foe", "赚入大观园", "凤姐素服登门，装作贤惠，把尤二姐接进了大观园。",
      "Lured in", "Dressed in white, all kindness, Xifeng calls on You Erjie and brings her into the garden."),
    P(69, "foe", "借剑杀人", "凤姐借秋桐之手日日折磨尤二姐，二姐终于吞金自尽。",
      "A borrowed sword", "Through Qiutong, Xifeng torments Erjie day after day until she swallows gold.")),
  E("xifeng", "zhanghua",
    P(68, "tie", "唆讼", "凤姐叫旺儿找来张华，给他银子，叫他去告贾琏。",
      "A lawsuit", "Xifeng has Zhang Hua found and paid to sue Jia Lian."),
    P(69, "foe", "斩草除根", "凤姐又想除掉张华，旺儿只骗她说张华已被劫杀。",
      "Loose ends", "Then she wants Zhang Hua dead; her servant lies that robbers have killed him.")),
  E("xifeng", "youshi",
    P(13, "aid", "协理宁国府", "尤氏病倒，凤姐替她料理秦氏的丧事。",
      "Running the funeral", "With Madam You ill, Xifeng takes charge of Qin Keqing’s funeral.", (13, 14)),
    P(68, "foe", "大闹宁国府", "凤姐闯进宁府，滚到尤氏怀里哭骂，啐了她一脸。",
      "The scene", "Xifeng storms into the Ning mansion, weeping and railing in Madam You’s arms and spitting in her face.")),
  E("xifeng", "jiarong",
    P(6, "tie", "借炕屏", "贾蓉来向凤姐借玻璃炕屏，凤姐笑骂着借了，又叫他回来，半日却只说“罢了，你且去罢”。",
      "The glass screen", "Jia Rong comes to borrow a glass screen; Xifeng teases him, calls him back, then says nothing."),
    P(68, "foe", "跪地赔罪", "凤姐大闹宁国府，贾蓉跪在地下自己打嘴巴赔罪。",
      "Begging pardon", "When Xifeng storms the Ning mansion, Jia Rong kneels and slaps his own face.")),
  E("xifeng", "xiaohong",
    P(27, "mas", "收为丫鬟", "小红替凤姐传话，一大串话说得清清楚楚，凤姐当场把她要了去。",
      "Recruited", "Xiaohong delivers Xifeng’s message so clearly that Xifeng takes her on at once.")),
  E("xifeng", "qiaojie",
    P(7, "kin", "母女", "巧姐是贾琏和凤姐的女儿。",
      "Mother and daughter", "Qiaojie is their daughter."),
    P(84, "kin", "惊风", "巧姐病了，贾环来探病碰翻了药铞子，凤姐大骂。",
      "The medicine", "When Jia Huan upsets the sick Qiaojie’s medicine, Xifeng is furious.")),
  E("xifeng", "zhaoyiniang",
    P(25, "foe", "魇魔法", "赵姨娘请马道婆魇镇凤姐和宝玉。",
      "Black magic", "Concubine Zhao has Mother Ma bewitch Xifeng and Baoyu.")),
  E("xifeng", "wangziteng",
    P(4, "kin", "叔侄", "凤姐是王子腾的侄女。",
      "Uncle and niece", "Xifeng is Wang Ziteng’s niece.")),
  E("xifeng", "baoer",
    P(44, "foe", "撞破", "凤姐撞破私情，打了鲍二家的，鲍二家的随即上吊死了。",
      "Caught", "Xifeng beats Bao Er’s wife, who then hangs herself.")),
  E("xifeng", "daiyu",
    P(25, "aid", "吃茶", "凤姐打趣黛玉：“你既吃了我们家的茶，怎么还不给我们家作媳妇？”",
      "A joke", "Xifeng teases Daiyu: you’ve drunk our family’s tea — when will you marry into it?"),
    P(96, "foe", "设奇谋", "凤姐献计：瞒着宝玉，说娶的是林姑娘，实则娶宝钗。",
      "The switch", "Xifeng’s plan: Baoyu will be told he is marrying Daiyu, but the bride will be Baochai.")),
  E("xifeng", "baoyu",
    P(25, "kin", "叔嫂同难", "凤姐与宝玉一同中了魇魔法，同在贾母房里昏睡。",
      "Bewitched together", "Xifeng and Baoyu are bewitched together and lie senseless in Grandmother Jia’s rooms.")),
  E("xifeng", "qiutong",
    P(69, "tie", "借刀", "凤姐虽恨秋桐，却借她来对付尤二姐。",
      "A borrowed sword", "Xifeng hates Qiutong but uses her against You Erjie.")),
  E("xifeng", "jiayun",
    P(24, "aid", "种树的差事", "贾芸送来冰片麝香，凤姐便把大观园种树的差事给了他。",
      "A job", "Jia Yun’s gift of borneol and musk wins him the job of planting trees in the garden.")),
]
