# -*- coding: utf-8 -*-
"""Dream of the Red Chamber relationships, part 2: the young ladies, the Ning mansion, the related families,
the servants and the world outside."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import P, E  # noqa: E402

EDGES_B = [
  # =============================================================== Li Wan and the young ladies
  E("liwan", "jialan",
    P(4, "kin", "守寡教子", "贾兰是李纨的独子，李纨守寡，惟知侍亲养子。",
      "Mother and son", "Jia Lan is the only son of the widowed Li Wan, who lives to raise him."),
    P(119, "kin", "中举", "贾兰中了举人。",
      "Success", "Jia Lan passes the provincial examination.")),
  E("liwan", "tanchun",
    P(55, "aid", "共理家务", "凤姐病了，王夫人叫李纨和探春一同理家。",
      "Running the house", "With Xifeng ill, Li Wan and Tanchun run the household together.")),
  E("liwan", "daiyu",
    P(98, "aid", "送终", "宝玉成婚那天，李纨守在潇湘馆，看着黛玉咽气。",
      "At her deathbed", "On Baoyu’s wedding day Li Wan stays with the dying Daiyu.", (97, 98))),
  E("liwan", "baoyu",
    P(37, "aid", "诗社掌坛", "海棠社成立，李纨自荐掌坛，号“稻香老农”，宝玉当了“怡红公子”。",
      "Club president", "Li Wan takes the chair of the new poetry club as “the Old Farmer”; Baoyu becomes “the Lord of Red Delight”.")),
  E("yuanchun", "baochai",
    P(28, "tie", "端午节礼", "端午节礼，元妃给宝钗的独与给宝玉的一样，宝玉疑心传错了，宝钗心里越发没意思。",
      "The festival gifts", "The Consort sends Baochai the same gifts as Baoyu; he thinks it a mistake, and Baochai is all the more embarrassed.")),
  E("yuanchun", "lingguan",
    P(18, "aid", "额外赏赐", "元妃看了龄官的戏，额外赏了她。",
      "Rewarded", "The Consort rewards Lingguan for her singing.")),
  E("yingchun", "sunshaozu",
    P(79, "kin", "误嫁", "迎春被许给孙绍祖。",
      "The marriage", "Yingchun is married to Sun Shaozu."),
    P(80, "foe", "中山狼", "迎春回门，哭诉孙绍祖好色好赌，还指着她的脸说贾赦使了他五千银子，把她“准折买给我的”。",
      "The wolf", "Home on a visit, Yingchun weeps that her husband is a lecher and gambler who says she was sold to him for a debt."),
    P(109, "foe", "折磨致死", "迎春出嫁一年多，被孙家揉搓致死。",
      "Death", "Worn down by her husband’s abuse, Yingchun dies little more than a year after the wedding.")),
  E("yingchun", "siqi",
    P(7, "mas", "主仆", "司棋是迎春的大丫鬟。",
      "Mistress and maid", "Siqi is Yingchun’s senior maid."),
    P(77, "tie", "不能相保", "司棋被撵，哭求迎春说情，迎春虽然舍不得，却没有留下她。",
      "No help", "As Siqi is led away she begs Yingchun to plead for her; Yingchun is sorry, but does not keep her.")),
  E("tanchun", "zhaoyiniang",
    P(27, "tie", "做鞋", "赵姨娘抱怨探春给宝玉做鞋，不给亲兄弟做；探春气得说“我只管认得老爷、太太两个人，别人我一概不管”。",
      "Shoes", "Concubine Zhao complains that Tanchun makes shoes for Baoyu rather than her own brother; Tanchun answers that she recognizes only her father and Lady Wang."),
    P(55, "tie", "辱亲女", "赵国基死了，探春按旧例只给二十两丧银，赵姨娘跑来哭闹，探春哭着顶了回去。",
      "The funeral money", "When her brother dies, Concubine Zhao makes a scene over the customary twenty taels; Tanchun, in tears, stands firm.")),
  E("tanchun", "jiahuan",
    P(20, "kin", "同母姐弟", "贾环是探春的同母弟弟。",
      "Brother", "Jia Huan is Tanchun’s full brother.")),
  E("tanchun", "wangshanbao",
    P(74, "foe", "一记耳光", "王善保家的仗势掀探春的衣襟，探春当场打了她一记耳光。",
      "A slap", "When Wang Shanbao’s wife makes a show of lifting her jacket, Tanchun slaps her face.")),
  E("tanchun", "baochai",
    P(56, "aid", "兴利除宿弊", "探春把园子分给婆子们承包，宝钗从旁提点，叫她们分些利给众人。",
      "Reforms", "Tanchun leases the garden plots to the servant women; Baochai advises sharing the profit.")),
  E("xichun", "ruhua",
    P(7, "mas", "主仆", "入画是惜春的丫鬟。",
      "Mistress and maid", "Ruhua is Xichun’s maid."),
    P(74, "foe", "撵走", "入画箱里搜出男人的东西，惜春坚决不要她，叫尤氏带走。",
      "Sent away", "Men’s things are found in Ruhua’s chest, and Xichun refuses to keep her.")),
  E("xichun", "youshi",
    P(74, "tie", "杜绝宁国府", "惜春对尤氏说：“不但不要入画，如今我也大了，连我也不便往你们那边去了。”",
      "Cutting ties", "Xichun tells Madam You she will have nothing more to do with the Ning mansion."),
    P(115, "tie", "矢素志", "惜春立意出家，以死相逼，尤氏拦不住。",
      "The vow", "Xichun is set on taking vows, and Madam You cannot stop her.", (115, 118))),
  E("xichun", "jiazhen",
    P(3, "kin", "兄妹", "惜春是贾珍的胞妹。",
      "Brother and sister", "Xichun is Jia Zhen’s sister.")),
  E("xichun", "jiajing",
    P(3, "kin", "父女", "惜春是贾敬的女儿。",
      "Father and daughter", "Xichun is Jia Jing’s daughter.")),
  E("xichun", "miaoyu",
    P(87, "aid", "下棋谈禅", "妙玉难得出庵，来和惜春下棋，又和惜春一起拿禅语打趣宝玉。",
      "Chess and Zen", "Miaoyu, who rarely leaves her hermitage, comes to play chess with Xichun, and the two tease Baoyu with Zen riddles."),
    P(112, "aid", "守夜", "妙玉陪惜春守夜，正遇上家中遭贼；次日夜里妙玉便被劫走，惜春出家的心更定了。",
      "The vigil", "Miaoyu keeps Xichun company through the night of the robbery; the next night she is carried off, and Xichun’s resolve hardens.", (111, 112))),
  E("xichun", "zijuan",
    P(118, "mas", "随侍修行", "惜春出家，紫鹃自愿跟去伺候。",
      "Following her", "When Xichun takes vows, Zijuan asks to serve her.")),
  E("xichun", "zhineng",
    P(7, "aid", "玩伴", "惜春和智能儿一处玩，说“我明儿也要剃了头同他作姑子去”。",
      "Playmates", "Playing with the little nun, Xichun says she will shave her head and become a nun too.")),

  # =============================================================== the Ning mansion
  E("jiajing", "jiazhen",
    P(2, "kin", "父子", "贾敬一心修道，把官让儿子贾珍袭了。",
      "Father and son", "Jia Jing, devoted to his elixirs, has handed his rank to his son."),
    P(63, "kin", "奔丧", "贾敬服丹死去，贾珍从外头赶回奔丧。",
      "The funeral", "Jia Jing dies of his elixir, and Jia Zhen hurries home for the funeral.", (63, 64))),
  E("jiazhen", "youshi",
    P(5, "kin", "夫妻", "尤氏是贾珍的妻子。",
      "Husband and wife", "Madam You is Jia Zhen’s wife.")),
  E("jiazhen", "jiarong",
    P(2, "kin", "父子", "贾蓉是贾珍的儿子。",
      "Father and son", "Jia Rong is Jia Zhen’s son.")),
  E("jiazhen", "qinkeqing",
    P(13, "tie", "尽我所有", "秦氏死后，贾珍哭得泪人一般，说办丧事“不过尽我所有罢了”，拄着拐杖操办丧事。",
      "“All I have”", "At her death Jia Zhen weeps uncontrollably and spends without limit on her funeral, hobbling about on a stick.")),
  E("jiazhen", "youerjie",
    P(64, "tie", "作主改嫁", "贾珍作主，逼张华退了亲，把尤二姐许给贾琏。",
      "Giving her away", "Jia Zhen breaks Erjie’s old betrothal and gives her to Jia Lian.")),
  E("jiazhen", "yousanjie",
    P(65, "tie", "反被戏骂", "贾珍、贾琏想轻薄尤三姐，反被她借酒戏骂了一场。",
      "Turned tables", "When Jia Zhen and Jia Lian try to take liberties, Sanjie, drinking, mocks and berates them.")),
  E("jiazhen", "jiaoda",
    P(7, "mas", "老仆", "焦大跟着太爷出过兵，如今在宁府里谁也不敢惹他。",
      "An old servant", "Jiao Da went to war with the founder, and no one in the Ning mansion dares cross him.")),
  E("jiaoda", "jiarong",
    P(7, "foe", "醉骂", "焦大借着酒骂到贾蓉头上，被捆起来塞了满嘴马粪。",
      "Drunken abuse", "Drunk, Jiao Da abuses even Jia Rong, and is tied up and gagged with horse dung.")),
  E("jiazhen", "jiaqiang",
    P(9, "kin", "抚养", "贾蔷父母早亡，从小跟着贾珍过活。",
      "Raised by him", "Orphaned, Jia Qiang has grown up in Jia Zhen’s house.")),
  E("jiarong", "qinkeqing",
    P(5, "kin", "夫妻", "秦可卿是贾蓉的妻子。",
      "Husband and wife", "Qin Keqing is Jia Rong’s wife.")),
  E("jiarong", "jiarui",
    P(12, "foe", "捉贾瑞", "贾蓉、贾蔷替凤姐捉住贾瑞，逼他写了欠契，又泼了他一身屎尿。",
      "The trap sprung", "Jia Rong and Jia Qiang catch Jia Rui for Xifeng, force an IOU from him and drench him in filth.")),
  E("jiaqiang", "jiarui",
    P(12, "foe", "设局", "贾蔷和贾蓉一起设局捉弄贾瑞。",
      "The trap", "Jia Qiang joins Jia Rong in the trap.")),
  E("jiarong", "jiaqiang",
    P(9, "aid", "最相亲厚", "贾蔷和贾蓉最相亲厚，常相共处。",
      "Inseparable", "Jia Qiang and Jia Rong are the closest of friends.")),
  E("jiarong", "youerjie",
    P(64, "tie", "撺掇", "贾蓉撺掇贾琏偷娶尤二姐，自己也存着私心。",
      "Matchmaker", "Jia Rong eggs Jia Lian on to take Erjie, with designs of his own.")),
  E("jiaqiang", "lingguan",
    P(30, "love", "划蔷", "龄官在蔷薇架下一遍遍地划“蔷”字。",
      "A name in the earth", "Lingguan scratches “Qiang” in the earth again and again."),
    P(36, "love", "放雀", "贾蔷买了只会衔旗串戏台的雀儿哄龄官，龄官说这是拿雀儿比她们，贾蔷当即把雀儿放了。",
      "The bird set free", "Jia Qiang buys Lingguan a performing bird; when she says it is caged like the girls, he sets it free.")),
  E("qinkeqing", "qinzhong",
    P(7, "kin", "姐弟", "秦钟是秦可卿的弟弟。",
      "Sister and brother", "Qin Zhong is her younger brother.")),
  E("qinkeqing", "jinghuan",
    P(5, "aid", "兼美", "梦中警幻的妹妹乳名兼美，字可卿，“鲜艳妩媚，有似乎宝钗，风流袅娜，则又如黛玉”。",
      "Her namesake", "In the dream Disenchantment’s sister, also called Keqing, has Baochai’s beauty and Daiyu’s grace.")),
  E("qinkeqing", "yuanyang",
    P(111, "tie", "引路", "鸳鸯要殉主时，看见秦可卿的魂拿着汗巾比着上吊，像是教她死法；魂出窍后，又见秦氏在前引路。",
      "Showing the way", "As Yuanyang prepares to die, Qin Keqing’s ghost appears with a sash as if to show her how, then leads her spirit away.")),
  E("youshi", "youerjie",
    P(63, "kin", "姊妹", "尤二姐是尤氏的继妹，贾敬丧中随母亲来宁府照应。",
      "Stepsisters", "Erjie, Madam You’s stepsister, comes to help during the funeral.")),
  E("youshi", "yousanjie",
    P(63, "kin", "姊妹", "尤三姐是尤氏的继妹。",
      "Stepsisters", "Sanjie is Madam You’s stepsister.")),
  E("youerjie", "yousanjie",
    P(63, "kin", "姊妹", "二姐温柔，三姐刚烈。",
      "Sisters", "Erjie is gentle, Sanjie fierce."),
    P(69, "kin", "托梦", "尤三姐托梦给姐姐，劝她拿剑斩了凤姐，同归警幻案下。",
      "A dream", "Sanjie appears to her sister in a dream, urging her to kill Xifeng with the sword and come with her to the Land of Illusion.")),
  E("yousanjie", "liuxianglian",
    P(65, "love", "思嫁柳二郎", "尤三姐要自己拣人，原来五年前就看中了柳湘莲，非他不嫁。",
      "Her choice", "Sanjie insists on choosing for herself: she has loved Liu Xianglian for five years and will marry no one else.", (65, 66)),
    P(66, "love", "鸳鸯剑", "柳湘莲以祖传鸳鸯剑为定礼，又疑心她不干净，来要回定礼；三姐用剑自刎，湘莲抚尸痛哭，随道士出家。",
      "The sword", "Liu gives his family’s twin swords as a pledge, then, suspicious, asks for them back; Sanjie cuts her throat with the sword, and Liu, weeping over her, leaves the world.")),
  E("youerjie", "zhanghua",
    P(64, "tie", "指腹为婚", "张华与尤二姐指腹为婚，后被逼写了退婚书。",
      "Betrothed", "Zhang Hua was betrothed to Erjie before birth, but is forced to give her up."),
    P(68, "tie", "告状", "张华受凤姐唆使，告贾琏强逼退亲、停妻再娶。",
      "The lawsuit", "Prompted by Xifeng, Zhang Hua sues Jia Lian.")),
  E("youerjie", "qiutong",
    P(69, "foe", "辱骂", "秋桐天天指桑骂槐，辱骂尤二姐。",
      "Abuse", "Qiutong abuses Erjie every day.")),
  E("youerjie", "pinger",
    P(69, "aid", "暗中照顾", "尤二姐受气，只有平儿暗中拿钱弄菜给她吃。",
      "Secret kindness", "Only Ping’er quietly brings Erjie food.")),

  # =============================================================== the Lins and the Shis
  E("linruhai", "daiyu",
    P(2, "kin", "父女", "黛玉是林如海和贾敏的独女，五岁时由贾雨村教她读书。",
      "Father and daughter", "Daiyu is the only child of Lin Ruhai and Jia Min; at five she is taught by Jia Yucun."),
    P(14, "kin", "捐馆扬州", "林如海病故扬州，黛玉回去侍疾送终。",
      "His death", "Lin Ruhai dies in Yangzhou, with Daiyu at his side.", (12, 14))),
  E("linruhai", "yucun",
    P(2, "aid", "西宾", "林如海请贾雨村教黛玉读书，又写荐书送他去见贾政。",
      "Tutor", "Lin Ruhai hires Jia Yucun to teach Daiyu, then recommends him to Jia Zheng.", (2, 3))),
  E("linruhai", "jiamu",
    P(3, "kin", "岳母女婿", "林如海娶的是贾母的女儿贾敏。",
      "Son-in-law", "Lin Ruhai married Grandmother Jia’s daughter Jia Min.")),
  E("daiyu", "yucun",
    P(3, "aid", "师生", "贾雨村是黛玉的启蒙老师，随她一同进京。",
      "Teacher and pupil", "Jia Yucun, her first teacher, travels with her to the capital.", (2, 3))),
  E("daiyu", "zijuan",
    P(3, "mas", "鹦哥", "贾母把身边的二等丫头鹦哥给了黛玉，就是后来的紫鹃。",
      "A gift", "Grandmother Jia gives Daiyu her maid Parrot, later called Zijuan."),
    P(57, "aid", "知心", "紫鹃劝黛玉趁老太太还硬朗，早定终身大事。",
      "A true friend", "Zijuan urges Daiyu to settle her future while Grandmother Jia is still strong."),
    P(97, "aid", "最知心", "黛玉临终对紫鹃说：“妹妹，你是我最知心的……我拿你就当我的亲妹妹。”",
      "Like a sister", "Dying, Daiyu tells Zijuan she has been like her own sister.")),
  E("daiyu", "xueyan",
    P(3, "mas", "从小跟随", "雪雁是黛玉从扬州带来的小丫头。",
      "From home", "Xueyan came with Daiyu from Yangzhou."),
    P(97, "tie", "借去扶新娘", "凤姐把雪雁借去扶新娘，好叫宝玉相信娶的是黛玉。",
      "Borrowed", "Xifeng borrows Xueyan to attend the bride so Baoyu will believe he is marrying Daiyu.")),
  E("daiyu", "xiangling",
    P(48, "aid", "教诗", "香菱拜黛玉为师学诗，黛玉教她先读王维、杜甫、李白。",
      "Poetry lessons", "Xiangling asks Daiyu to teach her poetry; Daiyu starts her on Wang Wei, Du Fu and Li Bai.")),
  E("daiyu", "miaoyu",
    P(41, "tie", "大俗人", "黛玉问吃茶的水是不是旧年的雨水，妙玉冷笑说“你这么个人，竟是大俗人，连水也尝不出来”。",
      "“A vulgarian”", "When Daiyu asks if the tea is made with last year’s rainwater, Miaoyu scoffs that she cannot even taste water."),
    P(76, "aid", "续联诗", "黛玉和湘云中秋联诗，妙玉出来止住，邀到栊翠庵，续完了全诗。",
      "Finishing the poem", "Miaoyu interrupts Daiyu and Xiangyun’s linked verse at a mournful line, takes them to her hermitage and finishes the poem herself.")),
  E("daiyu", "xiangyun",
    P(22, "tie", "戏子", "湘云说小旦的扮相像林妹妹，黛玉恼了，连宝玉也一起恼。",
      "The actress", "Xiangyun says an actress looks like Daiyu, and Daiyu takes offence."),
    P(76, "aid", "凹晶馆联诗", "中秋夜两人在凹晶馆联诗，联出“寒塘渡鹤影，冷月葬花魂”。",
      "Linked verse", "On the mid-autumn night the two compose linked verse by the pond, ending on a crane’s shadow and a buried flower-soul.")),
  E("daiyu", "qingwen",
    P(26, "tie", "闭门", "黛玉夜里去怡红院，晴雯正在使性子，没听出是她，不肯开门，黛玉在花荫下独自悲泣。",
      "The closed gate", "Qingwen, in a temper, refuses to open the gate to a voice she doesn’t recognize; Daiyu weeps alone among the flowers.", (26, 27)),
    P(34, "aid", "送帕", "晴雯奉宝玉之命，给黛玉送去两块旧手帕。",
      "The handkerchiefs", "Qingwen carries Baoyu’s handkerchiefs to Daiyu.")),
  E("daiyu", "shadajie",
    P(96, "tie", "泄机关", "黛玉在园中听见傻大姐哭，才知道宝玉要娶宝钗，顿时迷了本性。",
      "The slip", "From Simple Sister’s tears Daiyu learns that Baoyu is to marry Baochai, and loses her senses.")),
  E("daiyu", "xueyima",
    P(57, "aid", "爱语慰痴颦", "薛姨妈抚慰黛玉，又说要把她许给宝玉。",
      "Comfort", "Aunt Xue comforts Daiyu and says she should marry Baoyu.")),
  E("daiyu", "zhouruijia",
    P(7, "tie", "送宫花", "周瑞家的最后才把宫花送到黛玉处，黛玉冷笑：“我就知道，别人不挑剩下的也不给我。”",
      "Last pick", "Given the last of the palace flowers, Daiyu says she knew she would get what the others left.")),
  E("daiyu", "xiren",
    P(82, "tie", "东风西风", "袭人来探黛玉的口气，说起妻妾之争，黛玉说“但凡家庭之事，不是东风压了西风，就是西风压了东风”。",
      "East wind, west wind", "Xiren sounds Daiyu out about wives and concubines; Daiyu remarks that in any household either the east wind prevails or the west.")),
  E("xiangyun", "cuilv",
    P(21, "mas", "主仆", "翠缕是湘云的丫鬟。",
      "Mistress and maid", "Cuilü is Xiangyun’s maid."),
    P(31, "mas", "论阴阳", "翠缕缠着湘云讲阴阳，随后在蔷薇架下拾到宝玉丢的金麒麟。",
      "Yin and yang", "Cuilü quizzes Xiangyun about yin and yang, then finds the gold unicorn Baoyu dropped.")),
  E("xiangyun", "baochai",
    P(32, "aid", "体恤", "宝钗告诉袭人，湘云在家里一点儿作不得主，做针线常到三更半夜。",
      "Understanding", "Baochai tells Xiren that Xiangyun has no say at home and sews till midnight."),
    P(37, "aid", "螃蟹宴", "湘云要做东起社，宝钗替她出主意，从自家铺子里拿螃蟹办了一场螃蟹宴。",
      "The crab feast", "Xiangyun wants to host the poetry club; Baochai helps her give a crab feast.", (37, 38))),
  E("xiangyun", "xiangling",
    P(49, "aid", "论诗", "香菱缠着湘云谈诗，湘云高谈阔论，宝钗笑她们“呆香菱之心苦，疯湘云之话多”。",
      "Talking poetry", "Xiangling and Xiangyun talk poetry endlessly, and Baochai laughs at dotty Xiangling and chattering Xiangyun.")),

  # =============================================================== the Wangs and the Xues
  E("wangziteng", "xueyima",
    P(4, "kin", "兄妹", "薛姨妈是王子腾的妹妹。",
      "Brother and sister", "Aunt Xue is Wang Ziteng’s sister.")),
  E("wangziteng", "xuepan",
    P(4, "kin", "舅甥", "薛蟠打死了人，舅舅王子腾得了信，叫他们进京。",
      "Uncle and nephew", "When Xue Pan kills a man, his uncle calls the family to the capital.", (3, 4))),
  E("wangziteng", "yucun",
    P(16, "aid", "保荐", "贾雨村补了京缺，都是王子腾累上保本。",
      "Patron", "Wang Ziteng’s recommendations win Jia Yucun a post in the capital.")),
  E("xueyima", "xuepan",
    P(4, "kin", "母子", "薛蟠是薛姨妈的独子，母亲管不住他。",
      "Mother and son", "Xue Pan is Aunt Xue’s only son, far beyond her control.")),
  E("xueyima", "baochai",
    P(4, "kin", "母女", "宝钗是薛姨妈的女儿，母亲事事倚靠她。",
      "Mother and daughter", "Aunt Xue relies on her daughter in everything.")),
  E("baochai", "xuepan",
    P(4, "kin", "兄妹", "宝钗是薛蟠的妹妹。",
      "Brother and sister", "Baochai is Xue Pan’s sister."),
    P(34, "tie", "金要拣有玉的", "薛蟠赌气说宝钗：“从先妈和我说，你这金要拣有玉的才可正配”，宝钗委屈得哭了一夜。",
      "Hurtful words", "In a temper Xue Pan taunts her that her gold locket must be matched with a jade; Baochai cries all night.")),
  E("baochai", "yinger",
    P(7, "mas", "主仆", "莺儿是宝钗的丫鬟。",
      "Mistress and maid", "Ying’er is Baochai’s maid."),
    P(35, "mas", "打络子", "宝钗叫莺儿用金线配黑珠线打个络子，把通灵玉络上。",
      "A net for the jade", "Baochai has Ying’er knot a net of gold and black thread for Baoyu’s jade.")),
  E("baochai", "xiren",
    P(21, "aid", "赏识", "宝钗到怡红院和袭人闲谈，觉得她“倒有些识见”。",
      "Respect", "Talking with Xiren, Baochai finds her sensible."),
    P(36, "aid", "代绣兜肚", "宝钗替袭人坐在宝玉床边绣鸳鸯兜肚。",
      "Embroidering", "Baochai takes Xiren’s place by Baoyu’s bed, embroidering.")),
  E("baochai", "xiangling",
    P(48, "aid", "入园同住", "薛蟠出门，宝钗把香菱带进园子同住。",
      "Into the garden", "With Xue Pan away, Baochai brings Xiangling to live with her in the garden."),
    P(80, "aid", "收留", "香菱被夏金桂和薛蟠折磨，宝钗把她带到自己房里。",
      "Taken in", "When Jingui and Xue Pan torment her, Baochai takes Xiangling into her own rooms.")),
  E("baochai", "xiaohong",
    P(27, "tie", "金蝉脱壳", "宝钗听见小红和坠儿的私话，假装在找黛玉。",
      "Overheard", "Baochai overhears Xiaohong’s secret and pretends to be looking for Daiyu.")),
  E("baochai", "jinchuan",
    P(32, "aid", "送衣装裹", "宝钗拿自己的两套衣服给金钏装裹。",
      "Clothes for the dead", "Baochai gives two of her own dresses for Jinchuan’s burial.")),
  E("baochai", "baoqin",
    P(49, "kin", "堂姊妹", "宝琴是宝钗的堂妹。",
      "Cousins", "Baoqin is Baochai’s cousin.")),
  E("baochai", "xiajingui",
    P(83, "tie", "吞声", "夏金桂指桑骂槐，宝钗只好忍气吞声。",
      "Swallowing it", "Baochai bears Jingui’s insults in silence.")),
  E("baochai", "sengdao",
    P(7, "aid", "冷香丸与金锁", "宝钗吃的冷香丸，方子是一个和尚给的；金锁上的吉利话，也是那和尚给的。",
      "Pills and a locket", "A monk gave Baochai the recipe for her pills and the words engraved on her locket.", (7, 8))),
  E("xuepan", "xiangling",
    P(4, "tie", "抢买", "薛蟠为了抢买英莲，打死了冯渊。",
      "Bought", "Xue Pan seizes Yinglian after his men kill her other buyer."),
    P(16, "kin", "收房", "薛蟠摆酒请客，明堂正道地收香菱做了妾。",
      "Concubine", "Xue Pan formally takes Xiangling as a concubine."),
    P(80, "foe", "贪夫棒", "薛蟠听了夏金桂的挑唆，抓起门闩毒打香菱。",
      "The beating", "Egged on by his wife, Xue Pan beats Xiangling with a door bar."),
    P(120, "kin", "扶正", "薛蟠出狱后，把香菱扶为正室。",
      "Wife at last", "Released from prison, Xue Pan makes Xiangling his wife.")),
  E("xuepan", "fengyuan",
    P(4, "foe", "打死", "冯渊买了英莲，薛蟠来抢，喝令家奴把冯渊打死。",
      "Killed", "Feng Yuan has bought Yinglian; Xue Pan has him beaten to death.")),
  E("xuepan", "liuxianglian",
    P(47, "foe", "苦打", "薛蟠调戏柳湘莲，被他诱到苇塘边痛打。",
      "The beating", "Xue Pan makes a pass at Liu, who lures him out and thrashes him."),
    P(66, "aid", "结拜", "柳湘莲救了遇盗的薛蟠，二人结为生死弟兄。",
      "Sworn brothers", "Liu saves Xue Pan from robbers, and they become sworn brothers.")),
  E("xuepan", "xiajingui",
    P(79, "kin", "悔娶", "薛蟠娶了夏金桂，她立意要压倒丈夫。",
      "A bad match", "Xue Pan marries Xia Jingui, who means to rule him."),
    P(103, "foe", "自焚身", "金桂下毒要害香菱，反毒死了自己。",
      "Poisoned", "Jingui poisons herself with the soup meant for Xiangling.")),
  E("xuepan", "yucun",
    P(4, "aid", "葫芦案", "贾雨村徇情枉法，放过了薛蟠。",
      "The Gourd Case", "Jia Yucun lets Xue Pan off for the killing.")),
  E("xueke", "baoqin",
    P(49, "kin", "兄妹", "薛蝌送妹妹宝琴进京出嫁。",
      "Brother and sister", "Xue Ke brings his sister to the capital for her wedding.")),
  E("xueke", "xiajingui",
    P(91, "foe", "勾引", "夏金桂看上薛蝌，叫宝蟾送酒送果，屡次勾引。",
      "Temptation", "Jingui sends wine and fruit to Xue Ke to seduce him.", (90, 91)),
    P(100, "foe", "拉扯", "金桂拉住薛蝌往屋里拽，被香菱撞见。",
      "Caught", "Jingui drags Xue Ke toward her room, and Xiangling sees it.")),
  E("xueke", "xuepan",
    P(49, "kin", "堂兄弟", "薛蝌是薛蟠的堂弟。",
      "Cousins", "Xue Ke is Xue Pan’s cousin."),
    P(85, "kin", "奔走", "薛蟠犯了人命，薛蝌四处打点。",
      "Bribes", "When Xue Pan kills again, Xue Ke runs about bribing officials.", (85, 86))),
  E("xiajingui", "xiangling",
    P(80, "foe", "改名秋菱", "夏金桂把香菱改名秋菱，挑唆薛蟠打她。",
      "Renamed", "Jingui renames Xiangling and turns Xue Pan against her."),
    P(103, "foe", "投毒", "金桂在汤里下毒要害香菱，宝蟾换了碗，金桂自己毒发身亡。",
      "Poison", "Jingui poisons Xiangling’s soup; the bowls are switched and she dies herself.")),

  # =============================================================== servants
  E("pinger", "qiaojie",
    P(119, "aid", "救巧姐", "平儿陪着巧姐躲到刘姥姥的乡下。",
      "Escape", "Ping’er goes with Qiaojie to hide in Granny Liu’s village.")),
  E("pinger", "yuanyang",
    P(46, "aid", "姊妹", "鸳鸯、平儿、袭人从小一处长大；鸳鸯抗婚时，平儿和袭人来劝她。",
      "Old friends", "Yuanyang, Ping’er and Xiren grew up together; the other two come to comfort her.")),
  E("xiren", "qingwen",
    P(31, "tie", "“我们”", "晴雯和宝玉拌嘴，袭人来劝，说了一句“我们”，晴雯冷笑着讥讽她。",
      "“We”", "When Qingwen quarrels with Baoyu, Xiren intervenes, and Qingwen mocks her for saying “we”.")),
  E("xiren", "jiangyuhan",
    P(28, "tie", "汗巾", "宝玉把袭人的松花汗巾送了琪官，又把琪官的大红汗巾系在袭人腰上。",
      "The sashes", "Baoyu gives Xiren’s green sash to the actor and ties the actor’s red one on her."),
    P(120, "kin", "姻缘前定", "袭人嫁给蒋玉菡，见了那条松花汗巾，才知姻缘前定。",
      "Fated", "Xiren marries Jiang Yuhan and recognizes the green sash.")),
  E("xiren", "limama",
    P(20, "foe", "倚老卖老", "李嬷嬷见袭人躺着不理她，骂袭人是“忘了本的小娼妇”，凤姐赶来才把她拉走。",
      "An old nurse’s abuse", "Finding Xiren lying ill, Nanny Li abuses her as an ungrateful hussy until Xifeng leads her away.")),
  E("qingwen", "wangshanbao",
    P(74, "foe", "告状", "王善保家的在王夫人面前告晴雯；抄检时晴雯把箱子倒了一地。",
      "Denounced", "Wang Shanbao’s wife denounces Qingwen; at the search Qingwen tips her whole trunk out in defiance.")),
  E("yuanyang", "siqi",
    P(71, "aid", "撞见", "鸳鸯夜里撞见司棋和潘又安在山石后私会，答应保密。",
      "Discovered", "Yuanyang stumbles on Siqi and her cousin together, and promises silence."),
    P(72, "aid", "立誓", "司棋病了，鸳鸯去看她，发誓不告诉一个人。",
      "A vow", "Siqi falls ill with fear; Yuanyang visits and swears to tell no one.")),
  E("siqi", "wangshanbao",
    P(74, "kin", "外孙女", "司棋是王善保家的外孙女，抄检时偏从她箱里搜出私情信物。",
      "Granddaughter", "Siqi is Wang Shanbao’s wife’s granddaughter; the search finds her love letters.")),
  E("zhouruijia", "liulaolao",
    P(6, "aid", "引见", "周瑞家的引刘姥姥见了凤姐。",
      "An introduction", "Zhou Rui’s wife takes Granny Liu to see Xifeng.")),
  E("zhouruijia", "xiangling",
    P(7, "tie", "品格儿", "周瑞家的见了香菱，说她“竟有些象咱们东府里蓉大奶奶的品格儿”。",
      "A likeness", "Zhou Rui’s wife notices that Xiangling looks a little like Qin Keqing.")),
  E("fangguan", "zhaoyiniang",
    P(60, "foe", "茉莉粉", "芳官拿茉莉粉当蔷薇硝给了贾环，赵姨娘跑来打她，被藕官、蕊官等围住撕打。",
      "The powder", "Fangguan gives Jia Huan jasmine powder for rose-nitre; Concubine Zhao comes to hit her and is mobbed by the young actresses.")),
  E("fangguan", "jiahuan",
    P(60, "tie", "蔷薇硝", "贾环向宝玉讨蔷薇硝，芳官不肯给，拿茉莉粉糊弄他。",
      "Rose-nitre", "Jia Huan begs Baoyu for some rose-nitre; Fangguan fobs him off with jasmine powder.")),
  E("caixia", "jiahuan",
    P(25, "love", "相好", "彩霞和贾环合得来，贾环抄经时只有她肯理他。",
      "Fond of him", "Caixia is fond of Jia Huan; she alone is kind to him."),
    P(72, "love", "难成", "彩霞被放出去，来旺家的要强娶她作儿媳，她托妹妹求赵姨娘，盼贾环来讨她。",
      "Thwarted", "Released and pressed to marry another, Caixia appeals to Concubine Zhao, hoping Jia Huan will ask for her.")),
  E("caixia", "zhaoyiniang",
    P(72, "aid", "契合", "赵姨娘素日和彩霞契合，巴不得把她给了贾环。",
      "An ally", "Concubine Zhao likes Caixia and wants her for Jia Huan.")),
  E("jiahuan", "yinger",
    P(20, "tie", "赖账", "贾环和莺儿掷骰子输了赖账，莺儿抱怨，宝玉把贾环打发走了。",
      "Cheating", "Jia Huan cheats Ying’er at dice, and Baoyu sends him away.")),
  E("jiahuan", "zhaoyiniang",
    P(20, "kin", "母子", "贾环是赵姨娘的儿子，赌钱回来又挨了她一顿骂。",
      "Mother and son", "Jia Huan is Concubine Zhao’s son; when he comes back from a lost game she scolds him.")),
  E("jiahuan", "qiaojie",
    P(84, "foe", "碰翻药铞", "贾环去看病中的巧姐，碰翻了药铞子。",
      "The medicine", "Visiting the sick Qiaojie, Jia Huan upsets her medicine pot."),
    P(118, "foe", "欺弱女", "贾环和王仁、贾芸合谋，要把巧姐卖给外藩。",
      "The plot", "Jia Huan plots with Wang Ren and Jia Yun to sell Qiaojie to a foreign prince.", (117, 119))),
  E("jiayun", "xiaohong",
    P(24, "love", "遗帕", "小红丢了手帕，梦见贾芸拾了来找她。",
      "The handkerchief", "Xiaohong loses her handkerchief and dreams that Jia Yun has found it.", (24, 25)),
    P(26, "love", "传心事", "贾芸留下小红的手帕，借坠儿把自己的一块给她，两人暗中有情。",
      "Messages", "Through a little maid the two exchange handkerchiefs and feelings.", (26, 27))),
  E("jiayun", "qiaojie",
    P(118, "foe", "卖巧姐", "贾芸参与谋卖巧姐。",
      "The plot", "Jia Yun joins the plot to sell Qiaojie.", (117, 119))),
  E("qiaojie", "liulaolao",
    P(42, "aid", "取名巧姐", "刘姥姥给大姐儿取名巧姐，说“必然是遇难成祥，逢凶化吉，却从这‘巧’字上来”。",
      "Named", "Granny Liu names the child: by this “luck”, she says, she will turn misfortune into good."),
    P(119, "aid", "救出", "刘姥姥把巧姐藏到乡下，又替她说了周家的亲事。",
      "Rescued", "Granny Liu hides Qiaojie in the country and finds her a husband.")),

  # =============================================================== the world outside
  E("beijingwang", "jiangyuhan",
    P(28, "aid", "赠汗巾", "蒋玉菡送给宝玉的大红汗巾，原是北静王给他的。",
      "The sash", "The red sash Jiang Yuhan gives Baoyu came from the Prince of Beijing.")),
  E("qinzhong", "zhineng",
    P(15, "love", "馒头庵", "秦钟在馒头庵与智能儿私会。",
      "The convent", "Qin Zhong and Zhineng meet secretly at the convent."),
    P(16, "love", "私逃", "智能儿私逃进城找秦钟，被秦业撞见撵出，秦业气死，秦钟病亡。",
      "Running away", "Zhineng runs away to find him; his father throws her out and dies of rage, and Qin Zhong soon follows.")),
  E("liuxianglian", "sengdao",
    P(66, "aid", "出家", "柳湘莲哭别尤三姐后，随破庙里一个道士飘然而去。",
      "Leaving the world", "After Sanjie’s death Liu follows a Taoist from a ruined temple away.")),
  E("shiyin", "sengdao",
    P(1, "aid", "好了歌", "甄士隐听跛足道人唱《好了歌》，作了一篇注解，随道人飘然而去。",
      "The Song of Good-and-Done", "Hearing the lame Taoist’s song, Zhen Shiyin writes a commentary on it and goes off with him.")),
  E("shiyin", "yucun",
    P(1, "aid", "资助", "甄士隐送贾雨村五十两银子和两套冬衣，资助他进京赶考。",
      "Patron", "Zhen Shiyin gives Jia Yucun fifty taels and winter clothes for the journey."),
    P(103, "tie", "空遇旧", "雨村在急流津遇见出家的甄士隐，认出几分，士隐却不肯相认。",
      "Unacknowledged", "Yucun meets the Taoist Shiyin at a ferry and half recognizes him, but Shiyin will not admit who he is."),
    P(120, "aid", "详说太虚情", "雨村与士隐再会，士隐把太虚幻境的事细细说给他听。",
      "The explanation", "Meeting again, Shiyin tells Yucun the whole story of the Land of Illusion.")),
  E("shiyin", "xiangling",
    P(1, "kin", "父女", "英莲是甄士隐的独女，元宵看灯时被拐走。",
      "Father and daughter", "Yinglian, his only daughter, is stolen at the Lantern Festival."),
    P(120, "kin", "度脱", "香菱死后，甄士隐度她回太虚幻境销号。",
      "Bringing her home", "After her death Shiyin leads her spirit back to the Land of Illusion.")),
  E("shiyin", "jiaoxing",
    P(1, "mas", "主仆", "娇杏是甄家的丫鬟。",
      "Maid", "Jiaoxing is a maid in the Zhen house.")),
  E("yucun", "jiaoxing",
    P(1, "love", "回顾", "娇杏回头看了雨村两眼，雨村便以为她有意于己。",
      "A backward glance", "Jiaoxing glances back at Yucun twice, and he thinks she admires him."),
    P(2, "kin", "扶正", "雨村做官后娶娇杏为二房，后来扶为正室。",
      "Wife", "Become an official, Yucun takes her as a concubine and then as his wife.")),
  E("yucun", "xiangling",
    P(4, "tie", "葫芦案", "雨村明知英莲是恩人之女，却徇情枉法，任她落在薛蟠手里。",
      "Betrayal", "Knowing she is his benefactor’s daughter, Yucun still leaves her to Xue Pan.")),
  E("fengyuan", "xiangling",
    P(4, "love", "一见钟情", "冯渊一眼看上了被拐的英莲，立誓娶她为妻。",
      "Love at first sight", "Feng Yuan falls for the kidnapped girl and vows to marry her.")),
  E("jinghuan", "sengdao",
    P(1, "aid", "交割", "一僧一道要把顽石带到警幻仙子宫中交割清楚。",
      "Handing it over", "The monk and the Taoist take the stone to Disenchantment’s palace to hand it over.")),
  E("jinghuan", "shiyin",
    P(1, "aid", "梦入幻境", "甄士隐梦中随僧道到了太虚幻境的牌坊前，见对联“假作真时真亦假，无为有处有还无”。",
      "The gate", "In his dream Shiyin reaches the gate of the Land of Illusion, with its couplet: when the false is taken for true, the true becomes false.")),
  E("jinghuan", "xiangling",
    P(120, "aid", "销号", "甄士隐把香菱的魂魄送到警幻案前对册销号。",
      "Struck off", "Shiyin brings Xiangling’s spirit before Disenchantment to be struck from the registers.")),
  E("miaoyu", "liulaolao",
    P(41, "tie", "成窑杯", "刘姥姥用过的成窑杯，妙玉嫌脏，叫人搁在外头不要了。",
      "The teacup", "Miaoyu throws out the precious cup Granny Liu drank from.")),
  E("jiarui", "sengdao",
    P(12, "tie", "风月宝鉴", "跛足道人送贾瑞风月宝鉴，嘱咐只照背面，他偏照正面。",
      "The mirror", "The lame Taoist gives Jia Rui a mirror, warning him to look only at its back; he looks at the front.")),
  E("madaopo", "zhaoyiniang",
    P(25, "tie", "五百两欠契", "赵姨娘许了马道婆五百两银子的欠契，马道婆拿出两个纸人，叫她写上宝玉、凤姐的年庚八字。",
      "The bargain", "For an IOU of five hundred taels, Mother Ma hands over two paper figures to be marked with Baoyu’s and Xifeng’s birth dates."),
    P(81, "tie", "事败", "马道婆用魇魔法害人的事在一家当铺败露，被拿问。",
      "Exposed", "Mother Ma’s witchcraft is exposed at a pawnshop and she is arrested.")),
]
