# -*- coding: utf-8 -*-
"""Dream of the Red Chamber: the related families (Lin, Shi, Wang, Xue) and the servants. Fields as in nodes_jia.py."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import N  # noqa: E402

NODES_KIN = [
  # =============================================================== 林家 the Lins
  N(id="linruhai", zh="林如海", py="Lín Rúhǎi", en="Lin Ruhai", grp="kin", debut=2, dies=14,
    camps=[(2, "lin")],
    sub=("巡盐御史 · 黛玉之父", "Salt commissioner at Yangzhou, Daiyu’s father"),
    bio=("姑苏人，前科的探花，钦点巡盐御史，娶了贾母的女儿贾敏(第2回)。妻子死后，他把独女黛玉送到京城外祖母家，请正在他家教书的贾雨村一路护送，又写信给内兄贾政，替雨村谋了官职(第2—3回)。第十二回他病重，接黛玉回扬州；第十四回传来消息，他于九月初三日巳时去世。",
         "A Suzhou man who came third in the palace examination and was appointed salt commissioner; he married Grandmother Jia’s daughter Jia Min (ch. 2). After his wife’s death he sends his only daughter Daiyu to her grandmother in the capital, with her tutor Jia Yucun as escort, and writes to his brother-in-law Jia Zheng to find Yucun a post (chs. 2–3). He falls gravely ill in chapter 12 and sends for Daiyu; in chapter 14 word comes that he has died."),
    icon=("乌纱长须，儒雅清瘦。", "Black gauze hat, long beard, a thin scholarly face.")),
  N(id="daiyu", zh="林黛玉", py="Lín Dàiyù", en="Lin Daiyu", grp="kin", debut=1, dies=98,
    camps=[(1, "lin")],
    sub=("林如海之女 · 贾母的外孙女", "Lin Ruhai’s daughter, Grandmother Jia’s granddaughter"),
    bio=("前身是灵河岸上三生石畔的绛珠仙草，受神瑛侍者甘露灌溉，修成女体，发愿随他下世为人，“但把我一生所有的眼泪还他”(第1回)。母亲死后她进京投奔外祖母，“步步留心，时时在意，不肯轻易多说一句话，多行一步路”(第3回)。她住潇湘馆，号“潇湘妃子”(第37回)，诗才第一：《葬花吟》(第27回)、菊花诗夺魁(第38回)、《秋窗风雨夕》(第45回)、《五美吟》(第64回)、《桃花行》(第70回)。她和宝玉自小一处长大，常为“金玉”之说争吵怄气(第29回)；宝玉向她“诉肺腑”(第32回)，挨打后又托晴雯送她两块旧手帕，她在帕上题了三首诗(第34回)。",
         "In a former life she was the Crimson Pearl flower beside the Stone of Three Lives, watered with dew by the attendant Shenying; given human form, she vowed to follow him into the world and repay him with all the tears of her life (ch. 1). After her mother’s death she comes to her grandmother’s house, watching every step and every word (ch. 3). She lives at Bamboo Lodge, takes the pen name “Consort of the Xiang River” (ch. 37), and is the finest poet of them all: the Burial of Flowers (ch. 27), the prize-winning chrysanthemum poems (ch. 38), Autumn Wind and Rain (ch. 45), Five Beauties (ch. 64), Peach Blossom (ch. 70). She and Baoyu have grown up together and quarrel endlessly over the prophecy of a “gold and jade” match (ch. 29); he pours out his heart to her (ch. 32), and after his beating sends her two old handkerchiefs, on which she writes three poems (ch. 34)."),
    late=("她从傻大姐口中得知宝玉要娶宝钗，顿时“迷迷痴痴”(第96回)；病中焚了诗稿和题诗的手帕(第97回)，在宝玉成婚的同一时刻死去，临终叫道“宝玉，宝玉，你好……”(第98回)。",
          "From Simple Sister she learns that Baoyu is to marry Baochai, and loses her senses (ch. 96); she burns her poems and the handkerchiefs (ch. 97), and dies at the hour of his wedding, crying, “Baoyu, Baoyu, how could you…” (ch. 98)."),
    icon=("肩荷花锄，挂着纱囊(葬花)。", "A flower hoe on her shoulder and a silk bag for fallen petals.")),

  # =============================================================== 史家 the Shis
  N(id="xiangyun", zh="史湘云", py="Shǐ Xiāngyún", en="Shi Xiangyun", grp="kin", debut=20, dies=None,
    camps=[(20, "shi")],
    sub=("贾母的侄孙女", "Grandmother Jia’s grandniece"),
    bio=("史家的姑娘，贾母娘家的侄孙女，自幼父母双亡，在叔婶家“一点儿作不得主”，常做针线到三更半夜(第32回)。她心直口快，咬舌，把“二哥哥”叫成“爱哥哥”(第20回)；又当众说戏子扮相像林妹妹，惹得黛玉生气(第22回)。她带着一只金麒麟，宝玉在清虚观也得了一只，回目说“因麒麟伏白首双星”(第29、31回)。她劝宝玉留心仕途经济，被宝玉说“林姑娘从来说过这些混账话不曾”(第32回)。她做东请螃蟹宴(第37—38回)，在芦雪庵烤鹿肉(第49回)，醉卧芍药裀(第62回)，中秋夜和黛玉在凹晶馆联诗：“寒塘渡鹤影，冷月葬花魂”(第76回)。",
         "A girl of the Shi family, Grandmother Jia’s grandniece, orphaned as a baby and raised by an uncle and aunt in whose house she has no say, sewing till midnight (ch. 32). Frank and boyish, she lisps “Ai-gege” for “Er-gege” (ch. 20) and blurts out that an actress looks like Daiyu (ch. 22). She wears a gold unicorn, and Baoyu gets a matching one at the Taoist temple — a hint that they will grow old together (chs. 29, 31). When she urges him to think of a career, he asks whether Miss Lin has ever talked such rubbish (ch. 32). She hosts the crab feast (chs. 37–38), roasts venison in the snow (ch. 49), falls asleep drunk on a bed of peony petals (ch. 62), and on the mid-autumn night composes linked verse with Daiyu by the pond (ch. 76)."),
    late=("她出嫁后回门，贾母称赞她女婿甚好(第108回)；贾母去世时，丈夫已得了痨病(第110回)，应了曲中“云散高唐，水涸湘江”。",
          "Married, she comes home on a visit, and Grandmother Jia praises her husband (ch. 108); by Grandmother Jia’s death he is ill with consumption (ch. 110) — “the clouds scatter, the river runs dry”."),
    icon=("鬓边簪花，腰系金麒麟。", "Flowers in her hair and the gold unicorn at her waist.")),

  # =============================================================== 王家 the Wangs
  N(id="wangziteng", zh="王子腾", py="Wáng Zǐténg", en="Wang Ziteng", grp="kin", debut=3, dies=96,
    camps=[(3, "wang")],
    sub=("京营节度使 · 九省统制", "Commander of the capital garrison, later of nine provinces"),
    bio=("金陵王家的当家人，王夫人和薛姨妈的哥哥(第4回)，凤姐的叔父。他由京营节度使升了九省统制，奉旨出都查边(第4回)，后来又升九省都检点(第53回)，是贾、薛两家在朝中的靠山。薛蟠打死人命，是他得了消息，想叫薛家进京(第3回)；贾雨村能补京缺，也靠他“累上保本”(第16回)。",
         "Head of the Wang family of Jinling, brother of Lady Wang and Aunt Xue (ch. 4) and uncle of Xifeng. He rises from commander of the capital garrison to commander of nine provinces (ch. 4), later to their inspector-general (ch. 53), and is the Jias’ and Xues’ protector at court. It is he who, hearing of Xue Pan’s killing, wants the Xues brought to the capital (ch. 3), and his recommendations bring Jia Yucun a post there (ch. 16)."),
    late=("他奉召进京入阁，途中“赶路劳乏，偶然感冒风寒”，在十里屯请医调治，“误用了药，一剂就死了”(第95—96回)。贾家从此失去了最大的靠山。",
          "Summoned to the capital as a grand secretary, he catches a chill on the road and dies of a wrongly prescribed medicine (chs. 95–96). The Jias lose their greatest protector."),
    icon=("武官顶戴，绣狮补服。", "A military official’s hat and a lion rank badge.")),

  # =============================================================== 薛家 the Xues
  N(id="xueyima", zh="薛姨妈", py="Xuē yímā", en="Aunt Xue", grp="kin", debut=3, dies=None,
    camps=[(3, "xue")], born=("王", "Wang"),
    sub=("王夫人之妹 · 薛蟠与宝钗之母", "Lady Wang’s sister, mother of Xue Pan and Baochai"),
    bio=("王家的女儿，和王夫人“一母所生”，嫁到皇商薛家，丈夫早死(第4回)。儿子薛蟠打死了人，她借送宝钗待选之名带着儿女进京，住在荣府的梨香院(第4回)。她性情慈和，见黛玉孤苦，把她搂在怀里抚慰，又说想把她说给宝玉，“岂不四角俱全”(第57回)。",
         "Born a Wang, Lady Wang’s full sister, and widow of an imperial merchant (ch. 4). When her son Xue Pan kills a man she brings her children to the capital, on the pretext of presenting Baochai for palace service, and lives in the Rong mansion’s Pear Fragrance Court (ch. 4). Warm-hearted, she comforts the lonely Daiyu and says she should marry Baoyu (ch. 57)."),
    late=("薛蟠又打死了人(第85—86回)，夏金桂在家中撒泼，她终日受气。薛蟠出狱后，她做主把香菱扶为正室(第120回)。",
          "Xue Pan kills again (chs. 85–86) and his wife Jingui rules the house with her tantrums. When he is released she has him make Xiangling his wife (ch. 120)."),
    icon=("中年妇人，抹额，面带笑容。", "Matronly, with a headband and a kind smile.")),
  N(id="xuepan", zh="薛蟠", py="Xuē Pán", en="Xue Pan", grp="kin", debut=3, dies=None,
    camps=[(3, "xue")],
    sub=("薛家独子 · 人称“呆霸王”", "The Xues’ only son, “the Bully King”"),
    bio=("皇商薛家的独子，“性情奢侈，言语傲慢”，人称“呆霸王”(第4回)。他为抢买英莲，喝令豪奴打死了冯渊，由贾雨村胡乱判断了事(第4回)。他把柳湘莲当作戏子调戏，被柳湘莲诱到北门外苇塘边痛打一顿，羞得出门做生意去了(第47—48回)；后来路上遇盗，被柳湘莲所救，二人结为生死弟兄(第66回)。第七十九回他娶了夏金桂，从此家宅不宁；他听了金桂的挑唆，拿门闩毒打香菱(第80回)。",
         "Only son of the imperial merchant family, extravagant and arrogant — “the Bully King” (ch. 4). To get the girl Yinglian he has his men beat Feng Yuan to death, and Jia Yucun lets him off (ch. 4). He makes a pass at Liu Xianglian, taking him for an actor, and is lured out of the city and thrashed, after which he leaves on a trading trip out of shame (chs. 47–48); later Liu saves him from robbers and they become sworn brothers (ch. 66). In chapter 79 he marries Xia Jingui and has no more peace at home; egged on by her, he beats Xiangling with a door bar (ch. 80)."),
    late=("第八十五回他在外酒后打死了酒保，薛家花钱打点，知县断为误伤(第85—86回)。后来遇赦出狱，立誓改过，把香菱扶为正室(第120回)。",
          "In chapter 85 he kills a waiter in a drunken brawl; the family’s bribes get the magistrate to rule it an accident (chs. 85–86). Pardoned at last, he swears to reform and makes Xiangling his wife (ch. 120)."),
    icon=("圆脸，瓜皮帽，手提马鞭。", "Round face, skullcap and a riding whip.")),
  N(id="baochai", zh="薛宝钗", py="Xuē Bǎochāi", en="Xue Baochai", grp="kin", debut=4, dies=None,
    camps=[(4, "xue"), (97, "rong", "嫁给宝玉", "Marries Baoyu")],
    sub=("薛姨妈之女 · 王夫人的外甥女", "Aunt Xue’s daughter, Lady Wang’s niece"),
    bio=("“品格端方，容貌丰美”，人多谓黛玉所不及；她又“行为豁达，随分从时”，连小丫头们也喜欢和她玩(第5回)。她从胎里带来一股热毒，靠一个和尚给的方子配了“冷香丸”压着(第7回)；项上的金锁錾着“不离不弃，芳龄永继”，和宝玉玉上的“莫失莫忘，仙寿恒昌”正是一对(第8回)。她住蘅芜苑，号“蘅芜君”(第37回)。在滴翠亭外她偷听到小红的私话，便故意喊“颦儿，我看你往那里藏”，金蝉脱壳(第27回)。她劝黛玉别在人前说《西厢》《牡丹亭》里的句子，两人从此交心，结为金兰(第42、45回)。凤姐病时她协助探春理家(第56回)。",
         "Upright, beautiful and generous, liked by everyone down to the youngest maids — many think her lovelier than Daiyu (ch. 5). She was born with a feverish humour, kept down by “Cold Fragrance Pills” made to a monk’s recipe (ch. 7); her gold locket is engraved “Never leave me, never forsake me, and youth will last for ever”, which pairs exactly with the words on Baoyu’s jade (ch. 8). She lives at Alpinia Park (ch. 37). Overhearing two maids’ secret by Dripping Emerald Pavilion, she calls out “Pin’er, where are you hiding?” so they will think it was Daiyu (ch. 27). She gently warns Daiyu against quoting love stories in company, and the two become true friends (chs. 42, 45). She helps Tanchun run the household while Xifeng is ill (ch. 56)."),
    late=("宝玉失玉疯癫，贾母、王夫人和凤姐定下调包计，她含悲出嫁，宝玉还以为娶的是黛玉(第96—97回)。婚后她把黛玉已死的实情告诉宝玉，宝玉痛哭之后，病反倒渐渐好了(第98回)。宝玉中举出走时，她已怀有身孕(第119—120回)。",
          "When Baoyu loses his wits the elders arrange the switch, and she is married to him, in sorrow, while he believes his bride is Daiyu (chs. 96–97). She tells him the truth of Daiyu’s death; after weeping he slowly recovers (ch. 98). When he disappears after the examination she is carrying his child (chs. 119–120)."),
    icon=("项戴金锁，手执团扇。", "The gold locket at her throat, a round fan in her hand.")),
  N(id="baoqin", zh="薛宝琴", py="Xuē Bǎoqín", en="Xue Baoqin", grp="kin", debut=49, dies=None,
    camps=[(49, "xue")],
    sub=("薛蝌之妹 · 宝钗的堂妹", "Xue Ke’s sister, Baochai’s cousin"),
    bio=("随哥哥薛蝌进京待嫁，她已许了梅翰林的儿子(第49回)。她生得极美，贾母一见便逼着王夫人认作干女儿，又把一件野鸭子头上毛织的凫靥裘给了她(第49回)，还向薛姨妈打听她的生辰，想说给宝玉，听说已有人家才作罢(第50回)。雪中她披着凫靥裘立在山坡上，身后丫鬟抱着一瓶红梅，贾母说比仇十洲的《双艳图》还好(第50回)。她作了十首怀古诗(第51回)。",
         "She comes to the capital with her brother Xue Ke to be married, already betrothed to the son of an academician named Mei (ch. 49). She is so lovely that Grandmother Jia makes Lady Wang adopt her and gives her a cloak woven from wild-duck feathers (ch. 49), and even asks about her horoscope with Baoyu in mind, until she learns the girl is spoken for (ch. 50). Standing on a snowy slope in that cloak, with a maid holding a vase of red plum behind her, she is lovelier than any painting, the old lady says (ch. 50). She writes ten poems on historic sites (ch. 51)."),
    icon=("披凫靥裘，手持红梅。", "A cloak of duck feathers, a branch of red plum.")),
  N(id="xueke", zh="薛蝌", py="Xuē Kē", en="Xue Ke", grp="kin", debut=49, dies=None,
    camps=[(49, "xue")],
    sub=("薛蟠的堂弟 · 宝琴之兄", "Xue Pan’s cousin, Baoqin’s brother"),
    bio=("宝琴的哥哥，送妹妹进京出嫁(第49回)。他为人稳重；薛姨妈看中了邢夫人的侄女邢岫烟，托凤姐求贾母作保山，把岫烟说给了他(第57回)。",
         "Baoqin’s brother, who brings her to the capital to be married (ch. 49). Steady and decent, he is matched by Aunt Xue, through Grandmother Jia, with Lady Xing’s niece, the poor but graceful Xing Xiuyan (ch. 57)."),
    late=("薛蟠犯了人命，他四处奔走打点(第85—86回)。夏金桂看上了他，叫宝蟾送酒送果子勾引，他一概不理(第90—91回)；金桂拉住他往屋里拽，被香菱撞见(第100回)。",
          "When Xue Pan kills again he runs about bribing officials (chs. 85–86). Xia Jingui sets her eyes on him and sends her maid with wine and fruit to seduce him, but he ignores them (chs. 90–91); once she drags him toward her room, and Xiangling sees it (ch. 100)."),
    icon=("青衫书生。", "A young scholar in a plain gown.")),
  N(id="xiajingui", zh="夏金桂", py="Xià Jīnguì", en="Xia Jingui", grp="kin", debut=79, dies=103,
    camps=[(79, "xue")], born=("夏", "Xia"),
    sub=("薛蟠之妻", "Xue Pan’s wife"),
    bio=("“桂花夏家”的独女，“外具花柳之姿，内秉风雷之性”(第79回)。嫁进薛家后，她立意要压倒薛蟠，把香菱的名字改成“秋菱”，又把自己的丫鬟宝蟾给了薛蟠，挑唆薛蟠毒打香菱(第79—80回)。",
         "Only daughter of the Xias, rich from osmanthus groves: “a flower outside, a storm within” (ch. 79). Married to Xue Pan, she sets out to master him; she renames Xiangling, gives her own maid to her husband, and stirs him up to beat Xiangling (chs. 79–80)."),
    late=("她看上了薛蝌，屡次勾引不成(第90—91、100回)，便把怨气都撒在香菱身上；第一百零三回她在汤里下毒想毒死香菱，宝蟾却把两碗汤换了，她自己毒发身亡。",
          "She tries again and again to seduce Xue Ke (chs. 90–91, 100) and takes her spite out on Xiangling; in chapter 103 she poisons Xiangling’s soup, but her maid switches the bowls and Jingui dies of her own poison."),
    icon=("艳妆，柳眉倒竖。", "Gaudy finery, brows raised in anger.")),

  # =============================================================== 丫鬟仆妇 servants
  N(id="pinger", zh="平儿", py="Píng’ér", en="Ping’er", grp="serv", debut=6, dies=None,
    camps=[(6, "rong")],
    sub=("凤姐的陪嫁丫鬟 · 贾琏的通房", "Xifeng’s maid from home, Jia Lian’s concubine"),
    bio=("凤姐从娘家带来的丫鬟，也是贾琏的屋里人，凤姐的心腹。刘姥姥一进荣国府，见她穿金戴银，还以为她就是凤姐(第6回)。她替贾琏藏下多姑娘的头发，在凤姐面前替他遮掩(第21回)；凤姐生日撞破贾琏与鲍二家的私情，凤姐和贾琏都拿她出气，宝玉请她到怡红院替她理妆(第44回)。坠儿偷了她的虾须镯，她怕宝玉没脸、晴雯生气，悄悄告诉了麝月(第52回)；玫瑰露、茯苓霜的案子，她替柳五儿洗清冤枉，又顾全了探春的体面(第61回)。尤二姐受气时，只有她暗中照顾(第69回)。",
         "The maid Xifeng brought from home, now also Jia Lian’s concubine and Xifeng’s right hand. On her first visit Granny Liu sees her in silks and jewels and takes her for Xifeng (ch. 6). She hides another woman’s lock of hair from Xifeng to save Jia Lian (ch. 21); on Xifeng’s birthday both Xifeng and Jia Lian vent their anger on her, and Baoyu takes her to his rooms to repair her make-up (ch. 44). When a maid steals her bracelet she tells only Sheyue, to spare Baoyu and Qingwen (ch. 52); she clears an innocent girl in a theft case while protecting Tanchun’s face (ch. 61). When You Erjie is persecuted, only Ping’er secretly helps her (ch. 69)."),
    late=("凤姐死后，她和刘姥姥一起把巧姐救出，藏到乡下(第119回)；贾琏感激她，打算把她扶正(第119回)。",
          "After Xifeng’s death she and Granny Liu save Qiaojie and hide her in the country (ch. 119); grateful, Jia Lian means to make her his wife (ch. 119)."),
    icon=("发髻简洁，腰挂钥匙。", "A simple bun and a bunch of keys at her waist.")),
  N(id="xiren", zh="袭人", py="Xírén", en="Xiren", grp="serv", debut=3, dies=None,
    camps=[(3, "rong"), (120, "out", "嫁给蒋玉菡", "Married to Jiang Yuhan")],
    sub=("宝玉的首席丫鬟", "Baoyu’s chief maid"),
    bio=("本名珍珠，原是贾母的丫鬟，贾母爱她“心地纯良，克尽职任”，给了宝玉；宝玉知道她姓花，从旧诗“花气袭人”里给她改名袭人(第3回)。她和宝玉“初试云雨情”(第6回)，又借家里要赎她回去的话，要宝玉答应改掉几样毛病(第19回)。宝玉挨打后，她向王夫人进言，劝她设法叫宝玉搬出园子以防不测，从此王夫人把她当作宝玉未来的姨娘看待(第34、36回)。晴雯等人被撵，宝玉疑心是她告的密(第77回)。",
         "Originally Grandmother Jia’s maid Pearl, given to Baoyu for her devotion; knowing her surname is Hua, “flower”, he renames her from an old line of poetry about the fragrance of flowers (ch. 3). She is the first to share his bed (ch. 6), and uses a threat of leaving to make him promise to mend his ways (ch. 19). After his beating she advises Lady Wang to move him out of the garden for safety, and is treated from then on as his future concubine (chs. 34, 36). When Qingwen and others are dismissed, Baoyu suspects her of informing (ch. 77)."),
    late=("宝玉出走后，她被家里许给了蒋玉菡，含悲出嫁；洞房里见了宝玉当年换给蒋玉菡的那条松花绿汗巾，才知他就是琪官，“始信姻缘前定”(第120回)。",
          "After Baoyu disappears her family marries her to Jiang Yuhan. On the wedding night she sees the green sash Baoyu once gave the actor Qiguan, and knows her fate was fixed long ago (ch. 120)."),
    icon=("手持松花绿汗巾。", "Holding a pale green sash.")),
  N(id="qingwen", zh="晴雯", py="Qíngwén", en="Qingwen", grp="serv", debut=5, dies=78,
    camps=[(5, "rong"), (77, "out", "病中被撵出大观园", "Thrown out of the garden while ill")],
    sub=("宝玉的丫鬟", "Baoyu’s maid"),
    bio=("赖大家买来孝敬贾母的丫头，后给了宝玉，模样最出众，口齿最伶俐，心直口快。她跌断了扇骨，宝玉说了两句，两人吵了起来；晚上宝玉索性拿扇子给她撕着玩，“千金难买一笑”(第31回)。宝玉挨打后托她给黛玉送去两块旧手帕(第34回)。宝玉的孔雀裘烧了个洞，她病中熬夜替他补好(第52回)。王善保家的告她“妖妖趫趫”，王夫人叫来一看，骂她“真象个病西施”(第74回)；抄检时她挽着头发闯进来，将箱子掀开，把东西尽情倒了一地(第74回)。第七十七回她病中被撵出园子，宝玉偷偷去看她，她铰下两根指甲给宝玉，又和宝玉换了贴身的袄儿，说“早知如此，我当日也另有个道理”。次日她便咽了气(第78回)。",
         "Bought by a steward’s family as a gift for Grandmother Jia and passed on to Baoyu; the prettiest and sharpest-tongued of his maids. She breaks a fan, he scolds, they quarrel; that evening he gives her fans to tear for the fun of it — a smile is worth more than gold (ch. 31). After his beating she carries his handkerchiefs to Daiyu (ch. 34). When his peacock-feather cloak is burnt she mends it overnight though she is ill (ch. 52). Denounced by Wang Shanbao’s wife as a flirt, she is sneered at by Lady Wang as a “sickly Xi Shi” (ch. 74); at the search she tips her whole trunk out on the floor (ch. 74). In chapter 77 she is thrown out while sick; Baoyu visits her in secret, and she cuts off two of her fingernails for him and exchanges inner jackets with him — had she known she would be accused anyway, she says, she would have acted otherwise. She dies the next day (ch. 78)."),
    late=("宝玉看见她当年补过的雀金裘，“人亡物在”，填了一首词祭她(第89回)。",
          "Seeing the cloak she mended, Baoyu writes a lyric for her (ch. 89)."),
    icon=("手持撕开的扇子。", "A torn fan.")),
  N(id="sheyue", zh="麝月", py="Shèyuè", en="Sheyue", grp="serv", debut=5, dies=None,
    camps=[(5, "rong")],
    sub=("宝玉的丫鬟", "Baoyu’s maid"),
    bio=("怡红院的大丫鬟，性情稳重，凡事学着袭人。众人都出去玩时她独自看屋子，宝玉替她篦头，被晴雯撞见取笑(第20回)。坠儿偷镯子的事，平儿只悄悄告诉了她(第52回)。宝玉生日夜宴，她掣得荼蘼花签，题着“韶华胜极”，下面一句是“开到荼蘼花事了”(第63回)。",
         "A senior maid at Red Delight, steady and modelled on Xiren. Left alone to mind the rooms while the others play, she has her hair combed by Baoyu, and Qingwen catches them (ch. 20). Ping’er confides the bracelet theft to her alone (ch. 52). At Baoyu’s birthday party she draws the briar-rose lot, “Beauty at its height”: “When the briar roses bloom, the flowers are done” (ch. 63)."),
    icon=("手执篦子。", "A fine-toothed comb.")),
  N(id="zijuan", zh="紫鹃", py="Zǐjuān", en="Zijuan", grp="serv", debut=3, dies=None,
    camps=[(3, "lin"), (118, "kong", "随惜春修行", "Follows Xichun into religion")],
    sub=("黛玉的丫鬟", "Daiyu’s maid"),
    bio=("原名鹦哥，贾母见黛玉的两个人都不中用，把自己身边的这个二等丫头给了她(第3回)，后改名紫鹃，与黛玉情同姊妹。为了试探宝玉，她骗他说林姑娘明年要回苏州去，宝玉当场急得两眼发直、人事不省，见了姓林的就闹(第57回)。事后她劝黛玉“趁早儿老太太还明白硬朗的时节，作定了大事要紧”(第57回)。",
         "Once Grandmother Jia’s maid Parrot, given to Daiyu because the servants she brought were too young or too old (ch. 3), later renamed Zijuan, “cuckoo”, and like a sister to her. To test Baoyu she tells him Daiyu will go back to Suzhou next year; he goes rigid and senseless, and screams at anything called Lin (ch. 57). Afterwards she urges Daiyu to settle her future while Grandmother Jia is still strong (ch. 57)."),
    late=("黛玉临终，只有她守在身边，黛玉说“妹妹，你是我最知心的”(第97—98回)。她怨宝玉负心，后来听宝玉隔窗诉说苦衷，才渐渐明白(第113回)。惜春出家，她自愿跟去伺候(第118回)。",
          "She is with Daiyu at the end, when Daiyu calls her the friend who knew her best (chs. 97–98). She blames Baoyu until he pours out his heart to her through her window (ch. 113). When Xichun takes vows, Zijuan asks to go with her (ch. 118)."),
    icon=("手捧药碗。", "Carrying a bowl of medicine.")),
  N(id="xueyan", zh="雪雁", py="Xuěyàn", en="Xueyan", grp="serv", debut=3, dies=None,
    camps=[(3, "lin")],
    sub=("黛玉从家里带来的小丫鬟", "The little maid Daiyu brought from home"),
    bio=("黛玉从扬州带来的小丫头，才十岁，“甚小，一团孩气”(第3回)。冬天她奉紫鹃之命给黛玉送手炉到梨香院，黛玉借题讥讽宝玉：“也亏你倒听他的话。我平日和你说的，全当耳旁风”(第8回)。",
         "The little maid Daiyu brought from Yangzhou, only ten and still a child (ch. 3). Sent with a hand-warmer to Pear Fragrance Court on Zijuan’s orders, she gives Daiyu the chance to tease Baoyu: how obedient she is to that one, when she ignores everything Daiyu says (ch. 8)."),
    late=("宝玉成婚那夜，凤姐把她借去扶新娘，好叫宝玉以为娶的是黛玉(第97回)。",
          "On Baoyu’s wedding night Xifeng borrows her to attend the bride, so that Baoyu will believe he is marrying Daiyu (ch. 97)."),
    icon=("小丫头，捧着手炉。", "A small girl with a hand-warmer.")),
  N(id="yinger", zh="莺儿", py="Yīng’ér", en="Ying’er", grp="serv", debut=7, dies=None,
    camps=[(7, "xue")],
    sub=("宝钗的丫鬟", "Baochai’s maid"),
    bio=("本名金莺，宝钗嫌拗口，只叫她莺儿(第35回)。宝钗看宝玉的通灵玉，她在旁说玉上的字“倒象和姑娘的项圈上的两句话是一对儿”(第8回)。她手巧，替宝玉打梅花络子，宝钗叫她用金线配黑珠线把通灵玉络上(第35回)；她采柳条编花篮，惹得春燕的姑妈骂了一场(第59回)。",
         "Her name was Jinying, “golden oriole”, but Baochai found it awkward and shortened it (ch. 35). When Baochai reads the words on Baoyu’s jade, she remarks that they seem to pair with those on her mistress’s locket (ch. 8). Clever with her hands, she knots Baoyu a plum-blossom net for his jade in gold and black thread (ch. 35), and weaves baskets from willow twigs, setting off a quarrel with the women who tend the willows (ch. 59)."),
    icon=("手编柳条花篮。", "Weaving a willow basket.")),
  N(id="yuanyang", zh="鸳鸯", py="Yuānyāng", en="Yuanyang", grp="serv", debut=24, dies=111,
    camps=[(24, "rong")],
    sub=("贾母的大丫鬟", "Grandmother Jia’s chief maid"),
    bio=("贾母最信任的丫鬟，管着贾母的箱笼钱物，宴席上替贾母“三宣牙牌令”(第40回)。贾赦要讨她做妾，邢夫人亲自来说，嫂子也来劝，她拉着嫂子到贾母跟前跪下，拿剪子铰头发，发誓“这一辈子莫说是‘宝玉’，便是‘宝金’‘宝银’‘宝天王’‘宝皇帝’，横竖不嫁人就完了”(第46回)。她夜里撞见司棋和表弟潘又安在山石后私会，答应保密，后来又去看病中的司棋，发誓不告诉一个人(第71—72回)。",
         "The maid Grandmother Jia trusts most, keeper of her chests and money, who calls the rules of the domino game at the garden feast (ch. 40). When Jia She wants her as a concubine and Lady Xing and her own sister-in-law press her, she kneels before Grandmother Jia, cuts off her hair and swears she will marry no one — not a Baoyu, nor a gold one, nor a silver one, nor the emperor himself (ch. 46). Coming upon Siqi and her cousin together one night, she promises silence, and later visits the frightened, sick Siqi to swear it again (chs. 71–72)."),
    late=("贾母死后，她想到“自己跟着老太太一辈子，身子也没有着落”，在贾母的套间里上吊殉主；临死前看见秦可卿的魂拿着汗巾作上吊的样子，死后又由她引路(第111回)。",
          "After Grandmother Jia’s death, with no future and no protector, she hangs herself in her mistress’s rooms, led by the ghost of Qin Keqing (ch. 111)."),
    icon=("手持剪刀，剪下一绺头发。", "Scissors in hand and a lock of cut hair.")),
  N(id="jinchuan", zh="金钏", py="Jīnchuàn", en="Jinchuan", grp="serv", debut=7, dies=32,
    camps=[(7, "rong"), (30, "out", "被王夫人撵出", "Dismissed by Lady Wang")],
    sub=("王夫人的丫鬟 · 玉钏之姐", "Lady Wang’s maid, Yuchuan’s sister"),
    bio=("王夫人的大丫鬟。王夫人午睡，宝玉来了，她和宝玉说笑，说“金簪子掉在井里头，有你的只是有你的”；王夫人翻身起来打了她一个嘴巴，骂她“下作小娼妇，好好的爷们，都叫你教坏了”，不顾她苦苦哀求，把她撵了出去(第30回)。她含羞赌气，投井而死(第32回)。宝玉在她生日那天偷偷出城，到水仙庵的井台上焚香祭她(第43回)。",
         "Lady Wang’s senior maid. While her mistress naps she jokes with Baoyu; Lady Wang springs up, slaps her, calls her a shameless hussy for leading the young master astray, and dismisses her despite her pleas (ch. 30). Shamed and proud, she drowns herself in a well (ch. 32). On her birthday Baoyu slips out of the city and burns incense for her at the well of a convent (ch. 43)."),
    icon=("腕戴金钏。", "A gold armlet on her wrist.")),
  N(id="yuchuan", zh="玉钏", py="Yùchuàn", en="Yuchuan", grp="serv", debut=25, dies=None,
    camps=[(25, "rong")],
    sub=("金钏的妹妹 · 王夫人的丫鬟", "Jinchuan’s sister, Lady Wang’s maid"),
    bio=("金钏的妹妹，也在王夫人房里当差(第25、30回)。宝玉挨打后想吃莲叶羹，王夫人派她送去；她恨宝玉害死了姐姐，冷着脸不理他，宝玉百般赔笑，骗她亲口尝了一口，她才笑了(第35回)。金钏死后，王夫人把金钏的月钱加给了她，她一人领双份(第36回)。",
         "Jinchuan’s sister, also in Lady Wang’s service (chs. 25, 30). Sent with lotus-leaf soup for Baoyu after his beating, she will not look at the young man she blames for her sister’s death, until he tricks her into tasting the soup and she has to laugh (ch. 35). After Jinchuan’s death Lady Wang gives her her sister’s wages as well (ch. 36)."),
    icon=("手捧莲叶羹。", "Carrying the lotus-leaf soup.")),
  N(id="siqi", zh="司棋", py="Sīqí", en="Siqi", grp="serv", debut=7, dies=92,
    camps=[(7, "rong"), (77, "out", "被撵出大观园", "Thrown out of the garden")],
    sub=("迎春的丫鬟", "Yingchun’s maid"),
    bio=("迎春的大丫鬟，王善保家的外孙女，性子刚强，为了一碗炖鸡蛋带着小丫头到厨房乱翻乱掷，大闹一场(第61回)。她和表弟潘又安在园中山石后私会，被鸳鸯撞见(第71回)。抄检大观园时，偏偏从她箱子里搜出潘又安的字帖和信物，王善保家的只好自己打自己的嘴巴(第74回)。她被撵出园子，哭求迎春说情，迎春也没有留她(第77回)。",
         "Yingchun’s senior maid, granddaughter of Wang Shanbao’s wife; strong-willed enough to have her maids ransack the kitchen over a bowl of steamed egg (ch. 61). Yuanyang comes upon her with her cousin Pan You’an behind the rocks in the garden (ch. 71). At the search his letters and keepsakes are found in her trunk, and her grandmother has to slap her own face (ch. 74). Dismissed, she begs Yingchun to plead for her, but her mistress does not keep her (ch. 77)."),
    late=("潘又安发了财回来娶她，她母亲不答应，她一头撞在墙上死了，潘又安也拿小刀抹了脖子(第92回)。",
          "Pan You’an comes back rich to marry her, but her mother refuses; Siqi dashes her head against a wall and dies, and he cuts his own throat (ch. 92)."),
    icon=("刚强的丫鬟，手握一只同心如意。", "A strong-willed maid holding a love token.")),
  N(id="xiaohong", zh="小红", py="Xiǎohóng", en="Xiaohong", grp="serv", debut=24, dies=None,
    camps=[(24, "rong")],
    sub=("怡红院的小丫鬟 · 后归凤姐", "A junior maid at Red Delight, later Xifeng’s"),
    bio=("本名林红玉，管家林之孝的女儿，因“红玉”二字犯了宝玉、黛玉的名讳，改叫小红(第24回)。她在怡红院只做粗活，好不容易趁屋里没人给宝玉倒了碗茶，就被秋纹、碧痕骂了一顿(第24回)。她丢的手帕被贾芸捡去，两人借小丫头坠儿传递心意(第24、26回)。她在滴翠亭说私话，被宝钗听见(第27回)；那天她替凤姐传话，一大串话说得清清楚楚，凤姐当场把她要了去(第27回)。",
         "Born Lin Hongyu, daughter of the steward Lin Zhixiao; renamed because “Hongyu” clashed with the names of Baoyu and Daiyu (ch. 24). She does rough work at Red Delight, and the one time she manages to pour Baoyu tea, the senior maids scold her (ch. 24). Jia Yun picks up the handkerchief she lost, and they exchange feelings through the little maid Zhuier (chs. 24, 26). Baochai overhears her talking about it by Dripping Emerald Pavilion (ch. 27); that same day she delivers a long message for Xifeng so clearly that Xifeng takes her on at once (ch. 27)."),
    icon=("手拿一方手帕。", "A handkerchief in her hand.")),
  N(id="fangguan", zh="芳官", py="Fāngguān", en="Fangguan", grp="serv", debut=58, dies=None,
    camps=[(58, "rong"), (77, "kong", "随水月庵智通出家", "Becomes a nun at Water Moon Convent")],
    sub=("梨香院的小戏子 · 后归怡红院", "A young actress, later Baoyu’s maid"),
    bio=("为元妃省亲从苏州买来学戏的十二个女孩子之一，唱正旦。国丧期间戏班遣散，贾母把她分给了宝玉(第58回)。她天真任性，为洗头的事和干娘大吵(第58回)；她拿茉莉粉冒充蔷薇硝给了贾环，引得赵姨娘来打她，众小戏子一拥而上和赵姨娘撕打(第60回)。宝玉生日夜宴，她喝醉了睡在宝玉身边(第63回)；宝玉给她改了个番名，叫“耶律雄奴”(第63回)。抄检后王夫人骂“唱戏的女孩子，自然是狐狸精了”，把她撵出去；她和藕官、蕊官寻死觅活要剪了头发做尼姑，跟着水月庵的智通走了(第77回)。",
         "One of the twelve girls bought in Suzhou to sing for the Imperial Consort, the troupe’s leading lady. When the troupe is disbanded during a period of state mourning, Grandmother Jia gives her to Baoyu (ch. 58). Spoilt and spirited, she quarrels with her foster mother over washing her hair (ch. 58); she fobs Jia Huan off with jasmine powder instead of rose-nitre, Concubine Zhao comes to beat her, and the other actresses mob Concubine Zhao (ch. 60). At Baoyu’s birthday party she falls asleep drunk beside him (ch. 63), and he gives her a Khitan nickname (ch. 63). After the search Lady Wang calls all actresses vixens and dismisses her; she and two friends threaten to die unless they can shave their heads, and she goes off with a nun from Water Moon Convent (ch. 77)."),
    icon=("男装短打，额前留着碎发。", "Dressed as a boy, with a fringe.")),
  N(id="lingguan", zh="龄官", py="Língguān", en="Lingguan", grp="serv", debut=18, dies=None,
    camps=[(18, "rong")],
    sub=("梨香院戏班的小旦", "The troupe’s best young actress"),
    bio=("贾蔷从苏州买来的十二个女孩子中唱得最好的小旦，“眉蹙春山，眼颦秋水”，大有林黛玉之态(第30回)。省亲时元妃要她再作两出，贾蔷命她演《游园》《惊梦》，她“自为此二出原非本角之戏，执意不作”，定要演《相约》《相骂》，元妃很喜欢，额外赏了她(第18回)。夏天她蹲在蔷薇架下，用簪子在地上一遍遍地划“蔷”字，宝玉在花外看呆了，下起雨来，他提醒她避雨，自己反淋湿了(第30回)。宝玉请她唱曲，她正色说“嗓子哑了”；看见她和贾蔷的情形，宝玉才明白“人生情缘，各有分定”(第36回)。",
         "The best singer among the twelve girls Jia Qiang bought in Suzhou, with knitted brows and sad eyes very like Daiyu’s (ch. 30). When the Imperial Consort asks for two more scenes, Lingguan refuses the ones Jia Qiang chooses because they are not her roles and insists on two others; the Consort is delighted and rewards her (ch. 18). On a summer day she crouches under the rose trellis scratching one character in the earth with her hairpin, over and over; Baoyu watches, spellbound, and when the rain comes he calls to her to take shelter and gets soaked himself (ch. 30). When he asks her to sing she says coldly that her voice is gone; watching her with Jia Qiang, he understands that each person’s love is meant for someone (ch. 36)."),
    icon=("手持金簪，在地上划字。", "Scratching characters in the earth with a hairpin.")),
  N(id="zhouruijia", zh="周瑞家的", py="Zhōu Ruì jiā de", en="Zhou Rui’s wife", grp="serv", debut=6, dies=None,
    camps=[(6, "rong")],
    sub=("王夫人的陪房", "Lady Wang’s woman from her family"),
    bio=("王夫人的陪房。刘姥姥的女婿家早年帮过周瑞，刘姥姥一进荣国府，就是找她引见了凤姐(第6回)。薛姨妈让她把十二枝宫花送给姑娘们，她最后送到黛玉那里，黛玉问是不是别人都有，冷笑道“我就知道，别人不挑剩下的也不给我”(第7回)。抄检大观园时她也在其列(第74回)。",
         "A servant who came with Lady Wang at her marriage. Granny Liu’s family once did her husband a favour, so on her first visit it is Zhou Rui’s wife who takes her to Xifeng (ch. 6). Sent round with twelve palace flowers for the girls, she comes to Daiyu last, and Daiyu remarks that she knew she would get what the others left (ch. 7). She is one of the searchers of the garden (ch. 74)."),
    icon=("中年仆妇，手捧宫花匣子。", "A servant woman carrying a box of palace flowers.")),
  N(id="wangshanbao", zh="王善保家的", py="Wáng Shànbǎo jiā de", en="Wang Shanbao’s wife", grp="serv", debut=74, dies=None,
    camps=[(74, "rong")],
    sub=("邢夫人的陪房", "Lady Xing’s woman from her family"),
    bio=("邢夫人的陪房，平日在园中没人奉承她，心中早已不忿。绣春囊事发，她趁机在王夫人面前告晴雯的状，撺掇抄检大观园(第74回)。抄到探春处，她仗势去掀探春的衣襟，挨了探春一记耳光；到了迎春处，偏从自己外孙女司棋的箱子里搜出潘又安的情书，只好自己打自己的嘴巴，众人都说“现世现报”(第74回)。",
         "Lady Xing’s woman, resentful because no one in the garden pays her court. When the embroidered pouch turns up she slanders Qingwen to Lady Wang and pushes for a search of the garden (ch. 74). At Tanchun’s she makes a show of lifting her jacket and is slapped for it; at Yingchun’s the love letters turn up in her own granddaughter Siqi’s trunk, and she has to slap her own face, to general satisfaction (ch. 74)."),
    icon=("老仆妇，提着灯笼。", "An old woman with a lantern.")),
  N(id="qiutong", zh="秋桐", py="Qiūtóng", en="Qiutong", grp="serv", debut=69, dies=None,
    camps=[(69, "rong")],
    sub=("贾赦赏给贾琏的妾", "A maid Jia She gives Jia Lian as a concubine"),
    bio=("贾赦房中十七岁的丫鬟，因贾琏办事得力，贾赦把她赏给贾琏为妾；她和贾琏早有旧情，如今“一对烈火干柴”(第69回)。她自恃是贾赦所赐，连凤姐、平儿也不放在眼里，天天指桑骂槐，辱骂尤二姐；凤姐正好借她这把剑“借剑杀人”(第69回)。",
         "A seventeen-year-old maid of Jia She’s, given to Jia Lian as a reward; the two had long had their eyes on each other (ch. 69). Proud of being her master’s gift, she defers to no one, not even Xifeng, and abuses You Erjie day after day — just the “borrowed sword” Xifeng needs (ch. 69)."),
    icon=("浓妆，叉着腰。", "Heavily made up, hands on hips.")),
  N(id="shadajie", zh="傻大姐", py="Shǎ dàjiě", en="Simple Sister", grp="serv", debut=73, dies=None,
    camps=[(73, "rong")],
    sub=("贾母房中做粗活的丫头", "A simple-minded maid of all work in Grandmother Jia’s rooms"),
    bio=("十四五岁，“体肥面阔，两只大脚”，心性愚顽，贾母喜欢她爽利，叫她做粗活，常拿她取笑(第73回)。她在园中山石背后捡到一个绣着春意的香囊，以为是两个妖精打架，拿着走时迎面碰上邢夫人，由此引出抄检大观园(第73—74回)。",
         "A plump, big-footed girl of fourteen or so, slow-witted; Grandmother Jia likes her bluntness and keeps her for rough work and for laughs (ch. 73). Behind a rock in the garden she finds a pouch embroidered with an erotic scene, which she takes for two goblins fighting, and runs straight into Lady Xing with it — the start of the search of the garden (chs. 73–74)."),
    late=("黛玉在园中听见她哭，问起来，她说因为说了“宝二爷娶宝姑娘”的话挨了打——黛玉从此迷了本性(第96回)。",
          "Daiyu finds her crying in the garden: she has been slapped for saying that Baoyu is to marry Baochai. It drives Daiyu out of her senses (ch. 96)."),
    icon=("胖丫头，手拿香囊。", "A plump girl holding an embroidered pouch.")),
  N(id="mingyan", zh="茗烟", py="Míngyān", en="Mingyan", grp="serv", debut=9, dies=None,
    camps=[(9, "rong")],
    sub=("宝玉的小厮", "Baoyu’s page"),
    bio=("宝玉的心腹书童，后来改名焙茗。闹学堂时他受贾蔷挑唆，冲进学堂大骂金荣(第9回)；他带宝玉偷偷到袭人家去(第19回)，又从书坊里买来许多古今小说和传奇角本给宝玉解闷(第23回)。金钏生日，他陪宝玉到城外水仙庵的井台上焚香，还替宝玉祷告：“二爷心事不能出口，让我代祝”(第43回)。",
         "Baoyu’s trusted page, later renamed Beiming. Egged on by Jia Qiang, he storms into the schoolroom to abuse Jin Rong (ch. 9); he takes Baoyu secretly to Xiren’s home (ch. 19), and smuggles him romances and plays from the bookshops (ch. 23). On Jinchuan’s birthday he goes with Baoyu to a convent well and adds his own prayer, since his master’s feelings cannot be spoken aloud (ch. 43)."),
    icon=("小厮，捧着书匣。", "A page holding a book box.")),
  N(id="limama", zh="李嬷嬷", py="Lǐ mómo", en="Nanny Li", grp="serv", debut=3, dies=None,
    camps=[(3, "rong")],
    sub=("宝玉的奶妈", "Baoyu’s wet nurse"),
    bio=("宝玉的乳母，仗着奶过宝玉，常常倚老卖老。她拿走了宝玉留给晴雯的豆腐皮包子，又喝了宝玉沏好的枫露茶，宝玉一气之下摔了茶杯，要回贾母撵她出去(第8回)。她吃了宝玉留给袭人的酥酪(第19回)；又因袭人病着没起身招呼，骂袭人是“忘了本的小娼妇”，凤姐赶来才把她劝走(第20回)。",
         "Baoyu’s wet nurse, who presumes on it. She takes the dumplings Baoyu saved for Qingwen and drinks his maple-dew tea, and he smashes his cup in fury and threatens to have her dismissed (ch. 8). She eats the junket he saved for Xiren (ch. 19), and when Xiren is too ill to get up for her, abuses her as an ungrateful little hussy until Xifeng leads her away (ch. 20)."),
    icon=("老妇人，拄着拐杖。", "An old woman with a stick.")),
  N(id="caixia", zh="彩霞", py="Cǎixiá", en="Caixia", grp="serv", debut=23, dies=None,
    camps=[(23, "rong"), (72, "out", "被放出府去", "Sent home to be married")],
    sub=("王夫人的丫鬟", "Lady Wang’s maid"),
    bio=("王夫人房里的丫鬟，向来和贾环合得来；贾环在王夫人房里抄经，众丫鬟都不理他，只有她倒杯茶给他(第25回)。她年纪大了，又多病，王夫人放她出去让家里择婿，凤姐的陪房来旺家的仗势替自己那个酗酒赌博、容颜丑陋的儿子求娶她；她托妹妹去找赵姨娘，盼着贾环来讨她(第72回)。",
         "A maid of Lady Wang’s and the only one who is kind to Jia Huan: when he copies sutras in Lady Wang’s room and the others ignore him, she brings him tea (ch. 25). Grown up and often ill, she is released to be married, and Xifeng’s servant Lai Wang’s wife uses her influence to get her for her own drunken, gambling, ugly son; Caixia sends her sister to Concubine Zhao, hoping Jia Huan will ask for her (ch. 72)."),
    icon=("丫鬟，端着茶盏。", "A maid with a cup of tea.")),
  N(id="baoer", zh="鲍二家的", py="Bào Èr jiā de", en="Bao Er’s wife", grp="serv", debut=44, dies=44,
    camps=[(44, "rong")],
    sub=("荣府仆人鲍二的妻子", "Wife of the servant Bao Er"),
    bio=("凤姐生日那天，贾琏趁凤姐在席上，把她叫到房里私会。她说“多早晚你那阎王老婆死了就好了”，又说贾琏该把平儿扶正，全被凤姐在窗外听见(第44回)。凤姐冲进去打了她一顿，她羞愤之下上吊死了，贾琏拿了二百两银子发送了事(第44回)。",
         "On Xifeng’s birthday Jia Lian brings her to his room while his wife is at the party. She wishes aloud that his “she-devil” would die, and says he should make Ping’er his wife — and Xifeng hears it all from the window (ch. 44). Xifeng bursts in and beats her; in shame she hangs herself, and Jia Lian pays two hundred taels to settle the matter (ch. 44)."),
    icon=("仆妇，鬓发散乱。", "A servant woman with tousled hair.")),
  N(id="ruhua", zh="入画", py="Rùhuà", en="Ruhua", grp="serv", debut=7, dies=None,
    camps=[(7, "ning"), (74, "out", "被惜春撵走", "Sent away by Xichun")],
    sub=("惜春的丫鬟", "Xichun’s maid"),
    bio=("惜春的丫鬟，周瑞家的送宫花时，惜春就命她收了花(第7回)。抄检时在她箱子里搜出一大包金银锞子、一副玉带板子和一包男人的靴袜，她跪下哭诉是珍大爷赏她哥哥的，因父母在南方，托人悄悄带进来叫她收着(第74回)。惜春不肯留她，叫尤氏带回去，“或打，或杀，或卖，我一概不管”(第74回)。",
         "Xichun’s maid, who takes in the palace flowers for her mistress (ch. 7). At the search a bundle of gold and silver, a jade belt plaque and men’s boots and socks are found in her chest; she weeps that they are gifts from Jia Zhen to her brother, smuggled in for safekeeping (ch. 74). Xichun will not keep her: Madam You may “beat her, kill her or sell her” as she likes (ch. 74)."),
    icon=("丫鬟，抱着包袱。", "A maid clutching a bundle.")),
  N(id="cuilv", zh="翠缕", py="Cuìlǚ", en="Cuilü", grp="serv", debut=21, dies=None,
    camps=[(21, "shi")],
    sub=("湘云的丫鬟", "Xiangyun’s maid"),
    bio=("湘云的丫鬟(第21回)。她跟着湘云在园中走，问东问西，缠着湘云讲“阴阳”的道理，问到人有没有阴阳，被湘云笑骂“下流东西”；随后她在蔷薇架下拾到宝玉丢的金麒麟(第31回)。",
         "Xiangyun’s maid (ch. 21). Walking in the garden she pesters her mistress about yin and yang until Xiangyun laughs at her; then she finds the gold unicorn Baoyu dropped under the rose trellis (ch. 31)."),
    icon=("手捧金麒麟。", "Holding the gold unicorn.")),
  N(id="xiangling", zh="香菱", py="Xiānglíng", en="Xiangling", grp="serv", debut=1, dies=120,
    camps=[(1, "out"), (4, "xue", "被卖给薛蟠", "Sold to Xue Pan")],
    sub=("甄士隐之女英莲 · 薛蟠之妾", "Zhen Shiyin’s lost daughter Yinglian, Xue Pan’s concubine"),
    bio=("甄士隐的独女，小名英莲，眉心有一颗米粒大的胭脂痣。三岁那年元宵看灯，家人霍启抱她出门，把她弄丢了，她被拐子拐走(第1回)。拐子把她先卖给冯渊，又卖给薛蟠，冯渊被打死，她被薛家带走(第4回)，改名香菱；薛蟠后来摆酒请客，正式收她做了妾(第16回)。她憨厚好学，求黛玉教她作诗，“茶饭无心，坐卧不定”，梦里都在吟诗，三易其稿写成咏月诗(第48回)。夏金桂进门后把她改名秋菱，挑唆薛蟠毒打她，宝钗把她带到自己房里(第80回)。",
         "Zhen Shiyin’s only daughter Yinglian, with a tiny red mole between her brows. At three, carried out to see the lanterns, she is lost by a servant and stolen by a kidnapper (ch. 1). He sells her first to Feng Yuan and then to Xue Pan; Feng Yuan is killed and the Xues take her (ch. 4), renaming her Xiangling, and Xue Pan later takes her formally as a concubine (ch. 16). Simple and eager, she begs Daiyu to teach her poetry, forgets to eat, composes in her dreams, and writes three drafts of a moon poem (ch. 48). Xia Jingui renames her and turns Xue Pan against her, and Baochai takes her in (ch. 80)."),
    late=("夏金桂想毒死她，反而自己误服毒汤身死(第103回)。薛蟠出狱后把她扶为正室，后来她难产而死，留下一个儿子；甄士隐度她回太虚幻境销号(第120回)。",
          "Xia Jingui tries to poison her and dies of her own poison (ch. 103). Released from prison, Xue Pan makes her his wife; she dies in childbirth, leaving a son, and her father leads her spirit back to the Land of Illusion (ch. 120)."),
    icon=("眉心一点胭脂痣，手持诗卷。", "A tiny red mole between her brows, a book of poems.")),
]
