# -*- coding: utf-8 -*-
"""Dream of the Red Chamber: the two Jia households (Ning and Rong) and the Jia clan.

Fields (see data_hl.py for the rest)
  grp:    roster group: ning / rong / kin / serv / out
  debut:  chapter in which the person first appears or is formally introduced
  dies:   chapter of death (or of the first report of it), or None
  camps:  [(chapter, household[, zh label, en label]), ...]  household from that chapter on; the optional label says
          what happened (married off, thrown out, took vows)
  bio:    the story in chapters 1-80 (Cao Xueqin's text); citations "(第N回)" / "(ch. N)" become chapter chips
  late:   the story in chapters 81-120 (the Cheng-Gao continuation), shown only when the last forty chapters are on
  born:   birth family of a woman who married into the household, as (zh, en)
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import N  # noqa: E402

NODES_JIA = [
  # =============================================================== 宁国府 the Ning mansion
  N(id="jiajing", zh="贾敬", py="Jiǎ Jìng", en="Jia Jing", grp="ning", debut=2, dies=63,
    camps=[(2, "ning")],
    sub=("宁国公之孙 · 贾珍与惜春之父", "Grandson of the Duke of Ning, father of Jia Zhen and Xichun"),
    bio=("宁国公的孙子，中过进士，却一心想做神仙，把世袭的官让儿子贾珍袭了，自己住在都中城外，“和道士们胡羼”，烧丹炼汞，家里的事一概不管(第2回)。他过生日也不肯回府，对来请他的贾珍说“我是清净惯了的”，不愿受儿孙们磕头(第10回)。第六十三回他吞服自己炼的金丹而死，“肚中坚硬似铁，面皮嘴唇烧的紫绛皱裂”；宁府办丧事，尤氏把继母尤老娘和两个妹妹接来照应，二尤的故事由此开始。",
         "Grandson of the first Duke of Ning, he passed the highest examination but cares only for becoming an immortal: he has handed his hereditary rank to his son Jia Zhen and lives outside the city with Taoist priests, refining elixirs and ignoring the family (ch. 2). He will not even come home for his birthday, telling Jia Zhen, who comes to invite him, that he is used to quiet and wants no kowtowing (ch. 10). In chapter 63 he dies after swallowing an elixir of his own making, his belly hard as iron and his lips burnt and cracked. For the funeral Madam You brings in her stepmother and two stepsisters — the start of the You sisters’ story."),
    icon=("道冠道袍，手托丹炉。", "Taoist cap and robe, holding an elixir furnace.")),
  N(id="jiazhen", zh="贾珍", py="Jiǎ Zhēn", en="Jia Zhen", grp="ning", debut=2, dies=None,
    camps=[(2, "ning")],
    sub=("宁府当家人 · 贾氏族长", "Master of the Ning mansion and head of the clan"),
    bio=("贾敬的儿子，袭了官，又是贾氏族长。冷子兴说他“那里肯读书，只一味高乐不了，把宁国府竟翻了过来，也没有人敢来管他”(第2回)。儿媳秦可卿死后，他哭得泪人一般，说办丧事“不过尽我所有罢了”，用了原是义忠亲王老千岁要的樯木棺材，又替儿子贾蓉捐了个龙禁尉(第13回)。贾敬丧中，他作主退了尤二姐与张华的婚约，把二姐许给贾琏(第64回)；他和贾琏想轻薄尤三姐，反被三姐借酒戏骂了一场(第65回)。居丧期间他在府中聚赌取乐；中秋前夜他带着妻妾开夜宴赏月，祠堂那边的墙下传来一声长叹(第75回)。",
         "Jia Jing’s son, who holds the family rank and heads the clan. Leng Zixing says he never opens a book and has “turned the Ning mansion upside down” with his pleasures, and no one dares stop him (ch. 2). When his daughter-in-law Qin Keqing dies he weeps uncontrollably, spends “everything I have” on her funeral, buys her a coffin of wood once meant for a prince, and purchases a guard’s commission for his son so the rites can be grander (ch. 13). During his father’s funeral he breaks off You Erjie’s old betrothal and gives her to Jia Lian (ch. 64); when he and Jia Lian try to take liberties with You Sanjie, she turns the tables and mocks them over the wine (ch. 65). In mourning, he hosts gambling parties at home; on the eve of mid-autumn, as he feasts under the moon with his wife and concubines, a long sigh is heard from beside the ancestral hall (ch. 75)."),
    late=("宁府被锦衣军查抄，贾珍被革去世职，发往海疆效力赎罪(第105、107回)。到第一百二十回遇赦回家，仍搬回宁国府去住。",
          "When imperial guards search the Ning mansion he is stripped of his rank and sent to serve on the coast (chs. 105, 107). He is pardoned and back home by chapter 120, ready to move into the Ning mansion again."),
    icon=("暖帽石青褂，三绺短须。", "Winter hat, dark blue surcoat and a short beard.")),
  N(id="youshi", zh="尤氏", py="Yóu shì", en="Madam You", grp="ning", debut=5, dies=None,
    camps=[(5, "ning")], born=("尤", "You"),
    sub=("贾珍之妻 · 宁府的女主人", "Jia Zhen’s wife, mistress of the Ning mansion"),
    bio=("贾珍的妻子，性情随和，说话没有多少分量。宁府梅花开时，她治酒请荣府的人赏花，宝玉就在这天睡在了秦可卿房里(第5回)。秦可卿病重，她为媳妇发愁(第10回)；秦氏死时她正犯了胃疼旧疾，贾珍只好请凤姐来协理宁国府(第13回)。贾敬死后她独自料理丧事，接来继母和两个妹妹(第63回)。贾琏偷娶尤二姐的事败露，凤姐大闹宁国府，滚到她怀里哭骂，啐了她一脸(第68回)。抄检大观园后，惜春执意不要入画，还要和宁府断绝来往，姑嫂吵了一场(第74回)。",
         "Jia Zhen’s wife, easy-going and without much say. When the plum trees bloom she gives a party for the Rong household, the day Baoyu naps in Qin Keqing’s room (ch. 5). She frets over her daughter-in-law’s illness (ch. 10), and is laid up with her old stomach trouble when Qin Keqing dies, so Jia Zhen asks Xifeng to run the funeral (ch. 13). At her father-in-law’s death she manages alone and brings in her stepmother and two stepsisters (ch. 63). When Jia Lian’s secret marriage to You Erjie comes out, Xifeng storms the Ning mansion, weeping and railing in her arms and spitting in her face (ch. 68). After the search of the garden Xichun refuses to keep her maid Ruhua and breaks with the Ning mansion, and the two quarrel (ch. 74)."),
    late=("她从荒废的大观园穿过，回去便病倒了，宁府上下接连生病，请人到园中驱邪(第102回)。宁府被抄后靠荣府接济(第106回)；惜春立意出家，以死相逼，她拦不住，只得自己作主答应(第115、117—118回)。",
          "Walking home through the deserted garden, she falls ill, and sickness spreads through the Ning household until exorcists are called in (ch. 102). After the search the Ning family lives on the Rongs’ charity (ch. 106), and she cannot stop Xichun from taking vows, and in the end consents herself (chs. 115, 117–118)."),
    icon=("满头珠翠，披石青披风。", "Pearl and kingfisher ornaments, a dark blue cape.")),
  N(id="jiarong", zh="贾蓉", py="Jiǎ Róng", en="Jia Rong", grp="ning", debut=2, dies=None,
    camps=[(2, "ning")],
    sub=("贾珍之子 · 秦可卿之夫", "Jia Zhen’s son, Qin Keqing’s husband"),
    bio=("贾珍的儿子，十七八岁，“面目清秀，身材俊俏，轻裘宝带，美服华冠”(第6回)。他来荣府向凤姐借玻璃炕屏，婶侄之间说笑亲昵(第6回)。他和贾蔷替凤姐捉住贾瑞，逼他写了欠契，又泼了他一身屎尿(第12回)。妻子秦可卿死后，父亲替他捐了五品龙禁尉，好让丧礼风光(第13回)。祖父贾敬丧中，他撺掇贾琏偷娶尤二姐，自己也存着私心(第64回)；凤姐大闹宁国府，他跪在地下自己打嘴巴赔罪(第68回)。",
         "Jia Zhen’s son, seventeen or eighteen, handsome and finely dressed (ch. 6). He comes to borrow a glass screen from Xifeng, and aunt and nephew banter familiarly (ch. 6). With Jia Qiang he springs Xifeng’s trap on Jia Rui, forcing an IOU from him and drenching him in filth (ch. 12). When his wife Qin Keqing dies his father buys him a guard’s commission so her funeral can be grander (ch. 13). During his grandfather’s funeral he eggs Jia Lian on to marry You Erjie in secret, with designs of his own (ch. 64); when Xifeng storms the Ning mansion he kneels and slaps his own face to beg her pardon (ch. 68)."),
    late=("宁府被抄时，他和父亲一同被锦衣军带走(第105回)。",
          "When the Ning mansion is searched he is taken away with his father (ch. 105)."),
    icon=("年少俊俏，瓜皮小帽。", "A handsome youth in a skullcap.")),
  N(id="qinkeqing", zh="秦可卿", py="Qín Kěqīng", en="Qin Keqing", grp="ning", debut=5, dies=13,
    camps=[(5, "ning")], born=("秦", "Qin"),
    sub=("贾蓉之妻 · 金陵十二钗之一", "Jia Rong’s wife, one of the Twelve Beauties of Jinling"),
    bio=("营缮郎秦业从养生堂抱养的女儿，“生的形容袅娜，性格风流”(第8回)，是贾母“重孙媳中第一个得意之人”(第5回)。宝玉在她房中午睡，梦游太虚幻境，梦中警幻把乳名兼美、字可卿的妹妹许给了他(第5回)。第十回她卧病不起，张太医说她“心性高强，聪明不过”，思虑太过伤了脾。第十三回她托梦给凤姐，嘱咐趁着盛时在祖茔附近多置田庄，以防将来败落，又说“三春过后诸芳尽，各自须寻各自门”；随即传来她的死讯，“合家皆知，无不纳罕，都有些疑心”。宁府为她办了极其奢华的丧事，丫鬟瑞珠触柱而死。",
         "Adopted from a foundling home by the minor official Qin Ye, she grew up graceful and charming (ch. 8), and is Grandmother Jia’s favourite among her great-grandsons’ wives (ch. 5). Baoyu naps in her room and dreams of the Land of Illusion, where the fairy Disenchantment marries him to her own sister, also called Keqing (ch. 5). In chapter 10 she falls ill; the doctor says she is too proud and too clever, and has worried herself sick. In chapter 13 she appears to Xifeng in a dream, urging her to buy land by the family graves while times are good, against the day of ruin; then news comes that she has died, and “the whole household wondered, and had their suspicions”. The Ning mansion gives her a lavish funeral, and her maid Ruizhu dashes her head against a pillar."),
    late=("第一百一十一回，鸳鸯决意殉主时，看见一个女人拿着汗巾作上吊的样子，正是秦可卿；她说自己是太虚幻境里管风情月债的，来引鸳鸯同去。",
          "In chapter 111, as Yuanyang resolves to die, she sees a woman with a sash as if about to hang herself: it is Qin Keqing, who says she keeps the accounts of love in the Land of Illusion and has come to lead Yuanyang there."),
    icon=("云髻高挽，簪金凤，着绛红袄。", "Hair piled high with a golden phoenix pin, a deep red jacket.")),
  N(id="jiaqiang", zh="贾蔷", py="Jiǎ Qiáng", en="Jia Qiang", grp="ning", debut=9, dies=None,
    camps=[(9, "ning")],
    sub=("宁府正派玄孙 · 梨香院戏班的管事", "Of the main Ning line; manager of the girls’ opera troupe"),
    bio=("宁府正派玄孙，父母早亡，从小跟着贾珍过活，“比贾蓉生的还风流俊俏”，与贾蓉最相亲厚；因有人说闲话，贾珍才让他搬出宁府另住(第9回)。闹学堂时是他暗中挑唆茗烟出头(第9回)。为了元妃省亲，他到姑苏采买了十二个女孩子，在梨香院教戏(第16—18回)。他和小旦龄官相爱：龄官在蔷薇架下一遍遍地划“蔷”字(第30回)；他买了只会衔旗串戏台的雀儿哄她开心，龄官却说这是拿雀儿比她们，他当场把雀儿放了、笼子拆了(第36回)。",
         "Of the main Ning line, orphaned young and raised in Jia Zhen’s house; even handsomer than Jia Rong, and his closest friend, until gossip makes Jia Zhen move him out (ch. 9). In the school brawl it is he who quietly sets the page Mingyan on (ch. 9). For the Imperial Consort’s visit he goes to Suzhou to buy twelve girls and trains them as an opera troupe at Pear Fragrance Court (chs. 16–18). He and the actress Lingguan are in love: she scratches the character of his name in the earth again and again (ch. 30); he buys her a bird that performs on a toy stage, but when she says it is caged like the girls, he lets it go and tears the cage apart (ch. 36)."),
    late=("贾政出门后，他和贾芸、贾环等在外书房聚赌喝酒(第117回)。",
          "With Jia Zheng away he gambles and drinks in the outer study with Jia Yun, Jia Huan and their friends (ch. 117)."),
    icon=("瓜皮小帽，手提鸟笼。", "Skullcap, carrying a birdcage.")),
  N(id="youerjie", zh="尤二姐", py="Yóu Èrjiě", en="You Erjie", grp="ning", debut=63, dies=69,
    camps=[(63, "ning"), (65, "rong", "被贾琏偷娶为二房", "Secretly married by Jia Lian")],
    sub=("尤氏的继妹 · 贾琏的二房", "Madam You’s stepsister, Jia Lian’s secret second wife"),
    bio=("尤老娘的女儿，尤氏的继妹，早年就“指腹为婚”许给了张华(第64回)。贾敬丧中，贾琏看上了她，贾蓉从中撺掇，贾珍作主逼张华写了退婚书，贾琏在小花枝巷买了房子，偷偷娶她做了二房(第64—65回)。她“在先已和姐夫不妥”，如今一心只想做个本分人(第64—65回)。凤姐知道后，素服登门，装作贤良把她接进大观园(第68回)，又暗中唆使张华告状，让秋桐天天辱骂(第68—69回)；她怀的男胎被庸医胡君荣打了下来，终于吞金自尽(第69回)。",
         "Daughter of Madam You’s stepmother, betrothed before birth to Zhang Hua (ch. 64). During Jia Jing’s funeral Jia Lian falls for her; Jia Rong eggs him on, Jia Zhen forces Zhang Hua to give her up, and Jia Lian secretly marries her and sets her up in a house in Flower Lane (chs. 64–65). Once on easy terms with her sister’s husband, she now wants only to be a good wife (chs. 64–65). When Xifeng finds out, she calls on her in white, all kindness, and brings her into the garden (ch. 68); then she secretly sets Zhang Hua to sue and lets Qiutong abuse her daily (chs. 68–69). After a quack doctor causes her to lose the boy she is carrying, she swallows gold and dies (ch. 69)."),
    icon=("鬓边一朵小花，衣裙素淡。", "A small flower in her hair, pale clothes.")),
  N(id="yousanjie", zh="尤三姐", py="Yóu Sānjiě", en="You Sanjie", grp="ning", debut=63, dies=66,
    camps=[(63, "ning")],
    sub=("尤二姐之妹", "Erjie’s younger sister"),
    bio=("尤二姐的妹妹，容貌绝色，性情刚烈。贾珍、贾琏想轻薄她，她反客为主，借酒戏骂，把两人弄得“欲近不能，欲远不舍”(第65回)。她说五年前就看中了串戏的柳湘莲，非他不嫁，当众把一根玉簪击作两段，“一句不真，就如这簪子”，从此“非礼不动，非礼不言”(第65—66回)。柳湘莲以祖传的鸳鸯剑为定礼，回京后听说她是宁府里的人，起了疑心，来要回定礼；她在房中听见，摘下剑来，“右手回肘只往项上一横”，自刎而死(第66回)。",
         "Erjie’s sister, dazzlingly beautiful and fierce. When Jia Zhen and Jia Lian try to take liberties, she turns the tables, drinking and mocking them until they can neither come near nor tear themselves away (ch. 65). She declares she has loved the actor-gentleman Liu Xianglian for five years and will marry no one else; snapping a jade hairpin in two, she swears that if she lies she will be like the pin, and from then on behaves with perfect propriety (chs. 65–66). Liu gives his family’s twin swords as a pledge, but back in the capital he hears she belongs to the Ning household, grows suspicious and comes to take the pledge back. Hearing this, she draws the sword and cuts her own throat (ch. 66)."),
    icon=("手握鸳鸯剑。", "Holding the mandarin-duck sword.")),
  N(id="jiaoda", zh="焦大", py="Jiāo Dà", en="Jiao Da", grp="serv", debut=7, dies=None,
    camps=[(7, "ning")],
    sub=("宁府老仆", "An old servant of the Ning mansion"),
    bio=("从小跟着宁国公出过三四回兵，从死人堆里把主子背出来，没东西吃就偷来给主子吃，两日没水喝，“自己喝马溺”(第7回)。如今老了，仗着这些功劳，喝醉了谁都敢骂。第七回他被派夜里送秦钟回家，借酒大骂，骂到贾蓉头上，又嚷“每日家偷狗戏鸡，爬灰的爬灰，养小叔子的养小叔子”，被小厮们捆起来，塞了满嘴马粪。",
         "As a boy he went to war with the first Duke of Ning, carried his master out from among the dead, stole food for him and drank horse urine so that his master could have the water (ch. 7). Now old and proud of it, he abuses anyone when drunk. In chapter 7, sent to see Qin Zhong home at night, he rails even at Jia Rong and shouts that the house is full of incest and adultery, until the pages tie him up and stuff his mouth with horse dung."),
    late=("宁府被抄，焦大哭着说：“只有跟着太爷捆人的，那里倒叫人捆起来！”(第105回)",
          "When the Ning mansion is searched he weeps that he used to tie people up for the old masters, and now he is the one tied up (ch. 105)."),
    icon=("白发老仆，醉眼，敞着短褂。", "A white-haired old servant, drunk, his jacket open.")),
  N(id="xichun", zh="贾惜春", py="Jiǎ Xīchūn", en="Jia Xichun", grp="ning", debut=3, dies=None,
    camps=[(3, "ning"), (118, "kong", "带发修行", "Takes vows at home")],
    sub=("贾敬之女 · 贾珍之妹 · 四姑娘", "Jia Jing’s daughter, Jia Zhen’s sister: the fourth young lady"),
    bio=("宁府贾敬的女儿、贾珍的胞妹，自幼由贾母养在荣府，姊妹中年纪最小，黛玉初见时她“身量未足，形容尚小”(第3回)。她和来府里走动的小尼姑智能儿一处玩，笑说“我明儿也要剃了头同他作姑子去”(第7回)。她擅长绘画，贾母命她把大观园画成一幅画(第40、42回)。抄检大观园时，丫鬟入画箱里搜出男人的东西，她执意叫尤氏带走，又说“不但不要入画，如今我也大了，连我也不便往你们那边去了”，尤氏骂她“心冷口冷心狠意狠”(第74回)。",
         "Jia Jing’s daughter and Jia Zhen’s sister, raised by Grandmother Jia in the Rong mansion; the youngest of the girls, still small when Daiyu arrives (ch. 3). Playing with the little nun Zhineng, she laughs that she will shave her head and become a nun too (ch. 7). She paints, and Grandmother Jia asks her to paint the whole garden (chs. 40, 42). When men’s things are found in her maid Ruhua’s chest during the search of the garden, she insists Madam You take the girl away and says she will have nothing more to do with the Ning mansion; Madam You calls her cold and hard-hearted (ch. 74)."),
    late=("她和妙玉下棋谈禅(第87回)。贾府遭贼，妙玉被劫，她更坚定了出家的念头(第112回)，以死相逼，终于得到王夫人允许带发修行，紫鹃自愿跟去伺候(第115、117—118回)，后来栊翠庵就给她静修(第120回)，应了判词“独卧青灯古佛旁”。",
          "She plays chess and talks Zen with Miaoyu (ch. 87). After the robbery and Miaoyu’s abduction her mind is made up (ch. 112); threatening to die if refused, she wins Lady Wang’s consent to take vows at home, with Zijuan to serve her (chs. 115, 117–118), and is later given Green Bower Hermitage (ch. 120) — “alone by a dim lamp beside an old Buddha”, as her verse foretold."),
    icon=("素衣，手持画笔。", "Plain clothes, a painting brush in hand.")),

  # =============================================================== 荣国府 the Rong mansion
  N(id="jiamu", zh="贾母", py="Jiǎmǔ", en="Grandmother Jia", grp="rong", debut=3, dies=110,
    camps=[(3, "rong")], born=("史", "Shi"),
    sub=("史太君 · 荣国府的老祖宗", "The Lady Dowager, matriarch of the Rong mansion"),
    bio=("金陵史家的女儿，荣国公之子贾代善的妻子，府里上下叫她“老祖宗”。她最疼宝玉；女儿贾敏死后，又把外孙女黛玉接进府来，一见便搂入怀中大哭(第3回)。宝玉挨打，她赶来说“先打死我，再打死他，岂不干净了！”(第33回)。她两宴大观园，带着刘姥姥游园取乐(第40—41回)。贾赦想讨她的丫鬟鸳鸯做妾，她气得浑身乱战，连王夫人也一起数落，事后又向王夫人赔不是(第46回)。元宵夜宴上她“破陈腐旧套”，笑话才子佳人的戏文千篇一律(第54回)。",
         "Born into the Shi family of Jinling and widow of the Duke of Rong’s son, she is “the Old Ancestress” to the whole household. Baoyu is her darling; when her daughter Jia Min dies she brings her granddaughter Daiyu to live with her, and weeps as she takes her in her arms (ch. 3). When Jia Zheng beats Baoyu she arrives crying, “Kill me first, then him!” (ch. 33). She gives two feasts in the garden and shows Granny Liu around (chs. 40–41). When Jia She wants her maid Yuanyang as a concubine she shakes with rage and scolds even Lady Wang, then apologizes to her (ch. 46). At the Lantern Festival she makes fun of the stale plots of romances (ch. 54)."),
    late=("宝玉失玉疯癫，她同意凤姐的调包计，让宝玉娶宝钗冲喜；听说黛玉的病是为宝玉，她冷了心，说“咱们这种人家，别的事自然没有的，这心病也是断断有不得的”(第96—97回)。抄家后她散出多年的积蓄分给子孙(第107回)，第一百一十回寿终，享年八十三岁。",
          "When Baoyu loses his jade and his wits, she agrees to Xifeng’s plan to marry him to Baochai for luck; told that Daiyu is lovesick for Baoyu, she hardens her heart: in a family like theirs, she says, such feelings must not be (chs. 96–97). After the search she divides her savings among the family (ch. 107), and dies at eighty-three in chapter 110."),
    icon=("白发，戴抹额，拄龙头拐杖。", "White hair, a brocade headband and a dragon-headed cane.")),
  N(id="jiashe", zh="贾赦", py="Jiǎ Shè", en="Jia She", grp="rong", debut=2, dies=None,
    camps=[(2, "rong")],
    sub=("贾母长子 · 袭一等将军", "Grandmother Jia’s elder son, holder of the family title"),
    bio=("贾母的长子，袭着一等将军的爵位，却不住荣府正院，另在东边的院子里过活(第3回)。他贪财好色：想讨母亲的丫鬟鸳鸯做妾，鸳鸯当着贾母的面拿剪子铰头发拒绝(第46回)；为了石呆子的二十把古扇，让贾雨村诬石呆子拖欠官银，抄了扇子，贾琏说了一句不是，被他打得动不得(第48回)。他把女儿迎春许给了孙绍祖；孙绍祖后来说，是贾赦使了他五千两银子，“把你准折买给我的”(第79—80回)。",
         "Grandmother Jia’s elder son, who holds the family title but lives in a separate courtyard to the east (ch. 3). Greedy and lecherous, he wants his mother’s maid Yuanyang as a concubine, and she cuts off her hair before Grandmother Jia to refuse him (ch. 46); to get twenty antique fans he has Jia Yucun ruin their poor owner on a false charge, and beats his son Jia Lian senseless for objecting (ch. 48). He marries his daughter Yingchun to Sun Shaozu, who later says Jia She owed him five thousand taels and sold her to him to pay it (chs. 79–80)."),
    late=("抄家时查出他交通外官、恃强凌弱等罪，被发往台站效力赎罪(第105—107回)，后来遇赦回家(第120回)。",
          "The search turns up his dealings with provincial officials and his abuses of power, and he is sent to serve at a frontier post (chs. 105–107); he is pardoned and home again by chapter 120."),
    icon=("顶戴官帽，八字须，手持古扇。", "An official’s hat, a drooping moustache and an antique fan.")),
  N(id="xingfuren", zh="邢夫人", py="Xíng fūrén", en="Lady Xing", grp="rong", debut=3, dies=None,
    camps=[(3, "rong")], born=("邢", "Xing"),
    sub=("贾赦之妻", "Jia She’s wife"),
    bio=("贾赦的妻子，“禀性愚弱，只知承顺贾赦以自保，次则婪取财货为自得”(第46回)。贾赦要讨鸳鸯，她亲自去说媒，碰了钉子，还挨了贾母一顿数落(第46回)。她和儿媳凤姐不和：贾母八十大寿时，当众替得罪了尤氏的婆子向凤姐求情，给凤姐没脸(第71回)。迎春的乳母聚赌被罚，她反来责备迎春(第73回)。傻大姐捡到的绣春囊偏偏落到她手里，她把它封了送给王夫人，由此引出抄检大观园(第73—74回)。",
         "Jia She’s wife, “dull and weak, who keeps herself safe by obeying her husband and takes her pleasure in money” (ch. 46). She goes in person to win Yuanyang for Jia She, is rebuffed, and is scolded by Grandmother Jia for her pains (ch. 46). She and her daughter-in-law Xifeng do not get on: at Grandmother Jia’s eightieth birthday she pointedly asks Xifeng, in front of everyone, to release two women who had offended Madam You (ch. 71). When Yingchun’s nurse is caught gambling she blames Yingchun (ch. 73). It is she who receives the embroidered pouch found by Simple Sister, and she sends it sealed to Lady Wang — which leads to the search of the garden (chs. 73–74)."),
    late=("贾母丧事上她身为长房，死拿住银子不放，让凤姐处处掣肘(第110回)。贾琏出门后，她听信兄弟邢大舅和王仁、贾芸等人，要把孙女巧姐许给外藩做妾，多亏平儿和刘姥姥把巧姐藏到乡下(第118—119回)。",
          "At Grandmother Jia’s funeral, as wife of the senior line, she keeps a tight grip on the money and hobbles Xifeng (ch. 110). With Jia Lian away, her brother, Wang Ren and Jia Yun talk her into sending her granddaughter Qiaojie to a foreign prince as a concubine; Ping’er and Granny Liu hide the girl in the country (chs. 118–119)."),
    icon=("中年妇人，抹额，衣着素净。", "Middle-aged, a headband and sober clothes.")),
  N(id="jiazheng", zh="贾政", py="Jiǎ Zhèng", en="Jia Zheng", grp="rong", debut=2, dies=None,
    camps=[(2, "rong")],
    sub=("贾母次子 · 工部员外郎 · 宝玉之父", "Grandmother Jia’s younger son, an official; Baoyu’s father"),
    bio=("贾母的次子，“自幼酷喜读书”，皇上额外赐了个主事之衔，入部习学，后升员外郎(第2回)。宝玉周岁抓周，只抓脂粉钗环，他从此不喜欢这个儿子(第2回)。大观园落成，他带宝玉一路题对额，嘴上骂“畜生”，心里也暗暗称许(第17回)。元宵制灯谜，见女儿们的谜底尽是爆竹、算盘、风筝、海灯之类，觉得不祥，“心内愈思愈闷”(第22回)。宝玉结交琪官、金钏投井，贾环又进谗言，他把宝玉按在凳上打得半死，贾母赶来才罢手(第33回)。",
         "Grandmother Jia’s younger son, a lover of books since boyhood, given a post by special favour and later promoted (ch. 2). When the year-old Baoyu grabbed only rouge and hairpins from the objects laid out to test his future, his father took against him (ch. 2). When the garden is finished he takes Baoyu round to compose its inscriptions, calling him a beast while secretly admiring him (ch. 17). At the Lantern Festival his daughters’ riddles all turn out to be firecrackers, an abacus, a kite and a temple lamp — things that flare and vanish — and he grows uneasy (ch. 22). When he hears of Baoyu’s friendship with an actor and of Jinchuan’s death, with Jia Huan adding his slander, he has Baoyu held down and beats him almost to death, until Grandmother Jia arrives (ch. 33)."),
    late=("他外放江西粮道，被手下家人蒙蔽，遭参降职(第96、99—102回)；回京后家里被抄，他复袭了荣国府的世职(第105—107回)。他扶贾母灵柩南下安葬，回京途中在毗陵驿船头的雪影里看见一个光头赤脚、披着大红猩猩毡斗篷的人向他倒身下拜，正是宝玉；随后宝玉被一僧一道夹着飘然而去(第120回)。",
          "Posted to Jiangxi, he is deceived by his own servants and demoted (chs. 96, 99–102); back in the capital, after the family is searched, he inherits the Rong title (chs. 105–107). On his way back from burying his mother in the south, he sees in the falling snow at Piling a figure with a shaven head and bare feet, wrapped in a scarlet cloak, bowing to him: it is Baoyu, who then goes off between the monk and the Taoist (ch. 120)."),
    icon=("官帽长须，背手而立。", "An official’s hat and a long beard, hands behind his back.")),
  N(id="wangfuren", zh="王夫人", py="Wáng fūrén", en="Lady Wang", grp="rong", debut=3, dies=None,
    camps=[(3, "rong")], born=("王", "Wang"),
    sub=("贾政之妻 · 宝玉之母", "Jia Zheng’s wife, Baoyu’s mother"),
    bio=("金陵王家的女儿，王子腾和薛姨妈的姊妹，凤姐的姑母。她吃斋念佛，对黛玉说宝玉是她的“孽根祸胎”(第3回)。她平日“宽仁慈厚”，可一见丫鬟和宝玉调笑便勃然大怒：午睡时金钏和宝玉说笑，她翻身打了金钏一个嘴巴，把她撵了出去，金钏投井而死(第30、32回)。宝玉挨打后，袭人劝她设法叫宝玉搬出园子，她感动得叫袭人“我的儿”，从此每月从自己的月钱里给袭人二两银子一吊钱(第34、36回)。绣春囊事发，她听信王善保家的，抄检大观园，又亲自撵走晴雯、芳官、四儿等人(第74、77回)。",
         "Born into the Wang family of Jinling, sister of Wang Ziteng and Aunt Xue, aunt of Xifeng. A pious vegetarian, she warns Daiyu that Baoyu is the “root of all trouble” (ch. 3). Usually kind and mild, she is enraged by any flirtation with her son: when Jinchuan jokes with Baoyu while she naps, she slaps the girl and dismisses her, and Jinchuan drowns herself (chs. 30, 32). After the beating Xiren advises moving Baoyu out of the garden; touched, Lady Wang calls her “my child” and pays her a concubine’s allowance from her own purse (chs. 34, 36). When the embroidered pouch turns up she listens to Wang Shanbao’s wife, orders the garden searched, and in person dismisses Qingwen, Fangguan, Si’er and others (chs. 74, 77)."),
    late=("宝玉失玉后，她和贾母依了凤姐的调包计，让宝玉娶宝钗(第96—97回)。宝玉中举后出走，她哭得饮食不进，“命在垂危”(第119回)。",
          "After Baoyu loses the jade she and Grandmother Jia accept Xifeng’s plan to marry him to Baochai (chs. 96–97). When Baoyu disappears after the examination she cannot eat and almost dies of grief (ch. 119)."),
    icon=("手持念珠，鬓插珠钗。", "A rosary in hand, pearl hairpins.")),
  N(id="zhaoyiniang", zh="赵姨娘", py="Zhào yíniáng", en="Concubine Zhao", grp="rong", debut=20, dies=113,
    camps=[(20, "rong")],
    sub=("贾政之妾 · 探春与贾环之母", "Jia Zheng’s concubine, mother of Tanchun and Jia Huan"),
    bio=("贾政的妾，生了探春和贾环，在府里处处受人轻视，也处处惹人厌。她嫉恨宝玉和凤姐，写了五百两银子的欠契给马道婆，马道婆给了她两个纸人，叫她写上二人的生辰八字，自己在家作法，宝玉和凤姐当即发狂，几乎丧命(第25回)。兄弟赵国基死了，她嫌探春按旧例只给二十两丧银，跑去哭闹，说“如今你舅舅死了，你多给了二三十两银子，难道太太就不依你”，被探春顶了回去(第55回)。她为茉莉粉冒充蔷薇硝的事带头去打芳官，反被藕官、蕊官等小戏子围住撕打(第60回)。",
         "Jia Zheng’s concubine and mother of Tanchun and Jia Huan, looked down on by everyone and disliked for good reason. Hating Baoyu and Xifeng, she signs Mother Ma an IOU for five hundred taels, and Mother Ma bewitches the two with paper figures marked with their birth dates; both go mad and nearly die (ch. 25). When her brother dies and Tanchun, running the household, allows only the customary twenty taels for his funeral, she makes a scene: surely her daughter could spare more for her “uncle”? Tanchun stands firm (ch. 55). Over a packet of jasmine powder passed off as rose-nitre she goes to beat the actress Fangguan, and is mobbed by the other girls (ch. 60)."),
    late=("马道婆用魇魔法害人的事败露(第81回)。贾母灵柩停在铁槛寺时，她突然中邪，满嘴胡话，又自己撕开衣服，“好象有人剥他的样子”，闹了一夜后死去，人人都说她是被阴司拷打死的(第112—113回)。",
          "Mother Ma’s witchcraft is exposed (ch. 81). While Grandmother Jia’s coffin lies at Iron Threshold Temple, Concubine Zhao is suddenly possessed, raves, tears open her clothes as if someone were stripping her, and dies after a night of howling; everyone says she was tortured to death in the underworld (chs. 112–113)."),
    icon=("鬓边插红花，嘴角下撇。", "A red flower in her hair, the corners of her mouth turned down.")),
  N(id="jialian", zh="贾琏", py="Jiǎ Lián", en="Jia Lian", grp="rong", debut=2, dies=None,
    camps=[(2, "rong")],
    sub=("贾赦之子 · 凤姐之夫", "Jia She’s son, Xifeng’s husband"),
    bio=("贾赦的儿子，捐了个同知，帮着叔父贾政料理家务，“于世路上好机变，言谈去的”(第2回)。林如海病重，他护送黛玉回扬州，林如海死后又送她回京(第12—16回)。他好色成性：女儿出痘时和多姑娘鬼混，靠平儿瞒下一绺青丝(第21回)；凤姐生日那天和鲍二家的私通，被凤姐撞破，他拔剑要杀凤姐，闹到贾母跟前(第44回)；贾敬丧中他偷娶了尤二姐(第64—65回)，父亲把丫鬟秋桐赏给他做妾后，他又冷落了二姐(第69回)。",
         "Jia She’s son, who has bought a minor office and helps his uncle Jia Zheng run the household; clever in worldly matters and a smooth talker (ch. 2). When Lin Ruhai is dying he escorts Daiyu home and brings her back after the funeral (chs. 12–16). He is a lecher: while his daughter has smallpox he carries on with a servant’s wife, and Ping’er hides the lock of hair she left behind (ch. 21); on Xifeng’s birthday he is caught with Bao Er’s wife and draws a sword on Xifeng in front of Grandmother Jia (ch. 44); during Jia Jing’s funeral he secretly marries You Erjie (chs. 64–65), and then neglects her once his father gives him the maid Qiutong (ch. 69)."),
    late=("抄家时查出凤姐背着他放高利贷，他从此冷淡凤姐(第105—106回)。凤姐死后，平儿和刘姥姥救出巧姐，他越发敬重平儿，打算等父亲回来就把平儿扶正(第119回)。",
          "The search reveals that Xifeng has been lending money at interest behind his back, and he turns cold to her (chs. 105–106). After her death Ping’er and Granny Liu save Qiaojie, and he resolves to make Ping’er his wife (ch. 119)."),
    icon=("瓜皮帽，青缎马褂。", "A skullcap and a dark satin riding jacket.")),
  N(id="xifeng", zh="王熙凤", py="Wáng Xīfèng", en="Wang Xifeng", grp="rong", debut=3, dies=114,
    camps=[(3, "rong")], born=("王", "Wang"),
    sub=("贾琏之妻 · 荣府的管家奶奶", "Jia Lian’s wife, who runs the Rong household"),
    bio=("王子腾的侄女，王夫人的内侄女，“自幼假充男儿教养的，学名王熙凤”，贾母叫她“凤辣子”(第3回)。黛玉进府，众人都敛声屏气，只有她人还没到，笑声先到：“我来迟了，不曾迎接远客！”(第3回)。她替王夫人管着荣府，秦可卿死后又协理宁国府，赏罚分明(第13—14回)。小厮兴儿说她“嘴甜心苦，两面三刀，上头一脸笑，脚下使绊子，明是一盆火，暗是一把刀”(第65回)。她毒设相思局，害死了对她起淫心的贾瑞(第12回)；在铁槛寺收了三千两银子，拆散张金哥的婚事，逼死了一对未婚夫妻(第15—16回)；又把尤二姐赚进园中，借秋桐之手逼她吞金(第68—69回)。",
         "Wang Ziteng’s niece and Lady Wang’s, “brought up as a boy” and given a scholar’s name; Grandmother Jia calls her “Peppery Feng” (ch. 3). When Daiyu arrives, everyone is hushed except Xifeng, whose laugh arrives before she does: “I’m late to welcome our guest!” (ch. 3). She runs the Rong household for Lady Wang, and after Qin Keqing’s death the Ning household too, with strict rewards and punishments (chs. 13–14). A page describes her as “sweet of mouth and bitter of heart… a fire in the open and a knife in the dark” (ch. 65). She lures the lovesick Jia Rui to his death (ch. 12); for three thousand taels she breaks a girl’s betrothal at Iron Threshold Temple, and drives the young couple to suicide (chs. 15–16); she lures You Erjie into the garden and destroys her with a “borrowed sword” (chs. 68–69)."),
    late=("她献“掉包儿的法子”，瞒着宝玉让他娶宝钗(第96回)。抄家时查出她放债盘剥的借券，从此失势，贾琏也冷淡了她(第105—106回)；贾母丧事她手中无钱，处处不周，“力诎失人心”(第110回)。她病中托刘姥姥照看巧姐(第113回)，第一百一十四回病死，回目说她“历幻返金陵”。",
          "She devises the switch by which Baoyu is married to Baochai (ch. 96). The search uncovers her moneylending, and she loses her power and her husband’s regard (chs. 105–106); short of money for Grandmother Jia’s funeral, she can no longer command the household (ch. 110). Ill, she entrusts Qiaojie to Granny Liu (ch. 113), and dies in chapter 114, “returning to Jinling”."),
    icon=("金丝八宝攒珠髻，朝阳五凤挂珠钗，缕金百蝶穿花大红袄(第3回)。", "A gold and pearl headdress with five phoenixes, and a red jacket with gold butterflies, as in chapter 3.")),
  N(id="liwan", zh="李纨", py="Lǐ Wán", en="Li Wan", grp="rong", debut=3, dies=None,
    camps=[(3, "rong")], born=("李", "Li"),
    sub=("贾珠的遗孀 · 贾兰之母", "Widow of Jia Zhu, mother of Jia Lan"),
    bio=("国子监祭酒李守中的女儿，嫁给贾政的长子贾珠，贾珠早死，留下儿子贾兰(第4回)。她“虽青春丧偶，居家处膏粱锦绣之中，竟如槁木死灰一般”，只知侍亲养子，陪小姑们针黹诵读(第4回)。大观园里她住稻香村，诗社她自荐掌坛，号“稻香老农”(第37回)。凤姐病时，她和探春、宝钗一起理家(第55—56回)。",
         "Daughter of a chancellor of the Imperial Academy, married to Jia Zheng’s eldest son Jia Zhu, who died young leaving her with a son, Jia Lan (ch. 4). Though widowed young and surrounded by luxury, she lives “like dead wood and cold ashes”, caring only for her elders and her son and keeping the girls company at their needlework and books (ch. 4). In the garden she lives at Sweet-rice Village and presides over the poetry club as “the Old Farmer” (ch. 37). When Xifeng falls ill she runs the household with Tanchun and Baochai (chs. 55–56)."),
    late=("黛玉临终时，众人都在忙宝玉的婚事，只有她和探春、紫鹃守在潇湘馆(第97—98回)。贾兰中举(第119回)，应了判词“到头谁似一盆兰”。",
          "While everyone else is busy with Baoyu’s wedding, she, Tanchun and Zijuan stay with the dying Daiyu (chs. 97–98). Her son passes the examination (ch. 119), as her verse foretold."),
    icon=("素服无珠翠，手持书卷。", "Plain clothes without jewels, a book in hand.")),
  N(id="yuanchun", zh="贾元春", py="Jiǎ Yuánchūn", en="Jia Yuanchun", grp="rong", debut=2, dies=95,
    camps=[(2, "gong")],
    sub=("贾政长女 · 贤德妃", "Jia Zheng’s eldest daughter, the Imperial Consort"),
    bio=("贾政的长女，生在大年初一，所以叫元春(第2回)。她“因贤孝才德，选入宫作女史”(第2回)；入宫前亲自教宝玉读书识字，“其名分虽系姊弟，其情状有如母子”(第18回)。第十六回她晋封凤藻宫尚书，加封贤德妃；为了她回家省亲，贾府修了大观园。元宵省亲那夜，她“满眼垂泪”，对祖母和母亲说“当日既送我到那不得见人的去处”，又隔帘对父亲说“田舍之家，虽齑盐布帛，终能聚天伦之乐”(第18回)。回宫后她命宝玉和姊妹们住进园中(第23回)。端午节的赏赐，只有宝玉和宝钗的一样(第28回)。",
         "Jia Zheng’s eldest daughter, born on New Year’s Day, hence her name, “first spring” (ch. 2). She entered the palace as a lady-in-waiting for her virtue and talent (ch. 2); before that she had taught Baoyu to read, “a sister in name, a mother in fact” (ch. 18). In chapter 16 she is raised to Imperial Consort, and the family builds the garden for her visit home. On the night of the visit she weeps, telling her grandmother and mother that they sent her “to a place where no one may be seen”, and telling her father, through a curtain, that a farmer’s family has at least the joy of being together (ch. 18). Back in the palace she orders Baoyu and the girls to live in the garden (ch. 23). Her festival gifts are the same for Baoyu and Baochai alone (ch. 28)."),
    late=("第八十三回她在宫中染恙；第九十五回因“痰气壅塞”薨逝，应了判词“虎兕相逢大梦归”。",
          "She falls ill in the palace in chapter 83 and dies in chapter 95, “when tiger meets rhinoceros”, as her verse said."),
    icon=("凤冠霞帔。", "Phoenix crown and embroidered cape.")),
  N(id="yingchun", zh="贾迎春", py="Jiǎ Yíngchūn", en="Jia Yingchun", grp="rong", debut=3, dies=109,
    camps=[(3, "rong"), (79, "out", "嫁给孙绍祖", "Married to Sun Shaozu")],
    sub=("贾赦之女 · 二姑娘", "Jia She’s daughter, the second young lady"),
    bio=("贾赦的妾所生，“温柔沉默，观之可亲”(第3回)，下人叫她“二木头”，“戳一针也不知嗳哟一声”(第65回)。她的攒珠累丝金凤被乳母拿去典了做赌本，丫鬟们为此争吵，她也不追问，只在旁边看《太上感应篇》(第73回)。抄检大观园时，她的丫鬟司棋箱子里搜出表弟潘又安的情书(第74回)；司棋被撵，她也不替司棋说一句话(第77回)。贾赦把她许给了孙绍祖(第79回)；回娘家时她哭诉孙绍祖“一味好色，好赌酗酒”，又说他骂她是贾赦使了他五千银子“准折买给我的”(第80回)。",
         "Jia She’s daughter by a concubine, “gentle and quiet, easy to like” (ch. 3); the servants call her “Wooden Second”, who wouldn’t say ouch if you stuck a needle in her (ch. 65). When her nurse pawns her gold phoenix to gamble, she doesn’t pursue it, and reads a book of moral tracts while her maids argue (ch. 73). Her maid Siqi is found with love letters from her cousin (ch. 74), and when Siqi is dismissed Yingchun says nothing for her (ch. 77). Her father marries her to Sun Shaozu (ch. 79); home on a visit, she weeps that her husband is a lecher, gambler and drunkard who says she was sold to him to pay her father’s debt (ch. 80)."),
    late=("她最后一次回贾府时对贾母说“我只是没有再来的时候了”，不久便被孙绍祖折磨致死，应了判词“金闺花柳质，一载赴黄粱”(第109回)。",
          "On her last visit she tells her grandmother she will never come again, and soon dies of her husband’s cruelty — “within a year”, as her verse said (ch. 109)."),
    icon=("低头，手持《太上感应篇》。", "Head bowed, holding a book of moral tracts.")),
  N(id="tanchun", zh="贾探春", py="Jiǎ Tànchūn", en="Jia Tanchun", grp="rong", debut=3, dies=None,
    camps=[(3, "rong"), (102, "out", "远嫁海疆", "Married far away on the coast")],
    sub=("贾政与赵姨娘之女 · 三姑娘", "Daughter of Jia Zheng and Concubine Zhao, the third young lady"),
    bio=("赵姨娘所生，“削肩细腰，长挑身材，鸭蛋脸面，俊眼修眉，顾盼神飞，文彩精华，见之忘俗”(第3回)。她发起海棠诗社，号“蕉下客”(第37回)。凤姐病时她代管家务，按旧例只给生母的兄弟二十两丧银，不肯徇私(第55回)；又把园子分给婆子们承包，兴利除弊(第56回)。抄检大观园，她秉烛开门等候，说“这样大族人家，若从外头杀来，一时是杀不死的……必须先从家里自杀自灭起来，才能一败涂地”；王善保家的仗势掀她的衣襟，她当场打了一记耳光(第74回)。",
         "Concubine Zhao’s daughter, tall and slender, with bright eyes and a lively, striking face (ch. 3). She founds the Crabflower poetry club (ch. 37). Running the household while Xifeng is ill, she allows her own mother’s brother only the customary funeral money (ch. 55), and leases the garden plots to the servants to cut waste (ch. 56). When the searchers come she waits with the lamps lit: a great family, she says, cannot be destroyed from outside — it must first destroy itself from within. When Wang Shanbao’s wife lifts her jacket in mock search, Tanchun slaps her face (ch. 74)."),
    late=("贾政在外任上把她许给镇守海疆的周家(第99—100回)，第一百零二回远嫁，应了判词里“清明涕送江边望，千里东风一梦遥”。宝玉中举出走后，她随夫家回京探亲(第119回)。",
          "Her father betroths her to the son of a coastal commander (chs. 99–100), and she sails away in chapter 102, as her verse said. She returns on a visit after Baoyu disappears (ch. 119)."),
    icon=("身旁一只风筝。", "A kite beside her.")),
  N(id="baoyu", zh="贾宝玉", py="Jiǎ Bǎoyù", en="Jia Baoyu", grp="rong", debut=1, dies=None,
    camps=[(1, "rong"), (120, "kong", "随一僧一道而去", "Leaves with the monk and the Taoist")],
    sub=("贾政与王夫人之子 · 衔玉而生", "Son of Jia Zheng and Lady Wang, born with a jade in his mouth"),
    bio=("女娲补天剩下的一块顽石，被一僧一道携入红尘；又说他前身是赤瑕宫的神瑛侍者，曾以甘露浇灌绛珠仙草(第1回)。他生下来嘴里衔着一块五彩晶莹的玉，抓周时只抓脂粉钗环，七八岁时说“女儿是水作的骨肉，男人是泥作的骨肉”(第2回)。他厌恶读书做官，把讲仕途经济的人叫作“禄蠹”(第19、32回)，却对园中女孩子个个用心。他在秦可卿房中梦游太虚幻境(第5回)，住进大观园的怡红院(第23回)，号“绛洞花主”“怡红公子”(第37回)。为了琪官和金钏的事，他被父亲打得半死(第33回)；晴雯被逐而死，他写了《芙蓉女儿诔》祭她(第78回)。",
         "A stone left over when the goddess Nüwa mended the sky, carried into the world by a monk and a Taoist; or, in another telling, the attendant Shenying, who watered the Crimson Pearl flower with dew (ch. 1). He was born with a jade in his mouth, grabbed only rouge and hairpins at his first birthday, and at seven or eight declared that girls are made of water and men of mud (ch. 2). He loathes study and officialdom, calling careerists “salary-worms” (chs. 19, 32), and cares for every girl in the garden. He dreams of the Land of Illusion in Qin Keqing’s room (ch. 5), moves into the garden’s Red Delight Court (ch. 23) and takes the pen names “Lord of the Crimson Cave” and “Prince of Red Delight” (ch. 37). Over the actor Qiguan and the maid Jinchuan his father beats him almost to death (ch. 33); when Qingwen dies, wronged, he writes a dirge for her (ch. 78)."),
    late=("他失了通灵玉，神志昏乱，在不知情中娶了宝钗，黛玉在同一时刻死去(第94—98回)。后来和尚送回通灵玉，他魂游太虚幻境，渐渐看破(第115—116回)。第一百一十九回他与侄子贾兰同中乡试，出了考场便不知去向；贾政在毗陵驿船头的雪影里见他光头赤脚、披着大红猩猩毡斗篷，向父亲拜了四拜，随一僧一道而去(第120回)。皇上听说后，赏了他一个“文妙真人”的道号(第120回)。",
          "He loses his jade and his wits, is married to Baochai without knowing it, and at that hour Daiyu dies (chs. 94–98). When a monk returns the jade his spirit revisits the Land of Illusion, and he begins to see through the world (chs. 115–116). In chapter 119 he and his nephew Jia Lan pass the provincial examination together, and he walks out of the examination hall and vanishes. In the snow at Piling his father sees him, head shaven and feet bare in a scarlet cloak, bow four times and go off between the monk and the Taoist (ch. 120). The emperor grants him a Taoist title (ch. 120)."),
    icon=("束发嵌宝紫金冠，二龙抢珠金抹额，项上挂着通灵宝玉(第3回)。", "A jewelled cap of purple gold, a gold headband with two dragons, and the jade at his neck (ch. 3).")),
  N(id="jiahuan", zh="贾环", py="Jiǎ Huán", en="Jia Huan", grp="rong", debut=20, dies=None,
    camps=[(20, "rong")],
    sub=("贾政与赵姨娘之子", "Son of Jia Zheng and Concubine Zhao"),
    bio=("探春的同母弟弟，“人物委琐，举止荒疏”(第23回)。他和莺儿掷骰子赖账，被宝玉打发走，回去又挨赵姨娘一顿骂(第20回)。他嫉恨宝玉，在王夫人房里抄经时故意推倒蜡灯，把滚热的蜡油泼在宝玉脸上(第25回)；金钏投井后，他对贾政说是宝玉“强奸不遂”逼死的，引来宝玉一顿毒打(第33回)。王夫人房里的彩霞和他相好(第25、72回)。",
         "Tanchun’s full brother, mean in looks and manners (ch. 23). He cheats the maid Ying’er at dice, is sent away by Baoyu, and is scolded again by his mother (ch. 20). Jealous of Baoyu, he knocks over a candle while copying sutras in Lady Wang’s room and splashes hot wax over Baoyu’s face (ch. 25); after Jinchuan’s death he tells his father that Baoyu tried to force himself on her, bringing on Baoyu’s beating (ch. 33). Lady Wang’s maid Caixia is fond of him (chs. 25, 72)."),
    late=("他去看出痘的巧姐，碰翻了药铞子，凤姐大骂，母子更结了怨(第84回)。贾政出门、凤姐死后，他和舅舅王仁、贾芸等串通，要把巧姐卖给外藩王爷(第117—119回)。",
          "Visiting the sick Qiaojie, he knocks over her medicine and Xifeng curses him and his mother (ch. 84). With Jia Zheng away and Xifeng dead, he plots with her brother Wang Ren and Jia Yun to sell Qiaojie to a foreign prince (chs. 117–119)."),
    icon=("瓜皮帽，斜着眼睛。", "Skullcap, a sidelong look.")),
  N(id="jialan", zh="贾兰", py="Jiǎ Lán", en="Jia Lan", grp="rong", debut=4, dies=None,
    camps=[(4, "rong")],
    sub=("贾珠与李纨之子", "Son of Jia Zhu and Li Wan"),
    bio=("李纨的独子，父亲贾珠早死，五岁已入学读书(第4回)。闹学堂时他劝贾菌不要惹事(第9回)。他拿着小弓在园中追鹿，说“这会子不念书，闲着作什么？所以演习演习骑射”(第26回)。",
         "Li Wan’s only son, whose father died young; at five he is already at school (ch. 4). In the school brawl he tries to keep his friend Jia Jun out of trouble (ch. 9). He chases a deer through the garden with a little bow: with no lessons today, he says, he is practising archery (ch. 26)."),
    late=("第一百一十九回与宝玉同中乡试，宝玉第七名，他第一百三十名。",
          "In chapter 119 he passes the provincial examination with Baoyu: Baoyu seventh, Jia Lan one hundred and thirtieth."),
    icon=("小小少年，手持小弓。", "A boy with a little bow.")),
  N(id="qiaojie", zh="巧姐", py="Qiǎojiě", en="Qiaojie", grp="rong", debut=7, dies=None,
    camps=[(7, "rong"), (120, "out", "许配乡下周家", "Betrothed to a country family")],
    sub=("贾琏与凤姐之女", "Daughter of Jia Lian and Xifeng"),
    bio=("凤姐的女儿，原叫大姐儿(第7回)。她小时出过痘疹(第21回)。她生在七月初七，凤姐请刘姥姥给她取名，刘姥姥取了“巧哥儿”，说“以毒攻毒，以火攻火”，“必然是遇难成祥，逢凶化吉，却从这‘巧’字上来”(第42回)。",
         "Xifeng’s daughter, at first just called “Eldest Daughter” (ch. 7); she has smallpox as a small child (ch. 21). Born on the seventh of the seventh month, an unlucky day, she is named by Granny Liu, who chooses a name meaning “Lucky” to fight fire with fire: she will meet disaster and turn it to good fortune (ch. 42)."),
    late=("凤姐临死把她托付给刘姥姥(第113回)。贾琏出门后，舅舅王仁和贾环、贾芸等串通，要把她卖给外藩王爷做妾，平儿和刘姥姥连夜把她藏到乡下(第118—119回)；后来许给乡下一户姓周的财主人家，应了判词“偶因济刘氏，巧得遇恩人”(第119—120回)。",
          "Dying, Xifeng entrusts her to Granny Liu (ch. 113). With Jia Lian away, her uncle Wang Ren, Jia Huan and Jia Yun plot to sell her to a foreign prince; Ping’er and Granny Liu spirit her away to the country (chs. 118–119), where she is betrothed to the son of a rich farmer named Zhou — “because she once helped a woman named Liu”, as her verse said (chs. 119–120)."),
    icon=("小女孩，手持纺锤。", "A little girl holding a spindle.")),
  N(id="jiarui", zh="贾瑞", py="Jiǎ Ruì", en="Jia Rui", grp="rong", debut=9, dies=12,
    camps=[(9, "rong")],
    sub=("塾师贾代儒之孙", "Grandson of the clan schoolmaster Jia Dairu"),
    bio=("贾家族中塾师贾代儒的孙子，父母早亡。代儒有事时由他代管学堂，他“最是个图便宜没行止的人”，闹学堂时偏袒金荣(第9回)。宁府家宴上他在园中撞见凤姐，起了淫心(第11回)。凤姐两次假意约他：一次在穿堂里冻了一夜，一次被贾蓉、贾蔷捉住，写了欠契，又被泼了一身屎尿(第12回)。他相思成疾，跛足道人给他一面“风月宝鉴”，嘱咐只照背面；他偏照正面，在镜中与凤姐相会，终于一命呜呼(第12回)。",
         "Grandson of the clan schoolmaster, orphaned young. He runs the school when his grandfather is away, greedy and unprincipled, and takes Jin Rong’s side in the brawl (ch. 9). At a feast in the Ning garden he accosts Xifeng and is consumed by desire (ch. 11). Twice she pretends to meet him: once he freezes all night in a passage, then Jia Rong and Jia Qiang catch him, force an IOU from him and pour filth over him (ch. 12). Sick with longing, he is given a two-sided mirror by a lame Taoist and told to look only at its back; he looks at the front, where Xifeng beckons him in, and dies (ch. 12)."),
    icon=("手持风月宝鉴。", "Holding the two-sided Mirror of Love.")),
  N(id="jiayun", zh="贾芸", py="Jiǎ Yún", en="Jia Yun", grp="rong", debut=24, dies=None,
    camps=[(24, "rong")],
    sub=("贾家旁支的穷子弟", "A poor young man of the Jia clan"),
    bio=("后廊上住的五嫂子的儿子，家境贫寒，“生得着实斯文清秀”(第24回)。宝玉说他“倒象我的儿子”，他便顺口认了宝玉做父亲(第24回)。为了谋个差事，他向舅舅卜世仁赊香料不成，倒是街坊泼皮“醉金刚”倪二借了他银子；他买了冰片麝香送给凤姐，得了在大观园种树的差事(第24回)。他捡到小红丢的手帕，两人借坠儿暗通心意(第24、26回)。",
         "Son of a poor widow of the clan, refined and good-looking (ch. 24). When Baoyu says he looks like his son, Jia Yun promptly adopts Baoyu as his “father” (ch. 24). Looking for work, he is refused credit by his own uncle but lent money by the local tough, the “Drunken Diamond” Ni Er; with it he buys borneol and musk for Xifeng and gets the job of planting trees in the garden (ch. 24). He picks up a handkerchief dropped by the maid Xiaohong, and the two exchange feelings through a go-between (chs. 24, 26)."),
    late=("后来他和贾环、王仁等人串通，要把巧姐卖给外藩(第117—119回)。",
          "Later he joins Jia Huan and Wang Ren in the plot to sell Qiaojie to a foreign prince (chs. 117–119)."),
    icon=("青布长衫，手捧锦盒。", "A plain gown, holding a gift box.")),
]
