# -*- coding: utf-8 -*-
"""Dream of the Red Chamber: people outside the households — friends, officials, clergy and the immortals who frame
the story. Fields as in nodes_jia.py."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import N  # noqa: E402

NODES_OUT = [
  N(id="jinghuan", zh="警幻仙姑", py="Jǐnghuàn xiāngū", en="Fairy Disenchantment", grp="out", debut=1, dies=None,
    camps=[(1, "kong")],
    sub=("太虚幻境的主人", "Mistress of the Land of Illusion"),
    bio=("“居离恨天之上，灌愁海之中”，放春山遣香洞太虚幻境的仙姑，“司人间之风情月债，掌尘世之女怨男痴”(第5回)。一僧一道要把顽石带到她宫中“交割清楚”(第1回)。宝玉在秦可卿房中入梦，她带他看“金陵十二钗”的正副册，命舞女演唱《红楼梦》十二支曲，又把妹妹兼美许配给他，盼他从此“改悟前情，留意于孔孟之间，委身于经济之道”(第5回)。",
         "The fairy who lives “above the Sky of Parting Sorrow, amid the Sea of Brimming Grief”, in charge of the loves and griefs of the mortal world (ch. 5). The monk and the Taoist take the stone to her palace to hand it over (ch. 1). In Baoyu’s dream she shows him the registers of the Twelve Beauties of Jinling, has the twelve songs of the Dream of the Red Chamber performed, and gives him her sister in marriage, hoping that, once disillusioned with love, he will turn to the classics and to the world’s affairs (ch. 5)."),
    late=("宝玉魂魄再游太虚幻境，重看册子(第116回)；全书结尾，甄士隐把香菱的魂魄送到太虚幻境，交她“对册”(第120回)。",
          "Baoyu’s spirit visits her realm again and rereads the registers (ch. 116); at the end Zhen Shiyin brings Xiangling’s spirit to her to be checked against the registers (ch. 120)."),
    icon=("仙衣飘带，手捧册籍。", "Fairy robes with flowing ribbons, holding the registers.")),
  N(id="sengdao", zh="一僧一道", py="Yī sēng yī dào", en="The Monk and the Taoist", grp="out", debut=1, dies=None,
    camps=[(1, "kong")],
    sub=("茫茫大士与渺渺真人", "The Boundless Buddhist and the Infinite Taoist"),
    bio=("一个癞头跣脚的和尚，一个跛足蓬头的道士，即茫茫大士、渺渺真人。他们把女娲补天剩下的顽石变成扇坠大小的美玉，携入红尘(第1回)。他们在书中时隐时现：和尚说甄士隐抱着的英莲是“有命无运，累及爹娘之物”，道士唱《好了歌》度走了甄士隐(第1回)；宝钗的冷香丸方子和金锁上的吉利话都是和尚给的(第7—8回)；跛足道人送贾瑞风月宝鉴(第12回)；宝玉、凤姐中了魇魔法，二人来把通灵玉持诵一番，救了他们(第25回)；柳湘莲随之出家的那个道士，也常被认为就是他(第66回)。",
         "A scabby-headed, barefoot monk and a lame, tousled Taoist — immortals in disguise. They turn the stone left over from the mending of the sky into a little jade and carry it into the world (ch. 1). They come and go through the book: the monk warns that the infant Yinglian will bring her parents grief, and the Taoist’s song carries Zhen Shiyin away (ch. 1); the monk gave Baochai her pill recipe and the words on her locket (chs. 7–8); the Taoist gives Jia Rui the fatal mirror (ch. 12); when Baoyu and Xifeng are bewitched the pair arrive and chant over the jade to save them (ch. 25); the Taoist whom Liu Xianglian follows out of the world is often taken to be him (ch. 66)."),
    late=("宝玉失玉病危，和尚送回了玉，又引宝玉魂游太虚幻境(第115—116回)；宝玉中举后随二人而去，贾政在雪地里看见了这一幕(第120回)。",
          "When Baoyu is dying without his jade, the monk brings it back and leads his spirit to the Land of Illusion (chs. 115–116). After the examination Baoyu leaves with them, and his father sees them go in the snow (ch. 120)."),
    icon=("一个癞头和尚，一个跛足道士。", "A scabby-headed monk and a lame Taoist.")),
  N(id="shiyin", zh="甄士隐", py="Zhēn Shìyǐn", en="Zhen Shiyin", grp="out", debut=1, dies=None,
    camps=[(1, "kong")],
    sub=("姑苏乡宦 · 英莲之父", "A gentleman of Suzhou, Yinglian’s father"),
    bio=("姑苏阊门外十里街仁清巷的乡宦，“禀性恬淡，不以功名为念”(第1回)。他午睡时梦见一僧一道携着一块美玉去太虚幻境挂号，醒来在街上遇见二人(第1回)。他资助穷书生贾雨村进京赶考；元宵节女儿英莲被拐，三月十五葫芦庙失火，烧光了家产，投奔岳丈封肃又受尽冷眼(第1回)。一天他听见跛足道人唱《好了歌》，替它作了一篇注解，便随道人飘然而去(第1回)。",
         "A country gentleman of Suzhou, “content and indifferent to fame” (ch. 1). Napping, he dreams of the monk and the Taoist carrying a jade to the Land of Illusion, and on waking meets them in the street (ch. 1). He pays for the poor scholar Jia Yucun to go to the examinations; then his daughter is kidnapped at the Lantern Festival, fire from the Gourd Temple burns his house, and his father-in-law treats him with contempt (ch. 1). Hearing the lame Taoist sing the Song of Good-and-Done, he writes a commentary on it and walks away with him (ch. 1)."),
    late=("贾雨村在急流津的一座破庙里遇见他，认出了他，他却不肯说破(第103回)。全书结尾，他再遇雨村，“详说太虚情”，又把香菱度回太虚幻境(第120回)。",
          "Jia Yucun comes upon him in a ruined temple by a ferry and knows him, but Shiyin will not admit who he is (ch. 103). At the end they meet again, and Shiyin explains the Land of Illusion and leads Xiangling’s spirit home (ch. 120)."),
    icon=("道袍，手持拂尘。", "A Taoist robe and a fly whisk.")),
  N(id="jiaoxing", zh="娇杏", py="Jiāoxìng", en="Jiaoxing", grp="out", debut=1, dies=None,
    camps=[(1, "out")],
    sub=("甄家的丫鬟 · 后为雨村夫人", "A maid of the Zhens, later Yucun’s wife"),
    bio=("甄家的丫鬟。贾雨村在甄家书房外看见她撷花，她回头看了雨村两次，雨村便以为她有意于己(第1回)。雨村做了知府，向封肃讨她做二房，一年后生了儿子，又赶上正室病死，便被扶为正室夫人(第2回)。书中说她“偶因一着错，便为人上人”。",
         "A maid in the Zhen house. Jia Yucun sees her picking flowers and she looks back at him twice, which he takes as admiration (ch. 1). Become a prefect, he asks for her as a concubine; she bears him a son, his wife dies, and she becomes his lady (ch. 2) — “one chance glance, and she rose above everyone”."),
    icon=("丫鬟回首。", "A maid looking back over her shoulder.")),
  N(id="yucun", zh="贾雨村", py="Jiǎ Yǔcūn", en="Jia Yucun", grp="out", debut=1, dies=None,
    camps=[(1, "out")],
    sub=("名化，字时飞 · 由穷书生做到大官", "A poor scholar who rises high"),
    bio=("胡州人，寄居姑苏葫芦庙卖字为生，甄士隐送他五十两银子和两套冬衣，资助他进京赶考(第1回)。他中了进士，做了知府，因“恃才侮上”被革职，到林如海家做西宾，教黛玉读书(第2回)；托林如海的荐书投到贾政门下，复了官，补授应天府(第3回)。上任第一桩案子就是薛蟠打死冯渊：他明知被拐的英莲正是恩人甄士隐的女儿，却听了门子的话，“徇情枉法，胡乱判断了此案”，事后又寻了个不是，把门子远远充发了(第4回)。他还替贾赦夺了石呆子的古扇(第48回)。",
         "A Huzhou man living at the Gourd Temple in Suzhou and selling his calligraphy, until Zhen Shiyin gives him fifty taels and winter clothes for the journey to the examinations (ch. 1). He passes, becomes a prefect, is dismissed for arrogance, and becomes Daiyu’s tutor in Lin Ruhai’s house (ch. 2); with Lin’s letter to Jia Zheng he is restored to office as prefect of Yingtian (ch. 3). His first case is Xue Pan’s killing of Feng Yuan: knowing that the kidnapped girl is his benefactor’s daughter, he still twists the law to please the powerful, and later has the clerk who advised him exiled on a pretext (ch. 4). He also seizes a poor man’s antique fans for Jia She (ch. 48)."),
    late=("他做到京兆府尹，在急流津遇见已经出家的甄士隐，认出了他，士隐却不肯相认(第103回)。后来他犯了贪婪索诈的案子，遇赦褫籍为民，在急流津觉迷渡口再遇甄士隐，听他“详说太虚情”；随后他在草庵中睡着，被空空道人叫醒，便指点空空道人把《石头记》托给曹雪芹传述(第120回)。",
          "Become governor of the capital, he meets Zhen Shiyin, now a Taoist, at a ferry and knows him, but Shiyin will not acknowledge him (ch. 103). Later convicted of extortion and pardoned as a commoner, he meets Shiyin there again and hears the whole story of the Land of Illusion; then, asleep in a hut, he is woken by the Taoist Vanitas and sends him to Cao Xueqin with the Story of the Stone (ch. 120)."),
    icon=("乌纱官帽，八字胡。", "An official’s hat and a moustache.")),
  N(id="fengyuan", zh="冯渊", py="Féng Yuān", en="Feng Yuan", grp="out", debut=4, dies=4,
    camps=[(4, "out")],
    sub=("金陵小乡宦之子", "Son of a minor gentleman in Jinling"),
    bio=("父母俱亡，略有些薄产，平生“酷爱男风，最厌女子”，偏偏一眼看上了拐子卖的英莲，立誓再不交结男子，也不再娶第二个，择定三日后过门(第4回)。拐子又偷偷把英莲卖给薛蟠，冯渊来夺人，被薛家的豪奴打得半死，抬回家三日就死了(第4回)。",
         "An orphan of small means who had cared only for boys, until he sees the kidnapped Yinglian and vows to give up his old ways and take no other wife; he fixes the wedding for three days later (ch. 4). The kidnapper sells her again to Xue Pan, and when Feng Yuan comes to claim her, Xue Pan’s men beat him so badly that he dies three days later (ch. 4)."),
    icon=("年轻公子。", "A young gentleman.")),
  N(id="liulaolao", zh="刘姥姥", py="Liú lǎolao", en="Granny Liu", grp="out", debut=6, dies=None,
    camps=[(6, "out")],
    sub=("乡下来的老寡妇", "An old countrywoman"),
    bio=("女婿王狗儿的祖上和王家连过宗，家里过冬没了着落，她带着外孙板儿到荣府碰运气(第6回)。经周瑞家的引见，凤姐给了她二十两银子(第6回)。后来她送瓜果菜蔬来谢，贾母留她住下(第39回)，带她游大观园：开席时她高声说“老刘，老刘，食量大似牛，吃一个老母猪不抬头”，逗得众人笑倒(第40回)；喝醉了误入宝玉的卧房睡了一觉(第41回)。她给凤姐的女儿取名巧姐，满载而归(第42回)。",
         "Her son-in-law’s family once claimed kinship with the Wangs, so, with nothing for the winter, she takes her grandson to the Rong mansion to try her luck (ch. 6). Zhou Rui’s wife takes her to Xifeng, who gives her twenty taels (ch. 6). Later she brings country produce to say thanks; Grandmother Jia keeps her (ch. 39) and shows her the garden, where she plays the clown — “Old Liu, old Liu, eats like an ox, gobbles a sow and won’t look up!” (ch. 40) — and gets drunk and falls asleep in Baoyu’s bed (ch. 41). She names Xifeng’s daughter and goes home laden with gifts (ch. 42)."),
    late=("凤姐临终把巧姐托付给她(第113回)；王仁、贾环等要卖巧姐，她把巧姐和平儿藏到乡下，又替巧姐说成了周家的亲事(第119—120回)。",
          "The dying Xifeng entrusts Qiaojie to her (ch. 113); when Wang Ren and Jia Huan plot to sell the girl, Granny Liu hides her and Ping’er in the country and finds her a husband (chs. 119–120)."),
    icon=("白发老妪，包着头巾，挎着竹篮。", "White-haired, in a headscarf, with a basket on her arm.")),
  N(id="qinzhong", zh="秦钟", py="Qín Zhōng", en="Qin Zhong", grp="out", debut=7, dies=16,
    camps=[(7, "out")],
    sub=("秦可卿之弟", "Qin Keqing’s younger brother"),
    bio=("秦业的儿子，“眉清目秀，粉面朱唇，身材俊俏，举止风流，似在宝玉之上”，宝玉一见便要和他结交(第7回)。两人一同入家塾读书，惹出闹学堂一场风波(第9回)。秦可卿出殡，他在馒头庵与小尼姑智能儿私会，被宝玉撞破(第15回)。他回家后染病；智能儿私逃进城找他，被他父亲撞见撵了出去，父亲气死，他病情加重，临终对宝玉说“以前你我见识自为高过世人，我今日才知自误了。以后还该立志功名，以荣耀显达为是”(第16回)。",
         "Son of Qin Ye, even prettier and more graceful than Baoyu, who wants to be his friend at first sight (ch. 7). They join the clan school together, and set off a brawl (ch. 9). During his sister’s funeral he meets the young nun Zhineng in secret at Bun Convent, and Baoyu catches them (ch. 15). He falls ill at home; Zhineng runs away to find him, his father throws her out and dies of rage, and Qin Zhong, dying, tells Baoyu that they thought themselves above the world but were wrong, and that he should seek an official career after all (ch. 16)."),
    icon=("清秀少年书生。", "A delicate young scholar.")),
  N(id="zhineng", zh="智能儿", py="Zhìnéng’ér", en="Zhineng", grp="out", debut=7, dies=None,
    camps=[(7, "kong")],
    sub=("水月庵的小尼姑", "A young nun of Water Moon Convent"),
    bio=("水月庵（俗称馒头庵）老尼净虚的徒弟，常随师父到贾府走动，和惜春一处玩(第7回)。她长大了，渐知风月，看上了秦钟(第15回)。秦可卿出殡，宝玉、秦钟住在馒头庵，秦钟夜里和她私会，被宝玉按住(第15回)。秦钟回家后，她私逃进城去找他，被秦业撞见撵了出去，秦业气死，秦钟也病重而亡(第16回)。",
         "A novice of Water Moon Convent, known as Bun Convent, who often visits the Jias with her abbess and plays with Xichun (ch. 7). Grown older, she falls for Qin Zhong (ch. 15), and meets him at night while the funeral party stays at the convent; Baoyu catches them (ch. 15). She runs away to the city to find Qin Zhong, is thrown out by his father, who dies of rage, and Qin Zhong soon dies too (ch. 16)."),
    icon=("光头小尼姑。", "A young nun with a shaven head.")),
  N(id="beijingwang", zh="北静王", py="Běijìng wáng", en="Prince of Beijing", grp="out", debut=14, dies=None,
    camps=[(14, "out")],
    sub=("名水溶 · 四王之一", "Shui Rong, one of the four princes"),
    bio=("名叫水溶，“年未弱冠，生得形容秀美，情性谦和”(第14回)。秦可卿出殡，他亲自设祭路祭，召宝玉上前相见，夸他“名不虚传，果然如'宝'似'玉'”，又把皇上所赐的鹡鸰香念珠送给宝玉(第14—15回)。宝玉对他十分敬慕；后来蒋玉菡送给宝玉的大红汗巾，原也是北静王给蒋玉菡的(第28回)。",
         "Shui Rong, not yet twenty, handsome and modest (ch. 14). At Qin Keqing’s funeral procession he sets up an offering on the road, calls Baoyu to him, praises him as living up to his name, and gives him a rosary that was a gift from the emperor (chs. 14–15). Baoyu admires him; the red sash the actor Jiang Yuhan gives Baoyu was a gift from the prince (ch. 28)."),
    late=("锦衣军查抄贾府时，他奉旨前来，处处照应贾政(第105回)。",
          "When the imperial guards search the Jia house he arrives with the emperor’s orders and shields Jia Zheng (ch. 105)."),
    icon=("白簪缨银翅王帽，白蟒袍(第15回)。", "A white prince’s cap with silver wings and a white dragon robe (ch. 15).")),
  N(id="jiangyuhan", zh="蒋玉菡", py="Jiǎng Yùhán", en="Jiang Yuhan", grp="out", debut=28, dies=None,
    camps=[(28, "out")],
    sub=("忠顺王府的小旦 · 小名琪官", "Actor of the Prince of Zhongshun’s troupe, also called Qiguan"),
    bio=("名驰天下的小旦，小名琪官。在冯紫英家的酒席上与宝玉相识，两人一见如故，互换了汗巾：他把北静王送他的一条茜香国女国王进贡的大红汗巾子送给宝玉，宝玉把袭人的松花绿汗巾给了他(第28回)。他从忠顺王府出走，王府长史官找上贾府，说宝玉知道他的下落，宝玉只得说出他在东郊紫檀堡置了房子(第33回)，随即挨了父亲一顿毒打。",
         "The most famous young actor of female roles, also called Qiguan. He meets Baoyu at a dinner and they exchange sashes: his is a crimson one, tribute from a far kingdom, given him by the Prince of Beijing; Baoyu’s is a green one belonging to Xiren (ch. 28). When he runs away from the Prince of Zhongshun, the prince’s steward comes to the Jias, and Baoyu has to reveal that the actor has bought a house east of the city (ch. 33) — and is then beaten by his father."),
    late=("他后来在临安伯府唱戏时又见到了宝玉(第93回)；宝玉出家后，他娶了袭人，婚后第二天在她箱中看见那条猩红汗巾，又拿出那条松花绿汗巾，两人才知姻缘前定(第120回)。",
          "Baoyu sees him on stage again at a party (ch. 93); after Baoyu leaves the world Jiang marries Xiren, and the day after the wedding the two sashes tell them both who the other is (ch. 120)."),
    icon=("旦角打扮，手持大红汗巾。", "In a young actor’s costume, holding the crimson sash.")),
  N(id="liuxianglian", zh="柳湘莲", py="Liǔ Xiānglián", en="Liu Xianglian", grp="out", debut=47, dies=None,
    camps=[(47, "out"), (66, "kong", "随道士出家", "Leaves with a Taoist")],
    sub=("世家子弟 · 回目称“冷二郎”", "A gentleman of an old family, “the Cold Hero” of the chapter titles"),
    bio=("原是世家子弟，父母早丧，“素性爽侠，不拘细事，酷好耍枪舞剑，赌博吃酒，以至眠花卧柳，吹笛弹筝，无所不为”，又爱串戏，常扮生旦，被人误认作优伶(第47回)。薛蟠把他当成戏子调戏，他假意相约，把薛蟠诱到北门外苇塘边痛打一顿，然后远走他乡(第47回)。后来他救了遇盗的薛蟠，结为弟兄(第66回)；贾琏为尤三姐作媒，他以祖传的鸳鸯剑为定礼，回京后听宝玉说她是宁府里的人，起了疑心，来要回定礼，三姐当场自刎。他抚尸大哭，恍惚中见三姐来辞别，醒来随一个道士，“不知往那里去了”(第66回)。",
         "From an old family, orphaned young; bold and careless, he loves swordplay, gambling, drinking, music and pleasure, and acts in amateur theatricals, so that people take him for an actor (ch. 47). When Xue Pan makes a pass at him he pretends to agree, lures him out of the city, thrashes him, and leaves the capital (ch. 47). Later he saves Xue Pan from robbers and they become sworn brothers (ch. 66). Jia Lian proposes a match with You Sanjie and Liu gives his family’s twin swords as a pledge; but back in the capital, told she lives in the Ning mansion, he grows suspicious and asks for the swords back, and she kills herself before him. Weeping over her, he sees her ghost say goodbye, and goes off with a Taoist, “no one knows where” (ch. 66)."),
    icon=("佩剑的侠客。", "A swordsman with a sword at his side.")),
  N(id="miaoyu", zh="妙玉", py="Miàoyù", en="Miaoyu", grp="out", debut=18, dies=None,
    camps=[(18, "kong"), (112, "out", "被强盗劫走", "Carried off by robbers")],
    sub=("栊翠庵带发修行的尼姑", "A nun at Green Bower Hermitage"),
    bio=("苏州读书仕宦人家的小姐，自幼多病，买了许多替身都不中用，只得亲自入了空门，带发修行(第18回)。贾府为省亲请她住进大观园的栊翠庵(第18回)。她性情孤僻：刘姥姥用过的成窑杯，她嫌脏不要了；她拿五年前收的梅花上的雪水沏茶，请宝钗、黛玉吃“梯己茶”，宝玉也跟了来，黛玉问是不是旧年的雨水，她冷笑说“你这么个人，竟是大俗人，连水也尝不出来”(第41回)。宝玉生日，她送来一张粉笺子，落款“槛外人”(第63回)。中秋夜她续完了黛玉、湘云在凹晶馆的联诗(第76回)。",
         "Daughter of a scholar-official family of Suzhou, sickly from birth, who could only be saved by taking vows herself, though she keeps her hair (ch. 18). The Jias invite her to live at Green Bower Hermitage in the garden (ch. 18). She is fastidious and aloof: she throws away the precious cup Granny Liu drank from, and makes tea for Baochai and Daiyu with snow she gathered from plum blossoms five years before; when Daiyu asks if it is last year’s rainwater, Miaoyu scoffs that she cannot even taste water (ch. 41). For Baoyu’s birthday she sends a card signed “one outside the threshold” (ch. 63). On the mid-autumn night she completes the linked verse Daiyu and Xiangyun began by the pond (ch. 76)."),
    late=("她在惜春处下棋，见了宝玉不觉脸红，夜里打坐走火入魔(第87回)。贾府遭贼，盗贼用闷香把她劫走，从此不知下落(第112回)，应了判词“可怜金玉质，终陷淖泥中”。",
          "Seeing Baoyu at Xichun’s, she blushes; that night her meditation goes astray (ch. 87). Robbers break into the Jia house and carry her off, drugged, and she is never heard of again (ch. 112) — “sunk at last in the mire”, as her verse said."),
    icon=("尼僧帽，手持拂尘。", "A nun’s hood and a fly whisk.")),
  N(id="madaopo", zh="马道婆", py="Mǎ dàopó", en="Mother Ma", grp="out", debut=25, dies=None,
    camps=[(25, "kong")],
    sub=("宝玉的寄名干娘", "Baoyu’s godmother in religion"),
    bio=("宝玉的寄名干娘，常在各府里走动。她来贾府，哄得贾母每天为宝玉在佛前点海灯，舍五斤香油(第25回)。在赵姨娘房里，赵姨娘写了五百两银子的欠契给她，她便拿出两个纸人和十个纸铰的青面白发鬼，教赵姨娘把宝玉、凤姐的年庚八字写在纸人上，各带五个鬼掖在二人床上，自己在家作法；不久宝玉和凤姐便发起狂来，几乎丧命(第25回)。",
         "Baoyu’s godmother in religion, who visits all the great houses. She talks Grandmother Jia into paying for an ever-burning lamp for Baoyu (ch. 25). In Concubine Zhao’s room, for an IOU of five hundred taels, she hands over two paper figures and ten paper demons: Zhao is to write Baoyu’s and Xifeng’s birth dates on the figures and hide them, five demons each, in their beds, while Mother Ma works the spell at home. Soon both go mad and almost die (ch. 25)."),
    late=("她受人买嘱，用魇魔法害一家当铺的内眷，事情败露，被锦衣府拿住送入刑部监(第81回)。",
          "Bribed to bewitch a pawnbroker’s household, she is caught and handed over to the imperial guard (ch. 81)."),
    icon=("道婆，手持纸人。", "A sorceress holding paper figures.")),
  N(id="zhanghua", zh="张华", py="Zhāng Huá", en="Zhang Hua", grp="out", debut=64, dies=None,
    camps=[(64, "out")],
    sub=("尤二姐指腹为婚的未婚夫", "Erjie’s betrothed from before her birth"),
    bio=("皇粮庄头之子，和尤二姐指腹为婚；家里遭了官司，败落了；贾府的家人把他父子叫来，仗着贾珍的势逼他们写了退婚文约，尤老娘给了二十两银子(第64回)。凤姐知道后，叫旺儿找到他，给他银子，唆使他到都察院告贾琏“国孝家孝之中，背旨瞒亲，仗财依势，强逼退亲，停妻再娶”，借此大闹宁国府(第68回)。事后凤姐还想斩草除根，叫旺儿去结果了他，旺儿只骗她说张华已在路上被劫杀(第69回)。",
         "Son of a farm steward, betrothed to You Erjie before either was born; when his family is ruined, the Jias’ servants, backed by Jia Zhen’s power, force Zhang Hua and his father to give her up, and her mother pays them twenty taels (ch. 64). Xifeng has him found and paid to sue Jia Lian for marrying during mourning and taking a second wife by force — the pretext for her scene at the Ning mansion (ch. 68). Afterwards she wants him dead, but her servant lies that robbers have killed him (ch. 69)."),
    icon=("落魄少年。", "A down-at-heel young man.")),
  N(id="sunshaozu", zh="孙绍祖", py="Sūn Shàozǔ", en="Sun Shaozu", grp="out", debut=79, dies=None,
    camps=[(79, "out")],
    sub=("大同府人 · 迎春的丈夫", "A man of Datong, Yingchun’s husband"),
    bio=("大同府人，祖上是军官出身，当年因希慕荣宁二府的势力拜在贾家门下(第79回)。他“相貌魁梧，体格健壮，弓马娴熟，应酬权变”，在兵部候缺题升，贾赦便把迎春许给了他；贾政劝过，贾赦不听(第79回)。迎春回门时哭诉他“一味好色，好赌酗酒，家中所有的媳妇丫头将及淫遍”，还骂迎春说贾赦使了他五千两银子，“把你准折买给我的”(第80回)。",
         "From Datong, of a military family that once attached itself to the Jias for their influence (ch. 79). Big, strong, a fine horseman and a smooth talker, waiting for promotion at the Board of War, he is given Yingchun by Jia She against Jia Zheng’s advice (ch. 79). Home on a visit, she weeps that he is a lecher, gambler and drunkard who has slept with every woman in his house, and says she was sold to him to pay her father’s debt of five thousand taels (ch. 80)."),
    late=("贾府被抄后，他派人来讨贾赦欠他的银子(第106回)；迎春出嫁一年多，就被他折磨死了(第109回)。",
          "After the search he sends to demand the money Jia She owes him (ch. 106); a little over a year after the wedding Yingchun is dead of his cruelty (ch. 109)."),
    icon=("武官打扮，满脸横肉。", "Military dress, a brutal face.")),
  N(id="zhenbaoyu", zh="甄宝玉", py="Zhēn Bǎoyù", en="Zhen Baoyu", grp="out", debut=2, dies=None,
    camps=[(2, "out")],
    sub=("金陵甄家的公子", "Son of the Zhen family of Jinling"),
    bio=("金陵甄家的公子，和宝玉同名，模样、脾气也一样。贾雨村在甄家坐馆时，听他说读书要“两个女儿伴着”才认得字(第2回)。甄家的女人来请安，见了宝玉，说两个宝玉“模样是一样”；宝玉随后梦见自己到了甄家，见到一个和自己一样的宝玉，醒来才知是梦——原来他对着镜子睡着了(第56回)。",
         "Son of the Zhen family of Jinling, with the same name, looks and temperament as Baoyu. When Jia Yucun was his tutor, the boy said he could only learn his characters with two girls beside him (ch. 2). The Zhen servants meet Baoyu and say the two boys look the same; soon after, Baoyu dreams he visits the Zhens and meets a Baoyu just like himself, and wakes to find he fell asleep facing a mirror (ch. 56)."),
    late=("甄家抄家后又蒙恩起复，他随母进京，和宝玉相见，却满口“文章经济”“立德立言”，宝玉大失所望，回目说“证同类宝玉失相知”(第115回)。",
          "Restored to favour after their own disgrace, the Zhens come to the capital, and the two Baoyus meet at last; but Zhen Baoyu talks only of careers and virtue, and Jia Baoyu finds he has lost a kindred spirit (ch. 115)."),
    icon=("和宝玉一样的装束。", "Dressed exactly like Baoyu.")),
]
