# -*- coding: utf-8 -*-
"""Verses for the person cards: the registers (判词) Baoyu reads in the Land of Illusion and the twelve songs
of the Dream of the Red Chamber (红楼梦曲), both in chapter 5, plus a few other poems about particular people.
Chinese text as in the common editions; the English versions are our own plain renderings.

Each entry: dict(k=kind, t=(zh title, en title), pic=(zh, en) or None, zh=[lines], en=[lines], note=(zh, en) or None)
  kind: reg (a register verse; pic is the picture above it) / song / poem
"""

REG_DAI_CHAI = dict(
    k="reg", t=("金陵十二钗正册 · 判词", "The Twelve Beauties of Jinling, first register"),
    pic=("两株枯木，木上悬着一围玉带；又有一堆雪，雪下一股金簪。",
         "Two dead trees with a jade belt hanging from them; a drift of snow with a gold hairpin buried in it."),
    zh=["可叹停机德，堪怜咏絮才。", "玉带林中挂，金簪雪里埋。"],
    en=["Alas for the virtue that stopped the loom,", "and pity the talent that sang of willow-down:",
        "a jade belt hangs in the wood,", "a gold pin lies buried in snow."],
    note=("这一首同咏宝钗与黛玉：“停机德”说宝钗，“咏絮才”说黛玉；“玉带林”倒读是林黛玉，“雪里”谐“薛”，“金簪”即宝钗。",
          "One verse for both girls: Baochai has the wife’s virtue, Daiyu the poet’s gift; read backwards, “jade belt” and “wood” give Lin Daiyu, “snow” (xue) is Xue, and the gold hairpin is Baochai."))

VERSES = {
  "daiyu": [
    REG_DAI_CHAI,
    dict(k="song", t=("红楼梦曲 · 枉凝眉", "Song: Brows Knit in Vain"), pic=None,
         zh=["一个是阆苑仙葩，一个是美玉无瑕。", "若说没奇缘，今生偏又遇着他；", "若说有奇缘，如何心事终虚化？",
             "一个枉自嗟呀，一个空劳牵挂。", "一个是水中月，一个是镜中花。",
             "想眼中能有多少泪珠儿，", "怎经得秋流到冬尽，春流到夏！"],
         en=["One is a fairy flower from paradise, one a flawless jade.", "If they had no strange bond, why did they meet in this life?",
             "If they had, why did their hopes come to nothing?", "One sighs in vain, one longs in vain;",
             "one is the moon in the water, one the flower in the mirror.", "How many tears can a pair of eyes hold,",
             "to flow from autumn to winter’s end, from spring into summer?"],
         note=None),
  ],
  "baochai": [
    REG_DAI_CHAI,
    dict(k="song", t=("红楼梦曲 · 终身误", "Song: A Life Misspent"), pic=None,
         zh=["都道是金玉良姻，俺只念木石前盟。", "空对着，山中高士晶莹雪；", "终不忘，世外仙姝寂寞林。",
             "叹人间，美中不足今方信：", "纵然是齐眉举案，到底意难平。"],
         en=["All speak of the match of gold and jade; I remember only the bond of wood and stone.",
             "In vain I face the crystal snow of the recluse on the mountain;",
             "I cannot forget the lonely wood of the fairy beyond the world.",
             "Now I believe that even beauty is never whole:",
             "though husband and wife honour each other at table, the heart is never at peace."],
         note=("曲子用宝玉的口吻：“山中高士晶莹雪”指宝钗，“世外仙姝寂寞林”指黛玉。",
               "The song is in Baoyu’s voice: the recluse’s snow is Baochai (Xue), the lonely wood is Daiyu (Lin).")),
  ],
  "yuanchun": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一张弓，弓上挂着香橼。", "A bow with a citron hanging from it."),
         zh=["二十年来辨是非，榴花开处照宫闱。", "三春争及初春景，虎兕相逢大梦归。"],
         en=["Twenty years she has judged right from wrong;", "where the pomegranate blooms, she lights the palace.",
             "Three springs cannot match the first spring’s splendour;", "when tiger meets rhinoceros, the great dream ends."],
         note=("“弓”谐“宫”，“橼”谐“元”；“三春”指迎、探、惜三个妹妹，“初春”即元春。",
               "Bow (gong) sounds like “palace”, citron (yuan) like her name; the three springs are her three sisters, the first spring herself.")),
    dict(k="song", t=("红楼梦曲 · 恨无常", "Song: Grieving at Impermanence"), pic=None,
         zh=["喜荣华正好，恨无常又到。", "眼睁睁，把万事全抛；荡悠悠，把芳魂消耗。", "望家乡，路远山高。",
             "故向爹娘梦里相寻告：", "儿命已入黄泉，天伦呵，须要退步抽身早！"],
         en=["Glory at its height — and then death comes.", "With open eyes she leaves all things behind; drifting, her soul wastes away.",
             "She looks toward home: the road is long, the mountains high.", "So she seeks her parents in a dream:",
             "“Your child has gone to the Yellow Springs. Father, mother — step back and withdraw in time!”"],
         note=None),
  ],
  "tanchun": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("两人放风筝，一片大海，一只大船，船中有一女子掩面泣涕之状。",
              "Two people flying kites; a sea and a great ship, and in it a woman weeping into her hands."),
         zh=["才自精明志自高，生于末世运偏消。", "清明涕送江边望，千里东风一梦遥。"],
         en=["Clever and high-minded,", "born in a declining age, her luck runs out.",
             "At Qingming, in tears, she is seen off from the river;", "a thousand miles on the east wind, home is a distant dream."],
         note=None),
    dict(k="song", t=("红楼梦曲 · 分骨肉", "Song: Parted from Her Own"), pic=None,
         zh=["一帆风雨路三千，把骨肉家园齐来抛闪。", "恐哭损残年，告爹娘，休把儿悬念。",
             "自古穷通皆有定，离合岂无缘？", "从今分两地，各自保平安。", "奴去也，莫牵连。"],
         en=["One sail through wind and rain, three thousand li: she leaves her family and her home.",
             "Fearing their tears will wear out their old age, she begs her parents not to worry for her.",
             "Since ancient times fortune has been fixed; are partings and meetings not fated?",
             "From now on we live apart; keep safe, each of us.", "I am going — do not hold me."],
         note=None),
  ],
  "xiangyun": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("几缕飞云，一湾逝水。", "Wisps of flying cloud and a bend of flowing water."),
         zh=["富贵又何为，襁褓之间父母违。", "展眼吊斜晖，湘江水逝楚云飞。"],
         en=["What use are wealth and rank?", "In swaddling clothes she lost her parents.",
             "In the blink of an eye she mourns the setting sun:", "the Xiang flows away, the clouds of Chu fly off."],
         note=None),
    dict(k="song", t=("红楼梦曲 · 乐中悲", "Song: Sorrow amid Joy"), pic=None,
         zh=["襁褓中，父母叹双亡。", "纵居那绮罗丛，谁知娇养？", "幸生来，英豪阔大宽宏量，", "从未将儿女私情略萦心上。",
             "好一似，霁月光风耀玉堂。", "厮配得才貌仙郎，博得个地久天长，", "准折得幼年时坎坷形状。",
             "终久是云散高唐，水涸湘江。", "这是尘寰中消长数应当，何必枉悲伤！"],
         en=["In swaddling clothes she lost both parents;", "though she lived among silks, who cherished her?",
             "Luckily she was born generous and bold,", "never troubling her heart with tender feelings —",
             "like a clear moon and fresh breeze shining on a jade hall.", "Matched with a gifted, handsome husband, she hoped for a lifetime together",
             "to make up for the hardships of her childhood.", "But in the end the clouds scatter over Gaotang and the Xiang runs dry.",
             "Such is the waxing and waning of this dusty world; why grieve in vain?"],
         note=None),
  ],
  "miaoyu": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一块美玉，落在泥垢之中。", "A fine jade fallen in the mud."),
         zh=["欲洁何曾洁，云空未必空。", "可怜金玉质，终陷淖泥中。"],
         en=["She longed to be pure, but was she ever?", "She said all is empty, but it was not.",
             "Pity such gold and jade", "sunk at last in the mire."],
         note=None),
    dict(k="song", t=("红楼梦曲 · 世难容", "Song: Too Pure for the World"), pic=None,
         zh=["气质美如兰，才华阜比仙。", "天生成孤癖人皆罕。", "你道是啖肉食腥膻，视绮罗俗厌；",
             "却不知太高人愈妒，过洁世同嫌。", "可叹这，青灯古殿人将老；", "辜负了，红粉朱楼春色阑。",
             "到头来，依旧是风尘肮脏违心愿。", "好一似，无瑕白玉遭泥陷；", "又何须，王孙公子叹无缘。"],
         en=["Her nature fine as an orchid, her gifts rich as a fairy’s,", "born aloof, rare among people.",
             "You find meat rank and silk vulgar;", "but the lofty are envied, the too pure shunned by all.",
             "Alas, she grows old by a dim lamp in an old shrine,", "wasting the spring of a girl in a red chamber.",
             "In the end the dust and dirt of the world defeat her:", "flawless white jade sunk in mud.",
             "Why should a young lord sigh that they were not to be?"],
         note=None),
  ],
  "yingchun": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一个恶狼，追扑一美女，欲啖之意。", "A wolf pouncing on a beautiful woman as if to devour her."),
         zh=["子系中山狼，得志便猖狂。", "金闺花柳质，一载赴黄粱。"],
         en=["The man is the wolf of Zhongshan,", "ruthless once he has his way.",
             "A flower from a golden chamber,", "within a year she wakes from the millet dream."],
         note=("“子系”合起来是繁体的“孫”字，指孙绍祖；“中山狼”出自忘恩负义的寓言。",
               "The first two characters together make the old form of “Sun”, her husband’s surname; the wolf of Zhongshan is the ungrateful beast of the fable.")),
    dict(k="song", t=("红楼梦曲 · 喜冤家", "Song: Married to an Enemy"), pic=None,
         zh=["中山狼，无情兽，全不念当日根由。", "一味的骄奢淫荡贪欢媾。", "觑着那，侯门艳质同蒲柳；",
             "作践的，公府千金似下流。", "叹芳魂艳魄，一载荡悠悠。"],
         en=["Wolf of Zhongshan, heartless beast, forgetting all he owed,", "arrogant, wasteful, lewd, greedy for pleasure,",
             "he treats a noble beauty like a common willow", "and tramples a duke’s daughter like a drab.",
             "Alas, within a year her lovely spirit drifts away."],
         note=None),
  ],
  "xichun": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一所古庙，里面有一美人在内看经独坐。", "An old temple, where a beautiful woman sits alone reading sutras."),
         zh=["勘破三春景不长，缁衣顿改昔年妆。", "可怜绣户侯门女，独卧青灯古佛旁。"],
         en=["Seeing that her sisters’ springs could not last,", "she trades her finery for a nun’s black robe.",
             "Pity the daughter of a noble house", "lying alone by a dim lamp beside an old Buddha."],
         note=None),
    dict(k="song", t=("红楼梦曲 · 虚花悟", "Song: Awakening from Empty Blossoms"), pic=None,
         zh=["将那三春看破，桃红柳绿待如何？", "把这韶华打灭，觅那清淡天和。", "说什么，天上夭桃盛，云中杏蕊多。",
             "到头来，谁把秋捱过？", "则看那，白杨村里人呜咽，青枫林下鬼吟哦。", "更兼着，连天衰草遮坟墓。",
             "这的是，昨贫今富人劳碌，春荣秋谢花折磨。", "似这般，生关死劫谁能躲？",
             "闻说道，西方宝树唤婆娑，上结着长生果。"],
         en=["Seeing through those three springs, what are red peach and green willow to her?",
             "She puts out the glow of youth to seek a plain and heavenly peace.",
             "What talk of peaches thick in heaven, of apricots among the clouds?", "Who, in the end, outlasts the autumn?",
             "Look: people sob in the village of white poplars, ghosts moan under the green maples,",
             "and withered grass covers the graves to the edge of the sky.",
             "Poor yesterday, rich today, people toil; flowers bloom in spring and are tormented in autumn.",
             "Who can escape the gates of life and death?",
             "They say that in the West there is a jewelled tree, the sala, bearing the fruit of eternal life."],
         note=None),
  ],
  "xifeng": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一片冰山，上面有一只雌凤。", "An iceberg with a hen phoenix on it."),
         zh=["凡鸟偏从末世来，都知爱慕此生才。", "一从二令三人木，哭向金陵事更哀。"],
         en=["This phoenix came in the last days of an age;", "everyone admired her talent.",
             "First obeying, then commanding, then cast aside —", "she goes weeping back to Jinling, sadder still."],
         note=("“凡鸟”合成繁体“鳳”字。“一从二令三人木”是个谜，历来解法不一，这里只取一种常见的读法。",
               "The first two characters combine into the old form of “phoenix”, her name. The third line is a riddle with many interpretations; we give one common reading.")),
    dict(k="song", t=("红楼梦曲 · 聪明累", "Song: Undone by Cleverness"), pic=None,
         zh=["机关算尽太聪明，反算了卿卿性命。", "生前心已碎，死后性空灵。", "家富人宁，终有个家亡人散各奔腾。",
             "枉费了，意悬悬半世心；", "好一似，荡悠悠三更梦。", "忽喇喇似大厦倾，昏惨惨似灯将尽。",
             "呀！一场欢喜忽悲辛。", "叹人世，终难定！"],
         en=["Too clever, scheming to the last, she schemed away her own life.", "Her heart broken while she lived, her spirit empty after death.",
             "A rich house and a peaceful family — yet in the end the house falls and all scatter.",
             "Wasted, half a lifetime of anxious care,", "like a drifting midnight dream.",
             "Crash! like a great house falling; dim, like a lamp about to die.", "Ah — joy turns suddenly to grief.",
             "Nothing in this world is certain!"],
         note=None),
  ],
  "qiaojie": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一座荒村野店，有一美人在那里纺绩。", "A village inn in the wilds, where a beautiful woman sits spinning."),
         zh=["势败休云贵，家亡莫论亲。", "偶因济刘氏，巧得遇恩人。"],
         en=["When power fails, speak no more of rank;", "when a house falls, speak no more of kin.",
             "Because her mother once helped a woman named Liu,", "by luck she finds a benefactor."],
         note=None),
    dict(k="song", t=("红楼梦曲 · 留余庆", "Song: Blessings Left Behind"), pic=None,
         zh=["留余庆，留余庆，忽遇恩人；", "幸娘亲，幸娘亲，积得阴功。", "劝人生，济困扶穷，",
             "休似俺那爱银钱忘骨肉的狠舅奸兄！", "正是乘除加减，上有苍穹。"],
         en=["Blessings left behind, blessings left behind — suddenly she meets her benefactor;",
             "thanks to her mother, thanks to her mother, who stored up hidden merit.", "So help the poor and those in need,",
             "and don’t be like my cruel uncle and false brother, who loved money and forgot their own blood!",
             "For gains and losses are reckoned by Heaven above."],
         note=None),
  ],
  "liwan": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("一盆茂兰，旁有一位凤冠霞帔的美人。", "A thriving potted orchid, and beside it a beauty in phoenix crown and embroidered cape."),
         zh=["桃李春风结子完，到头谁似一盆兰。", "如冰水好空相妒，枉与他人作笑谈。"],
         en=["Peach and plum bear their fruit in the spring wind and are done;", "in the end, who is like the potted orchid?",
             "Pure as ice and water, envied for nothing,", "she becomes a joke for others in the end."],
         note=("“李”是她的姓，“完”谐“纨”，“兰”是儿子贾兰。", "Plum (li) is her surname, “done” (wan) sounds like her name, and the orchid (lan) is her son Jia Lan.")),
    dict(k="song", t=("红楼梦曲 · 晚韶华", "Song: Late Splendour"), pic=None,
         zh=["镜里恩情，更那堪梦里功名！", "那美韶华去之何迅！再休提绣帐鸳衾。", "只这带珠冠，披凤袄，也抵不了无常性命。",
             "虽说是，人生莫受老来贫，也须要阴骘积儿孙。", "气昂昂头戴簪缨，光灿灿胸悬金印；",
             "威赫赫爵禄高登，昏惨惨黄泉路近。", "问古来将相可还存？也只是虚名儿与后人钦敬。"],
         en=["Love in a mirror, and fame in a dream!", "How fast the lovely years have gone; speak no more of the bridal bed.",
             "A pearl crown and a phoenix robe cannot buy off death.",
             "True, no one should be poor in old age — but one must store up merit for one’s children.",
             "Proudly wearing an official’s tassels, a gold seal gleaming on the breast,",
             "rank and salary high — and the road to the Yellow Springs is near.",
             "Where are the generals and ministers of old? Only empty names, for later ages to revere."],
         note=None),
  ],
  "qinkeqing": [
    dict(k="reg", t=("金陵十二钗正册 · 判词", "First register"),
         pic=("高楼大厦，有一美人悬梁自缢。", "A tall building, and in it a beautiful woman hanging from a beam."),
         zh=["情天情海幻情身，情既相逢必主淫。", "漫言不肖皆荣出，造衅开端实在宁。"],
         en=["In a sky and sea of love, a body made of love;", "when love meets love, wantonness follows.",
             "Don’t say the unworthy all come from Rong:", "the trouble truly began in Ning."],
         note=("小说正文写她病死，册子上的画却是悬梁自缢，因此历来有人认为曹雪芹原稿中她是自缢而死。",
               "The novel says she died of illness, but the register shows her hanging; many readers think that in Cao Xueqin’s first draft she took her own life.")),
    dict(k="song", t=("红楼梦曲 · 好事终", "Song: The End of a Fine Affair"), pic=None,
         zh=["画梁春尽落香尘。擅风情，秉月貌，便是败家的根本。", "箕裘颓堕皆从敬，家事消亡首罪宁。", "宿孽总因情。"],
         en=["From the painted beam, at spring’s end, fragrant dust falls. Her charm and her beauty were the root of the family’s ruin.",
             "The decline began with Jing; for the house’s fall, Ning bears the first blame.", "All old sins come from love."],
         note=None),
  ],
  "qingwen": [
    dict(k="reg", t=("金陵十二钗又副册 · 判词", "Twelve Beauties, third register"),
         pic=("水墨渲染的满纸乌云浊雾。", "Nothing but dark clouds and murky mist in ink wash."),
         zh=["霁月难逢，彩云易散。", "心比天高，身为下贱。", "风流灵巧招人怨。", "寿夭多因毁谤生，多情公子空牵念。"],
         en=["A clear moon is seldom seen, bright clouds soon scatter.", "Her heart was higher than the sky, her station low.",
             "Her grace and wit drew ill will;", "slander cut her life short, and her tender young master longs for her in vain."],
         note=("“霁月”是晴，“彩云”是雯。", "A clear moon (qing) and bright clouds (wen) spell her name.")),
  ],
  "xiren": [
    dict(k="reg", t=("金陵十二钗又副册 · 判词", "Twelve Beauties, third register"),
         pic=("一簇鲜花，一床破席。", "A cluster of fresh flowers and a tattered mat."),
         zh=["枉自温柔和顺，空云似桂如兰。", "堪羡优伶有福，谁知公子无缘。"],
         en=["In vain her gentleness and patience,", "in vain her cassia and orchid grace.",
             "Envy the lucky actor —", "who knew the young master was not her fate?"],
         note=("“花”是她的姓；“席”谐“袭”。有人认为草编的破席又暗指“蒋”（草字头）。", "The flowers are her surname, Hua; the mat (xi) is her name, and some think the woven mat also hints at Jiang, the actor she will marry.")),
  ],
  "xiangling": [
    dict(k="reg", t=("金陵十二钗副册 · 判词", "Twelve Beauties, second register"),
         pic=("一株桂花，下面有一池沼，其中水涸泥干，莲枯藕败。", "A cassia tree above a pond gone dry, its lotus withered."),
         zh=["根并荷花一茎香，平生遭际实堪伤。", "自从两地生孤木，致使香魂返故乡。"],
         en=["Her root shares one fragrant stem with the lotus;", "her life has been sad indeed.",
             "Once a lone tree grows on two plots of earth,", "her fragrant soul goes home."],
         note=("“两地生孤木”合成“桂”字，指夏金桂。", "“Two plots of earth” and “a lone tree” put together make the character gui, as in Xia Jingui’s name.")),
  ],
  "baoyu": [
    dict(k="poem", t=("西江月二首（第3回）", "Two poems on Baoyu (ch. 3)"), pic=None,
         zh=["无故寻愁觅恨，有时似傻如狂。", "纵然生得好皮囊，腹内原来草莽。", "潦倒不通世务，愚顽怕读文章。",
             "行为偏僻性乖张，那管世人诽谤！", "富贵不知乐业，贫穷难耐凄凉。", "可怜辜负好韶光，于国于家无望。",
             "天下无能第一，古今不肖无双。", "寄言纨绔与膏粱：莫效此儿形状！"],
         en=["For no reason he seeks out sorrow, at times seems a fool or a madman;", "a handsome face, but nothing but weeds inside.",
             "Hopeless in worldly affairs, too stubborn to read his books,", "odd and perverse, he cares nothing for what people say.",
             "Rich, he cannot enjoy his fortune; poor, he could not bear the hardship.",
             "Pity he wastes the best years, no use to family or state:", "first in the world for uselessness, unmatched in unworthiness.",
             "A word to young men of wealth: do not follow his example!"],
         note=("这两首词明贬暗褒，是小说里描写宝玉的名篇。", "Mock blame that is really praise — the novel’s famous sketch of Baoyu.")),
  ],
  "shiyin": [
    dict(k="poem", t=("好了歌（第1回）", "The Song of Good-and-Done (ch. 1)"), pic=None,
         zh=["世人都晓神仙好，惟有功名忘不了！古今将相在何方？荒冢一堆草没了。",
             "世人都晓神仙好，只有金银忘不了！终朝只恨聚无多，及到多时眼闭了。",
             "世人都晓神仙好，只有姣妻忘不了！君生日日说恩情，君死又随人去了。",
             "世人都晓神仙好，只有儿孙忘不了！痴心父母古来多，孝顺儿孙谁见了？"],
         en=["Everyone knows immortals are blessed, but fame and office they cannot forget. Where are the generals and ministers of old? A heap of graves, overgrown with grass.",
             "Everyone knows immortals are blessed, but gold and silver they cannot forget. All their days they complain they have too little; by the time they have plenty, their eyes are closed.",
             "Everyone knows immortals are blessed, but their lovely wives they cannot forget. While you live she speaks of love each day; when you die she goes off with another.",
             "Everyone knows immortals are blessed, but their children they cannot forget. Doting parents there have always been; who has ever seen a dutiful son?"],
         note=("跛足道人唱的歌：“好”便是“了”，“了”便是“好”。甄士隐听了，为它作了一篇注解，便随他而去。",
               "The lame Taoist’s song: to be done with things is good, and the good is to be done. Hearing it, Zhen Shiyin writes a commentary on it and follows him.")),
  ],
}
