# -*- coding: utf-8 -*-
"""Game of Thrones (TV) relationships, part 3: the Targaryens and Essos, the Iron Islands, and the last seasons'
alliances. Format as in edges_got_a.py."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import P, E  # noqa: E402
from episodes_got import *  # noqa: E402,F401,F403

EDGES_C = [
  # =============================================================== the Targaryens
  E("aerys", "rhaegar",
    P(S1E2, "kin", "父子", "雷加是疯王的长子和继承人。", "Father and son", "Rhaegar was the Mad King’s eldest son and heir.")),
  E("aerys", "viserys",
    P(S1E2, "kin", "父子", "韦赛里斯是疯王的次子，自认是父亲的继承人。", "Father and son", "Viserys is the Mad King’s second son, who sees himself as his father’s heir.")),
  E("aerys", "daenerys",
    P(S1E2, "kin", "父女", "丹妮莉丝是疯王最小的孩子，生于父亲死后。", "Father and daughter", "Daenerys is the Mad King’s youngest child, born after his death.")),
  E("rhaegar", "daenerys",
    P(S1E1, "kin", "兄妹", "雷加是丹妮莉丝从未见过的大哥。", "Brother and sister", "Rhaegar is the eldest brother Daenerys never knew.")),
  E("rhaegar", "lyanna",
    P(S1E2, "foe", "掳走", "据劳勃所说，是雷加夺走了莱安娜，引发了叛乱。", "Abduction", "As Robert tells it, Rhaegar took Lyanna from him, and so began the rebellion."),
    P(S7E7, "love", "秘密成婚", "真相是两人相爱，雷加废除旧婚，与莱安娜秘密成婚。", "A secret marriage", "The truth: they loved each other, and Rhaegar set aside his first marriage to wed Lyanna in secret.")),
  E("rhaegar", "jon",
    P(S7E7, "kin", "父子", "琼恩是雷加与莱安娜的合法儿子，本名伊耿·坦格利安。", "Father and son", "Jon is the legitimate son of Rhaegar and Lyanna — Aegon Targaryen.")),
  E("daenerys", "viserys",
    P(S1E1, "kin", "兄妹", "丹妮莉丝从小在哥哥的威吓下长大。", "Brother and sister", "Daenerys has grown up in terror of her brother."),
    P(S1E6, "foe", "金冠", "韦赛里斯拔剑威胁妹妹，丹妮莉丝眼看他被熔金浇死，说他不是真龙。",
      "The golden crown", "When Viserys threatens her with a sword, Daenerys watches him die under molten gold and says he was no dragon.")),
  E("daenerys", "drogo",
    P(S1E1, "kin", "成婚", "韦赛里斯把丹妮莉丝嫁给卓戈，换一支军队。", "A wedding", "Viserys marries Daenerys to Drogo in exchange for an army."),
    P(S1E6, "love", "相爱", "丹妮莉丝赢得了卓戈的心，也赢得了多斯拉克人的尊重。", "Love", "Daenerys wins Drogo’s heart and the Dothraki’s respect."),
    P(S1E10, "love", "火葬", "丹妮莉丝闷死成了活死人的卓戈，为他举行火葬。", "The pyre", "Daenerys smothers the living husk of Drogo and burns him on a pyre.")),
  E("daenerys", "jorah",
    P(S1E1, "mas", "效忠", "乔拉投到丹妮莉丝身边，送她一套维斯特洛史书做结婚礼物。", "Sworn", "Jorah attaches himself to Daenerys and gives her books of Westerosi history as a wedding gift."),
    P(S1E2, "mas", "引路", "乔拉教丹妮莉丝多斯拉克人的规矩。", "Guide", "Jorah teaches Daenerys the ways of the Dothraki."),
    P(S1E7, "mas", "救驾", "乔拉在市场上识破了毒酒，救了丹妮莉丝。", "A life saved", "Jorah stops a poisoned cup in the market and saves her life."),
    P(S4E8, "tie", "放逐", "丹妮莉丝得知乔拉曾为劳勃监视她，把他逐出弥林。", "Banished", "Learning he once spied on her for Robert, Daenerys banishes Jorah."),
    P(S6E5, "tie", "表白", "乔拉向丹妮莉丝表白，坦白自己染上了灰鳞病。", "Confession", "Jorah tells Daenerys he loves her, and shows her his greyscale."),
    P(S7E5, "mas", "归来", "病愈的乔拉回到丹妮莉丝身边。", "Return", "Cured, Jorah comes back to her side."),
    P(S8E3, "mas", "战死", "长夜之战中，乔拉为保护丹妮莉丝战死。", "Fallen", "Jorah dies defending Daenerys in the Long Night.")),
  E("daenerys", "barristan",
    P(S3E1, "mas", "效忠", "巴利斯坦远渡重洋，向丹妮莉丝效忠。", "Sworn", "Barristan crosses the sea to swear himself to Daenerys."),
    P(S5E4, "mas", "殉职", "巴利斯坦死于鹰身女妖之子的伏击。", "Fallen", "Barristan dies in an ambush by the Sons of the Harpy.")),
  E("daenerys", "missandei",
    P(S3E1, "tie", "女译者", "弥桑黛替奴隶主给丹妮莉丝当翻译。", "The interpreter", "Missandei translates for the slaver who is dealing with Daenerys."),
    P(S3E4, "mas", "自由与追随", "丹妮莉丝还弥桑黛自由，她选择留下追随女王。", "Free, and loyal", "Freed by Daenerys, Missandei chooses to stay with her."),
    P(S8E4, "mas", "龙焰", "弥桑黛被瑟曦处死，临终喊出“龙焰”。", "Dracarys", "Executed by Cersei, Missandei’s last word is ‘Dracarys’.")),
  E("daenerys", "greyworm",
    P(S3E4, "mas", "无垢者", "丹妮莉丝解放无垢者，他们自愿追随她。", "The Unsullied", "Freed by Daenerys, the Unsullied choose to follow her."),
    P(S3E5, "mas", "统领", "无垢者推举灰虫子为统领。", "Commander", "The Unsullied choose Grey Worm as their commander.")),
  E("daenerys", "daario",
    P(S3E8, "mas", "投诚", "达里奥杀了另外两个队长，带次子团投奔丹妮莉丝。", "A turncoat", "Daario kills his fellow captains and brings the Second Sons to Daenerys."),
    P(S4E7, "love", "情人", "达里奥成了丹妮莉丝的情人。", "Lovers", "Daario becomes Daenerys’s lover."),
    P(S6E10, "love", "留下", "女王西征，把达里奥留在弥林。", "Left behind", "Sailing west, Daenerys leaves Daario in Meereen.")),
  E("daenerys", "illyrio",
    P(S1E1, "aid", "龙蛋", "伊利里欧促成婚事，送给丹妮莉丝三颗龙蛋。", "Dragon eggs", "Illyrio arranges the marriage and gives Daenerys three dragon eggs.")),
  E("viserys", "illyrio",
    P(S1E1, "aid", "收留", "伊利里欧收留了流亡的韦赛里斯，助他夺位。", "A patron", "Illyrio shelters the exiled Viserys and backs his claim.")),
  E("viserys", "drogo",
    P(S1E1, "aid", "交易", "韦赛里斯用妹妹换卓戈的军队。", "A bargain", "Viserys trades his sister for Drogo’s army."),
    P(S1E6, "foe", "金冠", "卓戈把熔化的黄金浇在韦赛里斯头上。", "The golden crown", "Drogo pours molten gold over Viserys’s head.")),
  E("daenerys", "mirri",
    P(S1E8, "aid", "救下", "丹妮莉丝从多斯拉克人手中救下弥丽。", "Saved", "Daenerys saves Mirri from the Dothraki."),
    P(S1E10, "foe", "火刑", "弥丽用血魔法报复，丹妮莉丝把她绑上火葬堆。", "The pyre", "Mirri takes her revenge with blood magic; Daenerys binds her to the pyre.")),
  E("drogo", "mirri",
    P(S1E8, "tie", "治伤", "弥丽为卓戈敷药治伤。", "The wound", "Mirri dresses Drogo’s wound."),
    P(S1E9, "tie", "血魔法", "卓戈垂危，弥丽在帐中施行血魔法。", "Blood magic", "As Drogo lies dying, Mirri works blood magic in his tent."),
    P(S1E10, "foe", "活死人", "血魔法让卓戈成了不言不动的活死人。", "A living husk", "The blood magic leaves Drogo alive but empty.")),
  E("daenerys", "hizdahr",
    P(S4E6, "tie", "收尸", "希兹达尔请求为被钉死的父亲收尸。", "A father’s body", "Hizdahr asks leave to bury his crucified father."),
    P(S5E5, "kin", "订婚", "丹妮莉丝为了安抚旧贵族，答应嫁给希兹达尔。", "Betrothed", "To win over the old nobility, Daenerys agrees to marry Hizdahr.")),
  E("daenerys", "tyrion",
    P(S5E7, "tie", "初见", "提利昂被带到丹妮莉丝面前。", "First meeting", "Tyrion is brought before Daenerys."),
    P(S6E10, "mas", "女王之手", "丹妮莉丝任命提利昂为女王之手。", "Hand of the Queen", "Daenerys names Tyrion her Hand."),
    P(S8E5, "tie", "背离", "丹妮莉丝不听提利昂的劝告，焚烧君临。", "Ignored", "Daenerys ignores Tyrion’s pleas and burns the city."),
    P(S8E6, "foe", "下狱", "提利昂扔掉首相胸针，被丹妮莉丝下狱。", "Arrested", "Tyrion throws down his pin and Daenerys has him arrested.")),
  E("daenerys", "varys",
    P(S6E10, "mas", "谋臣", "瓦里斯为丹妮莉丝争取到了维斯特洛的盟友。", "Counsellor", "Varys wins Daenerys allies in Westeros."),
    P(S7E2, "tie", "立誓", "丹妮莉丝质问瓦里斯的反复，瓦里斯说他效忠的是百姓。", "An oath", "Daenerys challenges Varys’s many loyalties; he says he serves the people."),
    P(S8E5, "foe", "处死", "瓦里斯散布琼恩的身世，丹妮莉丝用龙焰处死了他。", "Executed", "For spreading the truth of Jon’s birth, Daenerys burns Varys.")),
  E("jon", "daenerys",
    P(S7E3, "tie", "初见", "琼恩来到龙石岛，拒绝向丹妮莉丝屈膝，只求龙晶。", "First meeting", "At Dragonstone Jon will not bend the knee, and asks only for dragonglass."),
    P(S7E6, "love", "屈膝", "丹妮莉丝飞到长城以北救下琼恩，琼恩答应向她屈膝。", "Pledged", "Daenerys flies beyond the Wall to save him, and Jon pledges himself to her."),
    P(S7E7, "love", "相爱", "两人在北上的船上相爱。", "Lovers", "They become lovers on the voyage north."),
    P(S8E2, "tie", "姑侄", "琼恩告诉丹妮莉丝：他是雷加的儿子，她的侄子，继承顺序排在她前面。",
      "Aunt and nephew", "Jon tells Daenerys he is Rhaegar’s son — her nephew, and before her in the succession."),
    P(S8E6, "foe", "刺杀", "丹妮莉丝焚城之后，琼恩在铁王座前刺死了她。", "The dagger", "After the burning, Jon stabs Daenerys before the Iron Throne.")),
  E("daenerys", "nightking",
    P(S7E6, "foe", "韦赛利昂", "夜王射杀了丹妮莉丝的龙韦赛利昂。", "Viserion", "The Night King kills Daenerys’s dragon Viserion."),
    P(S8E3, "foe", "长夜", "丹妮莉丝骑龙与夜王在空中交锋。", "The Long Night", "Daenerys and the Night King fight dragon to dragon.")),
  E("daenerys", "olenna",
    P(S7E2, "aid", "献策", "奥莲娜劝丹妮莉丝别做绵羊，做一条龙。", "Advice", "Olenna advises Daenerys not to be a sheep, but a dragon.")),
  E("daenerys", "ellaria",
    P(S7E2, "aid", "结盟", "艾拉莉亚为复仇投奔丹妮莉丝。", "Alliance", "Ellaria joins Daenerys for revenge.")),
  E("daenerys", "yara",
    P(S6E9, "aid", "结盟", "雅拉献上舰队，丹妮莉丝答应帮她夺回铁群岛。", "Alliance", "Yara offers her fleet, and Daenerys promises to help her win back the Iron Islands.")),
  E("daenerys", "randyll",
    P(S7E5, "foe", "火刑", "蓝道拒绝屈膝，丹妮莉丝用龙焰烧死了他和他的儿子。", "Burned", "When Randyll will not kneel, Daenerys burns him and his son.")),
  E("daenerys", "sam",
    P(S8E1, "foe", "杀父之仇", "丹妮莉丝告诉山姆，她烧死了他的父亲和弟弟。", "His father", "Daenerys tells Sam she burned his father and brother.")),
  E("daenerys", "sansa",
    P(S8E1, "tie", "冷淡", "丹妮莉丝来到临冬城，珊莎冷淡相待。", "A cold welcome", "Sansa receives Daenerys coldly at Winterfell."),
    P(S8E4, "tie", "不信任", "珊莎始终不愿北境屈服于丹妮莉丝。", "Distrust", "Sansa will never let the North kneel to Daenerys.")),
  E("daenerys", "gendry",
    P(S8E4, "aid", "正名", "丹妮莉丝承认詹德利是劳勃之子，封他为风息堡公爵。", "Legitimised", "Daenerys legitimises Gendry as Robert’s son and Lord of Storm’s End.")),
  E("daenerys", "euron",
    P(S8E4, "foe", "射杀雷哥", "攸伦在龙石岛外伏击，射杀了雷哥。", "Rhaegal", "Euron ambushes Daenerys off Dragonstone and shoots down Rhaegal.")),
  E("daenerys", "melisandre",
    P(S7E2, "aid", "引荐", "梅丽珊卓来到龙石岛，劝丹妮莉丝召见琼恩。", "An introduction", "Melisandre comes to Dragonstone and urges Daenerys to summon Jon.")),
  E("aemon", "daenerys",
    P(S5E5, "kin", "远亲", "伊蒙学士听说远方的丹妮莉丝，叹息坦格利安家只剩她一人。", "Distant kin", "Maester Aemon hears of Daenerys and grieves that she is the last Targaryen and alone.")),
  E("jorah", "jeor",
    P(S1E9, "kin", "父子", "乔拉是老熊的儿子，因贩奴逃亡，父亲为此蒙羞。", "Father and son", "Jorah is the Old Bear’s son, who disgraced his father by selling slaves.")),
  E("jorah", "barristan",
    P(S4E8, "foe", "揭发", "巴利斯坦拿出劳勃的赦免令，揭穿了乔拉。", "Exposed", "Barristan brings out Robert’s pardon and exposes Jorah.")),
  E("jorah", "tyrion",
    P(S5E3, "foe", "劫持", "乔拉在瓦兰提斯劫持了提利昂，要把他献给女王。", "Kidnapped", "Jorah kidnaps Tyrion in Volantis to bring him to the queen."),
    P(S5E5, "tie", "同行", "两人一路同行，遭遇石民，乔拉染上灰鳞病。", "On the road", "Travelling together, they meet the Stone Men, and Jorah is infected.")),
  E("jorah", "sam",
    P(S7E2, "aid", "医治", "山姆冒险为乔拉剥除病皮，治好了他的灰鳞病。", "The cure", "Sam risks everything to cut away Jorah’s greyscale and cures him.")),
  E("jorah", "daario",
    P(S5E10, "tie", "并肩寻主", "两个爱着女王的男人一起去多斯拉克海寻找她。", "The search", "The two men who love the queen ride into the Dothraki sea to find her.")),
  E("jon", "jorah",
    P(S7E6, "aid", "长爪", "琼恩想把长爪还给乔拉，乔拉让他留着。", "Longclaw", "Jon offers Longclaw back to Jorah, who tells him to keep it.")),
  E("missandei", "greyworm",
    P(S4E4, "love", "暗生情愫", "弥桑黛教灰虫子说通用语，两人暗生情愫。", "Something unspoken", "Missandei teaches Grey Worm the Common Tongue, and something grows between them."),
    P(S7E2, "love", "相爱", "出征前夜，两人终于相爱。", "Lovers", "On the eve of war they become lovers."),
    P(S8E4, "love", "永别", "弥桑黛被瑟曦处死，灰虫子眼睁睁看着。", "Lost", "Grey Worm watches as Cersei executes Missandei.")),
  E("greyworm", "barristan",
    P(S5E4, "aid", "相救", "巴利斯坦为救灰虫子死在小巷里。", "Rescue", "Barristan dies in an alley saving Grey Worm.")),
  E("tyrion", "missandei",
    P(S5E10, "aid", "共治弥林", "丹妮莉丝离开后，提利昂与弥桑黛、灰虫子一同治理弥林。", "Governing Meereen", "With Daenerys gone, Tyrion governs Meereen with Missandei and Grey Worm.")),
  E("tyrion", "greyworm",
    P(S5E10, "tie", "共治弥林", "灰虫子对提利昂并不信任。", "Governing Meereen", "Grey Worm has little trust in Tyrion."),
    P(S8E6, "foe", "押送", "灰虫子押着提利昂去受审。", "Prisoner", "Grey Worm brings Tyrion to judgement.")),
  E("jon", "greyworm",
    P(S8E6, "foe", "囚徒", "琼恩刺死女王后被灰虫子关押。", "Prisoner", "After he kills the queen, Grey Worm holds Jon prisoner.")),
  # =============================================================== the Iron Islands
  E("balon", "theon",
    P(S2E2, "kin", "父子", "九年不见，巴隆对归来的儿子冷嘲热讽。", "Father and son", "Balon greets the son he has not seen for nine years with contempt."),
    P(S3E10, "tie", "弃子", "巴隆不肯为被阉割的席恩让步。", "Abandoned", "Balon will not bargain for a mutilated son.")),
  E("balon", "yara",
    P(S2E2, "kin", "父女", "雅拉是巴隆最信任的孩子。", "Father and daughter", "Yara is Balon’s most trusted child.")),
  E("balon", "euron",
    P(S6E2, "foe", "弑兄", "多年未归的弟弟攸伦在吊桥上把巴隆推了下去。", "Fratricide", "Euron, his long-absent brother, throws Balon from the bridge.")),
  E("yara", "theon",
    P(S2E2, "kin", "姐弟", "雅拉假装陌生人戏弄了刚回家的席恩。", "Sister and brother", "Yara makes a fool of her returning brother, pretending to be a stranger."),
    P(S4E6, "aid", "营救", "雅拉率人去恐怖堡营救席恩，席恩却不肯走。", "A rescue", "Yara raids the Dreadfort to rescue Theon, but he will not come."),
    P(S6E5, "aid", "支持", "席恩在选王会上支持雅拉。", "Support", "Theon speaks for Yara at the Kingsmoot."),
    P(S7E2, "tie", "跳海", "攸伦袭击船队，席恩丢下雅拉跳海逃生。", "Overboard", "When Euron attacks, Theon leaves Yara and jumps overboard."),
    P(S8E1, "aid", "救姐", "席恩救出了被攸伦俘虏的雅拉。", "Rescued", "Theon rescues Yara from Euron.")),
  E("yara", "euron",
    P(S6E2, "kin", "叔侄", "攸伦是雅拉的叔叔。", "Uncle and niece", "Euron is Yara’s uncle."),
    P(S6E5, "foe", "争位", "攸伦在选王会上夺去了雅拉的王位。", "The Kingsmoot", "Euron takes the crown from Yara at the Kingsmoot."),
    P(S7E2, "foe", "俘虏", "攸伦袭击船队，俘虏了雅拉。", "Captive", "Euron attacks the fleet and takes Yara prisoner.")),
  E("theon", "euron",
    P(S6E2, "kin", "叔侄", "攸伦是席恩的叔叔。", "Uncle and nephew", "Euron is Theon’s uncle."),
    P(S7E2, "foe", "跳海", "席恩面对攸伦的屠杀跳海逃生。", "Fled", "Facing Euron’s slaughter, Theon jumps overboard.")),
  E("theon", "nightking",
    P(S8E3, "foe", "最后的冲锋", "席恩冲向夜王，被他用长矛刺死。", "The last charge", "Theon charges the Night King and is killed with his own spear.")),
  E("ellaria", "euron",
    P(S7E2, "foe", "被俘", "攸伦截获了艾拉莉亚的船，俘虏了她和女儿泰妮丝。", "Captured", "Euron captures Ellaria and her daughter Tyene at sea."),
    P(S7E3, "foe", "献俘", "攸伦把艾拉莉亚母女献给瑟曦。", "A gift for Cersei", "Euron delivers Ellaria and her daughter to Cersei.")),
]
