# -*- coding: utf-8 -*-
"""Game of Thrones (TV) relationships, part 2: the Lannisters and King's Landing, the Baratheons, the Riverlands and the
Vale, the Reach and Dorne. Format as in edges_got_a.py."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import P, E  # noqa: E402
from episodes_got import *  # noqa: E402,F401,F403

EDGES_B = [
  # =============================================================== the Lannisters
  E("tywin", "cersei",
    P(S1E7, "kin", "父女", "瑟曦是泰温的女儿，一心渴望父亲的认可。", "Father and daughter", "Cersei is Tywin’s daughter, forever seeking his approval."),
    P(S4E10, "tie", "逼婚", "泰温要瑟曦嫁给洛拉斯，瑟曦当面说出了她和詹姆的关系。",
      "A marriage refused", "When Tywin orders her to marry Loras, Cersei tells him the truth about her and Jaime.")),
  E("tywin", "jaime",
    P(S1E7, "kin", "父子", "泰温对詹姆说，家族的传承比什么都重要。", "Father and son", "Tywin tells Jaime that nothing matters but the family’s legacy."),
    P(S4E1, "tie", "父子失和", "詹姆不肯离开御林铁卫回凯岩城继承家业，父子不欢而散。",
      "Estranged", "Jaime refuses to leave the Kingsguard and go home as heir to Casterly Rock, and they part in anger.")),
  E("tywin", "tyrion",
    P(S1E8, "tie", "父子", "泰温一向轻视这个侏儒儿子，只在用得着时才用他。", "Father and son", "Tywin has always despised his dwarf son, and uses him only when he must."),
    P(S1E10, "tie", "代理首相", "泰温派提利昂去君临代理首相，管住乔佛里。", "Acting Hand", "Tywin sends Tyrion to King’s Landing as acting Hand to rein in Joffrey."),
    P(S4E6, "foe", "审判", "泰温主持对提利昂弑君之罪的审判。", "The trial", "Tywin presides over Tyrion’s trial for regicide."),
    P(S4E10, "foe", "弑父", "提利昂在厕所里用十字弓射死了父亲。", "Patricide", "Tyrion kills his father with a crossbow on the privy.")),
  E("tywin", "kevan",
    P(S1E8, "kin", "兄弟", "凯冯是泰温的弟弟，一生追随兄长。", "Brothers", "Kevan is Tywin’s brother and has followed him all his life.")),
  E("tywin", "joffrey",
    P(S1E7, "kin", "祖孙", "泰温是乔佛里的外祖父。", "Grandfather and grandson", "Tywin is Joffrey’s grandfather."),
    P(S3E10, "tie", "管教", "泰温当着御前会议把乔佛里打发去睡觉。", "Sent to bed", "Before the small council, Tywin sends Joffrey to bed.")),
  E("tywin", "tommen",
    P(S1E7, "kin", "祖孙", "泰温是托曼的外祖父。", "Grandfather and grandson", "Tywin is Tommen’s grandfather."),
    P(S4E3, "tie", "教导", "在乔佛里灵前，泰温教托曼何为明君。", "A lesson", "Beside Joffrey’s body, Tywin teaches Tommen what makes a good king.")),
  E("tywin", "gregor",
    P(S1E7, "mas", "封臣", "魔山奉泰温之命在河间烧杀劫掠。", "Bannerman", "On Tywin’s orders, the Mountain ravages the Riverlands.")),
  E("tywin", "roose",
    P(S3E10, "aid", "密谋", "泰温承认：他与卢斯暗中勾结，许他北境守护之位。", "Conspirators", "Tywin admits he conspired with Roose, promising him the North.")),
  E("tywin", "walder",
    P(S3E10, "aid", "密谋", "泰温承认：红色婚礼是他与瓦德合谋策划的。", "Conspirators", "Tywin admits he plotted the Red Wedding with Walder Frey.")),
  E("tywin", "robb",
    P(S1E8, "foe", "宿敌", "罗柏南下，与泰温的大军对峙。", "Enemies", "Robb marches south against Tywin’s army."),
    P(S3E10, "foe", "红色婚礼", "泰温承认是他策划了红色婚礼：不费一兵一卒除掉了罗柏。", "The Red Wedding", "Tywin admits he arranged the Red Wedding, destroying Robb without risking a soldier.")),
  E("tywin", "olenna",
    P(S3E6, "tie", "谈婚论嫁", "泰温与奥莲娜唇枪舌剑，最终敲定洛拉斯娶瑟曦。", "Bargaining", "Tywin and Olenna cross swords over marriages and settle on Loras for Cersei.")),
  E("tywin", "oberyn",
    P(S4E3, "foe", "旧仇", "奥柏伦当面追问泰温：杀害伊莉亚是谁下的令。", "An old wound", "Oberyn presses Tywin about who gave the order to kill Elia.")),
  E("tywin", "shae",
    P(S4E10, "tie", "情妇", "提利昂越狱时，发现雪伊睡在泰温的床上。", "His mistress", "Escaping, Tyrion finds Shae in his father’s bed.")),
  E("tywin", "stannis",
    P(S2E9, "foe", "黑水河", "泰温率援军赶到，击溃了史坦尼斯。", "The Blackwater", "Tywin’s relief force breaks Stannis at the Blackwater.")),
  E("cersei", "jaime",
    P(S1E1, "love", "孪生情人", "瑟曦与詹姆是孪生姐弟，也是情人。", "Twins and lovers", "Cersei and Jaime are twins — and lovers."),
    P(S3E10, "love", "重逢", "失去右手的詹姆回到君临，与瑟曦重逢。", "Reunion", "Jaime, one-handed, comes home to Cersei."),
    P(S4E3, "tie", "灵前", "在乔佛里的灵前，詹姆强占了瑟曦。", "At the bier", "Beside Joffrey’s body, Jaime forces himself on Cersei."),
    P(S7E7, "tie", "决裂", "瑟曦背弃北上抗敌的承诺，詹姆离她而去。", "The break", "When Cersei breaks her word to fight the dead, Jaime leaves her."),
    P(S8E5, "love", "同死", "红堡崩塌，两人相拥，被埋在乱石之下。", "Together at the end", "As the Red Keep falls they die in each other’s arms.")),
  E("cersei", "tyrion",
    P(S1E1, "kin", "姐弟", "瑟曦恨这个害死母亲的弟弟。", "Sister and brother", "Cersei hates the brother whose birth killed their mother."),
    P(S2E1, "tie", "明争暗斗", "提利昂在君临代理首相，与瑟曦处处较劲。", "Rivals", "As acting Hand, Tyrion fights Cersei at every turn."),
    P(S4E2, "foe", "诬陷", "乔佛里死后，瑟曦咬定是提利昂下的毒。", "Accused", "After Joffrey’s death, Cersei swears Tyrion poisoned him."),
    P(S7E7, "tie", "密谈", "龙穴会谈后，提利昂独自去见瑟曦，说服她休战。", "A private talk", "After the Dragonpit summit Tyrion goes alone to Cersei and talks her into a truce.")),
  E("robert", "cersei",
    P(S1E1, "kin", "夫妻", "劳勃与瑟曦的婚姻是一桩政治联姻，两人彼此冷淡。", "Husband and wife", "Robert and Cersei’s is a political marriage, cold on both sides."),
    P(S1E7, "foe", "谋害", "瑟曦让蓝赛尔把劳勃灌醉，劳勃在狩猎中被野猪重伤。", "Murder", "Cersei has Lancel keep Robert drunk, and he is gored by a boar on the hunt.")),
  E("cersei", "joffrey",
    P(S1E1, "kin", "母子", "瑟曦溺爱乔佛里。", "Mother and son", "Cersei dotes on Joffrey."),
    P(S2E1, "tie", "掌掴", "瑟曦为乱伦流言打了乔佛里一巴掌，从此管不住他。", "The slap", "Cersei slaps Joffrey over the rumours of incest, and loses all hold over him."),
    P(S4E2, "kin", "丧子", "乔佛里中毒死在瑟曦怀里。", "Death of a son", "Joffrey dies of poison in his mother’s arms.")),
  E("cersei", "myrcella",
    P(S1E1, "kin", "母女", "弥赛菈是瑟曦的独女。", "Mother and daughter", "Myrcella is Cersei’s only daughter."),
    P(S2E6, "tie", "远嫁", "提利昂把弥赛菈送去多恩，瑟曦恨极了他。", "Sent away", "Tyrion sends Myrcella to Dorne, and Cersei never forgives him."),
    P(S6E1, "kin", "丧女", "弥赛菈的遗体被送回君临。", "A daughter lost", "Myrcella’s body comes home to King’s Landing.")),
  E("cersei", "tommen",
    P(S1E1, "kin", "母子", "托曼是瑟曦的幼子。", "Mother and son", "Tommen is Cersei’s younger son."),
    P(S6E6, "tie", "疏远", "托曼与大麻雀结盟，母子渐行渐远。", "Drifting apart", "Tommen sides with the High Sparrow, and drifts away from his mother."),
    P(S6E10, "kin", "丧子", "大圣堂爆炸后，托曼跳楼自尽。", "The last child", "After the Sept explodes, Tommen throws himself from a window.")),
  E("ned", "cersei",
    P(S1E7, "foe", "不胜则死", "艾德警告瑟曦带孩子出逃，瑟曦回答：玩权力的游戏，不胜则死。",
      "Win or die", "Ned warns Cersei to flee with her children; she answers that in the game of thrones you win or you die.")),
  E("cersei", "lancel",
    P(S2E4, "love", "私情", "提利昂识破瑟曦与表弟蓝赛尔私通，劳勃之死也有他的一份。", "An affair", "Tyrion discovers that Cersei has taken her cousin Lancel as a lover, and used him in Robert’s death."),
    P(S5E7, "foe", "告发", "皈依信仰的蓝赛尔向大麻雀供出了瑟曦。", "Denounced", "Lancel, now of the Faith, confesses everything about Cersei to the High Sparrow.")),
  E("cersei", "margaery",
    P(S3E2, "tie", "宫中对手", "玛格丽来到君临，瑟曦视她为对手。", "Rivals", "When Margaery comes to court, Cersei sees a rival."),
    P(S5E3, "foe", "王后之争", "玛格丽嫁给托曼，把瑟曦挤出宫廷。", "Two queens", "Margaery marries Tommen and edges Cersei out."),
    P(S6E10, "foe", "大圣堂", "瑟曦用野火炸毁大圣堂，玛格丽葬身火海。", "The Sept", "Cersei destroys the Sept with wildfire, and Margaery with it.")),
  E("cersei", "olenna",
    P(S4E2, "tie", "亲家", "两家联姻，两位老辣的女人互相提防。", "In-laws", "The two families are joined, and the two formidable women watch each other."),
    P(S6E10, "foe", "灭门之仇", "瑟曦炸毁大圣堂，奥莲娜的儿孙尽死。", "A family destroyed", "Cersei’s wildfire kills Olenna’s son and grandchildren."),
    P(S7E3, "foe", "毒酒", "瑟曦命詹姆攻下高庭，处死奥莲娜。", "Poison", "Cersei sends Jaime to take Highgarden and put Olenna to death.")),
  E("cersei", "highsparrow",
    P(S5E3, "aid", "利用", "瑟曦扶植大麻雀，想借信仰之手对付提利尔家。", "Use", "Cersei raises up the High Sparrow to strike at the Tyrells."),
    P(S5E7, "foe", "囚禁", "大麻雀反过来把瑟曦抓进了牢房。", "Imprisoned", "The High Sparrow turns on Cersei and imprisons her."),
    P(S6E10, "foe", "野火", "瑟曦用野火烧死了大麻雀。", "Wildfire", "Cersei burns the High Sparrow with wildfire.")),
  E("cersei", "qyburn",
    P(S5E2, "mas", "情报总管", "瑟曦任命科本为情报总管，他成了瑟曦最忠实的心腹。", "Master of Whisperers", "Cersei makes Qyburn her Master of Whisperers, and he becomes her most loyal servant."),
    P(S6E10, "mas", "女王之手", "瑟曦登基后，任命科本为女王之手。", "Hand of the Queen", "Crowned, Cersei names Qyburn her Hand.")),
  E("cersei", "gregor",
    P(S4E8, "mas", "勇士", "魔山作为瑟曦的勇士出战奥柏伦。", "Champion", "The Mountain fights Oberyn as Cersei’s champion."),
    P(S5E10, "mas", "无声的护卫", "复活的魔山成了瑟曦寸步不离的护卫。", "Silent guard", "The revived Mountain becomes Cersei’s constant guard.")),
  E("cersei", "euron",
    P(S7E1, "love", "求婚", "攸伦带着舰队来向瑟曦求婚。", "Courtship", "Euron comes with his fleet to ask for Cersei’s hand."),
    P(S8E1, "love", "同床", "攸伦带来黄金团，瑟曦与他同床。", "Bedfellows", "Euron brings the Golden Company, and Cersei takes him to bed.")),
  E("cersei", "ellaria",
    P(S5E10, "foe", "杀女之仇", "艾拉莉亚毒死了瑟曦的女儿弥赛菈。", "A daughter murdered", "Ellaria poisons Cersei’s daughter Myrcella."),
    P(S7E3, "foe", "以牙还牙", "瑟曦用同样的毒药毒死艾拉莉亚的女儿，让她眼看女儿死去。",
      "An eye for an eye", "Cersei poisons Ellaria’s daughter the same way and makes her watch.")),
  E("cersei", "littlefinger",
    P(S2E1, "tie", "权力即是权力", "小指头暗示瑟曦与詹姆的秘密，瑟曦命卫兵拿下他，又让他们放开。",
      "Power is power", "When Littlefinger hints at her secret, Cersei has the guards seize him — then lets him go.")),
  E("cersei", "bronn",
    P(S8E1, "mas", "雇佣", "瑟曦雇波隆去杀提利昂和詹姆。", "A contract", "Cersei hires Bronn to kill Tyrion and Jaime.")),
  E("cersei", "missandei",
    P(S8E4, "foe", "处决", "瑟曦在城头下令处死被俘的弥桑黛。", "Execution", "From the walls Cersei orders the captive Missandei put to death.")),
  E("cersei", "daenerys",
    P(S7E7, "foe", "龙穴会谈", "两位女王在龙穴会面，瑟曦假意答应休战。", "The Dragonpit", "The two queens meet at the Dragonpit, and Cersei pretends to agree to a truce."),
    P(S8E5, "foe", "焚城", "丹妮莉丝骑龙焚烧君临，瑟曦死在红堡废墟中。", "The burning", "Daenerys burns King’s Landing, and Cersei dies under the Red Keep.")),
  E("jaime", "tyrion",
    P(S1E1, "kin", "兄弟", "詹姆是家里唯一真心待提利昂好的人。", "Brothers", "Jaime is the only one of his family who has ever been kind to Tyrion."),
    P(S4E10, "aid", "放走", "詹姆把被判死刑的提利昂放出牢房。", "Freed", "Jaime lets Tyrion out of his death cell."),
    P(S7E5, "tie", "密会", "提利昂冒险潜入君临，与詹姆密会。", "A secret meeting", "Tyrion slips into King’s Landing to meet Jaime in secret."),
    P(S8E5, "aid", "最后的放行", "提利昂放走被捕的詹姆，让他带瑟曦出城。", "One last escape", "Tyrion frees the captured Jaime to get Cersei out of the city.")),
  E("jaime", "brienne",
    P(S2E8, "foe", "押送", "布蕾妮押送詹姆去君临，两人一路互相讥讽。", "Escort", "Brienne escorts Jaime to King’s Landing, and they trade insults all the way."),
    P(S3E3, "aid", "护她", "詹姆为保护布蕾妮不被侮辱，被砍掉了右手。", "Protection", "Jaime saves Brienne from rape, and loses his hand for it."),
    P(S3E7, "aid", "熊坑", "詹姆跳进熊坑救出布蕾妮。", "The bear pit", "Jaime leaps into the bear pit to save Brienne."),
    P(S4E4, "aid", "守誓剑", "詹姆把瓦雷利亚钢剑送给布蕾妮，托她寻找珊莎。", "Oathkeeper", "Jaime gives Brienne a Valyrian sword and asks her to find Sansa."),
    P(S8E2, "aid", "册封", "詹姆在临冬城封布蕾妮为骑士。", "Knighted", "At Winterfell, Jaime knights Brienne."),
    P(S8E4, "love", "相爱又离去", "长夜之战后两人相好，詹姆却回了君临找瑟曦。", "Lovers, then gone", "After the Long Night they become lovers, but Jaime goes back to Cersei.")),
  E("jaime", "aerys",
    P(S1E3, "foe", "弑君", "詹姆刺死了疯王，从此被叫做“弑君者”。", "Kingslayer", "Jaime killed the Mad King and has been called Kingslayer ever since."),
    P(S3E5, "foe", "真相", "詹姆说出真相：他杀疯王，是为了阻止疯王焚烧全城。", "The truth", "Jaime reveals he killed the king to stop him burning the city.")),
  E("jaime", "joffrey",
    P(S1E7, "kin", "生父", "乔佛里其实是詹姆与瑟曦的儿子。", "His father", "Joffrey is in truth the son of Jaime and Cersei.")),
  E("jaime", "myrcella",
    P(S1E7, "kin", "生父", "弥赛菈其实是詹姆的女儿。", "Her father", "Myrcella is in truth Jaime’s daughter."),
    P(S5E10, "kin", "父女相认", "弥赛菈在船上说她知道詹姆是她父亲，随即死在他怀里。", "Acknowledged", "On the ship Myrcella tells Jaime she knows he is her father, and dies in his arms.")),
  E("jaime", "tommen",
    P(S1E7, "kin", "生父", "托曼其实是詹姆的儿子。", "His father", "Tommen is in truth Jaime’s son."),
    P(S6E6, "tie", "被免职", "托曼与信仰结盟后，解除了詹姆的御林铁卫之职。", "Dismissed", "Allied with the Faith, Tommen dismisses Jaime from the Kingsguard.")),
  E("ned", "jaime",
    P(S1E5, "foe", "街头交锋", "提利昂被捕后，詹姆在街头截杀艾德的卫兵，与艾德交手。", "In the street", "After Tyrion’s arrest, Jaime attacks Ned and his guards in the street.")),
  E("robb", "jaime",
    P(S1E9, "foe", "阶下囚", "罗柏在呓语森林俘虏了詹姆。", "Prisoner", "Robb captures Jaime in the Whispering Wood.")),
  E("catelyn", "jaime",
    P(S2E8, "tie", "以人换人", "凯特琳私下放走詹姆，盼他换回两个女儿。", "A trade", "Catelyn secretly frees Jaime, hoping to win back her daughters.")),
  E("jaime", "bronn",
    P(S5E2, "aid", "同赴多恩", "波隆陪詹姆去多恩救弥赛菈。", "To Dorne", "Bronn goes with Jaime to Dorne to rescue Myrcella."),
    P(S7E4, "aid", "救命", "辎重之战中，波隆把冲向龙焰的詹姆扑进河里。", "A life saved", "In the loot train battle, Bronn knocks Jaime into the river out of the dragon’s fire.")),
  E("jaime", "olenna",
    P(S7E3, "foe", "毒酒", "詹姆给奥莲娜一杯毒酒，奥莲娜告诉他毒死乔佛里的是她。", "The poison cup", "Jaime gives Olenna poison, and she tells him she killed Joffrey.")),
  E("jaime", "euron",
    P(S8E5, "foe", "海滩决斗", "两人在红堡下的海滩上搏斗，攸伦被刺死。", "On the shore", "They fight on the shore below the Red Keep, and Euron dies.")),
  E("jaime", "blackfish",
    P(S6E7, "foe", "奔流城谈判", "詹姆劝黑鱼开城投降，黑鱼不为所动。", "Parley at Riverrun", "Jaime asks the Blackfish to yield Riverrun, and is refused.")),
  E("jaime", "edmure",
    P(S6E8, "foe", "逼降", "詹姆以艾德慕襁褓中的儿子相要挟，逼他下令打开奔流城。", "Surrender", "Threatening Edmure’s infant son, Jaime forces him to order Riverrun opened.")),
  E("jaime", "daenerys",
    P(S7E4, "foe", "冲锋", "辎重之战中，詹姆单骑冲向丹妮莉丝。", "The charge", "In the loot train battle, Jaime charges at Daenerys alone."),
    P(S8E2, "tie", "受审", "詹姆来到临冬城，丹妮莉丝要追究他杀死她父亲的罪。", "On trial", "At Winterfell Daenerys wants Jaime to answer for killing her father.")),
  E("tyrion", "shae",
    P(S1E9, "love", "情人", "提利昂与雪伊一夜长谈后相好。", "Lovers", "After a night of talk, Tyrion and Shae become lovers."),
    P(S4E2, "love", "赶她走", "为了保护雪伊，提利昂说狠话赶她离开君临。", "Sent away", "To save her, Tyrion drives Shae away with cruel words."),
    P(S4E6, "foe", "伪证", "雪伊在审判中作证，指控提利昂。", "Perjury", "At the trial Shae testifies against Tyrion."),
    P(S4E10, "foe", "掐死", "提利昂在父亲的床上发现雪伊，掐死了她。", "Strangled", "Tyrion finds Shae in his father’s bed and strangles her.")),
  E("tyrion", "bronn",
    P(S1E6, "mas", "决斗代理", "波隆为提利昂出战决斗，从此替他卖命。", "Champion", "Bronn fights for Tyrion in a trial by combat and stays in his pay."),
    P(S4E7, "tie", "拒绝出战", "波隆不肯冒死为提利昂对付魔山，两人友好分手。", "Declined", "Bronn will not fight the Mountain for Tyrion, and they part as friends."),
    P(S8E4, "tie", "讨价还价", "波隆奉瑟曦之命来杀两兄弟，最后用高庭换走了刀。", "A bargain", "Sent by Cersei to kill the brothers, Bronn sells his knife for Highgarden.")),
  E("tyrion", "pod",
    P(S2E2, "mas", "侍从", "波德被派来做提利昂的侍从。", "Squire", "Pod becomes Tyrion’s squire."),
    P(S2E9, "mas", "救主", "黑水河之战中，波德刺死了要暗杀提利昂的骑士。", "Saved", "At the Blackwater, Pod kills the knight trying to murder Tyrion.")),
  E("tyrion", "varys",
    P(S2E1, "tie", "斗智", "提利昂当上代理首相，与瓦里斯互相试探。", "Fencing", "As acting Hand, Tyrion and Varys take each other’s measure."),
    P(S4E10, "aid", "出逃", "瓦里斯把提利昂偷运出君临。", "Escape", "Varys smuggles Tyrion out of King’s Landing."),
    P(S8E5, "foe", "告发", "提利昂向丹妮莉丝告发了瓦里斯。", "Betrayal", "Tyrion reports Varys to Daenerys.")),
  E("tyrion", "joffrey",
    P(S1E2, "kin", "舅甥", "提利昂常当众教训乔佛里，还扇过他耳光。", "Uncle and nephew", "Tyrion has no patience with Joffrey and has slapped him more than once."),
    P(S4E2, "foe", "婚宴", "乔佛里在婚宴上百般羞辱提利昂，随即中毒身亡。", "The wedding", "Joffrey humiliates Tyrion at his wedding feast — and then dies of poison.")),
  E("tyrion", "lysa",
    P(S1E5, "foe", "天牢", "莱莎把提利昂关进鹰巢城的天牢。", "The sky cell", "Lysa puts Tyrion in a sky cell at the Eyrie.")),
  E("tyrion", "stannis",
    P(S2E9, "foe", "黑水河", "提利昂用野火烧毁了史坦尼斯的舰队。", "The Blackwater", "Tyrion destroys Stannis’s fleet with wildfire.")),
  E("tyrion", "pycelle",
    P(S2E3, "foe", "下狱", "提利昂识破派席尔是瑟曦的眼线，把他关进黑牢。", "Imprisoned", "Exposing Pycelle as Cersei’s man, Tyrion throws him in a cell.")),
  E("tyrion", "myrcella",
    P(S2E6, "tie", "安排远嫁", "提利昂把弥赛菈许配给多恩王子，送她远嫁。", "Sent to Dorne", "Tyrion betroths Myrcella to a Dornish prince and sends her away.")),
  E("tyrion", "oberyn",
    P(S4E7, "aid", "勇士", "奥柏伦为提利昂出战魔山。", "Champion", "Oberyn fights the Mountain as Tyrion’s champion.")),
  E("tyrion", "jon",
    P(S1E1, "aid", "私生子的铠甲", "提利昂对琼恩说：把私生子的身份当作铠甲穿在身上，就没人能用它伤害你。", "Like armour", "Tyrion tells Jon to wear being a bastard like armour, and it can never be used to hurt him."),
    P(S1E2, "aid", "同行北上", "提利昂与琼恩同去长城。", "North together", "Tyrion travels to the Wall with Jon."),
    P(S7E3, "aid", "龙石岛重逢", "琼恩来到龙石岛，提利昂为他引见丹妮莉丝。", "Dragonstone", "Jon comes to Dragonstone, and Tyrion brings him to Daenerys.")),
  E("kevan", "lancel",
    P(S1E8, "kin", "父子", "蓝赛尔是凯冯的儿子。", "Father and son", "Lancel is Kevan’s son.")),
  E("robert", "lancel",
    P(S1E3, "mas", "侍从", "蓝赛尔是劳勃国王的侍从。", "Squire", "Lancel is King Robert’s squire."),
    P(S1E7, "foe", "灌酒", "狩猎时，蓝赛尔一杯接一杯地给劳勃灌加了料的烈酒。", "The wine", "On the hunt, Lancel keeps Robert’s cup filled with strengthened wine.")),
  E("highsparrow", "lancel",
    P(S5E3, "mas", "皈依", "蓝赛尔皈依麻雀，追随大麻雀，后来加入信仰武装。", "Converted", "Lancel joins the Sparrows and later the Faith Militant.")),
  E("highsparrow", "tommen",
    P(S6E6, "aid", "结盟", "大麻雀说服托曼让王室与信仰结盟。", "Alliance", "The High Sparrow persuades Tommen to join the Crown to the Faith.")),
  E("qyburn", "pycelle",
    P(S6E10, "foe", "刺杀", "科本让孩子们用匕首刺死了派席尔。", "Murder", "Qyburn has his child spies stab Pycelle to death.")),
  E("qyburn", "gregor",
    P(S4E10, "aid", "救活", "科本用禁术救活了奄奄一息的魔山。", "Revived", "Qyburn saves the dying Mountain with forbidden arts."),
    P(S8E5, "foe", "摔死", "红堡崩塌时，魔山不再听命，把科本摔死在石头上。", "Turned on", "As the Red Keep falls the Mountain stops obeying and dashes Qyburn against the stones.")),
  E("sansa", "shae",
    P(S2E3, "mas", "侍女", "雪伊做了珊莎的侍女，真心护着她。", "Handmaid", "Shae becomes Sansa’s handmaid and truly looks after her.")),
  E("sandor", "gregor",
    P(S1E4, "kin", "兄弟", "魔山小时候把弟弟的脸按进火盆，兄弟俩从此结仇。", "Brothers", "As a boy the Mountain pushed his brother’s face into a brazier; they have hated each other since."),
    P(S7E7, "foe", "清算", "龙穴里，猎狗对魔山说：他们之间的账迟早要算。", "A reckoning", "At the Dragonpit, the Hound tells the Mountain their reckoning is coming."),
    P(S8E5, "foe", "同归于尽", "猎狗抱着魔山一同坠入火海。", "Together into the fire", "The Hound carries the Mountain with him down into the fire.")),
  E("joffrey", "sandor",
    P(S1E1, "mas", "贴身护卫", "猎狗是乔佛里的贴身护卫。", "Sworn shield", "The Hound is Joffrey’s sworn shield."),
    P(S2E9, "tie", "弃王而去", "黑水河之战中，猎狗弃乔佛里而去。", "Desertion", "At the Blackwater the Hound abandons Joffrey.")),
  E("loras", "gregor",
    P(S1E5, "foe", "比武", "洛拉斯骑一匹发情的母马击败魔山，魔山要杀他。", "The joust", "Loras unhorses the Mountain with a mare in heat, and the Mountain tries to kill him.")),
  E("loras", "sandor",
    P(S1E5, "aid", "救命", "猎狗挡住魔山，救了洛拉斯。", "A life saved", "The Hound stops the Mountain and saves Loras.")),
  E("oberyn", "gregor",
    P(S4E8, "foe", "比武审判", "奥柏伦逼魔山认罪，被他挤碎了头颅。", "Trial by combat", "Oberyn demands a confession from the Mountain, who crushes his skull.")),
  E("beric", "gregor",
    P(S1E6, "foe", "缉拿", "艾德派贝里去缉拿在河间烧杀的魔山。", "Sent after him", "Ned sends Beric to bring the Mountain to justice.")),
  # =============================================================== the court
  E("robert", "ned",
    P(S1E1, "aid", "生死之交", "劳勃与艾德一同长大，一同起兵，情同手足。", "Brothers in arms", "Robert and Ned grew up together and fought the rebellion together."),
    P(S1E5, "tie", "争执", "劳勃要刺杀丹妮莉丝，艾德愤而辞去首相之职。", "A quarrel", "When Robert orders Daenerys killed, Ned resigns as Hand."),
    P(S1E7, "aid", "托孤", "劳勃临终任命艾德为摄政，辅佐乔佛里。", "Last wishes", "Dying, Robert names Ned regent for Joffrey.")),
  E("robert", "lyanna",
    P(S1E1, "love", "未婚妻", "劳勃一生最爱莱安娜，至今在她墓前念念不忘。", "His betrothed", "Lyanna was the love of Robert’s life; he still mourns her at her tomb.")),
  E("robert", "rhaegar",
    P(S1E1, "foe", "宿敌", "劳勃说，他每晚都在梦里再杀雷加一次。", "Old enemies", "Robert says he kills Rhaegar again every night in his dreams."),
    P(S1E2, "foe", "三叉戟河", "劳勃在三叉戟河之战中亲手杀了雷加。", "The Trident", "Robert killed Rhaegar with his own hands at the Trident.")),
  E("robert", "aerys",
    P(S1E2, "foe", "推翻", "劳勃起兵推翻了疯王，登上铁王座。", "Overthrown", "Robert rose against the Mad King and took the Iron Throne.")),
  E("robert", "joffrey",
    P(S1E1, "kin", "父子", "乔佛里是劳勃的王储。", "Father and son", "Joffrey is Robert’s heir."),
    P(S1E7, "tie", "并非亲生", "艾德查明：乔佛里根本不是劳勃的儿子。", "Not his son", "Ned learns that Joffrey is not Robert’s son at all.")),
  E("robert", "myrcella",
    P(S1E1, "kin", "父女", "弥赛菈是劳勃名义上的女儿。", "Father and daughter", "Myrcella is Robert’s daughter in name.")),
  E("robert", "tommen",
    P(S1E1, "kin", "父子", "托曼是劳勃名义上的幼子。", "Father and son", "Tommen is Robert’s younger son in name.")),
  E("robert", "stannis",
    P(S2E1, "kin", "兄弟", "史坦尼斯是劳勃的大弟，认为哥哥从未善待自己。", "Brothers", "Stannis is Robert’s next brother, who feels he was never given his due.")),
  E("robert", "renly",
    P(S1E3, "kin", "兄弟", "蓝礼是劳勃最小的弟弟，在御前会议任职。", "Brothers", "Renly is Robert’s youngest brother and sits on his council.")),
  E("robert", "gendry",
    P(S1E4, "kin", "私生子", "詹德利是劳勃的私生子，自己并不知道。", "Bastard son", "Gendry is Robert’s bastard, though he does not know it.")),
  E("robert", "jonarryn",
    P(S1E1, "aid", "养父与首相", "琼恩·艾林是劳勃少年时的监护人，后来做了他的首相。", "Foster-father and Hand", "Jon Arryn fostered Robert as a boy and served as his Hand.")),
  E("robert", "barristan",
    P(S1E3, "mas", "御林铁卫", "巴利斯坦是劳勃的御林铁卫队长。", "Kingsguard", "Barristan commands Robert’s Kingsguard.")),
  E("robert", "daenerys",
    P(S1E5, "foe", "刺杀令", "劳勃得知丹妮莉丝怀孕，下令刺杀她。", "A death warrant", "Learning Daenerys is with child, Robert orders her killed.")),
  E("ned", "littlefinger",
    P(S1E3, "tie", "同僚", "小指头表面上帮艾德查案。", "Colleagues", "Littlefinger seems to help Ned with his inquiries."),
    P(S1E7, "foe", "出卖", "小指头临阵倒戈，用匕首抵住了艾德的喉咙。", "Betrayal", "At the decisive moment Littlefinger puts a knife to Ned’s throat.")),
  E("ned", "varys",
    P(S1E3, "tie", "同僚", "瓦里斯是御前会议里最难捉摸的人。", "Colleagues", "Varys is the hardest man on the council to read."),
    P(S1E5, "tie", "暗中示警", "比武大会期间，瓦里斯私下提醒艾德：兰尼斯特家想在比武中害死劳勃。", "A warning", "During the tourney Varys warns Ned privately that the Lannisters meant to kill Robert in the joust."),
    P(S1E9, "tie", "牢中劝降", "瓦里斯到牢里劝艾德认罪，说珊莎的性命也许就系于此。", "In the cells", "Varys comes to Ned’s cell and urges him to confess: Sansa’s life may depend on it.")),
  E("ned", "jonarryn",
    P(S1E1, "aid", "养父", "琼恩·艾林是艾德少年时的监护人。", "Foster-father", "Jon Arryn fostered Ned as a boy.")),
  E("ned", "joffrey",
    P(S1E9, "foe", "斩首", "乔佛里不顾劝阻，当众下令砍下艾德的头。", "Beheaded", "Against all counsel, Joffrey has Ned beheaded in public.")),
  E("ned", "gendry",
    P(S1E4, "aid", "线索", "艾德找到詹德利，看出他是劳勃的私生子。", "A clue", "Ned finds Gendry and sees he is Robert’s son.")),
  E("ned", "barristan",
    P(S1E3, "aid", "同僚", "巴利斯坦是艾德敬重的老骑士。", "Colleagues", "Barristan is an old knight Ned respects.")),
  E("ned", "syrio",
    P(S1E3, "aid", "雇佣", "艾德请西里欧教艾莉亚剑术。", "Hired", "Ned hires Syrio to teach Arya.")),
  E("littlefinger", "catelyn",
    P(S1E3, "tie", "旧情", "小指头少年时爱慕凯特琳，他告诉凯特琳匕首是提利昂的。", "Old love", "In love with Catelyn since boyhood, Littlefinger tells her the dagger was Tyrion’s."),
    P(S2E4, "tie", "送还遗骨", "小指头把艾德的遗骨送还凯特琳，还向她示爱。", "Ned’s bones", "Littlefinger brings Catelyn Ned’s bones and makes advances.")),
  E("littlefinger", "varys",
    P(S1E3, "tie", "宿敌", "两人同在御前会议，互相刺探。", "Rivals", "On the council the two spymasters watch each other."),
    P(S3E6, "tie", "混乱是阶梯", "小指头对瓦里斯说：混乱不是深渊，而是阶梯。", "Chaos is a ladder", "Littlefinger tells Varys that chaos is not a pit but a ladder.")),
  E("littlefinger", "lysa",
    P(S4E5, "love", "成婚", "莱莎终于嫁给了少年时就爱慕的小指头。", "Married", "Lysa marries Littlefinger, whom she has loved since girlhood."),
    P(S4E7, "foe", "月门", "小指头说他只爱过凯特琳，把莱莎推下了月门。", "The Moon Door", "Telling her he only ever loved Catelyn, Littlefinger pushes Lysa through the Moon Door.")),
  E("littlefinger", "jonarryn",
    P(S4E5, "foe", "幕后黑手", "毒杀琼恩·艾林的主谋是小指头。", "The hand behind it", "Littlefinger was behind Jon Arryn’s poisoning.")),
  E("littlefinger", "robin",
    P(S4E8, "mas", "监护人", "莱莎死后，小指头成了罗宾的监护人和谷地守护。", "Guardian", "After Lysa’s death Littlefinger becomes Robin’s guardian and Lord Protector of the Vale.")),
  E("littlefinger", "olenna",
    P(S4E4, "aid", "合谋", "小指头与奥莲娜合谋，在婚宴上毒死乔佛里。", "Conspirators", "Littlefinger and Olenna plot Joffrey’s poisoning.")),
  E("varys", "illyrio",
    P(S1E5, "aid", "密谋", "艾莉亚在红堡地下偷听到两人密谋。", "Conspirators", "Arya overhears them plotting under the Red Keep.")),
  E("cersei", "pycelle",
    P(S2E3, "mas", "眼线", "派席尔暗中为瑟曦通风报信。", "Her informer", "Pycelle carries tales to Cersei.")),
  # =============================================================== the Baratheons
  E("stannis", "renly",
    P(S2E1, "kin", "兄弟", "两兄弟都自立为王。", "Brothers", "Both brothers claim the crown."),
    P(S2E4, "foe", "争位", "史坦尼斯与蓝礼会面，谁也不肯让步。", "Rival kings", "Stannis and Renly parley; neither will yield."),
    P(S2E5, "foe", "弑弟", "梅丽珊卓生下的影子刺死了蓝礼。", "Fratricide", "A shadow born of Melisandre kills Renly.")),
  E("stannis", "selyse",
    P(S3E5, "kin", "夫妻", "赛丽丝是史坦尼斯的妻子，比丈夫更狂热地信奉光之王。", "Husband and wife", "Selyse is Stannis’s wife, more devoted to the Lord of Light than he is.")),
  E("stannis", "shireen",
    P(S3E5, "kin", "父女", "史坦尼斯爱女儿，只是不善表达。", "Father and daughter", "Stannis loves his daughter, though he cannot show it."),
    P(S5E9, "foe", "献祭", "史坦尼斯把希琳献祭给光之王。", "The sacrifice", "Stannis burns Shireen to the Lord of Light.")),
  E("stannis", "davos",
    P(S2E1, "mas", "洋葱骑士", "戴佛斯是史坦尼斯最忠心的骑士。", "The Onion Knight", "Davos is Stannis’s most loyal knight."),
    P(S3E1, "tie", "下狱", "戴佛斯想杀梅丽珊卓，被史坦尼斯关进地牢。", "Imprisoned", "When Davos tries to kill Melisandre, Stannis throws him in a cell."),
    P(S3E8, "mas", "重获信任", "史坦尼斯放出戴佛斯，要他发誓不再对梅丽珊卓动手，重新倚重他。", "Trusted again", "Stannis releases Davos, makes him swear never to raise a hand against Melisandre, and relies on him once more.")),
  E("stannis", "melisandre",
    P(S2E1, "tie", "神的使者", "梅丽珊卓说史坦尼斯是光之王选中的人，他渐渐深信不疑。", "Chosen", "Melisandre tells Stannis he is the Lord of Light’s chosen, and he comes to believe it."),
    P(S2E2, "love", "私情", "梅丽珊卓引诱史坦尼斯，答应为他生下儿子。", "Lovers", "Melisandre seduces Stannis and promises him a son."),
    P(S5E9, "tie", "献祭", "梅丽珊卓劝史坦尼斯献祭女儿。", "The sacrifice", "Melisandre persuades Stannis to sacrifice his daughter.")),
  E("stannis", "brienne",
    P(S5E10, "foe", "处决", "布蕾妮以谋杀蓝礼之罪处决了史坦尼斯。", "Execution", "Brienne executes Stannis for the murder of Renly.")),
  E("stannis", "mance",
    P(S4E10, "foe", "俘虏", "史坦尼斯击溃野人大军，俘虏了曼斯。", "Captured", "Stannis routs the wildling army and takes Mance prisoner."),
    P(S5E1, "foe", "火刑", "曼斯拒绝屈膝，史坦尼斯把他绑上火刑柱。", "The stake", "When Mance will not kneel, Stannis burns him.")),
  E("stannis", "jon",
    P(S4E10, "tie", "长城上的国王", "史坦尼斯来到长城，与琼恩结识。", "A king at the Wall", "Stannis comes to the Wall and meets Jon."),
    P(S5E2, "tie", "许以临冬城", "史坦尼斯提出要让琼恩成为临冬城公爵。", "Winterfell offered", "Stannis offers to make Jon Lord of Winterfell."),
    P(S5E3, "tie", "婉拒", "琼恩婉拒了史坦尼斯的提议，留在守夜人。", "Declined", "Jon turns Stannis down and stays with the Watch.")),
  E("stannis", "gendry",
    P(S3E8, "kin", "叔侄", "詹德利是劳勃的私生子，史坦尼斯的侄子；他的血被用来施法。", "Uncle and nephew", "Gendry is Stannis’s bastard nephew, whose blood is used in Melisandre’s spell.")),
  E("stannis", "ramsay",
    P(S5E9, "foe", "夜袭", "拉姆斯带二十人夜袭，烧了史坦尼斯的粮草。", "The raid", "Ramsay and twenty men burn Stannis’s supplies in the night."),
    P(S5E10, "foe", "大败", "波顿骑兵击溃了史坦尼斯的残军。", "Defeat", "The Bolton cavalry destroys what is left of Stannis’s army.")),
  E("stannis", "joffrey",
    P(S2E1, "foe", "揭发", "史坦尼斯宣布乔佛里是乱伦所生，无权继承王位。", "Denounced", "Stannis proclaims Joffrey a bastard born of incest.")),
  E("renly", "loras",
    P(S1E5, "love", "恋人", "蓝礼与洛拉斯秘密相爱。", "Lovers", "Renly and Loras are secret lovers.")),
  E("renly", "margaery",
    P(S2E3, "kin", "有名无实", "蓝礼娶了玛格丽，却始终没有圆房。", "In name only", "Renly marries Margaery but never consummates it.")),
  E("renly", "brienne",
    P(S2E3, "mas", "护卫", "布蕾妮在比武中赢得了加入蓝礼护卫的资格。", "His guard", "Brienne wins a place in Renly’s guard in the lists."),
    P(S2E5, "mas", "死在眼前", "蓝礼在布蕾妮怀里被影子刺死。", "In her arms", "Renly is killed by the shadow in Brienne’s arms.")),
  E("catelyn", "renly",
    P(S2E3, "tie", "求盟", "凯特琳为罗柏出使，劝蓝礼结盟。", "An embassy", "Catelyn comes to ask Renly to ally with Robb.")),
  E("renly", "melisandre",
    P(S2E5, "foe", "影子", "梅丽珊卓生下的影子刺死了蓝礼。", "The shadow", "The shadow Melisandre bore kills Renly.")),
  E("selyse", "shireen",
    P(S3E5, "kin", "母女", "赛丽丝对女儿冷淡严厉。", "Mother and daughter", "Selyse is cold and harsh to her daughter."),
    P(S5E9, "kin", "火刑柱前", "希琳被烧时，赛丽丝终于崩溃，哭喊着冲上前去。", "At the stake", "As Shireen burns, Selyse breaks and runs to her, screaming.")),
  E("melisandre", "selyse",
    P(S3E5, "aid", "信徒", "赛丽丝是梅丽珊卓最虔诚的信徒。", "Devotee", "Selyse is Melisandre’s most devoted follower.")),
  E("shireen", "davos",
    P(S3E5, "aid", "教读书", "希琳教不识字的戴佛斯读书。", "Lessons", "Shireen teaches Davos to read."),
    P(S6E9, "aid", "木雕小鹿", "戴佛斯在灰烬中找到他为希琳刻的木雕小鹿。", "The wooden stag", "Davos finds the wooden stag he carved for her in the ashes.")),
  E("melisandre", "shireen",
    P(S5E9, "foe", "火刑", "梅丽珊卓主持了希琳的火刑。", "The burning", "Melisandre presides as Shireen is burned.")),
  E("shireen", "gilly",
    P(S5E2, "aid", "教读书", "希琳在黑城堡教吉莉读书。", "Lessons", "At Castle Black, Shireen teaches Gilly to read.")),
  E("davos", "melisandre",
    P(S2E1, "foe", "不信", "戴佛斯从一开始就不信任红袍女。", "Distrust", "Davos mistrusts the red woman from the first."),
    P(S6E2, "tie", "请她一试", "戴佛斯请梅丽珊卓试着复活琼恩。", "One more try", "Davos asks Melisandre to try to bring Jon back."),
    P(S6E10, "foe", "揭穿", "戴佛斯当众揭穿梅丽珊卓烧死了希琳。", "Exposed", "Davos exposes Melisandre for burning Shireen.")),
  E("davos", "gendry",
    P(S3E10, "aid", "放走", "戴佛斯放詹德利乘小船逃走。", "Set free", "Davos sets Gendry free in a rowing boat."),
    P(S7E5, "aid", "找回", "戴佛斯在君临找到正在打铁的詹德利。", "Found again", "Davos finds Gendry at a forge in King’s Landing.")),
  E("davos", "jon",
    P(S4E10, "tie", "结识", "戴佛斯随史坦尼斯来到长城，结识了琼恩。", "Acquaintance", "Davos comes to the Wall with Stannis and meets Jon."),
    P(S6E1, "aid", "守护", "戴佛斯守着琼恩的遗体，挡住索恩的人。", "Guarding him", "Davos guards Jon’s body against Thorne’s men."),
    P(S6E10, "mas", "谋臣", "戴佛斯成了北境之王最信任的谋臣。", "Counsellor", "Davos becomes the King in the North’s most trusted adviser.")),
  E("melisandre", "gendry",
    P(S3E6, "tie", "王血", "梅丽珊卓买下詹德利，要用他的王者之血献祭。", "King’s blood", "Melisandre buys Gendry for his king’s blood.")),
  E("melisandre", "thoros",
    P(S3E6, "tie", "同道", "两位红袍祭司相遇，梅丽珊卓惊讶于索罗斯能让人复活。", "Fellow priests", "The two red priests meet, and Melisandre is astonished that Thoros can raise the dead.")),
  E("melisandre", "jon",
    P(S5E4, "tie", "引诱", "梅丽珊卓夜里来找琼恩，被他拒绝。", "Seduction", "Melisandre comes to Jon in the night and he turns her away."),
    P(S6E2, "tie", "复活", "梅丽珊卓让死去的琼恩复活。", "Resurrection", "Melisandre brings Jon back from the dead."),
    P(S6E10, "foe", "驱逐", "琼恩把梅丽珊卓逐出北境。", "Banished", "Jon banishes Melisandre from the North.")),
  E("brienne", "pod",
    P(S4E4, "mas", "侍从", "波德随布蕾妮出发，做了她的侍从。", "Squire", "Pod rides out with Brienne as her squire."),
    P(S8E6, "aid", "同列铁卫", "布蕾妮做了御林铁卫队长，波德也是铁卫一员。", "Kingsguard", "Brienne commands King Bran’s Kingsguard, with Pod among them.")),
  E("brienne", "tormund",
    P(S6E4, "love", "单相思", "托蒙德对布蕾妮一见倾心，布蕾妮避之不及。", "Smitten", "Tormund is smitten with Brienne, who wants nothing to do with it.")),
  E("brienne", "sandor",
    P(S4E10, "foe", "决斗", "布蕾妮与猎狗为争夺艾莉亚恶斗，猎狗重伤坠崖。", "The fight", "Brienne and the Hound fight over Arya, and he falls broken from a cliff.")),
  E("catelyn", "brienne",
    P(S2E5, "mas", "效忠", "蓝礼死后，布蕾妮向凯特琳宣誓效忠。", "Sworn", "After Renly’s death, Brienne swears herself to Catelyn."),
    P(S2E8, "mas", "托付", "凯特琳派布蕾妮押送詹姆去君临换回女儿。", "A charge", "Catelyn sends Brienne to take Jaime to King’s Landing in exchange for her daughters.")),
  # =============================================================== the Riverlands and the Vale
  E("walder", "robb",
    P(S1E9, "aid", "过河之约", "罗柏答应娶瓦德的一个女儿，换取渡河和佛雷家的兵马。", "The crossing", "Robb promises to marry one of Walder’s daughters in return for the crossing and Frey swords."),
    P(S2E10, "tie", "背约", "罗柏另娶泰莉莎，背弃了与佛雷家的婚约。", "A broken promise", "Robb marries Talisa and breaks his word to the Freys."),
    P(S3E9, "foe", "红色婚礼", "瓦德在婚宴上下令屠杀，罗柏被杀。", "The Red Wedding", "Walder gives the signal for the massacre in which Robb dies.")),
  E("walder", "catelyn",
    P(S1E9, "aid", "谈判", "凯特琳亲自到孪河城，与瓦德谈妥借道之约。", "Negotiation", "Catelyn goes into the Twins herself to strike the bargain."),
    P(S3E9, "foe", "以命相胁", "凯特琳挟持瓦德的妻子，求他放过罗柏，瓦德不为所动。", "A knife to his wife", "Catelyn threatens Walder’s wife to save Robb; Walder does not care.")),
  E("walder", "edmure",
    P(S3E6, "tie", "婚约", "瓦德要艾德慕娶自己的女儿萝丝琳。", "Betrothal", "Walder demands that Edmure marry his daughter Roslin."),
    P(S3E9, "foe", "囚禁", "红色婚礼后，艾德慕被关在孪河城地牢里。", "Imprisoned", "After the Red Wedding Edmure is thrown in the dungeons of the Twins.")),
  E("walder", "roose",
    P(S3E9, "aid", "合谋", "瓦德与卢斯合谋发动红色婚礼。", "Conspirators", "Walder and Roose carry out the Red Wedding together.")),
  E("edmure", "blackfish",
    P(S3E3, "kin", "叔侄", "黑鱼看不上侄子的鲁莽，却总替他收拾残局。", "Uncle and nephew", "The Blackfish despairs of his nephew’s rashness, and keeps covering for him.")),
  E("blackfish", "brienne",
    P(S6E8, "tie", "奔流城", "布蕾妮劝黑鱼随她去北境，黑鱼不肯离开奔流城。", "Riverrun", "Brienne asks the Blackfish to come north with her; he will not leave Riverrun.")),
  E("beric", "thoros",
    P(S3E4, "aid", "复活之恩", "索罗斯一次次用光之王的力量救活贝里。", "Raised again and again", "Thoros brings Beric back from death time after time.")),
  E("beric", "sandor",
    P(S3E5, "foe", "决斗审判", "猎狗在决斗审判中杀死贝里，贝里随即复活。", "Trial by combat", "The Hound kills Beric in a trial by combat; Beric rises again."),
    P(S6E8, "aid", "收留", "猎狗加入了贝里的无旗兄弟会。", "Taken in", "The Hound joins Beric’s Brotherhood.")),
  E("beric", "gendry",
    P(S3E6, "foe", "出卖", "无旗兄弟会把詹德利卖给了梅丽珊卓。", "Sold", "The Brotherhood sells Gendry to Melisandre.")),
  E("beric", "jon",
    P(S7E5, "aid", "同赴塞外", "贝里随琼恩到长城以北捉尸鬼。", "Beyond the Wall", "Beric goes north with Jon to catch a wight.")),
  E("thoros", "sandor",
    P(S6E8, "aid", "同伴", "猎狗加入兄弟会，与索罗斯一同北上。", "Comrades", "The Hound joins the Brotherhood and travels north with Thoros.")),
  E("lysa", "robin",
    P(S1E5, "kin", "母子", "莱莎对儿子溺爱至极。", "Mother and son", "Lysa smothers her son with love.")),
  E("lysa", "jonarryn",
    P(S1E5, "kin", "夫妻", "莱莎是琼恩·艾林的遗孀。", "Husband and wife", "Lysa is Jon Arryn’s widow."),
    P(S4E5, "foe", "毒杀", "莱莎在小指头的指使下毒死了丈夫。", "Poisoned", "At Littlefinger’s urging, Lysa poisoned her husband.")),
  E("lysa", "sansa",
    P(S4E5, "kin", "姨甥", "莱莎是珊莎的姨妈。", "Aunt and niece", "Lysa is Sansa’s aunt."),
    P(S4E7, "foe", "妒火", "莱莎嫉妒珊莎，要把她推下月门。", "Jealousy", "Jealous of Sansa, Lysa tries to push her through the Moon Door.")),
  E("jonarryn", "gendry",
    P(S1E4, "tie", "线索", "琼恩·艾林死前曾去看过詹德利。", "The trail", "Before he died, Jon Arryn had been to see Gendry.")),
  # =============================================================== the Reach and Dorne
  E("olenna", "margaery",
    P(S3E2, "kin", "祖孙", "奥莲娜是玛格丽的祖母和导师。", "Grandmother and granddaughter", "Olenna is Margaery’s grandmother and teacher."),
    P(S4E4, "kin", "暗示", "奥莲娜向玛格丽暗示，不会让她嫁给一个疯子。", "A hint", "Olenna lets Margaery understand she would never leave her married to a monster."),
    P(S6E10, "kin", "痛失", "玛格丽死在大圣堂的野火中。", "Lost", "Margaery dies in the wildfire at the Sept.")),
  E("olenna", "loras",
    P(S3E2, "kin", "祖孙", "洛拉斯是奥莲娜的孙子。", "Grandmother and grandson", "Loras is Olenna’s grandson.")),
  E("olenna", "mace",
    P(S4E2, "kin", "母子", "奥莲娜看不上自己的儿子，家里大事都由她做主。", "Mother and son", "Olenna has little use for her son and makes the family’s decisions herself.")),
  E("olenna", "joffrey",
    P(S4E4, "foe", "暗中下毒", "乔佛里之死的毒药，出自奥莲娜之手。", "The poisoner", "The poison that killed Joffrey came from Olenna."),
    P(S7E3, "foe", "亲口承认", "奥莲娜临死前向詹姆承认：是她毒死了乔佛里。", "Confession", "Dying, Olenna tells Jaime she poisoned Joffrey.")),
  E("olenna", "ellaria",
    P(S6E10, "aid", "结盟", "两个失去亲人的女人在多恩结盟，投奔丹妮莉丝。", "Alliance", "Two bereaved women make common cause in Dorne and turn to Daenerys.")),
  E("olenna", "sansa",
    P(S3E2, "aid", "直言", "奥莲娜请珊莎说出乔佛里的真面目。", "Plain speaking", "Olenna asks Sansa what Joffrey is really like.")),
  E("margaery", "loras",
    P(S2E3, "kin", "兄妹", "玛格丽与哥哥洛拉斯无话不谈。", "Brother and sister", "Margaery and Loras keep no secrets from each other."),
    P(S5E6, "kin", "作伪证", "为了救哥哥，玛格丽在信仰法庭上作伪证。", "Perjury", "To save her brother, Margaery lies before the Faith.")),
  E("margaery", "joffrey",
    P(S2E10, "love", "婚约", "玛格丽与乔佛里订婚。", "Betrothed", "Margaery is betrothed to Joffrey."),
    P(S4E2, "love", "婚礼", "婚宴上，新郎乔佛里中毒身亡。", "The wedding", "At the wedding feast her bridegroom dies of poison.")),
  E("margaery", "tommen",
    P(S4E4, "love", "示好", "乔佛里死后，玛格丽夜里去看年幼的托曼。", "A visit", "After Joffrey’s death, Margaery pays young Tommen a night visit."),
    P(S5E3, "love", "成婚", "玛格丽嫁给托曼，成为王后。", "Married", "Margaery marries Tommen and becomes queen."),
    P(S6E10, "love", "永别", "玛格丽死在大圣堂，托曼随即跳楼。", "The end", "Margaery dies in the Sept, and Tommen follows her.")),
  E("margaery", "highsparrow",
    P(S5E6, "foe", "囚禁", "大麻雀以作伪证之罪把玛格丽关进牢里。", "Imprisoned", "The High Sparrow imprisons Margaery for perjury."),
    P(S6E6, "tie", "假意皈依", "玛格丽假装虔诚，赢得了大麻雀的信任。", "Feigned faith", "Margaery feigns piety to win the High Sparrow’s trust.")),
  E("margaery", "sansa",
    P(S3E2, "aid", "结交", "玛格丽亲近珊莎，套问乔佛里的为人。", "Friendship", "Margaery befriends Sansa and draws her out about Joffrey."),
    P(S3E4, "aid", "提亲", "玛格丽向珊莎透露：提利尔家想让她嫁给洛拉斯。", "A match", "Margaery lets Sansa know the Tyrells want her to marry Loras.")),
  E("loras", "sansa",
    P(S3E5, "love", "未成的婚约", "提利尔家打算让珊莎嫁给洛拉斯，被泰温抢先破坏。", "A match that never was", "The Tyrells plan to marry Sansa to Loras; Tywin forestalls them.")),
  E("mace", "margaery",
    P(S4E2, "kin", "父女", "玛格丽是梅斯的女儿。", "Father and daughter", "Margaery is Mace’s daughter.")),
  E("mace", "loras",
    P(S4E2, "kin", "父子", "洛拉斯是梅斯的儿子。", "Father and son", "Loras is Mace’s son.")),
  E("loras", "highsparrow",
    P(S5E4, "foe", "逮捕", "大麻雀以鸡奸之罪逮捕了洛拉斯。", "Arrested", "The High Sparrow arrests Loras for sodomy."),
    P(S6E10, "foe", "认罪", "洛拉斯受审认罪，被剃发刻额。", "Confession", "Loras confesses at his trial and is shorn and branded.")),
  E("randyll", "sam",
    P(S6E6, "kin", "父子", "蓝道当年逼长子去长城，如今仍当众羞辱他。", "Father and son", "Randyll sent his eldest to the Wall and humiliates him still."),
    P(S8E1, "kin", "死讯", "山姆得知父亲和弟弟被丹妮莉丝烧死。", "The news", "Sam learns that Daenerys burned his father and brother.")),
  E("randyll", "jaime",
    P(S7E3, "aid", "倒戈", "蓝道背弃提利尔家，随詹姆攻打高庭。", "Turncoat", "Randyll abandons the Tyrells to take Highgarden with Jaime.")),
  E("olenna", "randyll",
    P(S6E6, "mas", "封臣", "蓝道是提利尔家麾下的大将。", "Bannerman", "Randyll is the Tyrells’ greatest soldier."),
    P(S7E3, "foe", "背弃", "蓝道倒向兰尼斯特，背弃了提利尔家。", "Betrayal", "Randyll goes over to the Lannisters.")),
  E("oberyn", "ellaria",
    P(S4E1, "love", "情人", "艾拉莉亚是奥柏伦的情人，两人形影不离。", "Lovers", "Ellaria is Oberyn’s paramour and his constant companion.")),
  E("oberyn", "doran",
    P(S5E2, "kin", "兄弟", "道朗是奥柏伦的哥哥，不肯为弟弟报仇开战。", "Brothers", "Doran is Oberyn’s brother, who will not go to war to avenge him.")),
  E("ellaria", "doran",
    P(S5E2, "tie", "不满", "艾拉莉亚不满道朗的软弱。", "Discontent", "Ellaria despises Doran’s caution."),
    P(S6E1, "foe", "弑君", "艾拉莉亚刺死了道朗，夺取多恩。", "Murder", "Ellaria stabs Doran and seizes Dorne.")),
  E("ellaria", "myrcella",
    P(S5E10, "foe", "毒吻", "艾拉莉亚用唇上的毒药毒死了弥赛菈。", "A poisoned kiss", "Ellaria kills Myrcella with poison on her lips.")),
  E("doran", "myrcella",
    P(S5E2, "aid", "保护", "道朗保护弥赛菈，不让艾拉莉亚伤害她。", "Protection", "Doran keeps Myrcella safe from Ellaria."),
    P(S5E9, "aid", "放行", "道朗放弥赛菈随詹姆回君临。", "Sent home", "Doran lets Myrcella go home with Jaime.")),
]
