# -*- coding: utf-8 -*-
"""Game of Thrones (TV) relationships, part 1: the Starks, the North, the Night's Watch and beyond the Wall.

Each relationship has phases P(episode, type, zh label, zh text, en label, en text[, ref]). For `mas` (allegiance) the
first person is the lord. Types: kin 亲缘 · love 情缘 · mas 效忠 · aid 友盟 · foe 仇敌 · tie 纠葛
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import P, E  # noqa: E402
from episodes_got import *  # noqa: E402,F401,F403

EDGES_A = [
  # =============================================================== Ned and Catelyn's family
  E("ned", "catelyn",
    P(S1E1, "kin", "夫妻", "两人奉父命成婚，多年来相敬相爱，育有五个孩子。",
      "Husband and wife", "Married by their families’ arrangement, they have grown to love each other and have five children.")),
  E("ned", "robb",
    P(S1E1, "kin", "父子", "罗柏是艾德的长子和继承人；艾德南下后，把临冬城交给了他。",
      "Father and son", "Robb is Ned’s eldest son and heir, left in charge of Winterfell when Ned goes south."),
    P(S1E8, "kin", "起兵救父", "艾德在君临被捕，罗柏召集北境诸侯南下，要救出父亲。",
      "To war for his father", "When Ned is arrested in King’s Landing, Robb calls the Northern lords to march south and free him.")),
  E("ned", "sansa",
    P(S1E1, "kin", "父女", "珊莎是艾德的长女，随父亲南下君临，准备嫁给王子。",
      "Father and daughter", "Ned’s elder daughter goes south with him, to be married to the prince."),
    P(S1E8, "kin", "当众求情", "珊莎当众求乔佛里饶恕父亲，乔佛里答应只要艾德认罪便从轻发落。",
      "Pleading for her father", "Sansa begs Joffrey publicly to spare her father; he promises mercy if Ned confesses."),
    P(S1E9, "kin", "刑台", "艾德认了罪，乔佛里却在刑台上反悔，当着珊莎的面下令斩首。",
      "The scaffold", "Ned confesses, but on the scaffold Joffrey changes his mind and orders the beheading before Sansa’s eyes.")),
  E("ned", "arya",
    P(S1E1, "kin", "父女", "艾德最懂这个野性难驯的小女儿。",
      "Father and daughter", "Ned understands his wild younger daughter better than anyone."),
    P(S1E3, "kin", "请师学剑", "艾德发现艾莉亚藏着一把剑，没有没收，反而替她请来布拉佛斯的剑师。",
      "A sword master", "Finding Arya’s hidden sword, Ned does not take it away but hires her a Braavosi sword master."),
    P(S1E9, "kin", "人群中的诀别", "艾德被押上刑台时，在人群中看见了艾莉亚，示意尤伦护住她。",
      "A last look", "On the scaffold Ned sees Arya in the crowd and signals to Yoren to protect her.")),
  E("ned", "bran",
    P(S1E1, "kin", "父子", "布兰是艾德的次子；艾德带他去看处决逃兵，教他担当。",
      "Father and son", "Bran is Ned’s second son; Ned takes him to see a deserter executed, to teach him what a lord must do.")),
  E("ned", "rickon",
    P(S1E1, "kin", "父子", "瑞肯是艾德最小的儿子。", "Father and son", "Rickon is Ned’s youngest son.")),
  E("ned", "jon",
    P(S1E1, "kin", "父子（私生子）", "艾德从战场上带回私生子琼恩，在临冬城把他养大，却从不肯说他的生母是谁。",
      "Father and bastard", "Ned brought his bastard Jon home from the war and raised him at Winterfell, but has never told him who his mother was."),
    P(S1E2, "kin", "临别之约", "分别时艾德答应琼恩，下次见面时告诉他母亲的事——两人再也没有见面。",
      "A promise", "At parting Ned promises to tell Jon about his mother the next time they meet. They never meet again."),
    P(S6E10, "kin", "舅甥", "布兰的幻象揭示：琼恩是莱安娜的儿子，艾德为了保护他，一辈子把他说成自己的私生子。",
      "Uncle and nephew", "Bran’s vision reveals that Jon is Lyanna’s son, whom Ned protected all his life by calling him his own bastard.")),
  E("ned", "benjen",
    P(S1E1, "kin", "兄弟", "班扬是艾德的弟弟，在长城当守夜人。", "Brothers", "Benjen is Ned’s younger brother, a brother of the Night’s Watch.")),
  E("ned", "lyanna",
    P(S1E1, "kin", "兄妹", "艾德把早逝的妹妹莱安娜葬在临冬城的墓窖里。", "Brother and sister", "Ned buried his sister Lyanna in the crypts of Winterfell."),
    P(S6E10, "kin", "临终托孤", "在极乐塔里，垂死的莱安娜把刚出生的孩子托付给哥哥，求他保护孩子。",
      "A dying wish", "In the Tower of Joy the dying Lyanna gives her newborn son to her brother and begs him to keep the child safe.")),
  E("catelyn", "robb",
    P(S1E1, "kin", "母子", "凯特琳是罗柏的母亲，也是他最倚重的谋士。", "Mother and son", "Catelyn is Robb’s mother and his most trusted counsellor."),
    P(S2E8, "tie", "私放詹姆", "凯特琳私自放走詹姆，罗柏大怒，把母亲看管起来。",
      "Jaime set free", "When Catelyn frees Jaime on her own, Robb is furious and has her confined."),
    P(S3E9, "kin", "母子同死", "红色婚礼上，凯特琳挟持瓦德的妻子求他放过罗柏，罗柏仍被刺死，她随即被杀。",
      "Dying together", "At the Red Wedding Catelyn holds a knife to Walder’s wife and begs for Robb’s life; he is killed anyway, and so is she.")),
  E("catelyn", "sansa",
    P(S1E1, "kin", "母女", "珊莎最像母亲，规矩、体面，向往南方。", "Mother and daughter", "Sansa is most like her mother — proper, gracious, dreaming of the south.")),
  E("catelyn", "arya",
    P(S1E1, "kin", "母女", "凯特琳为这个不肯守规矩的小女儿操碎了心。", "Mother and daughter", "Arya, who will not behave like a lady, is her mother’s constant worry."),
    P(S3E9, "kin", "近在咫尺", "艾莉亚赶到孪河城时，母亲就在城里；她没能进去。",
      "So close", "Arya reaches the Twins while her mother is inside; she never gets in.")),
  E("catelyn", "bran",
    P(S1E1, "kin", "母子", "凯特琳最怕布兰到处攀爬。", "Mother and son", "Catelyn lives in fear of Bran’s climbing."),
    P(S1E2, "kin", "守在床边", "布兰坠楼昏迷，凯特琳寸步不离，徒手抓住刺客的刀刃，救了他。",
      "At his bedside", "When Bran lies unconscious she never leaves him, and saves him from an assassin by grabbing the blade barehanded.")),
  E("catelyn", "rickon",
    P(S1E1, "kin", "母子", "瑞肯是凯特琳最小的孩子。", "Mother and son", "Rickon is Catelyn’s youngest child.")),
  E("catelyn", "jon",
    P(S1E1, "tie", "冷眼", "在凯特琳眼里，琼恩是丈夫不忠的证据，她从不给他好脸色。",
      "Cold shoulder", "To Catelyn, Jon is the living proof of her husband’s infidelity, and she never warms to him."),
    P(S1E2, "tie", "赶他出去", "琼恩临行前去看昏迷的布兰，凯特琳冷冷地叫他出去。",
      "“Get out”", "When Jon comes to say goodbye to the unconscious Bran, Catelyn coldly tells him to leave.")),
  # =============================================================== the Stark children
  E("robb", "jon",
    P(S1E1, "kin", "兄弟", "两人同年出生，一起长大，情同手足。", "Brothers", "Born the same year and raised together, they are as close as brothers can be."),
    P(S1E2, "kin", "道别", "琼恩北上长城前，两人在临冬城的庭院里道别，从此再没见面。",
      "Goodbye", "They say goodbye as Jon leaves for the Wall, and never see each other again.")),
  E("robb", "bran",
    P(S1E1, "kin", "兄弟", "罗柏是布兰的大哥。", "Brothers", "Robb is Bran’s eldest brother."),
    P(S1E6, "kin", "狼林相救", "布兰在狼林里遭野人袭击，罗柏赶来救下了他。",
      "To the rescue", "When wildlings attack Bran in the wolfswood, Robb rides to his rescue.")),
  E("sansa", "arya",
    P(S1E1, "tie", "姐妹不和", "珊莎文静守礼，艾莉亚野性难驯，两人从小就合不来。",
      "Sisters at odds", "Sansa is proper and ladylike, Arya wild; they have never got along."),
    P(S7E4, "kin", "重逢", "离散多年后，两姐妹在临冬城墓窖里父亲的石像前重逢。",
      "Reunited", "After years apart the sisters meet again before their father’s statue in the crypts of Winterfell."),
    P(S7E6, "tie", "猜忌", "艾莉亚拿着珊莎当年劝哥哥归顺的信质问她，小指头趁机挑拨两人。",
      "Suspicion", "Arya confronts Sansa with the letter she once wrote urging Robb to submit, and Littlefinger works to set them against each other."),
    P(S7E7, "kin", "联手", "姐妹联手揭穿小指头，在大厅里当众处决了他。",
      "Together", "The sisters join forces to expose Littlefinger and execute him in the great hall.")),
  E("jon", "arya",
    P(S1E1, "kin", "兄妹", "在所有兄弟姐妹中，琼恩和艾莉亚最亲。", "Brother and sister", "Of all his siblings, Jon is closest to Arya."),
    P(S1E2, "kin", "缝衣针", "琼恩北上前，送给艾莉亚一把细剑，她给它起名“缝衣针”。",
      "Needle", "Before he goes north Jon gives Arya a slim sword, which she names Needle."),
    P(S8E1, "kin", "重逢", "两人在临冬城的神木林里重逢，艾莉亚亮出了那把缝衣针。",
      "Reunited", "They meet again in the godswood at Winterfell, and Arya shows him Needle.")),
  E("jon", "sansa",
    P(S1E1, "kin", "兄妹", "珊莎小时候并不亲近这个私生的哥哥。", "Brother and sister", "As a girl, Sansa kept her bastard half-brother at a distance."),
    P(S6E4, "kin", "重逢", "珊莎逃到黑城堡，兄妹相拥；她劝琼恩夺回临冬城。",
      "Reunited", "Sansa reaches Castle Black and they embrace; she urges Jon to take back Winterfell."),
    P(S6E9, "tie", "各有主张", "珊莎早已瞒着琼恩写信给小指头求援，兄妹俩为作战计划争执不下。",
      "Different plans", "Sansa has secretly written to Littlefinger for help, and she and Jon quarrel over how to fight."),
    P(S8E4, "tie", "说出秘密", "琼恩要妹妹们发誓保守身世的秘密，珊莎转身就告诉了提利昂。",
      "The secret", "Jon makes his sisters swear to keep the secret of his birth; Sansa tells Tyrion at once."),
    P(S8E6, "kin", "北境女王", "琼恩被流放，珊莎加冕为北境女王，兄妹在码头道别。",
      "Farewell", "Jon goes into exile as Sansa is crowned Queen in the North; they say goodbye at the docks.")),
  E("jon", "bran",
    P(S1E1, "kin", "兄弟", "琼恩是布兰的哥哥。", "Brothers", "Jon is Bran’s elder half-brother."),
    P(S1E2, "kin", "告别", "琼恩北上前，到昏迷的布兰床前道别。", "Farewell", "Before going north Jon says goodbye at the unconscious Bran’s bedside."),
    P(S4E5, "kin", "擦肩而过", "卡斯特堡里，布兰听见琼恩的声音，却为了继续北上而没有出声。",
      "So near", "At Craster’s Keep Bran hears Jon’s voice but keeps silent so he can go on north."),
    P(S8E1, "kin", "重逢", "琼恩回到临冬城，布兰已经成了三眼乌鸦。", "Reunited", "Jon comes home to find Bran has become the Three-eyed Raven.")),
  E("jon", "rickon",
    P(S1E1, "kin", "兄弟", "琼恩是瑞肯的哥哥。", "Brothers", "Jon is Rickon’s elder half-brother."),
    P(S6E9, "kin", "只差一步", "拉姆斯放瑞肯在两军之间奔跑，琼恩策马去救，只差一步。",
      "One step short", "Ramsay sends Rickon running between the armies; Jon rides to save him and is a step too late.")),
  E("bran", "rickon",
    P(S1E1, "kin", "兄弟", "布兰与瑞肯同在临冬城长大。", "Brothers", "Bran and Rickon grow up together at Winterfell."),
    P(S3E9, "kin", "分别", "布兰执意北上，让欧莎带瑞肯去投奔安柏家。", "Parting", "Bran insists on going north and sends Rickon with Osha to the Umbers.")),
  E("sansa", "bran",
    P(S1E1, "kin", "姐弟", "珊莎是布兰的姐姐。", "Sister and brother", "Sansa is Bran’s elder sister."),
    P(S7E3, "kin", "重逢", "布兰回到临冬城，珊莎发现弟弟已经变成了另一个人。",
      "Reunited", "Bran comes home, and Sansa finds her brother has become someone else."),
    P(S8E6, "kin", "国王与女王", "布兰被推举为六国之王，珊莎成为独立的北境女王。",
      "King and queen", "Bran is chosen King of the Six Kingdoms, and Sansa becomes queen of an independent North.")),
  E("arya", "bran",
    P(S1E1, "kin", "姐弟", "艾莉亚是布兰的姐姐。", "Sister and brother", "Arya is Bran’s elder sister."),
    P(S7E4, "kin", "匕首", "布兰把小指头送他的瓦雷利亚钢匕首交给了艾莉亚。",
      "The dagger", "Bran gives Arya the Valyrian steel dagger Littlefinger gave him."),
    P(S8E3, "kin", "神木林", "夜王走向布兰时，艾莉亚用那把匕首从背后刺穿了他。",
      "In the godswood", "As the Night King reaches Bran, Arya stabs him with that same dagger.")),
  E("robb", "talisa",
    P(S2E4, "love", "一见倾心", "罗柏在战场上遇见正在救治伤兵的泰莉莎，被她吸引。",
      "Love at first sight", "Robb meets Talisa on the battlefield tending the wounded, and is drawn to her."),
    P(S2E10, "love", "秘密成婚", "罗柏违背与佛雷家的婚约，娶了泰莉莎。", "A secret wedding", "Breaking his promise to the Freys, Robb marries Talisa."),
    P(S3E9, "love", "同死", "红色婚礼上，泰莉莎和腹中的孩子先被刺死，罗柏随后被杀。",
      "Dying together", "At the Red Wedding Talisa and her unborn child are stabbed first, then Robb.")),
  E("catelyn", "edmure",
    P(S3E3, "kin", "姐弟", "艾德慕是凯特琳的弟弟，奔流城的继承人。", "Sister and brother", "Edmure is Catelyn’s younger brother, heir to Riverrun.")),
  E("catelyn", "blackfish",
    P(S3E3, "kin", "叔侄", "黑鱼是凯特琳的叔叔，从小看着她长大。", "Uncle and niece", "The Blackfish is Catelyn’s uncle, who watched her grow up.")),
  E("catelyn", "lysa",
    P(S1E5, "kin", "姐妹", "凯特琳押着提利昂来投奔妹妹莱莎，莱莎却只顾疑神疑鬼，不肯出兵。",
      "Sisters", "Catelyn brings Tyrion to her younger sister Lysa, who is lost in her fears and will not send help.")),
  E("robb", "edmure",
    P(S3E3, "kin", "舅甥", "艾德慕是罗柏的舅舅，却擅自出兵坏了罗柏的部署。",
      "Uncle and nephew", "Edmure is Robb’s uncle, and spoils his plans by attacking on his own."),
    P(S3E6, "kin", "代娶", "为了弥补罗柏背弃的婚约，艾德慕答应代他娶佛雷家的萝丝琳。",
      "A wedding in his place", "To make up for Robb’s broken promise, Edmure agrees to marry Roslin Frey in his stead.")),
  E("ned", "theon",
    P(S1E1, "tie", "养子与人质", "铁群岛叛乱失败后，艾德把巴隆的儿子席恩带回临冬城，当作养子，也当作人质。",
      "Ward and hostage", "After the ironborn rebellion Ned took Balon’s son Theon to Winterfell as his ward — and his hostage.")),
  E("robb", "theon",
    P(S1E1, "aid", "如同兄弟", "席恩与罗柏一同长大，情同手足。", "Like brothers", "Theon and Robb grew up together as close as brothers."),
    P(S2E1, "aid", "出使铁群岛", "罗柏派席恩回铁群岛，请他父亲出兵。", "An envoy", "Robb sends Theon home to the Iron Islands to ask his father for ships."),
    P(S2E6, "foe", "背叛", "席恩背叛罗柏，偷袭夺下了临冬城。", "Betrayal", "Theon betrays Robb and seizes Winterfell.")),
  E("bran", "theon",
    P(S1E6, "aid", "救命", "布兰在狼林遇险，席恩一箭射死了野人。", "To the rescue", "When Bran is attacked in the wolfswood, Theon shoots a wildling dead."),
    P(S2E6, "foe", "夺城", "席恩占领临冬城，逼布兰当众把城堡交给他。", "Winterfell taken", "Theon seizes Winterfell and makes Bran yield it to him publicly."),
    P(S8E2, "aid", "守护", "席恩回到临冬城，自请在神木林里守护布兰。", "Guarding him", "Theon comes back to Winterfell and asks to guard Bran in the godswood."),
    P(S8E3, "aid", "好人", "席恩战至最后一人，布兰告诉他：你是个好人。随后席恩冲向夜王而死。",
      "A good man", "When Theon has fought to the last, Bran tells him he is a good man, and Theon dies charging the Night King.")),
  E("sansa", "theon",
    P(S5E5, "tie", "重逢", "珊莎在临冬城认出了被称作“臭佬”的席恩，以为他杀了布兰和瑞肯。",
      "Reunited", "At Winterfell Sansa recognises Theon in ‘Reek’, and hates him for murdering Bran and Rickon, as she believes."),
    P(S5E7, "foe", "告密", "珊莎请席恩点灯求援，席恩却把此事告诉了拉姆斯。", "Betrayed", "Sansa asks Theon to light a candle for help; he tells Ramsay instead."),
    P(S5E10, "aid", "一起跳下", "席恩杀了要射死珊莎的米兰达，带她从城墙上跳下逃走。",
      "The leap", "Theon kills Myranda as she threatens Sansa and leaps from the walls with her."),
    P(S8E2, "aid", "重逢", "席恩回到临冬城，珊莎紧紧拥抱了他。", "Welcome home", "When Theon returns to Winterfell, Sansa embraces him.")),
  # =============================================================== the Starks and the world
  E("sansa", "joffrey",
    P(S1E2, "love", "婚约", "珊莎满心欢喜地与王子订婚，在三叉戟河边替他说话。",
      "Betrothed", "Delighted to be betrothed to the prince, Sansa takes his side at the Trident."),
    P(S1E10, "foe", "折磨", "乔佛里杀了她父亲，又逼她去看城头示众的首级。",
      "Torment", "Joffrey kills her father and makes her look at his head on the walls."),
    P(S2E10, "foe", "解除婚约", "乔佛里改娶玛格丽，却不放珊莎走。",
      "Set aside", "Joffrey sets Sansa aside for Margaery but will not let her go.")),
  E("sansa", "cersei",
    P(S1E8, "tie", "人质", "艾德被捕后，珊莎成了瑟曦手里的人质。", "Hostage", "After Ned’s arrest Sansa is a hostage in Cersei’s hands."),
    P(S2E9, "tie", "围城夜", "黑水河之战那夜，瑟曦对珊莎讲了许多冷酷的道理。",
      "The night of the siege", "On the night of the Blackwater, Cersei gives Sansa a merciless lesson in how the world works.")),
  E("sansa", "tyrion",
    P(S2E4, "aid", "解围", "乔佛里当众让人剥衣毒打珊莎，提利昂出面制止。",
      "Rescue", "When Joffrey has Sansa stripped and beaten in public, Tyrion stops it."),
    P(S3E8, "kin", "被迫成婚", "泰温逼两人成婚；新婚之夜，提利昂没有碰她。",
      "A forced marriage", "Tywin forces them to marry; on their wedding night Tyrion leaves her alone."),
    P(S8E4, "tie", "托付秘密", "珊莎把琼恩的身世告诉提利昂，明知他会转告丹妮莉丝。",
      "The secret", "Sansa tells Tyrion the truth of Jon’s birth, knowing he will tell Daenerys.")),
  E("sansa", "sandor",
    P(S1E4, "tie", "伤疤的来历", "比武大会上，珊莎从小指头那里听说了猎狗被哥哥烧伤的往事。",
      "The scar", "At the tourney, Littlefinger tells Sansa how the Hound’s brother burned his face."),
    P(S2E6, "aid", "救命", "暴乱中，猎狗把珊莎从暴民手里救了出来。", "A rescue", "In the riot the Hound pulls Sansa out of the mob."),
    P(S2E9, "tie", "提议出逃", "黑水河之战那夜，猎狗提出带珊莎回北方，她没有走。",
      "An offer", "On the night of the Blackwater the Hound offers to take Sansa north; she stays."),
    P(S8E4, "tie", "重逢", "猎狗与珊莎在临冬城重逢，说她已经不再是当年的小鸟。",
      "Reunited", "The Hound meets Sansa again at Winterfell and sees she is no longer the little bird she was.")),
  E("sansa", "littlefinger",
    P(S4E3, "tie", "救她出城", "乔佛里死后，小指头带珊莎逃出君临。", "Escape", "After Joffrey’s death, Littlefinger gets Sansa out of King’s Landing."),
    P(S5E3, "tie", "安排婚事", "小指头带她回临冬城，把她嫁给了拉姆斯·波顿。",
      "A marriage", "Littlefinger takes her back to Winterfell and gives her to Ramsay Bolton."),
    P(S6E5, "tie", "质问", "珊莎当面质问小指头的出卖，却不得不考虑他的谷地骑兵。",
      "Confronted", "Sansa confronts Littlefinger with his betrayal, but cannot ignore his knights of the Vale."),
    P(S6E9, "aid", "谷地援军", "决战关头，小指头带谷地骑兵赶到，扭转了战局。",
      "The Vale arrives", "At the decisive moment Littlefinger brings the knights of the Vale and turns the battle."),
    P(S7E7, "foe", "审判", "珊莎当众宣判小指头的罪行，艾莉亚处决了他。",
      "The trial", "Sansa pronounces judgement on Littlefinger before the lords, and Arya executes him.")),
  E("sansa", "ramsay",
    P(S5E3, "tie", "婚约", "小指头把珊莎许配给拉姆斯，她回到了临冬城。", "Betrothed", "Littlefinger betroths Sansa to Ramsay and she returns to Winterfell."),
    P(S5E6, "foe", "凌辱", "新婚之夜，拉姆斯强暴了珊莎，此后一直虐待她。", "Abuse", "Ramsay rapes Sansa on their wedding night and abuses her from then on."),
    P(S6E9, "foe", "复仇", "私生子之战后，珊莎放出拉姆斯饿了七天的猎犬。", "Revenge", "After the battle, Sansa sets Ramsay’s starving hounds on him.")),
  E("brienne", "sansa",
    P(S5E2, "tie", "被拒", "布蕾妮找到珊莎，珊莎在小指头身边，不肯接受她的保护。",
      "Refused", "Brienne finds Sansa with Littlefinger, and Sansa refuses her protection."),
    P(S6E1, "mas", "宣誓效忠", "布蕾妮从猎犬下救出珊莎，正式宣誓为她效命。", "Sworn", "Brienne saves Sansa from the hounds and swears to serve her.")),
  E("arya", "syrio",
    P(S1E3, "aid", "师徒", "西里欧教艾莉亚“水舞”剑术，也教她看清事物的真相。",
      "Master and pupil", "Syrio teaches Arya water dancing, and to see things as they truly are."),
    P(S1E8, "aid", "今天不行", "兰尼斯特士兵来抓艾莉亚，西里欧用木剑挡住他们，让她逃走。",
      "Not today", "When Lannister men come for Arya, Syrio holds them off with a wooden sword so she can run.")),
  E("arya", "joffrey",
    P(S1E2, "foe", "三叉戟河", "乔佛里欺负屠夫的儿子，艾莉亚出手，她的冰原狼咬伤了王子。",
      "At the Trident", "When Joffrey bullies a butcher’s boy, Arya fights back and her direwolf bites the prince.")),
  E("arya", "sandor",
    P(S1E2, "foe", "屠夫之子", "猎狗奉命杀死了艾莉亚的朋友、屠夫的儿子米凯。",
      "The butcher’s boy", "On orders, the Hound kills Arya’s friend Mycah, the butcher’s boy."),
    P(S3E7, "foe", "劫持", "猎狗劫走艾莉亚，想把她卖给罗柏换赎金。", "Kidnapped", "The Hound seizes Arya, meaning to sell her back to Robb."),
    P(S4E1, "tie", "同行", "两人一路流浪，艾莉亚从猎狗身上学会了在乱世里活下去。",
      "On the road", "Wandering together, Arya learns from the Hound how to survive in a broken land."),
    P(S4E10, "tie", "丢下他", "猎狗败给布蕾妮，重伤求死，艾莉亚却拿走他的钱袋，扬长而去。",
      "Left to die", "Broken by Brienne, the Hound begs for death; Arya takes his silver and walks away."),
    P(S8E5, "aid", "劝她回头", "君临陷落时，猎狗劝艾莉亚放下复仇，活下去。",
      "Go back", "As King’s Landing falls, the Hound tells Arya to give up revenge and live.")),
  E("arya", "gendry",
    P(S1E10, "aid", "结伴", "艾莉亚扮成男孩混在新兵中，与詹德利结伴北上。", "Companions", "Disguised as a boy among the recruits, Arya travels north with Gendry."),
    P(S2E8, "aid", "逃出赫伦堡", "两人和热派一起逃出了赫伦堡。", "Escape", "With Hot Pie, they escape Harrenhal together."),
    P(S3E6, "tie", "被卖", "无旗兄弟会把詹德利卖给红袍女，艾莉亚愤怒地看着他被带走。", "Sold", "Arya watches furiously as the Brotherhood sells Gendry to the red woman."),
    P(S8E2, "love", "相好", "长夜之战前夜，艾莉亚与詹德利同床。", "Lovers", "On the eve of the Long Night, Arya takes Gendry to bed."),
    P(S8E4, "love", "求婚被拒", "詹德利成为风息堡公爵，向艾莉亚求婚，她拒绝了：那不是她。",
      "No", "Made Lord of Storm’s End, Gendry asks Arya to marry him; she says no — that is not who she is.")),
  E("arya", "jaqen",
    P(S2E3, "aid", "救命之恩", "囚车着火时，艾莉亚把斧头递给锁在车里的贾昆。",
      "A life saved", "When the cart is burning, Arya passes an axe to the chained Jaqen."),
    P(S2E5, "aid", "三条人命", "贾昆欠她三条人命，答应替她杀死她说出名字的任何三个人。",
      "Three deaths", "Jaqen owes her three lives, and offers to kill any three people she names."),
    P(S2E10, "aid", "铁币", "临别时贾昆给了艾莉亚一枚铁币，换上另一张脸离去。",
      "The iron coin", "At parting Jaqen gives Arya an iron coin and leaves with another face."),
    P(S5E2, "mas", "师徒", "艾莉亚来到黑白之院，在贾昆门下学做“无名之人”。",
      "Master and pupil", "Arya comes to the House of Black and White to learn from Jaqen to be no one."),
    P(S6E8, "tie", "分道扬镳", "艾莉亚反杀流浪儿，告诉贾昆自己是艾莉亚·史塔克，离开了他。",
      "Parting ways", "Arya kills the Waif, tells Jaqen she is Arya Stark, and leaves him.")),
  E("tywin", "arya",
    P(S2E4, "tie", "侍酒", "泰温留艾莉亚做侍酒，常和她闲谈，却没认出她是谁。",
      "Cupbearer", "Tywin keeps Arya as his cupbearer and enjoys talking to her, never knowing who she is.")),
  E("arya", "brienne",
    P(S4E10, "tie", "错过", "布蕾妮找到艾莉亚，与猎狗决斗，艾莉亚趁乱走了。",
      "Missed", "Brienne finds Arya and fights the Hound for her, but Arya slips away."),
    P(S7E4, "aid", "切磋", "两人在临冬城的校场上切磋剑术，布蕾妮占不到上风。",
      "Sparring", "They spar in the yard at Winterfell, and Brienne cannot get the better of her.")),
  E("arya", "walder",
    P(S6E10, "foe", "复仇", "艾莉亚扮成侍女，割开了瓦德·佛雷的喉咙。", "Revenge", "Disguised as a serving girl, Arya cuts Walder Frey’s throat.")),
  E("arya", "littlefinger",
    P(S7E5, "tie", "跟踪", "艾莉亚跟踪小指头，找到了珊莎当年的信。", "Shadowing", "Arya follows Littlefinger and finds Sansa’s old letter."),
    P(S7E7, "foe", "处决", "临冬城大厅里，艾莉亚用匕首割开了小指头的喉咙。", "Execution", "In the great hall at Winterfell, Arya cuts Littlefinger’s throat.")),
  E("arya", "nightking",
    P(S8E3, "foe", "一击", "艾莉亚从暗处扑向夜王，一刀刺穿了他。", "One blow", "Arya leaps on the Night King from the dark and stabs him through.")),
  E("arya", "beric",
    P(S3E5, "tie", "复活", "艾莉亚亲眼看见贝里死而复生，问他能不能让父亲复活。",
      "Raised", "Arya sees Beric brought back from death and asks whether her father could be raised too."),
    P(S8E3, "aid", "舍身相护", "长夜之战中，贝里用身体挡住尸鬼，掩护艾莉亚逃走。", "His last life", "In the Long Night Beric holds back the dead so Arya can escape.")),
  E("arya", "melisandre",
    P(S3E6, "tie", "预言", "梅丽珊卓带走詹德利时，看着艾莉亚说她将闭上许多眼睛。",
      "A prophecy", "Taking Gendry away, Melisandre tells Arya she will shut many eyes forever."),
    P(S8E3, "tie", "蓝眼睛", "梅丽珊卓提醒艾莉亚：还有一双蓝眼睛等着她去闭上。",
      "Blue eyes", "Melisandre reminds Arya that there are blue eyes still for her to shut.")),
  E("bran", "jaime",
    P(S1E1, "foe", "推下高塔", "布兰撞见詹姆和瑟曦私通，詹姆把他推下了塔。",
      "The fall", "Bran sees Jaime with Cersei, and Jaime pushes him from the tower."),
    P(S8E1, "tie", "重逢", "詹姆来到临冬城，抬头看见坐在轮椅上的布兰。", "Face to face", "Arriving at Winterfell, Jaime looks up and sees Bran in his chair."),
    P(S8E2, "tie", "不追究", "布兰没有揭发詹姆，说那时的詹姆已不是现在的他。", "Forgiven", "Bran does not denounce Jaime, saying he is no longer the man who did it.")),
  E("bran", "hodor",
    P(S1E4, "mas", "代步", "布兰残废后，阿多背着他走遍各地。", "His legs", "After Bran is crippled, Hodor carries him wherever he goes."),
    P(S3E9, "mas", "易形", "布兰第一次进入阿多的意识，让他安静下来。", "Warging", "For the first time Bran slips into Hodor’s mind, to quiet him."),
    P(S6E5, "mas", "顶住门", "布兰的意识闯入少年威利斯，造就了“阿多”；阿多为保护布兰顶住洞门而死。",
      "Hold the door", "Bran’s mind reaches into the boy Wylis and makes him Hodor; Hodor dies holding the door for Bran.")),
  E("bran", "osha",
    P(S1E6, "foe", "袭击", "欧莎在狼林里袭击布兰，被罗柏擒住。", "Attacked", "Osha attacks Bran in the wolfswood and is captured by Robb."),
    P(S2E6, "aid", "护送", "席恩夺城后，欧莎带布兰和瑞肯逃出临冬城。", "Escape", "When Theon takes Winterfell, Osha gets Bran and Rickon out.")),
  E("bran", "luwin",
    P(S1E1, "aid", "师生", "鲁温学士是布兰的老师，辅佐他主持临冬城。", "Teacher and pupil", "Maester Luwin is Bran’s teacher and helps him govern Winterfell."),
    P(S2E10, "aid", "诀别", "临冬城被焚，垂死的鲁温嘱咐布兰北上长城。", "Farewell", "As Winterfell burns, the dying Luwin tells Bran to go north to the Wall.")),
  E("bran", "meera",
    P(S3E2, "aid", "同行", "梅拉一路保护布兰北上寻找三眼乌鸦。", "Companions", "Meera guards Bran on the long road north."),
    P(S7E4, "aid", "告别", "梅拉把布兰送回家，布兰只是淡淡道谢，她伤心离去。", "Farewell", "Meera brings Bran home; he thanks her coolly, and she leaves heartbroken.")),
  E("bran", "jojen",
    P(S3E2, "aid", "引路", "玖健告诉布兰他是易形者，领他去寻找三眼乌鸦。", "The guide", "Jojen tells Bran he is a warg and leads him to look for the Three-eyed Raven."),
    P(S4E10, "aid", "牺牲", "玖健死在鱼梁木前，他早已预见了自己的死。", "Sacrifice", "Jojen dies in sight of the weirwood — a death he had foreseen.")),
  E("threeeyed", "bran",
    P(S4E10, "mas", "师徒", "三眼乌鸦收布兰为徒，教他在幻象中看遍古今。", "Master and pupil", "The Raven takes Bran as his pupil, teaching him to see past and present."),
    P(S6E5, "mas", "传承", "洞穴被攻破之际，三眼乌鸦把一切传给布兰，死于夜王之手。",
      "The passing", "As the cave falls, the Raven passes everything to Bran and dies at the Night King’s hand.")),
  E("bran", "nightking",
    P(S6E5, "foe", "印记", "布兰在幻象中被夜王抓住手腕，留下了能被追踪的印记。", "The mark", "In a vision the Night King seizes Bran’s arm, leaving a mark he can follow."),
    P(S8E3, "foe", "神木林", "长夜之战中，夜王走进神木林来杀布兰。", "The godswood", "In the Long Night the Night King walks into the godswood to kill Bran.")),
  E("bran", "benjen",
    P(S1E1, "kin", "叔侄", "班扬是布兰的叔叔。", "Uncle and nephew", "Benjen is Bran’s uncle."),
    P(S6E6, "kin", "相救", "班扬突然出现，从尸鬼手中救下布兰和梅拉。", "Rescue", "Benjen appears out of nowhere to save Bran and Meera from the dead.")),
  E("bran", "sam",
    P(S3E10, "aid", "长城下的相遇", "布兰一行在长城下遇到山姆，山姆带他们穿过长城。", "At the Wall", "Bran’s party meets Sam at the Wall, and Sam shows them the way through."),
    P(S7E7, "aid", "揭开身世", "山姆和布兰拼出了真相：琼恩是雷加和莱安娜的合法儿子。", "The truth", "Sam and Bran piece it together: Jon is the legitimate son of Rhaegar and Lyanna.")),
  E("bran", "tyrion",
    P(S1E4, "aid", "马鞍", "提利昂为残废的布兰画了一副特制马鞍的图样。", "The saddle", "Tyrion designs a special saddle so the crippled Bran can ride."),
    P(S8E6, "mas", "国王与首相", "布兰为王，任命提利昂为国王之手。", "King and Hand", "King Bran names Tyrion his Hand.")),
  E("jon", "benjen",
    P(S1E1, "kin", "叔侄", "琼恩崇拜做游骑兵的叔叔，跟他北上长城。", "Uncle and nephew", "Jon idolises his ranger uncle and follows him to the Wall."),
    P(S7E6, "kin", "舍命相救", "冰湖边，班扬把马让给琼恩，自己留下挡住尸鬼。", "His last ride", "By the frozen lake Benjen gives Jon his horse and stays to hold back the dead.")),
  E("lyanna", "jon",
    P(S6E10, "kin", "母子", "幻象揭示：琼恩的生母是莱安娜。", "Mother and son", "The vision reveals that Jon’s mother was Lyanna.")),
  E("jon", "sam",
    P(S1E4, "aid", "挚友", "琼恩护住被教头欺负的山姆，两人成了一辈子的朋友。", "Friends", "Jon protects Sam from the master-at-arms, and they become friends for life."),
    P(S5E10, "aid", "送别", "琼恩送山姆和吉莉南下旧镇。", "Farewell", "Jon sends Sam and Gilly south to Oldtown."),
    P(S8E1, "aid", "告知身世", "山姆告诉琼恩：你不是私生子，你是伊耿·坦格利安。", "The truth", "Sam tells Jon he is no bastard — he is Aegon Targaryen.")),
  E("jon", "ygritte",
    P(S2E6, "tie", "俘虏", "琼恩俘虏了耶哥蕊特，却下不了手杀她。", "The captive", "Jon captures Ygritte but cannot kill her."),
    P(S3E5, "love", "相爱", "两人在山洞里成了恋人。", "Lovers", "They become lovers in a cave."),
    P(S3E10, "tie", "三箭", "琼恩逃回黑城堡，耶哥蕊特含泪射了他三箭。", "Three arrows", "As Jon escapes to Castle Black, Ygritte shoots him three times, weeping."),
    P(S4E9, "love", "死在怀里", "黑城堡之战中，耶哥蕊特中箭，死在琼恩怀里。", "In his arms", "In the battle for Castle Black, Ygritte is shot and dies in Jon’s arms.")),
  E("jeor", "jon",
    P(S1E7, "mas", "侍从", "老熊让琼恩做自己的侍从，有意栽培他。", "Steward", "The Old Bear makes Jon his steward, meaning to groom him."),
    P(S1E9, "mas", "长爪", "琼恩从尸鬼手中救下老熊，老熊把家传宝剑“长爪”送给他。",
      "Longclaw", "Jon saves the Old Bear from a wight and is given his family sword, Longclaw.")),
  E("aemon", "jon",
    P(S1E9, "aid", "忠告", "伊蒙学士劝琼恩守誓，说出自己也曾在家族与誓言间抉择。",
      "Counsel", "Maester Aemon counsels Jon to keep his vows, having once faced the same choice between family and oath."),
    P(S5E2, "aid", "关键一票", "总司令选举中，伊蒙投下决定性的一票，琼恩当选。", "The deciding vote", "Aemon casts the deciding vote that makes Jon Lord Commander.")),
  E("jon", "alliser",
    P(S1E3, "foe", "教头", "索恩处处刁难出身贵族的琼恩。", "The master-at-arms", "Thorne goes out of his way to humiliate the highborn Jon."),
    P(S5E10, "foe", "刺杀", "索恩带头以“为了守夜人”之名刺死了琼恩。", "Murder", "Thorne leads the men who stab Jon ‘for the Watch’."),
    P(S6E3, "foe", "绞刑", "琼恩复活后，亲手吊死了索恩。", "The noose", "Risen, Jon hangs Thorne himself.")),
  E("jon", "olly",
    P(S5E3, "mas", "侍从", "琼恩当上总司令后，让奥利做自己的侍从。", "Steward", "As Lord Commander, Jon makes Olly his steward."),
    P(S5E10, "foe", "最后一刀", "奥利诱琼恩出来，给了他最后一刀。", "The last blow", "Olly lures Jon out and strikes the last blow."),
    P(S6E3, "foe", "绞刑", "琼恩复活后，以叛变之罪吊死了奥利。", "The noose", "Risen, Jon hangs Olly for mutiny.")),
  E("jon", "edd",
    P(S2E1, "aid", "弟兄", "艾迪是琼恩在守夜人中最可靠的弟兄。", "Brothers", "Edd is Jon’s most dependable brother in the Watch."),
    P(S6E3, "aid", "交托", "琼恩离开守夜人，把黑城堡交给了艾迪。", "Handing over", "Leaving the Watch, Jon hands Castle Black to Edd.")),
  E("jon", "mance",
    P(S3E1, "tie", "投奔", "琼恩假意投奔曼斯，曼斯半信半疑地收下他。", "Joining", "Jon pretends to join Mance, who takes him in, half-trusting."),
    P(S4E10, "tie", "谈判", "琼恩孤身出城与曼斯谈判，恰逢史坦尼斯大军赶到。", "Parley", "Jon goes alone to parley with Mance just as Stannis arrives."),
    P(S5E1, "tie", "仁慈的一箭", "曼斯被绑上火刑柱，琼恩一箭射死了他，免他受苦。", "A merciful arrow", "As Mance burns, Jon shoots him dead to spare him the fire.")),
  E("jon", "tormund",
    P(S3E1, "tie", "野人", "托蒙德从一开始就不信任琼恩。", "The wildling", "Tormund mistrusts Jon from the start."),
    P(S5E8, "aid", "艰难屯", "两人一起去艰难屯劝野人南下，并肩对抗亡者。", "Hardhome", "They go to Hardhome together to bring the Free Folk south and fight the dead side by side."),
    P(S8E6, "aid", "同归长城以北", "琼恩被流放，与托蒙德一起向长城以北走去。", "North together", "Exiled, Jon rides north beyond the Wall with Tormund.")),
  E("jon", "lyannamo",
    P(S6E7, "aid", "熊岛", "琼恩和珊莎到熊岛求援，莱安娜派出六十二名士兵。", "Bear Island", "Jon and Sansa ask Bear Island for men, and Lyanna gives them sixty-two."),
    P(S6E10, "mas", "拥立", "莱安娜带头拥立琼恩为北境之王。", "Acclaimed", "Lyanna leads the lords in naming Jon King in the North.")),
  E("jon", "ramsay",
    P(S6E9, "foe", "私生子之战", "琼恩与拉姆斯在临冬城外决战，最后把他打得不成人形。",
      "Battle of the Bastards", "Jon and Ramsay meet before Winterfell; in the end Jon beats him bloody.")),
  E("jon", "nightking",
    P(S5E8, "foe", "艰难屯", "琼恩亲眼看见夜王把死去的野人唤起。", "Hardhome", "Jon watches the Night King raise the dead of Hardhome."),
    P(S7E6, "foe", "冰湖", "夜王掷矛射杀了韦赛利昂，琼恩险些死在冰湖下。", "The frozen lake", "The Night King kills Viserion, and Jon nearly drowns under the ice."),
    P(S8E3, "foe", "长夜", "琼恩在临冬城与亡者大军决战。", "The Long Night", "Jon fights the army of the dead at Winterfell.")),
  E("jon", "theon",
    P(S1E1, "tie", "同在临冬城", "席恩和琼恩一同在临冬城长大，彼此并不亲近。", "Raised together", "Theon and Jon grew up together at Winterfell without ever being close."),
    P(S7E7, "tie", "和解", "琼恩对席恩说：你既是葛雷乔伊，也是史塔克。席恩决定去救雅拉。",
      "Reconciled", "Jon tells Theon he is both a Greyjoy and a Stark, and Theon resolves to rescue Yara.")),
  E("jon", "littlefinger",
    P(S7E2, "foe", "掐喉警告", "小指头说起对凯特琳的爱和对珊莎的心思，琼恩掐住他的脖子警告他。",
      "A warning", "When Littlefinger talks of loving Catelyn and Sansa, Jon takes him by the throat.")),
  # =============================================================== the Night's Watch and beyond
  E("jeor", "aemon",
    P(S1E3, "aid", "同袍", "老熊倚重伊蒙学士的智慧。", "Old comrades", "The Old Bear relies on Maester Aemon’s wisdom.")),
  E("jeor", "alliser",
    P(S1E3, "mas", "总司令与教头", "索恩是老熊手下的教头。", "Commander and officer", "Thorne is the Old Bear’s master-at-arms.")),
  E("jeor", "craster",
    P(S2E1, "tie", "互利", "老熊对卡斯特的勾当睁一只眼闭一只眼，换取守夜人在塞外的落脚处。",
      "A bargain", "The Old Bear turns a blind eye to Craster’s ways in return for shelter beyond the Wall.")),
  E("aemon", "sam",
    P(S1E7, "mas", "侍从", "山姆被派去给伊蒙学士做侍从。", "Steward", "Sam is assigned to Maester Aemon as his steward."),
    P(S5E7, "aid", "送终", "山姆陪伊蒙学士走完最后一程。", "The end", "Sam is with Maester Aemon when he dies.")),
  E("sam", "alliser",
    P(S1E4, "foe", "受辱", "索恩在校场上当众羞辱山姆。", "Humiliated", "Thorne humiliates Sam in the training yard.")),
  E("sam", "edd",
    P(S2E1, "aid", "弟兄", "两人一同随老熊出塞。", "Brothers", "They go north on the great ranging together."),
    P(S8E3, "aid", "舍身相救", "长夜之战中，艾迪为救山姆被尸鬼刺死。", "Saved", "In the Long Night, Edd dies saving Sam.")),
  E("sam", "gilly",
    P(S2E2, "aid", "求助", "吉莉想逃离卡斯特堡，山姆替她向琼恩求情，琼恩没有答应。", "A plea", "Gilly wants to escape Craster’s Keep; Sam pleads for her with Jon, who refuses."),
    P(S3E4, "aid", "带她逃走", "叛乱中，山姆带着吉莉和她刚出生的儿子逃走。", "Escape", "In the mutiny Sam escapes with Gilly and her newborn son."),
    P(S5E7, "love", "相爱", "山姆为保护吉莉挨了打，两人终于在一起。", "Lovers", "Sam is beaten defending Gilly, and they become lovers."),
    P(S7E5, "love", "旧日记", "吉莉在学城读到雷加废婚另娶的记载，山姆没听进去。", "The diary", "At the Citadel Gilly reads aloud of Rhaegar’s annulment, and Sam is not listening.")),
  E("craster", "gilly",
    P(S2E2, "kin", "父亲兼丈夫", "卡斯特娶了自己的女儿吉莉。", "Father and husband", "Craster has taken his daughter Gilly as a wife.")),
  E("craster", "nightking",
    P(S4E4, "tie", "献婴", "卡斯特一直把生下的男婴献给异鬼。", "The offerings", "Craster gave his sons to the White Walkers.")),
  E("mance", "tormund",
    P(S3E1, "mas", "首领与部下", "托蒙德是曼斯最得力的头领。", "King and war chief", "Tormund is Mance’s right hand.")),
  E("mance", "ygritte",
    P(S3E1, "mas", "首领与部下", "耶哥蕊特追随曼斯南下。", "King and follower", "Ygritte follows Mance south.")),
  E("tormund", "ygritte",
    P(S3E1, "aid", "同伴", "托蒙德与耶哥蕊特是并肩作战的同伴。", "Comrades", "Tormund and Ygritte fight side by side."),
    P(S4E10, "aid", "火葬", "托蒙德请琼恩按自由民的规矩火化耶哥蕊特。", "The pyre", "Tormund asks Jon to burn Ygritte as the Free Folk do.")),
  E("olly", "ygritte",
    P(S4E9, "foe", "一箭", "奥利一箭射死了杀害他父亲的耶哥蕊特。", "One arrow", "Olly shoots Ygritte, who killed his father.")),
  E("alliser", "olly",
    P(S5E10, "aid", "同谋", "索恩与奥利合谋刺杀琼恩。", "Conspirators", "Thorne and Olly plot Jon’s murder together.")),
  E("nightking", "threeeyed",
    P(S6E5, "foe", "攻破洞穴", "夜王攻进洞穴，亲手杀死了三眼乌鸦。", "The cave", "The Night King breaks into the cave and kills the Three-eyed Raven himself.")),
  E("hodor", "meera",
    P(S6E5, "aid", "顶住门", "梅拉拖着布兰逃出，喊阿多顶住门。", "Hold the door", "Meera drags Bran away, shouting for Hodor to hold the door.")),
  E("osha", "rickon",
    P(S2E6, "aid", "护送", "欧莎带着瑞肯逃出临冬城，此后一直照顾他。", "Protector", "Osha gets Rickon out of Winterfell and looks after him from then on."),
    P(S6E3, "aid", "同被出卖", "安柏家把欧莎和瑞肯一起交给了拉姆斯。", "Betrayed together", "The Umbers hand Osha and Rickon over to Ramsay together.")),
  E("osha", "luwin",
    P(S2E10, "aid", "最后的仁慈", "鲁温学士重伤，欧莎应他所求结束了他的痛苦。", "Mercy", "At Luwin’s request, Osha ends his suffering.")),
  E("osha", "theon",
    P(S2E6, "tie", "引诱", "欧莎引诱席恩，趁他熟睡带孩子们逃走。", "Seduction", "Osha seduces Theon and slips away with the boys while he sleeps.")),
  E("osha", "ramsay",
    P(S6E4, "foe", "刺杀不成", "欧莎想用刀刺拉姆斯，被他识破刺死。", "A failed blow", "Osha reaches for a knife to kill Ramsay, and he kills her first.")),
  E("rickon", "ramsay",
    P(S6E3, "foe", "人质", "瑞肯被送到拉姆斯手里当人质。", "Hostage", "Rickon is delivered to Ramsay as a hostage."),
    P(S6E9, "foe", "一箭", "拉姆斯射死了奔向哥哥的瑞肯。", "The arrow", "Ramsay shoots Rickon as he runs to his brother.")),
  E("roose", "ramsay",
    P(S3E10, "kin", "父子（私生子）", "拉姆斯是卢斯的私生子。", "Father and bastard", "Ramsay is Roose’s bastard."),
    P(S4E8, "kin", "正名", "拉姆斯拿下卡林湾，卢斯承认他为波顿家的合法儿子。", "Legitimised", "When Ramsay takes Moat Cailin, Roose makes him a true Bolton."),
    P(S6E2, "foe", "弑父", "妻子生下儿子后，卢斯被拉姆斯刺死。", "Patricide", "When Roose’s wife bears a son, Ramsay stabs his father.")),
  E("robb", "roose",
    P(S2E4, "mas", "封臣", "卢斯·波顿是罗柏麾下的北境诸侯。", "Bannerman", "Roose Bolton is one of Robb’s Northern lords."),
    P(S3E9, "foe", "背叛", "红色婚礼上，卢斯亲手刺死了罗柏。", "Betrayal", "At the Red Wedding Roose stabs Robb himself.")),
  E("theon", "ramsay",
    P(S3E2, "tie", "相救", "一个年轻人自称受雅拉之托来救席恩。", "A rescue", "A young man claims Yara has sent him to rescue Theon."),
    P(S3E7, "foe", "阉割", "拉姆斯百般折磨席恩，把他阉割。", "Mutilation", "Ramsay tortures Theon and castrates him."),
    P(S4E2, "mas", "臭佬", "席恩被驯成唯命是从的“臭佬”，替拉姆斯刮脸。", "Reek", "Theon has been broken into ‘Reek’, who shaves Ramsay’s face."),
    P(S5E10, "foe", "出逃", "席恩带珊莎逃出临冬城。", "Escape", "Theon escapes Winterfell with Sansa.")),
  E("meera", "jojen",
    P(S3E2, "kin", "姐弟", "梅拉与玖健是黎德家的姐弟。", "Sister and brother", "Meera and Jojen are sister and brother of House Reed."),
    P(S4E10, "kin", "诀别", "玖健被尸鬼刺中，梅拉只得结束他的生命。", "Mercy", "When the dead stab Jojen, Meera has to end his life.")),
]
