# -*- coding: utf-8 -*-
"""Game of Thrones (TV): King's Landing and the south — the Lannisters and the court, the Baratheons, the Riverlands
and the Vale, the Reach and Dorne, and the Iron Islands. Field meanings are listed in nodes_got_north.py."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import N  # noqa: E402
from episodes_got import *  # noqa: E402,F401,F403

PRE = 0

NODES_SOUTH = [
  # =============================================================== the Lannisters
  N(id="tywin", zh="泰温", en="Tywin", full=("泰温·兰尼斯特", "Tywin Lannister"), house="lannister", grp="lannister",
    debut=S1E7, dies=S4E10,
    camps=[(S1E7, "lannister")],
    subs=[(S1E7, "凯岩城公爵", "Lord of Casterly Rock"), (S1E8, "国王之手", "Hand of the King")],
    sub=("凯岩城公爵，国王之手", "Lord of Casterly Rock, Hand of the King"),
    bios=[
      (S1E7, "兰尼斯特家族的家长，凯岩城公爵，冷酷精明，一切只为家族的延续与荣耀(S1E7)。",
       "Head of House Lannister and Lord of Casterly Rock, cold and shrewd, living only for the family’s legacy (S1E7)."),
      (S1E10, "乔佛里任命他为国王之手(S1E8)。詹姆被俘后，他留在前线，派提利昂去君临代行首相之职，管住乔佛里(S1E10)。",
       "Joffrey names him Hand of the King (S1E8). With Jaime captured he stays with his army and sends Tyrion to King’s Landing to act as Hand in his place and rein in Joffrey (S1E10)."),
      (S2E10, "他坐镇赫伦堡，没认出给他斟酒的女孩就是艾莉亚，两人常常闲谈(S2E5)。黑水河之战中，他与提利尔家的大军及时赶到，救下君临(S2E9)，随即亲自坐镇御前(S2E10)。",
       "Holding Harrenhal, he chats with his cupbearer without realising she is Arya Stark (S2E5). At the Blackwater he arrives with the Tyrell host in time to save the city (S2E9), and takes up his office as Hand in person (S2E10)."),
      (S3E10, "他拒绝把凯岩城交给提利昂(S3E1)，逼提利昂娶珊莎(S3E8)，又与瓦德·佛雷、卢斯·波顿合谋策划了红色婚礼(S3E10)。",
       "He refuses Tyrion Casterly Rock (S3E1), forces him to marry Sansa (S3E8), and plots the Red Wedding with Walder Frey and Roose Bolton (S3E10)."),
      (S4E10, "乔佛里死后，他主持了对提利昂弑君之罪的审判(S4E6)。提利昂越狱后找到坐在厕所里的他，用十字弓射死了他(S4E10)。",
       "After Joffrey’s death he presides over Tyrion’s trial for regicide (S4E6). Escaping, Tyrion finds him on the privy and kills him with a crossbow (S4E10)."),
    ]),
  N(id="kevan", zh="凯冯", en="Kevan", full=("凯冯·兰尼斯特", "Kevan Lannister"), house="lannister", grp="lannister",
    debut=S1E8, dies=S6E10,
    camps=[(S1E8, "lannister")],
    sub=("泰温的弟弟，蓝赛尔的父亲", "Tywin’s brother, Lancel’s father"),
    bios=[
      (S1E8, "泰温的弟弟，一生忠心辅佐兄长，是兰尼斯特家可靠的老将(S1E8)。",
       "Tywin’s brother, who has served him loyally all his life — the Lannisters’ steady old soldier (S1E8)."),
      (S6E10, "泰温死后，他与瑟曦不和；瑟曦被大麻雀囚禁期间，他回到君临出任国王之手。他死在贝勒大圣堂的野火爆炸中(S6E10)。",
       "After Tywin’s death he clashes with Cersei; while she is held by the High Sparrow he returns to King’s Landing as Hand of the King. He dies in the wildfire blast at the Great Sept of Baelor (S6E10)."),
    ]),
  N(id="cersei", zh="瑟曦", en="Cersei", full=("瑟曦·兰尼斯特", "Cersei Lannister"), house="lannister", grp="lannister",
    debut=S1E1, dies=S8E5,
    camps=[(S1E1, "lannister")],
    subs=[(S1E1, "劳勃的王后", "Robert’s queen"), (S1E8, "太后", "The Queen Mother"), (S6E10, "七国女王", "Queen of the Seven Kingdoms")],
    sub=("劳勃的王后，后自己登上铁王座", "Robert’s queen, later queen in her own right"),
    bios=[
      (S1E1, "泰温的女儿，劳勃国王的王后，与孪生弟弟詹姆私通。布兰撞见两人，被詹姆推下高塔(S1E1)。",
       "Tywin’s daughter and King Robert’s queen, secretly the lover of her twin Jaime. When Bran sees them, Jaime pushes him from the tower (S1E1)."),
      (S1E8, "艾德查出她的三个孩子都是詹姆所生，劝她出逃，她却回答：玩权力的游戏，不胜则死(S1E7)。劳勃死后，她撕毁遗诏，扶乔佛里继位，逮捕了艾德(S1E7)。",
       "When Ned discovers that all three of her children are Jaime’s and urges her to flee, she tells him that in the game of thrones you win or you die (S1E7). On Robert’s death she tears up his will, puts Joffrey on the throne and has Ned arrested (S1E7)."),
      (S2E9, "她做了太后，却管不住乔佛里，又处处与提利昂较劲(S2E1)。黑水河之战那夜，她带着托曼坐在王座上，准备城破时毒死他(S2E9)。",
       "Queen Mother now, she cannot control Joffrey and fights Tyrion at every turn (S2E1). On the night of the Blackwater she sits on the throne with Tommen, ready to poison him if the city falls (S2E9)."),
      (S4E10, "乔佛里在婚宴上中毒而死，她认定凶手是提利昂(S4E2)。父亲逼她嫁给洛拉斯，她当面说出了自己和詹姆的关系(S4E10)。",
       "When Joffrey dies of poison at his wedding she is certain Tyrion did it (S4E2). Told by her father to marry Loras, she tells him the truth about her and Jaime (S4E10)."),
      (S5E10, "为了对付玛格丽，她扶植大麻雀，重建信仰武装(S5E4)，结果自己也被抓进牢房(S5E7)，被剃光头发、赤身走过君临街头赎罪(S5E10)。",
       "To bring down Margaery she raises up the High Sparrow and rearms the Faith (S5E4), only to be imprisoned herself (S5E7) and made to walk naked and shorn through the city in atonement (S5E10)."),
      (S6E10, "女儿弥赛菈的尸体被送回君临(S6E1)。在受审那天，她用野火炸毁了贝勒大圣堂，大麻雀、玛格丽和提利尔家的男人尽数烧死；托曼随即跳楼自尽，她登上了铁王座(S6E10)。",
       "Her daughter Myrcella comes home dead (S6E1). On the day of her trial she blows up the Great Sept with wildfire, killing the High Sparrow, Margaery and the Tyrell men; Tommen throws himself from a window, and she takes the Iron Throne (S6E10)."),
      (S7E7, "她拒绝了攸伦的求婚(S7E1)，直到他献上艾拉莉亚母女才与他结盟，并用毒吻杀死艾拉莉亚的女儿(S7E3)，在龙穴会谈中假意答应出兵北上，暗中却雇来黄金团(S7E7)。",
       "She turns down Euron’s proposal (S7E1) until he brings her Ellaria and her daughter, then allies with him and kills the daughter with a poisoned kiss (S7E3), and at the Dragonpit pretends to agree to send her army north while she hires the Golden Company instead (S7E7)."),
      (S8E5, "丹妮莉丝焚烧君临时，她与詹姆在红堡地下相拥，一起被坍塌的乱石掩埋(S8E5)。",
       "As Daenerys burns King’s Landing she dies in Jaime’s arms in the cellars of the Red Keep, buried as it collapses (S8E5)."),
    ]),
  N(id="jaime", zh="詹姆", en="Jaime", full=("詹姆·兰尼斯特", "Jaime Lannister"), house="lannister", grp="lannister",
    debut=S1E1, dies=S8E5,
    camps=[(S1E1, "lannister"), (S1E9, "stark", "被罗柏俘虏", "Captured by Robb"), (S3E10, "lannister", "回到君临", "Back in King’s Landing"),
           (S7E7, "stark", "离开瑟曦，北上抗敌", "Leaves Cersei to fight the dead"), (S8E4, "lannister", "回君临找瑟曦", "Goes back to Cersei")],
    subs=[(S1E1, "御林铁卫，瑟曦的孪生弟弟", "Kingsguard, Cersei’s twin"), (S1E3, "御林铁卫，“弑君者”", "Kingsguard, ‘the Kingslayer’"), (S1E9, "罗柏的俘虏", "Robb’s prisoner"),
          (S3E3, "失去右手的骑士", "The knight who lost his sword hand"), (S3E10, "御林铁卫队长", "Lord Commander of the Kingsguard")],
    sub=("御林铁卫，“弑君者”，瑟曦的孪生弟弟", "Kingsguard, ‘the Kingslayer’, Cersei’s twin"),
    bios=[
      (S1E1, "瑟曦的孪生弟弟，御林铁卫。布兰撞见他和瑟曦私通，他把布兰推下高塔(S1E1)。",
       "Cersei’s twin, a knight of the Kingsguard. When Bran sees him with Cersei he pushes the boy from the tower (S1E1)."),
      (S1E3, "当年他背弃誓言，从背后刺死了疯王伊里斯，从此被人叫做“弑君者”(S1E3)。",
       "Long ago he broke his oath and stabbed the Mad King in the back, and has been called the Kingslayer ever since (S1E3)."),
      (S1E9, "提利昂被凯特琳抓走，他在君临街头截杀艾德的卫兵(S1E5)，回西境领兵，在呓语森林被罗柏俘虏(S1E9)。",
       "When Catelyn seizes Tyrion he attacks Ned and his guards in the street (S1E5), goes west to lead an army and is captured by Robb in the Whispering Wood (S1E9)."),
      (S3E3, "凯特琳放了他，让布蕾妮押送他回君临(S2E8)。他与布蕾妮由互相讥讽到渐生敬意，两人却被波顿的部下抓住，他握剑的右手被砍了下来(S3E3)。",
       "Catelyn releases him into Brienne’s custody to be taken to King’s Landing (S2E8). Their mutual contempt turns slowly to respect, but Bolton men capture them and cut off his sword hand (S3E3)."),
      (S3E10, "在浴池里，他向布蕾妮讲出当年杀疯王的真相：疯王要用野火烧掉整座君临(S3E5)。他跳进熊坑救出布蕾妮(S3E7)，回到君临与瑟曦重逢(S3E10)。",
       "In a bath he tells Brienne the truth of the Mad King’s death: Aerys meant to burn the whole city with wildfire (S3E5). He leaps into a bear pit to save her (S3E7) and comes home to Cersei (S3E10)."),
      (S4E10, "他在乔佛里的灵前强占了瑟曦(S4E3)，把瓦雷利亚钢剑“守誓剑”送给布蕾妮，托她寻找珊莎(S4E4)，又偷偷放走了被判死刑的提利昂(S4E10)。",
       "He forces himself on Cersei beside Joffrey’s body (S4E3), gives Brienne the Valyrian sword Oathkeeper to go and find Sansa (S4E4), and frees Tyrion from his death cell (S4E10)."),
      (S6E10, "他去多恩接弥赛菈，女儿却死在他怀里(S5E10)。他率军收复奔流城(S6E8)，回到君临时，瑟曦已经炸毁大圣堂、登上王位(S6E10)。",
       "He goes to Dorne to bring Myrcella home and she dies in his arms (S5E10). He retakes Riverrun (S6E8) and returns to find Cersei has destroyed the Great Sept and crowned herself (S6E10)."),
      (S7E7, "他攻下高庭，逼奥莲娜服毒(S7E3)，在辎重之战中冲向丹妮莉丝，险些葬身龙焰(S7E4)。瑟曦背弃出兵北上的承诺，他独自离开君临北上(S7E7)。",
       "He takes Highgarden and gives Olenna poison (S7E3), and charges Daenerys in the loot train battle, nearly dying in dragonfire (S7E4). When Cersei breaks her promise to send an army north, he leaves her and rides north alone (S7E7)."),
      (S8E5, "他在临冬城受审，布蕾妮为他作保(S8E2)；他封布蕾妮为骑士(S8E2)，与她并肩熬过长夜(S8E3)。最终他还是回到君临找瑟曦，杀死了攸伦，与瑟曦一同死在红堡的废墟中(S8E5)。",
       "Tried at Winterfell, he is vouched for by Brienne (S8E2); he knights her (S8E2) and fights beside her through the Long Night (S8E3). In the end he goes back to Cersei, kills Euron, and dies with her under the ruins of the Red Keep (S8E5)."),
    ]),
  N(id="tyrion", zh="提利昂", en="Tyrion", full=("提利昂·兰尼斯特", "Tyrion Lannister"), house="lannister", grp="lannister",
    debut=S1E1, dies=None,
    camps=[(S1E1, "lannister"), (S1E4, "arryn", "被凯特琳押往鹰巢城", "Taken to the Eyrie by Catelyn"),
           (S1E6, "lannister", "决斗审判后获释", "Freed after a trial by combat"),
           (S4E10, "none", "杀父后逃离君临", "Flees after killing his father"),
           (S5E8, "targaryen", "投奔丹妮莉丝", "Joins Daenerys"),
           (S8E6, "stark", "成为布兰国王的首相", "Hand to King Bran")],
    subs=[(S1E1, "泰温的幼子，侏儒", "Tywin’s youngest son, a dwarf"), (S1E10, "代理国王之手", "Acting Hand of the King"),
          (S3E3, "财政大臣", "Master of Coin"), (S4E2, "弑君嫌犯", "Accused of regicide"),
          (S5E8, "丹妮莉丝的谋士", "Daenerys’s adviser"), (S6E10, "女王之手", "Hand of the Queen"), (S8E6, "国王之手", "Hand of the King")],
    sub=("泰温的侏儒儿子，以智谋立身", "Tywin’s dwarf son, who lives by his wits"),
    bios=[
      (S1E1, "泰温的幼子，生来是侏儒，母亲因生他而死，父亲和姐姐都恨他。他嗜酒好色，读书最多，口才过人(S1E1)。",
       "Tywin’s youngest son, born a dwarf; his mother died bearing him, and his father and sister hate him for it. He drinks, whores, reads more than anyone and talks his way out of everything (S1E1)."),
      (S1E9, "凯特琳认定他主使了行刺布兰，把他抓到鹰巢城(S1E4—S1E5)。佣兵波隆替他决斗获胜(S1E6)；他凭口才让山地部落随他出征(S1E8)，在军营里认识了雪伊(S1E9)。",
       "Catelyn, convinced he sent the assassin after Bran, takes him to the Eyrie (S1E4–S1E5). The sellsword Bronn wins a trial by combat for him (S1E6); he talks the hill tribes into fighting for him (S1E8), and meets Shae in camp (S1E9)."),
      (S2E10, "他到君临代理首相，处处牵制乔佛里和瑟曦(S2E1)。黑水河之战中，他用野火烧毁史坦尼斯的舰队，亲自带兵出城，被人一剑劈伤了脸(S2E9)。醒来时父亲已接任首相，他的功劳无人提起(S2E10)。",
       "In King’s Landing as acting Hand he checks Joffrey and Cersei at every turn (S2E1). At the Blackwater he burns Stannis’s fleet with wildfire, leads a sortie himself and has his face slashed (S2E9). He wakes to find his father Hand and his part forgotten (S2E10)."),
      (S3E8, "父亲拒绝把凯岩城给他(S3E1)，让他做了财政大臣(S3E3)，又逼他娶了珊莎(S3E8)。",
       "His father refuses him Casterly Rock (S3E1), makes him Master of Coin (S3E3) and forces him to marry Sansa (S3E8)."),
      (S4E10, "乔佛里在婚宴上毒发身亡，他被当作凶手逮捕(S4E2)。审判中雪伊当庭作伪证，他要求决斗审判(S4E6)，奥柏伦替他出战而死(S4E8)。詹姆放他逃走，他在父亲床上撞见雪伊，掐死了她，又用十字弓射死了父亲(S4E10)。",
       "Joffrey dies of poison at his wedding and Tyrion is arrested for it (S4E2). At his trial Shae perjures herself and he demands a trial by combat (S4E6); Oberyn fights for him and dies (S4E8). Freed by Jaime, he finds Shae in his father’s bed, strangles her, and kills his father with a crossbow (S4E10)."),
      (S5E10, "瓦里斯带他渡海去了潘托斯(S5E1)，他被乔拉劫持(S5E3)，几经周折见到了丹妮莉丝(S5E7)。丹妮莉丝被龙带走后，他留下替她治理弥林(S5E10)。",
       "Varys smuggles him across the sea to Pentos (S5E1); he is kidnapped by Jorah (S5E3) and at last brought before Daenerys (S5E7). When her dragon carries her away he stays to govern Meereen for her (S5E10)."),
      (S6E10, "他放开被锁在地窖里的两条龙(S6E2)，与奴隶主谈判停战(S6E4)，奴隶主却背信攻城(S6E9)。丹妮莉丝任命他为女王之手(S6E10)。",
       "He unchains the two dragons in the pit (S6E2) and negotiates a truce with the masters (S6E4), who break it and attack (S6E9). Daenerys names him Hand of the Queen (S6E10)."),
      (S7E7, "他为丹妮莉丝出谋划策却屡屡失算，在龙穴会谈后独自去见瑟曦，说服她休战(S7E7)。",
       "His plans for Daenerys keep failing; after the Dragonpit summit he goes alone to Cersei and talks her into a truce (S7E7)."),
      (S8E6, "他劝丹妮莉丝饶恕百姓，却眼看她焚烧君临(S8E5)。他扔掉首相胸针，被投入大牢；在推举新王的大会上，他提议由布兰为王，自己再次成为国王之手(S8E6)。",
       "He begs Daenerys to spare the people and watches her burn the city (S8E5). He throws away his Hand’s pin and is imprisoned; at the great council he proposes Bran as king and becomes Hand once more (S8E6)."),
    ]),
  N(id="lancel", zh="蓝赛尔", en="Lancel", full=("蓝赛尔·兰尼斯特", "Lancel Lannister"), house="lannister", grp="lannister",
    debut=S1E3, dies=S6E10,
    camps=[(S1E3, "lannister"), (S5E1, "faith", "皈依麻雀", "Joins the Sparrows")],
    subs=[(S1E3, "劳勃的侍从，瑟曦的表弟", "Robert’s squire, Cersei’s cousin"), (S5E1, "麻雀信徒", "A Sparrow"),
          (S5E4, "信仰武装的修士", "A brother of the Faith Militant")],
    sub=("劳勃的侍从，后入信仰武装", "Robert’s squire, later of the Faith Militant"),
    bios=[
      (S1E3, "兰尼斯特家的少年，劳勃国王的侍从(S1E3)。", "A young Lannister, King Robert’s squire (S1E3)."),
      (S1E7, "狩猎时，他一杯接一杯地给劳勃灌加了料的烈酒，劳勃被野猪重伤(S1E7)。",
       "On the hunt he keeps Robert’s cup full of strengthened wine, and the boar gores the king (S1E7)."),
      (S2E4, "提利昂识破他与瑟曦私通、替她害死劳勃，逼他做自己的眼线(S2E4)。",
       "Tyrion discovers that he is Cersei’s lover and helped her kill Robert, and makes him his informer (S2E4)."),
      (S5E10, "黑水河之战中他负了重伤(S2E9)。他皈依了大麻雀(S5E1)，向信仰坦白了与瑟曦的私情和劳勃之死，瑟曦因此被捕(S5E7)。",
       "Badly wounded at the Blackwater (S2E9), he takes up with the High Sparrow (S5E1) and confesses to the Faith his affair with Cersei and his part in Robert’s death, and Cersei is arrested (S5E7)."),
      (S6E10, "他在地下追踪瑟曦的眼线，发现了堆积如山的野火，被刺伤后爬向即将燃尽的蜡烛，与大圣堂一同化为灰烬(S6E10)。",
       "Following one of Cersei’s little spies underground, he finds caches of wildfire and is stabbed; he crawls towards the guttering candle and dies as the Sept goes up (S6E10)."),
    ]),
  N(id="joffrey", zh="乔佛里", en="Joffrey", full=("乔佛里·拜拉席恩", "Joffrey Baratheon"), house="stagion", grp="lannister",
    debut=S1E1, dies=S4E2,
    camps=[(S1E1, "baratheon"), (S1E7, "lannister", "即位为王", "Becomes king")],
    subs=[(S1E1, "王太子", "Crown prince"), (S1E7, "国王", "King")],
    sub=("劳勃名义上的长子，残暴的少年国王", "Robert’s supposed heir, the cruel boy king"),
    bios=[
      (S1E2, "劳勃国王的长子和继承人，骄横怯懦。他在三叉戟河边欺负屠夫的儿子，被艾莉亚的冰原狼咬伤(S1E2)。",
       "King Robert’s eldest son and heir, arrogant and cowardly. At the Trident he bullies a butcher’s boy and is bitten by Arya’s direwolf (S1E2)."),
      (S1E10, "他其实是瑟曦与詹姆的儿子(S1E7)。劳勃死后他继位为王，不顾母亲和群臣的劝阻当众斩了艾德(S1E9)，还逼珊莎去看艾德的首级(S1E10)。",
       "He is in fact the son of Cersei and Jaime (S1E7). Crowned on Robert’s death, he has Ned beheaded against his mother’s and his council’s advice (S1E9) and makes Sansa look at the head (S1E10)."),
      (S2E10, "他下令杀死劳勃所有的私生子(S2E1)，以羞辱珊莎为乐(S2E4)；黑水河之战还没结束，他就躲回了城里(S2E9)。战后他改娶玛格丽(S2E10)。",
       "He orders all Robert’s bastards killed (S2E1) and torments Sansa for sport (S2E4); at the Blackwater he flees the walls before the battle is done (S2E9). Afterwards he sets Sansa aside for Margaery (S2E10)."),
      (S4E2, "在与玛格丽的婚宴上，他百般羞辱提利昂，喝下一杯酒后中毒窒息而死(S4E2)。",
       "At his wedding feast he humiliates Tyrion, drinks from his cup, and chokes to death on poison (S4E2)."),
      (S7E3, "多年后，奥莲娜向詹姆坦白：毒死他的是她(S7E3)。", "Years later Olenna tells Jaime that it was she who poisoned him (S7E3)."),
    ]),
  N(id="myrcella", zh="弥赛菈", en="Myrcella", full=("弥赛菈·拜拉席恩", "Myrcella Baratheon"), house="stagion", grp="lannister",
    debut=S1E1, dies=S5E10,
    camps=[(S1E1, "baratheon"), (S1E7, "lannister"), (S2E6, "martell", "远嫁多恩", "Sent to Dorne")],
    subs=[(S1E1, "瑟曦的女儿", "Cersei’s daughter"), (S2E6, "多恩王子的未婚妻", "Betrothed to a prince of Dorne")],
    sub=("瑟曦的女儿", "Cersei’s daughter"),
    bios=[
      (S1E1, "瑟曦的女儿，性情温和(S1E1)。", "Cersei’s daughter, a gentle girl (S1E1)."),
      (S2E6, "提利昂把她许配给多恩亲王的儿子崔斯丹，送去多恩，以换取马泰尔家的支持(S2E6)。",
       "Tyrion betroths her to Prince Trystane of Dorne and sends her there to win the Martells’ support (S2E6)."),
      (S5E10, "詹姆动身去多恩接她回家(S5E2)。临别时艾拉莉亚吻了她，唇上的毒药发作；她在船上认了詹姆为父亲，随即死在他怀里(S5E10)。",
       "Jaime sets out for Dorne to bring her home (S5E2). Ellaria kisses her goodbye with poison on her lips; on the ship she tells Jaime she knows he is her father, and dies in his arms (S5E10)."),
    ]),
  N(id="tommen", zh="托曼", en="Tommen", full=("托曼·拜拉席恩", "Tommen Baratheon"), house="stagion", grp="lannister",
    debut=S1E1, dies=S6E10,
    camps=[(S1E1, "baratheon"), (S1E7, "lannister"), (S6E6, "faith", "与大麻雀结盟", "Allies the crown with the Faith")],
    subs=[(S1E1, "瑟曦的幼子", "Cersei’s younger son"), (S4E5, "国王", "King")],
    sub=("瑟曦的幼子，乔佛里死后为王", "Cersei’s younger son, king after Joffrey"),
    bios=[
      (S1E1, "瑟曦的幼子，温和胆小，与哥哥完全不同(S1E1)。", "Cersei’s younger son, gentle and shy, nothing like his brother (S1E1)."),
      (S4E5, "乔佛里死后，他登上王位(S4E5)。", "After Joffrey’s death he is crowned king (S4E5)."),
      (S5E10, "他娶了玛格丽(S5E3)；大麻雀先后抓走王后和母亲，他软弱无力，只能眼看母亲受辱(S5E10)。",
       "He marries Margaery (S5E3); when the High Sparrow takes first his queen and then his mother he is powerless, and watches his mother’s humiliation (S5E10)."),
      (S6E10, "他被大麻雀说服，让王室与信仰结盟(S6E6)，又废除了决斗审判(S6E8)。大圣堂被炸、玛格丽惨死后，他从红堡的窗口一跃而下(S6E10)。",
       "Won over by the High Sparrow, he joins the Crown to the Faith (S6E6) and abolishes trial by combat (S6E8). After the Sept explodes and Margaery dies in it, he steps from a window of the Red Keep (S6E10)."),
    ]),
  N(id="sandor", zh="猎狗", en="The Hound", full=("桑铎·克里冈", "Sandor “the Hound” Clegane"), house="clegane", grp="lannister",
    debut=S1E1, dies=S8E5,
    camps=[(S1E1, "lannister"), (S2E9, "none", "黑水河之战中叛逃", "Deserts at the Blackwater"),
           (S6E8, "river", "加入无旗兄弟会", "Joins the Brotherhood"), (S7E5, "stark", "随琼恩北上", "Goes north with Jon"),
           (S8E4, "none", "南下找魔山复仇", "Rides south for his brother")],
    subs=[(S1E1, "乔佛里的贴身护卫", "Joffrey’s sworn shield"), (S2E9, "逃兵", "A deserter"),
          (S6E7, "隐姓埋名的劳工", "A labourer in hiding"), (S6E8, "无旗兄弟会的一员", "With the Brotherhood")],
    sub=("乔佛里的护卫，魔山的弟弟", "Joffrey’s bodyguard, the Mountain’s brother"),
    bios=[
      (S1E1, "乔佛里的贴身护卫，半边脸是可怕的烧伤(S1E1)。", "Joffrey’s sworn shield, half his face horribly burned (S1E1)."),
      (S1E2, "他奉命追杀屠夫的儿子(S1E2)。", "On orders, he hunts down the butcher’s boy (S1E2)."),
      (S1E4, "小指头向珊莎说出他伤疤的来历：小时候哥哥格雷果把他的脸按进火盆，从此他最怕火(S1E4)。",
       "Littlefinger tells Sansa how he got his scars: as a boy his brother Gregor pushed his face into a brazier, and he fears fire above all things (S1E4)."),
      (S1E5, "比武大会上，他挡住发狂的哥哥，救了洛拉斯(S1E5)。", "At the tourney he stops his raging brother and saves Loras (S1E5)."),
      (S2E9, "他在暴乱中救下珊莎(S2E6)。黑水河之战中，他面对野火退缩，弃王而去，临走前提出带珊莎一起离开(S2E9)。",
       "He saves Sansa in a riot (S2E6). At the Blackwater, faced with the wildfire, he abandons the king and offers to take Sansa with him (S2E9)."),
      (S4E10, "无旗兄弟会抓住他，他在决斗审判中杀死贝里(S3E5)。他劫走艾莉亚想换赎金(S3E7)，两人一路相伴(S4E1)；布蕾妮与他决斗，他重伤坠崖，艾莉亚却没有给他痛快(S4E10)。",
       "Taken by the Brotherhood, he kills Beric in a trial by combat (S3E5). He carries off Arya for ransom (S3E7) and they travel together (S4E1); fighting Brienne, he falls from a cliff badly hurt, and Arya leaves him without the mercy he asks for (S4E10)."),
      (S6E8, "一位修士救活了他，他在修士的村子里干活(S6E7)；村民被无旗兄弟会的叛徒杀害，他提斧复仇，随后加入兄弟会(S6E8)。",
       "A septon nurses him back to life and he works in his village (S6E7); when renegades of the Brotherhood murder them all, he takes an axe to them and then joins the Brotherhood (S6E8)."),
      (S7E7, "他在火中看到亡者大军(S7E1)，随琼恩到长城以北捉尸鬼(S7E6)，在龙穴把尸鬼放到瑟曦面前，又当面告诉魔山：他们之间的账迟早要算(S7E7)。",
       "He sees the army of the dead in the flames (S7E1), goes north with Jon to catch a wight (S7E6), sets it loose before Cersei at the Dragonpit, and tells the Mountain their reckoning is coming (S7E7)."),
      (S8E5, "长夜之战中他克服了对火的恐惧(S8E3)，随后南下复仇；他劝艾莉亚离开，在崩塌的红堡里抱着魔山一同坠入火海(S8E5)。",
       "He masters his fear of fire in the Long Night (S8E3) and rides south for revenge; he sends Arya away and, in the collapsing Red Keep, carries the Mountain with him down into the flames (S8E5)."),
    ]),
  N(id="gregor", zh="魔山", en="The Mountain", full=("格雷果·克里冈爵士", "Ser Gregor “the Mountain” Clegane"), house="clegane", grp="lannister",
    debut=S1E4, dies=S8E5,
    camps=[(S1E4, "lannister")],
    subs=[(S1E4, "泰温的封臣，“魔山”", "Tywin’s bannerman, ‘the Mountain’"), (S5E10, "复活的御林铁卫", "Revived as a knight of the Kingsguard")],
    sub=("“魔山”，猎狗的哥哥", "‘The Mountain’, the Hound’s brother"),
    bios=[
      (S1E4, "身形如山的骑士，泰温手下最凶残的打手。比武大会上，他一枪刺穿了谷地年轻骑士休的喉咙(S1E4)。",
       "A knight as big as a mountain, Tywin’s most brutal enforcer. At the tourney his lance goes through the throat of a young knight of the Vale, Ser Hugh (S1E4)."),
      (S1E5, "他输给洛拉斯，当场砍杀自己的马，又要杀洛拉斯，被弟弟猎狗拦下(S1E5)。",
       "Unhorsed by Loras, he beheads his own horse and goes for Loras until his brother the Hound stops him (S1E5)."),
      (S1E6, "他奉泰温之命在河间烧杀劫掠，代理首相艾德派贝里·唐德利恩去缉拿他(S1E6)。",
       "On Tywin’s orders he burns and pillages the Riverlands; Ned, as acting Hand, sends Beric Dondarrion to bring him to justice (S1E6)."),
      (S4E8, "他作为瑟曦的勇士与奥柏伦决斗，被刺得重伤倒地，却抓住奥柏伦，承认当年杀害了伊莉亚和她的孩子，随即挤碎了奥柏伦的头(S4E8)。",
       "Fighting Oberyn as Cersei’s champion, he is speared and brought down, but seizes Oberyn, confesses to killing Elia and her children, and crushes his skull (S4E8)."),
      (S5E10, "奥柏伦的毒矛让他奄奄一息，科本把他救活(S4E10)，变成一个不说话的巨人，在瑟曦赎罪游街后为她效命(S5E10)。",
       "Dying of Oberyn’s poisoned spear, he is kept alive by Qyburn (S4E10) and remade into a silent giant who serves Cersei from the end of her walk of atonement (S5E10)."),
      (S8E5, "君临陷落时，他把科本摔死在石头上，最后与猎狗同归于尽(S8E5)。",
       "As King’s Landing falls he kills Qyburn and goes down with the Hound (S8E5)."),
    ]),
  N(id="bronn", zh="波隆", en="Bronn", full=("波隆", "Bronn"), house="smallfolk", grp="lannister",
    debut=S1E4, dies=None,
    camps=[(S1E4, "none"), (S1E6, "lannister", "为提利昂决斗", "Fights for Tyrion")],
    subs=[(S1E4, "佣兵", "Sellsword"), (S2E2, "都城守备队长", "Commander of the City Watch"),
          (S3E1, "黑水的波隆爵士", "Ser Bronn of the Blackwater"), (S8E6, "高庭公爵、财政大臣", "Lord of Highgarden, Master of Coin")],
    sub=("佣兵，提利昂和詹姆的伙伴", "Sellsword, companion to Tyrion and Jaime"),
    bios=[
      (S1E4, "一个只认钱的佣兵，在路边旅店随凯特琳的人马押送提利昂(S1E4)。", "A sellsword who cares only for money; at a roadside inn he joins Catelyn’s party taking Tyrion away (S1E4)."),
      (S1E6, "他在鹰巢城替提利昂决斗，把莱莎的骑士踢出了月门(S1E6)，从此跟着提利昂。",
       "He fights for Tyrion at the Eyrie, kicking Lysa’s knight out through the Moon Door (S1E6), and stays at Tyrion’s side."),
      (S2E10, "提利昂当上代理首相，让他做了都城守备队长(S2E2)。黑水河之战中，他射出了点燃野火的那一箭(S2E9)。",
       "Tyrion, as acting Hand, gives him command of the City Watch (S2E2). At the Blackwater he looses the arrow that lights the wildfire (S2E9)."),
      (S4E7, "提利昂受审时，他不肯冒死去和魔山决斗，转而接受了瑟曦安排的婚约，要娶史铎克渥斯家的小姐(S4E7)。",
       "When Tyrion is on trial he will not risk his life against the Mountain, and accepts Cersei’s offer of a betrothal to Lollys Stokeworth instead (S4E7)."),
      (S7E4, "他陪詹姆去多恩救弥赛菈(S5E2)；辎重之战中，他把冲向龙焰的詹姆扑进了河里(S7E4)。",
       "He goes with Jaime to Dorne for Myrcella (S5E2), and in the loot train battle knocks Jaime into the river out of the dragon’s fire (S7E4)."),
      (S8E6, "瑟曦雇他去杀提利昂和詹姆，他却拿两人做交易，换来了高庭(S8E4)，最后成为高庭公爵和御前财政大臣(S8E6)。",
       "Hired by Cersei to kill Tyrion and Jaime, he bargains with them for Highgarden instead (S8E4), and ends as Lord of Highgarden and Master of Coin (S8E6)."),
    ]),
  N(id="pod", zh="波德", en="Pod", full=("波德瑞克·派恩", "Podrick Payne"), house="payne", grp="lannister",
    debut=S2E2, dies=None,
    camps=[(S2E2, "lannister"), (S4E4, "stark", "随布蕾妮寻找珊莎", "Goes with Brienne to find Sansa")],
    subs=[(S2E2, "提利昂的侍从", "Tyrion’s squire"), (S4E4, "布蕾妮的侍从", "Brienne’s squire"), (S8E6, "波德瑞克爵士，御林铁卫", "Ser Podrick of the Kingsguard")],
    sub=("提利昂的侍从，后随布蕾妮", "Tyrion’s squire, later Brienne’s"),
    bios=[
      (S2E9, "派恩家的少年，被派来做提利昂的侍从，笨手笨脚却忠心耿耿。黑水河之战中，有人要暗杀提利昂，他一枪刺穿刺客，救了主人(S2E9)。",
       "A boy of House Payne sent to squire for Tyrion, clumsy and utterly loyal. At the Blackwater, when a knight tries to kill Tyrion, Pod spears him and saves his master (S2E9)."),
      (S4E4, "提利昂入狱后，詹姆让他跟着布蕾妮去寻找珊莎(S4E4)。", "With Tyrion in prison, Jaime sends him with Brienne to find Sansa (S4E4)."),
      (S8E6, "他和布蕾妮救下珊莎(S6E1)，熬过了长夜之战，最后被封为骑士，成为布兰的御林铁卫(S8E6)。",
       "He helps Brienne rescue Sansa (S6E1), survives the Long Night, and ends a knight of King Bran’s Kingsguard (S8E6)."),
    ]),
  N(id="shae", zh="雪伊", en="Shae", full=("雪伊", "Shae"), house="essos", grp="lannister",
    debut=S1E9, dies=S4E10,
    camps=[(S1E9, "lannister")],
    subs=[(S1E9, "提利昂的情人", "Tyrion’s lover"), (S2E3, "珊莎的侍女", "Sansa’s handmaid")],
    sub=("提利昂的情人", "Tyrion’s lover"),
    bios=[
      (S1E9, "在军营里卖身的女子，来历不明。波隆把她带给提利昂，两人一夜长谈后相好(S1E9)。",
       "A camp follower of uncertain origins. Bronn brings her to Tyrion, and after a night of talk they become lovers (S1E9)."),
      (S2E10, "提利昂把她偷偷带进君临(S2E1)，又让她做珊莎的侍女，以掩人耳目(S2E3)。",
       "Tyrion smuggles her into King’s Landing (S2E1) and hides her as Sansa’s handmaid (S2E3)."),
      (S4E10, "提利昂为了保护她，故意说狠话赶她走(S4E2)。审判中她当庭作证，把两人私下的话都说成提利昂谋逆的证据(S4E6)；提利昂越狱时在泰温的床上撞见她，掐死了她(S4E10)。",
       "To protect her, Tyrion drives her away with cruel words (S4E2). At his trial she testifies against him, turning their private talk into evidence of treason (S4E6); escaping, he finds her in Tywin’s bed and strangles her (S4E10)."),
    ]),
  N(id="qyburn", zh="科本", en="Qyburn", full=("科本", "Qyburn"), house="maester", grp="lannister",
    debut=S3E1, dies=S8E5,
    camps=[(S3E1, "none"), (S3E10, "lannister", "随詹姆来到君临", "Comes to King’s Landing with Jaime")],
    subs=[(S3E1, "赫伦堡的幸存者", "A survivor at Harrenhal"), (S3E5, "被学城除名的学士", "A maester stripped of his chain"), (S5E2, "瑟曦的情报总管", "Cersei’s Master of Whisperers"),
          (S6E10, "女王之手", "Hand of the Queen")],
    sub=("被学城除名的学士，瑟曦的心腹", "A disgraced maester, Cersei’s creature"),
    bios=[
      (S3E1, "罗柏在惨遭屠戮的赫伦堡里发现的唯一幸存者，懂得医术(S3E1)。", "The one survivor Robb finds in massacred Harrenhal, a man with a healer’s skill (S3E1)."),
      (S3E5, "他在赫伦堡为詹姆治疗断腕；他曾是学士，因拿活人做实验被学城除去了颈链(S3E5)。", "He tends Jaime’s stump at Harrenhal; once a maester, he lost his chain for experimenting on the living (S3E5)."),
      (S5E10, "他救活了奄奄一息的魔山(S4E10)，被瑟曦任命为情报总管(S5E2)，在她赎罪游街之后把复活的魔山带到她面前(S5E10)。",
       "He keeps the dying Mountain alive (S4E10), is made Cersei’s Master of Whisperers (S5E2), and presents the revived giant to her after her walk of atonement (S5E10)."),
      (S6E10, "他收服了瓦里斯留下的孩子眼线，在大圣堂爆炸那天让孩子们刺死了派席尔，被瑟曦任命为女王之手(S6E10)。",
       "He takes over Varys’s child informers, has them stab Pycelle on the day the Sept explodes, and is made Hand of the Queen (S6E10)."),
      (S8E5, "红堡崩塌时，他想喝止魔山，被魔山一把摔在石头上死去(S8E5)。",
       "As the Red Keep collapses he tries to give the Mountain orders and is dashed against the stones (S8E5)."),
    ]),
  # =============================================================== the court
  N(id="pycelle", zh="派席尔", en="Pycelle", full=("派席尔大学士", "Grand Maester Pycelle"), house="maester", grp="court",
    debut=S1E3, dies=S6E10,
    camps=[(S1E3, "baratheon"), (S1E7, "lannister")],
    sub=("大学士，兰尼斯特家的内应", "Grand Maester, secretly a Lannister man"),
    bios=[
      (S1E3, "年迈的大学士，在御前会议上装作老态龙钟(S1E3)。", "The aged Grand Maester, who plays the doddering old man at the small council (S1E3)."),
      (S2E3, "提利昂设局试探御前会议，他把消息透露给瑟曦，暴露了自己一直替兰尼斯特家效力，被提利昂下狱(S2E3)。",
       "When Tyrion lays a trap for the council, Pycelle carries the tale to Cersei, showing he has always served the Lannisters, and Tyrion has him thrown in a cell (S2E3)."),
      (S6E10, "他在泰温之后依附瑟曦，又倒向大麻雀，在审判那天被科本的孩子们用匕首刺死(S6E10)。",
       "He serves Cersei after Tywin, drifts towards the High Sparrow, and on the day of the trial is stabbed to death by Qyburn’s children (S6E10)."),
    ]),
  N(id="varys", zh="瓦里斯", en="Varys", full=("瓦里斯", "Varys"), house="essos", grp="court",
    debut=S1E3, dies=S8E5,
    camps=[(S1E3, "baratheon"), (S1E7, "lannister"), (S4E10, "none", "带提利昂出逃", "Flees with Tyrion"),
           (S6E1, "targaryen", "在弥林辅佐丹妮莉丝", "Serves Daenerys in Meereen")],
    subs=[(S1E3, "御前情报总管，“八爪蜘蛛”", "Master of Whisperers, ‘the Spider’"), (S6E1, "丹妮莉丝的谋臣", "Daenerys’s counsellor")],
    sub=("情报总管“八爪蜘蛛”", "Master of Whisperers, ‘the Spider’"),
    bios=[
      (S1E3, "御前情报总管，宦官，眼线遍布七国，人称“八爪蜘蛛”。他私下提醒艾德，劳勃身边危机四伏(S1E3)。",
       "The eunuch Master of Whisperers, whose ‘little birds’ are everywhere — ‘the Spider’. He warns Ned privately that Robert is surrounded by danger (S1E3)."),
      (S1E5, "艾莉亚在红堡地下偷听到他和伊利里欧密谋，却听不明白(S1E5)。", "Arya overhears him plotting with Illyrio in the dungeons of the Red Keep, without understanding (S1E5)."),
      (S3E4, "他向提利昂讲出自己少年时被术士阉割的往事，说他效忠的是王国，而不是某个国王(S3E4)。",
       "He tells Tyrion how a sorcerer castrated him as a boy, and says his loyalty is to the realm, not to any king (S3E4)."),
      (S4E10, "他帮詹姆把提利昂偷运出君临，自己也随之出海(S4E10)。", "He helps Jaime smuggle Tyrion out of the city, and sails with him (S4E10)."),
      (S6E10, "他说服提利昂随他去投奔丹妮莉丝(S5E1)，在弥林追查鹰身女妖之子的后台(S6E2)，又南下多恩，为丹妮莉丝争取奥莲娜和艾拉莉亚(S6E10)。",
       "He persuades Tyrion to come with him to Daenerys (S5E1), hunts the backers of the Sons of the Harpy in Meereen (S6E2), and wins Olenna and Ellaria for her in Dorne (S6E10)."),
      (S8E5, "他认为琼恩比丹妮莉丝更适合为王，暗中写信散布琼恩的身世，被提利昂告发，丹妮莉丝用龙焰处死了他(S8E5)。",
       "Believing Jon a better ruler than Daenerys, he writes letters to spread the truth of Jon’s birth; Tyrion betrays him, and Daenerys has him burned by her dragon (S8E5)."),
    ]),
  N(id="littlefinger", zh="小指头", en="Littlefinger", full=("培提尔·贝里席", "Petyr “Littlefinger” Baelish"), house="baelish", grp="court",
    debut=S1E3, dies=S7E7,
    camps=[(S1E3, "baratheon"), (S1E7, "lannister", "出卖艾德", "Betrays Ned"), (S4E5, "arryn", "娶莱莎，主宰谷地", "Marries Lysa and takes the Vale")],
    subs=[(S1E3, "财政大臣", "Master of Coin"), (S2E10, "赫伦堡公爵", "Lord of Harrenhal"), (S4E5, "莱莎的丈夫", "Lysa’s husband"),
          (S4E8, "谷地守护", "Lord Protector of the Vale")],
    sub=("财政大臣，绰号“小指头”", "Master of Coin, called Littlefinger"),
    bios=[
      (S1E3, "出身卑微的财政大臣，开着君临最好的妓院。他少年时爱慕凯特琳，至今念念不忘，告诉凯特琳行刺布兰的匕首是提利昂的(S1E3)。",
       "The low-born Master of Coin, who keeps the best brothels in the city. In love with Catelyn since boyhood, he tells her the assassin’s dagger was Tyrion’s (S1E3)."),
      (S1E7, "他答应帮艾德调动都城守备队，临阵却用匕首抵住艾德的喉咙(S1E7)。",
       "He promises Ned the City Watch, then puts a knife to his throat at the decisive moment (S1E7)."),
      (S3E6, "他替王室与提利尔家牵线，被封为赫伦堡公爵(S2E10)，又对瓦里斯说：混乱不是深渊，而是阶梯(S3E6)。",
       "He brokers the alliance between the crown and the Tyrells and is made Lord of Harrenhal (S2E10), and tells Varys that chaos is not a pit but a ladder (S3E6)."),
      (S4E8, "乔佛里死后，他趁乱带走珊莎(S4E3)，向她透露自己与奥莲娜合谋下毒(S4E4)。他娶了莱莎(S4E5)，又把她推下月门(S4E7)，靠珊莎作证脱身(S4E8)。",
       "In the chaos of Joffrey’s death he spirits Sansa away (S4E3) and lets her know he plotted the poisoning with Olenna (S4E4). He marries Lysa (S4E5), pushes her through the Moon Door (S4E7), and escapes justice through Sansa’s testimony (S4E8)."),
      (S6E9, "他把珊莎嫁给拉姆斯(S5E6)。珊莎当面质问他的出卖，他仍带谷地骑兵赶到私生子之战的战场(S6E9)。",
       "He marries Sansa to Ramsay (S5E6). Though she confronts him with his betrayal, he brings the knights of the Vale to the Battle of the Bastards (S6E9)."),
      (S7E7, "他挑拨珊莎和艾莉亚反目(S7E6)，最终在临冬城大厅被当众审判，以谋害琼恩·艾林、出卖艾德的罪名被艾莉亚割喉(S7E7)。",
       "He tries to set Sansa and Arya against each other (S7E6), and is tried in the hall at Winterfell for the murder of Jon Arryn and the betrayal of Ned; Arya cuts his throat (S7E7)."),
    ]),
  N(id="highsparrow", zh="大麻雀", en="High Sparrow", full=("大麻雀", "The High Sparrow"), house="faith", grp="court",
    debut=S5E3, dies=S6E10,
    camps=[(S5E3, "faith")],
    subs=[(S5E3, "麻雀运动的领袖", "Leader of the Sparrows"), (S5E4, "大主教", "High Septon")],
    sub=("麻雀运动的领袖，后为大主教", "Leader of the Sparrows, later High Septon"),
    bios=[
      (S5E3, "赤足苦修的修士，带领“麻雀”们在君临救济穷人、惩戒罪人(S5E3)。",
       "A barefoot ascetic who leads the ‘Sparrows’ in King’s Landing, feeding the poor and punishing sinners (S5E3)."),
      (S5E10, "瑟曦扶他当上大主教，恢复了信仰武装(S5E4)。他先后逮捕洛拉斯、玛格丽和瑟曦本人(S5E4—S5E7)，罚瑟曦赤身游街赎罪(S5E10)。",
       "Cersei makes him High Septon and rearms the Faith Militant (S5E4). He arrests Loras, Margaery and then Cersei herself (S5E4–S5E7), and sends Cersei on a naked walk of atonement (S5E10)."),
      (S6E10, "他说服托曼让王室与信仰结盟(S6E6)，在审判瑟曦的那天，与大圣堂里所有的人一同葬身野火(S6E10)。",
       "He brings Tommen to unite the Crown and the Faith (S6E6), and on the day of Cersei’s trial dies in the wildfire with everyone in the Sept (S6E10)."),
    ]),
  N(id="syrio", zh="西里欧", en="Syrio", full=("西里欧·佛瑞尔", "Syrio Forel"), house="essos", grp="court",
    debut=S1E3, dies=None,
    camps=[(S1E3, "stark")],
    sub=("布拉佛斯的水舞者，艾莉亚的剑术老师", "Braavosi water dancer, Arya’s sword master"),
    bios=[
      (S1E3, "布拉佛斯海王的前任首席剑士，艾德请他来教艾莉亚“水舞”剑术(S1E3)。",
       "Once First Sword to the Sealord of Braavos, hired by Ned to teach Arya ‘water dancing’ (S1E3)."),
      (S1E8, "兰尼斯特的人来抓艾莉亚，他用一把木剑挡住全副武装的骑士，让艾莉亚逃走，此后下落不明(S1E8)。",
       "When Lannister men come for Arya he holds off an armoured knight with a wooden sword so she can run; his fate is never shown (S1E8)."),
    ]),
  # =============================================================== the Baratheons
  N(id="robert", zh="劳勃", en="Robert", full=("劳勃·拜拉席恩", "Robert Baratheon"), house="baratheon", grp="baratheon",
    debut=S1E1, dies=S1E7,
    camps=[(S1E1, "baratheon")],
    sub=("七国之王", "King of the Seven Kingdoms"),
    bios=[
      (S1E1, "推翻坦格利安王朝的叛军首领，登上铁王座已有十七年，如今发福嗜酒。他一生最爱的是艾德的妹妹莱安娜，北上请老友艾德出任首相(S1E1)。",
       "The rebel who overthrew the Targaryens, seventeen years on the Iron Throne and now fat and drinking. He has never loved anyone but Ned’s sister Lyanna, and comes north to make his old friend his Hand (S1E1)."),
      (S1E7, "他与瑟曦婚姻冷淡，下令刺杀远在厄索斯的丹妮莉丝(S1E5)。狩猎时，侍从蓝赛尔一杯接一杯地给他灌烈酒，他被野猪挑破肚子，临终任命艾德为摄政(S1E7)。",
       "Long estranged from Cersei, he orders the murder of Daenerys across the sea (S1E5). On a hunt, kept drunk by his squire Lancel, he is gored by a boar, and names Ned regent as he dies (S1E7)."),
    ]),
  N(id="stannis", zh="史坦尼斯", en="Stannis", full=("史坦尼斯·拜拉席恩", "Stannis Baratheon"), house="baratheon", grp="baratheon",
    debut=S2E1, dies=S5E10,
    camps=[(S2E1, "baratheon")],
    sub=("劳勃的大弟，自立为王", "Robert’s next brother, a claimant to the throne"),
    bios=[
      (S2E1, "劳勃的大弟，严厉刻板，认定自己是铁王座的合法继承人。他公开宣布乔佛里是乱伦所生，并在红袍女梅丽珊卓的影响下改信光之王(S2E1)。",
       "Robert’s next brother, stern and unbending, certain he is the rightful heir. He proclaims Joffrey a child of incest and, under the red priestess Melisandre, takes up the Lord of Light (S2E1)."),
      (S2E9, "梅丽珊卓为他生下影子，刺死了弟弟蓝礼(S2E5)。他率舰队进攻君临，在黑水河被野火和兰尼斯特援军击败(S2E9)。",
       "Melisandre gives birth to a shadow that kills his brother Renly (S2E5). He attacks King’s Landing and is broken at the Blackwater by wildfire and the Lannister relief (S2E9)."),
      (S4E10, "他向布拉佛斯的铁金库借到钱(S4E6)，北上长城，击溃曼斯的野人大军(S4E10)。",
       "He wins a loan from the Iron Bank of Braavos (S4E6), sails north and crushes Mance’s wildling army at the Wall (S4E10)."),
      (S5E10, "他南下讨伐波顿家，为了让风雪停下，把女儿希琳献祭给光之王(S5E9)。妻子自缢、大军溃散，他在临冬城外被布蕾妮以谋杀蓝礼之罪处决(S5E10)。",
       "Marching on the Boltons, he burns his daughter Shireen to the Lord of Light to end the storms (S5E9). His wife hangs herself, his army breaks, and Brienne executes him outside Winterfell for Renly’s murder (S5E10)."),
    ]),
  N(id="renly", zh="蓝礼", en="Renly", full=("蓝礼·拜拉席恩", "Renly Baratheon"), house="baratheon", grp="baratheon",
    debut=S1E3, dies=S2E5,
    camps=[(S1E3, "baratheon")],
    subs=[(S1E3, "劳勃的幼弟，法律大臣", "Robert’s youngest brother, Master of Laws"), (S2E3, "自立为王", "Claimant to the throne")],
    sub=("劳勃的幼弟，自立为王", "Robert’s youngest brother, a claimant to the throne"),
    bios=[
      (S1E5, "劳勃最小的弟弟，风流讨喜，在御前会议任法律大臣，私下与洛拉斯·提利尔相爱(S1E5)。",
       "Robert’s youngest brother, charming and easy, Master of Laws on the small council and secretly Loras Tyrell’s lover (S1E5)."),
      (S2E5, "劳勃死后他逃出君临，凭提利尔家的支持称王，娶了玛格丽(S2E3)；他拒绝让位给哥哥史坦尼斯，被梅丽珊卓生下的影子刺死在营帐里(S2E5)。",
       "After Robert’s death he flees the city, claims the crown with the Tyrells behind him and marries Margaery (S2E3); refusing to yield to his brother Stannis, he is stabbed in his tent by Melisandre’s shadow (S2E5)."),
    ]),
  N(id="selyse", zh="赛丽丝", en="Selyse", full=("赛丽丝·拜拉席恩", "Selyse Baratheon"), house="baratheon", grp="baratheon",
    born=("佛罗伦", "Florent"), debut=S3E5, dies=S5E10,
    camps=[(S3E5, "baratheon")],
    sub=("史坦尼斯之妻，狂热的光之王信徒", "Stannis’s wife, a zealot of the Lord of Light"),
    bios=[
      (S3E5, "史坦尼斯的妻子，狂热信奉光之王，冷待自己患过灰鳞病的女儿希琳(S3E5)。",
       "Stannis’s wife, a zealot of the Lord of Light who is cold to her greyscale-scarred daughter Shireen (S3E5)."),
      (S5E10, "她同意把希琳献祭给光之王，行刑时却崩溃哭喊(S5E9)；第二天她在林中自缢(S5E10)。",
       "She consents to Shireen’s burning, then breaks down screaming as it happens (S5E9); the next day she hangs herself (S5E10)."),
    ]),
  N(id="shireen", zh="希琳", en="Shireen", full=("希琳·拜拉席恩", "Shireen Baratheon"), house="baratheon", grp="baratheon",
    debut=S3E5, dies=S5E9,
    camps=[(S3E5, "baratheon")],
    sub=("史坦尼斯的独女，幼时患过灰鳞病", "Stannis’s only child, scarred by greyscale"),
    bios=[
      (S3E5, "史坦尼斯的独生女，幼时患过灰鳞病，半边脸留下疤痕。她教不识字的戴佛斯读书(S3E5)。",
       "Stannis’s only child, half her face scarred by greyscale she survived as a baby. She teaches Davos to read (S3E5)."),
      (S5E9, "她在黑城堡教吉莉读书(S5E2)。随父亲南征时，被父母献祭给光之王，在火刑柱上哭喊着死去(S5E9)。",
       "At Castle Black she teaches Gilly her letters (S5E2). On the march south her parents burn her as a sacrifice to the Lord of Light, crying out for them (S5E9)."),
    ]),
  N(id="davos", zh="戴佛斯", en="Davos", full=("戴佛斯·席渥斯爵士", "Ser Davos Seaworth"), house="seaworth", grp="baratheon",
    debut=S2E1, dies=None,
    camps=[(S2E1, "baratheon"), (S6E1, "stark", "史坦尼斯死后守护琼恩", "Stays with Jon after Stannis’s death")],
    subs=[(S2E1, "史坦尼斯的“洋葱骑士”", "Stannis’s ‘Onion Knight’"), (S3E8, "史坦尼斯的首相", "Stannis’s Hand"),
          (S6E10, "北境之王的谋臣", "Counsellor to the King in the North"), (S8E6, "御前造船大臣", "Master of Ships")],
    sub=("史坦尼斯的“洋葱骑士”，后辅佐琼恩", "Stannis’s ‘Onion Knight’, later Jon’s counsellor"),
    bios=[
      (S2E1, "出身跳蚤窝的走私者，当年风息堡被围时给史坦尼斯偷运洋葱，被封为骑士，也被砍掉了几根手指的指节(S2E1)。他不信光之王，却始终忠于史坦尼斯。",
       "A smuggler from Flea Bottom who ran onions through the siege of Storm’s End; Stannis knighted him and shortened the fingers of one hand for his past (S2E1). He has no faith in the Lord of Light, but none could be more loyal to Stannis."),
      (S3E10, "黑水河之战中他的儿子战死(S2E9)，他漂到礁岩上被人救回；回到龙石岛后，他想刺杀梅丽珊卓，被关进地牢(S3E1)。他在牢中学会读书，获释后重得史坦尼斯信任(S3E8)，又放走了要被献祭的詹德利(S3E10)。",
       "His son dies at the Blackwater (S2E9); he is rescued from a rock in the bay, and back on Dragonstone tries to kill Melisandre and is thrown in a cell (S3E1). There he learns to read; released, he is back in Stannis’s confidence (S3E8), and frees Gendry from being sacrificed (S3E10)."),
      (S5E9, "他替史坦尼斯说动铁金库(S4E6)，在长城与琼恩结下交情；史坦尼斯献祭希琳时，他被支开去了黑城堡(S5E9)。",
       "He talks the Iron Bank round for Stannis (S4E6) and befriends Jon at the Wall; when Stannis burns Shireen, Davos has been sent back to Castle Black (S5E9)."),
      (S6E10, "他守着琼恩的遗体，请梅丽珊卓试着复活他(S6E2)。他在焚烧希琳的灰烬里找到自己为她刻的木雕小鹿(S6E9)，当众揭穿梅丽珊卓，琼恩将她逐出北境(S6E10)。",
       "He guards Jon’s body and asks Melisandre to try to bring him back (S6E2). Finding in the ashes where Shireen burned the wooden stag he carved for her (S6E9), he denounces Melisandre, and Jon banishes her (S6E10)."),
      (S8E6, "他陪琼恩南下见丹妮莉丝(S7E3)，找回了詹德利(S7E5)，最后成为布兰的造船大臣(S8E6)。",
       "He goes south with Jon to meet Daenerys (S7E3), brings back Gendry (S7E5), and becomes Master of Ships to King Bran (S8E6)."),
    ]),
  N(id="melisandre", zh="梅丽珊卓", en="Melisandre", full=("梅丽珊卓", "Melisandre"), house="rhllor", grp="baratheon",
    debut=S2E1, dies=S8E3,
    camps=[(S2E1, "baratheon"), (S6E2, "stark", "复活琼恩", "Brings Jon back"), (S6E10, "none", "被琼恩逐出北境", "Banished by Jon"),
           (S7E2, "targaryen", "到龙石岛见丹妮莉丝", "Comes to Daenerys"), (S8E3, "stark", "长夜之战中归来", "Returns for the Long Night")],
    sub=("光之王的红袍女祭司", "Red priestess of the Lord of Light"),
    bios=[
      (S2E1, "来自亚夏的红袍女祭司，追随史坦尼斯，认定他是光之王选中的救世英雄(S2E1)。",
       "A red priestess from Asshai who believes Stannis is the Lord of Light’s chosen hero (S2E1)."),
      (S2E5, "她生下一个影子，刺杀了蓝礼(S2E5)。", "She gives birth to a shadow that kills Renly (S2E5)."),
      (S3E10, "她从无旗兄弟会手中买走詹德利(S3E6)，用他的血施法诅咒三位僭王(S3E8)。",
       "She buys Gendry from the Brotherhood (S3E6) and uses his blood to curse three usurpers (S3E8)."),
      (S5E9, "她随史坦尼斯北上，劝他把女儿希琳献祭给光之王(S5E9)。",
       "She follows Stannis north and persuades him to burn his daughter Shireen to the Lord of Light (S5E9)."),
      (S6E10, "她摘下项链，露出数百岁老妇的真容(S6E1)，却仍试着复活琼恩，竟然成功了(S6E2)。戴佛斯揭穿她烧死希琳，琼恩把她逐出北境(S6E10)。",
       "Taking off her necklace she shows her true, centuries-old face (S6E1), yet tries to raise Jon — and succeeds (S6E2). When Davos exposes Shireen’s burning, Jon banishes her (S6E10)."),
      (S8E3, "她去龙石岛为琼恩和丹妮莉丝牵线(S7E2)。长夜之战那夜，她回到临冬城点燃多斯拉克人的弯刀，天明时摘下项链，化为老妇死去(S8E3)。",
       "She goes to Dragonstone to bring Jon and Daenerys together (S7E2). On the night of the Long Night she returns to Winterfell to set the Dothraki blades alight, and at dawn takes off her necklace and dies an old woman (S8E3)."),
    ]),
  N(id="gendry", zh="詹德利", en="Gendry", full=("詹德利", "Gendry"), house="baratheon", grp="baratheon",
    debut=S1E4, dies=None,
    camps=[(S1E4, "none"), (S3E6, "baratheon", "被卖给梅丽珊卓", "Sold to Melisandre"), (S3E10, "none", "被戴佛斯放走", "Freed by Davos"),
           (S7E5, "stark", "随琼恩北上", "Joins Jon"), (S8E4, "baratheon", "受封风息堡公爵", "Made Lord of Storm’s End")],
    subs=[(S1E4, "铁匠学徒", "Blacksmith’s apprentice"), (S3E6, "劳勃的私生子", "Robert’s bastard"),
          (S8E4, "风息堡公爵詹德利·拜拉席恩", "Gendry Baratheon, Lord of Storm’s End")],
    sub=("劳勃的私生子，铁匠", "Robert’s bastard, a smith"),
    bios=[
      (S1E4, "君临的铁匠学徒。艾德追查琼恩·艾林的死因时找到了他，看出他是劳勃的私生子，他自己却不知道(S1E4)。",
       "A smith’s apprentice in King’s Landing. Ned, following Jon Arryn’s trail, finds him and sees he is Robert’s bastard, though Gendry does not know it (S1E4)."),
      (S2E8, "为躲避乔佛里对劳勃私生子的追杀，他混在去长城的新兵里，与艾莉亚结伴(S1E10)，在赫伦堡一起做苦工，又一起逃走(S2E8)。",
       "Hidden among recruits for the Wall from Joffrey’s purge of Robert’s bastards, he becomes Arya’s companion (S1E10), labours with her at Harrenhal and escapes with her (S2E8)."),
      (S3E10, "无旗兄弟会把他卖给梅丽珊卓(S3E6)，她要用他的“王者之血”施法；戴佛斯放他乘小船逃走(S3E10)。",
       "The Brotherhood sells him to Melisandre (S3E6), who wants his king’s blood; Davos sets him free in a rowing boat (S3E10)."),
      (S7E7, "戴佛斯在君临的铁匠铺里找到他(S7E5)，他随琼恩到长城以北，独自跑回东海望报信(S7E6)。",
       "Davos finds him at a forge in King’s Landing (S7E5); he goes north of the Wall with Jon and runs back alone to Eastwatch for help (S7E6)."),
      (S8E6, "他为长夜之战打造龙晶兵器(S8E1)，与艾莉亚相好(S8E2)；丹妮莉丝承认他是劳勃之子，封他为风息堡公爵，他向艾莉亚求婚却被拒绝(S8E4)。",
       "He forges dragonglass weapons for the Long Night (S8E1) and sleeps with Arya (S8E2); Daenerys legitimises him as Robert’s son and Lord of Storm’s End, and Arya turns down his proposal (S8E4)."),
    ]),
  N(id="brienne", zh="布蕾妮", en="Brienne", full=("塔斯的布蕾妮", "Brienne of Tarth"), house="tarth", grp="baratheon",
    debut=S2E3, dies=None,
    camps=[(S2E3, "baratheon"), (S2E5, "stark", "向凯特琳效忠", "Swears to Catelyn")],
    subs=[(S2E3, "蓝礼的御林护卫", "One of Renly’s Kingsguard"), (S2E5, "凯特琳的誓言骑士", "Sworn to Catelyn"),
          (S6E1, "珊莎的誓言骑士", "Sworn to Sansa"), (S8E2, "布蕾妮爵士", "Ser Brienne"), (S8E6, "御林铁卫队长", "Lord Commander of the Kingsguard")],
    sub=("塔斯岛的女骑士", "The warrior maid of Tarth"),
    bios=[
      (S2E3, "塔斯岛领主的女儿，身材高大，武艺超群。她在比武中击败洛拉斯，被蓝礼收为护卫(S2E3)。",
       "Daughter of the lord of Tarth, tall and a formidable fighter. She defeats Loras in the lists and Renly takes her into his guard (S2E3)."),
      (S2E8, "蓝礼在她眼前被影子刺死，她转而向凯特琳效忠(S2E5)，受命押送詹姆回君临(S2E8)。",
       "When Renly is killed before her eyes by a shadow she swears to Catelyn (S2E5), who sends her to take Jaime to King’s Landing (S2E8)."),
      (S3E10, "一路上她与詹姆互相敌视，后来一起被俘；詹姆为护她失去右手(S3E3)，又跳进熊坑救她(S3E7)。",
       "She and Jaime despise each other on the road until they are captured together; he loses his hand protecting her (S3E3) and leaps into a bear pit to save her (S3E7)."),
      (S4E10, "詹姆送她瓦雷利亚钢剑“守誓剑”，托她寻找珊莎(S4E4)。她找到了艾莉亚，与猎狗恶斗一场，艾莉亚却趁乱走掉了(S4E10)。",
       "Jaime gives her the Valyrian sword Oathkeeper to find Sansa (S4E4). She finds Arya instead and fights the Hound, but Arya slips away (S4E10)."),
      (S5E10, "珊莎拒绝了她的保护(S5E2)。她在临冬城外守候珊莎的信号，却遇上兵败的史坦尼斯，以蓝礼之仇处决了他(S5E10)。",
       "Sansa refuses her protection (S5E2). Watching Winterfell for Sansa’s signal, she comes on the defeated Stannis and executes him for Renly (S5E10)."),
      (S6E8, "她和波德从猎犬下救出珊莎，正式向她效忠(S6E1)，又去奔流城劝黑鱼出兵(S6E8)。",
       "She and Pod save Sansa from Ramsay’s hounds and she swears herself to Sansa (S6E1), then goes to Riverrun to bring the Blackfish north (S6E8)."),
      (S7E7, "她在临冬城教艾莉亚剑术(S7E4)，在龙穴劝詹姆说服瑟曦一起对抗亡者(S7E7)。",
       "She spars with Arya at Winterfell (S7E4) and at the Dragonpit begs Jaime to make Cersei join the fight against the dead (S7E7)."),
      (S8E6, "詹姆在临冬城封她为骑士(S8E2)。长夜之战后两人相好，詹姆却回了君临(S8E4)。她成为布兰的御林铁卫队长，在白典上为詹姆写下结局(S8E6)。",
       "Jaime knights her at Winterfell (S8E2). After the Long Night they become lovers, but he goes back to King’s Landing (S8E4). Lord Commander of King Bran’s Kingsguard, she completes Jaime’s entry in the White Book (S8E6)."),
    ]),
  # =============================================================== the Riverlands and the Vale
  N(id="edmure", zh="艾德慕", en="Edmure", full=("艾德慕·徒利", "Edmure Tully"), house="tully", grp="river",
    debut=S3E3, dies=None,
    camps=[(S3E3, "river")],
    subs=[(S3E3, "奔流城公爵", "Lord of Riverrun"), (S3E9, "佛雷家的俘虏", "A prisoner of the Freys"), (S8E6, "奔流城公爵", "Lord of Riverrun")],
    sub=("凯特琳的弟弟，奔流城公爵", "Catelyn’s brother, Lord of Riverrun"),
    bios=[
      (S3E3, "凯特琳的弟弟，刚刚继承了奔流城。父亲霍斯特的葬礼上，他三箭都没射中火船，最后叔叔黑鱼一箭替他射中；他擅自出兵，坏了罗柏的部署(S3E3)。",
       "Catelyn’s brother, newly Lord of Riverrun. At his father Hoster’s funeral he misses the burning boat three times until his uncle the Blackfish hits it for him; he has ruined Robb’s plans by attacking on his own (S3E3)."),
      (S3E9, "为了弥补罗柏的背约，他答应娶瓦德·佛雷的女儿萝丝琳(S3E6)。婚宴变成了屠杀，他被关进了孪河城的地牢(S3E9)。",
       "To make up for Robb’s broken promise he agrees to marry Walder Frey’s daughter Roslin (S3E6). The feast becomes a massacre and he is thrown in the dungeons of the Twins (S3E9)."),
      (S6E8, "佛雷家押着他去要挟奔流城，詹姆逼他下令开城投降(S6E8)。",
       "The Freys bring him to Riverrun as a hostage, and Jaime forces him to order the castle surrendered (S6E8)."),
      (S8E6, "他作为奔流城公爵出席推举新王的大会，想自荐为王，被珊莎请他坐下(S8E6)。",
       "As Lord of Riverrun he attends the great council and starts to put himself forward as king, until Sansa asks him to sit down (S8E6)."),
    ]),
  N(id="blackfish", zh="黑鱼", en="Blackfish", full=("布林登·徒利", "Brynden “the Blackfish” Tully"), house="tully", grp="river",
    debut=S3E3, dies=S6E8,
    camps=[(S3E3, "river")],
    sub=("凯特琳的叔叔，老练的战将", "Catelyn’s uncle, a seasoned commander"),
    bios=[
      (S3E3, "凯特琳的叔叔，身经百战。霍斯特葬礼上他一箭射中火船，替侄子艾德慕解了围(S3E3)。",
       "Catelyn’s uncle, a veteran of many wars. At Hoster’s funeral he hits the burning boat with one arrow and spares his nephew’s blushes (S3E3)."),
      (S3E9, "红色婚礼开始前，他离席出去，逃过一劫(S3E9)。", "He steps out of the hall just before the Red Wedding begins, and escapes it (S3E9)."),
      (S6E8, "他夺回奔流城据守(S6E6)，拒绝向詹姆投降(S6E7)，也不肯随布蕾妮去北境；艾德慕下令开城后，他留下来战死(S6E8)。",
       "He retakes Riverrun and holds it (S6E6), refusing Jaime’s terms (S6E7) and Brienne’s plea to go north; when Edmure opens the gates he stays to fight, and dies (S6E8)."),
    ]),
  N(id="walder", zh="瓦德", en="Walder Frey", full=("瓦德·佛雷", "Walder Frey"), house="frey", grp="river",
    debut=S1E9, dies=S6E10,
    camps=[(S1E9, "river"), (S3E9, "lannister", "在红色婚礼上倒向兰尼斯特", "Turns to the Lannisters at the Red Wedding")],
    sub=("孪河城城主，红色婚礼的主人", "Lord of the Crossing, host of the Red Wedding"),
    bios=[
      (S1E9, "孪河城的老领主，子孙成群，贪婪刻薄。罗柏要借道渡河，他逼罗柏答应娶他的一个女儿，艾莉亚嫁他的一个儿子(S1E9)。",
       "The old lord of the Twins, with a swarm of children, greedy and spiteful. To let Robb cross he makes him promise to marry one of his daughters, and Arya one of his sons (S1E9)."),
      (S3E9, "罗柏违约另娶，他要艾德慕来娶萝丝琳(S3E6)，在婚宴上与卢斯·波顿合谋，杀死了罗柏、凯特琳和北境将士(S3E9)。",
       "When Robb breaks his word he demands Edmure for Roslin (S3E6), and at the feast, with Roose Bolton, has Robb, Catelyn and the Northern host slaughtered (S3E9)."),
      (S6E10, "他拿艾德慕要挟奔流城(S6E6—S6E8)。一个侍女端上肉饼，说那是用他两个儿子做的馅，随即揭下面孔——她是艾莉亚，一刀割开了他的喉咙(S6E10)。",
       "He uses Edmure to win back Riverrun (S6E6–S6E8). A serving girl tells him the pie he is eating is made of his two sons, then shows her face — Arya — and cuts his throat (S6E10)."),
    ]),
  N(id="beric", zh="贝里", en="Beric", full=("贝里·唐德利恩", "Beric Dondarrion"), house="dondarrion", grp="river",
    debut=S1E6, dies=S8E3,
    camps=[(S1E6, "baratheon"), (S3E4, "river", "无旗兄弟会的首领", "Leads the Brotherhood"), (S7E5, "stark", "随琼恩北上", "Joins Jon")],
    subs=[(S1E6, "奉命缉拿魔山的骑士", "Knight sent after the Mountain"), (S3E4, "无旗兄弟会首领", "Leader of the Brotherhood without Banners")],
    sub=("无旗兄弟会首领，屡死屡生", "Leader of the Brotherhood without Banners, who keeps coming back from death"),
    bios=[
      (S1E6, "代理首相艾德派他去缉拿在河间烧杀的魔山(S1E6)。", "Ned, as acting Hand, sends him to bring the Mountain to justice in the Riverlands (S1E6)."),
      (S3E5, "他领导“无旗兄弟会”，在河间保护百姓、对抗兰尼斯特(S3E4)。他与猎狗决斗被杀，又被红袍僧索罗斯救活——这已是他第六次死而复生(S3E5)。",
       "He leads the Brotherhood without Banners, protecting the smallfolk of the Riverlands against the Lannisters (S3E4). Killed by the Hound in a trial by combat, he is raised again by the red priest Thoros — for the sixth time (S3E5)."),
      (S7E7, "他和索罗斯收留了猎狗(S6E8)，随琼恩到长城以北捉尸鬼(S7E6)。", "He and Thoros take in the Hound (S6E8) and go north with Jon to catch a wight (S7E6)."),
      (S8E3, "长夜之战中，他用身体挡住尸鬼，掩护艾莉亚逃走，终于真正死去(S8E3)。",
       "In the Long Night he holds back the dead with his body so Arya can escape, and dies for the last time (S8E3)."),
    ]),
  N(id="thoros", zh="索罗斯", en="Thoros", full=("密尔的索罗斯", "Thoros of Myr"), house="rhllor", grp="river",
    debut=S3E2, dies=S7E6,
    camps=[(S3E2, "river"), (S7E5, "stark", "随琼恩北上", "Joins Jon")],
    sub=("红袍僧，无旗兄弟会的一员", "Red priest of the Brotherhood"),
    bios=[
      (S3E5, "来自密尔的红袍僧，嗜酒如命。他在无旗兄弟会中一次次用光之王的力量救活贝里(S3E5)。",
       "A hard-drinking red priest from Myr who, in the Brotherhood, raises Beric again and again by the Lord of Light’s power (S3E5)."),
      (S7E6, "他随琼恩到长城以北捉尸鬼，为救猎狗被尸熊咬伤，夜里在冰湖中的岩石上冻死(S7E6)。",
       "Going north with Jon to catch a wight, he is mauled by a dead bear saving the Hound, and freezes to death on the rock in the frozen lake (S7E6)."),
    ]),
  N(id="lysa", zh="莱莎", en="Lysa", full=("莱莎·艾林", "Lysa Arryn"), house="arryn", grp="river",
    born=("徒利", "Tully"), debut=S1E5, dies=S4E7,
    camps=[(S1E5, "arryn")],
    sub=("凯特琳的妹妹，鹰巢城夫人", "Catelyn’s sister, Lady of the Eyrie"),
    bios=[
      (S1E5, "凯特琳的妹妹，琼恩·艾林的遗孀。丈夫死后她带着儿子逃回鹰巢城，疑神疑鬼。凯特琳押着提利昂来投奔她，她把提利昂关进天牢(S1E5)。",
       "Catelyn’s sister, Jon Arryn’s widow, who fled with her son to the Eyrie and trusts no one. When Catelyn brings her Tyrion, she throws him into a sky cell (S1E5)."),
      (S4E7, "小指头来到鹰巢城，她说漏了嘴：当年是她受小指头指使毒死了丈夫，又写信诬陷兰尼斯特家；随后两人匆匆成婚(S4E5)。她嫉妒珊莎，要把她推下月门，反被小指头推了下去(S4E7)。",
       "When Littlefinger arrives she lets slip that she poisoned her husband at his urging and wrote the letter blaming the Lannisters; then they are hurriedly married (S4E5). Jealous of Sansa, she tries to push her through the Moon Door, and Littlefinger pushes Lysa instead (S4E7)."),
    ]),
  N(id="robin", zh="罗宾", en="Robin", full=("罗宾·艾林", "Robin Arryn"), house="arryn", grp="river",
    debut=S1E5, dies=None,
    camps=[(S1E5, "arryn")],
    sub=("鹰巢城的小公爵", "The boy Lord of the Eyrie"),
    bios=[
      (S1E5, "莱莎的独子，体弱多病，这么大了还在吃奶，最爱看人从月门掉下去(S1E5)。",
       "Lysa’s only son, sickly, still at the breast, and fond of watching people fall through the Moon Door (S1E5)."),
      (S6E9, "母亲死后，他由小指头监护(S4E7)；小指头哄他派出谷地骑兵去帮珊莎(S6E4)。",
       "After his mother’s death he is in Littlefinger’s care (S4E7), and Littlefinger coaxes him into sending the knights of the Vale to help Sansa (S6E4)."),
      (S8E6, "长大成人后，他作为谷地公爵出席了推举新王的大会(S8E6)。", "Grown up, he sits at the great council as Lord of the Vale (S8E6)."),
    ]),
  N(id="jonarryn", zh="琼恩·艾林", en="Jon Arryn", full=("琼恩·艾林", "Jon Arryn"), house="arryn", grp="river",
    debut=S1E1, dies=PRE,
    camps=[(S1E1, "baratheon")],
    subs=[(S1E1, "前任国王之手，刚刚猝死", "The late Hand of the King, just dead"), (S4E5, "被毒杀的首相", "The poisoned Hand")],
    sub=("前任国王之手，莱莎的丈夫", "The late Hand of the King, Lysa’s husband"),
    bios=[
      (S1E1, "谷地公爵，劳勃和艾德少年时的监护人，劳勃的国王之手。剧集开始时他刚刚病死，莱莎来信说他是被兰尼斯特家害死的(S1E1)。",
       "Lord of the Vale, foster-father to Robert and Ned and Robert’s Hand. He has just died of a sudden illness as the story opens, and Lysa writes that the Lannisters killed him (S1E1)."),
      (S1E6, "艾德查明，他死前正在追查瑟曦孩子们的身世(S1E6)。", "Ned learns that before he died he was looking into the parentage of Cersei’s children (S1E6)."),
      (S4E5, "真相是：莱莎在小指头的指使下毒死了他，又写信诬陷兰尼斯特家，掀起了七国大乱(S4E5)。",
       "The truth: Lysa poisoned him at Littlefinger’s urging and wrote the letter blaming the Lannisters that set the realm at war (S4E5)."),
    ]),
  # =============================================================== the Reach and Dorne
  N(id="olenna", zh="奥莲娜", en="Olenna", full=("奥莲娜·提利尔", "Olenna Tyrell"), house="tyrell", grp="south",
    born=("雷德温", "Redwyne"), debut=S3E2, dies=S7E3,
    camps=[(S3E2, "tyrell"), (S7E2, "targaryen", "投奔丹妮莉丝", "Joins Daenerys")],
    sub=("提利尔家的老夫人，“荆棘女王”", "The Tyrell matriarch, ‘the Queen of Thorns’"),
    bios=[
      (S3E6, "梅斯的母亲，玛格丽和洛拉斯的祖母，言辞刻薄、手段老辣，人称“荆棘女王”。她向珊莎打听乔佛里的为人(S3E2)，又与泰温针锋相对地谈婚论嫁(S3E6)。",
       "Mace’s mother and grandmother of Margaery and Loras, sharp-tongued and shrewd — the Queen of Thorns. She asks Sansa what Joffrey is really like (S3E2) and fences with Tywin over marriages (S3E6)."),
      (S4E4, "乔佛里在婚宴上中毒身亡(S4E2)；不久她向玛格丽暗示，自己不会让孙女嫁给一个疯子(S4E4)。",
       "Joffrey dies of poison at his wedding (S4E2); soon after, she lets Margaery understand she would never have let her granddaughter stay married to a monster (S4E4)."),
      (S6E10, "她已离开君临回到高庭(S6E7)；大圣堂爆炸，儿孙尽死，她来到多恩，与艾拉莉亚结盟，准备投奔丹妮莉丝(S6E10)。",
       "She has already left King’s Landing for Highgarden (S6E7); with her son and grandchildren dead in the Sept, she comes to Dorne and joins Ellaria in turning to Daenerys (S6E10)."),
      (S7E3, "詹姆攻下高庭，给她一杯无痛的毒酒。她一饮而尽，然后告诉詹姆：毒死乔佛里的是她(S7E3)。",
       "Jaime takes Highgarden and offers her a painless poison. She drinks it down, then tells him that it was she who poisoned Joffrey (S7E3)."),
    ]),
  N(id="mace", zh="梅斯", en="Mace", full=("梅斯·提利尔", "Mace Tyrell"), house="tyrell", grp="south",
    debut=S4E2, dies=S6E10,
    camps=[(S4E2, "tyrell")],
    sub=("高庭公爵", "Lord of Highgarden"),
    bios=[
      (S4E2, "高庭公爵，奥莲娜的儿子，玛格丽和洛拉斯的父亲，富有而无谋，凡事听母亲安排(S4E2)。",
       "Lord of Highgarden, Olenna’s son and father of Margaery and Loras, rich and foolish, ruled by his mother (S4E2)."),
      (S6E10, "儿女被大麻雀囚禁，他想率军去解救(S6E6)，最后与他们一同死在大圣堂的野火中(S6E10)。",
       "When the High Sparrow holds his children he marches his army to free them (S6E6), and dies with them in the wildfire at the Sept (S6E10)."),
    ]),
  N(id="loras", zh="洛拉斯", en="Loras", full=("洛拉斯·提利尔爵士", "Ser Loras Tyrell"), house="tyrell", grp="south",
    debut=S1E5, dies=S6E10,
    camps=[(S1E5, "tyrell")],
    sub=("“百花骑士”，蓝礼的恋人", "The Knight of Flowers, Renly’s lover"),
    bios=[
      (S1E5, "提利尔家的幼子，“百花骑士”。他在比武大会上骑一匹发情的母马击败了魔山，私下与蓝礼相爱(S1E5)。",
       "Youngest son of House Tyrell, the Knight of Flowers. He unhorses the Mountain at the tourney on a mare in heat, and is secretly Renly’s lover (S1E5)."),
      (S2E9, "蓝礼称王后他做了护卫队长；蓝礼死后，他随提利尔大军倒向兰尼斯特，黑水河之战中及时赶到(S2E9)。",
       "He commands Renly’s guard; after Renly’s death he brings the Tyrell host over to the Lannisters and arrives in time at the Blackwater (S2E9)."),
      (S6E10, "泰温要他娶瑟曦(S3E5)，婚约后来作罢。他因与男人相好被大麻雀逮捕(S5E4)，受审时认罪，被剃发刻额，随即死在大圣堂的爆炸中(S6E10)。",
       "Tywin means to marry him to Cersei (S3E5), but it comes to nothing. Arrested by the High Sparrow for loving men (S5E4), he confesses at his trial, is shorn and branded, and dies moments later when the Sept explodes (S6E10)."),
    ]),
  N(id="margaery", zh="玛格丽", en="Margaery", full=("玛格丽·提利尔", "Margaery Tyrell"), house="tyrell", grp="south",
    debut=S2E3, dies=S6E10,
    camps=[(S2E3, "baratheon", "嫁给蓝礼", "Marries Renly"), (S2E10, "lannister", "与乔佛里订婚", "Betrothed to Joffrey"),
           (S6E6, "faith", "假意皈依信仰", "Feigns devotion to the Faith")],
    subs=[(S2E3, "蓝礼的王后", "Renly’s queen"), (S2E10, "乔佛里的未婚妻", "Joffrey’s betrothed"), (S4E2, "乔佛里的遗孀", "Joffrey’s widow"),
          (S5E3, "托曼的王后", "Tommen’s queen")],
    sub=("提利尔家的女儿，先后许嫁三位国王", "The Tyrell daughter who married three kings"),
    bios=[
      (S2E3, "提利尔家美丽聪慧的女儿。她嫁给蓝礼，明知他爱的是自己的哥哥洛拉斯(S2E3)。",
       "The clever, beautiful Tyrell daughter. She marries Renly knowing full well that he loves her brother Loras (S2E3)."),
      (S4E2, "蓝礼死后，她被许配给乔佛里(S2E10)，善于收买人心，在君临的平民中颇有声望；婚宴上新郎中毒身亡(S4E2)。",
       "After Renly’s death she is betrothed to Joffrey (S2E10) and wins the hearts of the common people of King’s Landing; her bridegroom dies of poison at the feast (S4E2)."),
      (S5E10, "她嫁给了托曼(S5E3)，把瑟曦挤出宫廷；为了哥哥在信仰法庭上作伪证，被大麻雀抓进牢里(S5E6)。",
       "She marries Tommen (S5E3) and edges Cersei out of court, but lies before the Faith to protect her brother and is imprisoned by the High Sparrow (S5E6)."),
      (S6E10, "她假意皈依信仰以求脱身(S6E6)。在大圣堂里，她察觉瑟曦没有到场，想带大家逃走，却被野火吞没(S6E10)。",
       "She feigns devotion to the Faith to win her way out (S6E6). In the Sept she realises Cersei has not come and tries to get everyone out, but the wildfire takes them (S6E10)."),
    ]),
  N(id="randyll", zh="蓝道", en="Randyll", full=("蓝道·塔利", "Randyll Tarly"), house="tarly", grp="south",
    debut=S6E6, dies=S7E5,
    camps=[(S6E6, "tyrell"), (S7E3, "lannister", "背弃提利尔家", "Betrays the Tyrells")],
    sub=("角陵伯爵，山姆的父亲", "Lord of Horn Hill, Sam’s father"),
    bios=[
      (S6E6, "山姆的父亲，河湾最出色的将领，瞧不起软弱的长子，当年逼他去了长城。山姆带吉莉回家，他在饭桌上当众羞辱山姆(S6E6)。",
       "Sam’s father, the finest soldier in the Reach, who despised his soft eldest son and sent him to the Wall. When Sam comes home with Gilly he humiliates him at dinner (S6E6)."),
      (S7E5, "他背弃提利尔家，随詹姆攻打高庭(S7E3)；辎重之战后被俘，拒绝向丹妮莉丝屈膝，与次子狄肯一同被龙焰烧死(S7E5)。",
       "He abandons the Tyrells to take Highgarden with Jaime (S7E3); captured after the loot train battle, he refuses to kneel to Daenerys and is burned by her dragon with his younger son Dickon (S7E5)."),
    ]),
  N(id="oberyn", zh="奥柏伦", en="Oberyn", full=("奥柏伦·马泰尔", "Oberyn Martell"), house="martell", grp="south",
    debut=S4E1, dies=S4E8,
    camps=[(S4E1, "martell")],
    sub=("“红毒蛇”，多恩亲王之弟", "‘The Red Viper’, brother to the Prince of Dorne"),
    bios=[
      (S4E1, "多恩亲王道朗的弟弟，“红毒蛇”，精通毒药与长矛。他来君临参加乔佛里的婚礼，真正的目的是为姐姐伊莉亚报仇：当年魔山杀死了她和她的孩子(S4E1)。",
       "Brother of Prince Doran of Dorne, the Red Viper, master of poisons and the spear. He comes to King’s Landing for Joffrey’s wedding, but really to avenge his sister Elia, killed with her children by the Mountain (S4E1)."),
      (S4E8, "他自愿为提利昂出战魔山(S4E7)，占尽上风，却在逼魔山认罪时一时大意，被魔山抓住挤碎了头颅(S4E8)。",
       "He volunteers to be Tyrion’s champion against the Mountain (S4E7), and has him beaten — but, demanding a confession, lets the Mountain seize him and crush his skull (S4E8)."),
    ]),
  N(id="ellaria", zh="艾拉莉亚", en="Ellaria", full=("艾拉莉亚·沙德", "Ellaria Sand"), house="martell", grp="south",
    debut=S4E1, dies=None,
    camps=[(S4E1, "martell"), (S7E2, "targaryen", "与丹妮莉丝结盟", "Allies with Daenerys"),
           (S7E3, "lannister", "被瑟曦囚禁", "Imprisoned by Cersei")],
    sub=("奥柏伦的情人", "Oberyn’s paramour"),
    bios=[
      (S4E8, "奥柏伦的情人，随他来到君临(S4E1)，眼看他死在魔山手下(S4E8)。",
       "Oberyn’s paramour, who comes with him to King’s Landing (S4E1) and watches him die at the Mountain’s hands (S4E8)."),
      (S5E10, "她带着奥柏伦的女儿们“沙蛇”向兰尼斯特家报复(S5E4)，用唇上的毒药毒死了弥赛菈(S5E10)。",
       "With Oberyn’s daughters, the Sand Snakes, she takes revenge on the Lannisters (S5E4), killing Myrcella with poison on her lips (S5E10)."),
      (S6E10, "她刺死了道朗亲王，夺取多恩(S6E1)，与奥莲娜一起投奔丹妮莉丝(S6E10)。",
       "She murders Prince Doran and takes Dorne (S6E1), and joins Olenna in turning to Daenerys (S6E10)."),
      (S7E3, "她的船队被攸伦截获(S7E2)。瑟曦用同样的毒药毒死了她的女儿泰妮丝，把她锁在地牢里眼看女儿死去(S7E3)。",
       "Euron captures her at sea (S7E2). Cersei poisons her daughter Tyene the same way and chains Ellaria in a cell to watch her die (S7E3)."),
    ]),
  N(id="doran", zh="道朗", en="Doran", full=("道朗·马泰尔", "Doran Martell"), house="martell", grp="south",
    debut=S5E2, dies=S6E1,
    camps=[(S5E2, "martell")],
    sub=("多恩亲王", "Prince of Dorne"),
    bios=[
      (S5E2, "多恩亲王，奥柏伦的哥哥，患痛风只能坐轮椅，处事谨慎，不愿为弟弟报仇开战(S5E2)。",
       "Prince of Dorne, Oberyn’s elder brother, gouty and in a wheeled chair, too cautious to go to war for his brother (S5E2)."),
      (S5E9, "他扣下闯入多恩的詹姆，最终放弥赛菈随他回君临(S5E9)。", "He detains Jaime when he comes to Dorne, then lets Myrcella go home with him (S5E9)."),
      (S6E1, "艾拉莉亚不满他的软弱，在流水花园刺死了他(S6E1)。", "Ellaria, despising his weakness, stabs him to death in the Water Gardens (S6E1)."),
    ]),
  # =============================================================== the Iron Islands
  N(id="balon", zh="巴隆", en="Balon", full=("巴隆·葛雷乔伊", "Balon Greyjoy"), house="greyjoy", grp="iron",
    debut=S2E2, dies=S6E2,
    camps=[(S2E2, "greyjoy")],
    sub=("铁群岛之王", "King of the Iron Islands"),
    bios=[
      (S2E2, "铁群岛之主，九年前叛乱失败，儿子席恩被艾德带走做人质。席恩回来劝他与罗柏结盟，他讥讽儿子已成了狼崽子，说王冠要凭铁与血自己去夺(S2E2)。",
       "Lord of the Iron Islands, whose rebellion failed nine years ago and cost him his son Theon as a hostage. When Theon comes home to propose an alliance with Robb, Balon sneers that he has become a wolf: he will take his crown by the iron price (S2E2)."),
      (S2E3, "他派雅拉和席恩出兵，趁罗柏南征偷袭北境(S2E3)。", "He sends Yara and Theon to raid the North while Robb is away in the south (S2E3)."),
      (S3E10, "拉姆斯寄来从席恩身上割下的东西，他不肯为一个废人让步，女儿雅拉便自行出兵去救(S3E10)。",
       "When Ramsay sends him a piece of Theon in a box, he will not bargain for a ruined son, and his daughter Yara sails to save Theon herself (S3E10)."),
      (S6E2, "他在风雨中走过吊桥，被弟弟攸伦推下桥去(S6E2)。", "Crossing a rope bridge in a storm, he is thrown from it by his brother Euron (S6E2)."),
    ]),
  N(id="yara", zh="雅拉", en="Yara", full=("雅拉·葛雷乔伊", "Yara Greyjoy"), house="greyjoy", grp="iron",
    debut=S2E2, dies=None,
    camps=[(S2E2, "greyjoy"), (S6E9, "targaryen", "与丹妮莉丝结盟", "Allies with Daenerys")],
    sub=("巴隆的女儿，铁种的女船长", "Balon’s daughter, an ironborn captain"),
    bios=[
      (S2E2, "巴隆的女儿，席恩的姐姐，深得父亲信任。席恩回家时，她假装陌生人戏弄了他一番(S2E2)。",
       "Balon’s daughter and Theon’s sister, her father’s trusted captain. When Theon comes home she pretends to be a stranger and makes a fool of him (S2E2)."),
      (S4E6, "她率船去恐怖堡营救席恩，席恩却已被拉姆斯驯服，不肯跟她走(S4E6)。",
       "She raids the Dreadfort to rescue Theon, but he is so broken by Ramsay that he will not come (S4E6)."),
      (S6E9, "父亲死后，她在选王会上被攸伦夺去王位，带着舰队和席恩出逃(S6E5)，在弥林与丹妮莉丝结盟(S6E9)。",
       "When her father dies, Euron wins the Kingsmoot from her; she flees with the fleet and Theon (S6E5) and allies with Daenerys in Meereen (S6E9)."),
      (S8E6, "攸伦突袭她的舰队，俘虏了她(S7E2)；席恩救出了她(S8E1)。她回到铁群岛，最后在大会上为铁群岛投票支持布兰为王(S8E6)。",
       "Euron ambushes her fleet and takes her captive (S7E2); Theon rescues her (S8E1). She goes home to the Iron Islands, and speaks for them at the council that chooses Bran (S8E6)."),
    ]),
  N(id="theon", zh="席恩", en="Theon", full=("席恩·葛雷乔伊", "Theon Greyjoy"), house="greyjoy", grp="iron",
    debut=S1E1, dies=S8E3, home="greyjoy",
    camps=[(S1E1, "stark", "临冬城的养子与人质", "Ward and hostage at Winterfell"), (S2E3, "greyjoy", "背叛罗柏，投回父亲", "Turns from Robb to his father"),
           (S2E10, "bolton", "被出卖，落入波顿家之手", "Betrayed into the Boltons’ hands"), (S5E10, "stark", "带珊莎逃走", "Escapes with Sansa"),
           (S6E4, "greyjoy", "回到铁群岛", "Back in the Iron Islands"), (S6E9, "targaryen", "随雅拉投奔丹妮莉丝", "With Yara, joins Daenerys"),
           (S8E2, "stark", "回临冬城保护布兰", "Comes back to Winterfell to guard Bran")],
    subs=[(S1E1, "巴隆的儿子，史塔克家的养子", "Balon’s son, the Starks’ ward"), (S2E6, "临冬城的占领者", "The taker of Winterfell"),
          (S2E10, "被囚的俘虏", "A prisoner"), (S3E10, "“臭佬”", "‘Reek’"), (S6E4, "席恩·葛雷乔伊", "Theon Greyjoy")],
    sub=("巴隆之子，史塔克家的养子", "Balon’s son, raised by the Starks"),
    bios=[
      (S1E1, "巴隆·葛雷乔伊的儿子，铁群岛叛乱失败后被艾德带回临冬城当人质，与罗柏一起长大(S1E1)。",
       "Son of Balon Greyjoy, taken to Winterfell as a hostage after the failed ironborn rebellion and raised alongside Robb (S1E1)."),
      (S2E10, "他奉罗柏之命回铁群岛求援，得不到父亲的认可，转而背叛罗柏(S2E3)。他偷袭夺下临冬城，处死罗德利克爵士(S2E6)，又烧死两个农家孩子冒充布兰和瑞肯(S2E7)；最后被自己的部下打晕出卖(S2E10)。",
       "Sent by Robb to seek his father’s help, he is scorned and turns on Robb (S2E3). He seizes Winterfell, beheads Ser Rodrik (S2E6) and burns two farm boys to pass off as Bran and Rickon (S2E7); in the end his own men knock him out and hand him over (S2E10)."),
      (S4E8, "他落到拉姆斯手里受尽折磨，被阉割(S3E7)，成了一个叫“臭佬”的奴仆(S3E10)，替拉姆斯骗开了卡林湾(S4E8)。",
       "In Ramsay’s hands he is tortured and castrated (S3E7) and remade as a servant called Reek (S3E10), who tricks Moat Cailin into surrendering for him (S4E8)."),
      (S5E10, "珊莎嫁进临冬城后，他被迫眼看她受辱(S5E6)；最后他杀了米兰达，带珊莎从城墙上跳下(S5E10)。",
       "When Sansa is married into Winterfell he is made to watch her abused (S5E6); at last he kills Myranda and leaps from the walls with Sansa (S5E10)."),
      (S6E9, "他把珊莎送到安全的地方，回到铁群岛(S6E4)，支持姐姐雅拉，随她投奔丹妮莉丝(S6E9)。",
       "Seeing Sansa to safety, he goes home to the Iron Islands (S6E4), stands behind his sister Yara and goes with her to Daenerys (S6E9)."),
      (S8E3, "攸伦袭击船队时他跳海逃生(S7E2)，后来救出雅拉(S8E1)，回到临冬城请求保护布兰(S8E2)。长夜之战中他守在布兰身边，最后冲向夜王，被刺死(S8E3)。",
       "When Euron attacks the fleet he jumps overboard (S7E2); later he rescues Yara (S8E1) and returns to Winterfell to guard Bran (S8E2). In the Long Night he stands by Bran to the end and dies charging the Night King (S8E3)."),
    ]),
  N(id="euron", zh="攸伦", en="Euron", full=("攸伦·葛雷乔伊", "Euron Greyjoy"), house="greyjoy", grp="iron",
    debut=S6E2, dies=S8E5,
    camps=[(S6E2, "greyjoy"), (S7E3, "lannister", "献上艾拉莉亚，与瑟曦结盟", "Wins Cersei’s alliance with his prisoners")],
    subs=[(S6E2, "巴隆的弟弟", "Balon’s brother"), (S6E5, "铁群岛之王", "King of the Iron Islands")],
    sub=("巴隆的弟弟，海盗之王", "Balon’s brother, a pirate king"),
    bios=[
      (S6E2, "巴隆的弟弟，在海上漂泊多年后突然归来，在吊桥上杀死了哥哥(S6E2)。",
       "Balon’s brother, back from long years at sea, who kills him on the bridge (S6E2)."),
      (S6E5, "他在选王会上夺得海石之位，雅拉带着舰队出逃(S6E5)。", "He wins the Kingsmoot, and Yara flees with the fleet (S6E5)."),
      (S7E7, "他带着千艘战舰来君临向瑟曦求婚(S7E1)，夜袭雅拉的舰队，把艾拉莉亚母女献给瑟曦(S7E2—S7E3)。",
       "He brings a thousand ships to King’s Landing to court Cersei (S7E1), destroys Yara’s fleet by night and gives Ellaria and her daughter to Cersei (S7E2–S7E3)."),
      (S8E5, "他射杀了丹妮莉丝的龙雷哥(S8E4)。君临陷落时他在海边与詹姆搏斗，刺伤詹姆，自己也被刺死(S8E5)。",
       "He shoots down Daenerys’s dragon Rhaegal (S8E4). As King’s Landing falls he fights Jaime on the shore, wounds him and is killed (S8E5)."),
    ]),
]
