# -*- coding: utf-8 -*-
"""Game of Thrones (TV): the Targaryens and Essos. Field meanings are listed in nodes_got_north.py."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import N  # noqa: E402
from episodes_got import *  # noqa: E402,F401,F403

PRE = 0

NODES_ESSOS = [
  # =============================================================== House Targaryen
  N(id="daenerys", zh="丹妮莉丝", en="Daenerys", full=("丹妮莉丝·坦格利安", "Daenerys Targaryen"), house="targaryen", grp="essos",
    debut=S1E1, dies=S8E6,
    camps=[(S1E1, "targaryen")],
    subs=[(S1E1, "流亡的坦格利安公主", "An exiled Targaryen princess"), (S1E2, "卓戈的卡丽熙", "Drogo’s khaleesi"),
          (S1E10, "龙之母", "Mother of Dragons"), (S3E10, "奴隶的解放者", "Breaker of chains"), (S4E5, "弥林女王", "Queen in Meereen"),
          (S7E1, "登陆龙石岛的女王", "Queen at Dragonstone")],
    sub=("坦格利安家的末裔，龙之母", "Last of the Targaryens, Mother of Dragons"),
    bios=[
      (S1E1, "疯王伊里斯的女儿，生于叛乱之后，随哥哥韦赛里斯流亡厄索斯。韦赛里斯把她嫁给多斯拉克的卓戈卡奥，换取一支军队(S1E1)。",
       "The Mad King’s daughter, born after his fall and raised in exile across the sea with her brother Viserys, who sells her in marriage to the Dothraki Khal Drogo for an army (S1E1)."),
      (S1E10, "她在多斯拉克人中渐渐站稳脚跟，爱上了卓戈(S1E6)。卓戈伤口溃烂，她请巫女弥丽用血魔法施救(S1E9)，却失去了腹中的孩子，卓戈也成了活死人。她闷死卓戈，把弥丽绑上火葬堆，自己抱着三颗龙蛋走进烈火，第二天带着三条小龙从灰烬中走出(S1E10)。",
       "Among the Dothraki she finds her strength and comes to love Drogo (S1E6). When his wound festers she asks the godswife Mirri to save him with blood magic (S1E9); she loses her unborn son and Drogo is left a living husk. She smothers him, binds Mirri to the pyre and walks into the fire with three dragon eggs, emerging next morning with three newborn dragons (S1E10)."),
      (S2E10, "她带残部穿越红色荒原，到了魁尔斯(S2E4)；龙被偷走，她闯进不朽之殿夺回了龙(S2E10)。",
       "She leads her people across the Red Waste to Qarth (S2E4); when her dragons are stolen she goes into the House of the Undying and takes them back (S2E10)."),
      (S3E10, "她在阿斯塔波用一条龙换来无垢者大军，转手就让龙烧死奴隶主，解放了全城(S3E4)；拿下渊凯后，被解放的奴隶把她高高举起，称她“弥莎”——母亲(S3E10)。",
       "In Astapor she trades a dragon for the Unsullied, then has the dragon burn the slavers and frees the city (S3E4); after she takes Yunkai the freed slaves lift her up and call her Mhysa — mother (S3E10)."),
      (S4E10, "她攻下弥林，把一百六十三个奴隶主钉在十字架上(S4E4)，决定留下来统治(S4E5)。得知乔拉曾为劳勃监视她，她放逐了乔拉(S4E8)；卓耿烧死一个孩子后，她把另外两条龙锁进地窖(S4E10)。",
       "She takes Meereen and crucifies a hundred and sixty-three masters (S4E4), and stays to rule (S4E5). Learning that Jorah once spied on her for Robert, she banishes him (S4E8); when Drogon kills a child she chains her other two dragons in a pit (S4E10)."),
      (S5E10, "鹰身女妖之子不断杀人，她答应嫁给希兹达尔、重开竞技场(S5E5)；竞技场遇袭时，卓耿飞来把她带走(S5E9)，落在多斯拉克海上，被一支卡拉萨围住(S5E10)。",
       "As the Sons of the Harpy keep killing, she agrees to marry Hizdahr and reopen the fighting pits (S5E5); when they attack the pit, Drogon carries her off (S5E9) to the Dothraki sea, where a khalasar surrounds her (S5E10)."),
      (S6E10, "她被押到维斯·多斯拉克，烧死了众卡奥，全体多斯拉克人向她跪拜(S6E4)。回到弥林后，她大败奴隶主的舰队，与雅拉结盟(S6E9)，任命提利昂为女王之手，扬帆西进(S6E10)。",
       "Taken to Vaes Dothrak, she burns the khals alive and the Dothraki kneel to her (S6E4). Back in Meereen she destroys the masters’ fleet and allies with Yara (S6E9), names Tyrion Hand and sails west (S6E10)."),
      (S7E7, "她登陆龙石岛(S7E1)，与琼恩相见(S7E3)，烧毁兰尼斯特的辎重车队(S7E4)，又飞到长城以北救下琼恩，却失去了龙韦赛利昂(S7E6)。她在船上与琼恩相爱，不知道两人是姑侄(S7E7)。",
       "She lands on Dragonstone (S7E1), meets Jon (S7E3), burns the Lannister loot train (S7E4) and flies beyond the Wall to save Jon, losing her dragon Viserion (S7E6). She and Jon become lovers on the voyage north, not knowing she is his aunt (S7E7)."),
      (S8E6, "她在临冬城得知琼恩才是铁王座的合法继承人(S8E2)。长夜之战后，她接连失去乔拉、雷哥和弥桑黛(S8E3—S8E4)。君临投降的钟声已经响起，她仍骑龙焚城(S8E5)，在铁王座前被琼恩刺死，卓耿把她的遗体带走(S8E6)。",
       "At Winterfell she learns Jon is the true heir to the Iron Throne (S8E2). After the Long Night she loses Jorah, Rhaegal and Missandei (S8E3–S8E4). When the bells of surrender ring in King’s Landing she burns the city anyway (S8E5); Jon stabs her before the Iron Throne, and Drogon carries her body away (S8E6)."),
    ]),
  N(id="viserys", zh="韦赛里斯", en="Viserys", full=("韦赛里斯·坦格利安", "Viserys Targaryen"), house="targaryen", grp="essos",
    debut=S1E1, dies=S1E6,
    camps=[(S1E1, "targaryen")],
    sub=("疯王的儿子，自称维斯特洛的国王", "The Mad King’s son, who calls himself king"),
    bios=[
      (S1E1, "疯王伊里斯的儿子，丹妮莉丝的哥哥，自认是维斯特洛的合法国王。他把妹妹嫁给卓戈卡奥，想换一支军队回去夺位(S1E1)。",
       "Son of the Mad King and Daenerys’s brother, who believes himself the rightful king of Westeros. He marries his sister to Khal Drogo in exchange for an army to win back the throne (S1E1)."),
      (S1E6, "他在多斯拉克人中受尽冷遇，对妹妹越来越凶暴。在维斯·多斯拉克的宴会上，他拔剑威胁怀孕的妹妹，卓戈答应给他一顶“金冠”——一锅熔化的黄金浇在他头上(S1E6)。",
       "Scorned among the Dothraki, he grows ever more violent towards his sister. At a feast in Vaes Dothrak he draws a sword on her and her unborn child, and Drogo gives him the golden crown he wants — a pot of molten gold poured over his head (S1E6)."),
    ]),
  N(id="rhaegar", zh="雷加", en="Rhaegar", full=("雷加·坦格利安", "Rhaegar Targaryen"), house="targaryen", grp="essos",
    debut=S1E1, dies=PRE, seen=S7E7,
    camps=[(S1E1, "targaryen")],
    subs=[(S1E1, "疯王的长子，劳勃的宿敌", "The Mad King’s heir, Robert’s old enemy"), (S1E2, "夺走莱安娜的人", "The man who took Lyanna"),
          (S7E7, "莱安娜的丈夫，琼恩的父亲", "Lyanna’s husband, Jon’s father")],
    sub=("疯王的长子，琼恩的生父", "The Mad King’s heir, Jon’s father"),
    bios=[
      (S1E1, "疯王伊里斯的长子，在剧集开始前就已死去。劳勃在莱安娜墓前说，他每晚都在梦里再杀那个人一次(S1E1)。",
       "The Mad King’s eldest son, dead before the story begins. At Lyanna’s tomb Robert says he kills that man again every night in his dreams (S1E1)."),
      (S1E2, "劳勃恨他夺走了莱安娜，在三叉戟河之战中亲手杀了他(S1E2)。", "Robert hates him for taking Lyanna, and killed him with his own hand at the Trident (S1E2)."),
      (S7E7, "吉莉在旧日记里读到，他曾秘密废除与伊莉亚·马泰尔的婚姻，另娶他人(S7E5)。布兰的幻象证实，他与莱安娜在神前成婚，两人的儿子名叫伊耿(S7E7)。",
       "Gilly reads in an old diary that he secretly had his marriage to Elia Martell annulled and married again (S7E5). Bran’s vision confirms that he wed Lyanna before the gods, and that their son was named Aegon (S7E7)."),
    ]),
  N(id="aerys", zh="疯王", en="The Mad King", full=("伊里斯二世·坦格利安", "Aerys II Targaryen, the Mad King"), house="targaryen", grp="essos",
    debut=S1E2, dies=PRE, seen=S6E6,
    camps=[(S1E2, "targaryen")],
    sub=("坦格利安王朝的末代国王", "The last Targaryen king"),
    bios=[
      (S1E2, "坦格利安王朝的末代国王，已在劳勃的叛乱中死去；劳勃说，他对史塔克家犯下的罪行令人发指(S1E2)。",
       "The last Targaryen king, dead in Robert’s rebellion; Robert speaks of the unspeakable things he did to the Starks (S1E2)."),
      (S1E3, "人称“疯王”：城破之时，他被自己的御林铁卫詹姆从背后刺死，詹姆从此被称为“弑君者”(S1E3)。",
       "The Mad King: as the city fell he was stabbed in the back by his own Kingsguard, Jaime, who has been called Kingslayer ever since (S1E3)."),
      (S3E5, "詹姆向布蕾妮说出真相：疯王打算用野火把整座君临烧成灰烬，还命令詹姆去杀他自己的父亲泰温(S3E5)。",
       "Jaime tells Brienne the truth: the Mad King meant to burn all King’s Landing with wildfire, and ordered Jaime to bring him his own father’s head (S3E5)."),
      (S6E6, "布兰在幻象中看到他高喊着要烧死所有人的样子(S6E6)。", "Bran glimpses him in a vision, screaming for everyone to burn (S6E6)."),
    ]),
  # =============================================================== Essos
  N(id="drogo", zh="卓戈", en="Drogo", full=("卓戈卡奥", "Khal Drogo"), house="dothraki", grp="essos",
    debut=S1E1, dies=S1E10,
    camps=[(S1E1, "essos")],
    sub=("多斯拉克卡奥，丹妮莉丝的丈夫", "Dothraki khal, Daenerys’s husband"),
    bios=[
      (S1E1, "统率四万骑兵的多斯拉克卡奥，从未打过败仗。韦赛里斯把妹妹丹妮莉丝嫁给了他(S1E1)。",
       "A Dothraki khal with forty thousand riders, never defeated. Viserys gives him his sister Daenerys in marriage (S1E1)."),
      (S1E7, "他与丹妮莉丝渐生情意。有人在市场上行刺怀孕的丹妮莉丝，他发誓要渡过毒水，为她夺下铁王座(S1E7)。",
       "He and Daenerys come to love each other. When someone tries to poison her in the market, he swears to cross the poison water and win her the Iron Throne (S1E7)."),
      (S1E10, "他在劫掠拉札林人的村庄后与人决斗，受了轻伤(S1E8)，伤口溃烂，丹妮莉丝请弥丽用血魔法救他(S1E9)。他从此不言不动，丹妮莉丝用枕头闷死了他，为他举行火葬(S1E10)。",
       "After raiding a Lhazareen village he takes a small wound in a duel (S1E8); it festers, and Daenerys asks Mirri for blood magic to save him (S1E9). It leaves him unable to move or speak; Daenerys smothers him with a pillow and burns him on a pyre (S1E10)."),
    ]),
  N(id="jorah", zh="乔拉", en="Jorah", full=("乔拉·莫尔蒙爵士", "Ser Jorah Mormont"), house="mormont", grp="essos",
    debut=S1E1, dies=S8E3,
    camps=[(S1E1, "targaryen"), (S4E8, "none", "被丹妮莉丝放逐", "Banished by Daenerys"),
           (S7E5, "targaryen", "病愈后回到女王身边", "Cured, returns to his queen")],
    subs=[(S1E1, "流亡的北境骑士", "An exiled Northern knight"), (S4E8, "被放逐的人", "An exile"),
          (S5E5, "身染灰鳞病的人", "Stricken with greyscale"), (S7E5, "女王的骑士", "The Queen’s knight")],
    sub=("老熊之子，丹妮莉丝的骑士", "The Old Bear’s son, Daenerys’s knight"),
    bios=[
      (S1E1, "熊岛莫尔蒙家的继承人，因贩卖奴隶被艾德判罪，逃亡厄索斯。他投到韦赛里斯兄妹身边，在婚礼上送给丹妮莉丝一套维斯特洛史书(S1E1)。",
       "Heir to Bear Island, who fled to Essos when Ned condemned him for selling slaves. He attaches himself to Viserys and Daenerys, and gives her books of Westerosi history as a wedding gift (S1E1)."),
      (S1E7, "他其实在为瓦里斯通风报信，想换取劳勃的赦免；可他渐渐爱上了丹妮莉丝，在市场上识破了毒酒(S1E7)。",
       "He is secretly informing on her to Varys in hope of a royal pardon — but he has come to love her, and stops the poisoned wine in the market (S1E7)."),
      (S4E8, "劳勃当年给他的赦免令被巴利斯坦交到丹妮莉丝手里，他的告密败露，被逐出弥林(S4E8)。",
       "Barristan brings Daenerys the royal pardon Robert once granted him; his spying exposed, he is banished from Meereen (S4E8)."),
      (S5E10, "他劫持提利昂献给女王(S5E3)，途中被石民抓伤，染上灰鳞病(S5E5)；他在竞技场上救了丹妮莉丝(S5E9)。",
       "He kidnaps Tyrion as a gift for her (S5E3), is infected with greyscale by the Stone Men on the way (S5E5), and saves Daenerys in the fighting pit (S5E9)."),
      (S6E5, "他向丹妮莉丝表白，又坦白了病情，女王命他去寻找解药(S6E5)。",
       "He tells Daenerys he loves her and shows her his disease, and she orders him to find a cure (S6E5)."),
      (S7E5, "山姆在学城冒险为他剥除病皮(S7E2)，他痊愈后(S7E3)回到女王身边(S7E5)。",
       "Sam secretly cuts away his diseased skin at the Citadel (S7E2); cured (S7E3), he returns to his queen (S7E5)."),
      (S8E3, "长夜之战中，他在丹妮莉丝身前一次次挡住尸鬼，最后死在她怀里(S8E3)。",
       "In the Long Night he holds the dead back from Daenerys again and again, and dies in her arms (S8E3)."),
    ]),
  N(id="barristan", zh="巴利斯坦", en="Barristan", full=("巴利斯坦·赛尔弥爵士", "Ser Barristan Selmy"), house="selmy", grp="essos",
    debut=S1E3, dies=S5E4,
    camps=[(S1E3, "baratheon"), (S3E1, "targaryen", "投奔丹妮莉丝", "Joins Daenerys")],
    subs=[(S1E3, "御林铁卫队长", "Lord Commander of the Kingsguard"), (S3E1, "丹妮莉丝的护卫", "Daenerys’s knight")],
    sub=("传奇骑士，劳勃的御林铁卫队长", "A legendary knight, Lord Commander of Robert’s Kingsguard"),
    bios=[
      (S1E3, "传奇骑士，劳勃的御林铁卫队长，当年也曾为坦格利安家效力(S1E3)。",
       "A legendary knight, Lord Commander of Robert’s Kingsguard, who once served the Targaryens too (S1E3)."),
      (S3E1, "劳勃死后他被解职，远赴厄索斯，在阿斯塔波救下遇刺的丹妮莉丝，向她效忠(S3E1)。",
       "Dismissed after Robert’s death, he crosses the sea, saves Daenerys from an assassin in Astapor and swears himself to her (S3E1)."),
      (S4E8, "他把劳勃当年给乔拉的赦免令交给女王，揭穿了乔拉的告密(S4E8)。",
       "He brings the queen the pardon Robert gave Jorah, exposing Jorah’s spying (S4E8)."),
      (S5E4, "他在弥林的小巷里援救遭伏击的灰虫子，与鹰身女妖之子力战而死(S5E4)。",
       "He goes to the aid of Grey Worm in an ambush in the alleys of Meereen and dies fighting the Sons of the Harpy (S5E4)."),
    ]),
  N(id="missandei", zh="弥桑黛", en="Missandei", full=("弥桑黛", "Missandei"), house="essos", grp="essos",
    debut=S3E1, dies=S8E4,
    camps=[(S3E1, "essos"), (S3E4, "targaryen", "获得自由，追随丹妮莉丝", "Freed, follows Daenerys")],
    subs=[(S3E1, "阿斯塔波奴隶主的女译者", "A slaver’s interpreter in Astapor"), (S3E4, "女王的译者与心腹", "The Queen’s interpreter and confidante")],
    sub=("纳斯岛出身的译者，丹妮莉丝的心腹", "Interpreter from Naath, Daenerys’s confidante"),
    bios=[
      (S3E4, "阿斯塔波奴隶主的女奴和翻译，通晓多种语言(S3E1)。丹妮莉丝买下无垢者时还了她自由，她选择留在女王身边(S3E4)。",
       "A slave interpreter for the slavers of Astapor, who speaks many tongues (S3E1). When Daenerys frees the Unsullied she frees Missandei too, who chooses to stay with her (S3E4)."),
      (S5E10, "她教灰虫子说通用语，两人互生情意(S4E4)。丹妮莉丝离开后，她和灰虫子、提利昂一同治理弥林(S5E10)。",
       "She teaches Grey Worm the Common Tongue and they come to care for each other (S4E4). When Daenerys is gone she governs Meereen with Grey Worm and Tyrion (S5E10)."),
      (S8E4, "她随女王西征，与灰虫子相爱(S7E2)。攸伦伏击舰队，她被俘到君临，在城头被魔山斩首，临死说出一句“龙焰”(S8E4)。",
       "She sails west with her queen and becomes Grey Worm’s lover (S7E2). Captured when Euron ambushes the fleet, she is beheaded by the Mountain on the walls of King’s Landing, her last word ‘Dracarys’ (S8E4)."),
    ]),
  N(id="greyworm", zh="灰虫子", en="Grey Worm", full=("灰虫子", "Grey Worm"), house="essos", grp="essos",
    debut=S3E4, dies=None,
    camps=[(S3E4, "targaryen")],
    sub=("无垢者统领", "Commander of the Unsullied"),
    bios=[
      (S3E5, "从小被训练成太监战士的无垢者。丹妮莉丝解放无垢者后，他们推举他为统领；他留下“灰虫子”这个名字，因为那是他获得自由那天的名字(S3E5)。",
       "One of the Unsullied, eunuch soldiers trained from childhood. Freed by Daenerys, they choose him as their commander; he keeps the name Grey Worm because it was his on the day he was freed (S3E5)."),
      (S5E4, "他在弥林遭鹰身女妖之子伏击，巴利斯坦为救他而死(S5E4)。", "Ambushed by the Sons of the Harpy in Meereen, he is saved by Barristan, who dies doing it (S5E4)."),
      (S7E3, "他与弥桑黛相爱(S7E2)，率无垢者攻下凯岩城(S7E3)。", "He and Missandei become lovers (S7E2), and he leads the Unsullied to take Casterly Rock (S7E3)."),
      (S8E6, "弥桑黛被瑟曦处死(S8E4)，他在君临屠杀投降的士兵(S8E5)；丹妮莉丝死后，他带无垢者乘船去了弥桑黛的故乡纳斯岛(S8E6)。",
       "After Cersei executes Missandei (S8E4) he slaughters surrendering soldiers in King’s Landing (S8E5); when Daenerys is dead he takes the Unsullied to Missandei’s home, Naath (S8E6)."),
    ]),
  N(id="daario", zh="达里奥", en="Daario", full=("达里奥·纳哈里斯", "Daario Naharis"), house="essos", grp="essos",
    debut=S3E8, dies=None,
    camps=[(S3E8, "targaryen")],
    sub=("次子团的佣兵队长，丹妮莉丝的情人", "Captain of the Second Sons, Daenerys’s lover"),
    bios=[
      (S3E8, "次子团的佣兵。他受命刺杀丹妮莉丝，却杀了另外两个队长，带次子团投奔女王(S3E8)。",
       "A sellsword of the Second Sons. Sent to kill Daenerys, he kills his two fellow captains instead and brings the company over to her (S3E8)."),
      (S3E9, "他与灰虫子、乔拉一起潜入渊凯，拿下了这座城(S3E9)。", "He slips into Yunkai with Grey Worm and Jorah and takes the city (S3E9)."),
      (S5E10, "他成了丹妮莉丝的情人(S4E7)。女王被卓耿带走后，他与乔拉去多斯拉克海寻找她(S5E10)。",
       "He becomes Daenerys’s lover (S4E7). When Drogon carries her away he goes with Jorah to search the Dothraki sea for her (S5E10)."),
      (S6E10, "他找回了女王(S6E4)；女王西征前，把他留在弥林维持秩序(S6E10)。",
       "He finds her again (S6E4); sailing west, she leaves him behind to keep the peace in Meereen (S6E10)."),
    ]),
  N(id="illyrio", zh="伊利里欧", en="Illyrio", full=("伊利里欧·莫帕提斯", "Illyrio Mopatis"), house="essos", grp="essos",
    debut=S1E1, dies=None,
    camps=[(S1E1, "essos")],
    sub=("潘托斯的富商总督", "A magister of Pentos"),
    bios=[
      (S1E1, "潘托斯的富商总督，收留了流亡的韦赛里斯兄妹，一手促成丹妮莉丝与卓戈的婚事，还送给她三颗龙蛋做结婚礼物(S1E1)。",
       "A magister of Pentos who shelters Viserys and Daenerys in exile, arranges her marriage to Drogo and gives her three dragon eggs as a wedding gift (S1E1)."),
      (S1E5, "艾莉亚在红堡地下偷听到他和瓦里斯密谋(S1E5)。", "Arya overhears him plotting with Varys beneath the Red Keep (S1E5)."),
    ]),
  N(id="mirri", zh="弥丽", en="Mirri", full=("弥丽·马兹·笃尔", "Mirri Maz Duur"), house="essos", grp="essos",
    debut=S1E8, dies=S1E10,
    camps=[(S1E8, "essos")],
    sub=("拉札林人的巫女", "A Lhazareen godswife"),
    bios=[
      (S1E8, "拉札林村庄的女祭司和医者。卓戈的骑兵劫掠她的村子，丹妮莉丝出面救下了她(S1E8)。",
       "A healer and priestess of a Lhazareen village. When Drogo’s riders sack it, Daenerys saves her (S1E8)."),
      (S1E10, "她给卓戈治伤，伤口却化脓溃烂；丹妮莉丝求她用血魔法救命(S1E9)。结果丹妮莉丝腹中的孩子死了，卓戈成了活死人；她说这是对屠村的报复，被丹妮莉丝绑上卓戈的火葬堆烧死(S1E10)。",
       "She treats Drogo’s wound and it festers; at Daenerys’s plea she works blood magic (S1E9). It kills Daenerys’s unborn son and leaves Drogo a husk; calling it revenge for her village, she is bound to Drogo’s pyre and burned (S1E10)."),
    ]),
  N(id="hizdahr", zh="希兹达尔", en="Hizdahr", full=("希兹达尔·佐·罗拉克", "Hizdahr zo Loraq"), house="essos", grp="essos",
    debut=S4E6, dies=S5E9,
    camps=[(S4E6, "essos"), (S5E5, "targaryen", "与丹妮莉丝订婚", "Betrothed to Daenerys")],
    sub=("弥林的旧贵族", "A Meereenese nobleman"),
    bios=[
      (S4E6, "弥林的贵族，父亲被丹妮莉丝钉死在十字架上，他请求为父亲收尸(S4E6)。",
       "A nobleman of Meereen whose father Daenerys crucified; he asks for leave to bury him (S4E6)."),
      (S5E9, "丹妮莉丝为了安抚旧贵族，答应嫁给他(S5E5)；在重开的竞技场上，鹰身女妖之子发动袭击，他被刺死(S5E9)。",
       "To win over the old nobility Daenerys agrees to marry him (S5E5); when the Sons of the Harpy attack the reopened fighting pit, he is stabbed to death (S5E9)."),
    ]),
  N(id="jaqen", zh="贾昆", en="Jaqen", full=("贾昆·赫加尔", "Jaqen H’ghar"), house="faceless", grp="essos",
    debut=S2E2, dies=None,
    camps=[(S2E2, "essos")],
    subs=[(S2E2, "押往长城的囚犯", "A prisoner bound for the Wall"), (S2E10, "无面者", "A Faceless Man")],
    sub=("无面者", "A Faceless Man"),
    bios=[
      (S2E2, "一个被锁在囚车里押往长城的犯人，说话总用“一个人”自称(S2E2)。",
       "A prisoner chained in a cart bound for the Wall, who always speaks of himself as ‘a man’ (S2E2)."),
      (S2E10, "艾莉亚从着火的囚车里救了他(S2E3)，他答应替她杀三个人(S2E5)，帮她逃出赫伦堡后，换了一张脸消失了，临走留给她一枚铁币(S2E10)。",
       "Arya saves him from the burning cart (S2E3) and he offers her three deaths (S2E5); after helping her out of Harrenhal he changes his face before her eyes and disappears, leaving her an iron coin (S2E10)."),
      (S5E2, "艾莉亚来到布拉佛斯的黑白之院，他以本来面目出现，收她为徒(S5E2)。",
       "When Arya comes to the House of Black and White in Braavos, he appears and takes her as his pupil (S5E2)."),
      (S6E8, "艾莉亚违背命令，他允许流浪儿去杀她(S6E6)；艾莉亚反杀流浪儿后，他说这个女孩终于成了无名之人，艾莉亚却说自己是艾莉亚·史塔克，离他而去(S6E8)。",
       "When Arya disobeys he gives the Waif leave to kill her (S6E6); after she kills the Waif instead he declares that a girl is finally no one — and she answers that she is Arya Stark, and leaves (S6E8)."),
    ]),
]
