# -*- coding: utf-8 -*-
"""Game of Thrones (TV): the Starks and the North, the Night's Watch, and the lands beyond the Wall.

Fields
  zh, en:  short names used on the map;  full: (zh, en) full names for the card
  house:   the house whose colours the person's seal takes (see HOUSES in data_got.py)
  grp:     roster group
  debut:   episode of first appearance (episodes are numbered 1-73; S3E9 etc. are names for them)
  dies:    episode of death, None, or PRE for people already dead when the series begins
  camps:   [(episode, camp[, zh label, en label]), ...] whose side the person is on from that episode
  subs:    [(episode, zh, en), ...] what the person is at that point of the story (spoiler-safe captions)
  sub:     a one-line summary for the whole-series view (and for everyone without `subs`)
  bios:    [(episode, zh, en), ...] the story told up to that episode; an entry is shown once the slider reaches it
  born:    birth family of a woman known by her husband's name, as (zh, en)
  seen:    for the dead-before-the-story, the first episode they are seen (in visions)
  down:    [(from, to)]: dead from `from` until brought back at `to`
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from tlhelpers import N  # noqa: E402
from episodes_got import *  # noqa: E402,F401,F403

PRE = 0

NODES_NORTH = [
  # =============================================================== the Starks
  N(id="ned", zh="艾德", en="Ned", full=("艾德·史塔克", "Eddard “Ned” Stark"), house="stark", grp="north",
    debut=S1E1, dies=S1E9, home="stark",
    camps=[(S1E1, "stark"), (S1E2, "baratheon", "出任国王之手，南下君临", "Rides south as Hand of the King"), (S1E8, "stark", "以叛国罪下狱", "Imprisoned for treason")],
    subs=[(S1E1, "临冬城公爵、北境守护", "Lord of Winterfell, Warden of the North"), (S1E2, "国王之手", "Hand of the King"),
          (S1E8, "以叛国罪下狱", "Imprisoned for treason")],
    sub=("临冬城公爵，劳勃的国王之手", "Lord of Winterfell, Robert’s Hand"),
    bios=[
      (S1E1, "北境之主，以荣誉自持。他亲手处斩了逃离长城的守夜人逃兵；劳勃国王北上临冬城，请这位老战友接替刚死去的琼恩·艾林出任国王之手。妻子的妹妹莱莎来信说琼恩·艾林是被兰尼斯特家害死的，他决定南下(S1E1)。",
       "Lord of the North and a man of rigid honour. He beheads a deserter from the Night’s Watch with his own hand. When King Robert, his old comrade, comes to Winterfell to ask him to replace the dead Jon Arryn as Hand, a letter from his wife’s sister Lysa claims the Lannisters murdered Arryn, and he agrees to go south (S1E1)."),
      (S1E7, "在君临，他顺着琼恩·艾林留下的线索找到铁匠学徒詹德利和一本贵族家谱，明白了瑟曦的三个孩子都不是劳勃亲生(S1E6)。他先警告瑟曦带孩子出逃，劳勃却在狩猎中重伤身亡；他拿出国王的遗诏，请小指头调来都城守备队，结果被小指头出卖(S1E7)。",
       "In King’s Landing he follows Jon Arryn’s trail to a smith’s apprentice, Gendry, and a book of noble lineages, and realises none of Cersei’s three children is Robert’s (S1E6). He warns Cersei to flee with them; then Robert is mortally wounded hunting, and when Ned produces the king’s will and asks Littlefinger for the City Watch, Littlefinger betrays him (S1E7)."),
      (S1E9, "为了保全女儿，他在贝勒大圣堂前公开认罪，承认乔佛里是合法国王；乔佛里却当众下令将他斩首(S1E9)。",
       "To save his daughters he confesses to treason before the Great Sept of Baelor and acknowledges Joffrey as king. Joffrey has him beheaded on the spot (S1E9)."),
      (S6E3, "多年后，布兰在幻象中看到少年时的他在临冬城练剑(S6E2)，又看到他在多恩边境的极乐塔下与拂晓神剑亚瑟·戴恩决斗(S6E3)。",
       "Years later Bran sees him as a boy in the yard at Winterfell (S6E2), and as a young man fighting Ser Arthur Dayne at the Tower of Joy (S6E3)."),
      (S6E10, "幻象揭开了他守了一辈子的秘密：琼恩不是他的私生子，而是妹妹莱安娜临终托付给他的孩子(S6E10)。",
       "The vision reveals the secret he kept all his life: Jon is not his bastard but the child his sister Lyanna entrusted to him as she died (S6E10)."),
    ]),
  N(id="catelyn", zh="凯特琳", en="Catelyn", full=("凯特琳·史塔克", "Catelyn Stark"), house="stark", grp="north",
    born=("徒利", "Tully"), debut=S1E1, dies=S3E9,
    camps=[(S1E1, "stark")],
    subs=[(S1E1, "艾德公爵的妻子", "Lord Eddard’s wife"), (S1E10, "北境之王的母亲", "Mother of the King in the North")],
    sub=("艾德之妻，罗柏的母亲", "Ned’s wife, Robb’s mother"),
    bios=[
      (S1E1, "出身河间的徒利家，嫁给艾德，生下罗柏、珊莎、艾莉亚、布兰和瑞肯。她始终容不下丈夫带回家的私生子琼恩(S1E1)。",
       "Born a Tully of Riverrun and married to Ned, she is the mother of Robb, Sansa, Arya, Bran and Rickon, and has never accepted the bastard Jon her husband brought home (S1E1)."),
      (S1E4, "布兰坠楼昏迷，她日夜守在床边，赤手挡下了来行刺布兰的刺客(S1E2)。她认定刺客的匕首属于提利昂，在路边旅店当众把他拿下(S1E4)。",
       "She keeps vigil by the unconscious Bran and fights off, barehanded, the assassin sent to kill him (S1E2). Convinced the dagger belonged to Tyrion, she arrests him in a roadside inn (S1E4)."),
      (S2E8, "她替罗柏出使，去说服蓝礼结盟，却眼看蓝礼被一个影子刺死，收下了布蕾妮的效忠(S2E5)。听说布兰和瑞肯“死了”，她私自放走詹姆，让布蕾妮押他回君临换回两个女儿(S2E8)。",
       "Sent by Robb to win Renly’s alliance, she watches a shadow kill him and takes Brienne into her service (S2E5). Believing Bran and Rickon dead, she frees Jaime on her own authority and sends him with Brienne to trade for her daughters (S2E8)."),
      (S3E9, "她陪罗柏去孪河城参加弟弟艾德慕的婚礼。宴会上乐声一变，她最先察觉卢斯·波顿袖下的锁甲；罗柏被杀后，她割断了瓦德·佛雷妻子的喉咙，随即自己也被割喉(S3E9)。",
       "She goes with Robb to the Twins for her brother Edmure’s wedding. When the music changes she is the first to notice the mail under Roose Bolton’s sleeve; after Robb is killed she cuts the throat of Walder Frey’s wife and has her own throat cut (S3E9)."),
    ]),
  N(id="robb", zh="罗柏", en="Robb", full=("罗柏·史塔克", "Robb Stark"), house="stark", grp="north",
    debut=S1E1, dies=S3E9,
    camps=[(S1E1, "stark")],
    subs=[(S1E1, "艾德的长子与继承人", "Ned’s eldest son and heir"), (S1E8, "北境大军的统帅", "Leader of the Northern host"),
          (S1E10, "北境之王", "King in the North")],
    sub=("北境之王", "The King in the North"),
    bios=[
      (S1E1, "艾德的长子与继承人。父亲南下后，他以少年之身留守临冬城，主持北境事务(S1E1)。",
       "Ned’s eldest son and heir, left in charge of Winterfell and the North when his father goes south (S1E1)."),
      (S1E10, "父亲被捕，他召集北境诸侯南下(S1E8)；为了在孪河城渡河，他答应娶瓦德·佛雷的一个女儿，随后在呓语森林俘虏了詹姆(S1E9)。父亲被斩后，北境诸侯推举他为“北境之王”(S1E10)。",
       "When his father is arrested he calls the Northern lords to war (S1E8). To cross at the Twins he promises to marry one of Walder Frey’s daughters, then captures Jaime in the Whispering Wood (S1E9). After Ned’s execution the lords proclaim him King in the North (S1E10)."),
      (S2E10, "他在战场上连战连胜，却爱上了在军中救治伤兵的泰莉莎(S2E4)，违背与佛雷家的婚约，娶了她(S2E10)。",
       "He wins every battle he fights, but falls in love with Talisa, a healer tending the wounded (S2E4), and marries her in breach of his pact with the Freys (S2E10)."),
      (S3E9, "他处死擅杀俘虏的卡史塔克伯爵，因此失去半支军队(S3E5)；为了挽回佛雷家，他让舅舅艾德慕代他娶佛雷家的女儿(S3E6)。在孪河城的婚宴上，他眼看泰莉莎被刺死，自己被卢斯·波顿一刀刺穿心口(S3E9)。",
       "He executes Lord Karstark for murdering prisoners and loses half his army (S3E5), and to win back the Freys he has his uncle Edmure marry a Frey in his place (S3E6). At the wedding feast at the Twins he watches Talisa stabbed to death and is himself stabbed through the heart by Roose Bolton (S3E9)."),
    ]),
  N(id="talisa", zh="泰莉莎", en="Talisa", full=("泰莉莎·史塔克", "Talisa Stark"), house="stark", grp="north",
    born=("梅葛", "Maegyr"), debut=S2E4, dies=S3E9,
    camps=[(S2E4, "none"), (S2E10, "stark", "嫁给罗柏", "Marries Robb")],
    subs=[(S2E4, "在战场上救治伤兵的女子", "A healer on the battlefield"), (S2E8, "瓦兰提斯的贵族女子", "A noblewoman of Volantis"), (S2E10, "罗柏的王后", "Robb’s queen")],
    sub=("罗柏的妻子", "Robb’s wife"),
    bios=[
      (S2E4, "一个在战场上救治伤兵的女子，不分敌我。罗柏第一次见她，她正在为一个兰尼斯特士兵截肢(S2E4)。",
       "A healer on the battlefield who tends the wounded of both sides; Robb first meets her as she amputates a Lannister soldier’s foot (S2E4)."),
      (S2E8, "她向罗柏讲起自己的身世：出身瓦兰提斯的贵族之家，因为厌恶那里的奴隶制，来到维斯特洛救治伤者(S2E8)。",
       "She tells Robb who she is: born to a noble family of Volantis, she left in disgust at its slavery to come and heal the wounded of Westeros (S2E8)."),
      (S2E10, "她和罗柏相爱，在一座小圣堂里秘密成婚(S2E10)。",
       "She and Robb fall in love and marry in secret (S2E10)."),
      (S3E9, "她怀上了罗柏的孩子(S3E7)，随军去孪河城赴宴，在红色婚礼上第一个遇害，腹部被连刺数刀(S3E9)。",
       "Pregnant with Robb’s child (S3E7), she goes with him to the Twins and is the first victim of the Red Wedding, stabbed repeatedly in the belly (S3E9)."),
    ]),
  N(id="sansa", zh="珊莎", en="Sansa", full=("珊莎·史塔克", "Sansa Stark"), house="stark", grp="north",
    debut=S1E1, dies=None,
    camps=[(S1E1, "stark"), (S1E8, "lannister", "父亲被捕后成为人质", "A hostage after her father’s arrest"),
           (S4E3, "arryn", "被小指头带出君临", "Spirited away by Littlefinger"),
           (S5E3, "bolton", "被许配给拉姆斯", "Promised to Ramsay"), (S5E10, "stark", "与席恩逃出临冬城", "Escapes Winterfell with Theon"),
           (S8E6, "stark", "加冕为北境女王", "Crowned Queen in the North")],
    subs=[(S1E1, "艾德的长女", "Ned’s elder daughter"), (S1E2, "乔佛里王子的未婚妻", "Betrothed to Prince Joffrey"),
          (S1E8, "君临的人质", "A hostage in King’s Landing"), (S3E8, "提利昂的妻子", "Tyrion’s wife"),
          (S4E5, "化名阿蕾妮，小指头的“外甥女”", "Disguised as Alayne, Littlefinger’s ‘niece’"),
          (S5E6, "拉姆斯·波顿的妻子", "Ramsay Bolton’s wife"), (S6E9, "临冬城夫人", "Lady of Winterfell"),
          (S8E6, "北境女王", "Queen in the North")],
    sub=("艾德的长女，后为北境女王", "Ned’s elder daughter, later Queen in the North"),
    bios=[
      (S1E1, "艾德的长女，向往南方的宫廷和骑士的故事，满心欢喜地要嫁给乔佛里王子(S1E1)。",
       "Ned’s elder daughter, dreaming of southern courts and songs of knights, delighted to be promised to Prince Joffrey (S1E1)."),
      (S1E10, "她在三叉戟河边不肯指证乔佛里，自己的冰原狼淑女因此被处死(S1E2)。父亲被捕后，她写信劝哥哥罗柏归顺，又当众求乔佛里开恩(S1E8)；乔佛里却砍了父亲的头，还逼她去看城头示众的首级(S1E10)。",
       "At the Trident she will not speak against Joffrey, and her wolf Lady is killed for it (S1E2). After her father’s arrest she writes to Robb urging him to submit and begs Joffrey publicly for mercy (S1E8); Joffrey beheads Ned and makes her look at the head on the walls (S1E10)."),
      (S2E10, "她成了君临的人质，常被乔佛里当众羞辱，提利昂几次替她解围(S2E4)；黑水河之战那夜，猎狗提出带她离开，她没有走(S2E9)。乔佛里改娶玛格丽，解除了与她的婚约(S2E10)。",
       "A hostage in King’s Landing, she is humiliated by Joffrey in public, and Tyrion steps in more than once (S2E4). On the night of the Blackwater the Hound offers to take her away; she stays (S2E9). Joffrey sets her aside to marry Margaery (S2E10)."),
      (S3E8, "提利尔家想让她嫁给洛拉斯，泰温抢先一步，逼她嫁给了提利昂(S3E8)。",
       "The Tyrells plan to marry her to Loras; Tywin forestalls them and marries her to Tyrion (S3E8)."),
      (S4E8, "乔佛里在婚宴上中毒身亡，她被小指头趁乱带出君临(S4E3)，到了鹰巢城。小指头把莱莎姨妈推下月门，她在谷地诸侯面前替他作证，开始学着在权谋中自保(S4E8)。",
       "When Joffrey is poisoned at his wedding, Littlefinger smuggles her out of King’s Landing (S4E3) to the Eyrie. After he pushes her aunt Lysa through the Moon Door she lies for him before the lords of the Vale, and begins to play the game herself (S4E8)."),
      (S5E10, "小指头把她嫁给了拉姆斯·波顿(S5E6)。新婚之夜起便受尽凌辱，最后她和席恩一起从临冬城城墙上跳下逃走(S5E10)。",
       "Littlefinger marries her to Ramsay Bolton (S5E6). Abused from her wedding night on, she escapes with Theon by leaping from the walls of Winterfell (S5E10)."),
      (S6E9, "布蕾妮救下她并向她效忠(S6E1)。她到黑城堡与琼恩重逢(S6E4)，劝他夺回临冬城；决战关头她搬来小指头的谷地骑兵扭转战局，又把拉姆斯喂了他自己的猎犬(S6E9)。",
       "Brienne rescues her and swears to serve her (S6E1). Reunited with Jon at Castle Black (S6E4), she urges him to retake Winterfell; at the decisive moment she brings Littlefinger’s knights of the Vale to turn the battle, and feeds Ramsay to his own hounds (S6E9)."),
      (S7E7, "琼恩南下期间，她替他治理北境。小指头挑拨她和艾莉亚，她却与妹妹、布兰联手，在临冬城大厅里当众审判并处死了小指头(S7E7)。",
       "She governs the North while Jon is away. Littlefinger tries to set her against Arya, but she, Arya and Bran turn the tables and have him tried and executed in the great hall of Winterfell (S7E7)."),
      (S8E6, "她始终不信任丹妮莉丝，把琼恩的身世告诉了提利昂(S8E4)。大会推举布兰为王后，她宣布北境独立，加冕为北境女王(S8E6)。",
       "Never trusting Daenerys, she tells Tyrion the secret of Jon’s birth (S8E4). When the council chooses Bran as king, she declares the North independent and is crowned Queen in the North (S8E6)."),
    ]),
  N(id="arya", zh="艾莉亚", en="Arya", full=("艾莉亚·史塔克", "Arya Stark"), house="stark", grp="north",
    debut=S1E1, dies=None, home="stark",
    camps=[(S1E1, "stark"), (S1E8, "none", "父亲被捕后逃亡", "On the run after her father’s arrest"),
           (S2E4, "lannister", "在赫伦堡给泰温当侍酒", "Tywin’s cupbearer at Harrenhal"), (S2E8, "none", "逃出赫伦堡", "Escapes Harrenhal"),
           (S3E2, "river", "落入无旗兄弟会手中", "Taken in by the Brotherhood"), (S3E7, "none", "被猎狗劫走", "Seized by the Hound"),
           (S5E2, "essos", "在布拉佛斯投入黑白之院", "Enters the House of Black and White"),
           (S6E8, "stark", "以艾莉亚·史塔克之名离开无面者", "Leaves the Faceless Men as Arya Stark")],
    subs=[(S1E1, "艾德的幼女", "Ned’s younger daughter"), (S1E8, "四处逃亡", "On the run"), (S1E10, "扮成男孩“阿利”", "Disguised as the boy ‘Arry’"),
          (S2E4, "泰温的侍酒", "Tywin’s cupbearer"), (S3E7, "猎狗的俘虏", "The Hound’s captive"),
          (S5E2, "黑白之院的学徒", "Apprentice at the House of Black and White"), (S6E8, "艾莉亚·史塔克", "Arya Stark"),
          (S8E3, "长夜之战的英雄", "Hero of the Long Night")],
    sub=("艾德的幼女，曾入无面者门下", "Ned’s younger daughter, trained by the Faceless Men"),
    bios=[
      (S1E2, "艾德的幼女，不爱针线爱刀剑，性子像姑姑莱安娜。琼恩临走送她一把细剑，她给它起名“缝衣针”(S1E2)。",
       "Ned’s younger daughter, who prefers swords to needlework and takes after her aunt Lyanna. Before he leaves, Jon gives her a slim sword; she names it Needle (S1E2)."),
      (S1E8, "到了君临，父亲请布拉佛斯剑师西里欧教她“水舞”(S1E3)。父亲被捕那天，西里欧挡住追兵让她逃走(S1E8)。",
       "In King’s Landing her father engages the Braavosi swordmaster Syrio to teach her ‘water dancing’ (S1E3). On the day of her father’s arrest Syrio holds off the guards so she can escape (S1E8)."),
      (S1E10, "父亲被押上刑台时她就在人群里，守夜人尤伦把她的脸扳开，没让她看见行刑(S1E9)。尤伦剪短她的头发，让她扮成男孩混进去长城的新兵队伍，她在路上结识了詹德利(S1E10)。",
       "She is in the crowd when her father is brought to the block; Yoren of the Night’s Watch turns her face away so she does not see (S1E9). He crops her hair and hides her, as a boy, among recruits bound for the Wall, where she meets Gendry (S1E10)."),
      (S2E10, "她被俘到赫伦堡，泰温留她做侍酒(S2E4)，看出她不是平民(S2E5)。贾昆·赫加尔欠她三条人命，替她杀人，又帮她逃走(S2E8)；临别时给了她一枚铁币，教她一句“凡人皆有一死”(S2E10)。",
       "Taken to Harrenhal, she becomes cupbearer to Tywin (S2E4), who sees she is no common girl (S2E5). Jaqen H’ghar owes her three deaths, kills for her and helps her escape (S2E8), and at parting gives her an iron coin and the words valar morghulis (S2E10)."),
      (S4E10, "她落入无旗兄弟会手中(S3E2)，又被猎狗劫走，猎狗想拿她向罗柏换赎金(S3E7)；两人赶到孪河城时，红色婚礼刚刚开始(S3E9)。她跟着猎狗一路流浪，学会了杀人，每晚念着复仇名单。布蕾妮与猎狗恶斗之后，她丢下重伤的猎狗，独自乘船去了布拉佛斯(S4E10)。",
       "She falls in with the Brotherhood without Banners (S3E2), then is carried off by the Hound, who means to ransom her to Robb (S3E7); they reach the Twins as the Red Wedding begins (S3E9). Wandering with him, she learns to kill and recites a list of names every night. After Brienne and the Hound fight, she leaves him badly wounded and sails alone for Braavos (S4E10)."),
      (S5E10, "她进了黑白之院，在贾昆门下学做“无名之人”(S5E2)。她违命私自杀了马林·特兰特爵士，被罚失明(S5E10)。",
       "She enters the House of Black and White to train under Jaqen as ‘no one’ (S5E2). Killing Ser Meryn Trant on her own account, she is punished with blindness (S5E10)."),
      (S6E10, "她重见光明(S6E3)，却不肯杀一个女演员，被流浪儿追杀；她反杀流浪儿，宣布自己是艾莉亚·史塔克(S6E8)。回到维斯特洛后，她扮成侍女割开了瓦德·佛雷的喉咙(S6E10)。",
       "She regains her sight (S6E3), but will not kill an actress and is hunted by the Waif; she kills the Waif instead and declares herself Arya Stark (S6E8). Back in Westeros she cuts Walder Frey’s throat, disguised as a serving girl (S6E10)."),
      (S7E7, "她戴着瓦德的脸毒死了佛雷家的男丁(S7E1)，回到临冬城与珊莎、布兰重逢(S7E4)，最后亲手处决了小指头(S7E7)。",
       "Wearing Walder’s face, she poisons the men of House Frey (S7E1), comes home to Winterfell and her sister and brother (S7E4), and executes Littlefinger herself (S7E7)."),
      (S8E6, "长夜之战中，她从暗处扑向夜王，一刀刺穿了他，所有异鬼和尸鬼随之崩散(S8E3)。她拒绝了詹德利的求婚(S8E4)，在君临的火海中死里逃生(S8E5)，最后扬帆驶向维斯特洛以西的未知海域(S8E6)。",
       "In the Long Night she leaps on the Night King from the dark and stabs him, and every White Walker and wight falls with him (S8E3). She turns down Gendry’s proposal (S8E4), survives the burning of King’s Landing (S8E5), and sails west into uncharted seas (S8E6)."),
    ]),
  N(id="bran", zh="布兰", en="Bran", full=("布兰·史塔克", "Bran Stark"), house="stark", grp="north",
    debut=S1E1, dies=None,
    camps=[(S1E1, "stark"), (S3E10, "beyond", "越过长城北上", "Crosses the Wall"),
           (S7E3, "stark", "回到临冬城", "Returns to Winterfell"), (S8E6, "stark", "被推举为六国之王", "Chosen King of the Six Kingdoms")],
    subs=[(S1E1, "艾德的次子，爱攀爬", "Ned’s second son, a climber"), (S1E3, "坠楼致残的孩子", "Crippled by a fall"),
          (S4E10, "三眼乌鸦的学徒", "Pupil of the Three-eyed Raven"), (S6E5, "新的三眼乌鸦", "The new Three-eyed Raven"),
          (S8E6, "六国之王“断腿布兰”", "Bran the Broken, King of the Six Kingdoms")],
    sub=("艾德的次子，后为三眼乌鸦与国王", "Ned’s second son; the Three-eyed Raven, later king"),
    bios=[
      (S1E1, "艾德的次子，最爱攀爬城墙。他在一座旧塔上撞见瑟曦和詹姆私通，被詹姆推下窗去(S1E1)。",
       "Ned’s second son, who loves to climb. On an old tower he sees Cersei and Jaime together, and Jaime pushes him out of the window (S1E1)."),
      (S2E10, "他从昏迷中醒来(S1E2)，双腿已废，记不起坠楼的事(S1E3)，开始梦见一只三眼乌鸦(S1E4)。席恩夺取临冬城后，欧莎带他和瑞肯逃出城去(S2E6)，又悄悄藏回地下墓窖(S2E8)；临冬城被焚后，他们带着阿多北上(S2E10)。",
       "He wakes from his coma (S1E2) unable to walk and remembering nothing of the fall (S1E3), and begins dreaming of a three-eyed crow (S1E4). When Theon seizes Winterfell, Osha gets him and Rickon out (S2E6) and they hide in the crypts (S2E8); after Winterfell is burned they set out north with Hodor (S2E10)."),
      (S4E10, "黎德家的玖健和梅拉找到他，告诉他自己是“易形者”(S3E2)。他让欧莎带瑞肯南去(S3E9)，自己越过长城(S3E10)，在卡斯特堡落入叛变的守夜人手中，脱身后终于找到住在鱼梁木根下的三眼乌鸦(S4E10)。",
       "Jojen and Meera Reed find him and tell him he is a warg (S3E2). He sends Rickon south with Osha (S3E9) and crosses the Wall (S3E10), escapes the mutineers at Craster’s Keep, and at last reaches the Three-eyed Raven in the roots of a weirwood (S4E10)."),
      (S6E10, "三眼乌鸦带他在幻象中回到过去，看到少年时的父亲(S6E2)、极乐塔(S6E3)和阿多的来历。他擅自去看亡者大军，被夜王抓住手腕留下印记；异鬼攻进洞穴，三眼乌鸦和阿多为他而死，他接过了三眼乌鸦的衣钵(S6E5)。幻象最终告诉他：琼恩的生母是莱安娜(S6E10)。",
       "The Raven takes him back in visions to his father’s boyhood (S6E2), to the Tower of Joy (S6E3) and to the making of Hodor. Spying on the army of the dead alone, he is seized and marked by the Night King; the dead overrun the cave, the Raven and Hodor die for him, and he becomes the Three-eyed Raven himself (S6E5). His visions show him at last that Jon’s mother was Lyanna (S6E10)."),
      (S7E7, "他回到临冬城，却已不像从前的布兰(S7E3)。他把小指头送的匕首交给艾莉亚(S7E4)，又和山姆一起确认：琼恩是雷加与莱安娜的合法儿子，本名伊耿·坦格利安(S7E7)。",
       "He comes home to Winterfell, no longer quite the boy who left (S7E3). He gives Arya the dagger Littlefinger gave him (S7E4) and, with Sam, confirms that Jon is the legitimate son of Rhaegar and Lyanna — Aegon Targaryen (S7E7)."),
      (S8E6, "长夜之战中，他以自己为饵，在神木林里等待夜王(S8E3)。战争结束后，提利昂提议由他为王，大会推举“断腿布兰”为六国之王(S8E6)。",
       "In the Long Night he waits in the godswood as bait for the Night King (S8E3). Afterwards, on Tyrion’s proposal, the council chooses ‘Bran the Broken’ as King of the Six Kingdoms (S8E6)."),
    ]),
  N(id="rickon", zh="瑞肯", en="Rickon", full=("瑞肯·史塔克", "Rickon Stark"), house="stark", grp="north",
    debut=S1E1, dies=S6E9,
    camps=[(S1E1, "stark"), (S6E3, "bolton", "被安柏家交给拉姆斯", "Handed to Ramsay by the Umbers")],
    subs=[(S1E1, "艾德的幼子", "Ned’s youngest son"), (S6E3, "拉姆斯的人质", "Ramsay’s hostage")],
    sub=("艾德的幼子", "Ned’s youngest son"),
    bios=[
      (S1E1, "艾德最小的儿子，还是个孩子(S1E1)。", "Ned’s youngest son, still a small child (S1E1)."),
      (S3E9, "临冬城失陷后，他跟着布兰一路逃亡(S2E10)；布兰决意越过长城，让欧莎带他去投奔安柏家(S3E9)。",
       "He flees Winterfell with Bran (S2E10); resolved to go beyond the Wall, Bran sends him with Osha to the Umbers (S3E9)."),
      (S6E9, "小琼恩·安柏把他和欧莎交给拉姆斯当见面礼(S6E3)。私生子之战开场，拉姆斯让他在两军之间奔跑，就在琼恩够到他之前一箭射死了他(S6E9)。",
       "Smalljon Umber hands him and Osha to Ramsay as a token (S6E3). At the start of the Battle of the Bastards Ramsay makes him run between the armies and shoots him dead just before Jon can reach him (S6E9)."),
    ]),
  N(id="jon", zh="琼恩", en="Jon", full=("琼恩·雪诺", "Jon Snow"), house="stark", grp="north",
    debut=S1E1, dies=None, down=[(S5E10, S6E2)],
    camps=[(S1E1, "stark"), (S1E3, "nw", "加入守夜人", "Joins the Night’s Watch"),
           (S2E10, "beyond", "奉命假意投奔野人", "Goes over to the wildlings, on orders"),
           (S3E10, "nw", "逃回黑城堡", "Back at Castle Black"), (S6E3, "stark", "离开守夜人", "Leaves the Watch"),
           (S6E10, "stark", "被拥立为北境之王", "Proclaimed King in the North"),
           (S7E6, "targaryen", "答应向丹妮莉丝屈膝", "Pledges to bend the knee to Daenerys"),
           (S8E6, "beyond", "流放长城，随野人北去", "Exiled to the Wall, goes north with the Free Folk")],
    subs=[(S1E1, "艾德的私生子", "Ned’s bastard son"), (S1E3, "守夜人新兵", "Recruit of the Night’s Watch"),
          (S1E7, "总司令的侍从", "Steward to the Lord Commander"), (S2E10, "混入野人中的守夜人", "A crow among the wildlings"),
          (S3E10, "守夜人", "Brother of the Night’s Watch"), (S5E2, "守夜人总司令", "Lord Commander of the Night’s Watch"),
          (S6E3, "离开守夜人的琼恩·雪诺", "Jon Snow, free of his vows"), (S6E10, "北境之王", "King in the North"),
          (S7E7, "伊耿·坦格利安", "Aegon Targaryen"), (S8E6, "流放长城以北", "Exiled beyond the Wall")],
    sub=("艾德的“私生子”，实为雷加与莱安娜之子", "Ned’s ‘bastard’, in truth the son of Rhaegar and Lyanna"),
    bios=[
      (S1E1, "临冬城公爵艾德的私生子，与兄弟姐妹一同长大，却总被凯特琳冷眼相待。雪地里找到冰原狼幼崽时，他替每个史塔克孩子讨下一只，自己留下了那只白色的“白灵”(S1E1)。",
       "Lord Eddard’s bastard son, raised with his half-siblings under Catelyn’s cold eye. When the direwolf pups are found he claims one for each Stark child, and the white runt, Ghost, for himself (S1E1)."),
      (S1E10, "他随叔叔班扬北上加入守夜人(S1E2)，在黑城堡与山姆成为朋友(S1E4)，在心树前立誓后被派去做总司令的侍从(S1E7)。他从尸鬼手中救下老熊(S1E8)，得到瓦雷利亚钢剑“长爪”(S1E9)。父亲被斩后他想逃去帮罗柏，被朋友们追了回来(S1E10)。",
       "He goes north with his uncle Benjen to join the Night’s Watch (S1E2), befriends Sam at Castle Black (S1E4), takes his vows before a heart tree and is made the Lord Commander’s steward (S1E7). He saves the Old Bear from a wight (S1E8) and is given the Valyrian sword Longclaw (S1E9). When his father is executed he tries to desert to join Robb, but his friends bring him back (S1E10)."),
      (S3E10, "在塞外，他俘虏了野人姑娘耶哥蕊特却下不了手(S2E6)；奉断掌科林之命，他杀了科林，假装投奔曼斯·雷德(S2E10)。他和耶哥蕊特相爱(S3E5)，随野人翻过长城，最后不肯滥杀无辜，逃了出来(S3E9)，赶回黑城堡报信时被耶哥蕊特射了三箭(S3E10)。",
       "Beyond the Wall he captures the wildling Ygritte and cannot bring himself to kill her (S2E6). At Qhorin Halfhand’s order he kills Qhorin and goes over to Mance Rayder (S2E10). He and Ygritte become lovers (S3E5); he climbs the Wall with the wildlings, refuses to kill an innocent and escapes (S3E9), and takes three of Ygritte’s arrows on his way to warn Castle Black (S3E10)."),
      (S4E10, "他带人突袭卡斯特堡，铲除叛徒(S4E5)。野人攻打黑城堡，他指挥守城，耶哥蕊特死在他怀里(S4E9)；他孤身出城与曼斯谈判，恰逢史坦尼斯大军赶到(S4E10)。",
       "He leads a raid on Craster’s Keep to wipe out the mutineers (S4E5). When the wildlings storm Castle Black he leads the defence, and Ygritte dies in his arms (S4E9). He goes alone to parley with Mance just as Stannis’s army arrives (S4E10)."),
      (S5E10, "他当选守夜人总司令(S5E2)，力排众议放野人过长城，在艰难屯亲眼看见夜王唤起死者(S5E8)。回到黑城堡后，索恩和奥利等人以“为了守夜人”之名把他刺死(S5E10)。",
       "Elected Lord Commander (S5E2), he insists on letting the wildlings through the Wall, and at Hardhome sees the Night King raise the dead (S5E8). Back at Castle Black, Thorne, Olly and others stab him to death ‘for the Watch’ (S5E10)."),
      (S6E10, "梅丽珊卓让他复活(S6E2)。他吊死了叛徒，离开守夜人(S6E3)，与珊莎重逢(S6E4)；私生子之战中他险些被己方人潮压死，靠谷地骑兵才转败为胜(S6E9)。北境诸侯拥立他为北境之王(S6E10)。",
       "Melisandre brings him back to life (S6E2). He hangs the traitors and leaves the Watch (S6E3), is reunited with Sansa (S6E4), and nearly suffocates in the crush at the Battle of the Bastards before the knights of the Vale win it for him (S6E9). The Northern lords proclaim him King in the North (S6E10)."),
      (S7E7, "他南下龙石岛求见丹妮莉丝，请她给龙晶、共抗异鬼(S7E3)；为了说服瑟曦，他带人到长城以北捉尸鬼，被丹妮莉丝乘龙救回，答应向她屈膝(S7E6)。两人在北上的船上相爱，而布兰和山姆这时发现：他是雷加与莱安娜的合法儿子(S7E7)。",
       "He sails to Dragonstone to ask Daenerys for dragonglass and help against the dead (S7E3). To convince Cersei he leads a hunt for a wight beyond the Wall, is saved by Daenerys on her dragons, and pledges to bend the knee (S7E6). They become lovers on the voyage north — while Bran and Sam learn he is the legitimate son of Rhaegar and Lyanna (S7E7)."),
      (S8E6, "山姆把身世告诉了他(S8E1)，他又告诉了丹妮莉丝(S8E2)。丹妮莉丝焚烧君临后，他在王座厅里刺死了她；他被判回守夜人，最后与托蒙德和野人们一起向长城以北走去(S8E6)。",
       "Sam tells him the truth of his birth (S8E1) and he tells Daenerys (S8E2). After she burns King’s Landing he stabs her to death in the throne room; sentenced to the Night’s Watch, he rides north beyond the Wall with Tormund and the Free Folk (S8E6)."),
    ]),
  N(id="benjen", zh="班扬", en="Benjen", full=("班扬·史塔克", "Benjen Stark"), house="stark", grp="north",
    debut=S1E1, dies=S7E6,
    camps=[(S1E1, "nw"), (S6E6, "beyond", "半死之身，守护布兰", "Half-dead, watching over Bran")],
    subs=[(S1E1, "艾德之弟，守夜人首席游骑兵", "Ned’s brother, First Ranger of the Watch"), (S1E7, "在长城以北失踪", "Missing beyond the Wall"),
          (S6E6, "半生半死的游骑兵", "A ranger neither living nor dead")],
    sub=("艾德之弟，守夜人首席游骑兵", "Ned’s brother, First Ranger of the Watch"),
    bios=[
      (S1E1, "艾德的弟弟，守夜人首席游骑兵(S1E1)。", "Ned’s younger brother and First Ranger of the Night’s Watch (S1E1)."),
      (S1E7, "他带琼恩北上长城(S1E2)，不久出塞巡逻(S1E3)，后来他的马独自跑了回来，人却杳无音讯(S1E7)。",
       "He brings Jon to the Wall (S1E2) and rides out on patrol (S1E3); later his horse comes back without him (S1E7)."),
      (S6E6, "多年后他突然出现，从尸鬼手中救下布兰和梅拉：他曾被异鬼刺伤，森林之子用龙晶阻止他变成尸鬼，从此半死半生(S6E6)。",
       "Years later he reappears to save Bran and Meera from the dead: stabbed by a White Walker, he was kept from turning by the Children of the Forest and lives on, half-dead (S6E6)."),
      (S7E6, "他在冰湖边又救了琼恩，把自己的马让给他，独自留下挡住尸鬼(S7E6)。",
       "At the frozen lake he saves Jon too, gives him his horse and stays behind to hold off the dead (S7E6)."),
    ]),
  N(id="lyanna", zh="莱安娜", en="Lyanna", full=("莱安娜·史塔克", "Lyanna Stark"), house="stark", grp="north",
    debut=S1E1, dies=PRE, seen=S6E2,
    camps=[(S1E1, "stark")],
    subs=[(S1E1, "艾德的妹妹，劳勃的未婚妻", "Ned’s sister, Robert’s betrothed"), (S6E10, "琼恩的生母", "Jon’s mother"),
          (S7E7, "雷加的妻子、琼恩的生母", "Rhaegar’s wife, Jon’s mother")],
    sub=("艾德的妹妹，琼恩的生母", "Ned’s sister, Jon’s mother"),
    bios=[
      (S1E1, "艾德的妹妹，早已去世，葬在临冬城的墓窖里。她曾与劳勃订婚，劳勃至今对她念念不忘(S1E1)。",
       "Ned’s sister, long dead and buried in the crypts of Winterfell. She was betrothed to Robert, who has never stopped mourning her (S1E1)."),
      (S1E2, "劳勃认定是雷加·坦格利安夺走了她，为此起兵推翻了坦格利安王朝(S1E2)。",
       "Robert holds that Rhaegar Targaryen took her from him — the cause of the rebellion that overthrew the Targaryens (S1E2)."),
      (S6E10, "布兰在幻象中看到少女时代的她(S6E2)。在多恩边境的极乐塔里，她产后垂危，求哥哥艾德保护她刚生下的孩子——那就是琼恩(S6E10)。",
       "Bran sees her as a girl in a vision (S6E2). In the Tower of Joy, dying after childbirth, she begs her brother Ned to protect her newborn son — Jon (S6E10)."),
      (S7E7, "雷加并没有掳走她：两人两情相悦，雷加废除了先前的婚姻，与她秘密成婚(S7E7)。",
       "Rhaegar had not abducted her: they loved each other, and he had his first marriage annulled to marry her in secret (S7E7)."),
    ]),
  # =============================================================== Winterfell's household
  N(id="luwin", zh="鲁温学士", en="Maester Luwin", full=("鲁温学士", "Maester Luwin"), house="maester", grp="north",
    debut=S1E1, dies=S2E10,
    camps=[(S1E1, "stark")],
    sub=("临冬城的学士", "Maester of Winterfell"),
    bios=[
      (S1E1, "临冬城的学士，史塔克家孩子们的老师和顾问(S1E1)。", "Maester of Winterfell, tutor and counsellor to the Stark children (S1E1)."),
      (S2E10, "罗柏南征后，他辅佐年幼的布兰主持临冬城。席恩夺城后，他劝席恩放弃无望的死守；铁种倒戈打晕席恩时，戴贡刺伤了他，他求欧莎给他一个痛快(S2E10)。",
       "With Robb at war he helps young Bran govern Winterfell. When Theon takes the castle he urges him to give up a hopeless stand; when the ironborn turn on Theon, Dagmer stabs Luwin, and he asks Osha to end his pain (S2E10)."),
    ]),
  N(id="hodor", zh="阿多", en="Hodor", full=("阿多", "Hodor"), house="smallfolk", grp="north",
    debut=S1E1, dies=S6E5,
    camps=[(S1E1, "stark")],
    sub=("临冬城的马夫，只会说“阿多”", "Winterfell’s stable hand, who only ever says ‘Hodor’"),
    bios=[
      (S1E1, "临冬城的马夫，身材魁梧，心地单纯，只会说“阿多”两个字(S1E1)。", "Winterfell’s gentle giant of a stable hand, who says only ‘Hodor’ (S1E1)."),
      (S1E4, "布兰残废后，阿多背着他走来走去，成了他的腿(S1E4)。", "After Bran is crippled, Hodor carries him everywhere and becomes his legs (S1E4)."),
      (S6E5, "布兰在幻象中看到，阿多年轻时本名威利斯，能说会道。异鬼攻进洞穴时，梅拉喊着让阿多“顶住门”；布兰的意识此时闯进年轻的威利斯，他倒地抽搐，把这句话喊了一遍又一遍，最后只剩“阿多”。阿多用身体堵住洞门，被尸鬼撕碎(S6E5)。",
       "In Bran’s visions he was once a boy called Wylis, who could talk like anyone. As the dead break into the cave Meera cries ‘Hold the door!’, and Bran, reaching into the past, sends the young Wylis into a fit repeating the words until they blur into ‘Hodor’. Hodor holds the door with his body and is torn apart (S6E5)."),
    ]),
  N(id="osha", zh="欧莎", en="Osha", full=("欧莎", "Osha"), house="beyond", grp="north",
    debut=S1E6, dies=S6E4,
    camps=[(S1E6, "beyond"), (S1E7, "stark", "被俘后留在临冬城", "Captured, made to serve Winterfell"),
           (S6E3, "bolton", "与瑞肯被交给拉姆斯", "Handed to Ramsay with Rickon")],
    sub=("被俘的野人女子，后护送瑞肯", "A captured wildling who becomes Rickon’s protector"),
    bios=[
      (S1E6, "越过长城南下的野人，在狼林里袭击布兰，被罗柏和席恩擒住，留在临冬城做仆役(S1E6)。",
       "A wildling who has come south of the Wall; she attacks Bran in the wolfswood and is taken by Robb and Theon to serve at Winterfell (S1E6)."),
      (S2E10, "席恩夺城后，她引诱席恩，趁机带布兰、瑞肯和阿多逃出城去(S2E6)，又藏回墓窖(S2E8)，又亲手结束了重伤的鲁温学士的痛苦(S2E10)。",
       "When Theon takes Winterfell she seduces him and slips away with Bran, Rickon and Hodor (S2E6), hiding in the crypts (S2E8), and later ends the dying Maester Luwin’s pain (S2E10)."),
      (S6E4, "她带瑞肯投奔安柏家(S3E9)，却被小琼恩·安柏一起交给拉姆斯(S6E3)。她想用刀刺拉姆斯，被他识破刺死(S6E4)。",
       "She takes Rickon to the Umbers (S3E9), only to be handed to Ramsay with him by Smalljon Umber (S6E3). She tries to stab Ramsay and is killed (S6E4)."),
    ]),
  N(id="meera", zh="梅拉", en="Meera", full=("梅拉·黎德", "Meera Reed"), house="reed", grp="north",
    debut=S3E2, dies=None,
    camps=[(S3E2, "stark"), (S3E10, "beyond", "随布兰越过长城", "Crosses the Wall with Bran"),
           (S7E3, "stark", "护送布兰回到临冬城", "Brings Bran home")],
    sub=("黎德家的女儿，布兰的护卫", "Daughter of House Reed, Bran’s protector"),
    bios=[
      (S3E2, "颈泽黎德家的女儿，与弟弟玖健一同找到布兰，一路用长矛和猎刀保护他(S3E2)。",
       "Daughter of the Reeds of the Neck; she and her brother Jojen find Bran and guard him with spear and knife (S3E2)."),
      (S6E6, "弟弟死后(S4E10)，她在洞穴里陪布兰修行。异鬼来袭时，她拖着布兰的雪橇逃出(S6E5)，被班扬救下(S6E6)。",
       "After her brother’s death (S4E10) she stays with Bran in the cave; when the dead attack she drags his sledge to safety (S6E5) until Benjen rescues them (S6E6)."),
      (S7E4, "她把布兰送回临冬城，布兰却说自己已不再是从前那个男孩，她伤心地告别回乡(S7E4)。",
       "She brings Bran home to Winterfell and, told he is no longer the boy she knew, sadly takes her leave (S7E4)."),
    ]),
  N(id="jojen", zh="玖健", en="Jojen", full=("玖健·黎德", "Jojen Reed"), house="reed", grp="north",
    debut=S3E2, dies=S4E10,
    camps=[(S3E2, "stark"), (S3E10, "beyond", "随布兰越过长城", "Crosses the Wall with Bran")],
    sub=("黎德家之子，能做绿色之梦", "Son of House Reed, who dreams true"),
    bios=[
      (S3E2, "颈泽黎德家的儿子，能做预知未来的“绿色之梦”。他找到布兰，教他认识自己易形者的天赋，领他去寻找三眼乌鸦(S3E2)。",
       "Son of the Reeds of the Neck, who has ‘green dreams’ that come true. He finds Bran, teaches him what it means to be a warg, and leads him to look for the Three-eyed Raven (S3E2)."),
      (S4E10, "就在鱼梁木已经在望的时候，骷髅尸鬼从雪下钻出刺中了他，姐姐梅拉只得亲手结束他的生命(S4E10)。",
       "Within sight of the weirwood the dead burst from the snow and stab him, and his sister Meera has to end his life (S4E10)."),
    ]),
  # =============================================================== Northern lords
  N(id="roose", zh="卢斯", en="Roose", full=("卢斯·波顿", "Roose Bolton"), house="bolton", grp="north",
    debut=S2E4, dies=S6E2,
    camps=[(S2E4, "stark"), (S3E9, "bolton", "在红色婚礼上背叛罗柏", "Betrays Robb at the Red Wedding")],
    subs=[(S2E4, "恐怖堡伯爵，罗柏的封臣", "Lord of the Dreadfort, Robb’s bannerman"), (S3E10, "北境守护", "Warden of the North")],
    sub=("恐怖堡伯爵，红色婚礼的主谋之一", "Lord of the Dreadfort, one of the plotters of the Red Wedding"),
    bios=[
      (S2E4, "恐怖堡伯爵，北境诸侯中最阴冷的一位，在罗柏麾下作战，主张剥俘虏的皮(S2E4)。",
       "Lord of the Dreadfort, the coldest of the Northern lords, fighting for Robb; he suggests flaying the prisoners (S2E4)."),
      (S3E9, "他暗中与泰温和瓦德·佛雷勾结，在孪河城的婚宴上亲手刺死罗柏，说是代兰尼斯特家向他问好(S3E9)；事后被泰温封为北境守护。",
       "Secretly in league with Tywin and Walder Frey, he stabs Robb at the wedding feast with the Lannisters’ regards (S3E9), and is made Warden of the North."),
      (S6E2, "他承认私生子拉姆斯为合法继承人(S4E8)，却在妻子生下儿子之后被拉姆斯刺死(S6E2)。",
       "He legitimises his bastard Ramsay (S4E8), but when his wife bears him a son, Ramsay stabs him to death (S6E2)."),
    ]),
  N(id="ramsay", zh="拉姆斯", en="Ramsay", full=("拉姆斯·波顿", "Ramsay Bolton"), house="bolton", grp="north",
    debut=S3E2, dies=S6E9,
    camps=[(S3E2, "bolton")],
    subs=[(S3E2, "自称来救席恩的年轻人", "A young man who offers to help Theon"), (S3E10, "卢斯的私生子拉姆斯·雪诺", "Ramsay Snow, Roose’s bastard"),
          (S4E8, "拉姆斯·波顿", "Ramsay Bolton"), (S6E2, "恐怖堡伯爵", "Lord of the Dreadfort")],
    sub=("卢斯的私生子，以虐人为乐", "Roose’s bastard, a sadist"),
    bios=[
      (S3E2, "一个不肯说出名字的年轻人，自称受雅拉之托来救被囚的席恩(S3E2)。",
       "A young man who will not give his name, claiming Yara has sent him to rescue the captive Theon (S3E2)."),
      (S3E10, "他假装放席恩逃走，又把他抓回去百般折磨，阉了他(S3E7)，最后才露出身份：他是卢斯·波顿的私生子(S3E10)。",
       "He pretends to free Theon, then drags him back to be tortured and castrated (S3E7), revealing at last that he is Roose Bolton’s bastard (S3E10)."),
      (S4E8, "他把席恩折磨成唯命是从的“臭佬”，借他骗开了卡林湾，因此被父亲承认为波顿家的合法儿子(S4E8)。",
       "He breaks Theon into the cringing ‘Reek’ and uses him to take Moat Cailin, and is legitimised as a Bolton for it (S4E8)."),
      (S5E10, "他娶了珊莎，在新婚之夜强暴了她(S5E6)；又带二十人夜袭，烧了史坦尼斯的粮草(S5E9)，大败史坦尼斯(S5E10)。",
       "He marries Sansa and rapes her on their wedding night (S5E6), burns Stannis’s supplies with twenty men (S5E9) and routs his army (S5E10)."),
      (S6E9, "他刺死父亲，把继母和刚出生的弟弟喂了猎犬(S6E2)，又杀了欧莎(S6E4)。私生子之战中他射死瑞肯，兵败后被琼恩打得不成人形，珊莎放出他饿了七天的猎犬(S6E9)。",
       "He murders his father and feeds his stepmother and newborn brother to his hounds (S6E2), and kills Osha (S6E4). At the Battle of the Bastards he shoots Rickon; defeated and beaten bloody by Jon, he is given by Sansa to his own starving hounds (S6E9)."),
    ]),
  N(id="lyannamo", zh="莱安娜·莫尔蒙", en="Lyanna Mormont", full=("莱安娜·莫尔蒙", "Lyanna Mormont"), house="mormont", grp="north",
    debut=S6E7, dies=S8E3,
    camps=[(S6E7, "stark")],
    sub=("熊岛的少女领主", "The young Lady of Bear Island"),
    bios=[
      (S6E7, "熊岛莫尔蒙家年仅十岁的女领主。琼恩和珊莎上门求援，她当面质问，最后派出六十二名士兵(S6E7)。",
       "The ten-year-old Lady of Bear Island. When Jon and Sansa come asking for men she questions them sharply, then gives them sixty-two (S6E7)."),
      (S6E10, "她在临冬城大厅里痛斥没有出兵的诸侯，带头拥立琼恩为北境之王(S6E10)。",
       "In the hall at Winterfell she shames the lords who did not fight and leads the call to make Jon King in the North (S6E10)."),
      (S8E3, "长夜之战中，她被巨人尸鬼抓起捏碎，临死前一刀刺进巨人的眼睛，与它同归于尽(S8E3)。",
       "In the Long Night a dead giant crushes her in its fist; dying, she drives her dagger into its eye and takes it with her (S8E3)."),
    ]),
  # =============================================================== the Night's Watch
  N(id="jeor", zh="老熊", en="Jeor Mormont", full=("杰奥·莫尔蒙", "Jeor Mormont, the Old Bear"), house="mormont", grp="wall",
    debut=S1E3, dies=S3E4,
    camps=[(S1E3, "nw")],
    sub=("守夜人总司令，人称“老熊”", "Lord Commander of the Night’s Watch, the ‘Old Bear’"),
    bios=[
      (S1E3, "守夜人总司令，人称“老熊”，治军严厉而通情理(S1E3)。", "Lord Commander of the Night’s Watch, the ‘Old Bear’, stern but fair (S1E3)."),
      (S1E9, "他看重琼恩，让他做自己的侍从(S1E7)；琼恩从尸鬼手中救了他的命(S1E8)，他把家传的瓦雷利亚钢剑“长爪”送给琼恩——这把剑本该传给他那因贩奴而逃亡的儿子乔拉(S1E9)。",
       "He takes Jon as his steward (S1E7), and when Jon saves him from a wight (S1E8) he gives him the family’s Valyrian sword, Longclaw — the sword that should have gone to his disgraced son Jorah (S1E9)."),
      (S2E10, "他率大队人马出塞，查探野人和异鬼的动静(S2E1)，在先民拳峰遭到异鬼大军袭击(S2E10)。",
       "He leads a great ranging north to learn what the wildlings and the White Walkers are doing (S2E1), and is attacked by the army of the dead at the Fist of the First Men (S2E10)."),
      (S3E4, "他带残部退到卡斯特堡，饥饿的弟兄们发动叛乱，叛变者拉斯特从背后刺死了他(S3E4)。",
       "Retreating with the survivors to Craster’s Keep, he is stabbed in the back by the mutineer Rast (S3E4)."),
    ]),
  N(id="aemon", zh="伊蒙学士", en="Maester Aemon", full=("伊蒙学士", "Maester Aemon"), house="nw", grp="wall",
    debut=S1E3, dies=S5E7,
    camps=[(S1E3, "nw")],
    subs=[(S1E3, "黑城堡的盲眼老学士", "The blind old maester of Castle Black"), (S1E9, "伊蒙·坦格利安", "Aemon Targaryen")],
    sub=("黑城堡的学士，伊蒙·坦格利安", "Maester of Castle Black, Aemon Targaryen"),
    bios=[
      (S1E3, "黑城堡的盲眼学士，年过百岁，是守夜人的智囊(S1E3)。",
       "The blind maester of Castle Black, more than a hundred years old, the Watch’s wisest counsellor (S1E3)."),
      (S1E9, "琼恩想去追随罗柏，他劝琼恩守誓，并说出自己的身世：他是伊蒙·坦格利安，当年放弃王位来到长城，家族覆灭时也没有离开(S1E9)。",
       "When Jon wants to join Robb he counsels him to keep his vows, and reveals that he is Aemon Targaryen, who gave up a throne for the Wall and stayed even as his family was destroyed (S1E9)."),
      (S5E2, "总司令选举中，他投下决定性的一票，琼恩当选(S5E2)。", "His deciding vote makes Jon Lord Commander (S5E2)."),
      (S5E5, "山姆给他读来自奴隶湾的消息，他叹息丹妮莉丝孤身在远方，自己却老得无法帮她(S5E5)。",
       "When Sam reads him the news from Slaver’s Bay he grieves that Daenerys is alone so far away, and he too old to help her (S5E5)."),
      (S5E7, "临终时他神志恍惚，以为弟弟伊耿还在身边，安然离世(S5E7)。", "He dies peacefully, wandering in mind and thinking his long-dead brother Aegon is beside him (S5E7)."),
    ]),
  N(id="alliser", zh="索恩", en="Thorne", full=("艾里沙·索恩爵士", "Ser Alliser Thorne"), house="nw", grp="wall",
    debut=S1E3, dies=S6E3,
    camps=[(S1E3, "nw")],
    sub=("黑城堡的教头，处处与琼恩为敌", "Master-at-arms at Castle Black, Jon’s enemy"),
    bios=[
      (S1E3, "黑城堡的教头，曾为坦格利安家作战，看不起贵族出身的新兵，尤其厌恶琼恩(S1E3)。",
       "Castle Black’s master-at-arms, who fought for the Targaryens and despises highborn recruits, Jon above all (S1E3)."),
      (S4E9, "老熊死后，他代理总司令，在野人攻城时身先士卒，负了重伤(S4E9)。",
       "Acting Lord Commander after the Old Bear’s death, he fights at the front when the wildlings attack and is badly wounded (S4E9)."),
      (S5E10, "他在总司令选举中败给琼恩(S5E2)，不满琼恩放野人过长城，带人以“为了守夜人”之名刺死了琼恩(S5E10)。",
       "He loses the election for Lord Commander to Jon (S5E2) and, enraged that Jon lets the wildlings through the Wall, leads the men who stab him ‘for the Watch’ (S5E10)."),
      (S6E3, "琼恩复活后，以叛变之罪亲手把他吊死(S6E3)。", "Brought back to life, Jon hangs him for mutiny (S6E3)."),
    ]),
  N(id="edd", zh="艾迪", en="Edd", full=("艾迪·托勒特", "Eddison “Dolorous Edd” Tollett"), house="nw", grp="wall",
    debut=S2E1, dies=S8E3,
    camps=[(S2E1, "nw")],
    subs=[(S2E1, "守夜人，“忧郁的艾迪”", "‘Dolorous Edd’ of the Watch"), (S6E3, "守夜人代理总司令", "Acting Lord Commander")],
    sub=("守夜人，琼恩忠实的兄弟", "Jon’s loyal brother of the Watch"),
    bios=[
      (S3E1, "守夜人里一个满腹牢骚却极可靠的弟兄。他随老熊出塞，在先民拳峰死里逃生(S3E1)。",
       "A gloomy but utterly reliable brother of the Watch. He goes north with the Old Bear and survives the Fist of the First Men (S3E1)."),
      (S6E3, "他随琼恩去艰难屯接野人(S5E8)；琼恩被刺后，他和戴佛斯守护遗体(S6E1)。琼恩复活后离开守夜人，把黑城堡交给了他(S6E3)。",
       "He goes with Jon to Hardhome (S5E8) and, after Jon’s murder, guards the body with Davos (S6E1). When Jon rises and leaves the Watch he hands Edd command of Castle Black (S6E3)."),
      (S8E3, "长夜之战中，他为救山姆被尸鬼从背后刺死(S8E3)。",
       "In the Long Night he is stabbed in the back by a wight while saving Sam (S8E3)."),
    ]),
  N(id="olly", zh="奥利", en="Olly", full=("奥利", "Olly"), house="nw", grp="wall",
    debut=S4E3, dies=S6E3,
    camps=[(S4E3, "nw")],
    sub=("父母死于野人之手的少年，后为琼恩的侍从", "A boy orphaned by wildlings, later Jon’s steward"),
    bios=[
      (S4E3, "他的村庄被野人和瑟恩人血洗，父母被杀，他逃到黑城堡报信，留下来当了守夜人(S4E3)。",
       "His village is massacred by wildlings and Thenns; he escapes to Castle Black with the news and stays to join the Watch (S4E3)."),
      (S4E9, "黑城堡之战中，他一箭射死了耶哥蕊特(S4E9)。", "In the battle for Castle Black he shoots Ygritte dead (S4E9)."),
      (S5E10, "他做了琼恩的侍从，却无法原谅琼恩与野人结盟，在刺杀中给了琼恩最后一刀(S5E10)。",
       "He becomes Jon’s steward, but cannot forgive his pact with the wildlings, and strikes the last blow when Jon is murdered (S5E10)."),
      (S6E3, "琼恩复活后，以叛变之罪吊死了他(S6E3)。", "Brought back to life, Jon hangs him for mutiny (S6E3)."),
    ]),
  N(id="sam", zh="山姆", en="Sam", full=("山姆威尔·塔利", "Samwell Tarly"), house="tarly", grp="wall",
    debut=S1E4, dies=None,
    camps=[(S1E4, "nw")],
    subs=[(S1E4, "被父亲逼来守夜的胖少年", "A fat boy sent to the Wall by his father"), (S3E8, "杀死异鬼的守夜人", "The brother who killed a White Walker"),
          (S6E10, "学城的见习学士", "A novice at the Citadel"), (S8E6, "大学士", "Grand Maester")],
    sub=("守夜人，琼恩的挚友，后为大学士", "Jon’s best friend in the Watch, later Grand Maester"),
    bios=[
      (S1E4, "角陵塔利家的长子，因为体胖胆小，被父亲逼着放弃继承权、加入守夜人。琼恩护着他，两人成了挚友(S1E4)。",
       "Eldest son of the Tarlys of Horn Hill, forced by his father to give up his inheritance and join the Watch for being fat and timid. Jon protects him and they become fast friends (S1E4)."),
      (S3E10, "他在卡斯特堡结识吉莉(S2E2)，在叛乱中带着她和刚出生的儿子逃走(S3E4)，用龙晶匕首杀死了一个异鬼(S3E8)，终于回到黑城堡(S3E10)。",
       "He meets Gilly at Craster’s Keep (S2E2), escapes the mutiny with her and her newborn son (S3E4), kills a White Walker with a dragonglass dagger (S3E8), and gets them back to Castle Black (S3E10)."),
      (S5E10, "他在黑城堡的书库里埋头苦读，寻找对付异鬼的办法。伊蒙学士死后(S5E7)，他带着吉莉南下旧镇学做学士(S5E10)。",
       "Buried in Castle Black’s library, he searches for ways to fight the White Walkers. After Maester Aemon dies (S5E7) he takes Gilly south to train as a maester in Oldtown (S5E10)."),
      (S6E6, "路过角陵时，父亲仍然当众羞辱他，他带走了家传的瓦雷利亚钢剑“碎心”(S6E6)。",
       "Stopping at Horn Hill, he is humiliated by his father again, and takes the family’s Valyrian sword, Heartsbane (S6E6)."),
      (S7E7, "他在学城冒险医治乔拉的灰鳞病(S7E2)，又从吉莉随口念出的旧日记里错过了雷加废婚另娶的记载(S7E5)；回到临冬城后，他与布兰一同确认了琼恩的身世(S7E7)。",
       "At the Citadel he treats Jorah’s greyscale against the rules (S7E2), half-hears Gilly read of Rhaegar’s annulment and second marriage (S7E5), and back at Winterfell confirms Jon’s parentage with Bran (S7E7)."),
      (S8E6, "他得知丹妮莉丝烧死了自己的父亲和弟弟，把琼恩的身世告诉了琼恩(S8E1)。长夜之战中他死里逃生，最后成为布兰的大学士(S8E6)。",
       "Learning that Daenerys has burned his father and brother, he tells Jon who he really is (S8E1). He survives the Long Night and becomes Bran’s Grand Maester (S8E6)."),
    ]),
  # =============================================================== beyond the Wall
  N(id="gilly", zh="吉莉", en="Gilly", full=("吉莉", "Gilly"), house="beyond", grp="wall",
    debut=S2E2, dies=None,
    camps=[(S2E2, "beyond"), (S3E10, "nw", "随山姆来到黑城堡", "Comes to Castle Black with Sam")],
    sub=("卡斯特的女儿和妻子，山姆的爱人", "Craster’s daughter and wife, Sam’s love"),
    bios=[
      (S2E2, "卡斯特的女儿，也是他的妻子之一，怀着他的孩子。她怕孩子是男婴，想逃出卡斯特堡，山姆替她求琼恩，琼恩没有答应(S2E2)。",
       "Craster’s daughter and one of his wives, pregnant by him. Afraid her child will be a boy, she wants to escape; Sam pleads for her with Jon, who refuses (S2E2)."),
      (S3E10, "她生下儿子，在叛乱中随山姆逃出卡斯特堡(S3E4)，一路来到黑城堡(S3E10)。",
       "She gives birth to a son and flees Craster’s Keep with Sam during the mutiny (S3E4), all the way to Castle Black (S3E10)."),
      (S7E5, "她随山姆到了旧镇，在学城的旧日记里读到雷加王子曾秘密废除婚约、另娶他人，山姆却没留心(S7E5)。",
       "In Oldtown, reading an old septon’s diary at the Citadel, she comes across Prince Rhaegar’s secret annulment and remarriage — and Sam does not listen (S7E5)."),
    ]),
  N(id="craster", zh="卡斯特", en="Craster", full=("卡斯特", "Craster"), house="beyond", grp="wall",
    debut=S2E1, dies=S3E4,
    camps=[(S2E1, "beyond")],
    sub=("娶自己女儿的野人，把男婴献给异鬼", "A wildling who weds his daughters and gives his sons to the White Walkers"),
    bios=[
      (S2E2, "住在长城以北的野人，与守夜人互惠往来。他娶自己的女儿为妻(S2E1)，生下的男婴都送进树林；琼恩看见异鬼把婴儿抱走(S2E2)。",
       "A wildling north of the Wall who trades favours with the Night’s Watch. He marries his own daughters (S2E1) and leaves his sons in the woods; Jon sees a White Walker carry one away (S2E2)."),
      (S3E4, "老熊带残部来他的堡垒避难，他吝惜粮食又辱骂守夜人，被一个弟兄刺死，引发了叛乱(S3E4)。",
       "When the Old Bear brings the survivors to his keep, he grudges them food and insults them, and is stabbed by one of the brothers, setting off the mutiny (S3E4)."),
    ]),
  N(id="mance", zh="曼斯", en="Mance", full=("曼斯·雷德", "Mance Rayder"), house="beyond", grp="wall",
    debut=S3E1, dies=S5E1,
    camps=[(S3E1, "beyond")],
    sub=("“塞外之王”，守夜人的逃兵", "King-beyond-the-Wall, a deserter from the Watch"),
    bios=[
      (S3E1, "曾是守夜人，后来叛逃，把长城以北互不相容的部落团结起来，被称为“塞外之王”。琼恩前来投奔，他半信半疑地收下了他(S3E1)。",
       "Once a brother of the Night’s Watch, he deserted and united the quarrelling tribes beyond the Wall as the King-beyond-the-Wall. When Jon comes to join him he takes him in, half-trusting (S3E1)."),
      (S4E10, "他率大军南下，想赶在异鬼之前越过长城；黑城堡久攻不下，又被史坦尼斯的骑兵击溃，被俘(S4E10)。",
       "He leads his host south to get through the Wall ahead of the dead; Castle Black holds, Stannis’s cavalry routs his army, and he is taken (S4E10)."),
      (S5E1, "他拒绝向史坦尼斯屈膝，被判火刑；琼恩不忍他受苦，一箭射穿了他的心脏(S5E1)。",
       "He refuses to kneel to Stannis and is burned at the stake; Jon, unwilling to see him suffer, shoots him through the heart (S5E1)."),
    ]),
  N(id="tormund", zh="托蒙德", en="Tormund", full=("托蒙德·巨人克星", "Tormund Giantsbane"), house="beyond", grp="wall",
    debut=S3E1, dies=None,
    camps=[(S3E1, "beyond"), (S6E4, "stark", "随琼恩出征临冬城", "Marches with Jon"),
           (S8E6, "beyond", "带自由民回到长城以北", "Takes the Free Folk home")],
    sub=("野人首领，琼恩的朋友", "Wildling chief, Jon’s friend"),
    bios=[
      (S3E6, "曼斯手下的野人头领，豪爽粗犷，号称“巨人克星”。他带队翻越长城(S3E6)。",
       "One of Mance’s war leaders, loud and fearless, called Giantsbane. He leads the climb over the Wall (S3E6)."),
      (S4E10, "攻打黑城堡时他被俘(S4E9)，请琼恩按自由民的规矩火化耶哥蕊特(S4E10)。",
       "Captured in the attack on Castle Black (S4E9), he asks Jon to burn Ygritte as the Free Folk do (S4E10)."),
      (S5E8, "他被琼恩说服，一起去艰难屯劝野人南下，在亡者的袭击中死里逃生(S5E8)。",
       "Persuaded by Jon, he goes with him to Hardhome to bring the Free Folk south, and survives the attack of the dead (S5E8)."),
      (S6E9, "他带着野人为琼恩夺回临冬城(S6E9)，对布蕾妮一见倾心。",
       "He brings the Free Folk to fight for Jon at Winterfell (S6E9), and is smitten with Brienne."),
      (S8E6, "长城倒塌时他从东海望逃生(S7E7)，熬过了长夜之战，最后带着野人和琼恩回到长城以北(S8E6)。",
       "He escapes when the Wall falls at Eastwatch (S7E7), survives the Long Night, and goes home beyond the Wall with the Free Folk and Jon (S8E6)."),
    ]),
  N(id="ygritte", zh="耶哥蕊特", en="Ygritte", full=("耶哥蕊特", "Ygritte"), house="beyond", grp="wall",
    debut=S2E6, dies=S4E9,
    camps=[(S2E6, "beyond")],
    sub=("“被火吻过”的野人姑娘，琼恩的恋人", "The red-haired wildling girl Jon loves"),
    bios=[
      (S2E6, "红发的野人弓箭手。琼恩俘虏了她却下不了手，两人在雪原上一路斗嘴(S2E6)。",
       "A red-haired wildling archer. Jon captures her but cannot kill her, and they bicker their way across the snow (S2E6)."),
      (S3E10, "琼恩投奔野人后，她与琼恩相爱(S3E5)，一起翻越长城(S3E6)；琼恩逃回黑城堡时，她含泪射了他三箭(S3E10)。",
       "When Jon joins the wildlings they become lovers (S3E5) and climb the Wall together (S3E6); when he flees back to Castle Black she shoots him three times, in tears (S3E10)."),
      (S4E9, "攻打黑城堡时，她在混战中找到琼恩，却迟迟没有放箭，被少年奥利一箭射死在琼恩怀里(S4E9)。",
       "In the battle for Castle Black she finds Jon and hesitates to shoot; the boy Olly shoots her, and she dies in Jon’s arms (S4E9)."),
    ]),
  N(id="threeeyed", zh="三眼乌鸦", en="Three-eyed Raven", full=("三眼乌鸦", "The Three-eyed Raven"), house="weirwood", grp="wall",
    debut=S4E10, dies=S6E5,
    camps=[(S4E10, "beyond")],
    sub=("住在鱼梁木根下的先知", "The seer in the roots of the weirwood"),
    bios=[
      (S4E10, "一个与鱼梁木的根长在一起的老人，借着树和鸟兽的眼睛看遍古今。布兰历尽艰辛来到他面前，他告诉布兰：你不会再走路，但你会飞(S4E10)。",
       "An old man grown into the roots of a weirwood, who sees past and present through trees and birds. When Bran at last reaches him he tells him he will never walk again — but he will fly (S4E10)."),
      (S6E5, "他带布兰在幻象中回到过去(S6E2)。夜王循着布兰手腕上的印记攻进洞穴，他在最后时刻把记忆传给布兰，被夜王斩杀(S6E5)。",
       "He takes Bran back through visions of the past (S6E2). When the Night King follows the mark on Bran’s arm into the cave, he passes his memories to Bran at the last moment and is cut down (S6E5)."),
    ]),
  N(id="nightking", zh="夜王", en="Night King", full=("夜王", "The Night King"), house="dead", grp="wall",
    debut=S4E4, dies=S8E3,
    camps=[(S4E4, "dead")],
    sub=("异鬼之首，亡者大军的统帅", "Leader of the White Walkers and the army of the dead"),
    bios=[
      (S4E4, "异鬼之首。卡斯特的最后一个儿子被叛变者留在林中献祭，又被带到冰原上，他伸手一点，婴儿的眼睛就变成了冰蓝色(S4E4)。",
       "Leader of the White Walkers. When Craster’s last son is carried to him across the ice, he touches the baby’s cheek and its eyes turn ice-blue (S4E4)."),
      (S5E8, "在艰难屯，他张开双臂，让刚刚死去的成千野人站了起来(S5E8)。",
       "At Hardhome he raises his arms, and the thousands of wildlings who have just died stand up again (S5E8)."),
      (S6E5, "布兰的幻象揭示了他的来历：他原是先民，森林之子把龙晶刺进他的心脏，造出了第一个异鬼。他在幻象中抓住布兰的手腕留下印记，随即攻破了三眼乌鸦的洞穴(S6E5)。",
       "Bran’s visions reveal his origin: he was one of the First Men, turned into the first White Walker when the Children of the Forest drove dragonglass into his heart. He seizes Bran’s arm in a vision, marking him, and breaks into the Raven’s cave (S6E5)."),
      (S7E7, "他掷出冰矛射杀了丹妮莉丝的龙韦赛利昂，把它变成尸龙(S7E6)，骑着尸龙摧毁了东海望一段长城(S7E7)。",
       "He brings down Daenerys’s dragon Viserion with a thrown spear of ice and raises it (S7E6), then rides it to bring down the Wall at Eastwatch (S7E7)."),
      (S8E3, "长夜之战中，他走进临冬城神木林，来到布兰面前，被艾莉亚扑上来一刀刺穿，所有异鬼和尸鬼随他一同崩解(S8E3)。",
       "In the Long Night he walks into the godswood at Winterfell to Bran, and Arya leaps on him with a dagger; he shatters, and every White Walker and wight with him (S8E3)."),
    ]),
]
