# -*- coding: utf-8 -*-
"""Chapter titles (回目) of the 120-chapter Mao Zonggang text, with English renderings."""

CH_ZH = [
  "宴桃园豪杰三结义　斩黄巾英雄首立功",
  "张翼德怒鞭督邮　何国舅谋诛宦竖",
  "议温明董卓叱丁原　馈金珠李肃说吕布",
  "废汉帝陈留践位　谋董贼孟德献刀",
  "发矫诏诸镇应曹公　破关兵三英战吕布",
  "焚金阙董卓行凶　匿玉玺孙坚背约",
  "袁绍磐河战公孙　孙坚跨江击刘表",
  "王司徒巧使连环计　董太师大闹凤仪亭",
  "除暴凶吕布助司徒　犯长安李傕听贾诩",
  "勤王室马腾举义　报父仇曹操兴师",
  "刘皇叔北海救孔融　吕温侯濮阳破曹操",
  "陶恭祖三让徐州　曹孟德大战吕布",
  "李傕郭汜大交兵　杨奉董承双救驾",
  "曹孟德移驾幸许都　吕奉先乘夜袭徐郡",
  "太史慈酣斗小霸王　孙伯符大战严白虎",
  "吕奉先射戟辕门　曹孟德败师淯水",
  "袁公路大起七军　曹孟德会合三将",
  "贾文和料敌决胜　夏侯惇拔矢啖睛",
  "下邳城曹操鏖兵　白门楼吕布殒命",
  "曹阿瞒许田打围　董国舅内阁受诏",
  "曹操煮酒论英雄　关公赚城斩车胄",
  "袁曹各起马步三军　关张共擒王刘二将",
  "祢正平裸衣骂贼　吉太医下毒遭刑",
  "国贼行凶杀贵妃　皇叔败走投袁绍",
  "屯土山关公约三事　救白马曹操解重围",
  "袁本初败兵折将　关云长挂印封金",
  "美髯公千里走单骑　汉寿侯五关斩六将",
  "斩蔡阳兄弟释疑　会古城主臣聚义",
  "小霸王怒斩于吉　碧眼儿坐领江东",
  "战官渡本初败绩　劫乌巢孟德烧粮",
  "曹操仓亭破本初　玄德荆州依刘表",
  "夺冀州袁尚争锋　决漳河许攸献计",
  "曹丕乘乱纳甄氏　郭嘉遗计定辽东",
  "蔡夫人隔屏听密语　刘皇叔跃马过檀溪",
  "玄德南漳逢隐沦　单福新野遇英主",
  "玄德用计袭樊城　元直走马荐诸葛",
  "司马徽再荐名士　刘玄德三顾草庐",
  "定三分隆中决策　战长江孙氏报仇",
  "荆州城公子三求计　博望坡军师初用兵",
  "蔡夫人议献荆州　诸葛亮火烧新野",
  "刘玄德携民渡江　赵子龙单骑救主",
  "张翼德大闹长坂桥　刘豫州败走汉津口",
  "诸葛亮舌战群儒　鲁子敬力排众议",
  "孔明用智激周瑜　孙权决计破曹操",
  "三江口曹操折兵　群英会蒋干中计",
  "用奇谋孔明借箭　献密计黄盖受刑",
  "阚泽密献诈降书　庞统巧授连环计",
  "宴长江曹操赋诗　锁战船北军用武",
  "七星坛诸葛祭风　三江口周瑜纵火",
  "诸葛亮智算华容　关云长义释曹操",
  "曹仁大战东吴兵　孔明一气周公瑾",
  "诸葛亮智辞鲁肃　赵子龙计取桂阳",
  "关云长义释黄汉升　孙仲谋大战张文远",
  "吴国太佛寺看新郎　刘皇叔洞房续佳偶",
  "玄德智激孙夫人　孔明二气周公瑾",
  "曹操大宴铜雀台　孔明三气周公瑾",
  "柴桑口卧龙吊丧　耒阳县凤雏理事",
  "马孟起兴兵雪恨　曹阿瞒割须弃袍",
  "许褚裸衣斗马超　曹操抹书问韩遂",
  "张永年反难杨修　庞士元议取西蜀",
  "赵云截江夺阿斗　孙权遗书退老瞒",
  "取涪关杨高授首　攻雒城黄魏争功",
  "诸葛亮痛哭庞统　张翼德义释严颜",
  "孔明定计捉张任　杨阜借兵破马超",
  "马超大战葭萌关　刘备自领益州牧",
  "关云长单刀赴会　伏皇后为国捐生",
  "曹操平定汉中地　张辽威震逍遥津",
  "甘宁百骑劫魏营　左慈掷杯戏曹操",
  "卜周易管辂知机　讨汉贼五臣死节",
  "猛张飞智取瓦口隘　老黄忠计夺天荡山",
  "占对山黄忠逸待劳　据汉水赵云寡胜众",
  "诸葛亮智取汉中　曹阿瞒兵退斜谷",
  "玄德进位汉中王　云长攻拔襄阳郡",
  "庞令明抬榇决死战　关云长放水淹七军",
  "关云长刮骨疗毒　吕子明白衣渡江",
  "徐公明大战沔水　关云长败走麦城",
  "玉泉山关公显圣　洛阳城曹操感神",
  "治风疾神医身死　传遗命奸雄数终",
  "兄逼弟曹植赋诗　侄陷叔刘封伏法",
  "曹丕废帝篡炎刘　汉王正位续大统",
  "急兄仇张飞遇害　雪弟恨先主兴兵",
  "孙权降魏受九锡　先主征吴赏六军",
  "战猇亭先主得仇人　守江口书生拜大将",
  "陆逊营烧七百里　孔明巧布八阵图",
  "刘先主遗诏托孤儿　诸葛亮安居平五路",
  "难张温秦宓逞天辩　破曹丕徐盛用火攻",
  "征南寇丞相大兴师　抗天兵蛮王初受执",
  "渡泸水再缚番王　识诈降三擒孟获",
  "武乡侯四番用计　南蛮王五次遭擒",
  "驱巨兽六破蛮兵　烧藤甲七擒孟获",
  "祭泸水汉相班师　伐中原武侯上表",
  "赵子龙力斩五将　诸葛亮智取三城",
  "姜伯约归降孔明　武乡侯骂死王朗",
  "诸葛亮乘雪破羌兵　司马懿克日擒孟达",
  "马谡拒谏失街亭　武侯弹琴退仲达",
  "孔明挥泪斩马谡　周鲂断发赚曹休",
  "讨魏国武侯再上表　破曹兵姜维诈献书",
  "追汉军王双受诛　袭陈仓武侯取胜",
  "诸葛亮大破魏兵　司马懿入寇西蜀",
  "汉兵劫寨破曹真　武侯斗阵辱仲达",
  "出陇上诸葛妆神　奔剑阁张郃中计",
  "司马懿占北原渭桥　诸葛亮造木牛流马",
  "上方谷司马受困　五丈原诸葛禳星",
  "陨大星汉丞相归天　见木像魏都督丧胆",
  "武侯预伏锦囊计　魏主拆取承露盘",
  "公孙渊兵败死襄平　司马懿诈病赚曹爽",
  "魏主政归司马氏　姜维兵败牛头山",
  "丁奉雪中奋短兵　孙峻席间施密计",
  "困司马汉将奇谋　废曹芳魏家果报",
  "文鸯单骑退雄兵　姜维背水破大敌",
  "邓士载智败姜伯约　诸葛诞义讨司马昭",
  "救寿春于诠死节　取长城伯约鏖兵",
  "丁奉定计斩孙綝　姜维斗阵破邓艾",
  "曹髦驱车死南阙　姜维弃粮胜魏兵",
  "诏班师后主信谗　托屯田姜维避祸",
  "钟会分兵汉中道　武侯显圣定军山",
  "邓士载偷度阴平　诸葛瞻战死绵竹",
  "哭祖庙一王死孝　入西川二士争功",
  "假投降巧计成虚话　再受禅依样画葫芦",
  "荐杜预老将献新谋　降孙皓三分归一统",
]

CH_EN = [
  "Three heroes swear brotherhood in the Peach Garden; they win their first battle against the Yellow Turbans",
  "Zhang Fei flogs the inspector; He Jin, the empress’s brother, plots against the eunuchs",
  "Dong Zhuo rebukes Ding Yuan at Wenming; Li Su wins Lü Bu with gold and pearls",
  "The Han emperor is deposed and the Prince of Chenliu enthroned; Cao Cao offers a sword to kill Dong Zhuo",
  "Cao Cao’s forged edict rallies the lords; three heroes fight Lü Bu at the pass",
  "Dong Zhuo burns the palaces; Sun Jian hides the imperial seal and breaks his oath",
  "Yuan Shao fights Gongsun Zan at the Pan River; Sun Jian crosses the river against Liu Biao",
  "Minister Wang Yun lays the chain plot; Dong Zhuo storms the Phoenix Pavilion",
  "Lü Bu helps Wang Yun kill the tyrant; Li Jue takes Jia Xu’s advice and attacks Chang’an",
  "Ma Teng rises for the throne; Cao Cao marches to avenge his father",
  "Liu Bei saves Kong Rong at Beihai; Lü Bu defeats Cao Cao at Puyang",
  "Tao Qian thrice offers Xuzhou to Liu Bei; Cao Cao battles Lü Bu",
  "Li Jue and Guo Si turn on each other; Yang Feng and Dong Cheng rescue the emperor",
  "Cao Cao moves the emperor to Xu; Lü Bu seizes Xuzhou by night",
  "Taishi Ci fights the Little Conqueror; Sun Ce battles Yan Baihu",
  "Lü Bu shoots the halberd at the camp gate; Cao Cao is routed on the Yu River",
  "Yuan Shu raises seven armies; Cao Cao joins forces with three generals",
  "Jia Xu reads the enemy and wins; Xiahou Dun pulls out the arrow and eats his eye",
  "Cao Cao besieges Xiapi; Lü Bu dies at the White Gate Tower",
  "Cao Cao hunts at Xutian; Dong Cheng receives the secret edict",
  "Cao Cao talks of heroes over wine; Guan Yu takes the city and kills Che Zhou",
  "Yuan Shao and Cao Cao raise their armies; Guan Yu and Zhang Fei capture two generals",
  "Mi Heng strips and curses the traitor; Physician Ji is tortured for trying to poison Cao Cao",
  "The traitor kills a pregnant consort; Liu Bei flees to Yuan Shao",
  "Guan Yu sets three conditions on the hill; Cao Cao lifts the siege of Baima",
  "Yuan Shao loses men and generals; Guan Yu hangs up his seal and seals up the gold",
  "Guan Yu rides a thousand li alone; he slays six generals at five passes",
  "Cai Yang’s death ends the brothers’ doubts; lord and vassals reunite at Gucheng",
  "The Little Conqueror beheads Yu Ji; the green-eyed boy takes over the east",
  "Yuan Shao is defeated at Guandu; Cao Cao raids Wuchao and burns the grain",
  "Cao Cao beats Yuan Shao at Cangting; Liu Bei takes refuge with Liu Biao",
  "Yuan Shang fights for Ji; Xu You proposes breaching the Zhang River",
  "Cao Pi takes Lady Zhen in the chaos; Guo Jia’s last plan settles Liaodong",
  "Lady Cai overhears behind a screen; Liu Bei leaps the Tan torrent",
  "Liu Bei meets a hermit at Nanzhang; Shan Fu finds his lord at Xinye",
  "Liu Bei takes Fancheng by a ruse; Xu Shu rides back to recommend Zhuge Liang",
  "Sima Hui recommends a scholar again; Liu Bei visits the thatched cottage three times",
  "Zhuge Liang lays out the three-way plan at Longzhong; the Suns take revenge on the Yangtze",
  "Liu Qi begs for advice three times; Zhuge Liang’s first battle at Bowang",
  "Lady Cai proposes giving Jing away; Zhuge Liang burns Xinye",
  "Liu Bei leads the people across the river; Zhao Yun rescues his lord’s son alone",
  "Zhang Fei holds Changban Bridge; Liu Bei flees to Hanjin",
  "Zhuge Liang out-argues the scholars; Lu Su stands against the crowd",
  "Zhuge Liang provokes Zhou Yu; Sun Quan resolves to fight Cao Cao",
  "Cao Cao loses men at Sanjiangkou; Jiang Gan is fooled at the Gathering of Heroes",
  "Zhuge Liang borrows arrows; Huang Gai takes a flogging for a secret plan",
  "Kan Ze delivers the false surrender; Pang Tong passes on the chain plan",
  "Cao Cao composes a poem at a feast on the river; the northern fleet is chained together",
  "Zhuge Liang prays for wind at the Seven Stars Altar; Zhou Yu sets the fire",
  "Zhuge Liang foresees Huarong; Guan Yu lets Cao Cao go",
  "Cao Ren fights the men of Wu; Zhuge Liang provokes Zhou Yu once",
  "Zhuge Liang puts off Lu Su; Zhao Yun takes Guiyang by a ruse",
  "Guan Yu spares Huang Zhong; Sun Quan fights Zhang Liao",
  "Lady Wu looks over the bridegroom at a temple; Liu Bei weds again",
  "Liu Bei wins Lady Sun over; Zhuge Liang provokes Zhou Yu twice",
  "Cao Cao feasts at the Bronze Sparrow Terrace; Zhuge Liang provokes Zhou Yu a third time",
  "The Sleeping Dragon mourns at Chaisang; the Young Phoenix governs Leiyang",
  "Ma Chao rises to avenge his father; Cao Cao cuts off his beard and throws away his robe",
  "Xu Chu strips to fight Ma Chao; Cao Cao’s smudged letter sows doubt in Han Sui",
  "Zhang Song confounds Yang Xiu; Pang Tong proposes taking Shu",
  "Zhao Yun stops the boat and takes back A Dou; Sun Quan’s letter sends Cao Cao home",
  "Yang and Gao die at Fu Pass; Huang Zhong and Wei Yan vie for glory at Luo",
  "Zhuge Liang weeps for Pang Tong; Zhang Fei spares Yan Yan",
  "Zhuge Liang traps Zhang Ren; Yang Fu borrows troops and defeats Ma Chao",
  "Ma Chao fights at Jiameng Pass; Liu Bei becomes governor of Yi",
  "Guan Yu goes to the banquet with a single blade; Empress Fu dies for the state",
  "Cao Cao conquers Hanzhong; Zhang Liao’s fame shakes Xiaoyao Ford",
  "Gan Ning raids the Wei camp with a hundred horsemen; Zuo Ci mocks Cao Cao with a cup",
  "Guan Lu foresees the future in the Book of Changes; five ministers die resisting the traitor",
  "Zhang Fei takes Wakou Pass by a ruse; Huang Zhong wins Mount Tiandang",
  "Huang Zhong waits on the facing height; Zhao Yun beats a larger army at the Han River",
  "Zhuge Liang takes Hanzhong; Cao Cao retreats through Xie Valley",
  "Liu Bei becomes King of Hanzhong; Guan Yu takes Xiangyang",
  "Pang De carries his coffin to battle; Guan Yu floods the seven armies",
  "Guan Yu has his bone scraped; Lü Meng crosses the river in white",
  "Xu Huang fights on the Mian River; Guan Yu flees to Maicheng",
  "Guan Yu’s spirit appears at Jade Spring Hill; Cao Cao is haunted in Luoyang",
  "The divine physician dies treating a headache; the crafty hero gives his last commands",
  "Cao Pi forces Cao Zhi to compose a poem; Liu Feng is executed for abandoning his uncle",
  "Cao Pi deposes the emperor and usurps the Han; the King of Hanzhong takes the throne",
  "Zhang Fei is murdered in his haste for revenge; Liu Bei marches to avenge his brothers",
  "Sun Quan submits to Wei and receives the nine honors; Liu Bei marches on Wu and rewards his army",
  "Liu Bei catches his enemies at Xiaoting; a scholar is made commander to defend the river",
  "Lu Xun burns seven hundred li of camps; Zhuge Liang lays out the stone maze",
  "Liu Bei leaves his son in Zhuge Liang’s care; Zhuge Liang turns back five armies without leaving home",
  "Qin Mi out-argues Zhang Wen; Xu Sheng burns back Cao Pi",
  "The chancellor marches south; the king of the Man is captured for the first time",
  "Meng Huo is bound again across the Lu; caught a third time after a false surrender",
  "Zhuge Liang’s fourth ruse; Meng Huo is caught a fifth time",
  "The beasts are routed for the sixth victory; the rattan armor burns and Meng Huo is caught a seventh time",
  "The chancellor sacrifices at the Lu and turns home; he submits his memorial and marches north",
  "Zhao Yun kills five generals; Zhuge Liang takes three cities",
  "Jiang Wei joins Zhuge Liang; Zhuge Liang curses Wang Lang to death",
  "Zhuge Liang defeats the Qiang in the snow; Sima Yi captures Meng Da on schedule",
  "Ma Su ignores advice and loses Jieting; Zhuge Liang’s zither turns back Sima Yi",
  "Zhuge Liang weeps as he executes Ma Su; Zhou Fang cuts his hair to trick Cao Xiu",
  "Zhuge Liang submits a second memorial; Jiang Wei’s false letter defeats the Wei army",
  "Wang Shuang dies pursuing the Shu army; Zhuge Liang takes Chencang",
  "Zhuge Liang crushes the Wei army; Sima Yi invades Shu",
  "The Shu army raids Cao Zhen’s camp; Zhuge Liang shames Sima Yi in a battle of formations",
  "Zhuge Liang poses as a god at Longshang; Zhang He falls into a trap racing for Jiange",
  "Sima Yi takes the northern plain and the Wei bridge; Zhuge Liang builds wooden oxen and gliding horses",
  "Sima Yi is trapped in Shangfang Valley; Zhuge Liang prays to the stars at Wuzhang",
  "A great star falls and the chancellor dies; a wooden statue terrifies the Wei commander",
  "Zhuge Liang’s sealed plan waits in reserve; the Wei emperor takes down the dew-catching plate",
  "Gongsun Yuan dies at Xiangping; Sima Yi feigns illness to fool Cao Shuang",
  "The power of Wei passes to the Sima clan; Jiang Wei is defeated at Niutou Mountain",
  "Ding Feng fights with short weapons in the snow; Sun Jun plots at a banquet",
  "A Shu general traps Sima Zhao; Cao Fang is deposed, and Wei reaps what it sowed",
  "Wen Yang drives off an army alone; Jiang Wei fights with his back to the river",
  "Deng Ai outwits Jiang Wei; Zhuge Dan rises against Sima Zhao",
  "Yu Quan dies loyal at Shouchun; Jiang Wei fights hard at Changcheng",
  "Ding Feng plots the death of Sun Chen; Jiang Wei defeats Deng Ai in a battle of formations",
  "Cao Mao rides out and dies at the south gate; Jiang Wei abandons his grain and wins",
  "Liu Shan believes slander and recalls his army; Jiang Wei goes to farm at Tazhong to escape",
  "Zhong Hui marches on Hanzhong by several roads; Zhuge Liang’s spirit appears at Mount Dingjun",
  "Deng Ai crosses Yinping in secret; Zhuge Zhan dies fighting at Mianzhu",
  "A prince weeps at the ancestral temple and dies for duty; two generals vie for glory in Shu",
  "A false surrender comes to nothing; a second abdication copies the first",
  "Old Yang Hu recommends Du Yu; Sun Hao surrenders and the three become one",
]

assert len(CH_ZH) == len(CH_EN) == 120
